### DISCUSSION TITLE
Identify when Vector has processed all the logs

### DISCUSSION THREAD

**Discussion by anupamdialpad** [vectordotdev/vector#10133] [Q&A] [answered]
Hi,

We are running Vector as a sidecar container inside K8s pods. Vector is ingesting log files from some locations and outputting it to some sinks. Is there a way to identify how much of the logs Vector has processed? Or has Vector processed all the logs and passed them to the sink?

**Comment by jdrouet** [comment, marked as answer]
Hi!
If you want to have those internal information and send them somewhere else, you can use the [`internal_metrics`](https://vector.dev/docs/reference/configuration/sources/internal_metrics/).
If you want to do it to troubleshoot, you can use [`vector top`](https://vector.dev/docs/reference/cli/#top) in the running container and you will see what vector is handling.
Tell me if you need more information 😉

**Reply by anupamdialpad** [reply]
Would definitely need more information 😄 
With `internal_metrics` how can I check that Vector has processed all the log files (source) and has emitted the result out via the sink?

**Reply by jdrouet** [reply]
I opened [this PR](https://github.com/vectordotdev/vector-demos/pull/12) this morning to have a demo on how to use the `internal_metrics` with Vector and Prometheus.

You can see on the [`internal_metrics`](https://vector.dev/docs/reference/configuration/sources/internal_metrics/#component_received_events_total) documentation that a `component_received_events_total` metric is accessible.
Depending on the sink you pick you can have the information of how many events went out.

For example, with the `datadog_logs` sink, you can have [`buffer_sent_events_total` event](https://vector.dev/docs/reference/configuration/sinks/datadog_logs/#buffer_sent_events_total) that could fit your needs.

**Reply by anupamdialpad** [reply]
Programmatically can I get what is the count of "events in" for a given source using `vector top`? Would be great if you can add a code snippet for it. 
Following is a sample vector config for a source I am using 
```toml
[sources.log_source]
  type = "file"
  include = ["/var/log/somefile.log"]

  multiline.start_pattern = '.*'
  multiline.condition_pattern = '^(?P<year>[0-9]{4})-(?P<month>[0-9]{2})-(?P<day>[0-9]{2})'
  multiline.mode = "halt_before"
  multiline.timeout_ms = 1000

  ignore_older_secs = 86400 # 24h
```
