### DISCUSSION TITLE
prefix for path in a transform object, how ?

### DISCUSSION THREAD

**Discussion by StefanSa** [vectordotdev/vector#10631] [Q&A] [answered]
Hi there,
Is it possible to give a prefix for the path during logfile parsing, e.g. parse_syslog.
A prefix of `.sophos.xg.` will then become `.sophos.xg.hostname` during parsing.
The general question is, is it possible to dynamically generate the path with a path prefix ?

Example kv filter:
```
# split Sophos-XG fields
- kv:
    field: log.original
    field_split: " (?=[a-zA-Z0-9\\_\\-]+=)"
    value_split: "="
    prefix: "sophos.xg."
    ignore_missing: true
    ignore_failure: false
    trim_value: "\"
```
