### DISCUSSION TITLE
How to call API and consume the output using exec

### DISCUSSION THREAD

**Discussion by satscreate** [vectordotdev/vector#11527] [Q&A] [answered]
Any example script for exec source, which calls an API every N minute and collects the response and transform.?
Tried,
```
sources:
  my_source_id:
    type: exec
    command: ["curl","-k","https://gorest.co.in/public/v2/users"]
sinks:
  stdout:
    type: console
    inputs:
      - my_source_id
    target: stdout
    encoding:
      codec: json
```

Any examples?

**Comment by jszwedko** [comment, marked as answer]
Hi @satscreate ,

If you want to call it on an interval, you should use `mode.scheduled` with  `scheduled.exec_interval_secs` like:

```yaml
sources:
  my_source_id:
    type: exec
    command: ["curl","-k","https://gorest.co.in/public/v2/users"]
    mode: scheduled
    scheduled:
      exec_interval_secs: 600 # five minutes
```

Otherwise, what you have seems reasonable to me.
