### DISCUSSION TITLE
Getting error from docker vector instance for exec command

### DISCUSSION THREAD

**Discussion by satscreate** [vectordotdev/vector#11794] [Q&A] [answered]
Getting error from docker vector instance,

Vector.yaml:
```
sources:
  my_source_id:
    type: exec
    command: ["curl","-k","https://gorest.co.in/public/v2/users"]
    mode: scheduled
    scheduled:
      exec_interval_secs: 600 # five minutes
sinks:
  stdout:
    type: console
    inputs:
      - my_source_id
    target: stdout
    encoding:
      codec: json

```

**Log:**
`ERROR source{component_kind="source" component_id=stdin component_type=exec component_name=stdin}: vector::internal_events::exec: Unable to exec. command=curl -k https://gorest.co.in/public/v2/users error=Os { code: 2, kind: NotFound, message: "No such file or directory" }`

Any Idea?

**Comment by jszwedko** [comment, marked as answer]
Hi @satscreate ,

That error message would indicate that the image you are using doesn't have `curl` available. The Vector images we publish are as slimmed down as possible and so don't include `curl`. If you need it, I'd recommend building your own image, based on the Vector images, that installs `curl`.

It does look like the `alpine` based images have `wget` available so that could be another option. The `debian` based images do not.

Let me know if this helps!

**Reply by satscreate** [reply]
have tried alpine based images with wget. But some osError thrown.
So unfortunately cannot use any vector images with exec command to call the API's. 
Any help document available to build vector images with curl added to them as a docker image? Currently this is happing with the help of running docker swarm services like this,
**docker.yaml**
```
version: '3.8'
services:
    vector:
      image: timberio/vector:0.18.1-distroless-libc
      command: -c /vector.yaml
      configs:
        - vector.yaml
      networks:
        - metrics
      volumes:
        - vector_data:/var/lib/vector
      deploy:
        mode: replicated
        endpoint_mode: dnsrr
```

dockerFile look like this,
```
# Use Python 3.8 image as base image
FROM python:3.8-slim AS base

# Start a new stage for building the application dependencies
FROM base AS depbuilder

# Install required building dependencies
RUN apt update \
    && apt install --assume-yes --no-install-recommends \  <---- **Can i add curl here?**
        build-essential

# Install and build required Python dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

...
```

Can i add curl into the dockerFile ? will that help?
How can i build own vector image with curl added to it.
