### DISCUSSION TITLE
How to increase through put for Vector consuming from kafka

### DISCUSSION THREAD

**Discussion by pkirubak** [vectordotdev/vector#12085] [Q&A] [answered]
**Suspect two issues** 
1.  Lua transform is reducing the consumption rate
2.  with multiple instance of vector, the source is not getting load shared across replicas

**Configuration**: 
```
sources:
  kafka_metric_read:
    type: kafka
    bootstrap_servers: “xxx.svc.cluster.local:9092"
    group_id: "vector-group"
    topics:
      - “t_metric"
    auto_offset_reset: "latest"
    acknowledgements:
      enabled: true

transforms:
  aggregator_metric_processing:
    type: remap
    inputs: ["kafka_metric_read"]
    source: |-
      .metric = parse_json!(.message)
      #.metric.timestamp = to_timestamp!(.metric.timestamp)

## refer https://github.com/vectordotdev/vector/discussions/7689#discussioncomment-885366
  metric_process:
    type: lua
    inputs:
      - aggregator_metric_processing
    version: '2'
    hooks:
      process: |
        function (event, emit)
          event.metric = event.log.metric
          event.log = nil
          emit(event)
        end

sinks:
  prom_metric:
    type: prometheus_remote_write
    inputs: ["metric_process"]
    endpoint: http://thanos-receive.svc.cluster.local:9598/api/v1/receive
    healthcheck: true
    request:
      retry_attempts: 0
      timeout_secs: 120
```

In kafka, the ingress rate is ~21k where as the egress is around 17k  , so i suspect the bottle neck is not at transforms but at the vector's consuming from kafka ..

Looking at utilisation metrics , looks like there is some lag at lua transform.
```
sum(vector_utilization) by (component_type)

{component_type="remap"} | 0.0946328675065908
{component_type="lua"} | 0.9684126307364543
{component_type="prometheus_remote_write"} | 0.08025006493975331
{component_type="prometheus_exporter"} | 0.000161718097033596
```

Any suggestion on how to improve through put and how to enable multiple instance of vector to consume will help.
