### DISCUSSION TITLE
Elasticsearch index name based on kubernetes.pod_namespace value

### DISCUSSION THREAD

**Discussion by andy812** [vectordotdev/vector#12196] [Q&A] [answered]
I use kubernetes_logs source elasticsearch sink and can't find the way how to generate index name based on kubernetes.pod_namespace value. For examle:
```
  sources:
    monitoring_grafana:
      type: kubernetes_logs
      extra_label_selector: "app.kubernetes.io/instance=prom,app.kubernetes.io/name=grafana"
  sinks:
    es:
      type: elasticsearch
      inputs:
        - monitoring_grafana
      bulk:
        index: "vector-{{kubernetes.pod_namespace}}-%Y-%m-%d"
```
What should i use instead of `{{kubernetes.pod_namespace}}`? Please, add an example in documentation.
