### DISCUSSION TITLE
Two and more sources

### DISCUSSION THREAD

**Discussion by kirill-ratkin** [vectordotdev/vector#12714] [Q&A] [answered]
Hi,
Could you advice, how to configure 'vector' to process several sources?
I have two (or maybe three) files on a disk. There are csv and json. They are quite large.
And I'd like to get data from them, mix data got from all and sink to database.

It's quite easy to do it in 'awk' or 'python' but I'd like to have more performance and 'vector' looks very very exciting. But I can't understand how to configure several inputs .. :(

**Comment by jszwedko** [comment, marked as answer]
Hi @kirill-ratkin !

You can provide multiple paths to the `file` source like:

```toml
[sources.my_source_id]
type = "file"
include = [ "/tmp/foo.log", "/tmp/bar.log" ]
```

Does this help answer your question?
