### DISCUSSION TITLE
Bad rate on log to metric counter

### DISCUSSION THREAD

**Discussion by LinTechSo** [vectordotdev/vector#12914] [Q&A] [answered]
If I increase the replica number of vector instances on the Kubernetes cluster and I put a log to metric transformation on the pipeline that counts a specific field, the rate of that count will be Invalid...
it gives us zero rates but we are using demo logs with a time intervals of 1 second...

**Comment by jszwedko** [comment]
Hi @LinTechSo !

Apologies, I'm not quite sure I understand the issue. Could you provide the Vector configuration you are using, the expected output, and the actual output?

**Reply by LinTechSo** [reply]
Hi @jszwedko 
i have some vector piplines that i use them as a log shippers 
and also i deployed ds vector log generator manifests  that produce logs with rate of 1 per minutes and send them to the kafka then my main vector read that from kafka and count it and send it to loki:
source[Kafka] ------>  transform[log counter] ----> sink[loki] 
so my main vector  counter configuration:
``` tag_counter_metrics:
        type: "log_to_metric"
        inputs:
          - to_json
        metrics:
          - type: counter
            name: vll_tag_total
            field: tag
            namespace: vll
            tags:
              tag: "{{tag}}"
              source_cluster: "{{cluster}}"
              source_node: "{{node_name}}"
```
the rate of this log to metric counter become zero in some times per node  (one per 5 minutes for example) after i increased  the replica number but  we don't have any log loss ...
i set the vector deployment replica to 1 and everything works fine but why ?

( Kubernetes  1.21 cluster with vector  version 0.22.0 )

this [link](https://lokitest.s3.ir-thr-at1.arvanstorage.com/Screenshot_2022-06-06_19-55-01.png) is a screenshot of my grafana that shows  my issue very well

the first panel is counter rate with replica 1
the seccond panel is counter rate with replica 3

**Reply by jszwedko** [reply]
Could you share the `loki` sink configuration? One guess I have is that you have multiple Vector instances writing to the same Loki stream, which could cause problems.

**Reply by LinTechSo** [reply]
```
      loki_sink:
        type: loki
        inputs:
          - filterـtest
        endpoint: http://loki.test.svc:3100
        out_of_order_action: rewrite_timestamp
        labels:
          tag: "{{tag}}"
        batch:
          max_bytes: 1024000
        buffer:
          type: memory
          max_events: 5000
          when_full: block
        tenant_id: "test"
        remove_timestamp: false
        encoding:
          codec: json
```
