### DISCUSSION TITLE
Docker + Boto3 + Python + Vector Seems not finding boto3

### DISCUSSION THREAD

**Discussion by satscreate** [vectordotdev/vector#13282] [Q&A] [answered]
I've been trying to add some python libs to vector image as i wanted to run python scripts via vector file.
But getting below error,
`"ImportError: No module named boto3"`

DockerFile:
```
FROM timberio/vector:0.22.2-debian
RUN apt update && apt install --assume-yes \
    python \
    python3-pip
VOLUME [/var/lib/vector/]
RUN pip install boto3
RUN vector --version # buildkit
ENTRYPOINT ["/usr/bin/vector"]
```

Built command:
`docker build -t vector/custom .`

Compose.yaml
```
services:
  vector:
    image: vector/custom
    command: -c /vector.yaml
.....
```

vector.yaml calls a python script:
```
sources:
  exec:
    type: exec
    command: ["bash", "-c", "python test.py"]
.....
```
test.py:
```
import json
import os
import io
import time
import gzip
import boto3
boto3.resource(....)
....
```

When i deploy above stack i am always getting below error, any idea?
```
{"command":["bash","-c","python /test.py"],"host":"54353535","message":"    import boto3","pid":33,"source_type":"exec","stream":"stderr"}
{"command":["bash","-c","python /test.py"],"host":"54353535","message":"ImportError: No module named boto3","pid":33,"source_type":"exec","stream":"stderr"}
```
