### DISCUSSION TITLE
Using docker container envrioment variables as loki log labels

### DISCUSSION THREAD

**Discussion by dpewsey** [vectordotdev/vector#13593] [Q&A] [answered]
Looking to lift environment variables out of docker and use to define loki log labels. Wondering if anyone knows if this is possible.
Here is the config toml
```          data_dir = "alloc/data/vector/"
          [api]
            enabled = true
            address = "0.0.0.0:8686"
            playground = true
          [sources.logs]
            type = "docker_logs"
          [sinks.out]
            type = "console"
            inputs = [ "logs" ]
            encoding.codec = "json"
          [sinks.loki]
            type = "loki"
            inputs = ["logs"]
            endpoint = "url"
            encoding.codec = "json"
            healthcheck.enabled = true
            [sinks.loki.labels]
              testing = '{{ env.\\[1\\] }}'`
```

I've tried with this and escaping out the characters. 

Anyone any ideas?

Thanks

**Comment by spencergilbert** [comment, marked as answer]
Hi @dpewsey - to clarify, are the env variables in the container that Vector is running in - or are you looking for variables from the containers the logs were collected from?

```toml
[sources.logs]
  type = "docker_logs"
[sinks.loki]
  type = "loki"
  inputs = ["logs"]
  endpoint = "http://url:3100"
  encoding.codec = "json"
  healthcheck.enabled = true
  [sinks.loki.labels]
    testing = '"${ENV}'
```

The above would populate the `testing` label with an env var VAR, set in Vector's container ([ref](https://vector.dev/docs/reference/configuration/#environment-variables)).

The second part (getting variables from the container that generated the log) probably isn't possible.
