### DISCUSSION TITLE
is there a guide on how Reduce works

### DISCUSSION THREAD

**Discussion by tshepang** [vectordotdev/vector#13797] [Q&A] [answered]
I think I don't understand Reduce, because given the following, I expected to have an event whenever `.count` reached 10 events (assuming sum merge strategy would happen magically on that field):

```toml
inputs = ["activity"]
type = "reduce"
ends_when = "to_float!(.count) == 10"
group_by = [
  "name",
  "node",
]
```
This gets fed events of this shape
```json
{
  "count": 1.0,
  "name": "some-name",
  "node": "some-node",
  "timestamp": "2022-08-02T13:40:22.815Z"
}
```
What I get instead is just an assortment of events with varying `.count` values.
