### DISCUSSION TITLE
Buffering to disk based on health status

### DISCUSSION THREAD

**Discussion by hemanthofficial3009** [vectordotdev/vector#13828] [Q&A] [answered]
Hello Team, We have a case where we cannot continuously write to disk for buffering the logs(being streamed out from http/tcp/udp) because of certain hardware limitations. To address this case we will need to persist logs in the disk space of the host system only when streaming is not possible i.e., when the health status of the down stream vector instance is bad.  Can you suggest any solution that would come handy to address this case. Thanks

**Comment by tobz** [comment]
👋🏻 

Just to understand the use case better: what's the limitation around not being able to continuously write to disk? Space, I/O, wear on the storage device, etc?

**Reply by hemanthofficial3009** [reply]
As we wanted to use this approach on a wide range of connected systems, the limitations on hardware would include Space (there are few systems with a very minimal space), wear of SD cards in few cases, limited read/write cycles

**Comment by tobz** [comment, marked as answer]
In the case where minimizing disk write activity _overall_ is preferred, we do have an experimental feature you can try out: **overflow buffers.**

Normally, you would choose between either in-memory or disk buffers, and deal with the trade-offs of whichever one you picked, but overflow buffers allow you to compose a _buffer topology_ consisting of multiple buffer _stages_. An additional `when_full` option called `overflow` instructs the buffer to _overflow_ events to the next buffer in the topology if it cannot currently accept any more events.

This feature is still experimental, and we have some issues around actually documenting it (since it's a rather advanced feature), but here's an example of what it might look like to configure:

```toml
[sinks.http]
type = "http"
...

# This first stage of the buffer is an in-memory buffer that can hold 500 events. We set it to
# "overflow" into the disk buffer in the second stage rather than block or drop.
[[sinks.http.buffer]]
type = "memory"
max_events = 500
when_full = "overflow"

# This second stage of the buffer is a disk buffer that can hold up to 1GiB. Once this stage fills
# up, though, we have to block.
[[sinks.http.buffer]]
type = "disk"
max_size = 1073741824
when_full = "block"
```

This configures the `http` sink to primarily use an in-memory buffer that should hold a maximum  500 events, and when that stage is full, events will temporarily flow to the disk stage, which is configured to hold a maximum of 1GiB. If both stages fill up, we still end up blocking and propagating backpressure... but crucially, we shouldn't write to the disk buffer under normal, steady-state workloads.

All of the same caveats apply to each stage of the buffer, such as the disk buffer still having files on disk even if all events have been drained and processed, and so on.
