### DISCUSSION TITLE
exclude_paths_glob_patterns does not work

### DISCUSSION THREAD

**Discussion by mindrunner** [vectordotdev/vector#14029] [Q&A] [answered]
I am using `vector` to push `k8s` logs to `logtail`. Some  of my pods are very verbose and I want to exclude them by using `exclude_paths_glob_patterns`. However, I can still see logs of excluded pods being pushed to `logtail`. I also tried annotating `pods` with `vector.dev/exclude: "true"`. That didn't work either. What am I missing here?

```
customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      kubernetes_logs:
        type: kubernetes_logs
        exclude_paths_glob_patterns: 
          - "**/dockermailserver/**"
          - "**/prep-config/**"
          - "**/timescaledb/**"
          - "**/prometheus-adapter/**"
          - "**/external-dns/**"
      host_metrics:
        filesystem:
          devices:
            excludes: [binfmt_misc]
          filesystems:
            excludes: [binfmt_misc]
          mountPoints:
            excludes: ["*/proc/sys/fs/binfmt_misc"]
        type: host_metrics
      internal_metrics:
        type: internal_metrics
    sinks:
      logtail:
        type: http
        inputs: [kubernetes_logs]
        uri: https://in.logtail.com/
        encoding:
          codec: json
        auth:
          strategy: bearer
          token: xxxxxxxxxx
      prom_exporter:
        type: prometheus_exporter
        inputs: [host_metrics, internal_metrics]
        address: 0.0.0.0:9090
```
