### DISCUSSION TITLE
syslog TLS error in vector

### DISCUSSION THREAD

**Discussion by LinTechSo** [vectordotdev/vector#14137] [Q&A]
Hi . i get `Connection error. error=TLS handshake failed: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:ssl/record/rec_layer_s3.c:1544:SSL alert number 42 error_code="connection_failed" error_type="writer_failed" stage="sending" internal_log_rate_secs=10` in vector by adding self signed certificate with openssl . 
i test and verify the openssl command and outputs , but everything seems to be ok. 
using vector version 0.23.3

**Comment by jszwedko** [comment]
Hi @LinTechSo !

Can you share:

* Vector configuration
* The openssl commands you are running to verify the certificate

**Reply by LinTechSo** [reply]
Hi. thanks for the reply.  I share them. I'm using cert-manager on the Kubernetes cluster to provide self-signed certificates. my client uses the certificates (public key) by hand and uploads them to open a connection to my vector Syslog server via tls TCP so the validation of the certificate doesn't important in this case and I don't have an idea why this error.

**Comment by LinTechSo** [comment]
Hi @jszwedko 
Yes. this is my vector configuration
```
sources:
  input_logs:
    type: syslog
    address: 0.0.0.0:5000
    mode: tcp 
    tls:
      enabled: true
      crt_file: "/opt/tls.crt"
      key_file: "/opt/tls.key"
      verify_certificate: false
sinks:
  console_all:
    type: console
    inputs:
      - input_logs
    target: stdout
    encoding:
      codec: json
```

and this is my self signed certificate request

```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
spec:
  selfSigned: {}
```
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
```
