### DISCUSSION TITLE
no metric on File source on max_byte_line exceeded

### DISCUSSION THREAD

**Discussion by filipmnowak** [vectordotdev/vector#14144] [General]
hello there!

as in the title: seems like `File` source is not emitting any useful metric signifying [this](https://github.com/vectordotdev/vector/blob/36ea6cbd56b39e26e841bb892d3d9859604ebc75/lib/file-source/src/buffer.rs#L72) event? or perhaps i am missing something?

perhaps rejection should count into `component_discarded_events_total`?

For following source configuration:

```yaml
  test_source:
    type: file
    include:
      - logs/*.txt
    read_from: beginning
    data_dir: vector_work_dir
    max_line_bytes: 2
```

and following log:

```
a
b
c
abc
```

i am getting:

```
log_collector_component_received_events_total (...) 5
log_collector_component_sent_events_total (...) 5
log_collector_events_in_total (...) 5
log_collector_events_out_total (...) 5
```

thank you,
Filip
