### DISCUSSION TITLE
How to convert a CSV file into a JSON, line by line, using LUA?

### DISCUSSION THREAD

**Discussion by rcmv** [vectordotdev/vector#14287] [Q&A] [answered]
Hi!

I would like to convert a CSV file into JSON line by line. I think I can use the remap function with parse_json for this effect but I'm very noob with this and sure how to make it. My attempts failed.

Can someone help me with this simple example of a CSV below?

Timestamp;country;duration;quality
06/09/2022 10:33;UAE;7.8470;3.5362
06/09/2022 10:30;Saudi_Arabia;10.0380;3.4051
06/09/2022 10:27;Switzerland;7.8720;2.4598
06/09/2022 10:24;Israel;9.9360;2.8292

**Edit**:
After some search in the documentation I tried to implement this using Lua with the code below:

```
`[sources.my_csv_files_id]
type = "file"
include = [ "/home/rcmv2/ftp/" ]
start_at_beginning = true

[transforms.lua]
inputs = ["my_csv_files_id"]
type = "lua"
version = "2"
source = """
    csv = require("csv") 
    column_names = {  
        "Timestamp",
	"country",
	"duration",
	"quality",
    }
"""
hooks.process = """
  function (event, emit)
    fields = csv.openstring(event.log.message):lines()() 
    event.log.message = nil 

    for column, value in ipairs(fields) do 
      column_name = column_names[column] 
      event.log[column_name] = value 
    end

    emit(event) 
  end
"""
[sinks.console]
inputs = ["my_csv_files_id"]
type = "console"
encoding.codec = "json"`
```

I'm not get any output though...
Any help?
Thanks

**Comment by jszwedko** [comment]
Hi @rcmv ,

I think your issue is that your transform is being skipped as you've specified the source, `my_csv_files_id`, as the input to the sink rather than `lua`.

However, I'd also recommend looking at `remap` and [`parse_csv`](https://vector.dev/docs/reference/vrl/functions/#parse_csv). Something like:

```toml
[sources.my_csv_files_id]
type = "file"
include = [ "/home/rcmv2/ftp/" ]
start_at_beginning = true

[transforms.remap]
inputs = ["my_csv_files_id"]
type = "remap"
source = """
    csv = require("csv") 
    row = parse_csv!(.message)
    .Timestamp = row[0]
    .country = row[1]
   .duration = row[2]
   .quality = row[3]
"""

[sinks.console]
inputs = ["remap"]
type = "console"
encoding.codec = "json"
```

I didn't test it, but something like that should work.
