### DISCUSSION TITLE
Http Sources ingesting data after 3 invocations each time

### DISCUSSION THREAD

**Discussion by yahya-zuberi** [vectordotdev/vector#14472] [Q&A]
Hello,
so I am using vector and ingesting events in it using http source. The issue I am facing is that after every 3 consecutive invocations vector issue 1 event in. Here is my sources code:

```
sources:
    src:
      type: http
      acknowledgements:
        enabled: false
      address: "[::]:9000"
      encoding: text
      path: ""
      strict_path: false
      headers:
        - User-Agent
        - x-forwarded-for
        - HTTP_X_REAL_IP 
```

Any idea why is this happening?
