### DISCUSSION TITLE
Testing vector config by reading vector tap from stdin

### DISCUSSION THREAD

**Discussion by godber** [vectordotdev/vector#14824] [Q&A]
I thought it would be handy to tap my log stream and pipe it straight into a local instance of vector configured to read from `stdin` and send to `console`.  The problem is the `stdin` source creates a whole new event for each event coming from the tap.  I was hoping to find a `raw` option on the `stdin` source that just read in existing events over `stdin` without creating a new event.

Is there another source that does this?  Or perhaps I'm not understanding the descriptions of the `decoding.codec` options, maybe one of those does what I am asking.  Is this possible in some other way I've not considered?  Basically I want to do:

```
vector tap foo | vector -C config/ -w
```

So I can quickly iterate on my transforms.

```
sources:
  in:
    type: stdin

# transforms:
# ...

sinks:
  out:
    inputs:
      - in
    type: console
    encoding:
      codec: json
```

**Comment by jszwedko** [comment]
HI @godber !

Good question. I think to do what you want we'd need to add the `native_json` codec to `vector tap` so that you could do:

```
vector tap --format native_json foo | vector -C config/ -w
```

With:

```
sources:
  in:
    type: stdin
    decoding:
      codec: "native_json"

# transforms:
# ...

sinks:
  out:
    inputs:
      - in
    type: console
    encoding:
      codec: native_json
```

The `native_json` codec is meant to be a representation of events that Vector can natively decode.

If that makes sense to you, would you want to open a feature request to add a `native_json` codec to `vector tap`?

If you just use the `stdin` source and `console` sink, and not `vector tap`, you should be able to use the `native_json` encoding right now.
