### DISCUSSION TITLE
how to use filter type support wildcard？

### DISCUSSION THREAD

**Discussion by trustnote-wang** [vectordotdev/vector#15215] [Q&A] [answered]
[transforms.service_logs]
type = "filter"
inputs = [ "parse_logs_download" ]
condition = '''
   .service = "*cross"
'''

I want to filter out that the service field contains 'cross' string，but it doesn't work, how to do it?

**Comment by spencergilbert** [comment, marked as answer]
👋

Hi, @trustnote-wang. You can use the VRL functions documented at https://vrl.dev/functions. You probably want to use [ends_with](https://vector.dev/docs/reference/vrl/functions/#ends_with) based on your example glob.

```toml
[transforms.service_logs]
type = "filter"
inputs = [ "parse_logs_download" ]
condition = '''
ends_with!(.service, "cross")
'''
```
