### DISCUSSION TITLE
Derive array type parameter from environment variable

### DISCUSSION THREAD

**Discussion by pirxthepilot** [vectordotdev/vector#15430] [Q&A] [answered]
Hello,

Say I have this config:

```toml
[sources.my_source_id]
type = "kafka"
bootstrap_servers = "10.14.22.123:9092,10.14.23.332:9092"
group_id = "consumer-group-name"
key_field = "message_key"
topics = [ "foo", "bar", "baz" ]
```

I would like the `topic` values to come from an environment variable. The most obvious way is to just use a regex:

```
KAFKA_TOPICS="^(foo|bar|baz)"
```

But I wonder if it's possible to instead set an environment variable like this

```
KAFKA_TOPICS="foo,bar,baz"
```

then have vector do some sort of `split` to convert it to an array? Something like:

```
topics = split("${KAFKA_TOPICS}", ",") 
```

but obviously, this doesn't work.

Thanks in advance!
