### DISCUSSION TITLE
Kafka sink batch messages

### DISCUSSION THREAD

**Discussion by luk-ada** [vectordotdev/vector#15452] [Q&A] [answered]
Hello

I'm using Kubernetes logs as a source and Kafka sink as destination to send logs to the Azure Event Hub. After reviewing number of messages in the Event Hub and in log search engine it looks like 1 Event == 1 Message in the Event hub. Recently we had a problem with reading lot off messages produced by one AKS cluster which is based in the different Azure Region (EH also in different region). We are reading messages using Vectors. No problems in the same region, 1 Vector is able to work on similar load.
I would like to batch messages before sent to the Event Hub to have more logs in one message.
I tried every option from [batch](https://vector.dev/docs/reference/configuration/sinks/kafka/#batch). Still it seams like single messages per log.

Vector 0.24.1

Sink config:
```
sinks:
  event_hub:
    type: kafka
    inputs: ["kubernetes_logs"]
    bootstrap_servers: "${NAMESPACE}.servicebus.windows.net:9093"
    topic: "${EVENT_HUB}"
    compression: "none"
    encoding:
      codec: "json"
    librdkafka_options:
      "security.protocol": sasl_ssl
      "sasl.mechanism": "PLAIN"
      "sasl.username": "$$ConnectionString"
      "sasl.password": "${PASSWORD}"
      # https://learn.microsoft.com/en-us/azure/event-hubs/apache-kafka-configurations#librdkafka-configuration-properties
      "socket.keepalive.enable": "true"
      "metadata.max.age.ms": "180000"
      "retries": "2"
      "request.timeout.ms": "60000"
      "partitioner": "consistent_random"
```

**Comment by tobz** [comment]
The `kafka` sink is explicitly designed to maintain a "one event equals one Kafka message" relationship. The batching configuration affects how the underlying Kafka client library, `librdkafka`, will do send operation batching. This can make sending messages to Kafka brokers more efficient, but it doesn't change the "one event equalis one Kafka message" behavior.

One approach you could try is to aggregate your events in a [`reduce`](https://vector.dev/docs/reference/configuration/transforms/reduce/) transform before they reach the `kafka` sink. This would involve something like:

```yaml
transforms:
  wrap_event:
    type: remap
    inputs:
      - name_of_component
    source: |-
      . = { "events": . }
  aggregated_events:
    type: reduce
    inputs:
      - wrap_event
    merge_strategies:
      events: array
sinks:
  kafka_output:
    type: kafka
    inputs:
      - aggregated_events
```

What this is doing is:

- takes the original event and wraps it in an object, where the original event is now set on the `events` field (so an original event that looks like `{ "foo": "bar" }` becomes `{ "events": { "foo": "bar" } }`)
- aggregate those events by taking the value of the `events` field and pushing it into an array (so the event emitted by `reduce` looks like `{ "events": [{ "foo": "bar" }, { "foo": "bar" }, ...] }`)
- feed those reduced events into your `kafka` sink

We're sort of abusing `reduce` here to get the intended behavior. This means that, by default, it will flush itself every 1 second with all of the events it has reduced so far: it doesn't have a way to specify emitting an event after it's reduced a specific number of input events, so it's not _quite_ the same as the sink batching setting.
