### DISCUSSION TITLE
Omitting Kubernetes fields in source

### DISCUSSION THREAD

**Discussion by ottramst** [vectordotdev/vector#15485] [Q&A] [answered]
Hey all!

When upgrading from 0.24 to 0.26, we seemed to have lost the option to omit specific fields in the `kubernetes_logs` source.

In 0.24 it was possible to omit like so:
```
sources:
  kubernetes_logs:
    type: kubernetes_logs
    namespace_annotation_fields:
      namespace_labels: ""
```

In 0.26 it gives the next error
```
"Configuration error.","error":"Invalid field path \"\" for key `sources.kubernetes_logs`"
```

I would want to avoid implementing a remap for this, because it will just raise the resource cost on the Vector agent in Kubernetes.

Any advice here?

Many thanks!
