### DISCUSSION TITLE
Elasticsearch sink issue

### DISCUSSION THREAD

**Discussion by LinTechSo** [vectordotdev/vector#15778] [Q&A]
Hi. 
i set up kafka ------> vector[es sink] ------> es
after 11:40  in screenshot  my data insertion in Elasticsearch became zero in some cases and i don't know why.  after i restarting my vector dev on 18:30 pm the issue seems to be fixed. 
![Screenshot_20221229_191112](https://user-images.githubusercontent.com/53074289/209976380-1090ee41-20e5-4d51-8365-328d3a22972f.png)

i am using vector using 0.26.0 with kafka source and elasticsearch sink

would you please help me figure this out
i never have seen this  before  in previous versions

**Comment by LinTechSo** [comment]
this is my vector configuration
```
  data_store:
    type: elasticsearch
    inputs:
      - to_json
    compression: none
    endpoints: 
      - "https://test.te"
    api_version: auto
    mode: bulk
    bulk:
      action: index
      index: "test-%F"
    healthcheck:
      enabled: true
    auth:
      user: "test"
      password: "test"
      strategy: "basic"
    acknowledgements:
      enabled: true
```
