### DISCUSSION TITLE
Improve vector kafka source performance

### DISCUSSION THREAD

**Discussion by LinTechSo** [vectordotdev/vector#15884] [Q&A] [answered]
Hi all,
i want to ask if  you could help or provide a working configuration for improving Kafka consuming performance  with vector dev Kafka source.
i want to know how can i  parallel Kafka consuming or etc.
my current configuration:
```
        type: kafka
        bootstrap_servers: kafka.default.svc:9092
        commit_interval_ms: 2000
        fetch_wait_max_ms: 1000
        session_timeout_ms: 20000
        socket_timeout_ms: 60000
        group_id: test
        topics:
          - test_topic

```
but my problem is my Kafka lag is too high per topic
for example the rate of Kafka produce on specific topic is about 1800 rps and the vector consume with 10 replica is 1200 rps (k8s env)

could you help me figure this out . i think there should be a configuration to increase Kafka librdkafka parallelism within vector  or something

using vector version 0.25.2

thanks.
