### DISCUSSION TITLE
Repetitious logs from vector source file

### DISCUSSION THREAD

**Discussion by LinTechSo** [vectordotdev/vector#16064] [Q&A]
Hi all.
I think i see some duplication with below configuration from my vector source file reading:

```
sources:
  my-file:
    type: file
    ignore_older_secs: 600
    include:
      - "/var/log/test.log"
    read_from: beginning

transforms:
  parse-test:
    type: remap
    inputs:
      - my-file
    source: |
       .tag = "hello"


sinks:
  log-forwarder-test:
    type: http
    inputs:
      - parse-test
    uri: https://test.com/

```
My problem is that the rate of my log entries in my data sources is too high from reading this log file and also I see log duplication.

I think enabling health checks or acknowledgments in my vector sink may cause this issue but haven't proven it yet. am I wrong?

Any suggestion/advice would help. 

thanks.
