### DISCUSSION TITLE
Vector throwing 401 with basic_auth for loki sink

### DISCUSSION THREAD

**Discussion by Amit-Hora** [vectordotdev/vector#16225] [Q&A]
I have enabled basic auth for loki. But vector client is unable to authenticate itself while sending messages. Below is my vector client config

```
sinks:
    loki_sink:
      type: loki
      inputs:
        - sflow_trans
      endpoint: http://loki-gateway:80
      auth:
        password: examplepassword
        strategy: basic
        user: lokiuser
      labels:
        forwader1: vector
        type: nflow
        tenant_id: xx-nflow
        zone: |-
          {{ print "{{ dvc_zone }}" }}
      encoding:
        codec: json
      healthcheck:
        enabled: false
```
When I check the nginx logs , I can see the loki user is trying to POST something but getting 401. Below are my Nginx log

`10.0.1.6 - lokiuser [31/Jan/2023:22:37:47 +0000]  401 "POST /loki/api/v1/push HTTP/1.1" 10 "-" "Vector/0.27.0 (x86_64-unknown-linux-gnu 5623d1e 2023-01-18)" "-"`

I am switching from logstash to vector. I thought try to with logstash again to confirm if there is some other problem, But it turns out that with logstash it just works fine. This is my logstash config - 
```
   output {
      loki{
       url => "http://loki-gateway:80/loki/api/v1/push"
       include_fields => ["stream","vpcid","subnetid","interfaceid","accountid","protocol","flowdirection","logstatus","action","cluster","logtype"]
       message_field => "formatted_message"
       tenant_id => "xx-nflow1"
       username => "lokiuser"
       password => "examplepassword"
     }
     }
```
Below are my nginx logs for logstash

`10.0.1.42 - new [01/Feb/2023:00:39:38 +0000]  204 "POST /loki/api/v1/push HTTP/1.1" 0 "-" "loki-logstash" **"-"**`

Any pointers? How can I get this resolved ?
Thanks.
