### DISCUSSION TITLE
Extract http request args (query parameters)

### DISCUSSION THREAD

**Discussion by LinTechSo** [vectordotdev/vector#16396] [Q&A] [answered]
Hi all. 
I assume that the below request  from another vector with an HTTP sink comes to our vector with source http

```
https://myenv.dev/?app_name=test-app&env=stage
```

How can I extract the `app_name=test-app&env=stage` from the request in the vector HTTP source?

My current configuration is this:
```
sources:
  input_logs:
    type: http
    address: 0.0.0.0:8080
    encoding: json
    path: ""
    strict_path: false
    path_key: log

transforms:
  to_json:
    type: remap
    inputs:
      - input_logs
    source: |
       --------------
```

I also checked the `query_parameters` but didn't help because could not extract the args dynamically...
would you help me figure this out.

Appreciate it.

**Comment by neuronull** [comment, marked as answer]
👋 hello

Assuming `.logz_stream` is `"/?app_name=test-app&env=stage"` when the transform starts, what would you like to be the resulting values of `.logz.labels` , and `.logz.stream` ?

**Reply by LinTechSo** [reply]
Hi @neuronull. thanks for the reply.
I want to extract the HTTP query params in vector HTTP source dynamically

**Reply by neuronull** [reply]
You're welcome, happy to help.

The `query_parameters` option in the `http_server` source is currently accepting String only values, and won't interpolate env variables. That could be an enhancement which could help your situation and remove the need for the remap transform.

With the current state of things, you can probably work around this by using the `parse_query_string` VRL function, passing in the `.path` from the log event exported from the `http_server` source.

See

https://vector.dev/docs/reference/vrl/functions/#parse_query_string

https://vector.dev/docs/reference/configuration/sources/http_server/#structured-fields

**Reply by LinTechSo** [reply]
The .path only contains the HTTP request path and doesn't have query params

**Comment by LinTechSo** [comment]
i use this configuration but still doesn't work
```
    sources:
      input_logs:
        type: http
        address: 0.0.0.0:8080
        encoding: json
        path: ""
        strict_path: false

    
    transforms:
      to_json:
        type: remap
        inputs:
          - input_logs
        source: |
            .path = .path

            test = parse_query_string!(.path)

```
