### DISCUSSION TITLE
Vector memory explodes with recursion

### DISCUSSION THREAD

**Discussion by MadsRC** [vectordotdev/vector#16682] [General]
I have a Vector source of type Splunk HEC and the workload that ships data to it sends it to the `/services/collector/raw` endpoint. The data shipped is newline delimited JSON (fi t helps, it is logs from Cloudflare, using their LogPush to Splunk HEC).

When piping that directly to a sink, Vectors memory usage idles at around 30-40MB. For that I'm using this config:

```toml
[sources.http]
type = "splunk_hec"
address = "0.0.0.0:8080"
valid_tokens = [ "${HEC_TOKEN}" ]

[sinks.queue]
type = "kafka"
inputs = [ "filter" ]
bootstrap_servers = "${KAFKA_BROKERS}"
topic = "${KAFKA_TOPIC}"

  [sinks.queue.encoding]
  codec = "json"
  [sinks.queue.tls]
  enabled = true
```

However, since one big blog of newline delimited JSON is of limited use, I want to explode the ndjson to individual events. When doing that with this config, Vectors memory usage explodes to 5GB+

```toml
[sources.http]
type = "splunk_hec"
address = "0.0.0.0:8080"
valid_tokens = [ "${HEC_TOKEN}" ]

[transforms.filter]
type = "remap"
inputs = [ "http" ]
source = '''
  events = []
  buf = split!(.message, "\n")
  map_values(buf) -> |value| {
    if value != "" {
        temp = {}
        temp.event = parse_json!(value)
        events = push(events, temp)
    }
  }
  . = events
'''

[sinks.queue]
type = "kafka"
inputs = [ "filter" ]
bootstrap_servers = "${KAFKA_BROKERS}"
topic = "${KAFKA_TOPIC}"

  [sinks.queue.encoding]
  codec = "json"
  [sinks.queue.tls]
  enabled = true
```

I've tried replicating it on a local instance of Vector, but I can't seem to replicate it there. The environment where it happens is a Kubernetes cluster running the 0.27.1-debian image (which I also tried using locally to replicate the issue).

Does anyone have any idea why the above config would cause memory to explode like that?
