### DISCUSSION TITLE
Vector Agent - Kubernetes source fails to follow configs "ignore_older_secs: 86400" and "read_from: end"

### DISCUSSION THREAD

**Discussion by EdN-terascope** [vectordotdev/vector#16813] [Q&A]
In Vector Agent the kubernetes source is configured to not replay old log events, but old logs are still being processed.

using vector 0.27.0 with helm chart 0.16.3 on kubernetes v1.22.13

Here is the source stanza from the helm chart - is this configured properly? to pick up logs that are a day old or less and follow events added to the end of the file.
```
         sources:
             kubernetes_logs:
               type: kubernetes_logs
               ignore_older_secs: 86400
               read_from: end
               self_node_name: ${VECTOR_SELF_NODE_NAME}
```
This should prevent older logs from being sourced, right?  Currently prior events, in some cases going back many months, are being processed.   Any suggestions are appreciated

Also using journald source with "since_now: true" and getting expected results - thanks
