### DISCUSSION TITLE
How to parse from stdin, exiting after stream is finished?

### DISCUSSION THREAD

**Discussion by strokirk** [vectordotdev/vector#16978] [Q&A] [answered]
Hi! 

I have a few ad-hoc commands where it would be very useful to be able to use `vector` in a shell pipeline, but I can't seem to find any information on how to make vector exit after being done with the log stream.

**Comment by jszwedko** [comment, marked as answer]
Can you share your config? I think `vector` _should_ shutdown if there is only a `stdin` source and its input stream closes.

**Reply by strokirk** [reply]
Sure! Doing a minimal recreation showed me that it was due to me having an (inactive) file source in the same file... 

```toml
[sources.in]
type = "file"
include = ["./log.log"]
multiline.mode = "halt_before"
multiline.condition_pattern = "^[A-Z]+ "
multiline.start_pattern = "^[A-Z]+ "
multiline.timeout_ms = 1

[sources.stdin]
type = "stdin"

[sinks.out]
inputs = ["stdin"]
type = "console"
```

What's the proper way to solve this? Have multiple config file that inherit each other, and activate the relevant one depending on task?
