### DISCUSSION TITLE
reduce message field from elasticsearch

### DISCUSSION THREAD

**Discussion by uglyliu** [vectordotdev/vector#17151] [General]
Kafka log content is  about as follows:
`
{
 "@metadata": {
  "beat": "filebeat",
  "type": "_doc",
  "version": "7.10.0"
 },
 "message": {
  "upstream_response_time": "0.056",
  "upstream_status": "200"
 }
}
`
And Finally, there will be more message fields written in elasticsearch，as follows
![image](https://user-images.githubusercontent.com/22983421/231976119-9a7f3766-e0cb-43c1-bd70-2c3f1750072f.png)

The vector configuration is as follows
[transforms.parse_logs]
type = "json_parser"
inputs = ["dummy_logs"]
source = '''
. = parse_json!(.message)
.message = parse_json!(.message)
'''
My purpose is to finally display on elasticsearch, there is no message field，as follows
![image](https://user-images.githubusercontent.com/22983421/231975901-4bf3f9d3-b32f-4079-90d6-6dd577bcce5f.png)

**Comment by monwolf** [comment]
I'm doing this on filebeat itself:

```
processors:
  - decode_json_fields:
      fields: ['message']
      target: "json"
  - rename:
      fields:
        - from: json.@timestamp
          to: json.log_timestamp
      ignore_missing: false
      fail_on_error: true
  - move_fields:
      from: "json"
      to: ""
  - drop_fields:
      fields: ['message', 'agent', 'ecs', 'input', 'log', 'json']
```
This could work for you as well.
