### DISCUSSION TITLE
how load secrets in vector

### DISCUSSION THREAD

**Discussion by LinTechSo** [vectordotdev/vector#17255] [Q&A]
Hi.
i want to load secret from external vault .
i read about `secret` in following link : [example](https://vector.dev/highlights/2022-07-07-secrets-management/)
but i don't understand too much about it. 
is it correct that we use this feature like the below configuration in main yaml file?
```
    secret:
      vault-test: 
        type: "exec"
        command: ["curl -H 'X-Vault-Token: s.1234'   -H 'X-Vault-Namespace: vault' -X GET http://test.com/v1/demo/data/test"]

    sources:
      demo-test:
        type: demo_logs
        format: json

    sinks:
      console_all:
        type: console
        inputs:
          - demo-test
        target: stdout
        acknowledgements:
          enabled: true
        encoding:
          codec: json
``` 

i would appreciate if anyone help me figure this out.
is there any example or quick start doc?
