### DISCUSSION TITLE
Vector reports fields in GCP service account credentials.json file are unknown

### DISCUSSION THREAD

**Discussion by danhul** [vectordotdev/vector#17382] [Q&A]
I configured vector to ship logs to gcp_stackdriver(Google operations)

```
  sinks:
    google_stackdriver_sink:
      type: "gcp_stackdriver_logs"
      credentials_path: "/path/to/credentials.json"
      project_id: "<project-id>"
      inputs:
        - logs.apache
      log_id: "<log_id>"
      resource:
        type: global
      batch:
        max_size: 1048576
        timeout_secs: 1
```

I downloaded the credentials.json file from Google Cloud but as shown below Vector claims the fields in the credentials.json file are unknown. 

2023-05-11T11:14:29.844667Z ERROR vector::cli: Configuration error. error=unknown field `type` at line 12 column 3

The first standard field in credentials.json is `"type": "service_account"`. If I put the line `"project_id" `before` "type",` vector reports "project_id" is unknown field.

**Comment by jszwedko** [comment]
Hi @danhul ! Could you provide the credentials file with the credentials themselves redacted?

**Reply by danhul** [reply]
Hi @jszwedko,

Here is the content of the credentials.json file

```
{
    "type": "service_account",
    "project_id": "project-id",
    "private_key_id": "private-key-id",
    "private_key": "-----BEGIN PRIVATE KEY-----\n ... \n-----END PRIVATE KEY-----\n",
    "client_email": "client@... .iam.gserviceaccount.com",
    "client_id": "client-id",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/....iam.gserviceaccount.com"
}
```

**Reply by danhul** [reply]
Hi @jszwedko  did you get the time to look at the credentials file I sent last week?

**Reply by jszwedko** [reply]
Hi @danhul ! I was able to try this just now, but I don't get a configuration error with 0.29.1 at least. This is the config I'm using:

```yaml
sources:
  in:
    type: stdin
sinks:
  google_stackdriver_sink:
    type: "gcp_stackdriver_logs"
    credentials_path: "credentials.json"
    project_id: "foo"
    inputs:
      - stdin
    log_id: "bar"
    resource:
      type: global
    batch:
      max_size: 1048576
      timeout_secs: 1
```

and the credentials file you provided. Vector starts up OK -- it just fails to send events -- which seems different than the deserialization issue you were seeing. What version of Vector are you trying?
