### DISCUSSION TITLE
The way Vector discover changes in file input type

### DISCUSSION THREAD

**Discussion by gl1ridae** [vectordotdev/vector#17515] [Q&A] [answered]
Hi! I'm trying to replace big filebeat deployment in company, and started testing Vector recently. The question I have - is there any documentation, or maybe someone know about the way how Vector find changes in discovered files? I'm trying to fine-tune instance, but the time delivery is quite a huge - 99 percentile is about 2-6sec. Is there any way to tune the time discovery? Maybe decrease file polling interval? Or maybe frequency of sending events in sink?

Vector version: **0.30.0**
OS details:
```bash
> uname -r
2.6.32-5-amd64

> cat /etc/debian-release
squeeze
```
Example of config:
```yaml
sources:
  my_events_src:
    type: file
    include:
      - /var/lib/state/SVC/*.log*
    exclude:
      - '*.gz$'
    file_key: ''
    host_key: ''
    glob_minimum_cooldown_ms: 100
    ignore_not_found: false
    line_delimiter: "\n"
    max_line_bytes: 1048576
    max_read_bytes: 1048576
    multi_line_timeout: 1000
    oldest_first: false
    read_from: beginning
    fingerprint:
      ignored_header_bytes: 0
      lines: 1
      strategy: checksum
transforms:
  my_events_tfm:
    type: remap
    inputs:
      - my_events_src
    drop_on_error: true
    source: |
      . = parse_json!(.message)
      .@Event.ReadTime = now()
sinks:
  my_events_snk:
    inputs:
      - my_events_tfm
    address: "logstash_tcp_input:1221"
    mode: tcp
    type: socket
    encoding:
      codec: json
    healthcheck:
      enabled: true
    buffer:
      type: disk
      when_full: block
      max_size: 536870912
```
