### DISCUSSION TITLE
Node name insted of vector pod name

### DISCUSSION THREAD

**Discussion by therus000** [vectordotdev/vector#17612] [Q&A] [answered]
Good day 
i used  vector to send the kubernets audit-logs to kafka
everything works fine.
but i didnt find where i can change the vector pod name to the node name of kubernetes
it looks like this 
![image](https://github.com/vectordotdev/vector/assets/48754322/7a0f33a5-c0af-4a1a-8491-ef90cb00a082)

 my vector configs:

```
type: file
        include:
          - /var/lib/rancher/rke2/server/logs/audit.log
        host_key: host
        read_from: end
```

**Comment by spencergilbert** [comment, marked as answer]
The hostname returned Vector will return the container's hostname, you can use something like we do in the [Helm chart](https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/_pod.tpl#L58-L61) and use a `remap` transform to replace the `host` with the value from the environment variable.

**Comment by therus000** [comment]
can you explain little
i already used transforms and remap to add fixed text to log
what should i add to .hostname to get a nodename where is vector run


```
   transforms:
      add_env:
        type: remap
        inputs:
          - audit_file
        source: |-
          .kubernetes_cluster = "mycluster"
          .hostname = spec.nodeName
```

i try like this and i got error
