### DISCUSSION TITLE
source/address field: hostname not supported ?

### DISCUSSION THREAD

**Discussion by softlion** [vectordotdev/vector#17866] [Q&A]
It looks like vector does not resolve hostnames for sockets.

I have a docker network with 2 containers, I wanted to use the docker version of vector with a source port on the other container.  
I can not rely on IPs as docker may change them.  
Do you know a solution ?  
Ty !

```toml
[sources.some]
type = "socket"
address = "somehost.local:30001"
```

```
Configuration error. error=Must be a valid IPv4/IPv6 address with port, or start with "systemd"
```
