### DISCUSSION TITLE
Source: UDP & protobuf

### DISCUSSION THREAD

**Discussion by lzwaan** [vectordotdev/vector#18273] [Q&A]
Is it possible to use UDP as source and to decode (juniper) protobuf messages?

**Comment by jszwedko** [comment]
Hi @lzwaan ,

Yes you could use the `socket` source to do this. As of v0.32.0 there is a configurable protobuf decoder. You just have to provide the protobuf desc file. See https://vector.dev/docs/reference/configuration/sources/socket/#decoding.protobuf for more details.

**Reply by lzwaan** [reply]
Thank you for the quick reply. Is there a specific way for vector/rust how to create the description file? Because when i created one with protoc, vector was complaining about the format, do you maybe have a example command to do it correctly?

**Reply by jszwedko** [reply]
Can you share what you tried? I haven't actually tried to use this feature yet so I'm not sure exactly how the desc file is expected to be generated. You can see some example desc files that were added with the implementation: https://github.com/vectordotdev/vector/pull/18019/files#diff-f8ae81252cbe11d856362cb940fee1d887d24529704764ea37e44fd304b0c766 . If you are more familiar with protobuf than I am maybe something will jump out to you.

**Reply by Daniel599** [reply]
given a proto file named [`test_protobuf.proto`](https://github.com/vectordotdev/vector/blob/a06c71102867af5e4526e445f9ba8f4506382a30/lib/codecs/tests/data/decoding/protobuf/test_protobuf.proto)
you can run the following commands to create a desc file
```bash
cd /var/protobuf # folder contains test_protobuf.proto
protoc -o /var/protobuf/test_protobuf.desc test_protobuf.proto --include_imports
```
Edit: added `--include_imports`

your vector's config file should look something like the following:
```toml
[sources.my_kafka_protobuf]
type = "kafka"
bootstrap_servers = "localhost:9092"
group_id = "consumer-group-name"
topics = [ "protobuf_topic" ]
[sources.my_kafka_protobuf.decoding]
codec = "protobuf"
[sources.my_kafka_protobuf.decoding.protobuf]
desc_file = "/var/protobuf/test_protobuf.desc"
message_type = "test_protobuf.Person"


[sinks.my_sink_id]
type = "console"
inputs = [ "my_kafka_protobuf" ]
target = "stdout"
[sinks.my_sink_id.encoding]
codec = "json"
```

hope this helps.
