### DISCUSSION TITLE
Poblems trying to use AWS sink with assume_role

### DISCUSSION THREAD

**Discussion by agustin-munoz** [vectordotdev/vector#18689] [Q&A] [answered]
Hello,

On our setup in order to access S3 bucket placed on another account we use sts assume role with external-id and role-session-name, we have a provided credentials file and we are able to use sts assume role, then access the bucket.

I am trying to setup this using AWS S3 sink, having this:

Credentials file set in /etc/aws/credentials and environment variable **AWS_CONFIG_FILE** set to use that file
Environment variables ARN_EXTERNAL_ID and AWS_ROLE_SESSION_NAME

The sink section:

```
sinks:
  audit_bucket:
    type: aws_s3
    inputs:
      - squid-logs.shadow
    acknowledgements:
      enabled: false
    auth:
      assume_role: ${ARN}
      external_id: ${ARN_EXTERNAL_ID}
    bucket: s3sinkbucket
    encoding:
      codec: json
    healthcheck:
      enabled: false
    region: eu-central-1
    storage_class: STANDARD_IA
    filename_append_uuid: true
    filename_time_format: "%Y/%m/%d"
    key_prefix: "squid_log/maint5.eu-central-1.aws.openpaas-maint.axa-cloud.com/%F/"
```

When I start vector it is stopping with following error:

2023-09-27T08:17:34.874299Z ERROR vector::cli: Configuration error. error=data did not match any variant of untagged enum AwsAuthentication

If I remove the external_id, then it starts but it is not able to perform sts as the user is not allowed.

Is there any way to place together assume_role and external_id ??
