### DISCUSSION TITLE
Vector as a receiver for td-agent

### DISCUSSION THREAD

**Discussion by gl1ridae** [vectordotdev/vector#18756] [Q&A] [answered]
Hi all! I'm trying to setup integration with td-agent, since vector supported fluent as a [source](https://vector.dev/docs/reference/configuration/sources/fluent/), but as a result I'm having an empty messages.

Versions:
- vector: **0.29.1**
- td-agent: **4.3.0**

My vector config:
```yaml
sources:
  src_fluent:
    type: fluent
    address: 0.0.0.0:19020
    keepalive:
      time_secs: 10
sinks:
  snk_fluent:
    type: file
    inputs:
    - src_fluent
    path: "/srv/vector/output/fluent.out"
    encoding:
      codec: raw_message

```

And here is config for td-agent:
```xml
<source>
  @type tail
  tag vectortest
  path /srv/vectortest/vector.log
  <parse>
   @type none
  </parse>
  pos_file /srv/vectortest/vector.log.pos
</source>

<match vectortest>
  @type copy

  <store>
      @type forward
      send_timeout 60s
      compress gzip
      <server>
        name vector
        host <vector host ip address>
        port 19020
      </server>
  </store>

</match>
```

I've tried it with and without compression from td-agent side, different kind of parsers but no luck at all. I understand that support is in beta status now, but wonder maybe there's something obvious I'm missing. The fact that I'm receiving empty messages means the issue should be on a side of source, while parsing message. I'll really appreciate any help here.
