### DISCUSSION TITLE
Issue

### DISCUSSION THREAD

**Discussion by shivamsoni1** [vectordotdev/vector#18775] [General] [answered]
my vector.yaml file is  -
sources:
  my_source_id:
    type: opentelemetry
    grpc:
      address: 0.0.0.0:4317
    http:
      address: 0.0.0.0:4318

sinks:
  my_sink_id:
    type: console
    inputs:
      - my_source_id
    encoding:
      codec: json

but getting this error Configuration error. error=Input "my_sourc_id" for sink "my_sink_id" doesn't match any components.

pls help

**Comment by jszwedko** [comment]
Hi @shivamsoni1 ,

It looks like you have a typo since the error message says `my_sourc_id` but the source id is actually `my_source_id`.

**Comment by jtweaver** [comment]
I'm also seeing this issue. It's not a typo. It appears to be a bug. Here's a simple full example:

```
api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  otlp_logs:
    type: "opentelemetry"
    grpc:
      address: 0.0.0.0:4317
    http:
      address: 0.0.0.0:4318
      keepalive:
        max_connection_age_jitter_factor: 0.1
        max_connection_age_secs: 300
sinks:
  console:
    inputs:
      - otlp_logs
    target: stdout
    type: console
    encoding:
      codec: json
```
