### DISCUSSION TITLE
Timestamp literal in tests

### DISCUSSION THREAD

**Discussion by tadej0mins** [vectordotdev/vector#18791] [Q&A]
Hello,

I got the following `vector.yaml` configuration:

```
sources:
  vector_internal_logs:
    type: "internal_logs"

transforms:
  vector_internal_format:
    type: "remap"
    inputs:
      - "vector_internal_logs"
    source: |-
      . = {
          "time": format_timestamp!(.timestamp, format: "%FT%T%.3f"),
          "message": .message
      }

sinks:
  console:
    type: "console"
    inputs:
      - "vector_internal_format"
    encoding:
      codec: "json"

tests:
  - name: "vector_internal_format"
    inputs:
      - insert_at: "vector_internal_format"
        type: "log"
        log_fields:
          timestamp: t'2023-10-05T12:44:54.345262416Z'
          message: "Some message"

    outputs:
      - extract_from: "vector_internal_format"
        conditions:
          - type: "vrl"
            source: |-
              assert_eq!(.time, "2023-10-05T12:44:54.345", "time invalid")

```

I want to test `vector_internal_format` transformation and I don't know how to specify timestamp input (under log_fields) to be of a type `Timestamp` (so that `format_timestamp` function would not throw an error: `expected timestamp, got string`).
