### DISCUSSION TITLE
AWS Opensearch(es) assume_role auth not working

### DISCUSSION THREAD

**Discussion by nic-igaw** [vectordotdev/vector#18835] [Q&A] [answered]
Hi,
I've created AWS ECS cluster of vector applications that basically takes log data via http_server and reroutes the data to AWS Opensearch, but the aws authentication `assume_role` option is giving me a terrible time and it'd be lovely if I can get any help or insight regarding this issue.

Below are the config specifications that I've used:

I've created a task role(`vector-task-role`) with appropriate trusted relationship settings

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

and set in my vector config to assume the same iam role as the one I've given the task:

```yaml

# input sources to vector
sources:
  logs_http:
    type: http_server
    method: "POST"
    address: "0.0.0.0:80"
    path: "/logs/http"
    encoding: "json"

# output location from vector
sinks:
  output_opensearch:
    type: elasticsearch
    inputs:
      - logs_http
    endpoints:
      - [redacted_es_endpoint]
    aws:
      region: "ap-northeast-2"
    bulk:
      index: "{{ .application_name }}-%Y%m%d"
    # ES health check
    healthcheck:
      enabled: false
    auth:
      strategy: "aws"
      assume_role: "arn:aws:iam::[redacted_account_no]:role/vector-task-role"
      region: "ap-northeast-2"
```

This is the error message I get:
```text
<Code>AccessDenied</Code>\n    <Message>User: arn:aws:sts::[redacted_account_no]:assumed-role/vector-task-role/bd70121139e84e788534139edd9e4e4c is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[redacted_account_no]:role/vector-task-role</Message>
```

I've went through all the permissions in the `vector-task-role` and event gave it all permission just to see if there was something wrong on my end, but it still wouldn't work.

Does this error have to do with the aws sdk vector uses?

Any help would be delightful.

Thanks!
