### DISCUSSION TITLE
Trying to capture protobufServer() output from PowerDNS recursor, but not seeing anything (v0.33.0)

### DISCUSSION THREAD

**Discussion by james-stevens** [vectordotdev/vector#18897] [Q&A]
I'm using the PowerDNS recursor to implement DNS filtering using an RPZ. I should be able to see RPZ block events logged via their protobuf interface. Looking at its internal metrics, `vector` is reporting that it is receiving bytes, but not logging anything to file, but I can get it to log the `dnstap` data from `pdns_recursor` fine.

https://docs.powerdns.com/recursor/lua-config/protobuf.html

PowerDNS provide the `proto` file (see link), which I compiled,using `protoc`, into a `desc` file and `vector validate` is happy with picking up the message type from the `desc`.

My vector config
```
healthchecks:
  require_healthy: true

sources:
  src_my_prom:
    type: internal_metrics

  dnstap_src:
    type: dnstap
    raw_data_only: false
    socket_path: /run/vector/dnstap.sock
    socket_file_mode: 0o777

  dns_msg:
    type: socket
    address: "0.0.0.0:4100"
    mode: "tcp"
    decoding:
      codec: protobuf
      protobuf:
        desc_file: /etc/vector/dnsmessage.desc
        message_type: PBDNSMessage


sinks:
  output_my_prom:
    type: prometheus_exporter
    address: 0.0.0.0:9598
    inputs: [ src_my_prom ]

  msg_to_files:
    type: file
    inputs: [ dns_msg ]
    healthcheck:
      enabled: true
    framing:
      method: "newline_delimited"
    path: "/opt/dnsmsg/%Y/%m/%d/%H/%M/dnsmsg_%s.log"
    encoding:
      codec: json
      metric_tag_values: full

  tap_to_files:
    type: file
    inputs: [ dnstap_src ]
    healthcheck:
      enabled: true
    framing:
      method: "newline_delimited"
    path: "/opt/dnstap/%Y/%m/%d/%H/%M/dnstap_%s.log"
    encoding:
      codec: json
      metric_tag_values: full
```

Then I have `protobufServer("127.0.0.1:4100")` in my `recursor.lua` to enable the `pdns-recursor` end.

Using `netstat -nap` I can see the two applications are connected to each other.

When I `curl` the metrics from `vector`, and look for `vector_component_received_bytes_total` & `dns_msg`, I can see bytes coming in, but I never see any files logged in `/opt/dnsmsg` (directory is owned by `vector`).

The metric `vector_component_received_event_bytes_total` for `msg_to_files` is also zero.

There's nothing logged by either application in `syslog` or `systemctl`
