### DISCUSSION TITLE
Let me try one more question

### DISCUSSION THREAD

**Discussion by Manniac07** [vectordotdev/vector#18891] [Q&A]
I know my questions don't gain much traction but let me try one more time. And this might be a very easy one but I can't find it. 

In reference to my earlier question about labels [nested labels](https://github.com/vectordotdev/vector/discussions/18821). 

I am now putting both labels into their own arrays dynamically. Is there a simple way to return the size of each array? Lua documentation says to add a # in front of the array but that is used in vector to signal the start of a comment.

**Comment by jszwedko** [comment]
Hi @Manniac07 ! I'm not sure if I understand the specific use-case you have, but using `#` in a `lua` transform configuration should be fine. For example:

```
transforms:
  my_transform_id:
    type: lua
    inputs:
      - my-source-or-transform-id
    version: "2"
    hooks:
      process: |-
        function (event, emit)
        	#s can be used in here without being YAML comments
        end
```
