### DISCUSSION TITLE
how can I use prometheus_exporter with ipv6?

### DISCUSSION THREAD

**Discussion by zey1996** [vectordotdev/vector#18926] [Q&A] [answered]
I have a k8s cluster on IPv6, and the Vector pod works on IPv6. 
I use the Vector prometheus exporter sink, and I know the address option. 
I hope the prometheus exporter listens to the IPv6 address. How should I do it? 
My IPv4 setting is 0.0.0.0:9090.

setting:
```
      prom_exporter:
        type: prometheus_exporter
        inputs: [internal_metrics]
        address: 0.0.0.0:9090
```
