### DISCUSSION TITLE
What is data_dir? Should the user create it?

### DISCUSSION THREAD

**Discussion by ddxv** [vectordotdev/vector#19123] [Q&A] [answered]
```toml
[sources.nginx_logs]
type = "file"
include = [ "/var/log/nginx/access.log" ]
read_from = "end"

[sinks.my_sink_id]
type = "console"
inputs = ["nginx_logs"]
encoding.codec = "json"
```

When trying to run the above on a fresh install of Vector from the downloaded bash script (not via apt) I encountered the same issue as this discussion:
https://github.com/vectordotdev/vector/discussions/11390

```2023-11-12T03:46:29.890581Z ERROR vector::topology::builder: Configuration error. error=Source "nginx_logs": data_dir "/var/lib/vector/" does not exist```

Based on the above discussion, I tried creating fixing by creating `sudo mkdir /var/lib/vector` but that led to the next error:
```Configuration error. error=Source "nginx_logs": Could not create subdirectory "nginx_logs" inside of data dir "/var/lib/vector/": Permission denied (os error 13)```

This feels like I'm going the wrong direction due to the permissions. Instead what should I be doing?
