### DISCUSSION TITLE
Access Metadata

### DISCUSSION THREAD

**Discussion by coredump17** [vectordotdev/vector#19212] [General]
Hi All,

I have a socket

```yaml
sources:
  src_syslog:
    type: socket
    address: 0.0.0.0:514
    mode: udp


transforms:
  add_tags:
    type: remap
    inputs:
      - src_syslog
    source: |-
       .meta.listener = "src_syslog"
```

When i tap the transform 'add_tags' with -m (meta) i see component_id. I want to use the vrl to .meta.listener = %component_id instead of hard coding it but it shows as null. 

i tried  .meta.listener = %component_id  and .meta.listener = .component_id

```
  vector tap -m  --outputs-of add_tags
{"component_id":"src_syslog","component_kind":"source","component_type":"socket","event"...blah}
```

any help would be greatly appreciated.
