### DISCUSSION TITLE
Upgrade failed on vector helm chart

### DISCUSSION THREAD

**Discussion by Angel0r** [vectordotdev/vector#19229] [Q&A]
Hey!

New to vector and I want to try it out. I installed the vector helm chart with the Agent role and everything was fine. However when I changed the customConfig: {} so it could send the logs to Loki I got:
`Error: UPGRADE FAILED: cannot patch "vector" with kind Service: Service "vector" is invalid: spec.ports: Required value`
customConfig look like bellow:
```yaml
customConfig:
  sinks:
    loki:
      inputs:
        - logs_json # Use the Kubernetes logs as input
      type: loki
      endpoint: http://<LOKI-IP>:3100 # Loki service address
      encoding:
        codec: json
      labels:
        - app: "web"
        - env: "test"

  sources:
    k8s_logs:
      type: kubernetes_logs
```
Should I change the vector service as well?

/Angelos
