### DISCUSSION TITLE
Benchmarking multiple source/sink combinations

### DISCUSSION THREAD

**Discussion by jlazic** [vectordotdev/vector#19278] [General]
# Benchmark

AMD Epyc 9554 (128 core)

TCP inputs are fed with 50GB file containing 8M log events in syslog RFC5524 format
Each input is being sent the same 50GB file, so 4 inputs will process total of 200GB
VRL remap is CPU intensive 250 lines of code.
At first we were assuming that CPU will be bottleneck for our pipelines because of
intensive VRL remapping, but it turned out that with single source/sink we simply can't
saturate more than 20 CPU cores.

In production we pull data from Kafka and sink it into Elasticsearch. Issue is that with
one source and sink per vector server we can't utilize more than 20 cores.
What we do now is duplicate sources and sinks in order to utilize CPU more. This is working
fine but we'd like to get to bottom of this and hopefuly be able to run single source/sink
per server.

Issue #18164 prompted me to run these tests and see if we can avoid running multiple inputs/sinks.

## Results

4in,4vrl,4s combination (4 inputs, 4 VRL remaps and 4 sinks) is winning combination for throughput,
and seems like only one that can scale verticaly to use most of the CPU available
Seems like sink is limiting factor, even though blackhole should not have any limitations.
This can be seen with 1in,1vrl,4s and 1in,4vrl,4s which both utilize CPU much better than any 
of other combinations that have just single sink.

Insights and comments from someone with more vector.dev exp would be really appriciated here.

|             | 4in,4vrl,4s | 4in,4vrl,1s | 4in,1vrl,1s | 1in,1vrl,1s | 1in,1vrl,4s | 1in,4vrl,4s
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |----
| input       | 45k/s       | 16k/s       | 14k/s       | 60k/s       | 80k/s       | 35k/s
| input total | 180k/s      | 64k/s       | 55k/s       | 60k/s       | 80k/s       | 140k/s
| sink        | 45k/s       | 64k/s       | 55k/s       | 60k/s       | 20k/s       | 35k/s
| sink total  | 180k/s      | 64k/s       | 55k/s       | 60k/s       | 80k/s       | 140k/s
| cpu         | 6800%       | 2300%       | 2200%       | 1900%       | 3400%       | 5000%
| vrl util    | 0.15        | 0.05        | 0.16        | 0.16        | 0.25        | 0.4
| sink util   | 0.75        | 0.95        | 0.77        | 0.74        | 0.38        | 0.55
| time        | 2m52.244s   | 7m46.586s   | 8m55.302s   | 2m14.218s   | 1m40.827s   | 0m55.454s

Bellow are configs used for testing

### 4 TCP sources into 4 VRL into 4 sinks

```toml
[sources.tcp-1]
    type = "socket"
    address = "0.0.0.0:9001"
    mode = "tcp"

[sources.tcp-2]
    type = "socket"
    address = "0.0.0.0:9002"
    mode = "tcp"

[sources.tcp-3]
    type = "socket"
    address = "0.0.0.0:9003"
    mode = "tcp"

[sources.tcp-4]
    type = "socket"
    address = "0.0.0.0:9004"
    mode = "tcp"

[transforms.parse-1]
    inputs = [ "tcp-1" ]
    type = "remap"
    file = "adn.vrl"

[transforms.parse-2]
    inputs = [ "tcp-2" ]
    type = "remap"
    file = "adn.vrl"

[transforms.parse-3]
    inputs = [ "tcp-3" ]
    type = "remap"
    file = "adn.vrl"

[transforms.parse-4]
    inputs = [ "tcp-4" ]
    type = "remap"
    file = "adn.vrl"

[sinks.blackhole-1]
    type = "blackhole"
    inputs = [ "parse-1" ]

[sinks.blackhole-2]
    type = "blackhole"
    inputs = [ "parse-2" ]

[sinks.blackhole-3]
    type = "blackhole"
    inputs = [ "parse-3" ]

[sinks.blackhole-4]
    type = "blackhole"
    inputs = [ "parse-4" ]
```

### 4 TCP sources into 4 VRL into 1 sink

```toml
[sources.tcp-1]
    type = "socket"
    address = "0.0.0.0:9001"
    mode = "tcp"

[sources.tcp-2]
    type = "socket"
    address = "0.0.0.0:9002"
    mode = "tcp"

[sources.tcp-3]
    type = "socket"
    address = "0.0.0.0:9003"
    mode = "tcp"

[sources.tcp-4]
    type = "socket"
    address = "0.0.0.0:9004"
    mode = "tcp"

[transforms.parse-1]
    inputs = [ "tcp-1" ]
    type = "remap"
    file = "adn.vrl"

[transforms.parse-2]
    inputs = [ "tcp-2" ]
    type = "remap"
    file = "adn.vrl"

[transforms.parse-3]
    inputs = [ "tcp-3" ]
    type = "remap"
    file = "adn.vrl"

[transforms.parse-4]
    inputs = [ "tcp-4" ]
    type = "remap"
    file = "adn.vrl"

[sinks.blackhole]
    type = "blackhole"
    inputs = [ "parse-*" ]
```

### 4 TCP sources into 1 VRL into 1 sink

```toml
[sources.tcp-1]
    type = "socket"
    address = "0.0.0.0:9001"
    mode = "tcp"

[sources.tcp-2]
    type = "socket"
    address = "0.0.0.0:9002"
    mode = "tcp"

[sources.tcp-3]
    type = "socket"
    address = "0.0.0.0:9003"
    mode = "tcp"

[sources.tcp-4]
    type = "socket"
    address = "0.0.0.0:9004"
    mode = "tcp"

[transforms.parse]
    inputs = [ "tcp-*" ]
    type = "remap"
    file = "adn.vrl"

[sinks.blackhole]
    type = "blackhole"
    inputs = [ "parse" ]
```

### 1 TCP source into 1 VRL into 1 sink

```toml
[sources.tcp]
    type = "socket"
    address = "0.0.0.0:9001"
    mode = "tcp"

[transforms.parse]
    inputs = [ "tcp" ]
    type = "remap"
    file = "adn.vrl"

[sinks.blackhole]
    type = "blackhole"
    inputs = [ "parse" ]
```

### 1 TCP source into 1 VRL into 4 sink

```toml
[sources.tcp]
    type = "socket"
    address = "0.0.0.0:9001"
    mode = "tcp"

[transforms.parse]
    inputs = [ "tcp" ]
    type = "remap"
    file = "adn.vrl"

[transforms.lb]
    type = "remap"
    inputs = ["parse"]
    drop_on_error = true
    source = """
      .partition = mod(to_unix_timestamp!(.timestamp, unit: "milliseconds"), 4)
    """

 [transforms.route]
    type = "route"
    inputs = ["lb"]
    [transforms.route.route]
        sink1 = '.partition == 0'
        sink2 = '.partition == 1'
        sink3 = '.partition == 2'
        sink4 = '.partition == 3'
        
[sinks.blackhole-1]
    type = "blackhole"
    inputs = [ "route.sink1" ]

[sinks.blackhole-2]
    type = "blackhole"
    inputs = [ "route.sink2" ]

[sinks.blackhole-3]
    type = "blackhole"
    inputs = [ "route.sink3" ]

[sinks.blackhole-4]
    type = "blackhole"
    inputs = [ "route.sink4" ]
```

### 1 TCP source into 4 VRL into 4 sink

```toml
[sources.tcp]
    type = "socket"
    address = "0.0.0.0:9001"
    mode = "tcp"

[transforms.lb]
    type = "remap"
    inputs = ["tcp"]
    drop_on_error = true
    source = """
      .partition = mod(to_unix_timestamp!(.timestamp, unit: "milliseconds"), 4)
    """

[transforms.route]
    type = "route"
    inputs = ["lb"]
    [transforms.route.route]
        vrl-1 = '.partition == 0'
        vrl-2 = '.partition == 1'
        vrl-3 = '.partition == 2'
        vrl-4 = '.partition == 3'

[transforms.parse-1]
    inputs = [ "route.vrl-1" ]
    type = "remap"
    file = "adn.vrl"

[transforms.parse-2]
    inputs = [ "route.vrl-2" ]
    type = "remap"
    file = "adn.vrl"

[transforms.parse-3]
    inputs = [ "route.vrl-3" ]
    type = "remap"
    file = "adn.vrl"

[transforms.parse-4]
    inputs = [ "route.vrl-4" ]
    type = "remap"
    file = "adn.vrl"
        
[sinks.blackhole-1]
    type = "blackhole"
    inputs = [ "parse-1" ]

[sinks.blackhole-2]
    type = "blackhole"
    inputs = [ "parse-2" ]

[sinks.blackhole-3]
    type = "blackhole"
    inputs = [ "parse-3" ]

[sinks.blackhole-4]
    type = "blackhole"
    inputs = [ "parse-4" ]
```
