### DISCUSSION TITLE
Scrap all /metrics endpoints pods from DaemonSet, like Prometheus (Pod&ServiceMonitor)

### DISCUSSION THREAD

**Discussion by Momotoculteur** [vectordotdev/vector#19295] [Q&A]
Hello Guys 
I have this configuration defined in my image : 

Multiple nodes which run in each : 
- One vector agent
- One instance of cAdvisor 

cAdvisor is like kube-state-metrics, expose a lot of metrics on 8080/metrics. I can scrap directly KSM via prometheus_scrape Vector Datasource which work nicely, but this is a replicatSet. 
But cAdvisor run in daemonset to have node base metrics, not like KSM. I thought that i could make the same with cAdvisor, to call directly the pod and do not pass to the service : 
```
     sources:
      cadvisor:
        endpoints:
        - http://cadvisor:8080/metrics
        scrape_interval_secs: 60
        type: prometheus_scrape
```

But this seems to pass thought the service, because i have a lot of metrics, but not 100 % from all my nodes :wat: 

I'm a bit lost because i'm not expert in Kube & Vector, my apologies for this idiot question. 

Do i have to use a Prometheus agent, and scrap my pods with Pod&Service monitor, and then be scrapped from Vector with prometheus exporter source ? Or is this possible from Vector to scrap this kind of stuff directly without to use Prometheus ? 

Thanks a lots guys 

Ps: This is what i try to achieve 
<img width="500" alt="image" src="https://github.com/vectordotdev/vector/assets/7581959/d8233d8a-688c-497b-8b3f-3697d6c70c3b">
