### DISCUSSION TITLE
Kubernetes source

### DISCUSSION THREAD

**Discussion by inatale** [vectordotdev/vector#19374] [Q&A] [answered]
Hi! I'm wondering if Kubernetes source (https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/) also supports Kubernetes audit logs gathering (if audit enabled)? I found https://github.com/vectordotdev/vector/issues/1424 but didn't get if it was implemented or not. 

And if audit logs supported what is the structure of such events that exposed by Vector.dev Kubernetes source?

**Comment by jszwedko** [comment, marked as answer]
Hi @inatale !

https://github.com/vectordotdev/vector/issues/1424 has not been implemented. Currently Vector can only collect pod logs.

**Comment by inatale** [comment]
Finally we added the following lines:
```
    kubernetes_audit_logs:
      type: file
      include:
        - /var/log/kubernetes/audit/*.log
```
