### DISCUSSION TITLE
Vector not accepting connections on sink failure

### DISCUSSION THREAD

**Discussion by jakegut** [vectordotdev/vector#19815] [Q&A] [answered]
I'm using Vector `v0.35.0` in an aggregator configuration, where it accepts json via HTTP, from FluentBit agents, and inserting it into ClickHouse using the sink. I'm hosting it on AWS ECS Fargate in front of an NLB with health-checks enabled based on the API `/health` endpoint.

Whenever the sink starts to experience a large amount of failures, in my case a number of "connection resets" from ClickHouse Cloud whenever it scales up, Vector will soon stop accepting connections resulting in an unhealthy task and being killed off by AWS. Vector also shoots up in memory, but there's nothing indicating in the logs (level=info) to indicate that.

I tried buffering to filesystem to see how it would perform and it resulted in a 2-3x performance decrease, which is a considerable amount at our scale, so I haven't tried that out with ClickHouse Cloud scaling up.

Example error:
```
2024-02-06T08:57:49.515492Z  WARN sink{component_kind="sink" component_id=clickhouse_envoy component_type=clickhouse}:request{request_id=9069}:http: vector::internal_events::http_client: HTTP error. error=connection closed before message completed error_type="request_failed" stage="processing" internal_log_rate_limit=true
```

Vector config:
```
api:
  enabled: true
  address: "0.0.0.0:8686" 

sources:
  envoy_in:
    type: http_server
    address: 0.0.0.0:8123
    encoding: ndjson
    path_key: __vector_http_path

sinks:
  clickhouse_envoy:
    type: clickhouse
    inputs:
      - envoy_in
    endpoint: https://<host>.us-west-2.vpce.aws.clickhouse.cloud:8443
    database: default
    table: envoy
    auth:
      strategy: basic
      user: default
      password: <password>
    batch:
      max_bytes: 30000000
      timeout_secs: 2
# -- later tried --
    buffer:
      type: disk
      max_size: 4294967296 # 4 GB    
```
