### DISCUSSION TITLE
Can vector (inside a docker container as a service) connect to other docker services directly without HTTP Sink connection?

### DISCUSSION THREAD

**Discussion by phoenisx** [vectordotdev/vector#19905] [Q&A]
Hi

Is there a way to create a sink that can connect to Docker service directly, without exposing the other service as an HTTP to the outside world?

E.g. I have two docker services: `vector` and `analytics`, where `analytics` service is not exposed to the outside world, but lies in the same docker network where `vector` service lies.

So instead of creating an HTTP sink, like:
```yml
sinks:
   analytics:
      type: "http"
      inputs:
         - logs
      encoding:
         codec: "json"
      method: "post"
      request:
         retry_max_duration_secs: 10
      uri: "http://${SERVICE_ANALYTICS_NAME:-analytics}:${ANALYTICS_PORT:-3000}/api/logs?source_name=gotrue.logs.prod&api_key=your-super-secret-and-long-logflare-key"
```

Can I make the above work with service names directly.

**Comment by jszwedko** [comment]
This seems like less of a Vector question and more of a Docker DNS and networking question 🤔

**Reply by phoenisx** [reply]
Possibly, but my question was whether I can use an `uri` string in vector config with service name or does it always has to be a valid HTTP string, which I feel gets handled internally by service right?

I'm still learning, so possibly my question might seem stupid, but do correct me if I am wrong anywhere 😅

**Reply by jszwedko** [reply]
No worries! You can do what you have above and template the URI based on environment variables. This is documented here: https://vector.dev/docs/reference/configuration/#environment-variables

**Reply by phoenisx** [reply]
Thanks for the quick response.

I understand env variables is possible, but is the following possible?
```
uri: "${DOCKER_SERVICE_NAME}/api/logs"
```

where `DOCKER_SERVICE_NAME` is an env variable pointing to the internal docker service name, instead of the docker container name bound to the exposed HTTP endpoint.

**Reply by jszwedko** [reply]
That I'm not sure about. It seems like it would depend on whether the service is accessible via that hostname within the Docker container that Vector is running in.

**Reply by phoenisx** [reply]
Hi @jszwedko 

I am using the following setup to debug my source logs from docker, but am not even seeing any source logs getting logged to console stdout using `console` sink. Sharing my `vector.yml` and `docker-compose.yml` to add more context here:

```yml
# vector.yml
api:
   enabled: true
   address: "0.0.0.0:${VECTOR_SERVICE_PORT:-9001}"
sources:
   docker_host:
      type: docker_logs
      include_labels:
         - "com.foo.appname=foo-web-app"
         - "com.foo.appname=foo-web-service"
sinks:
   console_logs:
      type: console
      encoding:
         # codec: text
         codec: raw_message
      inputs:
         - docker_host
      target: stdout
```

```yml
# compose.yml
services:
   nginx:
      container_name: "reverse-proxy"
      image: nginx:latest
      ports:
         - "80:80"
      volumes:
         - ./nginx:/etc/nginx/conf.d:ro
      depends_on:
         - foo-web
         - foo-service
      networks:
         - proxy

   foo-web:
      image: foo-web
      container_name: "foo-web"
      networks:
         - proxy
   foo-service:
      image: foo-service
      container_name: "foo-service"
      networks:
         - proxy
   vector:
      container_name: foo-vector
      image: vector
      build:
         context: ./path/to/vector-dir
         dockerfile: ./Dockerfile
      networks:
         - proxy
      healthcheck:
         test:
         [
            "CMD",
            "wget",
            "--no-verbose",
            "--tries=1",
            "--spider",
            "http://vector:9001/health",
         ]
         timeout: 5s
         interval: 5s
         retries: 3
      env_file:
         - ./path/to/vector-dir/.env
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
   proxy:
```

Am I missing something here? This is my basic setup to just console log the docker source using vector to debug if the logs are received by vector service or not, but in my case nothing gets logged, Vector service starts with correct config file but nothing is getting tracked

**Reply by phoenisx** [reply]
I think the issue is with the docker labels. Removing the labels starts showing the logs, but also disables the filtering entirely.

I am using Docker labels and not Docker Container names, cause my Local and Production setups work very differently, and container names are dynamic.

**Reply by phoenisx** [reply]
Found one more thing, having a single label item works and vector detects it just fine, but the moment I add more than two labels in my .yml, vector service stops detecting the docker containers.
What I mean is that the following works

```yml
# vector.yml
...
sources:
   docker_host:
      type: docker_logs
      include_labels:
         - "com.foo.appname=foo-web-service"
...
```

But the following doesn't

```yml
# vector.yml
...
sources:
   docker_host:
      type: docker_logs
      include_labels:
         - "com.foo.appname=foo-web-app"
         - "com.foo.appname=foo-web-service"
...
```

_I also tried using different label key-value pairs for different images, but it still didn't work._

**Reply by phoenisx** [reply]
This seems to be a workaround for now:

```yml
# vector.yml
...
sources:
   foo_web:
      type: docker_logs
      include_labels:
         - "com.foo.appname=foo-web-app"
   foo_service:
      type: docker_logs
      include_labels:
         - "com.foo.appname=foo-web-service"
...
```
