### DISCUSSION TITLE
The checksum error metric is occurring from kubernetes_logs source. (metric name : vector_checksum_errors_total)

### DISCUSSION THREAD

**Discussion by pingping95** [vectordotdev/vector#20025] [General]
hello.

I am collecting Kubernetes container logs via Kubernetes Log source.

I am getting a checksum error.

<img width="1559" alt="image" src="https://github.com/vectordotdev/vector/assets/67780144/35131fcf-b7de-4fe4-be30-aef9a7df3993">

What does this mean and how can I resolve this error?

And this is my config.

```
  sources:
    internal-metrics:
      type: internal_metrics
      namespace: vector
      scrape_interval_secs: 15

    k8s:
      type: kubernetes_logs
      exclude_paths_glob_patterns:
        - "**/kube-system*/**"
...
        - "**/*.gz"
        - "**/*.tmp"

      glob_minimum_cooldown_ms: 5000
      read_from: beginning
      pod_annotation_fields:
        pod_name: "kubernetes.pod_name"
        pod_owner: ""
        pod_ips: ""
        pod_ip: ""
        pod_annotations: ""
        pod_namespace: "kubernetes.pod_namespace"
        pod_node_name: ""
        pod_uid: ""
        container_name: "kubernetes.container_name"
        container_image_id: ""
        container_image: ""
        container_id: ""
      node_annotation_fields:
        node_labels: ""
      namespace_annotation_fields:
        namespace_labels: ""
```

- Vector : 0.36.0
