### DISCUSSION TITLE
splunk_hec not showing its listening on port

### DISCUSSION THREAD

**Discussion by rajsinghtech** [vectordotdev/vector#20239] [Q&A] [answered]
<img width="1189" alt="image" src="https://github.com/vectordotdev/vector/assets/26187752/5f0b47e1-5fbb-40f1-bed7-4d189b58a143">

````yaml
    api:
      enabled: true
      address: 127.0.0.1:8687
      playground: true

    data_dir: ./data_dir

    # LOG DATAPLANE port 6000
    # METRICS DATAPLANE port 6001
    sources:
      # datadog_agent:
      #   address: 0.0.0.0:8282
      #   type: datadog_agent
      # fluent:
      #   address: 0.0.0.0:24224
      #   type: fluent
      # internal_metrics:
      #   type: internal_metrics
      # logstash:
      #   address: 0.0.0.0:5044
      #   type: logstash
      splunk_hec:
        address: 0.0.0.0:8088
        type: splunk_hec
      # statsd:
      #   address: 0.0.0.0:8125
      #   mode: tcp
      #   type: statsd
      # syslog:
      #   address: 0.0.0.0:9000
      #   mode: tcp
      #   type: syslog
      # vector:
      #   address: 0.0.0.0:6000
      #   type: vector
    sinks:
      splunk:
        type: console
        inputs:
          - splunk_hec
        encoding:
          codec: json
````
