### DISCUSSION TITLE
How to collect k8s container log file(not stdout and stderr )

### DISCUSSION THREAD

**Discussion by fcfangcc** [vectordotdev/vector#20308] [Q&A]
How to collect k8s pod/container log files (not stdout and stderr )?

Like app write logs to container path **/app/logs/test.log**

I try to use kubernetes_logs, but it seems to only collect logs from /var/log/pods/

k8s container runtime: containerd/docker

Maybe config like:
```yaml
sources:
  my_source_id:
    type: kubernetes_logs
    # like file source
    include:
      - /app/logs/*.log
```

Found real path like
**/var/lib/docker/overlay2/9e048600f8da25798790333d8c0d128ba9a9f5c3110c530239fde2737ec0a1b8/diff/app/logs/xxx.log**
