### DISCUSSION TITLE
Vector source is slow

### DISCUSSION THREAD

**Discussion by paulrozhkin** [vectordotdev/vector#20676] [Q&A]
Hello.
I'm trying to use a Vector Source with my gRPC client which use PushEventsRequest from vector.proto as in the issue [New grpc source](https://github.com/vectordotdev/vector/issues/573)

My config file:
```
sources:  
  my_grpc_server:
    type: "vector"
    version: "2"
    address: "0.0.0.0:8310"
    acknowledgements:
      enable: false

  vector_metrics:
    type: internal_metrics
    scrape_interval_secs: 70

sinks:
  stdout_vector_metrics:
    inputs:
      - "vector_metrics"
    type: "console"
    encoding:
      codec: "text"
```

But I have a problem that the vector processes only 30~50 requests per second in one gRPC connection (client can send ~10k requests):
```
2024-06-14T12:43:58.000Z vector_component_received_events_total{component_id="my_grpc_server",component_kind="source",component_type="vector",host="host"} = 0
...
2024-06-14T12:43:59.000Z vector_component_received_events_total{component_id="my_grpc_server",component_kind="source",component_type="vector",host="host"} = 45
```

Example of request in json format:
```
{
  "events": [
    {
      "metric": {
        "name": "metric",
        "timestamp": {
          "seconds": 12323213123,
          "nanos": 0
        },
        "tags_v1": {
          "System": "system"
        },
        "tags_v2": {},
        "kind": 0,
        "counter": {
          "value": 1.4
        },
        "namespace": "a",
        "interval_ms": 100
      }
    }]
}
```

Can I improve this with some vector configuration?
