### DISCUSSION TITLE
How to disable /health endpoint logging?

### DISCUSSION THREAD

**Discussion by stefanitsky** [vectordotdev/vector#20675] [Q&A]
I want to disable /health endpoint logs:
`{"appname":"meln1ks","facility":"ntp","hostname":"we.am","message":"You're not gonna believe what just happened","msgid":"ID93","procid":2650,"severity":"err","timestamp":"2024-06-14T11:47:45.354Z","version":1}
{"appname":"Scarface","facility":"local3","hostname":"up.cw","message":"There's a breach in the warp core, captain","msgid":"ID89","procid":2198,"severity":"crit","timestamp":"2024-06-14T11:47:46.354Z","version":1}
{"appname":"jesseddy","facility":"uucp","hostname":"some.ieee","message":"We're gonna need a bigger boat","msgid":"ID853","procid":1323,"severity":"alert","timestamp":"2024-06-14T11:47:47.354Z","version":2}
{"appname":"benefritz","facility":"syslog","hostname":"make.nowruz","message":"You're not gonna believe what just happened","msgid":"ID798","procid":9527,"severity":"notice","timestamp":"2024-06-14T11:47:48.355Z","version":2}
{"appname":"b0rnc0nfused","facility":"authpriv","hostname":"some.property","message":"Maybe we just shouldn't use computers","msgid":"ID520","procid":4639,"severity":"info","timestamp":"2024-06-14T11:47:49.354Z","version":1}
{"appname":"KarimMove","facility":"clockd","hostname":"up.jnj","message":"You're not gonna believe what just happened","msgid":"ID803","procid":6539,"severity":"err","timestamp":"2024-06-14T11:47:50.354Z","version":2}
{"appname":"jesseddy","facility":"local2","hostname":"for.gratis","message":"You're not gonna believe what just happened","msgid":"ID564","procid":4672,"severity":"info","timestamp":"2024-06-14T11:47:51.354Z","version":1}
{"appname":"BronzeGamer","facility":"local1","hostname":"we.stockholm","message":"A bug was encountered but not in Vector, which doesn't have bugs","msgid":"ID695","procid":2074,"severity":"alert","timestamp":"2024-06-14T11:47:52.354Z","version":2}
{"appname":"AmbientTech","facility":"user","hostname":"random.rehab","message":"Take a breath, let it go, walk away","msgid":"ID437","procid":3457,"severity":"err","timestamp":"2024-06-14T11:47:53.354Z","version":1}
{"appname":"jesseddy","facility":"user","hostname":"random.kerrylogistics","message":"Maybe we just shouldn't use computers","msgid":"ID183","procid":5791,"severity":"notice","timestamp":"2024-06-14T11:47:54.353Z","version":2}
{"appname":"BronzeGamer","facility":"news","hostname":"up.fashion","message":"Maybe we just shouldn't use computers","msgid":"ID653","procid":4913,"severity":"notice","timestamp":"2024-06-14T11:47:55.353Z","version":2}
`

Any ideas?

**Comment by jszwedko** [comment]
That looks like you have the `demo_log` source configured.

**Reply by stefanitsky** [reply]
vector.toml
```toml
[api]
address = "0.0.0.0:8080"
enabled = true
graphql = false
playground = false
```

source.toml
```toml
type = "kafka"
bootstrap_servers = "${KAFKA_BOOTSTRAP_SERVERS:?err}"
group_id = "vector"
topics = [ "${KAFKA_TOPIC:?err}" ]
```

sink.toml
```toml
type = "elasticsearch"
inputs = [ "parser" ]
endpoints = ["${ES_URL:?err}"]
mode = "bulk"
bulk.index = "${ES_INDEX:?err}"
api_version="v7"
auth.strategy = "basic"
auth.user = "${ES_AUTH_USER:?err}"
auth.password = "${ES_AUTH_PASSWORD:?err}"
tls.verify_certificate = false
```

parser.toml
```toml
type = "remap"
inputs = ["source"]
drop_on_error = true
source = """
. = parse_json!(.message)
.@timestamp = .calculated_at"""
```

**Reply by stefanitsky** [reply]
deployment.yaml
```yaml

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.portName }}
            initialDelaySeconds: {{ .Values.deployment.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.deployment.probes.liveness.failureThreshold }}

          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.portName }}
            initialDelaySeconds: {{ .Values.deployment.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.deployment.probes.startup.failureThreshold }}
```
