### DISCUSSION TITLE
Use vector to transfer OpenTelemetry ProtoBuf Data from S3 to Kafka

### DISCUSSION THREAD

**Discussion by scila1996** [vectordotdev/vector#20718] [General]
I everyone

I use OpenTelemetry Collector Contrib with exporters to AWS S3 with otlp_proto, data formated as ExportLogsServiceRequest. Then I use vector AWS S3 to read from S3 with SQS event and copy proto event to Kafka.

First. I create desc file from 

https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/collector/logs/v1/logs_service.proto#L36

```
protoc --descriptor_set_out=logs_service.desc --include_imports opentelemetry/proto/collector/logs/v1/logs_service.proto
```

and try to decode successfully

```
protoc --decode=opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest --descriptor_set_in=../logs_service.desc  < ../data/logs_101951345.binpb
```

and this i my vector config

```
schema:
  log_namespace: true

sources:
  s3_logs:
    type: aws_s3
    compression: auto
    decoding:
      codec: protobuf
      protobuf:
        desc_file: ./logs_service.desc
        message_type: opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest
    strategy: sqs
    sqs:
      delete_message: true
      queue_url: "https://sqs.ap-southeast-1.amazonaws.com/123456789012/pvcb-infinity-dev-s3-events-log-sqs-queue"
sinks:
  stdout:
    type: console
    inputs:
      - s3_logs
    encoding:
      codec: protobuf
      protobuf:
        desc_file: ./logs_service.desc
        message_type: opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest

```

But error are show as below

2024-06-23T18:21:27.647922Z ERROR source{component_kind="source" component_id=s3_logs component_type=aws_s3}: vector::internal_events::codecs: Failed deserializing frame. error=Error parsing protobuf: DecodeError { description: "unexpected end group tag", stack: [] } error_code="decoder_deserialize" error_type="parser_failed" stage="processing" internal_log_rate_limit=true
2024-06-23T18:21:27.648015Z ERROR source{component_kind="source" component_id=s3_logs component_type=aws_s3}: vector::internal_events::codecs: Internal log [Failed deserializing frame.] is being suppressed to avoid flooding.
2024-06-23T18:21:37.648059Z ERROR source{component_kind="source" component_id=s3_logs component_type=aws_s3}: vector::internal_events::codecs: Internal log [Failed deserializing frame.] has been suppressed 923297 times.
2024-06-23T18:21:37.648085Z ERROR source{component_kind="source" component_id=s3_logs component_type=aws_s3}: vector::internal_events::codecs: Failed deserializing frame. error=Error parsing protobuf: DecodeError { description: "unexpected end group tag", stack: [] } error_code="decoder_deserialize" error_type="parser_failed" stage="processing" internal_log_rate_limit=true

Does vector support to transfer OpenTelemetry Protobuf message to Kafka ? Is my configuration wrong ?

Thank
