### DISCUSSION TITLE
¿Vector > HAProxy > datadoghq.eu?

### DISCUSSION THREAD

**Discussion by julgsk** [vectordotdev/vector#20833] [Q&A]
Hello there,

Here is what I want to achieve:
vector (sink: datadog_logs) > (datadog-agent/)haproxy > datadoghq.eu

Some context:
- I have datadog agents (I am a Datadog customer) sending their metrics to a designated datadog agent with HAProxy (only one machine is authorized to send data to DD platform)
- I have Vector sending digested logs to a Kafka topic, works great

My objective:
- Send the same logs from Vector to the datadog "proxy" that will in its turn send these logs to DD platform

Is this achievable?

This vector config does not work:

```
sink_datadog:
  type: datadog_logs
    site: "datadoghq.eu"
    inputs:
      - my_great_input
    default_api_key: "super_secret_dd_api_key"
    proxy:
      enabled: true
      http: "http://fqdn_for_dd_agent:3838"
```

The 3838 port is found here: https://docs.datadoghq.com/agent/configuration/proxy/?tab=linux#haproxy
HAProxy is configured just like in the official docs, I use default ports.

This is excerpt from `/etc/haproxy/haproxy.cfg`:
```
# This declares the endpoint where your Agents connects for
# sending Logs (e.g the value of "logs.config.logs_dd_url")
# If sending logs with force_use_http: true
frontend logs_http_frontend
    bind *:3838
    mode http
    option tcplog
    default_backend datadog-logs-http
```

Thanks for your help!

**Comment by jszwedko** [comment]
Hi @jgresiak !

The `proxy` configuration in Vector is meant to be used with standard HTTP proxies, HAProxy is more of a load balancer rather than a generic proxy.. I think you want configuration more like:

```yaml
sink_datadog:
  type: datadog_logs
    endpoint: http://fqdn_for_dd_agent:3838"
    inputs:
      - my_great_input
    default_api_key: "super_secret_dd_api_key"
```

(note the use of the HAProxy URL as `endpoint`)

Note that you'll need to configure HAProxy listen and forward the logs specifically. That means configuration like:

```
frontend logs_http_frontend
    bind *:3838 ssl crt <PATH_TO_PROXY_CERTIFICATE_PEM>
    mode http
    option tcplog
    default_backend datadog-logs-http

backend datadog-logs-http
    balance roundrobin
    mode http
    # The following configuration is for HAProxy 1.8 and newer (you'll need to use the EU endpoint)
    server-template mothership 5 agent-http-intake.logs.datadoghq.com:443  check port 443 ssl verify required ca-file <PATH_TO_DATADOG_CERTIFICATES_CRT> check resolvers my-dns init-addr none resolve-prefer ipv4
    # Uncomment the following configuration for older HAProxy versions
    # server datadog agent-http-intake.logs.datadoghq.com:443 check port 443 ssl verify required ca-file <PATH_TO_DATADOG_CERTIFICATES_CRT>
```

This is shown on https://docs.datadoghq.com/agent/configuration/proxy/?tab=linux#haproxy

Alternatively, rather than HAProxy, you could use an actual HTTP proxy like Squid which just accepts and forwards any HTTP requests. This could be used with Vector's `proxy` configuration.

Hope this helps!
