### DISCUSSION TITLE
route to different sinks with different response times

### DISCUSSION THREAD

**Discussion by evanzhang87** [vectordotdev/vector#20845] [Q&A] [answered]
```
sources:
  sourceA:
    type: logstash

transforms:
  dispatcher:
    type: route
    inputs:
      - sourceA
    reroute_unmatched: false
    route:
      r1: .type == "sys"
      r2: .type != "sys"

sinks:
  sinkA: // faster response
    type: kafka
    inputs:
      - dispatcher.r1
  sinkB:  // slower response
    type: kafka
    inputs:
      - dispatcher.r2
```
Will this have a buckets effect?  Will sourceA's response time depend on sinkB?
