### DISCUSSION TITLE
Vector Sidecar data-dir config

### DISCUSSION THREAD

**Discussion by ShahroZafar** [vectordotdev/vector#20860] [Q&A]
We are planning to run vector as a sidecar for some critical application whose load is very high as compared to others. We are doing this to avoid CPU split meaning some pods consuming very large cpu as compared to others.
In the sidecar pattern we can have more than 1 pod running on the same node but we also want to limit that sidecar reads only its own logs so we have this in includes
`"/var/log/pods/{{ $namespace }}_${VECTOR_SELF_POD_NAME}_*/**/*"`

However we want to know how should we configure data-dir. Can we have same data-dir shared between 2 vector pods or we should separate them out.
Also since the include path has pod_name in it, if pod restarts, the path will change. So even if there is 1 pod on 1 node the files which are read will be different. How should we configure data-dir i.e. checkpointing in this case

Configs:

```
data_dir: /vector-data-dir
expire_metrics_secs: 300
acknowledgements:
  enabled: true
api:
  enabled: true
  address: 0.0.0.0:8686
  playground: false
sources:
  kubernetes_logs:
    type: kubernetes_logs
    glob_minimum_cooldown_ms: 5000
    ingestion_timestamp_field: "ingest_timestamp"
    include_paths_glob_patterns:
    - "/var/log/pods/{{ $namespace }}_${VECTOR_SELF_POD_NAME}_*/**/*"
  internal_metrics:
    type: internal_metrics
transforms:
  dedot_keys:
    type: remap
    inputs:
      - kubernetes_logs
    source: |
      . = map_keys(., recursive: true) -> |key| { replace(key, ".", "_") }
sinks:
  prometheus_exporter:
    type: prometheus_exporter
    flush_period_secs: 60
    inputs:
      - internal_metrics
    address: 0.0.0.0:9090
    buffer:
      type: memory
      when_full: block
      max_events: 500
  kafka:
    type: kafka
    bootstrap_servers: kafka:9092
    topic: vector
    batch:
      timeout_secs: 1
      max_bytes: 1000000
      max_events: 4000
    librdkafka_options:
      client.id: "vector"
      request.required.acks: "1"
    message_timeout_ms: 0
    buffer:
      type: memory
      when_full: block
      max_events: 1000
    inputs:
      - dedot_keys
    encoding:
      codec: json
    compression: zstd
```
