### DISCUSSION TITLE
performance

### DISCUSSION THREAD

**Discussion by alex-dengx** [vectordotdev/vector#20912] [General]
Does outputting to two different places at the same time during sinks lead to decreased performance?
My config file is  like this:

```
# Print parsed logs to stdout
sinks:
  elastic_sink:
    type: "elasticsearch"
    inputs: ["json_parser"]
    api_version: "v8"
    auth:
      strategy: "basic"
      user: "elastic"
      password: "password"
    bulk:
      index: "{{ event_name }}_logs"
    endpoints: ["https://10.173.67.100:9200","https://10.173.67.101:9200", "https://10.173.67.102:9200"]
    tls:
      ca_file: "/opt/logstash/config/ca.pem"
      verify_certificate: false
  to_vector:
    type: "vector"
    inputs:  ["json_parser"]
    address: "10.173.67.117:8000"
```

The source I configured comes from Kafka. When it doesn't sink to the next-level vector, there is almost no delay in Kafka. However, after I added a to_vector, the data from Kafka began to experience
