### DISCUSSION TITLE
ERROR vector::topology::builder: Configuration error. error=Sink "azure": OpenSSL error

### DISCUSSION THREAD

**Discussion by Idriel** [vectordotdev/vector#20952] [General]
Getting errors OpenSSL error when trying to use Azure_monitor_logs, using official Docker Debian version

```
sinks:
  azure:
    inputs:
      - demo_logs
    type: azure_monitor_logs
    customer_id: xxxxxxx
    log_type: custom_table_test_1_CL
    shared_key: xxxxxxxx
    time_generated_key: time_generated
    tls:
      verify_certificate: false
```
