### DISCUSSION TITLE
Vector not buffering in case of message_timeout_ms=0

### DISCUSSION THREAD

**Discussion by ShahroZafar** [vectordotdev/vector#20967] [Q&A]
We have a setup where `kubernetes_logs` source is used to read and push logs to kafka via `kafka` sink. In case of outage of kafka, with memory buffer in place. I see that queued messages keeps on increasing instead of storing them to buffer. This leads to continuous memory increase and OOMKill 

Configs are like this

```
    acknowledgements:
      enabled: true
    api:
      address: 0.0.0.0:8686
      enabled: true
      playground: false
    data_dir: /vector-data-dir
    expire_metrics_secs: 300
    sinks:
      kafka:
        batch:
          max_bytes: 1000000
          max_events: 10000
          timeout_secs: 2
        bootstrap_servers: kafka:9092
        buffer:
          max_events: 4000
          type: memory
          when_full: block
        compression: zstd
        encoding:
          codec: json
        inputs:
        - kubernetes_logs
        librdkafka_options:
          client.id: vector
          request.required.acks: "1"
        message_timeout_ms: 0
        topic: ingress
        type: kafka
      prometheus_exporter:
        address: 0.0.0.0:9090
        buffer:
          max_events: 500
          type: memory
          when_full: block
        flush_period_secs: 60
        inputs:
        - internal_metrics
        type: prometheus_exporter
    sources:
      internal_metrics:
        type: internal_metrics
      kubernetes_logs:
        glob_minimum_cooldown_ms: 5000
        include_paths_glob_patterns:
        - /var/log/pods/**/*
        ingestion_timestamp_field: ingest_timestamp
        type: kubernetes_logs
```
