### DISCUSSION TITLE
log_to_metric: I can't set the timestamp

### DISCUSSION THREAD

**Discussion by DePinto** [vectordotdev/vector#20993] [Q&A] [answered]
`log_to_metric` keeps defaulting the output to the current time.  I've tried formatting the input multiple ways:

#### Undesired Output
```
{"name":"foo","namespace":"bar","timestamp":"2024-08-02T20:11:42.262485106Z","kind":"absolute","gauge":{"value":4.299362}}
```

#### Attempt 1
```
{"file":"sourceFile.json","host":"machine","message":{"foo":4.299362},"source_type":"file","timestamp":"2024-07-02T20:10:31.316053532Z"}
```
from https://vector.dev/docs/about/under-the-hood/architecture/data-model/log/

#### Attempt 2
How I normally transform a json log events before sending to `log_to_metric`.
```
{"foo":4.299362,"timestamp":"2024-07-02T20:10:31.316053532Z"}
```

#### Attempt 3
Grasping at straws, I even tried embedding the timestamp in a tag and transforming after the conversion 
```
  transform-correct-timestamp:
    type: remap
    inputs:
      - transform-log-to-metric-json
    source: |
      .name = .tags.correcttimestamp # Just to test if remap is doing anything
      .timestamp = .tags.correcttimestamp
```
```
{
  "name": "2024-07-02T20:10:31.316053532Z",
  "namespace": "bar",
  "tags": {
    "correcttimestamp": "2024-07-02T20:10:31.316053532Z"
  },
  "timestamp": "2024-08-02T20:45:17.633498712Z",
  "kind": "absolute",
  "gauge": {
    "value": 4.299362
  }
}
```
