### DISCUSSION TITLE
Send traces from opentelemetry source to kafka sink

### DISCUSSION THREAD

**Discussion by otani88** [vectordotdev/vector#21018] [Q&A]
Hi everyone. We want to send traces from opentelemetry source to kafka sink with encoding protobuf. Right now it looks like:
```
sources:
    otel_traces:
      type: opentelemetry
      grpc:
        address: 0.0.0.0:4317
      http:
        address: 0.0.0.0:4318

sinks:
    kafka_traces:
      type: kafka
      inputs:
        - otel_traces.traces
      bootstrap_servers: <some_server>
      topic: traces-topic
      encoding:
        codec: protobuf
        protobuf:
          message_type: "opentelemetry.proto.trace.v1.Span"
          desc_file: "/etc/vector/opentelemetry.desc"
      compression: lz4
```

But I get error like:
`2024-08-06T17:20:07.620634Z ERROR vector::cli: Configuration error. error=Data type mismatch between otel_traces.traces (Trace) and kafka_traces (Log)`

Are there some ways to send traces to Kafka? Consumer of kafka topic is quickwit which expected protobuf format for work with OTEL traces.
