### DISCUSSION TITLE
Unable to validate encoding field

### DISCUSSION THREAD

**Discussion by BhautikChudasama** [vectordotdev/vector#21012] [Q&A]
### Issue

```yaml
# ...
sinks:
  my_sink_id:
    type: http
    inputs: ["kubernetes_logs"]
    uri: https://webhook.site/7e7707ca-ce37-464d-8540-e2745c5a3f0c
    encoding:
      codec: json
```

I am getting `Configuration error. error=unknown field encoding.codec` error in validation step.

### version
vector 0.40.0 (x86_64-apple-darwin 1167aa9 2024-07-29 15:08:44.028365803)
