### DISCUSSION TITLE
How to merge multiple lines of logs with special format and drop the other logs?

### DISCUSSION THREAD

**Discussion by shikiroot** [vectordotdev/vector#21026] [Q&A]
Log example:
```
timestamp hostname [pid][file.py][xid][rpc][INFO]:info msg
... lots of INFO ...
timestamp hostname [pid][file.py][xid][rpc][ERROR]:error msg
timestamp hostname [pid][WARNING]:[TRACE][0]Traceback (most recent call last):
timestamp hostname [pid][WARNING]:[TRACE][1]trace msg
timestamp hostname [pid][WARNING]:[TRACE][2]trace msg
... lots of TRACE ...
timestamp hostname [pid][WARNING]:[TRACE][n]Traceback end
timestamp hostname [pid][file.py][xid][rpc][INFO]:info msg
... lots of INFO ...
```
Our requirement is to merge multiple lines of logs with special format into one event and send it to Loki. In this example, we want to drop other logs, and merge the logs from `ERROR` to `Traceback end`, and send it to Loki, how should I write the config file?
Btw, we may also have some single line `ERROR` logs without `TRACE`, and those need to be dropped too.

I've tried the 2 configurations, but they do not work:
```
    multiline:
      start_pattern: "ERROR"
      mode: continue_through
      condition_pattern: "TRACE"
      timeout_ms: 500

    multiline:
      start_pattern: "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2} \\S+ \\[\\d+\\]\\[\\w+\\.py\\]\\[\\d+\\]\\[.*?\\]\\[ERROR\\]:(.*)$"
      mode: halt_before
      condition_pattern: "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2} \\S+ \\[\\d+\\]\\[\\w+\\.py\\]\\[\\d+\\]\\[.*?\\]\\[.*\\]:(.*)$"
      timeout_ms: 500
```

Before the vector, we are using td-agent, the config is like this:
```
<source>
  @type tail
  path /var/log/server/%Y-%m-%d/*.log
  read_from_head true
  pos_file /var/log/td-agent/pos/trace
  tag trace
  <parse>
    @type none
  </parse>
</source>

<filter trace>
  @type grep
  <regexp>
    key message
    pattern /ERROR|TRACE/
  </regexp>
</filter>

<filter trace>
  @type concat
  key message
  separator "\n"
  flush_interval 1
  multiline_start_regexp /ERROR/
  continuous_line_regexp /TRACE/
  multiline_end_regexp /Traceback end/
  timeout_label @NORMAL
</filter>

<label @NORMAL>
  <match>
    @type null
  </match>
</label>

<match trace>
  @type loki
  url ''
  drop_single_key true
  flush_interval 10s
  flush_at_shutdown true
  buffer_chunk_limit 10m
</match>
```
