### DISCUSSION TITLE
How to pass file_key from source to loki sink?

### DISCUSSION THREAD

**Discussion by shikiroot** [vectordotdev/vector#21081] [Q&A] [answered]
a source like this:
```
server_log_all_file:
  type: file
  file_key: path
  include:
    - /var/log/server/*/*/*.log
  ignore_older_secs: 600
  glob_minimum_cooldown_ms: 10000
```
a sink like this:
```
server_log_all_to_loki:
  inputs:
    - server_log_all_file
  type: loki
  encoding:
    codec: text
  endpoint: "http://loki_addr:3100"
  labels:
    logfile: "?"
```
How to set the logfile label?
