### DISCUSSION TITLE
playground. Filter out logs for condition

### DISCUSSION THREAD

**Discussion by agardnerIT** [vectordotdev/vector#21104] [Q&A]
I'm new to VRL and using the playground. I have an input event:

```
{
  "foo": "bar",
  "incoming_status": "INFO"
}
```

I want a rule which ignores (drops) any event where `incoming_status != ERROR`

In other words, I'm expecting output to be `{}` or `None` or `null` (or however VRL represents "nothing").

I can't find anything relevant in the `filter` documentation

**Comment by jorgehermo9** [comment]
I think the `filter` transform with this condition should work like that:

```
transforms:
  my_transform_id:
    type: filter
    inputs:
      - my-source-or-transform-id
    condition: .incoming_status != "ERROR"
```

https://vector.dev/docs/reference/configuration/transforms/filter/
