### DISCUSSION TITLE
How to add additional labels when use `prometheus_scape`?

### DISCUSSION THREAD

**Discussion by zyy17** [vectordotdev/vector#21106] [Q&A]
Here is my `config.toml`:

```toml
[sources.my_prometheus_source]
type = "prometheus_scrape"
endpoints = ["http://localhost:4000/metrics"]
instance_tag = "instance"
endpoint_tag = "endpoint"
honor_labels = true

[sinks.my_database_sink]
type = "prometheus_remote_write"
inputs = ["my_prometheus_source"]
endpoint = "http://localhost:4000/v1/prometheus/write?db=public"
```

If I need some additional labels that are the same as the original prometheus scrape job, for example:

- `job`
- `namespace`
- `container`
...

Can vector support add some additional labels in the `prometheus_scrape` source?

**Comment by zyy17** [comment]
I use the `transforms` to add labels:

```yaml
sources:
  my_prometheus_source:
    type: "prometheus_scrape"
    endpoints:
      - "http://localhost:4000/metrics"
    instance_tag: "instance"
    endpoint_tag: "endpoint"
    honor_labels: true

transforms:
  add_labels:
    type: remap
    inputs:
      - my_prometheus_source
    source: |
      .tags.job = "standalone"

sinks:
  my_database_sink:
    type: "prometheus_remote_write"
    inputs:
      - add_labels 
    endpoint: "http://localhost:4000/v1/prometheus/write?db=public"
```

It would be better if the vector could support adding some additional labels through some kind of K8s discovery if it is running in K8s.
