### DISCUSSION TITLE
How to send vector proto messages via rpc ?

### DISCUSSION THREAD

**Discussion by evanzhang87** [vectordotdev/vector#21253] [General]
Hello, I want to send messages (log messages) to `vector source` with my code, so I tried to use grpc, but it didn't work.
I use `event.proto` and `vector.proto` to generate code.
```

func TestVector(t *testing.T) {
	wrapper := &event_pb.EventWrapper{
		Event: &event_pb.EventWrapper_Log{
			Log: &event_pb.Log{
				Value: &event_pb.Value{
					Kind: &event_pb.Value_RawBytes{
						RawBytes: []byte("hello world"),
					},
				},
			},
		},
	}
	var events []*event_pb.EventWrapper
	events = append(events, wrapper)
	req := vector_pb.PushEventsRequest{
		Events: events,
	}
	addr := "xx.xx.xx.xx:9000"
	conn, err := grpc.NewClient(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatal(err)
	}
	cli := vector_pb.NewVectorClient(conn)

	ctx := context.TODO()
	t.Logf(req.String())
	res, err := cli.PushEvents(ctx, &req)
	if err != nil {
		log.Fatal(err)
	}
	t.Logf(res.String())
}
```
```
// test log

=== RUN   TestVector
    vector_test.go:38: events:{log:{value:{raw_bytes:"hello world"}}}
    vector_test.go:43: 
--- PASS: TestVector (0.01s)
PASS
```
`res.String()` always be "", is that OK? 
```
// vector config
sources:
  vector:
    type: vector
    address: 0.0.0.0:9000
sinks:
  file:
    type: file
    inputs:
      - vector
    path: /var/log/vector/output/vector.log
    encoding:
      codec: json

// vector source prints
{"source_type":"vector","timestamp":"2024-09-10T11:46:43.607741476Z"}
{"source_type":"vector","timestamp":"2024-09-10T11:48:37.998557858Z"}
{"source_type":"vector","timestamp":"2024-09-10T11:51:32.877463923Z"}
```
I can't get raw_bytes.
