### DISCUSSION TITLE
How to get k8s labels as value

### DISCUSSION THREAD

**Discussion by maipal-c** [vectordotdev/vector#21284] [General]
.app_name = .kubernetes.pod_labels.app.kubernetes.io/name
.app_identifier = .kubernetes.pod_namespace + "-" + .app_name

Can please someone confirm how to read values from k8s labels? like the / and . causing issue as a json key

**Comment by jszwedko** [comment]
Try `.kubernetes.pod_labels."app.kubernetes.io/name"`. Field names with special keys need to be quoted.

**Reply by maipal-c** [reply]
it says one argument type cannot be verified.

**Reply by maipal-c** [reply]
app_name = .kubernetes.pod_labels.app
            if app_name == null {
              app_name = .kubernetes.pod_labels."app.kubernetes.io/name"
            }
            if app_name == null {
              app_name = "unknown"
            }
            .app_index = join!([.kubernetes.pod_namespace, app_name, "logs"], separator: "_")
           
thank you this one worked

**Comment by maipal-c** [comment]
one more thing can you please confirm the following config is valid or not

```
sources:
      vault_logs:
         type: kubernetes_logs
         ignore_older_secs: 600
         extra_label_selector: "app.kubernetes.io/component=server,app.kubernetes.io/name=vault"
         node_annotation_fields:
            node_labels: ""
         pod_annotation_fields:
            pod_annotations: ""
            pod_ip: ""
            container_id: ""
            container_image: ""
         namespace_annotation_fields:
            namespace_labels: ""
      # sink data
      apisix_logs:
         type: kubernetes_logs
         ignore_older_secs: 600
         extra_label_selector: "app.kubernetes.io/name=apisix,app.kubernetes.io/component=data-plane"
         node_annotation_fields:
            node_labels: ""
         pod_annotation_fields:
            pod_annotations: ""
            pod_ip: ""
            container_id: ""
            container_image: ""
         namespace_annotation_fields:
            namespace_labels: ""
      kafka_logs:
         type: kubernetes_logs
         ignore_older_secs: 600
         extra_label_selector: "app.kubernetes.io/name=kafka"
         node_annotation_fields:
            node_labels: ""
         pod_annotation_fields:
            pod_annotations: ""
            pod_ip: ""
            container_id: ""
            container_image: ""
         namespace_annotation_fields:
            namespace_labels: ""

```
here i just want to have logs ffrom these 3 deployments. Am i doing correct?

and i guess it clearly not working..
```
2024-09-12T14:30:51.792744Z DEBUG vector::topology::running: Configuring outputs for source. component=vault_logs
2024-09-12T14:30:51.792811Z DEBUG vector::topology::running: Configuring output for component. component=vault_logs output_id=None
2024-09-12T14:30:51.792863Z DEBUG vector::topology::running: Configuring outputs for source. component=apisix_logs
2024-09-12T14:30:51.792902Z DEBUG vector::topology::running: Configuring output for component. component=apisix_logs output_id=None
2024-09-12T14:30:51.792967Z DEBUG vector::topology::running: Configuring outputs for source. component=kafka_logs
2024-09-12T14:30:51.793008Z DEBUG vector::topology::running: Configuring output for component. component=kafka_logs output_id=None
```
