### DISCUSSION TITLE
need help! DONE with vrl

### DISCUSSION THREAD

**Discussion by maipal-c** [vectordotdev/vector#21288] [General]
can anyone please explain what is wrong with my config - 

```
api:
  address: 127.0.0.1:8686
  enabled: true
data_dir: /vector-data-dir
sinks:
  es_cluster:
    auth:
      password: ${ELASTICSEARCH_PASSWORD}
      strategy: basic
      user: ${ELASTICSEARCH_USER}
    bulk:
      index: |
        {{ .app }}-logs-%Y-%m-%d
    endpoints:
    - http://elasticsearch-master-hl.databases.svc.cluster.local:9200
    inputs:
    - add_dynamic_index
    type: elasticsearch
sources:
  k8s_logs:
    ignore_older_secs: 600
    namespace_annotation_fields:
      namespace_labels: ""
    node_annotation_fields:
      node_labels: ""
    pod_annotation_fields:
      container_id: ""
      container_image: ""
      pod_annotations: ""
      pod_ip: ""
    type: kubernetes_logs
transforms:
  add_dynamic_index:
    inputs:
    - k8s_logs
    source: |
      tmp = .kubernetes.pod_owner
      tmp_arr = split!(tmp, "/")
      resource_name = tmp_arr[1]
      if resource_name == null {
         resource_name = "unknown"
      }
      .app = join!([.kubernetes.pod_namespace, resource_name], separator: "-")
    type: remap

```

ALL i want to do is to have seprate index for per deployment/statefullset/replicaset

now the error on vector side - 
```
2024-09-12T20:53:52.823203Z ERROR sink{component_kind="sink" component_id=es_cluster component_type=elasticsearch}:request{request_id=31}: vector::sinks::elasticsearch::service: Response contained errors. error_code="http_response_500" response=Response { status: 500, version: HTTP/1.1, headers: {"x-elastic-product": "Elasticsearch", "content-type": "application/json"}, body: b"{\"error\":{\"root_cause\":[{\"type\":\"json_e_o_f_exception\",\"reason\":\"Unexpected end-of-input in VALUE_STRING\\n at [Source: (byte[])\\\"{\\\"index\\\":{\\\"_index\\\":\\\"monitoring-prom-agent-kube-prometheus-stack-prometheus-shard-1-logs-2024-09-12\\\"; line: 1, column: 99]\"}],\"type\":\"json_e_o_f_exception\",\"reason\":\"Unexpected end-of-input in VALUE_STRING\\n at [Source: (byte[])\\\"{\\\"index\\\":{\\\"_index\\\":\\\"monitoring-prom-agent-kube-prometheus-stack-prometheus-shard-1-logs-2024-09-12\\\"; line: 1, column: 99]\"},\"status\":500}" }
```

error on es cluster - 
```
[2024-09-12T20:54:47,014][WARN ][r.suppressed             ] [elasticsearch-master-0] path: /_bulk, params: {timeout=60s}, status: 500 com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in VALUE_STRING
 at [Source: (byte[])"{"index":{"_index":"gitops-harbor-core-54cc84ff59-logs-2024-09-12"; line: 1, column: 66]
```

both logs have diff pod refrence but its the same error for all pods all logs, no new index at all on es cluster
