### DISCUSSION TITLE
log_to_metric tag expansion

### DISCUSSION THREAD

**Discussion by arch-xtof** [vectordotdev/vector#21352] [General]
I couldn't find any way/example to use `log_to_metric` transformation with dynamic tag names. Having something similar to [label expansion](https://vector.dev/docs/reference/configuration/sinks/loki/#label-expansion) from the Loki sink will be useful. 

This way it would be possible to define labels in this fashion:
```toml
[transforms.count_metrics.metrics.tags]
"*"  = "{{ labels }}"
```
Similarly to Loki:
```toml
[sinks.loki.labels]
"*" = "{{ labels }}"
```

**Comment by arch-xtof** [comment]
Right now I send them to the different transform to achieve this. 
```toml
[transforms.count_metrics_fixed]
  type = "remap"
  inputs = ["count_metrics"]
  source = '''
    .tags = merge(.tags, parse_json!(.tags.other_labels)) ?? .tags
    del(.tags.other_labels)
  '''
```
