### DISCUSSION TITLE
How to refer a nested JSON field in Loki sink's label?

### DISCUSSION THREAD

**Discussion by tiantangkuohai** [vectordotdev/vector#21496] [Q&A] [answered]
Hi vector,
   I try to add a label from a nested json field. But it doesn't working. How can I achieve this? I tried 2 ways, but all failed.

1. 
```
in loki sink configure:

    labels:
        host: "{{ host }}"
        method: "{{ .message.method }}"
        source_type: "{{ source_type }}"
```
2.
```
api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  demo_logs:
    type: demo_logs
    interval: 1
    format: json
transforms:
  my_throttle:
    type: throttle
    inputs:
      - demo_logs
    window_secs: 10
    threshold: 1
  my_remap:
    type: remap
    inputs:
      - my_throttle
    source: ".method = .host"
sinks:
  console:
    inputs:
      - my_throttle
    target: stdout
    type: console
    encoding:
      codec: json
  my_loki_sink:
    type: loki
    healthcheck:
        enabled: false
    encoding:
        codec: json
    labels:
        host: "{{ host }}"
        method: "{{ .method }}"
        source_type: "{{ source_type }}"
    inputs:
      - my_remap
    endpoint: http://loki.domain.com
    tenant_id: vector_test
```
