### DISCUSSION TITLE
docker creds and vectordev

### DISCUSSION THREAD

**Discussion by Andrey250419** [vectordotdev/vector#21554] [General]
Hi, I'm use this vector.yaml:

```
secret:
  clickhouse:
    type: "exec"
    command: [ "cat", "/run/secrets/clickhouse" ]

sources:
  service_logs:
    type: file
    include:
      - "/app/logs/*.log"


transforms:
  prepare_service_logs:
    inputs:
      - "service_logs"
    type: "remap"
    source: |-
      . = parse_json!(string!(.message))

sinks:
  clickhouse_sink:
    type: clickhouse
    auth:
      user: "${LOGS_CLICKHOUSE_USER}"
      password: "SECRET[clickhouse.password]"
      strategy: "basic"
    inputs:
      - prepare_service_logs
    endpoint: "${LOGS_CLICKHOUSE_HOST}"
    database: "${LOGS_CLICKHOUSE_DB}"
    table: "${LOGS_CLICKHOUSE_TABLE}"
    format: "json_as_string"
```
    
    where /run/secrets/clickhouse is: 
    echo "{\"password\": \"${LOGS_CLICKHOUSE_PASSWORD}\"}" | docker secret create clickhouse -
    
    and i get mistake:
    
    ERROR vector::cli: Configuration error. error=Error while retrieving secret from backend "clickhouse": invalid type: string "MY_PASSWORD", expected struct ExecResponse at line 1 column 46.
    
Could you please tell me what is wrong and perhaps there are some best practices for using docker creds in vectordev?
