### DISCUSSION TITLE
Disable context keys in a Kafka source.

### DISCUSSION THREAD

**Discussion by nuekaze** [vectordotdev/vector#21617] [Q&A] [answered]
Hi,

I am using a Kafka source to read data from a topic. I would like to know if there is a way to disable the context fields from being added to the record. The fields offset, partition, source_type and topic. I found at the bottom of the docs page it says that: "By default, the kafka source augments events with helpful context keys.", but I found no way of turning it off. I tried to change the "_key" fields to empty strings in the config but that did not work either.

**Comment by jszwedko** [comment]
Hi @nuekaze ,

You can use the `remap` transform to remove fields you don't want, but setting them to empty string on the source should also work and so, if it isn't, do you mind opening a bug report?

**Comment by mortrevere** [comment, marked as answer]
I can confirm that setting the following seems to remove them all : 
```yaml
      headers_key: ""
      offset_key: ""
      partition_key: ""
      topic_key: ""
      key_field: ""
```
