### DISCUSSION TITLE
Splunk HEC Metrics AggregatedSummary Support

### DISCUSSION THREAD

**Discussion by clmaestas-work** [vectordotdev/vector#21638] [Q&A] [answered]
Good afternoon,

I am testing out vector to see if it fulfill some of our needs. In our tests so far we are going prometheus -> vector -> splunk enterprise. So far it looks like it does what we need it to do, but I've hit one roadblock. It appears the AggregatedSummary metric type is not supported by the splunk_hec_metrics sink. Is this the case, have I not configured it correctly, or am I misreading the error message? 

For example here is the prometheus config:
```
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    static_configs:
      - targets: ['localhost:9090']
```

Here is the vector config:
```
api:
  enabled: true

sources:
  promScrape:
    type: prometheus_scrape
    endpoints:
      - http://localhost:9090/metrics

sinks:
  promToSplunk:
    type: splunk_hec_metrics
    inputs:
      - promScrape
    default_token: [my token]
    endpoint: [my endpoint]
    index: "promvecmetrics"
    tls:
      verify_certificate: false

```

With the above I get the following error:
```
ERROR sink{component_kind="sink" component_id=promToSplunk component_type=splunk_hec_metrics}: vector::internal_events::splunk_hec::sink: Invalid metric received. error="Metric kind not supported." error_type="invalid_metric" stage="processing" value=AggregatedSummary { quantiles: [Quantile { quantile: 0.0, value: 5.0525e-5 }, Quantile { quantile: 0.25, value: 8.2525e-5 }, Quantile { quantile: 0.5, value: 0.000108933 }, Quantile { quantile: 0.75, value: 0.000187652 }, Quantile { quantile: 1.0, value: 0.001971355 }], count: 2869, sum: 0.454619628 } kind=Absolute internal_log_rate_limit=true
```

Because of the `vector::internal_events::splunk_hec::sink: Invalid metric received.`  I assume this means that the `splunk_hec_metrics` sink does not support AggregatedSummary metrics. Is that interpretation correct. I ask because I see the open issue  [Support AggregatedSummary for gcp_stackdriver sink #9530 ](https://github.com/vectordotdev/vector/issues/9530) So I am thinking this may be another case where one of the sinks does not support AggregatedSummary.

If it is a supported metric type could you point me in the direction of a working example?

If it is not supported, is there a workaround to get this metric type through to splunk? I am guessing I would have to transform it, remap it, then send it too `splunk_hec_logs` where I could use the built in `log2metric` sourcetypes.

Finally is there a page I can go to too see all of the supported metric types for each sync for future reference.
