### DISCUSSION TITLE
Aggregator transform on count metrics don't behave as expected

### DISCUSSION THREAD

**Discussion by timtylin** [vectordotdev/vector#21672] [Q&A] [answered]
Using version `0.42.0`

I'm ingesting millions of of log events that I'm transforming into +1 count metrics. These events span over 1 hour. The metric conversion part went smoothly, but then I was hoping to aggregate them into 10 second bins before pushing to the metric server. 

However, during testing I couldn't seem to get the metric aggregation to respect the `interval_ms` setting. I've expected set it to `10_000`, but that seemed to have aggregated *everything* into a single metric. Further playing around with the metric showed that the value I enter into `interval_ms` seem to be treated as "minutes" instead of "milliseconds". For example, if I input a value of `2` for `interval_ms`, all my metrics get aggregated into 2 minute bins. Is this a bug?

Here's the relevant part of my config

```toml
[sources.in]
type = "stdin"

[transforms.alb]
type = "remap"
inputs = ["in"]
source = '''
  . = parse_aws_alb_log!(.message)
  .timestamp = parse_timestamp!(.request_creation_time, "%+")
'''

[transforms.alb_metric]
type = "log_to_metric"
inputs = [ "alb" ]

  [[transforms.alb_metric.metrics]]
  type = "counter"
  field = "elb_status_code"
  name = "load_balancer_request_response"
  namespace = "test"

    [transforms.alb_metric.metrics.tags]
    status = "{{elb_status_code}}"
    target_group = "{{target_group_arn}}"


[transforms.aggregated_alb_metric]
type = "aggregate"
inputs = [ "alb_metric"]
interval_ms = 10_000
```
