### DISCUSSION TITLE
Why don't 429 errors in the sink cause the buffer to fill up?

### DISCUSSION THREAD

**Discussion by tronboto** [vectordotdev/vector#21694] [Q&A]
[vector-repro.zip](https://github.com/user-attachments/files/17622880/vector-repro.zip)

See attached docker config to reproduce this but essentially I have a pipeline with the `demo_logs` source and the `elasticsearch` sink. I'm intentionally setting the write thread pool queue size to 0 in elasticsearch (opensearch) so that 429 errors are returned, or at least 429s are returned in the json response body, which is how elasticsearch does 429s.

At this point, given that I have set `request_retry_partial: true`, I'm expecting to see the `vector_buffer_events` metric go up but it remains at 0. However, if I then stop the opensearch container so that vector can no longer connect, `vector_buffer_events` does start to go up. Why is this?

Additionally, when our elasticsearch cluster is under load and starts returning 429 errors, we're seeing `rate(vector_http_client_requests_sent_total[5m])` for the `elasticsearch` sink continue to rise to huge numbers (see charts below), which isn't what I would expect given that the cluster is under load. From what I can tell, this is then causing bulk indexing tasks to pile up on the cluster, which is something ARC should be helping to avoid.

![image](https://github.com/user-attachments/assets/0a2b0aed-0d34-415f-bd94-648f9d3d8056)

**Comment by jszwedko** [comment]
> I'm intentionally setting the write thread pool queue size to 0 in elasticsearch (opensearch) so that 429 errors are returned, or at least 429s are returned in the json response body, which is how elasticsearch does 429s.

Can you confirm what HTTP status code Elasticsearch returns when returning a "429" response? We do have some logic that looks for "429"s in the response body, but only if the overall HTTP response is reported as successful (2xx): https://github.com/vectordotdev/vector/blob/acea5ae0fdaa5ffd3c90706b07bd34a3dd93f371/src/sinks/elasticsearch/retry.rs#L123-L143

Also, can you share your sink configuration?

**Comment by tronboto** [comment]
Hey @jszwedko. Thanks for getting back on this. Yes, the status code on these is 200. See below for the elasticsearch sink config:

```
  sink_elasticsearch:
    type: elasticsearch
    inputs:
      - transform_remap_set_processing_time
    endpoints:
      - host1
      - host2
      - host3
    api_version: v7
    batch:
      max_bytes: 20971520
    bulk:
      action: create
      index: "{{ '{{' }} es_index {{ '}}' }}-%Y.%m.%d"
    pipeline: ingest-pipeline
    buffer:
      max_events: 100000
    compression: gzip
    tls:
      ca_file: /etc/ssl/certs/ca-bundle.crt
      crt_file: /etc/vector/ssl/vector.cer
      key_file: /etc/vector/ssl/vector.key
    request_retry_partial: true
```
