### DISCUSSION TITLE
Remove file source additional context text

### DISCUSSION THREAD

**Discussion by itayvolo** [vectordotdev/vector#21705] [Q&A] [answered]
Hi,
Im using file source, and im trying to collect log lines from a file as raw as possible.
Seems like the file source adds some "context keys" to the log lines by default, how can I remove them?
Here's an example of it:

- original log lines:

Traceback (most recent call last):
  File "<test>", line 198, in _test_test

- log lines after vector pipeline with file source:

2024-11-05T14:20:03.873658952Z stderr F Traceback (most recent call last):
2024-11-05T14:20:03.873688283Z stderr F
2024-11-05T14:20:03.874434068Z stderr F File "<test>", line 198, in _test_test

**Comment by pront** [comment]
Hi @itayvolo, 

If are you referring the the metadata `2024-11-05T14:20:03.873658952Z stderr F` before the log payload (and assuming you didn't turn on log namespacing) then the log payload is stored at `.message`.

You can use the following to see the console output:
```
schema:
  log_namespace: false

data_dir: /path/to/your/data/dir

sources:
  my_file_source:
    type: file
    include:
      - /path/to/file_source.txt
    read_from: "beginning"

transforms:
  remove_metadata:
    type: remap
    inputs:
      - my_file_source
    source: |
      # Modification happens here
      . = .message

sinks:
  my_console_sink:
    type: console
    inputs:
      - remove_metadata
    encoding:
      codec: json
```
