### DISCUSSION TITLE
Can't get batch working with s3 sink

### DISCUSSION THREAD

**Discussion by extremeandy** [vectordotdev/vector#21799] [Q&A]
I have the following configured in `vector.yaml`:

```yaml
sinks:
  s3:
    type: aws_s3
    inputs:
      - remap_s3_logs
    bucket: my-bucket-name
    batch:
      max_events: 1000000
      timeout_secs: 300
    encoding:
      codec: raw_message
    filename_append_uuid: false
    filename_time_format: "%+"
    key_prefix: "{{ .container_name }}/%Y-%m-%d/{{ .container_name }}-{{ .image_tag }}-"
```

Everything seems to work except the batch config. I am seeing very small files (~3000 lines, ~50kB).

Documentation seems to suggest that [max_bytes](https://vector.dev/docs/reference/configuration/sinks/vector/#batch.max_bytes) is optional, so I didn't set that.

And from what I'm reading, the buffer size should be independent of the batch size, so I didn't configure anything there either.

Am I missing something?

**Edit**: Setting `max_bytes: 500000000` resolved this for me, though docs claim this is optional.
