### DISCUSSION TITLE
vector protobuf encoding uses 3x CPU compared to JSON encoding

### DISCUSSION THREAD

**Discussion by nmiculinic** [vectordotdev/vector#21863] [Q&A]
Image: timberio/vector:0.42.0-debian

I was very surprised when I switch kafka encoding to protobuf from JSON having 4.5x increase in CPU usage. Config:

```yaml
  kafka:
    compression: gzip
    encoding:
      codec: protobuf
      protobuf:
        desc_file: proto.desc
        message_type: <>
    batch:
      max_bytes: 1048576 # 1MiB
      max_events: 100
      timeout_secs: 1

```

with proto being (simple string key/value fields):

```proto
message LogRecord {
  ...

  // log message. 
  string message = 3;
  // log level (e.g. info, warn, error, debug)
  string level = 4;

  
   ...

  // timestamp in unix_ns
    google.protobuf.Timestamp timestamp = 24;
}
```

So yeah, I'm not sure what's happening here, or how to get performance in line with plain JSON shemaless encoding
