### DISCUSSION TITLE
transform output square brackets

### DISCUSSION THREAD

**Discussion by RFskynet** [vectordotdev/vector#21874] [Q&A] [answered]
Hi. Please tell me, can I wrap the output-transform in square brackets? This is the format my application requires.
Example:
invalid
{
"json": "json 1"
}

That's right, that's the only way
 [{
	"json": "json 1"
}]
Thanks!

**Comment by pront** [comment]
You can use a remap [like so](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiLiA9IFsuXSIsImV2ZW50Ijp7Im1lc3NhZ2UiOiJIZWxsbyBWUkwiLCJmb28iOiJkZWxldGUgbWUiLCJodHRwX3N0YXR1cyI6IjIwMCJ9LCJpc19qc29ubCI6ZmFsc2UsImVycm9yIjpudWxsfQ%3D%3D). BTW wrapping the top level output in an array `[{/* ... */}]` has different semantics vs `{}`.

**Reply by RFskynet** [reply]
Thank you. But for some reason it doesn't work in my case. Returns the same thing.
1. Example:
. = [.] not work
before
`{
	"message": "Hello VRL",
	"foo": "delete me",
	"http_status": "200"
}`
after
`{
	"message": "Hello VRL",
	"foo": "delete me",
	"http_status": "200"
}`

If .test = [.] it works like this
{"test": [
		{
			"foo": "delete me",
			"http_status": "200",
			"message": "Hello VRL"
		}
	]
}

2. could you give me more information about this

> BTW wrapping the top level output in an array [{/* ... */}] has different semantics vs {}

**Reply by pront** [reply]
1. Can you share a VRL playground link?
2. See [mapping one log into multiple](https://vector.dev/highlights/2021-07-16-remap-multiple/)

**Reply by RFskynet** [reply]
1. аналогично вашему [example](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiLiA9IFsuXSIsImV2ZW50Ijp7ImFubm90YXRpb25zIjp7InN1bW1hcnkiOiJ0ZXN0In19LCJpc19qc29ubCI6ZmFsc2UsImVycm9yIjpudWxsfQ%3D%3D)

My config:
```
[sources.files]
type = "file"
include = [ "/etc/vector/log1.log" ]

[transforms.vector-transform]
inputs = ["files"]
type = "remap"
source = """
. = [.]
"""
[sinks.file_output]
type = "file"
inputs = ["vector-transform"]
path = "/etc/vector/log2.log"
encoding.codec = "text"
```

Input log1.log -> {"annotations":{"summary":"test"}}
Output log2.log **without square brackets** -> {"annotations":{"summary":"test"}}

**Reply by jszwedko** [reply, marked as answer]
Correct, if an array is emitted by a `remap` transform than each element is then emitted as a separate event per [mapping one log into multiple](https://vector.dev/highlights/2021-07-16-remap-multiple/).

I think here you may want to actually do the encoding in `remap` to avoid this. Something like:

```toml
[sources.files]
type = "file"
include = [ "/etc/vector/log1.log" ]

[transforms.vector-transform]
inputs = ["files"]
type = "remap"
source = """
. = {"message": encode_json([.])}
"""
[sinks.file_output]
type = "file"
inputs = ["vector-transform"]
path = "/etc/vector/log2.log"
encoding.codec = "text"
```

Using the `text` codec should result in only the `message` field being output.
