### DISCUSSION TITLE
Kafka source low throughput

### DISCUSSION THREAD

**Discussion by Arty-Maly** [vectordotdev/vector#21880] [Q&A]
Hello, I have created a simple Vector pipeline that looks like this: Kafka -> Remap -> Kafka. 

I am noticing a low amount of messages coming from the Kafka source no matter what configuration I set or the amount of partitions I have. The amount of events in bytes emitted looks to be ~1MB per second. 

The utilization of my remap is low as well. Around  0.1. The rate is the same if I have lag or not (Kafka Broker has more messages in its queue)

Now my Pipeline can keep up with the Kafka source queue if there are no hiccups in the system. If I restart Vector and let lag build up, Vector will not be able to clear it. 

I have also tried to verify the bottleneck is in the Kafka Source and just tried a pipeline in the form of: 
1 )Kafka -> Black Hole
2) Kafka -> Remap -> Black Hole 

Both of those designs have the same symptoms. Kafka source returning emitting a low number of events to the next step. 

Acknowledgements are turned on and setting or removing the `encoding: json` in the source doesnt make a difference.

A simple example of my pipeline would be: 

```
sources:
      kafka:
         type: kafka
         topics: "my-topic"
         bootstrap_servers: "my.server:port"
         group_id: "my-group"
     transforms:
        extract:
            type: remap
            inputs:
               - kafka
            source: |
                . = parse_json!(.)
        sinks:
             emit_to_kafka:
             inputs: 
                 - extract
             ....
```

I have tried setting the kafka options in the source: `fetch.max.bytes, max.poll.records` and broker options as well. 
The only setting to have a difference was `fetch.wait.max.ms` but that just increased/decreased overall request rate with the amount of data returned over a period staying the same. 

Is there anything that I am missing or need to verify as to why my kafka source is not saturating my pipeline?
