### DISCUSSION TITLE
Metrics filters are not working properly

### DISCUSSION THREAD

**Discussion by uni-pooja-laad** [vectordotdev/vector#21890] [Q&A] [answered]
Hi team
Please see the last support chat:
https://discord.com/channels/742820443487993987/1285180794381275157/1285180794381275157
By latest suggrestion I got that I can use OR condition to get multiple prefix metrics.
My ask here is I just need metrics starting with either cpu.* or  kong.* or mem.*
I am trying this remap:
```
filter_metrics:
    type: filter
    inputs: [datadog_agent.metrics]
    condition: 
       type: vrl
       source: match!(to_string(.name) ?? "default", r'^(cpu.*|kong.*|mem.*)')
```

Error is : 
```
2024-11-26T07:20:11.641948Z ERROR vector::topology::builder: Configuration error. error=Transform "filter_metrics":
error[E620]: can't abort infallible function
  ┌─ :1:1
  │
1 │ match!(to_string(.name) ?? "default", r'^(cpu.*|kong.*|mem.*)')
  │ ^^^^^- remove this abort-instruction
  │ │
  │ this function can't fail
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples
```

Also tried this (tostring() function correction):
```
filter_metrics:
    type: filter
    inputs: [datadog_agent.metrics]
    condition: 
       type: vrl
       source: match!(tostring(.name) ?? "default", r'^(cpu.*|kong.*|mem.*)')
```

Error is:
```
2024-11-26T07:35:26.637294Z ERROR vector::topology::builder: Configuration error. error=Transform "filter_metrics":
error[E105]: call to undefined function
  ┌─ :1:8
  │
1 │ match!(tostring(.name) ?? "default", r'^(cpu.*|kong.*|mem.*)')
  │        ^^^^^^^^
  │        │
  │        undefined function
  │        did you mean "to_string"?
  │
  = learn more about error code 105 at https://errors.vrl.dev/105
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples

```
