### DISCUSSION TITLE
sampling not working as expected for custom field

### DISCUSSION THREAD

**Discussion by yjagdale** [vectordotdev/vector#21904] [General]
Hello team,

I am getting data on socket(TCP) and trying to sample data based on hostname. here is the example yaml
```yaml
sources:
  tcp_514:
    type: socket
    address: 0.0.0.0:514
    mode: TCP

transforms:
  sample_based_on_hostname:
    type: sample
    inputs:
      - tcp_514
    rate: 2000
    key_field: host

sinks:
  console:
      type: console
      encoding:
        codec: json
      inputs:
        - sample_based_on_hostname
```
m I missing anything?
