### DISCUSSION TITLE
Elastic search to send metrics

### DISCUSSION THREAD

**Discussion by uni-pooja-laad** [vectordotdev/vector#21948] [Q&A] [answered]
Hi team,
I am using sink: elasticsearch (https://vector.dev/docs/reference/configuration/sinks/elasticsearch/) to send logs to opensearch and they are working fine using below configuration:

```
opensearch-dev:
 sink:
        type: elasticsearch
        inputs: [output_opensearch_logs]
        api_version: v7
        compression: none
        doc_type: _doc
        endpoints:
          - https://endpooint:port
        auth:
          strategy: "basic"
          user: ""
          password: ""
        tls:
          verify_certificate: false
        mode: bulk
        bulk:
            index: "vector"
        batch:
          max_bytes: 100
          max_events: 5000
          timeout_secs: 11
```

I want to send metrics as well to opensearch. Will elasticsearch will be able to do?
Or is there any other way to send metrics?
