### DISCUSSION TITLE
Internal Metrics transforms question

### DISCUSSION THREAD

**Discussion by satellite-no** [vectordotdev/vector#21994] [Q&A] [answered]
Hi All! 

Im trying to utilize the `internal_metrics` source and send that externally but it appears it does not behave similar to other sources when using transforms.  Like I pipe `internal_metrics` > `default_transform` (adds field) > `console` that field is not there.  Whne I use the exact same transforms on the `demo_log` source it works as execpted.  Any guidance?  

Test config for replicate.

```yaml
sources:
  demo_log:
    type: demo_logs
    format: apache_common

  internal_metrics:
    type: "internal_metrics"


transforms:
  default_transform:
    type: remap
    inputs:
      - "internal_metrics"
    source: >-
      .app_id = "100000000"

sinks:
  console:
    type: console
    inputs:
      - "default_*"
    target: stdout
    encoding:
      codec: json
```
