### DISCUSSION TITLE
Error when trying to configure buffering

### DISCUSSION THREAD

**Discussion by hightwoltt** [vectordotdev/vector#22087] [Q&A] [answered]
I'm trying to set up buffering, in case the intermediate Vector host is unavailable. 
Below is my sinks configuration:
```
sinks:

  intermediary_vector:
    type: vector
    inputs:
      - add_host

   buffer:
      type: disk
      max_size: 1GiB
      when_full: block
    address: "192.168.8.103:9009"
```

After restarting the Vector container, I get the error:
`ERROR vector::cli: Configuration error. error=did not find expected key at line 46 column 4, while parsing a block mapping at line 41 column 3`

Please tell me what could be the reason? or how to do buffering in a different way? Thanks!

**Comment by jszwedko** [comment]
Hi @hightwoltt ,

I think the issue here is with YAML indentation. The line with `buffer:` needs to have one more leading space.

**Reply by pront** [reply, marked as answer]
Yes, try:

```
sinks:

  intermediary_vector:
    type: vector

    inputs:
      - add_host

    address: "192.168.8.103:9009"

    buffer:
      type: disk
      max_size: 1GiB
      when_full: block
```
