### DISCUSSION TITLE
Prometheus Remote Write Sink Timestamp

### DISCUSSION THREAD

**Discussion by BinjaFan** [vectordotdev/vector#22092] [Q&A]
Hello,

I’m currently testing a setup where:

- Vector A sends metrics to a Kafka topic.  
- Vector B consumes those metrics from Kafka.  
- Vector B then writes them remotely to Prometheus.  

Here’s the issue:  
- When Prometheus is unavailable for a while, Vector doesnt acknowledges messages in kafka (which what i expect with acknowledgements set to true)
- Vector acknowledges metrics in Kafka as soon as Prometheus becomes available again.  
- Although it looks like Vector is sending the data, I see gaps in Prometheus for the period when it was down.  
- I’m not sure if Vector is sending the original timestamps to Prometheus or not or it is something on prometheus side.

I believe Vector should handle it since i tested the same thing using prometheus agent and it works without any issue.

Could someone please help me figure out how to preserve these timestamps so I don’t have gaps?

Below is my Vector B configuration:  
```
---
sources:
  metrics:
    type: kafka
    bootstrap_servers: localhost:19092
    topics:
      - metrics
    group_id: metrics
    decoding:
      codec: native
    acknowledgements:
      enabled: true

sinks:
  rw:
    type: prometheus_remote_write
    inputs:
      - metrics
    endpoint: http://localhost:9090/api/v1/write
    batch:
      timeout_secs: 30 ## send data every 30 seconds
    healthcheck:
      enabled: false
    acknowledgements:
      enabled: true
```
