### DISCUSSION TITLE
Get compression working with aws_s3 sink (files uncompressed)

### DISCUSSION THREAD

**Discussion by mblarsen** [vectordotdev/vector#22105] [Q&A] [answered]
I'm having a hard time getting compression to work with the aws_s3 sink when using batch. Batching works just fine, but the uploaded file is always uncompressed.

This is my configuration

```yaml
sinks:
  amplitude_backup_s3:
    batch:
      max_bytes: 5242880
      timeout_secs: 300
    bucket: my-bucket
    buffer:
      max_size: 268435488
      type: disk
      when_full: block
    compression: gzip
    encoding:
      codec: json
    filename_append_uuid: false
    filename_extension: json.gz
    key_prefix: "year=%Y/month=%m/day=%d/ts="
    inputs:
      - amplitude_backup_source
    region: eu-central-1
    storage_class: INTELLIGENT_TIERING
    type: aws_s3

sources:
  amplitude_backup_source:
    address: 0.0.0.0:8080
    encoding: json
    type: http
    path: /2/httpapi
```

I'm using `timberio/vector:latest-alpine` docker image so I don't know the exact vector version. But fairly recent I would guess.
