### DISCUSSION TITLE
Errors when configuring the vector buffer

### DISCUSSION THREAD

**Discussion by hightwoltt** [vectordotdev/vector#22122] [Q&A]
My Vector is running in a Docker container, and when I try to configure buffering, I get these errors:
there is only 1 vector container on the host, I've tried different options with **drop_newest** and **block** combined with different types of buffering. Vector works fine, but if I write `docker exec -it vector bash` and write the `vector` command in the container, I get the following errors.

When configuring the buffer on disk:
**Conf**
```
sinks:

  intermediary_vector:
    type: vector
    inputs:
      - add_host
    address: "192.168.1.103:9009"

    buffer:
      - type: disk
	max_size: 1073741824
        when_full: drop_newest
```

**Error**:
`ERROR vector::topology::builder: Configuration error. error=Sink "intermediary_vector": error occurred when building buffer: failed to build individual stage 0: failed to load/create ledger: failed to lock buffer.lock; is another Vector process running and using this buffer?`

The `buffer.lock` file also appears in the container in the `/var/lib/vector/buffer/v2/intermediary_vector` directory. Deleting it doesn't help.

When configuring the buffer in memory:
**Conf**
```
sinks:

  intermediary_vector:
    type: vector
    inputs:
      - add_host
    address: "192.168.1.103:9009"

    buffer:
      - type: memory
        max_events: 5000
        when_full: drop_newest
```

**Error:**
```
ERROR vector::internal_events::socket: Error binding socket. error=error creating server listener: Address already in use (os error 98) error_code="socket_bind" error_type="io_failed" stage="receiving" mode=tcp internal_log_rate_limit=true
ERROR vector::app: An error occurred that Vector couldn't handle: error creating server listener: Address already in use (os error 98).
```
I will be very grateful for your help in solving this problem!
