### DISCUSSION TITLE
How to handle long log lines

### DISCUSSION THREAD

**Discussion by trahim** [vectordotdev/vector#22128] [Q&A]
Hi, I'm having issues using the file source and having my logs being truncated when they are longer log lines and subsequently having issues with parsing it. For context my message is essentially just a json string. 

Below is my config for my source and my transform I am using.

```yaml
    sources:
      tail_logs:
        data_dir: /vector-data-dir
        exclude:
        - /var/log/containers/vector-agent*.log
        - /var/log/containers/vector-aggregator*.log
        fingerprint:
          strategy: device_and_inode
        ignore_older_secs: 86400
        include:
        - /var/log/containers/*.log
        type: file
        max_line_bytes: 1024000
    transforms:
      content_logging_only:
        condition:
          source: |-
            remove_stdout, err = split(.message, r'stdout [a-zA-Z] ')[1]
            parsed_json, err = parse_json(remove_stdout)
            if err != null { log(remove_stdout, level: "error") }
            parsed_json.logType == "Special.Logger"
          type: vrl
        inputs:
        - tail_logs
        type: filter
```
In the log I've put in I can see the log get split into 2 in the agent logs.

Any ideas what I need to do? I couldn't find appropriate docs for this

**Comment by jszwedko** [comment]
Is it possible that the input log is split over multiple lines? Are you able to find it in the `.log` files?

**Reply by trahim** [reply]
Just checked and yup I can see the log is being split into separate lines. I'll have look as to why and then see how it interacts with this and mark as the answer is sorted. Thanks

**Reply by jszwedko** [reply]
👍 if needed, you can use the `reduce` transform in Vector to recombine lines into one event.

**Reply by trahim** [reply]
So had a play with the code locally and seems to split when deployed. For more context this is in kubernetes so likely because of [this ](https://stackoverflow.com/questions/61360759/logging-with-docker-and-kubernetes-logs-more-than-16k-split-up)and we had [this ](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing)setup in fluent bit.  Is there is vector equivalent or do we need to use the kube or docker source?

**Reply by jszwedko** [reply]
I believe `kubernetes_logs` source automatically recombines lines split by the container runtime, but not anything past that (which is where the `reduce` transform comes in). This is mentioned on https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#partial-message-merging.

**Reply by trahim** [reply]
Gotcha, thanks I'll take a look on setting it up. I'm guessing we don't have a guide for this as it would be log dependent? Like the ruby example?

**Reply by jszwedko** [reply]
Right, it depends on the input (same as fluentbit).

**Reply by trahim** [reply]
So I've carried on playing with this sorted out issues with reduce for anyone who may look at this in the future looking for advice I've attached my updated config.
```yaml
    sources:
      tail_logs:
        data_dir: /vector-data-dir
        exclude:
        - /var/log/containers/vector-agent*.log
        - /var/log/containers/vector-aggregator*.log
        fingerprint:
          strategy: device_and_inode
        ignore_older_secs: 86400
        include:
        - /var/log/containers/*.log
        type: file
        max_line_bytes: 1024000
    transforms:
      combine_long_lines:
        type: reduce
        group_by:
        - file
        inputs:
        - tail_logs
        merge_strategies:
          message: concat_raw
        starts_when:
            type: vrl
            source: match(string!(.message), r'^[1-2]\d{3}-(0[1-9]|1[0-2])-(3[0-1]|[1-2]\d|0[1-9])T(0\d|[0-2][0-9])(:[0-5]\d){2}.\d{9}Z (stdout|stderr) [a-zA-Z] \{"@timestamp":')
      content_logging_only:
        condition:
          source: |-
            remove_stdout, err = split(.message, r'stdout [a-zA-Z] ')[1]
            parsed_json, err = parse_json(remove_stdout)
            if err != null { log(remove_stdout, level: "error") }
            parsed_json.logType == "Special.Logger"
          type: vrl
        inputs:
        - tail_logs
        type: filter
```      

But I now seem to have a different issue when I am trying to parse this and split it to work with the JSON string(strip out the timestamp and stdout/stderr from the message) it seems to truncate it again. Is there a size limit to strings? Or is there a better way to strip that out so I can parse the message json string? 

This is my additional transformation

```yaml
parse:                                                                                                                                                                                                                                         
  type: remap                                                                                                                                                                                                                                  
  inputs:                                                                                                                                                                                                                                      
  - content_logging_only                                                                                                                                                                                                                       
  source: |-                                                                                                                                                                                                                                     
    .message = split!(.message, r'(stdout|stderr) [a-zA-Z] ')[1]
```
