### DISCUSSION TITLE
Adding fields to metrics doesnt work, only updating existing one.

### DISCUSSION THREAD

**Discussion by robinpecha** [vectordotdev/vector#22133] [Q&A] [answered]
Hi, I have following config where I need to add some fields to metric. 
```
sources:
   hostmetrics_local:
    type: host_metrics
    scrape_interval_secs: 30

transforms:
  host_metrics_local_remap:
    inputs: [ "hostmetrics_local" ]
    type: "remap"
    source: |
      .namespace = "my_company"
      .maintainer = "maintainer"
      .source_cat = "source_cat"

sinks:
  blackhole:
    type: blackhole
    inputs: 
      - host_metrics_local_remap
```
And this is output from vector tap, no fields was added, only namespace was updated.
```
{"name":"load5","namespace":"my_company","tags":{"collector":"load","host":"be7de7baa9db"},"timestamp":"2025-01-07T14:51:11.606623331Z","kind":"absolute","gauge":{"value":0.2490234375}}
 ```
 Please how to add fields to metrics?
 Thank you.
