### DISCUSSION TITLE
Vector source through GKE Gateways

### DISCUSSION THREAD

**Discussion by elwinar** [vectordotdev/vector#22131] [Q&A]
I can't get the _vector_ source to work through the GKE's Gateway.

The aggregator configuration is:

```
api:
  enabled: true
  address: 0.0.0.0:8686

sources:
  in:
    type: vector
    address: 0.0.0.0:8080
    tls:
      enabled: false

sinks:
  out:
    type: blackhole
    inputs:
    - in
```

and is exposed via a service and a httproute (the API is enabled for the healthcheck policy).

Trying to send dummy logs to it with the following configuration :

```
sources:
  in:
    type: "stdin"

sinks:
  out:
    type: vector
    inputs:
      - "in"
    address: https://hostname
```

results in the following log line:

```
2025-01-07T08:03:49.027306Z ERROR vector::topology::builder: msg="Healthcheck failed." error=Request failed: status: Unknown, message: "h2 protocol error: http2 error: connection error detected: frame with invalid size", details: [], metadata: MetadataMap { headers: {} } component_kind="sink" component_type="vector" component_id=out
```

(Relevant logs with debug enabled: [vector-log.txt](https://github.com/user-attachments/files/18329557/vector-log.txt))

I get that I probably misconfigured something, but I can't find it out. I've tried port-forwarding the service locally to rule out missconfiguration of the source/sink and it's working properly, so it's probably the Gateway shitting the bed.

My current gateway is defined as follows:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: default
  annotations:
    networking.gke.io/certmap: "${certmap}"
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
```

The one listener does TLS termination for me.

I ended up switching to the _http_server_ source to bypass the issue for now, I'll come back to it later. In the meantime, I would welcome any pointer or example if someone got it working.
