### DISCUSSION TITLE
采集socket源消息,怎么消除换行符

### DISCUSSION THREAD

**Discussion by papapy** [vectordotdev/vector#22141] [Q&A] [answered]
例如以下消息体message追加的\n
{
  "host": "10.33.210.7",
  "message": "hello world\n",
  "port": 40322,
  "source_type": "socket",
  "timestamp": "2025-01-08T03:20:17.637566208Z"
}

**Comment by jszwedko** [comment]
Can you share the configuration for the `socket` source?

**Reply by papapy** [reply]
```
sources:
  dummy_logs:
    type: socket
    address: 0.0.0.0:55555
    mode: udp

sinks:
  file:
    type: file
    inputs: ["dummy_logs"]
    path: demo-%Y-%m-%d.log
    encoding: 
      codec: raw_message
  print:
    type: "console"
    inputs: ["dummy_logs"]
    encoding:
      codec: "json"
      json:
        pretty: true
```

**Reply by papapy** [reply]
然后使用nc -u x.x.x.x 55555发送的消息

**Reply by jszwedko** [reply, marked as answer]
Got it, thanks! Yes, sending a message that ends with a newline with `nc` will result in Vector receiving the message with a newline. You can use a `remap` transform to trim it like:

```
sources:
  dummy_logs:
    type: socket
    address: 0.0.0.0:55555
    mode: udp

transforms:
    trim:
        type: remap
        inputs: ["dummy_logs"]
        source: |
            .message = strip_whitespace!(.message)

sinks:
  file:
    type: file
    inputs: ["trim"]
    path: demo-%Y-%m-%d.log
    encoding: 
      codec: raw_message
  print:
    type: "console"
    inputs: ["trim"]
    encoding:
      codec: "json"
      json:
        pretty: true
```

See https://vector.dev/docs/reference/configuration/transforms/remap/ for additional details.
