### DISCUSSION TITLE
aws_ecs_metrics source - invalid type: null, expected struct ContainerStats

### DISCUSSION THREAD

**Discussion by winadm87** [vectordotdev/vector#22185] [General]
Good day.
Tried to configure vector to gather ECS task metrics but got an error:
`
ERROR source{component_kind="source" component_id=source_aws_ecs_metrics component_type=aws_ecs_metrics}: vector::internal_events::aws_ecs_metrics: Parsing error. endpoint=http://169.254.170.2/v3/f4275bb6-2577-45f4-8500-49c6f5fa28ad/task/stats error=Error("invalid type: null, expected struct ContainerStats", line: 1, column: 72) stage="processing" error_type="parser_failed" internal_log_rate_limit=true
`

Vector configuration:
`
sources:
...
  source_aws_ecs_metrics:
    type: aws_ecs_metrics
    scrape_interval_secs: 15
    version: v4
...
`

In a deployed vector container, I can observe environments
`
ECS_CONTAINER_METADATA_URI=http://169.254.170.2/v3/f4275bb6-2577-45f4-8500-49c6f5fa28ad
ECS_CONTAINER_METADATA_URI_V4=http://169.254.170.2/v4/f4275bb6-2577-45f4-8500-49c6f5fa28ad
`

The versions:
EC2: AWS amz linux 2, amzn2-ami-ecs-hvm-2.0.20250102-x86_64-ebs
ECS agent: "Starting Amazon ECS Agent" version="1.89.2" commit="41d593c6"
Vector.dev: "timberio/vector:0.43.1-debian"

Questions:
1. If I have specify v4 in source - and vector can see env ECS_CONTAINER_METADATA_URI_V4 - why does it try to use v3 endpoint? In the [doc](https://vector.dev/docs/reference/configuration/sources/aws_ecs_metrics/#version) it is specified that v4 in that case should be used
2. I can curl to http://169.254.170.2/v3/f4275bb6-2577-45f4-8500-49c6f5fa28ad/task/stats and get payload from ec2 instance itself and from any container in the ECS task. Unfortunately, I can't check if this endpoint is available from vector container. But if endpoint is available from other containers - I assume that it is available from vector container too. The question why it sees null instead of payload.

**Comment by pront** [comment]
Can you share your config? (please redact any sensitive data first)

**Comment by winadm87** [comment]
```
sources:
  source_vector_metrics:
    type: internal_metrics

  source_vector_internal_logs:
    type: internal_logs

  source_aws_ecs_metrics:
    type: aws_ecs_metrics
    scrape_interval_secs: 15
    version: v4

  source_docker_logs:
    type: docker_logs
    docker_host: unix:///var/run/docker.sock

transforms:
  transform_vector_internal_logs:
    type: remap
    inputs:
      - source_vector_internal_logs
    source: |-
      .level = .metadata.level

  transform_docker_logs_add_level_label:
    type: remap
    inputs:
      - source_docker_logs
    source: |-
      .level = parse_regex(.message, r'.*level=(?P<level>[a-zA-Z]+).*') ?? "false"
      if !exists(.level.level) {
        .level = { "level": "empty" }
       }

  transform_docker_logs_reduce_error_message:
    type: reduce
    inputs:
      - transform_docker_logs_add_level_label
    group_by:
      - container_name
    merge_strategies:
      message: concat_newline
    starts_when:
      type: "vrl"
      source: .level.level != "empty"
    expire_after_ms: 1000

sinks:
  sink_prometheus_exporter:
    type: prometheus_exporter
    inputs:
      - source_vector_metrics
      - source_aws_ecs_metrics

  sink_vector_logs:
    type: loki
    inputs:
      - transform_vector_internal_logs
    endpoint: <sensitive_data>
    encoding:
      codec: json
    labels:
      prometheus: ${<sensitive_data>}
      container: vector
      level: "{{ .level }}"
    auth:
      user: <sensitive_data>
      password: ${<sensitive_data>}
      strategy: basic
    healthcheck: false

  sink_docker_logs:
    type: loki
    inputs:
      - transform_docker_logs_reduce_error_message
    endpoint: <sensitive_data>
    encoding:
      codec: raw_message
    labels:
      prometheus: ${<sensitive_data>}
      container: "{{ .container_name }}"
      level: "{{ .level.level }}"
    auth:
      user: <sensitive_data>
      password: ${<sensitive_data>}
      strategy: basic
    healthcheck: false
```
