### DISCUSSION TITLE
vector-agent with multiple vector_sinks

### DISCUSSION THREAD

**Discussion by jsbloo** [vectordotdev/vector#22189] [General]
Hello,
I have a vector agent, I want it to have N vector_sinks.
The vector port on my vector aggregators is 6000,
when I have a config like (in my agent customConfig): 

```
sinks:
  vector_sink_1:
    type: vector
    inputs: [k8_logs]
    address: vector.ns1.svc.cluster.local:6000
  vector_sink_2:
    type: vector
    inputs: [k8_logs]
    address: vector.ns2.svc.cluster.local:6000
   ```

I get a fatal kubernetes error , saying that I cannot have duplicate port numbers? 
Seems the way the helm-chart is configured is wrong? I can maybe just ignore the error, but it worries me.

It still deploys and seems to work, but how do I get around it? I cannot see ANY examples, showing this usecase am I doing something wrong?
