### DISCUSSION TITLE
Disable Buffer for Kafka Source to Clickhouse Sink

### DISCUSSION THREAD

**Discussion by seilerre** [vectordotdev/vector#22197] [Q&A]
I got a Vector config where I am writing from kafka to clickhouse. As Kafka is supposed to persist events and hand them to the consumer (Vector) in a reasonable pace, I would like to disable the buffer in Vector, so that when Vector is too slow to consumer a consumer lag is build in Kafka. Is this a bad idea? In my Clickhouse sink I tried to set:

```yaml
        buffer:
          max_events: 0
          type: memory
```

This however produces a config error.
