### DISCUSSION TITLE
[Splunk][JournalD] Missing journald metadata fields

### DISCUSSION THREAD

**Discussion by MC13-cmd** [vectordotdev/vector#22204] [General]
Hi, I'm using vector to get the journald logs from splunk universal forwarder that I collect using Journald input: https://docs.splunk.com/Documentation/Splunk/9.3.2/Data/CollecteventsfromJournalD. 

Here is my Splunk output config:
```
[tcpout]
defaultGroup = vector

[tcpout:vector]
server = 10.12.2.22:8088
sendCookedData = false
format = raw
metadata = true
```

Here is my vector config:
sources:
```
  splunk_input:
    type: "socket"
    address: "0.0.0.0:8088"
    mode: "tcp"
    decoding:
      codec: "bytes"

sinks:
  console_out:
    type: "console"
    inputs: ["splunk_input"]
    encoding:
      codec: "json"
```

Its working but in the console I can see only log messages without journald metadata fields like TRANSPORT, that splunk forwarder adds to the logs. I can see these metadata fields when I send logs directly to Splunk indexer. How can I see the Splunk metadata fields in Vector?
