### DISCUSSION TITLE
I think the checksum ignores duplicated data when reading the source file, but can I also receive duplicated data?

### DISCUSSION THREAD

**Discussion by dpa456** [vectordotdev/vector#22229] [Q&A]
I'm intentionally trying to upload duplicate data, is it possible?

vector sources code
```
sources:
      container_log_source:
        encoding:
          charset: utf-8
        include:
        - log.log
        line_delimiter: \n
        oldest_first: true
        read_from: beginning
        type: file
```

This is sample data.
```
{"log_type":"log","location":{"x":163.79275512695312,"y":-294.9390869140625,"z":92.150016784667969},"account_id":"96ba3bfc"}
{"log_type":"log","location":{"x":163.79275512695312,"y":-294.9390869140625,"z":92.150016784667969},"account_id":"96ba3bfc"}
{"log_type":"log","location":{"x":163.79275512695312,"y":-294.9390869140625,"z":92.150016784667969},"account_id":"96ba3bfc"}
```
