### DISCUSSION TITLE
Significant metric loss when using Vector's log_to_metric vs Datadog for nginx logs

### DISCUSSION THREAD

**Discussion by law** [vectordotdev/vector#22309] [Q&A]
I'm experiencing a significant discrepancy between metrics generated via Vector's log_to_metric transform and Datadog when processing the same nginx logs. The Vector pipeline consistently shows approximately 1/10th of the traffic volume compared to Datadog's measurements.

Setup details:
* Processing custom-formatted nginx logs
* Vector pipeline: nginx logs → log_to_metric transform → Mimir
* Metrics viewed through Grafana
* Same time periods and filtering criteria used in both Grafana and Datadog for comparison

Current observations:

* Mimir distributor logs show no errors
* Vector logs are mostly clean, with occasional parsing failures (few per hour) for specific cases like "client request-body too large" messages
* All components appear to be functioning, just with unexpectedly low data volume

Configurations:

Mimir config: https://pastebin.com/ixUGPwNP
Vector config: https://pastebin.com/2RfCGUK8

Questions:

* What debugging approaches would you recommend to trace where metrics might be getting dropped?
* Are there specific Vector or Mimir metrics I should monitor to identify potential bottlenecks?
* Would logs from any other components be helpful for diagnosis?

Any guidance on troubleshooting techniques or configuration issues would be greatly appreciated.

**Comment by pront** [comment]
Hi @law, here is a list of tools and techniques I use when debugging complex pipelines:

* `vector top` to see component metrics - [docs here](https://vector.dev/docs/reference/cli/#top)
  * For example, you can inspect how many events are produced by sources vs how many events reach the sinks
  * You can also add an [internal_metrics](https://vector.dev/docs/reference/configuration/sources/internal_metrics/) source and inspect the metrics
* With `vector tap` you see the input and/or outputs of your components - [guide here](https://vector.dev/guides/level-up/vector-tap-guide/)
  * caveat: sinks don't have outputs, you will need to check the downstream systems for actual payloads
  * Alternative: for each source or transform that I want to test, I connect it to a `console` sink (doesn't scale to many components but it is a very quick sanity check)

For your case specifically, I would investigate if events are dropped or if events get stuck in a retry loop. For example, is this [component_discarded_events_total](https://vector.dev/docs/reference/configuration/sinks/loki/#component_discarded_events_total) metric greater than 0?

**Reply by law** [reply]
![Screenshot 2025-02-04 at 00 14 42](https://github.com/user-attachments/assets/7837a0e7-f939-4057-bff7-05e3bbc8f74b)
I enabled internal_metrics, but the only step that I see that is adding to `component_discarded_events_total` is the `filter_monolith_nginx` transform which... is kind of expected.  That step is there to get rid of all the non-traffic-relevant nginx logs like "upstream disconnect", "invalid header", and so on and so on, so the actual 'generate_metrics_from_logs' step can succeed.

**Comment by jszwedko** [comment]
One potential thing to check here, since you mentioned it was off by a factor of 10, is if the metric type and interval is being set correctly in Datadog. We've seen issues in the past where the interval or type was wrong, causing things to appear to be off by a factor of 10. Also, what version of Vector are you running?

**Reply by law** [reply]
I've been looking through the Datadog dashboard we use for keeping track of site-traffic, and I'm not seeing anything that would modify the metric-type or interval.  It's a fairly simple dash that pulls directly from logs:

```
{
    "title": "K8S All Requests by Status Code",
    "type": "timeseries",
    "requests": [
        {
            "formulas": [
                {
                    "formula": "query1"
                }
            ],
            "queries": [
                {
                    "data_source": "logs",
                    "name": "query1",
                    "indexes": [
                        "main"
                    ],
                    "compute": {
                        "aggregation": "count"
                    },
                    "group_by": [
                        {
                            "facet": "@http.status_code",
                            "limit": 10,
                            "sort": {
                                "order": "desc",
                                "aggregation": "count"
                            }
                        }
                    ],
                    "search": {
                        "query": "service:monolith-nginx kube_namespace:production region:$Region.value"
                    }
                }
            ],
            "response_format": "timeseries",
            "style": {
                "palette": "dog_classic"
            },
            "display_type": "bars"
        }
    ],
    "yaxis": {
        "include_zero": true,
        "scale": "linear",
        "label": "",
        "min": "auto",
        "max": "auto"
    }
}
``` 

Also, we are running Vector version `0.44.0-debian`, if that helps.

**Reply by jszwedko** [reply]
🤔 can you check the metric type and interval of the one that Vector is publishing?

**Reply by law** [reply]
in Grafana, or Vector?  

Vector is sending the metrics as:
```
    generate_nginx_metrics:
      type: log_to_metric
      inputs:
        - parse_nginx
      metrics:
        - type: counter
          name: http_requests_total
          namespace: nginx
          field: .nginx.status
          timestamp: .timestamp
          tags:
            path_root: "{{ \"{{\" }} nginx.path_root {{ \"}}\" }}"
            status: "{{ \"{{\" }} nginx.status {{ \"}}\" }}"
            method: "{{ \"{{\" }} nginx.method {{ \"}}\" }}"
            app: "{{ \"{{\" }} app {{ \"}}\" }}"
            eks_clustername: "{{ \"{{\" }} eks_clustername {{ \"}}\" }}"
            env: "{{ \"{{\" }} env {{ \"}}\" }}"
            pod_name: "{{ \"{{\" }} kubernetes_pod_name {{ \"}}\" }}"
        - type: histogram
          name: http_response_time_seconds
          namespace: nginx
          field: .nginx.response_time
          tags:
            path_root: "{{ \"{{\" }} nginx.path_root {{ \"}}\" }}"
            status: "{{ \"{{\" }} nginx.status {{ \"}}\" }}"
            method: "{{ \"{{\" }} nginx.method {{ \"}}\" }}"
            app: "{{ \"{{\" }} app {{ \"}}\" }}"
            eks_clustername: "{{ \"{{\" }} eks_clustername {{ \"}}\" }}"
            env: "{{ \"{{\" }} env {{ \"}}\" }}"
            pod_name: "{{ \"{{\" }} kubernetes_pod_name {{ \"}}\" }}"
 ```
 
 Grafana is graphing it with:
 `sum by($group_by) (rate(nginx_http_requests_total{env="$env", eks_clustername="$eks_clustername"}[$__rate_interval]))`
 
 with additional options set as follows:
 ```
 Legend: auto
 Min Step: 1
 Format: time series
 Type: Range
 ```
