### DISCUSSION TITLE
Help with Prometheus Scrape query

### DISCUSSION THREAD

**Discussion by satellite-no** [vectordotdev/vector#22333] [Q&A]
Im trying to setup a prometheus scrape with a query parameter but having troubles.  I have a successful source setup with the below where I pull back many many metrics and then just drop the ones I dont want.  However my preference would be to only pull back the metrics that I want (filter fast and filter early).

```yaml
sources:
  redis: 
    type: prometheus_scrape
    endpoints:
      - "https://redis_server/metrics"
    scrape_interval_secs: 60
    tls:
      verify_certificate: false
```

The below is an example of one of the metrics im trying ot capture but am still pulling ALL metrics. Tried both items in list seperately which is based on the documentation from the scrape source. 
```yaml
sources:
  redis: 
    type: prometheus_scrape
    endpoints:
      - "https://redis_server/metrics"
    query:
      "match[]":
        - '{name="bdb_avg_latency"}'
        - '{__name__=~"bdb_avg_latency"}'
    scrape_interval_secs: 60
    tls:
      verify_certificate: false
```

Any insight would be helpful even if im just interpriting what the `query` param does.

**Comment by pront** [comment]
Hi @satellite-no, thanks for sharing this.

> filter fast and filter early
👍 

Hmm, your `prometheus_scrape` configuration looks correct to me. I am now wondering if Prometheus does not allow filtering metrics at scrape time when pulling from a `/metrics` endpoint (but I don't have a local environment setup to validate this). 

You can use a filter transform in Vector though:
```
transforms:
  filter_metrics:
    type: filter
    inputs:
      - redis
    condition: '{{ name == "bdb_avg_latency" }}'
```

**Reply by satellite-no** [reply]
Hmm, maybe im just confused with the purpose of the query option.  If Prometheus does not allow filtering metrics at scrape time when pulling from a /metrics endpoint I cannot see a purpose for the query parameter to exist or how it was ever tested and implemented. 

FYI, Im using the below to remove the stuff i dont want but seems terribley inificient when i want 5% of what is being pulled lol.
```yaml
type: filter
inputs:
  - prometheus_scrape_redis
condition:
  type: vrl
  source: |
    .name == "bdb_avg_latency" ||
    .name == "node_free_memory" ||
    .name == "node_cpu_idle" ||
    .name == "node_persistent_storage_free" ||
    .name == "node_ephemeral_storage_free" ||
    .name == "node_ingress_bytes" ||
    .name == "node_egress_bytes" ||
    .name == "redis_total_commands_processed" ||
    .name == "redis_used_memory" ||
    .name == "redis_process_cpu_usage_percent" ||
    .name == "redis_connected_clients" ||
    .name == "redis_used_memory" ||
    .name == "redis_db0_keys" ||
    .name == "bdb_crdt_syncer_local_ingress_lag_time" ||
    .name == "bdb_crdt_syncer_status" ||
    .name == "bdb_replicaof_syncer_local_ingress_lag_time" ||
    .name == "bbdb_replicaof_syncer_status" ||
    .name == "bdb_up" ||
    .name == "node_up" ||
    .name == "node_provisional_memory" ||
    .name == "bdb_conns"
```

**Reply by pront** [reply]
Right, can you see the produced URL and/or any logs on the Prometheus side? Just wanted to ensure that the final URL is conforming to the Prometheus HTTP API.

**Comment by satellite-no** [comment]
Well thats the fun part,  I dont have any visiblity to these boxes other then the metrics endpoint.  I assume (but not sure) that they are using the [redis exporter](https://redis.io/docs/latest/integrate/prometheus-with-redis-enterprise/prometheus-metrics-v1-to-v2/) that we are just scrapping thinking its v1 and not v2 which might be an issue(?).  

The part im confused about and this is my inexperiance with prometheus is I dont see an way to query specific metrics in the proper prometheus scrape [config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config). Researching online the only way i can see to do this is with the `metric_relabel_configs` seen below ([source](https://last9.io/docs/how-to-scrape-only-selective-metrics-in-prometheus/))

```yaml
    metric_relabel_configs:
    - source_labels: [__name__]
      action: keep
      regex: '(node_cpu)'
```
