### DISCUSSION TITLE
Extra null bytes as start of protobuf message

### DISCUSSION THREAD

**Discussion by fbs** [vectordotdev/vector#22334] [Q&A] [answered]
I'm testing http/protobuf between vector instances and ran into some 400s I do not understand. It seems like a http sink in protobuf mode adds extra null bytes at the start of the payload.

As a reproducer I created a single instance to act as both the log generator, and sink, and source, with 2 pipelines i.e.

```
source demo_logs -> remap to fixed format -> sink http/protobuf -->
source http/protobuf -> sink console as json
```

config:

```
api:
  enabled: true

sources:
  generate_syslog:
    type: "demo_logs"
    format: "syslog"
    count: 10
    interval: 5

  accept_http:
    type: http_server
    address: 127.0.0.1:5555
    decoding:
      # codec: protobuf
      codec: json
      protobuf:
        desc_file: test.desc
        message_type: SimpleMessage

transforms:
  remap_custom:
    inputs: ["generate_syslog"]
    type: "remap"
    source: |
      . = {}
      .message = "a test message"
      .bliep = 2

sinks:
  emit_http:
    inputs: ['remap_custom']
    type: http
    uri: http://127.0.0.1:5555
    encoding:
      # codec: protobuf
      codec: json
      protobuf:
        desc_file: test.desc
        message_type: SimpleMessage
    request:
      headers:
        content-type: x-protobuf

  emit_console:
    type: console
    encoding:
      codec: json
    inputs:
    - accept_http
    - remap_custom
```

In json mode this work and the console shows 2 lines:

```
{"bliep":2,"message":"a test message","path":"/","source_type":"http_server","timestamp":"2025-01-30T18:53:03.513011Z"}
{"bliep":2,"message":"a test message"}
```

inspection in wireguard shows:

```
POST / HTTP/1.1
content-type: x-protobuf
accept-encoding: zstd,gzip,deflate,br
user-agent: Vector/0.44.0 (aarch64-apple-darwin 3cdc7c3 2025-01-13 21:26:04.735691656)
host: 127.0.0.1:5555
content-length: 40

[{"bliep":2,"message":"a test message"}]

HTTP/1.1 200 OK
content-length: 0
date: Thu, 30 Jan 2025 20:20:11 GMT
```

However when switching to protobufs using:

```
syntax = "proto3";

message SimpleMessage {
  int64 bliep = 1;
  string message = 2;
  int64 bla = 3;
}
```

```
POST / HTTP/1.1
content-type: x-protobuf
accept-encoding: zstd,gzip,deflate,br
user-agent: Vector/0.44.0 (aarch64-apple-darwin 3cdc7c3 2025-01-13 21:26:04.735691656)
host: 127.0.0.1:5555
content-length: 22

a test message

HTTP/1.1 400 Bad Request
content-type: application/json
content-length: 149
date: Thu, 30 Jan 2025 20:22:36 GMT

{"code":400,"message":"Failed decoding body: ParsingError(Error parsing protobuf: DecodeError { description: \"invalid tag value: 0\", stack: [] })"}
```

Note the 3 nulls at the start of the protobuf message. The full payload:

```
000000120802120e612074657374206d657373616765
AAAAEggCEg5hIHRlc3QgbWVzc2FnZQ==
```

If I post the proto and base64 string in https://www.protobufpal.com/ it does seem to decode it ok.

```
{
  "bliep": 2,
  "message": "a test message",
  "bla": 0
}
```

If I use that same tool to encode just the message:

```
{
  "message": "a test message"
}

-> Eg5hIHRlc3QgbWVzc2FnZQ==
```

and send that it does actually work:

```
curl localhost:5555 -XPOST -d "$(echo -n Eg5hIHRlc3QgbWVzc2FnZQ==|base64 -D)" -v
< HTTP/1.1 200 OK
< content-length: 0
< date: Thu, 30 Jan 2025 20:34:50 GMT
```

vector console shows:

```
{"message":"a test message","path":"/","source_type":"http_server","timestamp":"2025-01-30T20:34:50.871782Z"}
```

Same for adding `bla: 123`

```
curl localhost:5555 -XPOST -d "$(echo -n Eg5hIHRlc3QgbWVzc2FnZRh7|base64 -D)"
{"bla":123,"message":"a test message","path":"/","source_type":"http_server","timestamp":"2025-01-30T20:37:39.358163Z"}
```
