### DISCUSSION TITLE
Separate labels from message in loki

### DISCUSSION THREAD

**Discussion by freedomwarrior** [vectordotdev/vector#22340] [Q&A] [answered]
Hello.
I deploy vector using helm chart with this config:
```
customConfig:
  data_dir: /vector-data-dir
  sources:
    k8s:
      type: kubernetes_logs
  sinks:
    loki:
      type: loki
      compression: snappy
      encoding:
        codec: json
      inputs: [k8s]
      endpoint: http://loki-gateway.default.svc.dev.k8s.local
      path: /loki/api/v1/push
      out_of_order_action: accept
      remove_timestamp: false
      remove_label_fields: true
      labels:
        forwarder: "vector"
```
And the problem is that all labels comes as regualar text, and message looks like that:
![image](https://github.com/user-attachments/assets/dcaad24c-ecdd-413f-b389-e24c96e925f6)
Message value and labels are mixed and I need to separate them.

**Comment by pront** [comment]
Hi @freedomwarrior, I see that this was closed. Did you figure out the issue? If so, please share here. It might help someone in the future.

**Reply by freedomwarrior** [reply, marked as answer]
Hello.
Yes, the problem is that I use `codec: json`, and it works as expected.
Instead need to use `text`
Here is my config:
```
  sources:
    k8s:
      type: kubernetes_logs

  transforms:
    k8s_ready:
      type: remap
      inputs:
        - k8s
      source: |
        .app = .kubernetes.pod_labels."app.kubernetes.io/name"
        .hostname = .kubernetes.node_labels."kubernetes.io/hostname"
        del(.file)
        del(.kubernetes)
        del(.source_type)
        del(.stream)
  sinks:
    loki:
      type: loki
      inputs:
        - k8s_ready
      compression: snappy
      encoding:
        codec: "text"
      labels:
        app: "{{`{{.app}}`}}"
        hostname: "{{`{{.hostname}}`}}"
      remove_label_fields: true
      endpoint: http://loki-gateway.default.svc.cl1.k8s.local
      path: /loki/api/v1/push
      remove_timestamp: true
      tenant_id: fake
```
