### DISCUSSION TITLE
moving from filebeat to vector

### DISCUSSION THREAD

**Discussion by therus000** [vectordotdev/vector#22349] [Q&A]
Good day
 im try to move for file to vector and i got this config 
```yaml
filebeat_path_custom:
  - type: log
    paths:
      - "/var/log/app-1/*.log"
    fields:
      haproxy: true
      product: nlb
    fields_under_root: true
    processors:
      - dissect:
          tokenizer: "%{prefix}[%{pid}]: %{message}"
          field: "message"
          overwrite_keys: true
          target_prefix: ""
      - decode_json_fields:
          fields: ["message"]
          target: "json"
          overwrite_keys: true
      - drop_fields:
          fields: ["prefix", "pid", "log", "ecs"]
          ignore_missing: true
```
i think i should use file as source for vector. but what about else. any one can help
