### DISCUSSION TITLE
Route by json field

### DISCUSSION THREAD

**Discussion by mohalaci** [vectordotdev/vector#22355] [Q&A] [answered]
Hello,
I have this config:
```
api:
  enabled: true
  address: 0.0.0.0:8686

sources:
   mobilelog-json:
    type: http_server
    address: 0.0.0.0:6624
   

transforms:
  json-parser:
    type: remap
    inputs:
      - mobilelog-json
    source: |-
      . = parse_json!(string!(.message))

  routed_mobile_logs:
    type: route
    inputs:
      - json-parser
    route:
      demo: '.attributes.env == "demo"'

sinks:
  console:
    inputs:
      - routed_mobile_logs.demo
    target: stdout
    type: console
    encoding:
      codec: json
```

but the routing is not working. 
I tried to POST this json to my vector instance:
`{
    "message": 
    "{\"attributes\":{\"logtype\":\"activitylog\",\"env\":\"demo\",\"app\":{\"name\":\"TESTAPP\"}},\"env\": \"demo\", \"attributes.env\": \"demo\"}"
}`
