### DISCUSSION TITLE
How to use vector as a lib to push to another vector instance

### DISCUSSION THREAD

**Discussion by rolandjitsu** [vectordotdev/vector#22382] [Q&A]
I was wondering if it is possible to use vector as a lib within my own rust program to push data to another vector endpoint. 

Typically, I would just use vector as an agent and have a vector 2 vector setup, but due to some restrictions, I cannot run additional services/programs.

Right now, I've enabled the `http_server` source and I simple POST the data, but it would be great to use the vector source and port instead of opening up an additional port:
```
[my program -> vector lib] -> vector aggregator :6000
```

**Comment by pront** [comment]
Can you share you config (redacting any sensitive data) please?

If you can achieve it with HTTP there should not be much difference vs Vector --> Vector. But I am missing some context here.

## Appendix
Using `vector generate`:

```
vector generate vector/remap/vector
data_dir: /var/lib/vector/
sources:
  source0:
    address: 0.0.0.0:6000
    type: vector
    acknowledgements: {}
transforms:
  transform0:
    inputs:
    - source0
    drop_on_abort: false
    drop_on_error: false
    metric_tag_values: single
    reroute_dropped: false
    runtime: ast
    type: remap
sinks:
  sink0:
    inputs:
    - transform0
    address: 127.0.0.1:6000
    compression: false
    type: vector
    batch: {}
    request:
      rate_limit_duration_secs: 1
      rate_limit_num: 9223372036854775807
      retry_attempts: 9223372036854775807
      retry_initial_backoff_secs: 1
      retry_jitter_mode: Full
      retry_max_duration_secs: 30
      timeout_secs: 60
      adaptive_concurrency:
        decrease_ratio: 0.9
        ewma_alpha: 0.4
        initial_concurrency: 1
        max_concurrency_limit: 200
        rtt_deviation_scale: 2.5
    healthcheck:
      enabled: true
      uri: null
    buffer:
      type: memory
      max_events: 500
      when_full: block
```
