### DISCUSSION TITLE
Dyanamic Routing with route or exclusive_route

### DISCUSSION THREAD

**Discussion by satellite-no** [vectordotdev/vector#22423] [Q&A] [answered]
Is there any way to do dynamic routing?

example of what im looking for. 

```yaml
type: exclusive_route
inputs:
  - vector
route:
  - name: "{{ .source }}"
  	condition:
  		type: vrl
  		source: exists(.source)
```

Background:
 I have a "recieving" vector cluster sending to a backend "transforms" cluster with the vector sink/source.  But since the source for inputs is now just 'vector' it makes routing a little more challenging so I was hoping for a dynamic way of routing these for later inputs.
