### DISCUSSION TITLE
2 sinks in one

### DISCUSSION THREAD

**Discussion by therus000** [vectordotdev/vector#22425] [Q&A]
good day
i got 2 same sinks on http (send logs to victorialog) the difference  only in uri?
i didnt found in documentaion way to combine those two sinks in one!
is it possible to do that ?
```yaml
    vlogs-01:
      inputs:
        - kafka
      type: http
      uri: "http://os:9428/insert/jsonline?_stream_fields=k8s.namespace,k8s.pod_name&_msg_field=message,json.msg,log4j.message,json.err,json.message&_time_field=timestamp,ts,@timestamp,time"
      compression: gzip
      encoding:
        codec: json
      framing:
        method: newline_delimited
      healthcheck:
        enabled: false
    vlogs-02:
      inputs:
        - kafka
      type: http
      uri: "http://os:9428/insert/jsonline?_stream_fields=k8s.namespace,k8s.pod_name&_msg_field=message,json.msg,log4j.message,json.err,json.message&_time_field=timestamp,ts,@timestamp,time"
      compression: gzip
      encoding:
        codec: json
      framing:
        method: newline_delimited
      healthcheck:
        enabled: false
```
```
