### DISCUSSION TITLE
How do I get the value of a variable from transforms to sinks

### DISCUSSION THREAD

**Discussion by Ilyin-V-V** [vectordotdev/vector#22432] [Q&A] [answered]
How do I get the value of a variable stack_namespace from transforms to skins ?
```
sources:
  swarm:
    type: docker_logs
    auto_partial_merge: true
    include_labels: ["com.docker.stack.namespace=dev"]

transforms:
  remap_swarm:
    type: remap
    inputs:
      - "swarm"
    source: |
      .stack_namespace = .label."com.docker.stack.namespace"
      del(.label)
      del(.stream)

sinks:
  file:
    inputs:
      - "remap_swarm"
    type: file
    path: /out/{{ transforms.remap_swarm.source.stack_namespace }}
    encoding:
      codec: "json"
```

**Comment by Ilyin-V-V** [comment]
ERROR sink{component_kind="sink" component_id=file component_type=file}: vector::internal_events::template: Failed to render template for "path". error=Missing fields on event: ["transforms.remap_swarm.source.stack_namespace"] error_type="template_failed"

**Comment by Ilyin-V-V** [comment, marked as answer]
I figured it out
```
sources:
  swarm:
    type: docker_logs
    auto_partial_merge: true
    include_labels: ["com.docker.stack.namespace=dev"]

transforms:
  remap_swarm:
    type: remap
    inputs:
      - "swarm"
    source: |
      .stack_namespace = .label."com.docker.stack.namespace"
      del(.label)
      del(.stream)

sinks:
  file:
    inputs:
      - "remap_swarm"
    type: file
    path: "/out/{{ .stack_namespace }}"
    encoding:
      codec: "json"
```
