### DISCUSSION TITLE
Sink victorialogs as HTTP (&_time_field)

### DISCUSSION THREAD

**Discussion by homelab8330** [vectordotdev/vector#22472] [Q&A] [answered]
i found this sink in documentation about victoria logs 
```
sinks:
  vlogs:
    inputs:
      - your_input
    type: http
    uri: http://localhost:9428/insert/jsonline?_stream_fields=host,container_name&_msg_field=message&_time_field=timestamp&debug=1
    compression: gzip
    encoding:
      codec: json
    framing:
      method: newline_delimited
    healthcheck:
      enabled: false
```
my qustion is about uri and 

```
&_time_field=timestamp
```
is it possible to write multi timestamps in here like
 
```
_time_field=timestamp,ts,@timestamp,time,json.ts
```

or it will be conflict and  i must write only one?
