### DISCUSSION TITLE
Vector crashes on k8s if the sink goes down

### DISCUSSION THREAD

**Discussion by rolandjitsu** [vectordotdev/vector#22498] [Q&A]
I'm in a bit of a pickle. I'm running vector as an aggregator on k8s, configured to consume data from a http server source and push to an Elasticsearch sink.

After running a few tests, it looks like if the sink goes down, but data is still flowing in, Vector pods will eventually crash and show the following error:
```
The container last terminated with exit code 137 because of OOMKilled.
```

<img width="1044" alt="Screenshot 2025-02-24 at 14 19 17" src="https://github.com/user-attachments/assets/459d0e3d-80ba-4804-a7e7-93850c708b45" />

I've found the following related issues:
1. [#11942](https://github.com/vectordotdev/vector/issues/11942)
2. [#17942](https://github.com/vectordotdev/vector/discussions/17942)
3. [#18578](https://github.com/vectordotdev/vector/discussions/18578) - similar; points to a bug in vector that was resolved, but for a different sink
4. [#19815](https://github.com/vectordotdev/vector/discussions/19815) - sounds similar to what we're experiencing

But I'm a bit confused about it. Mainly because as soon as the sink goes down, the sources will start seeing non-200 http status codes, which to me feels like the the buffering mechanism does not work or it's not intended to work in this case. If it would, I should see 200 since the request made it through to vector and should only start returning non-200 after the buffer is full and can no longer take anymore data.

I'm just looking for some clarification on what exactly is the expected behaviour:
1. Does vector buffer events send to the http endpoint?
2. If requests return non-200, does this mean that the events were still buffered? The non-200 just means that we didn't get an ack from vector/sink that the events made it through?
5. Is there some documentation on the status codes returned from vector when using the http source? At first, it looked like the status codes are the same as Elasticsearch returned, but that cannot be true since there may be multiple sinks returning different status codes

I use the [vector](https://github.com/vectordotdev/helm-charts/tree/develop/charts/vector) helm chart with the following config:

<details>
<summary>Config</summary>

```yaml
vector:
  role: "Aggregator"

  image:
    repository: timberio/vector
    pullPolicy: IfNotPresent
    tag: "0.42.0-alpine"

  replicas: 2

  secrets:
    generic: {}

  env:
    - name: ES_USERNAME
      value: elastic
    - name: ES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elastic-user
          key: elastic

  resources: {}

  persistence:
    enabled: true

  # NOTE: When we set this, we need to configure a bunch of other stuff (e.g. HAProxy, etc.)
  # https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/configmap.yaml
  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    acknowledgements:
      enabled: true
    # https://vector.dev/blog/log-namespacing/
    schema:
      log_namespace: true
    sources:
      # https://vector.dev/docs/reference/configuration/sources/internal_metrics/
      internal_metrics:
        type: internal_metrics
      # https://vector.dev/docs/reference/configuration/sources/host_metrics/
      host_metrics:
        type: host_metrics
      # https://vector.dev/docs/reference/configuration/sources/vector/
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
      vector_http:
        type: http_server
        address: 0.0.0.0:8888
        encoding: ndjson
        method: POST
        response_code: 200
    transforms:
      logs:
        type: filter
        inputs:
          - vector_http
        condition: '.kind == "Log"'
      remapped_logs:
        type: remap
        inputs:
          - logs
        source: |-
          .@timestamp = del(.timestamp)
          .metadata = {}
          .data_stream = {}
          .data_stream.type = "logs"
          .data_stream.dataset = "blackhole"
          .data_stream.namespace = "device"
      resource_usage:
        type: filter
        inputs:
          - vector_http
        condition: '.kind == "ResourceUsage"'
      remapped_resource_usage:
        type: remap
        inputs:
          - resource_usage
        source: |-
          .@timestamp = del(.timestamp)
          .metadata = {}
          .data_stream = {}
          .data_stream.type = "metrics"
          .data_stream.dataset = "resource_usage"
          .data_stream.namespace = "device"
    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [internal_metrics, host_metrics]
        address: 0.0.0.0:9090
      stdout:
        type: console
        inputs: [vector, vector_http]
        encoding:
          codec: json
      es_data_stream:
        type: elasticsearch
        inputs: [remapped_logs, remapped_resource_usage]
        # NOTE: We do not need to remap `timestamp` -> `@timestamp`; Vector does this for us when using `data_stream` mode.
        # https://github.com/vectordotdev/vector/blob/d49cf33748ad82292198888687b6b50a01d8500f/src/sinks/elasticsearch/mod.rs#L73
        # TODO: It seems that the above assumption is incorrect! Because w/o adding the `@timestamp`, we see:
        # 2025-02-12T05:53:22.008701Z ERROR sink{component_kind="sink" component_id=es_data_stream component_type=elasticsearch}:request{request_id=2769}: vector::sinks::util::retries: Not retriable; dropping the request. reason="error type: document_parsing_exception, reason: [1:381] failed to parse: data stream timestamp field [@timestamp] is missing" internal_log_rate_limit=true
        mode: data_stream
        data_stream:
          auto_routing: true
        auth:
          user: "${ES_USERNAME}"
          password: "${ES_PASSWORD}"
          strategy: "basic"
        endpoints:
          - https://es-endpoint.svc.cluster.local:9200
        tls:
          verify_certificate: false

  service:
    enabled: true

    # https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/service.yaml
    # https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/service-headless.yaml
    ports:
      - name: vector
        port: 6000
        protocol: TCP
      - name: vector-http
        port: 8888
        protocol: TCP
      - name: prom-exporter
        port: 9090
        protocol: TCP

  haproxy:
    enabled: true

    image:
      repository: haproxytech/haproxy-alpine
      pullPolicy: IfNotPresent
      tag: "2.6.12"

    replicas: 1

    # https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/haproxy/deployment.yaml
    containerPorts:
      - name: vector
        containerPort: 6000
        protocol: TCP
      - name: vector-http
        containerPort: 8888
        protocol: TCP
      - name: prom-exporter
        containerPort: 9090
        protocol: TCP

    # https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/haproxy/service.yaml
    service:
      annotations:
      ports:
        - name: vector
          port: 6000
          protocol: TCP
        - name: vector-http
          port: 8888
          protocol: TCP
        - name: prom-exporter
          port: 9090
          protocol: TCP

    # https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/haproxy/configmap.yaml
    customConfig: |
      global
        log stdout format raw local0 debug
        maxconn 4096
        stats socket /tmp/haproxy
        hard-stop-after {{ .Values.haproxy.terminationGracePeriodSeconds }}s

      defaults
        log     global
        option  dontlognull
        retries 3
        option  redispatch
        option  allbackups
        timeout client 15s
        timeout server 15s
        timeout connect 15s

      resolvers coredns
        nameserver dns1 kube-dns.kube-system.svc.cluster.local:53
        resolve_retries 3
        timeout resolve 2s
        timeout retry 1s
        accepted_payload_size 8192
        hold valid 10s
        hold obsolete 60s

      frontend stats
        mode http
        bind :::1024
        option httplog
        http-request use-service prometheus-exporter if { path /metrics }

      frontend vector
        mode http
        bind :::6000 proto h2
        option httplog
        default_backend vector

      frontend vector_http
        mode http
        bind :::8888 proto h1
        option httplog
        default_backend vector_http

      backend vector
        mode http
        balance roundrobin
        option tcp-check
        server-template srv 10 _vector._tcp.{{ include "vector.fullname" $ }}-headless.{{ $.Release.Namespace }}.svc.cluster.local resolvers coredns proto h2 check

      backend vector_http
        mode http
        balance roundrobin
        option tcp-check
        server-template srv 10 _vector-http._tcp.{{ include "vector.fullname" $ }}-headless.{{ $.Release.Namespace }}.svc.cluster.local resolvers coredns proto h1 check

  # Direct trafic to Traefik's vector entrypoint
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: vectorhttp
    hosts:
      - paths:
          - path: /
            pathType: Prefix
            port:
              name: vector-http
```
</details>

**NOTE**: On the source side, we have agents pushing to the http endpoint. As soon as a non-200 occurs, they will stop sending new events and keep retrying (at the first failure) until it receives 200, then it continues pushing. There's also a buffering mechanism on the agent side.
