### DISCUSSION TITLE
Is there a bug in internal metrics on 0.45.0

### DISCUSSION THREAD

**Discussion by satellite-no** [vectordotdev/vector#22545] [Q&A] [answered]
Im running `vector 0.45.0 (x86_64-unknown-linux-gnu 063cabb 2025-02-24 14:52:02.810034614)` on three seperate Vector instances and when I tap the outputs of the `internal_metrics` source i do not get any data.  Also all of my data that has feed my promtheus dashboard from this source has stopped work. 

example configs:
Source
```yaml
type: "internal_metrics"
scrape_interval_secs: 10
```

Transform:
```yaml
type: "remap"
inputs:
  - vector_internal_host_metrics
  - vector_internal_metrics
source: |
  .tags.vector_source = "Vector Internal Metrics"
  .tags.App         = "ABC123"
  .tags.Sources       = "Vector Internal"
  .tags.Ci            = del(.tags.host)
```

Sink:
```yaml
type: prometheus_exporter
inputs:
  - core_metric_vector_tags
address: 0.0.0.0:9598
flush_period_secs: 60
auth:
  token: <token>
  strategy: bearer
buffer:
  type: "disk"
  max_size: 53687091200
  when_full: "block"
```
