### DISCUSSION TITLE
Unable to extract labels from loki sink in vector

### DISCUSSION THREAD

**Discussion by surekha3** [vectordotdev/vector#22595] [Q&A] [answered]
Trying to collect kafka logs using vector latest version and sending to loki. But unable to extract any labels from loglines. when given under labels i.e.,
labels:
  env: "{{ env }}"
It's stating function env not found error though it's present within logline. Please help asap

**Comment by surekha3** [comment]
any help please

**Comment by surekha3** [comment]
Below is the sink config I used

```
 transforms:
    extract_transform:
      type: remap
      inputs:
        - kafka_logs
      source: |
              .topic = to_string!(.topic)
              . = parse_json!(.message)
              .host = .parsed.tags.host
  sinks:
    loki_sink:
      type: loki
      inputs:
        - extract_transform
      endpoint: http://loki-nob-gateway
      encoding:
        codec: "json"
      compression: none
      healthcheck: false
      labels:
        job: "kafka"
        topic: "{{ topic }}"
        host: "{{ host }}"
```

With this giving error function topic not defined and function host not defined though they're appearing in loglines when printed to console. Logs source is kafka
