### DISCUSSION TITLE
Splunk HEC source requires channel with ack disabled

### DISCUSSION THREAD

**Discussion by objectbased** [vectordotdev/vector#22642] [Q&A] [answered]
When testing a basic Splunk HEC source I've noticed that when a payload is sent to the `/services/collector/raw` endpoint without a `X-Splunk-Request-Channel` you get the below response back.

{ "text": "Data channel is missing", "code": 10 }

The below is my configuration for Vector that I have setup which includes acknowledgment being disabled.

```
sources:
  hec_8088:
    type: splunk_hec
    address: 0:0:0:0:8088
    acknowledgements:
      enabled: false
    valid_tokens:
      - abc123
```

Reading the docs from Splunk found below they mention channel is only required when acknowledgement is enabled, but in Vector it looks like this is required for any payloads sent to the "raw" endpoint regardless if acknowledgement is enabled or not. Is this the intended behavior?

https://docs.splunk.com/Documentation/Splunk/9.4.1/Data/AboutHECIDXAck#About_channels_and_sending_data
