### DISCUSSION TITLE
is there an easier way to do basename/dirname when using file source

### DISCUSSION THREAD

**Discussion by shantanugadgil** [vectordotdev/vector#22657] [Q&A] [answered]
I have the following minimal config file (experimented on the VRL playground)

I want to extract the "only file name" bit (first part of `basename`) from the full file name of the log file.

I have the following so far, but was wondering if there is there a more "proper" way of doing this?

(In the longer run I want to use the extracted name as a log label when forwarding to Loki.

```yaml

data_dir: /tmp/experiment/

sources:
  logs:
    type: file
    include:
      - /var/log/*.log

transforms:
  modify:
    type: remap
    inputs:
      - logs
    source: |
      parts = split!(.file, "/")
      basename = split!(parts[-1], ".")
      .service_name = basename[0]

sinks:
  my_sink_id:
    type: console
    inputs:
      - modify
    encoding:
      codec: json

```
