### DISCUSSION TITLE
Metrics via exec on Linux

### DISCUSSION THREAD

**Discussion by abubakr-cgs** [vectordotdev/vector#22655] [Q&A] [answered]
Hello, I am trying to bring some linux host metrics via vector's exec command in source.
In windows, I have achieved this by:
```
  cpu_usage:
    type: exec
    mode: scheduled
    scheduled:
      exec_interval_secs: 5
    command: 
      - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
      - "-Command"
      - "Write-Output (@{cpu_usage=(Get-Counter '\\Processor(_Total)\\% Processor Time').CounterSamples.CookedValue} | ConvertTo-Json -Compress)"
    decoding:
      codec: json 
```
I have avoided using $ symbols as it escapes in vector as an environment variable. and used Write-Output to dump it into a variable.
However for linux, I find it impossible, as a simple command for pulling cpu utilization needs $, something like this:
```
cpu_util=$(top -bn2 | grep '%Cpu' | tail -1 | grep -P '(....|...) id,' | awk '{print 100-$8}')
echo "{\"cpu_usage\": $cpu_util}"
```
Is there way to run exec command without variable names or not let $var names escape? I have gone through host_metrics and dont find any viable way to get direct cpu information. I would also be using these to fetch memory and disk information, so any help is appreciated. 
Thanks!

**Comment by abubakr-cgs** [comment]
For exec and running cpu metrics specifically, I have gotten a solution to follow for now
```
linux_cpu:
    type: exec
    mode: streaming
    streaming:
      respawn_on_exit: true
    command: ["sh", "-c", "top -bn2 | grep '%Cpu' | tail -1 | cut -d ',' -f 4 | cut -d ' ' -f 2"]
```
I am fetching the entire CPU metric result containing all values, since I can't use `awk` because it uses '$' notation for fetching, I decided to cut the idle % field that i need
and then, currently I'm using a transform to do (100-idle %) which gives me a solution. 
Any other help is also appreciated for fetching metrics with exec!

**Comment by pront** [comment]
Hi @abubakr-cgs, take a look at https://vector.dev/docs/reference/configuration/#escaping

> ```
> cpu_util=$(top -bn2 | grep '%Cpu' | tail -1 | grep -P '(....|...) id,' | awk '{print 100-$8}')
> echo "{\"cpu_usage\": $cpu_util}"
> ```

Also, you can rewrite the above without a variable:
```
command:
    - "/bin/sh"
    - "-c"
    - "top -bn2 | grep '%Cpu' | tail -1 | awk '/id,/ {print \"{\\\"cpu_usage\\\": \" 100-$8 \"}\"}'"
```

**Reply by abubakr-cgs** [reply, marked as answer]
Hey @pront , apologies for the late reply.
Using a double dollar sign is currently working good, according to this https://vector.dev/docs/reference/configuration/#escaping

Linux YAML
```
sources:
  memory_usage:
    type: "exec"
    mode: streaming
    command: ["sh", "-c", "free -m | awk 'NR==2{printf \"%s,%s,%s\", $$2, $$3, $$4}'"]
```

Result
```
{
  "command": [
    "sh",
    "-c",
    "free -m | awk 'NR==2{printf \"%s,%s,%s\", $2, $3, $4}'"
  ],
  "host": "DESKTOP-F1VAVE8",
  "message": "15866,10618,405",
  "pid": 3566328,
  "source_type": "exec",
  "stream": "stdout",
  "timestamp": "2025-04-09T05:26:34.569643376Z"
}
```
Thanks for your help!
