### DISCUSSION TITLE
Socket sink support for TTL?

### DISCUSSION THREAD

**Discussion by pkruk** [vectordotdev/vector#22697] [Q&A] [answered]
Hi,

I'm using vector to deliver logs to logstash with using a socket sink :) 

```
    sinks:
      logstash:
        type: socket
        inputs: ["parse_json"]
        mode: "tcp"
        address: "xxxxxxx:5045"
        encoding:
          codec: json
```

But on logstash we observed that traffic is not distributed evenly. It's looks like one ip is resolved from a host and all is sent to this one endpoint. Rigth now we observed that one node of our logstash is receiving a traffic and the rest is on zero.  There is any option to set a TTL in socket sink? 

We're using right now vector version: 0.42.0
