### DISCUSSION TITLE
Configuring the Datadog Agent to send metrics to Vector with latest datadog-agent versions

### DISCUSSION THREAD

**Discussion by ABHINAV-SUREKA** [vectordotdev/vector#22729] [Q&A] [answered]
Hi,

I have datadog-agent daemonset which sends metrics to vector statefulset.
The vector then processes/filters these metrics before sending them to Datadog backend.

The [vector doc](https://vector.dev/docs/reference/configuration/sources/datadog_agent/) for configuring datadog-agent to send metrics & other telemetry data to Vector, redirects to the page: [(LEGACY) Set Up Observability Pipelines in Datadog](https://docs.datadoghq.com/observability_pipelines/legacy/setup/datadog/?tab=docker).

The info provided in the latter isn't matching or up-to-date with that mentioned in [configuring-the-datadog-agent](https://vector.dev/docs/reference/configuration/sources/datadog_agent/#configuring-the-datadog-agent) section.

I am wondering what's the recommended way for datadog-agent to send metrics to vector.

Following the vector document for configuring the datadog-agent, if I do:
```
vector:
	metrics.enabled: true
	metrics.url: http://"<VECTOR_HOST>:<SOURCE_PORT>"
``` 
it works with datadog-agent version `7.50.3`.

But as soon as I upgrade datadog-agent to the later versions, say `7.60.3` or above, I run into the issue:
```
agent=core file=comp/forwarder/defaultforwarder/worker.go func=process host=<host_ip> level=ERROR line=222 msg="Error while processing transaction: error \"415 Unsupported Media Type\" while sending transaction to \"http://<vector_endpoint_url>:8282/api/v1/series\", rescheduling it: \"{\\\"code\\\":415,\\\"message\\\":\\\"Unsupported encoding zstd\\\"}\"" pod=datadog-agent-72sw9 time=2025-02-27T12:12:48Z
```

Note the below configuration I have in vector to receive metrics from datadog-agent:
```
    sources:
      datadog_agent:
        address: 0.0.0.0:8282
        type: datadog_agent
        store_api_key: true
        disable_logs: true
        disable_traces: true
        multiple_outputs: false
```

Please suggest the recommended way forward.
