### DISCUSSION TITLE
Proper use of reduce transform to target go panics

### DISCUSSION THREAD

**Discussion by davidcpell** [vectordotdev/vector#22740] [Q&A]
I'm trying to use `reduce` to combine go panics into a single log line with newline delimiters. In my testing, this results in a large drop in events received by the sink:

<img width="545" alt="image" src="https://github.com/user-attachments/assets/4ead2fbf-58cc-4b1c-952f-8aa3aeaeda77" />

A cleaned up version my config looks like this:

```yaml
sources:
  kubernetes:
    type: "kubernetes_logs"
transforms:
  combine_go_panics:
    type: reduce
    inputs:
      - kubernetes
    starts_when:
      type: vrl
      source: |
        starts_with(string!(.message), "panic: runtime error:")
    group_by: ["file"]
    merge_strategies:
      message: concat_newline
    expire_after_ms: 1000
    max_events: 1000
  go_panic_level:
    type: remap
    inputs:
      - combine_go_panics
    source: |
      if starts_with(string!(.message), "panic: runtime error:") {
        .level = "fatal"
      }
sinks:
  http:
    type: "http"
    uri: http://vector-aggregator:${PORT_AGGREGATOR:-8000}
    encoding:
      codec: "json"
    inputs:
    - "go_panic_level"
```

I was under the impression `starts_with` would mean an aggregation begins when `panic: runtime error` is seen and that for any other log a reduce would not begin and it would flow through to the next component as normal. Is that accurate? Any idea on what might be causing what I'm seeing with components received dropping so low on the sink?

**Comment by pront** [comment]
> I was under the impression starts_with would mean an aggregation begins when panic: runtime error is seen and that for any other log a reduce would not begin and it would flow through to the next component as normal. Is that accurate?

Hi @davidcpell, this is correct.

> Any idea on what might be causing what I'm seeing with components received dropping so low on the sink?

Looking at your `reduce` configuration, you can potentially reduce 1000 events to 1 in 1 second intervals. So I would expect a shard decline in `component_sent_events_total`. Also, the `stale_events_flushed_total` metric might be interesting.

**Comment by pront** [comment]
I went back to do an experiment. 

### Input File

```text
Starting the program...
panic: Boom

goroutine 1 [running]:
main.main()
    /path/to/file.go:7 +0x65
exit status 2
...
panic: Boom

goroutine 2 [running]:
main.main()
    /path/to/file.go:7 +0x65
exit status 2

```

### Vector Config

```yaml
data_dir: path/data/data_dir_0

sources:
  source_0:
    type: file
    include:
      - path/data/panics.txt
    read_from: "beginning"

transforms:
  t0:
    type: remap
    inputs:
      - source_0
    source: |
      .file = "a"

  combine_go_panics:
    type: reduce
    inputs:
      - t0
    starts_when:
      type: vrl
      source: |
        starts_with(string!(.message), "panic:")
    group_by: ["file"]
    merge_strategies:
      message: concat_newline
    expire_after_ms: 1000
    max_events: 1000


sinks:

  sink_0:
    type: console
    inputs:
      - combine_go_panics
    encoding:
      codec: json
      json:
        pretty: true

```

### Vector Output

```
2025-03-28T19:29:43.504710Z  INFO source{component_kind="source" component_id=source_0 component_type=file}:file_server: vector::internal_events::file::source: Found new file to watch. file=/Users/pavlos.rontidis/CLionProjects/vector/pront/data/panics.txt
{
  "file": "a",
  "host": "COMP-LPF0JYPP2Q",
  "message": "Starting the program...",
  "source_type": "file",
  "timestamp": "2025-03-28T19:29:43.505538Z",
  "timestamp_end": "2025-03-28T19:29:43.505538Z"
}
{
  "file": "a",
  "host": "COMP-LPF0JYPP2Q",
  "message": "panic: Boom\n\ngoroutine 1 [running]:\nmain.main()\n    /path/to/file.go:7 +0x65\nexit status 2\n...",
  "source_type": "file",
  "timestamp": "2025-03-28T19:29:43.505689Z",
  "timestamp_end": "2025-03-28T19:29:43.505932Z"
}
2025-03-28T19:29:44.515309Z DEBUG vector::internal_events::file::source: Files checkpointed. count=1 duration_ms=7
2025-03-28T19:29:44.546020Z DEBUG source{component_kind="source" component_id=source_0 component_type=file}:file_server: file_source::file_server: event_throughput=14.000/sec bytes_throughput=196.000/sec ratios={"discovery": 0.00012023014, "other": 0.0008569367, "reading": 0.00014852721, "sending": 0.0003028562, "sleeping": 0.9985739}
{
  "file": "a",
  "host": "COMP-LPF0JYPP2Q",
  "message": "panic: Boom\n\ngoroutine 2 [running]:\nmain.main()\n    /path/to/file.go:7 +0x65\nexit status 2",
  "source_type": "file",
  "timestamp": "2025-03-28T19:29:43.505968Z",
  "timestamp_end": "2025-03-28T19:29:43.506156Z"
}
```
