### DISCUSSION TITLE
Configure DataDog agent to send HTTP metric data to Vector

### DISCUSSION THREAD

**Discussion by fenill1** [vectordotdev/vector#22773] [Q&A]
Hello,

I have a Datadog agent to send HTTP metric data to vector, however I am not able to see any HTTP metric data if reading through the <component_id>.metrics  as suggested in the Vector documentation. [configuring-the-datadog-agent](https://vector.dev/docs/reference/configuration/sources/datadog_agent/#configuring-the-datadog-agent)

This is the datadog configuration (yaml)
```
vector:
 metrics.enabled: true
 metrics.url: http://0.0.0.0:6901
``` 

And this is the vector configuration (yaml)
```
sources:
  sample_agent:
    type: "datadog_agent"
    multiple_outputs: true
    address: "0.0.0.0:6901"

sinks:
  sample_metrics:
    type: "console"
    inputs:
      - "sample_agent.metrics"
    encoding:
      codec: "json"
```

The only way I am able to see any HTTP metric data is if reading through <component_id>.traces. 

This is the datadog configuration (yaml)
```
vector:
 traces.enabled: true
 traces.url: http://0.0.0.0:6901
``` 

And this is the vector configuration (yaml)
```
sources:
  sample_agent:
    type: "datadog_agent"
    multiple_outputs: true
    address: "0.0.0.0:6901"

sinks:
  sample_traces:
    type: "console"
    inputs:
      - "sample_agent.traces"
    encoding:
      codec: "json"
```

But for this to show 100% accurate data we have to set the -Ddd.trace.sample.rate=1 which is not sustainable. 

The question I have and would like assistance on is to understand if there is a better way to read through the HTTP metric data instead of doing it through traces. Is there anything else I need to do in order to get Datadog to output HTTP metric data to vector?

Thanks in advance for any help!
