### DISCUSSION TITLE
Batch Gauge Metrics from Prometheus Remote Write to InfluxDB v2 Without Aggregation

### DISCUSSION THREAD

**Discussion by adiwab** [vectordotdev/vector#22863] [General] [answered]
I’m using Vector with Prometheus Remote Write (beta) as a source and InfluxDB v2 as a sink. Prometheus sends gauge metrics (e.g., cpu_usage) every 15 seconds, but I want to batch these data points over 2 minutes before writing them to InfluxDB.

Current Behavior:
- Without Buffer: Data points are written immediately to InfluxDB (desired).
- With Buffer: Only the last data point is sent (e.g., 8% instead of all values like 30%, 32%, 40%, 8%).  (not desired).
- With Aggregation: Only the last data point is sent (e.g., 8% instead of all values like 30%, 32%, 40%, 8%).  (desired). (https://vector.dev/docs/reference/configuration/transforms/aggregate/)

Attempted Solutions:
- Buffer Configuration: Tried memory/disk buffers with max_events and max_size, but only the latest point is retained.
- Batch Settings: Added max_size to the InfluxDB sink, but no improvement.
- Timestamp Preservation: Verified Prometheus timestamps are present in the events, but InfluxDB still overwrites values.

Configuration Example:

```
sources:
  prometheus_source:
    type: prometheus_remote_write
    address: 127.0.0.1:9999
    auth:
      username: user
      password: pass

sinks:
  influxdb2:
    type: influxdb_metrics
    inputs: 
      - prometheus_source
    endpoint: https://my.url.dev/
    org: myorg
    bucket: mybucket
    token: mytoken
    tags:
      environment: 'prod'
    #buffer:
    #  type: disk
    #  max_size: 268435488
    #  when_full: block
```

Question:
How can I configure Vector to preserve and batch all gauge data points (with distinct timestamps) over a 2-minute window, rather than aggregating or overwriting them?

**Comment by adiwab** [comment, marked as answer]
**Info:**
Batching generally means that timestamp information will be aggregated away, and metric-specific compression will be applied to improve pipeline performance.

Therefore, this behavior is correct and intentional.

**Possible Solutions:**
1. Reduce data throughput using transforms/aggregate with an appropriate interval.
→ This calculates the respective value depending on the selected mode.
2. Using buffers or batch always forwards the last received metric.
→ Depending on the use case, important information might be lost.
3. Add a unique tag to the dataset using transforms/remap (e.g., a unique_id or a timestamp).
→ This doesn't align with Vector's intended purpose, but it enables the use of buffer and batch without losing individual data points.

Example:
```
transforms:
  add_unique_tag:
    type: remap
    inputs: [prom]
    source: |-
      .tags.timestamp = to_string(now())
      # OR
      .tags.unique_id = uuid_v4()
```
