### DISCUSSION TITLE
How to get the `sample` transform type to work?

### DISCUSSION THREAD

**Discussion by V3XATI0N** [vectordotdev/vector#22869] [Q&A]
I have the following sample:
```yaml
      dd_log_tags:
        type: sample
        inputs:
          - dd_log_tags_pre
        group_by: "{{ service }}"
        ratio: 0.1
        exclude: '.aggregator == "datadog"'
```

But this does not actually apply a sample ratio, I am still getting 100% of tags from the `dd_log_tags_pre` transform (which works fine). Every single event has an `aggregator` key, and some of those keys are `datadog`. I just want to take everything that *isn't* set to `datadog` and decrease it by 90% per `service`. As far as I can tell from the docs, this is correct, but it does nothing.
