### DISCUSSION TITLE
Issue with OTLP Source and Sink - Receiving 500 Internal Server Error

### DISCUSSION THREAD

**Discussion by LinTechSo** [vectordotdev/vector#22885] [Q&A]
Hi,
I'm new to using Vector and OpenTelemetry, and I'm encountering an issue when trying to send logs from a client Vector instance to a server Vector instance using the opentelemetry source and sink.

Here's my client Vector configuration:

```
otlp_sink:
    type: opentelemetry
    inputs:
      - demo_logs
    protocol:
      encoding:
        codec: json
      headers:
        X-Scope-OrgID: "demo-org"
        User-Agent: "vector-client"
        X-Consumer-Username: "demo-user"
      uri: "http://127.0.0.1:4318"
      type: http
```
And here's the relevant part of my server Vector configuration:

```
sources:
  internal_metrics:
    type: internal_metrics
  otlp_input:
    type: opentelemetry
    grpc:
      address: "0.0.0.0:4317"
    http:
      address: "0.0.0.0:4318"
      headers:
        - X-Scope-OrgID
        - User-Agent
        - X-Consumer-Username
```

I'm seeing the following error message in my client Vector logs:

```
2025-04-15T16:32:04.389932Z  WARN sink{component_kind="sink" component_id=otlp_sink component_type=opentelemetry}:request{request_id=1}: vector::sinks::util::retries: Retrying after response. reason=Http Status: 500 Internal Server Error internal_log_rate_limit=true
```

From what I understand, this minimal configuration should work—especially since both instances are using 4318 otlphttp. Am I missing something in the setup? Any guidance or insight would be greatly appreciated.

Thank you for your time and assistance!
version: vector 0.45.0
