### DISCUSSION TITLE
Is there any way to access source config attribute in VRL

### DISCUSSION THREAD

**Discussion by liuyangc3** [vectordotdev/vector#22891] [Q&A] [answered]
for example:
```yaml
sources:
  my_source:
    type: http_client
    endpoint: https://google.com

transforms:
  my_transform:
    type: remap
    inputs:
      - my_source
    source: |
      # how can I get the source config attributes like:
      my_source.endpoint
      my_source.type      
```
