### DISCUSSION TITLE
`vector validate` emits error `TCP bind failed: Address already in use (os error 98)` when doing systemd reload

### DISCUSSION THREAD

**Discussion by techministrator** [vectordotdev/vector#22916] [Q&A] [answered]
Hi Vector maintainers, 

I see that the command `vector validate` has problem with the case of reloading. 

I'm using Vector version `0.44.0`.

This is the systemd default configurations for vector.service on Ubuntu 22.04.

```
# /lib/systemd/system/vector.service
[Unit]
Description=Vector
Documentation=https://vector.dev
After=network-online.target
Requires=network-online.target

[Service]
User=vector
Group=vector
ExecStartPre=/usr/bin/vector validate
ExecStart=/usr/bin/vector
ExecReload=/usr/bin/vector validate
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
AmbientCapabilities=CAP_NET_BIND_SERVICE
EnvironmentFile=-/etc/default/vector
# Since systemd 229, should be in [Unit] but in order to support systemd <229,
# it is also supported to have it here.
StartLimitInterval=10
StartLimitBurst=5
[Install]
WantedBy=multi-user.target
```

Here is the simple vector config file with datadog agents

```yaml
sources:
  datadog_agents:
    type: datadog_agent
    address: 0.0.0.0:9000
    disable_logs: true
    disable_traces: true
    store_api_key: true

sinks:
  datadog_platform:
    inputs:
      - datadog_agents
    type: datadog_metrics
```

With that config, the running process of vector already takes the port `9000`. So when running `vector validate`, it would always result in this error because obviously the port is still being used by the current `vector` process:

```
$ vector validate
2025-04-21T10:57:33.627587Z  INFO vector::app: Log level is enabled. level="INFO"
√ Loaded ["/etc/vector/vector.yaml"]

Component errors
----------------
x Source "datadog_agents": TCP bind failed: Address already in use (os error 98)
```

I can totally just run the `kill -HUP <pid>` but I think it would be better if the vector validate is able to handle such above case.
