### DISCUSSION TITLE
How do I send an event to splunk using the splunk_hec_logs sink but keep metadata as metadata?

### DISCUSSION THREAD

**Discussion by bcronrath** [vectordotdev/vector#23006] [Q&A]
What I mean is, if I have an input that sends something like:
{
"event":"bunch of log data here",
"index":"index here",
"sourcetype":"sourcetype here"
}
How do I get it so the index and sourcetype and only sent as metadata, and not part of the event itself that makes it into the splunk event?  For example, using one of splunk docs examples:

curl "https://mysplunkserver.example.com:8088/services/collector?channel=00872DC6-AC83-4EDE-8AFE-8413C3825C4C" \
    -H "Authorization: Splunk CF179AE4-3C99-45F5-A7CC-3284AA91CF67" \
    -d '{"event": "Hello, world!", "sourcetype": "manual"}'
    
    This would show up in splunk just as "hello, world!" and the metadata for sourcetype would be set to "manual", but if I send this through the vector splunk_hec_logs sink, I would get an event that is literally that whole json blob {"event": "Hello, world!", "sourcetype": "manual"}

**Comment by satellite-no** [comment]
the [Splunk HEC logs](https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/) sink has fields you can use to define. the metadata so if you had an event in vector that is 

```json
{
"message":"this is a tomato",
"index":"veggies",
"sourcetype":"tomato"
"timestamp": "2024-05-05T12:12:12Z"
}
```

and the splunk hec sink was 
```yaml
sinks:
  my_sink_id:
    type: splunk_hec_logs
    encoding:
      codec: text
    inputs:
      - my-source-or-transform-id
    compression: none
    endpoint: https://http-inputs-hec.splunkcloud.com
    endpoint_target: event
    index: "{{ index }}"
    sourcetype: "{{ sourcetype }}"
    timestamp_key: timestamp
```

it would send the value of `.message` to the index `veggies`, with a sourcetype of `tomato`.

**Reply by bcronrath** [reply]
None of the works, curious if you've tried yourself to see how it looks in Splunk?  I had pretty much an entirely the same configuration as that already.  From my perspective the splunk sink just doesn't work properly at all, maybe I'm missing something but genuinely curious if anyone has gotten it to work correctly.  It continually just sends the entire incoming json and does zero effort to massage away any attached metadata from the event.

To resolve I just ended up using an http sink, works plenty fine and does exactly what I want, and not hard at all to use it with the splunk HEC.

**Reply by themasch** [reply]
so for me, these failed horrible: 
```
    index: "{{ index }}"
    sourcetype: "{{ sourcetype }}"
```

because they just created 1000s of " template_failed" events in seconds. 

I think `{{ .index }}` and `{{ .sourcetype }}` is more correct, but event that breaks if a single message is missing one of those fields. AFAICT there is no way to define a fallback for that. 

Heres what I am currently using: 

```yaml
sinks:
    splunk_out:
        type: "splunk_hec_logs"
        inputs:
            - "list"
            - "your"
            - "streams"
        endpoint: "https://${SPLUNK_HOST}:${SPLUNK_PORT}"
        default_token: "${SPLUNK_TOKEN}"
        index: "${SPLUNK_INDEX_NAME}"
        encoding:
            codec: "json"
        tls:
            verify_certificate: true
            verify_hostname: true
```

An putting `sourcetype` and `source` fields in message makes splunk to automatically pick them up. 
My problems right now are just that with how fluentbit worked, those fields where just metadata and not directly listed along the other event fields in splunk, while with vector those show as normal fields. So not sure right now whats wrong there. But submitting logs like this works for me.
