### DISCUSSION TITLE
Does not read file changes

### DISCUSSION THREAD

**Discussion by Toveal** [vectordotdev/vector#23009] [Q&A]
Hello
Vector 0.46.1 is installed as a service in Windows
Sometimes when modifying a file (added some lines) the changes are not read or processed. They are processed only after adding new changes. And then 2 changes are processed at once
I looked at the contents of the file through a text editor, the changes are there. The line ends with \n. The buffer is not filled. Communication with sink is stable. All tracked files have full permissions

Config:
```toml
data_dir = "C:/Files/VectorFiles/data"

[sources.logs]
type = "file"
include = ["C:/Files/20??????.log"]
ignore_older_secs = 86400
read_from = "end"

[transforms.add_metadata]
type = "remap"
inputs = ["logs"]
source = '''
.terminal_id = "SM-12"
'''

[sinks.vector]
type = "vector"
inputs = ["add_metadata"]
address = "172.25.12.11:6000"

[sinks.vector.buffer]
type = "disk"
max_size = 536_870_912
when_full = "block"
```

**Comment by Toveal** [comment]
I changed the config as below, hoping it would help — but it didn’t make any difference.

```toml
data_dir = "C:/Files/VectorFiles/data"

[sources.logs]
type = "file"
include = ["C:/Files/20??????.log"]
ignore_older_secs = 86400
fingerprint.strategy = "checksum"

[transforms.add_metadata]
type = "remap"
inputs = ["logs"]
source = '''
.terminal_id = "SM-12"
'''

[sinks.vector]
type = "vector"
inputs = ["add_metadata"]
address = "172.25.12.11:6000"

[sinks.vector.buffer]
type = "disk"
max_size = 536_870_912
when_full = "block"
```
