### DISCUSSION TITLE
Dynamic routing in one thread

### DISCUSSION THREAD

**Discussion by Toveal** [vectordotdev/vector#23019] [Q&A] [answered]
Hello. I need to send route data in one thread based on the identifier. Now my configuration looks like this:

```toml
[transforms.route_by_id]
type = "route"
inputs = ["remap_log"]
route.id1 = '.terminal_id == "1"'
route.id2 = '.terminal_id == "2"'
route.id3 = '.terminal_id == "3"'
```

Next I create a sink file for each route:

```toml
[sinks.http-out-id1]
type = "http"
inputs = ["route_by_id.id1"]
uri = "http://localhost:6002/event"
method = "post"
encoding.codec = "json"
request.concurrency = 1
```

Is there any way to improve such a configuration?
