### DISCUSSION TITLE
S3 Batching with VRL Template syntax Key_prefix

### DISCUSSION THREAD

**Discussion by satellite-no** [vectordotdev/vector#23013] [Q&A] [answered]
Quick question on the expected behavior of batching to s3.  I have the below s3 config for my sink which is accepting a lot of different data sources.  Based on this config would my assumption of multiple 30MB files being written to s3 OR 1 file a every 60 seconds be correct?  We are seeing hundreds of thousands of small 10kb files being written in reality.  The running theory we are testing is that the VRL Syntax is causing the files to be closed and written to s3 before they hit either condition.  

For an example we have a stream of two data sources with different `.unmapped.dl_partition_class_name` so sense the stream is alternation the variable its causing the files to be written premature.  

s3:
```yaml
type: aws_s3
inputs:
  - 'ocsf_*'
bucket: "dest_bucket_for_ocsf"
region: "us-east-1"
key_prefix: "ocsf/{{.unmapped.dl_partition_class_name}}/{{.unmapped.dl_partition_vendor_name}}/%Y%m%d/"
compression: zstd

healthcheck:
  enabled: true
  timeout_secs: 15

batch:
  max_bytes: 30973400 # 30 MB
  timeout_secs: 60

encoding:
  codec: json
```

**Comment by pront** [comment]
When batching is configured like this:

```yaml
batch:
  max_bytes: 30973400  # 30MB
  timeout_secs: 60     # 60s
```

Vector should flush a batch to S3 when either:

* The batch reaches 30MB
* 60 seconds pass since the batch started
* Or per when https://vector.dev/docs/reference/configuration/sinks/aws_s3/#batch.max_events are accumulated

However, a separate batch is maintained for each unique S3 object key, and in your case, the key is dynamically derived from:

`ocsf/{{.unmapped.dl_partition_class_name}}/{{.unmapped.dl_partition_vendor_name}}/%Y%m%d/`

If `.unmapped.dl_partition_class_name` or `.unmapped.dl_partition_vendor_name` alternates frequently (e.g. for every event), then Vector will never accumulate a large batch, because each event is routed to a different S3 object key.
