### DISCUSSION TITLE
Buffering an event until a second event is received

### DISCUSSION THREAD

**Discussion by Toveal** [vectordotdev/vector#23032] [Q&A]
Sometimes vector does not send an event until the next event arrives. The second event ‘Pushes’ the first event. How can I fix this?
My Sink config:

```toml
[sinks.http-out-SM-5-test]
type = "http"
inputs = ["route_by_kassa.SM-5"]
uri = "http://localhost:3001/test-event"
method = "post"
encoding.codec = "json"

request.headers.content_type = "application/json"
request.concurrency = 1
request.timeout_secs = 31536000

buffer.type = "disk"
buffer.max_size = 536_870_912
buffer.when_full = "block"
```
