### DISCUSSION TITLE
aws_cloudwatch_logs sink in failing in vector image (0.28.1-distroless-libc)

### DISCUSSION THREAD

**Discussion by shreyasarani23** [vectordotdev/vector#23031] [Q&A] [answered]
Below is my sink which will send some application logs to aws_cloudwatch. Currently I have 2 replicas for vector deployment the 1st pod is running fine without any error and in the 2nd pod I am getting the below error. I understand that I am using little older version of vector image: (0.28.1-distroless-libc) is the below error know issue in the older versions of vector image? By upgrading the vector to latest version will the issue be resolved? 

```
app-logs-cloudwatch:
    type: aws_cloudwatch_logs
    inputs:
    - app-logs-filter-K8-log
    region: "us-east-1"
    group_name: "/k8-logs/app"
    stream_name: |-
      {{ print "app-k8-logs"}}-%Y.%m.%d
    encoding:
      codec: json
 ```
 Below is the error I am getting
 
 ```
 2025-05-12T07:22:57.511086Z ERROR vector::topology::builder: msg="Healthcheck failed." error=DescribeLogGroups failed: failed to construct request: Failed to load credentials from the credentials provider: Credentials provider timed out after 5 seconds component_kind="sink" component_type="aws_cloudwatch_logs" component_id=app-logs-cloudwatch component_name=app-logs-cloudwatch
 
 ```
