### DISCUSSION TITLE
Log namespace configuration for sink

### DISCUSSION THREAD

**Discussion by piclemx** [vectordotdev/vector#23088] [General] [answered]
Hello,

I'm trying to make my configuration of vector that would contains the following.

I want to use the `kafka.topic`, `kafka.partition` and `kafka.offset` to populate the field of `sourcetype` with something like

Should result into this `topic::partition::offset`

I have enable the `log_namespace` to true also globally.

Source:
- Kafka

Sink:
- Splunk HEC Logs

**Comment by pront** [comment]
Preserving discord discussion here:

piclem — 11:44
What would be the way to get the source metadata from the remap

Pavlos — 11:45
```
event = .
field_from_event = .foo

all_metadata = %
tags = %datadog_agent.ddtags
timestamp = %vector.ingest_timestamp
```

Sample from https://vector.dev/blog/log-namespacing/

Namespace feature guide: https://vector.dev/guides/level-up/log_namespace/

**Reply by piclemx** [reply]
Seems that event with trying to do a `remap` transformation it doesn't work.

```yaml
    transforms:
      timestamp:
        type: remap
        inputs: 
            - '*'
        source: |
          set_semantic_meaning(.["@timestamp"], "timestamp")
          .source = "kafka::{{ %kafka_in.topic }}::{{ %kafka_in.partition }}::{{ %kafka_in.offset }}"
   ```

I did switch a little bit since our conversation.

```yaml
    sources:
        kafka_in:
            type: kafka
            bootstrap_servers: brokers1:9092
            topics:
                - topic1
            group_id: vector-group-id
            auto_offset_reset: latest
            decoding:
                codec: json

    transforms:
      timestamp:
        type: remap
        inputs: 
            - '*'
        source: |
          log(.message."@timestamp", level: "info")
          set_semantic_meaning(.message."@timestamp", "timestamp")
          topic = %kafka_in.topic
          log(topic, level: "info")
          #partition = to_string(%kafka_in.partition) ?? "partition" 
          #offset = to_string(%kafka_in.offset) ?? "offset"
          #.source = "kafka::" + topic + "::" + partition + "::" +  offset
```


Seems that I always don't have the timestamp correctly. so the `set_sementic_meaning` seems to not work because my field seems empty.
