### DISCUSSION TITLE
Performance issues

### DISCUSSION THREAD

**Discussion by satellite-no** [vectordotdev/vector#23124] [Q&A]
Background: I have a large Vector deployment Im running into performance issues with.  Im seeing around 50MB/s average on my source & sink with 16vCPU nodes.  Based on the [capacity planning](https://vector.dev/docs/setup/going-to-prod/sizing/) guide I'd expect this to be more like 160MB/s.  Now with that being said our transform rate IS around 160MB/s.  Note CPU on these instances if low <50% but RAM is almost always maxed out (disk buffer in use). 

Question:
1. What metric is best to use to compare the throughput rate with the estimated? 
2. How do I know where my bottle neck is?  I'm assuming its a sink but im only sending data to s3 & Clickhouse based on some testing I think s3 is the issue but I'd assume I could write to s3 from an AWS VPC very quickly.  

Any ideas to get these systems performing as expected would be appreciated.

**Comment by jszwedko** [comment]
Hi @satellite-no ,

Can you share your configuration? That might help us help you identify bottlenecks.

To identify bottlenecks in the topology, I usually look at the `utilization`internal metric. This metric is an indication of the ratio of time a given component spends processing vs. waiting for input. Typically the first component in a given topology path that has a `utilization` close to 1 is the bottleneck as it is never waiting for input.

**Reply by satellite-no** [reply]
I have a complex config so Im not certain i can share the entire thing but below is my s3 configuration and a generalized flow of data. 

```yaml
type: aws_s3
inputs:
  - 'route_ocsf_to_s3.all_vendors'
bucket: "bucket_name"
region: "us-east-1"
key_prefix: "ocsf/{{.unmapped.dl_partition_class_name}}/{{.unmapped.dl_partition_vendor_name}}/%Y%m%d/"
compression: zstd

healthcheck:
  enabled: true
  timeout_secs: 15

batch:
  max_bytes: 5368709000 # 5GB
  timeout_secs: 60

encoding:
  codec: json
  
buffer:
  type: "disk"
  max_size: 200000000000 # 200GB
  when_full: "block"
 ```
 
 source (s3) -> remap -> sink (vector) -> source (vector) -> exclusive_route -> exclusive_route -> remap -> remap -> exclusive route) -> sink 
 
 My utilization percents are normally less than 50% across all sources, sinks, and transforms.
