### DISCUSSION TITLE
Datadog Logs Source Environment Variable Injection

### DISCUSSION THREAD

**Discussion by jspdhillon** [vectordotdev/vector#23122] [Q&A] [answered]
Hey, i'm running vector agents in my k8s cluster. I have a vector-agent running on port 6767. My goal is to have `datadog-agent` pass logs to the `vector-agent` running on the same node so host tags don't get obfuscated. 

Here's my `datadog.yaml` helm chart agent configuration:
```
agents:
    useConfigMap: true
    customAgentConfig:
      vector:
        logs:
          enabled: true
          url: "http://$(DD_AGENT_HOST):6767"
```

`vector-agent.yaml`
```
...
    - containerPort: 6767
      hostPort: 6767
      name: datadog-logs
      protocol: TCP
...
      datadog_logs_source:
        type: datadog_agent
        address: 0.0.0.0:6767
        disable_metrics: true
        disable_traces: true
...
```

The variable injection in datadog.yaml does not work in `customAgentConfig`, I have tried:

- [autodiscovery template variables](https://docs.datadoghq.com/containers/guide/template_variables/) %%env_DD_AGENT_HOST%%
- shell substitution $(DD_AGENT_HOST)
- yaml substitution ${DD_AGENT_HOST}

Is it even possible to inject an environment variable into this field?

Alternatively, is there a parameter to run `vector-agent` on the `hostNetwork` so I can just refer to localhost instead of determining the host's ip using the downstream api and injecting that into my `datadog` configuration?

**Comment by pront** [comment]
Hi @jspdhillon, I see that this discussion was closed. Did you figure out a solution?

**Reply by jspdhillon** [reply, marked as answer]
Yeah I figured it out, you need to set this environment variable https://github.com/DataDog/datadog-agent/blob/b60575ea4f8cefde88eb0bc3dd5d5fb74d917cac/pkg/config/config_template.yaml#L588-L592 which will let you override the upstream endpoint and allow for you to interpolate strings/other environment variables.

```   
 - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: DD_OBSERVABILITY_PIPELINES_WORKER_LOGS_URL # URL endpoint for the Observability Pipelines Worker to send logs to
    value: "http://$(HOST_IP):6767"
```
