### DISCUSSION TITLE
Memory enrichment table: Difference between global `enrichment_tables` config vs usage as sink

### DISCUSSION THREAD

**Discussion by ChristianCiach** [vectordotdev/vector#23150] [Q&A] [answered]
I am trying to wrap my head around the the memory enrichment tables as highlighted in https://vector.dev/highlights/2025-02-24-memory_enrichment_table/

I pretty much understand everything written in that article, until the very last section called "Use as a sink":

What is the difference between defining the enrichment table using the global configuration option `enrichment_tables` vs configuring it as a sink with `type: memory_enrichment_table`?

* Both configurations use an `inputs` of sources or transformers to populate the table and also share the exact same configuration options like `tty`.
* What is the name of the enrichment table when defining it as a sink, to reference it using the `get_enrichment_table_record` VRL function? Is it the name of the sink?
* When would I prefer the sink over the global configuration or vice versa?
* Why is the sink type `memory_enrichment_table` not listed at https://vector.dev/docs/reference/configuration/sinks/?

I am so confused.

Kindly pinging @esensar, because I strongly assume he knows it best :)

**Comment by ChristianCiach** [comment]
I think I might get it, after looking at the sources. The last section of https://vector.dev/highlights/2025-02-24-memory_enrichment_table/ is highly misleading, maybe even wrong. This is my understanding now:

* You never explicitly define a memory enrichment table as a sink. The sink will be implicitly created from the globally configured enrichment tables having `type: memory`.
* The name of the sink is identical to the name of the enrichment table. This is not documented *anywhere*, but it also doesn't really matter, since we never explicitly reference a sink as outputs. Instead, it's the other way around: Sinks define sources and transformers *as inputs*, which we do in `enrichtment_tables.[id].inputs`, which is btw an attribute **not documented at all** at https://vector.dev/docs/reference/configuration/global-options/. In fact, when having an enrichment_table of type `memory`, this enrichment_table can then be configured with all common attributes of a sink. Weird!

Quote from the linked article:

> For example, here is how to introduce this new component as a sink if you have another source that can populate the cache:
> ```yaml
>  memory_table_sink:
>    inputs: [ "another_source_or_transform" ]
>    type: memory_enrichment_table
>    ttl: 60
>    flush_interval: 5
> ```

This sentence probably tries to convey the fact that the configured enrichment table automatically **generates** a sink that looks roughly like that YAML snippet. (Although that is not entirely correct, since the name of the sink will be `memory_table`, not `memory_table_sink`, *I think*)

**Reply by ChristianCiach** [reply]
I think this is all very confusing. I wonder why the sinks are even created automatically, instead of properly exposing a new sink type `memory_enrichment_table` to the user. Something like this:

```yaml
enrichment_tables:
  some_cache:
    type: memory
    ttl: 60
    flush_interval: 5

sinks:
  some_cache_sink:
    type: memory_enrichment_table
    inputs: [a_source_or_transformer]
    table_key: some_cache
```

This would mean that there could be multiple sinks that contribute to the same table. This may be the reason it was not done this way.

I just see that an enrichment table can now be used as a source by configuring `enrichment_tables.[id].source_config`. Wouldn't it make a lot of sense to introduce an analogous `enrichment_tables.[id].sink_config`?:

```yaml
enrichment_tables:
  some_cache:
    type: memory
    ttl: 60
    flush_interval: 5
    sink_config:
      inputs: [another_source_or_transform]
      sink_key: some_cache_sink  # could default to the name of the table
```

@esensar Did i get any of that wrong?
