### DISCUSSION TITLE
Problems with aws auth in http_client and prometheus_scrape sources

### DISCUSSION THREAD

**Discussion by T-Sh** [vectordotdev/vector#23164] [Q&A] [answered]
According to docs, [prometheus_scrape](https://vector.dev/docs/reference/configuration/sources/prometheus_scrape/#auth.auth) and [http_client](https://vector.dev/docs/reference/configuration/sources/http_client/#auth.auth) sources support aws auth in outcoming request. I've tried next configurations:
```
sources:
  prometheus-source:
    type: prometheus_scrape
    endpoints:
     - http://127.0.0.1/metrics/
    scrape_interval_secs: 30
    scrape_timeout_secs: 20
    auth:
      strategy: aws
      service: vector
      auth:
        secret_access_key: <access_key>
        access_key_id: <key_id>
        region: us-east-1
  http-source:
    type: http_client
    endpoint: http://127.0.0.1/metrics/
    auth:
      strategy: aws
      service: vector
      auth:
        secret_access_key: <access_key>
        access_key_id: <key_id>
        region: us-east-1
```

But both sources don't send auth headers in requests (based on vector debug logs and actual request in polled service). Debug logs from vector:
```
DEBUG source{component_kind="source" component_id=http-source component_type=http_client}:http: vector::internal_events::http_client: Sending HTTP request. uri=http://127.0.0.1/metrics/ method=GET version=HTTP/1.1 headers={"accept": "text/plain", "user-agent": "Vector/0.47.0 (x86_64-unknown-linux-gnu 3d5af22 2025-05-20 13:53:41.638057046)", "accept-encoding": "identity"} body=[empty]

DEBUG source{component_kind="source" component_id=prometheus-source component_type=prometheus_scrape}:http: vector::internal_events::http_client: Sending HTTP request. uri=http://127.0.0.1/metrics/ method=GET version=HTTP/1.1 headers={"accept": "text/plain", "user-agent": "Vector/0.47.0 (x86_64-unknown-linux-gnu 3d5af22 2025-05-20 13:53:41.638057046)", "accept-encoding": "identity"} body=[empty]
```

@johannesfloriangeiger I assume you added this feature in https://github.com/vectordotdev/vector/pull/22744. Can you help what I am doing wrong and how to make it work?
