### DISCUSSION TITLE
TCP/TLS performance issue

### DISCUSSION THREAD

**Discussion by snarbles** [vectordotdev/vector#23181] [Q&A] [answered]
Any way to improve Event Per Second (EPS) using TCP/TLS?  We seem to be throttled around 40k EPS which is less than our UDP which is about 80k EPS:
```  
  source_palo_tls:
    type: syslog
    address: 0.0.0.0:10001
    mode: tcp
    receive_buffer_bytes: 268435456
    max_length: 409600
    tls:
      enabled: true
      crt_file: /etc/vector/cert/logs.pem
      key_file: /etc/vector/cert/logs.key
      ca_file: /etc/vector/cert/ca_chain.pem
      # if sending system presents a cert, set to true
      verify_certificate: false
      verify_hostname: false
```
      
   
We also set these settings in sysctl.d:
```
net.core.rmem_default = 268435456
net.core.wmem_default = 268435456
net.core.rmem_max = 268435456
net.core.wmem_max = 268435456
net.core.netdev_max_backlog = 2000

net.ipv4.tcp_rmem = 8192 2097152 268435456
net.ipv4.tcp_wmem = 4096 524288 268435456
```
