### DISCUSSION TITLE
Can I get the errors about excluded filesystems to go away?

### DISCUSSION THREAD

**Discussion by jerrac** [vectordotdev/vector#23203] [Q&A]
```
Jun 13 13:23:47 myhost vector[1123893]: 2025-06-13T20:23:47.769981Z ERROR source{component_kind="source" component_id=host_metrics component_type=host_metrics}: vector::internal_events::host_metrics: Failed to load partitions info. mount_point="/run/docker/netns/ingress_sbox" error=FFI function "statvfs" call failed: Permission denied (os error 13) error_type="reader_failed" stage="receiving" internal_log_rate_limit=true
```

I have `/run/docker/netns/ingress_sbox` excluded. Both via mountpoints, and the filesystem type "nsfs".

```yaml
host_metrics:
              type: host_metrics
              filesystem:
                  mountpoints:
                      excludes:
                          - "/run/docker/netns*"
                  filesystems:
                      excludes:
                          - "tmpfs"
                          - "devtmpfs"
                          - "devfs"
                          - "iso9660"
                          - "overlay"
                          - "aufs"
                          - "squashfs"
                          - "nfs"
                          - "nsfs"
              network:
                  devices:
                    excludes:
                      - "veth*"
```
JetBrains AI says that the exclusion happens after the filesystem is checked, and that is why I'm still seeing those logs.

Is there a way to tell Vector it doesn't need to error on excluded filesystems?
