### DISCUSSION TITLE
KAFKA sink SCRAM-SHA-256 and SCRAM-SHA-512  issue

### DISCUSSION THREAD

**Discussion by huaqiangli** [vectordotdev/vector#23219] [Q&A]
I tried vector 0.42 and 0.47 version and have the same sasl probom,   mechanism PLAIN works ,  SCRAM-SHA-256 and SCRAM-SHA-512 failed.  

from the vector log, it reports such as   librdkafka: FAIL  SASL authentication error:Authentication failed during authentication due to invalid credentials, but i use kafka scripts in apache/kafka image to test ,  SCRAM-SHA-256 and SCRAM-SHA-512 work well.

**Comment by huaqiangli** [comment]
```yaml
sinks:
    vector:
      type: kafka
      bootstrap_servers: "192.168.167.55:29999"
      inputs:
        - file_csv
      topic: "test"
      encoding:
        codec: "json"
      sasl:
        enabled: true
        mechanism: "SCRAM-SHA-512"
        username: "client-user"
        password: "client-secret"
      librdkafka_options:
         security.protocol: "SASL_PLAINTEXT" 
```
