### DISCUSSION TITLE
What is the best way to filter logs with lowest cpu consumption?

### DISCUSSION THREAD

**Discussion by alpiua** [vectordotdev/vector#7159] [Q&A] [answered]
Hello,

Can someone help here?

I have a question about "filter" transform.
I have a config like this:
```
[sources.in]
  type = "file"
  include = ["/opt/app/*/logs/*/*.log"]
  fingerprint.strategy = "device_and_inode"

  [sources.in.multiline]
     start_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
     mode = "halt_before"
     condition_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
     timeout_ms = 999999999


[transforms.in_filter]
  type = "filter"
  inputs = ["in"]
  condition.type = "check_fields"
  condition."message.not_contains" = "NOT_FOUND - no exchange"
  condition."message.not_regex" = " (INFO|DEBUG|TRACE) "
```
the problem is that sometimes in the app I have a vast amount of messages coming to files, about 1-2 thousands per one second.
This activity lasts for about one hour.
And vector start consuming 3+ Gb of ram and making performance impact on the running node.

Is there is a better way to reduce ram and cpu consumption while have all messages with "INFO" filtered?

![зображення](https://user-images.githubusercontent.com/14225967/115148784-d4f88880-a069-11eb-8d1c-479f269367f5.png)

**Comment by jszwedko** [comment]
Hi @alpi-ua !

That is a lot of memory use! Would you be able to share a few more details:

* The number of files that are typically being processed
* Is the spike distributed across those files? Or is the spike just in one file?
* The rest of the config, including sinks

cc/ @blt @lukesteensen you might be interested in this.

**Reply by alpiua** [reply]
Here is my config
```toml
[api]                                                                                                                                                  
  enabled = true                                                                                                                                       
                                                                                                                                                       
[sources.journal]                                                                                                                                      
  type = "journald"                                                                                                                                    
  exclude_units = ["kernel","vector","telegraf","crond","init.scope","dnf-makecache.service","rsyslog"]                                      
                                                                                                                                                       
[sources.app_stderror]                                                                                                                               
  type = "file"                                                                                                                                        
  include = ["/opt/app/*/logs/stderror.log"]                                                                                                    
  fingerprint.strategy = "device_and_inode"                                                                                                            
  [sources.app_stderror.multiline]                                                                                                                   
    start_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'                                                                                                      
     mode = "halt_before"                                                                                                                              
     condition_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'                                                                                                 
     timeout_ms = 999999999                                                                                                                            
                                                                                                                                                       
[sources.app]                                                                                                                                        
  type = "file"                                                                                                                                        
  include = ["/opt/app/*/logs/*/*.log"]                                                                                                          
  fingerprint.strategy = "device_and_inode"                                                                                                            
                                                                                                                                                       
  [sources.app.multiline]                                                                                                                            
     start_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'                                                                                                     
     mode = "halt_before"                                                                                                                              
     condition_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'                                                                                                 
     timeout_ms = 999999999                                                                                                                            
                                                                                                                                                                                                                                                     
[transforms.app_filter]                                                                                                                              
  type = "filter"                                                                                                                                      
  inputs = ["app"]                                                                                                                                   
  condition.type = "check_fields"                                                                                                                      
  condition."message.not_contains" = "NOT_FOUND - no exchange"                                                                                         
  condition."message.not_regex" = " (INFO|DEBUG|TRACE) "                                                                                               
                                                                                                                                                       
                                                                                                                                                       
[sinks.app_prod]                                                                                                                                     
  type = "vector"                                                                                                                                      
  inputs = ["app_filter","app_stderror"]                                                                                                           
  address = "server:5001"                                                                                                               
  healthcheck = true                                                                                                                                   
  buffer.max_size = 10100000                                                                                                                           
  buffer.type = "disk"                                                                                                                                 
  buffer.when_full = "block" 

[sinks.system]                                                                                                                                         
  type = "vector"                                                                                                                                      
  inputs = ["journal"]                                                                                                                                 
  address = "server:5000"                                                                                                               
  healthcheck = true                                                                                                                                   
  buffer.max_size = 10100000                                                                                                                           
  buffer.type = "disk"                                                                                                                                 
  buffer.when_full = "block"
```

btw, with 'vector top' I can't see any activity on transform.app_filter - it showing N/A nevertheless showing activity on source.app.
I have timeout_ms 99999999 because of bug I [faced](https://github.com/timberio/vector/issues/6855) before
