### DISCUSSION TITLE
Buffering and data loss prevention on k8s

### DISCUSSION THREAD

**Discussion by asafdl** [vectordotdev/vector#8563] [Q&A] [answered]
Hi, I'm looking to configure buffering for my sink, with the intent of having 0 data loss. I saw in the docs that you suggest not using aws gp2 (what we are using) for disk buffer, are there any other suggestions for what I should use?

Also the disk buffer doesn't specify what volume it is loaded on, is there a way I can use a persistent volume and not the node volume for this?

Also is there any info on how hard is the performance hit for using disk buffer? I know it will be dependent on a bunch of things like type of disk + cpu etc. But is this on a scale of milliseconds, seconds or minutes difference?
 
Thanks.

**Comment by binarylogic** [comment, marked as answer]
Hey @asafdl great question! We're working on a set of comprehensive guides that'll cover questions like this and help with going to production with large deployments.

That said, could you provide a little more info about your data sources and sinks? In general, disk buffers should be a last resort for situations that do not offer alternative durability strategies. I would not use disk buffers if you absolutely cannot lose data. Better strategies include:

1. Using Vector's new end-to-end acknowledgement feature. This ensures that Vector does not advance reading data (sources) without confirmation that data was sent downstream (sinks). This pushes the responsibility of durability upstream, which is generally much better for performance. This feature is in beta, but our confidence is pretty high in its reliability. You can see the docs [here](https://github.com/timberio/vector/pull/7436).
2. Leverage systems designed for the level of durability you require. The obvious suggestion is Kafka/Kinesis, but we understand that is a very large ask of someone.
3. Finally, we are working through enterprise-level data loss strategies, like using other systems for external buffering (e.g. s3) and features like dead letter queues (routing failed events to another storage). We are expected complete these in Q3/Q4 of this year. If you're interested in being an early tester, please reach out to me (ben.johnson@datadoghq.com) and we can chat.

I hope that helps.

**Reply by JustinMason** [reply]
https://github.com/timberio/vector/pull/7436/files#diff-4bf4e464dd9a350607fd11f04ffe144264f5e5e0974c44d4ddf3433499904a4dR31
"In order to achieve at-least-once delivery between restarts your sink must be configured to use
disk-based buffers". If we are using Kafka as our source would we need disk-based buffers for a sink to avoid data loss on restarts? Or would vector replay the events it had not committed back to the Kafka source?  Does the Acknowledgement pattern control what offsets are committed, or is there a risk that Kafka offsets could be committed even though the sink hasn't acked?

**Reply by joshlreese** [reply]
> I would not use disk buffers if you absolutely cannot lose data

Would you mind elaborating on this? It was my understanding that the disk buffer was specifically for this use case. Is your comment related to the feature request created at https://github.com/timberio/vector/issues/8540 to ensure the buffer has been sync'd to the filesystem before acked?

I appreciate the insights here!

**Reply by asafdl** [reply]
Hi, thanks for the response.
Currently we are going to be sending our logs to splunk hec sink. The splunk hec endpoint provides it's own data loss prevention and redundancy, but my managers have set a 0 data loss policy and want insurance that the data will not be lost on our end as well if something were to happen to the splunk hec. 
We are currently using vector as a data source (kubernetes_logs) but that might change in future.

My plan was to do some performance tests to measure how some of AWS more robust SSDs handle this load https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#solid-state-drives such as io1 and io2, but if you say that this approach is not advised I might need to rethink this.

I will consult with my team about your 3. suggestion and mail you if it's relevant thanks :)
Also thanks to Spencer for answering my questions in discord #kubernetes channel if anyone reading this wants to follow up.

**Reply by binarylogic** [reply]
@JustinMason that language needs clarification (we are working on it), apologies for any confusion it created. Basically, disk buffers should only be used with sources where it upgrades durability. For example:

* Kafka is designed for high durability since it synchronizes data across multiple machines, taking data off of Kafka and placing it on a single machine (Vector's disk buffer) will downgrade durability. What happens if Vector's instance dies? It is much better for Vector to stop reading data from Kafka until it is ready. This uses Kafka as an upstream buffer, which is its core competency. This is also true for fan-out topologies where Vector is routing data to multiple sinks. If a single sink fails, Vector will stop reading from the upstream source and all sinks will cease to receive data.
* Alternatively, let's say you're receiving data from the `syslog` source, and the upstream Syslog client is a single machine that you want to get data off of as quickly as possible. In this case, Vector's disk buffers make more sense. You would not want to hold that data in memory in case the Vector instance dies. While this is better durability, it's still limited to a single machine. If you absolutely cannot lose data you should consider placing a buffer like Kafka/Kinesis in between your syslog client and Vector.

Now to answer your questions:

>  If we are using Kafka as our source would we need disk-based buffers for a sink to avoid data loss on restarts?

No, you should use in-memory buffers and do what is described in the first scenario above.

> Or would vector replay the events it had not committed back to the Kafka source?

Yes, once the sink becomes healthy Vector will resume reading data from Kafka.

> Does the Acknowledgement pattern control what offsets are committed, or is there a risk that Kafka offsets could be committed even though the sink hasn't acked?

Yes, this is the purpose fo the acknowledgment feature. It will only advance the Kafka offset once _all_ sinks have acknowledged successful delivery of the events.

Let me know if that helps! Again, we are plan to dramatically improve the user experience around durability over this quarter.

**Reply by joshlreese** [reply]
@binarylogic - Thank you for the detailed explanation here. One question regarding disk durability - would you consider a volume backend which ensures data durability (assuming a flush has occurred) and allows for node-mobility of an instance of Vector to be a downgrade in durability?

**Reply by JustinMason** [reply]
I am seeing data loss in a very basic example.  I assume I am missing a setting.

We have 2 processes.
"Router" sources from Kafka, sinks to Vector
"Sink" sources from Vector, sinks back to Kafka

"Router"
```YAML
      sources:
        kafka-in:
          type: kafka
          acknowledgements: true
          bootstrap_servers: logstreaming-kafka-bootstrap.kafka:9092
          group_id: router-consumer3
          topics:
            - vector.test.in
      transforms:
        timestamper:
          type: remap
          inputs:
            - kafka-in
          source: |-
            . = parse_json!(.message)
            .t1 = to_unix_timestamp(now())
      sinks:
        vector-sink:
          type: vector
          inputs:
            - timestamper
          address: sink:9000
          version: "2"
          buffer:
            type: disk
            max_size: 10485760
            when_full: block
```

"Sink"
```YAML
  sources: 
        vector_router_source:
          type: vector
          acknowledgements: true
          version: "2"
          address: 0.0.0.0:9000
      transforms:
        timestamper:
          type: remap
          inputs:
            - vector_router_source
          source: |-
            .t2 = to_unix_timestamp(now())
      sinks:
        sink:
          type: kafka
          inputs:
            - timestamper
          bootstrap_servers: logstreaming-kafka-bootstrap.kafka:9092
          encoding:
            codec: json
          healthcheck:
            enabled: true
          topic: vector.test.out
          buffer:
            type: disk
            max_size: 10485760
            when_full: block
```

This is running in GKE.  When we intentionally delete the "Sink" during a run we expect it to come back and resume from where it left off.  We are seeing gaps in whats "Sinked" back to Kafka.  When we don't delete the Sink, happy path, all the data sinks back to Kafka.
I have the acknowledgements, the Buffer Set to disk, and we are deploying to GKE with a persistent volume claim for both the "Router" and the "Sink", see router yaml section below:
```YAML
      name: vector
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 2
            memory: 6000Mi
          requests:
            cpu: 2
            memory: 6000Mi
        volumeMounts:
        - mountPath: /etc/vector/
          name: config
        - mountPath: /var/lib/vector/
          name: vector-router-data
      volumes:
      - configMap:
          name: router-config
        name: config
      - name: vector-router-data
        persistentVolumeClaim:
          claimName: vector-router-data
  volumeClaimTemplates:
  - metadata:
      name: vector-router-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
``` 

Am I missing something obvious?  I would assume that the "Router" process would not get acknowledgements from the "Sink" process and it would replay/buffer the data once the "Sink" resumed.

I'm seeing errors from the Router when I delete the Sink.
`:30.197 ERROR sink{component_kind="sink" component_name=vector-sink component_type=vector}:request{request_id=13548}: vector::sinks::util::retries: Non-retriable error; dropp │
│ Aug 10 02:47:30.198 ERROR sink{component_kind="sink" component_name=vector-sink component_type=vector}:request{request_id=13548}: vector::sinks::util::sink: Request failed. error=Request │`

Any ideas?
Thanks
