### DISCUSSION TITLE
Filter transform getting rate limited interally

### DISCUSSION THREAD

**Discussion by danthegoodman1** [vectordotdev/vector#8634] [Q&A] [answered]
I've got the following `values.yml` file:

```yaml
transforms:
  logFilter:
    type: filter
    inputs:
      - "kubernetes_logs"
    condition: "length(parse_regex!(.kubernetes.pod_name, r'.*deployment.*')) > 0"
  # jsonFlatten:
  #   type: remap
  #   inputs:
  #     - "logFilter"
  #   source: " .message = parse_json!(.message)\n"

sinks:
  # Adjust as necessary. By default we use the console sink
  # to print all data. This allows you to see Vector working.
  # /docs/reference/sinks/
  stdout:
    type: console
    inputs: ["logFilter"]
    target: "stdout"
    encoding: "json"

  lokiSink:
    type: loki
    inputs:
      - logFilter
    endpoint: http://loki.default.svc.cluster.local:3100
    encoding:
      codec: json
    healthcheck:
      enabled: true
    labels:
      forwarder: vector
      podname: "{{kubernetes.pod_name}}"
      nodename: "{{kubernetes.pod_node_name}}"
      messagetext: "{{message.message}}"
```

And I am getting errors:

```
Aug 09 16:54:18.635  WARN transform{component_kind="transform" component_name=logFilter component_type=filter}: vector::internal_events::conditions: VRL condition execution failed. internal_log_rate_secs=120
Aug 09 16:54:18.635  WARN transform{component_kind="transform" component_name=logFilter component_type=filter}: vector::internal_events::conditions: Internal log [VRL condition execution failed.] is being rate limited.
```

How do I remove this rate limit?

**Comment by jszwedko** [comment, marked as answer]
Hi @danthegoodman1 !

That rate limit you see there is specific to the log message from Vector. We typically rate limit error messages to avoid flooding people's logs in the event of catastrophic failure. Vector is not actually rate limiting events flowing through your topology. I opened https://github.com/timberio/vector/issues/8635 to try to clarify this.

**Reply by danthegoodman1** [reply]
Thanks @jszwedko,

It seems that it is preventing it from working, and I cannot see the error message (that I asusme it is throwing but rate limiting and not showing). How might I figure out what is wrong?

**Reply by jszwedko** [reply]
Hi @danthegoodman1 !

Are there error messages proceeding the two you listed above? I would have expected one from VRL with more context about why it failed.

In your above configuration, I believe it would only fail if: `.kubernetes.pod_name` does not exist on the event or is not a string.

**Reply by danthegoodman1** [reply]
No more errors before that unfortunately, all `INFO` messages.

**Reply by danthegoodman1** [reply]
@jszwedko Would .kuberntes.pod_name not always exist on the `kuberbetes_logs` source?

**Reply by jszwedko** [reply]
@danthegoodman1 theoretically yes, but we do have an open issue for a scenario where it might not be: #8345 . Do you see the log mentioned in that issue in your Vector logs?

**Reply by jszwedko** [reply]
I opened https://github.com/timberio/vector/issues/8684 to track outputting the VRL error when the condition fails. That would have helped here to identify exactly why it is failing to execute.

**Reply by jszwedko** [reply]
Just a note that I think you can simplify your condition check to:

```
contains(.kubernetes.pod_name, "deployment")
```

Credit to @spencergilbert

**Reply by danthegoodman1** [reply]
@jszwedko I don't see the log in #8345 unfortunately

**Reply by danthegoodman1** [reply]
Will try the `contains` when I get an opportunity, thanks for the tip!

**Reply by jszwedko** [reply]
@danthegoodman1  I might suggest putting a `remap` transform in front of your `filter` transform and logging events missing that key.

Something like:

```
if !exists(.kubernetes.pod_name) {
  log(.)
}
```

That may help shine some light on why those events are missing that key.

I could also be wrong and the `filter` transform was failing for a different reason, but I can't think of one.

**Reply by danthegoodman1** [reply]
@jszwedko Will do! And looks like you might have pinged the wrong person by accident XD

**Reply by danthegoodman1** [reply]
@jszwedko Just got the following:

```
Aug 12 17:56:36.481 ERROR vector::topology: Configuration error. error=Transform "logFilter":                                                                                                                              │
│ error[E100]: unhandled error                                                                                                                                                                                               │
│   ┌─ :1:1                                                                                                                                                                                                                  │
│   │                                                                                                                                                                                                                        │
│ 1 │ contains(.kubernetes.pod_name, "deployment.")                                                                                                                                                                          │
│   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                          │
│   │ │                                                                                                                                                                                                                      │
│   │ expression can result in runtime error                                                                                                                                                                                 │
│   │ handle the error case to ensure runtime success                                                                                                                                                                        │
│   │                                                                                                                                                                                                                        │
│   = see documentation about error handling at https://errors.vrl.dev/#handling                                                                                                                                             │
│   = learn more about error code 100 at https://errors.vrl.dev/100                                                                                                                                                          │
│   = see language documentation at https://vrl.dev
```

This is how I was doing it:

```yaml
transforms:
  remapLogWeirdness:
    type: remap
    inputs:
      - "kubernetes_logs"
    source: |-
      if !exists(.kubernetes.pod_name) {
        log(.)
      }
  logFilter:
    type: filter
    inputs:
      - "kubernetes_logs"
    condition: contains(.kubernetes.pod_name, "deployment.")
```
