### DISCUSSION TITLE
How do I add fixed attributes to the expanded array?

### DISCUSSION THREAD

**Discussion by PanHywel** [vectordotdev/vector#8644] [Q&A] [answered]
How do I add fixed attributes to the expanded array

### Vector Version

vector 0.15.0

```toml
[sources.httpSources]
type = "http"
address = "172.16.1.41:7001"
path = "/client-lua"
encoding = "json"
headers = ["x-forwarded-for"]


[transforms.parse_logs]
type = "remap"
inputs = ["httpSources"]
source = '''
. = .msg
.clientIp = .x-forwarded-for
'''


[sinks.print]
 type = "console"
 inputs = ["parse_logs"]
 encoding.codec = "json"
```

```json
{
   "x-forwarded-for":"192.168.1.1",
   "msg":[
     {
       "name":"tom"
     },
     {
       "name":"mimi"
     }
  ]
}

```
I hope to get：
```json
{
  "clientIp":"192.168.1.1",
  "name":"tom"
},
{
  "clientIp":"192.168.1.1",
  "name":"mimi"
}

```

**Comment by spencergilbert** [comment, marked as answer]
```toml
source = '''
. = .msg
.clientIp = .x-forwarded-for
'''
```
The first line here will replace the entire event (`.`) with the the `.msg` field, if present. The following line should set a root level field named `clientIp` to the contents of the `.x-forwarded-for` field (presumably a part of the `.msg` key you used above?). 

Could you share an example of an event that would be going into the `remap` transform here?

EDIT: if that second snippet is the example input, I think you may just want to use [`unnest`](https://vector.dev/docs/reference/vrl/functions/#unnest) on `.msg`

```toml
source = """
. = unnest!(.msg)
.clientIp = del(.x-forwarded-for)
"""
```

EDIT2: 💭 might require two remaps:
```toml
[transforms.parse_logs]
type = "remap"
inputs = ["httpSources"]
source = '''
. = unnest(.msg)
'''

[transforms.parse_logs]
type = "remap"
inputs = ["parse_logs"]
source = '''
. |= .msg
.clientIp = ."x-forwarded-for"
'''
```

**Reply by PanHywel** [reply]
@spencergilbert 
I'm really sorry, after modifying as you said, I get the following error.
msg is an array list and I need to tile msg and merge x-forwarded-for into each object.



![image](https://user-images.githubusercontent.com/13009686/128954067-04aacc4e-8c22-4ea3-a394-3806bf877e01.png)

I'm not very familiar with vrl, but I'm desperate for a solution to this problem, thanks for your reply

```toml

[transforms.parse_logs]
type = "remap"
inputs = ["httpSources"]
source = '''
., err = unnest(.msg)
'''

[transforms.parse_logs_two]
type = "remap"
inputs = ["parse_logs"]
source = '''
. |= .msg
.clientIp = del(."x-forwarded-for")
'''


[sinks.print]
 type = "console"
 inputs = ["parse_logs"]
 encoding.codec = "json"

```

**Reply by spencergilbert** [reply]
No problem! We're happy to help, just to confirm this is the expected contents of an event line?

```json
{
   "x-forwarded-for":"192.168.1.1",
   "msg":[
     {
       "name":"tom"
     },
     {
       "name":"mimi"
     }
  ]
}
```

**Reply by PanHywel** [reply]
Yes, the input is in this format and he has a msg and x-forwarded-for field. I need to unnest the msg and merge the x-forwarded-for field into each message in the unnest


**For example(This is my real input data content)：**

```
{
    "User-Agent": "Mozilla/5.0 (Linux; Android 10; WLZ-AN00; HMSCore 6.0.1.306) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 HuaweiBrowser/11.1.3.300 Mobile Safari/537.36",
    "msg": [
        {
            "appName": "[sdk]",
            "confId": "ea2075702a6b4341b12e14947fe78331",
            "text": "test",
            "time": "2021-08-11 10:02:58",
            "type": "debug",
            "userId": "1019195340"
        },
        {
            "appName": "[sdk]",
            "confId": "cv23430jk354j56445kkll75jo57k46k",
            "text": "test1",
            "time": "2021-08-11 10:03:02",
            "type": "debug",
            "userId": "1019195340"
        }
    ],
    "path": "/client-lua",
    "source_type": "http",
    "timestamp": "2021-08-11T02:05:01.447564798Z",
    "x-forwarded-for": "115.55.78.90"
}
```
**I need to convert it to the following output**
```
{
    "appName": "[sdk]",
    "confId": "ea2075702a6b4341b12e14947fe78331",
    "text": "test",
    "time": "2021-08-11 10:02:58",
    "type": "debug",
    "userId": "1019195340",
    "User-Agent": "Mozilla/5.0 (Linux; Android 10; WLZ-AN00; HMSCore 6.0.1.306) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 HuaweiBrowser/11.1.3.300 Mobile Safari/537.36",
    "x-forwarded-for": "115.55.78.90"
}
{
    "appName": "[sdk]",
    "confId": "cv23430jk354j56445kkll75jo57k46k",
    "text": "test1",
    "time": "2021-08-11 10:03:02",
    "type": "debug",
    "userId": "1019195340",
    "User-Agent": "Mozilla/5.0 (Linux; Android 10; WLZ-AN00; HMSCore 6.0.1.306) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 HuaweiBrowser/11.1.3.300 Mobile Safari/537.36",
    "x-forwarded-for": "115.55.78.90"
}
```

**Reply by PanHywel** [reply]
@spencergilbert 
hi, I get each property from the msg and it works fine now, but not sure if there is a more elegant way to do it, if you know of one, please let me know。


Current configuration
```toml
[transforms.parse_logs]
type = "remap"
inputs = ["httpSources"]
source = '''
. = unnest!(.msg)
#.clientIp = del(."x-forwarded-for")
'''

[transforms.parse_logs_two]
type = "remap"
inputs = ["parse_logs"]
source = '''
.appName = .msg.appName
.confId = .msg.confId
.text = .msg.text
.time = .msg.time
.type = .msg.type
.userId = .msg.userId
.clientIp = del(."x-forwarded-for")
.userAgent =del(."User-Agent")
.siteDomain = msg.siteDomain
.userName = msg.userName
.playerVersion = msg.playerVersion
.playerMode = msg.playerMode
.siteId = msg.siteId
del(.timestamp)
del(.source_type)
del(.path)
del(.msg)
'''
```
Results of the run：
```json
{
    "appName": "[sdk]",
    "clientIp": "192.168.1.",
    "confId": "m3sREDCdMS",
    "path": "/client-lua",
    "playerMode": null,
    "playerVersion": null,
    "siteDomain": null,
    "siteId": null,
    "text": "",
    "time": "2021-08-11 15:53:48",
    "type": "debug",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.67",
    "userId": "1000097388939",
    "userName": null
}
```

**Reply by spencergilbert** [reply]
I'll have a look in a little bit here, and see what I can come up with locally - I'm pretty certain we can make it simpler 🙂

**Reply by spencergilbert** [reply]
I think you got pretty well close actually, this is a little simpler.

```toml
[transforms.explode]
    type = "remap"
    inputs = ["parse"]
    source = """
      . = unnest!(.msg)
    """
[transforms.remap]
    type = "remap"
    inputs = ["explode"]
    source = """
      ua = del(."User-Agent")
      xff = del(."x-forwarded-for")
      . = .msg
      ."User-Agent" = ua
      ."x-forwarded-for" = xff
    """
```
