### DISCUSSION TITLE
Does vector support automatic deletion of files after reading?

### DISCUSSION THREAD

**Discussion by PanHywel** [vectordotdev/vector#8732] [Q&A] [answered]
I am writing logs to a file by hour via Nginx lua, and then reading the file via vector to write the contents to kafka, but when the reading is done, the file needs to be deleted manually, which bothers me a lot.
Does vector support automatic deletion of individual files after they are read?

```toml
[sources.nginx_file_sources]
  type = "file"
  include = ["/openresty/nginx/conf/waf/log/*.log"]
  data_dir = "/vector"

```
