### ISSUE TITLE
Soak test with enrichment involved

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#10007]
We've previously had a soak test with the following config, in the old style:

```toml
# An Enrichment config
#
# This configuration loads an enrichment data file and performs
# 10 searches through that file per event.


##
## Enrichment table
##

[enrichment_tables.viplist]
type = "file"
file.path = "/etc/enrichment/users.csv"
file.encoding.type = "csv"
schema.dob = "date"
schema.from = "date"
schema.to = "date"

##
## Sources
##

[sources.socket]
type = "socket"
address = "0.0.0.0:9876"
mode = "tcp"

[sources.internal_metrics]
type = "internal_metrics"

##
## Transform
##

[transforms.remapvip]
type = "remap"
inputs = ["socket"]
source = '''
. = parse_json!(.message)
.from = parse_timestamp!(string!(.from) + " 00:00:00", format: "%Y-%m-%d %T")
.to = parse_timestamp!(string!(.to) + " 00:00:00", format: "%Y-%m-%d %T")

# Split SSN
ssnSplits = parse_regex!(.ssn, r'(?P<first5>[0-9]{1,5})(?P<last4>[0-9]{1,4})')
.ssnFirst5 = slice!(.ssn, 0, 5)
.ssnLast4 = slice!(.ssn, 5, 9)

# Rule 1 - 9 digit SSN
log(.ssn, rate_limit_secs: 0)
vip_row = find_enrichment_table_records("viplist", { "ssn": .ssn, "dob": { "from": .from, "to": .to } }) ?? []
.found1 = vip_row

vip_row = find_enrichment_table_records!("viplist", { "ssnLast4": .ssnLast4, "last_name": .last_name, "dob": { "from": .from, "to": .to } })
.found2 = vip_row

vip_row = find_enrichment_table_records!("viplist", { "last_name": .last_name, "first_name": .first_name, "dob": { "from": .from, "to": .to } })
.found3 = vip_row

vip_row = find_enrichment_table_records!("viplist", { "last_name": .last_name, "first_name": .first_name, "city": .city, "dob": { "from": .from, "to": .to } })
.found4 = vip_row

vip_row = find_enrichment_table_records!("viplist", { "last_name": .last_name, "first_name": .first_name, "zipcode": .zipcode, "dob": { "from": .from, "to": .to } })
.found5 = vip_row

vip_row = find_enrichment_table_records!("viplist", { "phone_number": .phone_number, "dob": { "from": .from, "to": .to } })
.found6 = vip_row

vip_row = find_enrichment_table_records!("viplist", { "phone_number": .phone_number, "first_name": .first_name, "last_name": .last_name, "dob": { "from": .from, "to": .to } })
.found7 = vip_row

vip_row = find_enrichment_table_records!("viplist", { "first_name": .first_name,
                                                      "last_name": .last_name,
                                                      "street_address": .street_address,
                                                      "city": .city,
                                                      "state": .state,
                                                      "zipcode": .zipcode,
                                                      "dob": { "from": .from, "to": .to } })
.found8 = vip_row

vip_row = find_enrichment_table_records!("viplist", { "first_name": .first_name,
                                                      "last_name": .last_name,
                                                      "city": .city,
                                                      "dob": { "from": .from, "to": .to } })
.found9 = vip_row

vip_row = find_enrichment_table_records!("viplist", { "first_name": .first_name,
                                                      "last_name": .last_name,
                                                      "zipcode": .zipcode,
                                                      "dob": { "from": .from, "to": .to } })
.found10 = vip_row
'''

##
## Sinks
##

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"

[sinks.blackhole]
type = "blackhole"
inputs = ["remapvip"]

```

We would like to have this ported over to the new CI style.
