### ISSUE TITLE
Vector stops publishing messages to Loki

### ISSUE THREAD

**Issue by mahodar03** [vectordotdev/vector#10010]
Hi,

We have vector deployed on our production machines and we noticed that when vector starts on a machine with no internet connectivity and when the connection does recover eventually vector will not push  logs to the Loki endpoint hosted on grafana cloud after a few minutes. When the internet connection recovers, vector can resolve the address of the endpoint and will publish for a few minutes and will then stop sending logs to grafana. Restarting the vector will correct this issue and logs can be observed on grafana again.

We also have a few machines running with vector version `vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)` and similar config without observing this issue.

### Vector Version

```
vector 0.17.3 (x86_64-unknown-linux-gnu d72c6e7 2021-10-21)

```

### Vector Configuration File

```toml
data_dir = "/var/lib/vector"


[sources.journald]
    type = "journald"

#[transforms.remap]
#    type = "remap"
#    inputs = ["journald"]
#    source = '''
#        .severity = to_syslog_facility!(to_int!(.PRIORITY))
#     '''

# Output data
[sinks.loki]
    inputs = ["journald"]
    type = "loki"
    healthcheck = true
     
    #request.concurrency = "adaptive"
    #request.retry_max_duration_secs = 600

    endpoint = "https://logs-prod-us-central1.grafana.net"
    
    auth.strategy = "basic"
    auth.user = "${GRAFANA_USER_ID}"
    auth.password = "${GRAFANA_USER_PASSWORD}"
    
    encoding.codec = "json"
    encoding.timestamp_format = "rfc3339"
    
    labels.host = "{{host}}"
    labels.severity = "{{PRIORITY}}"
    labels.units = "{{_SYSTEMD_UNIT}}"
    labels.syslogid = "{{SYSLOG_IDENTIFIER}}"
```

### Expected Behavior

After the internet connection becomes available vector to publish logs to Loki continuously. 

### Actual Behavior

After the internet connection becomes available vector will publish logs to grafana for a few minutes and will stop sending them until the process is restarted.
