### ISSUE TITLE
Redis sink: support for streams

### ISSUE THREAD

**Issue by NicolasFloquet** [vectordotdev/vector#10042]
Hello!

Since redis is already supported as a sink, I feel that supporting [streams](https://redis.io/topics/streams-intro) could be a nice low hanging fruit feature to add.

### Proposal

Suggested configuration:
```
sinks:
  my_sink_id:
    type: redis
    inputs:
      - my-source-or-transform-id
    url: redis://127.0.0.1:6379/0
    data_type: stream
    stream:
       name: 'stream-name'
       key: 'my-key'
       maxlen: 10
```

With such configuration,  each  log would be added to the stream as following:

`XADD stream-name MAXLEN 10 * my-key <logdata>`
