### ISSUE TITLE
`syslog` decoding codec in sources does not validate input messages

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#10086]
### Vector Version

```
vector 0.17.3 (x86_64-unknown-linux-gnu d72c6e7 2021-10-21)
```

### Vector Configuration File

Consider the following Vector configuration file:
```yaml
sources:
  stdin:
    type: stdin
    decoding:
        codec: syslog

sinks:
  console:
    type: console
    inputs:
      - stdin
    encoding: json

```

### Expected Behavior

We expect the `syslog` decoding codec to parse syslog messages and to emit errors if an incoming message is not valid Syslog.

For example, if we send this to Vector's `stdin` (in the above pipeline):
```
<34>1 2003-10-11T22:14:15.003Z mymachine.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8
```
We get this from Vector's `stdout` (from the above pipeline):
```json
{"appname":"su","facility":"auth","host":"myhost","hostname":"mymachine.example.com","message":"BOM'su root' failed for lonvick on /dev/pts/8","msgid":"ID47","severity":"crit","source_type":"stdin","timestamp":"2003-10-11T22:14:15.003Z","version":1}
```

And if we send this malformed Syslog message:
```
<34>1 2003-10- mymachine.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8
```
Then the source emits an error indicating that the incoming message was not valid Syslog, and the message dropped.

### Actual Behavior

Instead, for the above malformed Syslog message, the `syslog` decoding codec seems to silenty fallback to placing the malformed message into the `message` field of the event:
```json
{"host":"myhost","message":"<34>1 2003-10- mymachine.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8","source_type":"stdin","timestamp":"2021-11-17T16:25:48.053979500Z"}
```

This is not good behaviour for error handling and, more importantly, the event is not dropped, potentially disrupting the rest of the pipeline with unparsed data.

The interesting thing is that, if we use the `json` decoding codec, then it does handle errors as expected:
```yaml
sources:
  stdin:
    type: stdin
    decoding:
        codec: json

sinks:
  console:
    type: console
    inputs:
      - stdin
    encoding: json
```

Good Input:
```
{"good":"JSON value"}
```
Good Output:
```json
{"good":"JSON value","host":"myhost","source_type":"stdin","timestamp":"2021-11-17T16:29:14.614870600Z"}
```

Bad Input:
```
this is NOT a valid JSON value!
```
Vector reports the malformed message as expected:
```
Nov 17 16:29:48.608  WARN source{component_kind="source" component_id=stdin component_type=stdin component_name=stdin}: vector::internal_events::decoder: Failed parsing frame. error=Error parsing JSON: Error("expected ident", line: 1, column: 2) internal_log_rate_secs=10
```

EDIT: For the record, the VRL version of `parse_syslog()` does handle errors as expected too:
```coffee
parse_syslog!("<34>1 2003-10- mymachine.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8")
# function call error for "parse_syslog" at (0:111): unable to parse input as valid syslog message
```
