### ISSUE TITLE
Vector rust panic with log_to_metric transform

### ISSUE THREAD

**Issue by valerypetrov** [vectordotdev/vector#10080]
### Vector Version
We've tried 0.17.0 and 0.17.3, no luck.
<!---
[root@sjc06-c02-lss11 valery.petrov]# vector --version
vector 0.17.0 (x86_64-unknown-linux-gnu 3d34cde 2021-10-08)
```

```

### Vector Configuration File

With this config, it's working fine
```toml
[sinks.elasticsearch_app_c01]

  type = "elasticsearch"
  inputs = ["remap_app"]
  compression = "none"
  bulk_action = "index"
  doc_type = "_doc"
  endpoint = "http://:9201"
  index = "vector-logs-{{ index_pattern }}-%Y.%m.%d"
  batch.max_bytes = 50490000
  request.concurrency = "adaptive"
  buffer.type = "memory"
  buffer.max_events = 500000

[transforms.vector_component_metrics_app]

  type = "log_to_metric"
  inputs = ["remap_app"]

  [[transforms.vector_component_metrics_app.metrics]]
    field = "component_type"
    name = "component_type_vector"
    namespace = "component"
    type = "counter"
    tags.host = "${HOSTNAME}"
    tags.component_type = "{{ component_type }}"
    tags.log_type = "{{ log_type }}"

[transforms.vector_truncate_metrics_app]

  type = "log_to_metric"
  inputs = ["remap_app"]

  [[transforms.vector_truncate_metrics_app.metrics]]
    field = "long_field"
    name = "long_field_type_vector"
    namespace = "long_field"
    type = "counter"
    tags.host = "${HOSTNAME}"
    tags.long_field = "{{ long_field }}"
    tags.log_type = "{{ log_type }}"


[transforms.aggregate_influx]
  type = "aggregate"
  inputs = ["vector_component_metrics_app", "vector_truncate_metrics_app" ]
  interval_ms = 10_000

[transforms.set_timestamp]
  type = "remap"
  inputs = ["aggregate_influx"]
  source = '''
  .timestamp = now()
 '''


[sinks.influxdb]
  type = "influxdb_metrics"
  inputs = ["set_timestamp"]
  endpoint = ":8086"
  namespace = "vector"
  database = "elk-vector-stats"
  healthcheck = true
  batch.max_events = 2000
  batch.timeout = 5
```

With this one it will crash:
```toml
[sinks.elasticsearch_app_c01]

  type = "elasticsearch"
  inputs = ["remap_app"]
  compression = "none"
  bulk_action = "index"
  doc_type = "_doc"
  endpoint = "http://:9201"
  index = "vector-logs-{{ index_pattern }}-%Y.%m.%d"
  batch.max_bytes = 50490000
  request.concurrency = "adaptive"
  buffer.type = "memory"
  buffer.max_events = 500000

[transforms.vector_component_metrics_app]

  type = "log_to_metric"
  inputs = ["elasticsearch_app_c01"]

  [[transforms.vector_component_metrics_app.metrics]]
    field = "component_type"
    name = "component_type_vector"
    namespace = "component"
    type = "counter"
    tags.host = "${HOSTNAME}"
    tags.component_type = "{{ component_type }}"
    tags.log_type = "{{ log_type }}"

[transforms.vector_truncate_metrics_app]

  type = "log_to_metric"
  inputs = ["elasticsearch_app_c01"]

  [[transforms.vector_truncate_metrics_app.metrics]]
    field = "long_field"
    name = "long_field_type_vector"
    namespace = "long_field"
    type = "counter"
    tags.host = "${HOSTNAME}"
    tags.long_field = "{{ long_field }}"
    tags.log_type = "{{ log_type }}"


[transforms.aggregate_influx]
  type = "aggregate"
  inputs = ["vector_component_metrics_app", "vector_truncate_metrics_app" ]
  interval_ms = 10_000

[transforms.set_timestamp]
  type = "remap"
  inputs = ["aggregate_influx"]
  source = '''
  .timestamp = now()
 '''


[sinks.influxdb]
  type = "influxdb_metrics"
  inputs = ["set_timestamp"]
  endpoint = ":8086"
  namespace = "vector"
  database = "elk-vector-stats"
  healthcheck = true
  batch.max_events = 2000
  batch.timeout = 5
```

Here is the full trace:
```
/usr/bin/vector --config /etc/vector/vector_app.toml
Nov 17 12:32:53.483  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info"
Nov 17 12:32:53.484  INFO vector::app: Loading configs. paths=["/etc/vector/vector_app.toml"]
thread 'main' panicked at 'internal error: entered unreachable code', src/config/validation.rs:287:74
stack backtrace:
   0:     0x562bfeede9e0 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x562bfeede9e0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562bfeede9e0 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x562bfeede9e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x562bfef4b34c - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x562bfeed0175 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x562bfeee273b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x562bfeee273b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x562bfeee273b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x562bfeee2211 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x562bfeee2f44 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x562bfeee29f7 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:517:13
  12:     0x562bfeedeedc - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x562bfeee2989 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x562bfb08f7a1 - core::panicking::panic_fmt::h12a3a3c256485fca
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:     0x562bfb08f6ed - core::panicking::panic::h344f23ad26057b48
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:50:5
  16:     0x562bfc34fa72 - vector::config::compiler::compile::h5a4cef5fc20e89f7
  17:     0x562bfc1f1c09 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcddf9401a4a4b935
  18:     0x562bfc3dd538 - vector::app::Application::prepare_from_opts::{{closure}}::hab523502f16cfd3d
  19:     0x562bfc3d578e - vector::app::Application::prepare_from_opts::h5a8f34bba3e9b5b5
  20:     0x562bfc3d4e90 - vector::app::Application::prepare::h9ab133e1135701ea
  21:     0x562bfb09811d - vector::main::h899a2b8eed539bd2
  22:     0x562bfb0980c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h713899aa9235b116
  23:     0x562bfb0980d9 - std::rt::lang_start::{{closure}}::h76fa64e5385c6e97
  24:     0x562bfeee354a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha9408abe89f69dc4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
  25:     0x562bfeee354a - std::panicking::try::do_call::h5b0cc9e9102acb65
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  26:     0x562bfeee354a - std::panicking::try::hddc7f8229138b3ba
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  27:     0x562bfeee354a - std::panic::catch_unwind::hfa401ff8bab2986e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  28:     0x562bfeee354a - std::rt::lang_start_internal::{{closure}}::h8163422320d11405
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
  29:     0x562bfeee354a - std::panicking::try::do_call::hc742cc7bb4f0fb20
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  30:     0x562bfeee354a - std::panicking::try::ha37d8d2dd1acf7d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  31:     0x562bfeee354a - std::panic::catch_unwind::h8a5381d5ecf437bc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  32:     0x562bfeee354a - std::rt::lang_start_internal::h7e2cee8c90d4a4d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  33:     0x562bfb0981b2 - main
  34:     0x7fb8fab00505 - __libc_start_main
  35:     0x562bfb097fc4 - <unknown>
  36:                0x0 - <unknown>
```
