### ISSUE TITLE
Allow disabling labels for `internal_metrics`

### ISSUE THREAD

**Issue by Zelpher** [vectordotdev/vector#10104]
### Current Vector Version

```
v0.17.3
```
### Use-cases

We are currently using Vector for collecting pods logs through `kubernetes_logs` source. For observability concerns, metrics are collected through a `prometheus` sink, exposing metrics from `internal_metrics`, but it generates high cardinality metrics due to `file` label.

### Attempted Solutions

We use `tag_cardinality_limit` transform, but it looks more like a quick fix as metrics are processed (in case of `drop_tag` behavior) and _partially aggregated_ when limit is exceeded (generating incorrect counters), or simply dropped.

### Proposal

Making `labels` configurable at source level would be nice in case of expected behavior (in our case, thousands of short-lived pods)

### Vector Configuration File
```yaml
sources:
  source-kubernetes-logs-collect:
    type: kubernetes_logs
    self_node_name: "${MY_NODE_NAME}"
    ingestion_timestamp_field: ingestion_timestamp
  source-internal-metrics:
    type: internal_metrics
transforms:
  transform-tag-cardinality-limit-to-internal-metrics:
    type: tag_cardinality_limit
    inputs:
    - source-internal-metrics
    mode: exact
    value_limit: 50
sinks:
  sink-prometheus-exporter:
    type: prometheus_exporter
    inputs:
    - transform-tag-cardinality-limit-to-internal-metrics
    address: 0.0.0.0:9598
```

### Additional Context
Impact on CPU / RAM consumption is not clearly identified, we assume that increasing cardinality should have some costs, but we do not have sufficient visibility at the moment.

![20211118_vector_internal_metrics](https://user-images.githubusercontent.com/3073431/142473712-4ccaeabf-3e3a-4cd0-b106-c40377ec112e.png)
