### ISSUE TITLE
[Topology] New reroute dropped feature creates `.dropped` stream regardless of `reroute_dropped=false` config

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#10129]
### Vector Version
```
vector 0.18.0 (x86_64-unknown-linux-gnu c77e085 2021-11-18)
```

### Vector Configuration File

Consider the following toy Vector pipeline configuration:
```yaml
sources:
  stdin:
    type: stdin

transforms:
  parse-syslog:
    type: remap
    inputs:
      - stdin
    drop_on_error: true
    reroute_dropped: true
    source: |-
      . = parse_syslog!(.message)
  parse-key-value:
    type: remap
    inputs:
      - parse-syslog
    drop_on_error: true
    reroute_dropped: true
    source: |-
      . = parse_key_value!(.message)

  logger:
    type: remap
    inputs:
      - '*.dropped'
    drop_on_error: true
    reroute_dropped: false
    source: |-
      host = string!(.host)
      message = string!(.message)
      component_id = string!(.metadata.dropped.component_id)
      log("component '" + component_id + "' dropped message from <" + host + ">: " + message, level: "warn")

sinks:
  console:
    type: console
    inputs:
      - parse-key-value
    encoding: json
```

### Expected Behavior

The above configuration should not have any cyclic dependency. For example, `vector graph` should show this:

![image](https://user-images.githubusercontent.com/5802993/142702426-fe7bdb7e-c59c-4aa6-ae67-6becf50f8a25.png)

### Actual Behavior

Vector seems instead to be creating an unexpected cyclic dependency at the `logger` component:

![image](https://user-images.githubusercontent.com/5802993/142702478-40ea50e4-78fb-4b90-9218-4defbc1153a0.png)

I noticed that using the following wildcard works as expected:
```yaml
    inputs:
      - 'parse-*.dropped'
```
Therefore, looks like using the wildcard at the very beginning is problematic?
The [documentation](https://vector.dev/docs/reference/configuration/#wilcards-in-component-ids) suggests that the wildcard can be used anywhere.

Furthermore, if you include the `logger` component as input for anything else, then Vector complaints about the cyclic dependency:
```yaml
sinks:
  console:
    type: console
    inputs:
      - parse-key-value
      - logger
    encoding: json
```
```
2021-11-19T22:49:39.562474Z ERROR vector::cli: Configuration error. error=Cyclic dependency detected in the chain [ logger -> logger ]
```
This is how I discovered this issue.

**Comment by hhromic** [comment]
Tested a bit more, and this wildcard usage works as expected:
```yaml
    inputs:
      - '*-key-value.*'
```

![image](https://user-images.githubusercontent.com/5802993/142701423-d0283bdc-d68e-4791-9e91-a73f0e19f337.png)

Therefore, it doesn't seem to be just a wildcard at the beginning, but the combination of the wildcard and a period.

**Comment by hhromic** [comment]
This wildcard usage also creates the cyclic dependency:
```yaml
    inputs:
      - '[a-z]*.dropped'
```

**Comment by spencergilbert** [comment]
@hhromic I suspect this is simply because `logger` will have a `logger.dropped` stream, which is matching your globs here?

**Comment by hhromic** [comment]
@spencergilbert , I thought about that too, but I'm explicitly setting for the `dropped` route to not be enabled:
```yaml
    reroute_dropped: false
```

Is there an easy way to confirm that indeed Vector is creating a `logger.dropped` stream even though it shouldn't?

**Comment by spencergilbert** [comment]
> @spencergilbert , I thought about that too, but I'm explicitly setting for the `dropped` route to not be enabled:
> 
> ```yaml
>     reroute_dropped: false
> ```
> 
> Is there an easy way to confirm that indeed Vector is creating a `logger.dropped` stream even though it shouldn't?

Doh - this is why I should have more coffee before answering things... Perhaps a `vector tap logger.dropped` or see if you can consume it to a `console` sink?

**Comment by hhromic** [comment]
> Perhaps a `vector tap logger.dropped` or see if you can consume it to a `console` sink?

Unfortunately, `vector tap component` will not reveal if the stream exists or not because it will silently sit there in case it doesn't exist. I think this is like that to accomodate for hot/live reloads of the configuration where a future component may appear.

Consuming it to a `console` sink not sure how it would work. I would have to artificially trigger a dropped event from the `logger` component and see if it shows up into the `console` sink even with `reroute_dropped=false` ?

Will check it out anyway. Thanks!

**Comment by spencergilbert** [comment]
> > Perhaps a `vector tap logger.dropped` or see if you can consume it to a `console` sink?
> 
> Unfortunately, `vector tap component` will not reveal if the stream exists or not because it will silently sit there in case it doesn't exist. I think this is like that to accomodate for hot/live reloads of the configuration where a future component may appear.
> 
> Consuming it to a `console` sink not sure how it would work. I would have to artificially trigger a dropped event from the `logger` component and see if it shows up into the `console` sink even with `reroute_dropped=false` ?
> 
> Will check it out anyway. Thanks!

Yeah, good call (and accurate on `tap`) - I was thinking trying to consume the stream when it _shouldn't_ exist, should error on startup.

**Comment by hhromic** [comment]
Alright, so just added this blackhole sink:
```yaml
  blackhole:
    type: blackhole
    inputs:
      - logger.dropped
```

And inded Vector happily runs with:
```
2021-11-22T15:32:45.684843Z  INFO vector::sinks::blackhole: Total events collected events=0 raw_bytes_collected=0
2021-11-22T15:32:46.685588Z  INFO vector::sinks::blackhole: Total events collected events=0 raw_bytes_collected=0
```

Just to confirm, I tried a bogus `logger.dropz` input and indeed Vector complains about a non-existing input.

So that would confirm the issue then. Vector is creating the `.dropped` stream regardless of `reroute_dropped=false`. A bit ashamed of not having test this before 🙈. I will update the issue accordingly.

**Comment by spencergilbert** [comment]
cc @lukesteensen

**Comment by JeanMertz** [comment]
> So that would confirm the issue then. Vector is creating the `.dropped` stream regardless of `reroute_dropped=false`.

This is a known limitation of the current implementation of the "dropped" stream. We're leveraging the existing topology feature set, which allowed us to bring this feature into a stable release more quickly, but it does have drawbacks (this is one of them, the other being that we have to require operators to explicitly set `reroute_dropped`, since we can't — yet — detect if the dropped stream is being used in a pipeline).

There are improvements planned for this feature going forward, and you running into this does prove to us that this is one of the issues we need to tackle 👍

For now, the best thing to do here is to explicitly exclude the streams you aren't interested in, in your glob pattern.

**Comment by lukesteensen** [comment]
To expand slightly on @JeanMertz's explanation, this limitation exists because this first version of our branching internals does not yet allow them to be dynamic. That is, the output exists whether or not it is used by a given config. Later iterations of our branching support will include the ability to make outputs dynamic based on the config, which is necessary to natively support things like exclusive routing.

That being said, I apologize for the confusion. This is something that should have been made more clear in the documentation. Looking at this today, I think there may be a way to implement a simple on/off for this output short of making the whole feature totally dynamic. I will either try to get that implemented or add a note to the docs clarifying that `dropped` is always present.

**Comment by hhromic** [comment]
@JeanMertz @lukesteensen thanks for your answers/clarifications.
Fully understood the limitation now, and I'm glad it is a known issue and not truly a "bug".

We can live with the current limitation so take your time guys to improve on this at your own pace.
The reroute dropped feature as it is today is already a great way to start this type of feature 👍.

**Comment by hhromic** [comment]
@lukesteensen can confirm that your PR indeed alleviated the situation here :)  Thanks again!
```
$ docker run --rm -it -v $PWD/vector.yaml:/vector.yaml:ro timberio/vector:nightly-distroless-libc graph -c /vector.yaml
2021-11-24T11:00:53.190110Z  WARN vector::config::loading: Transform "logger" has no consumers
digraph {
  "stdin" [shape=trapezium]
  "logger" [shape=diamond]
  "parse-key-value" -> "logger" [label="dropped"]
  "parse-syslog" -> "logger" [label="dropped"]
  "parse-key-value" [shape=diamond]
  "parse-syslog" -> "parse-key-value"
  "parse-syslog" [shape=diamond]
  "stdin" -> "parse-syslog"
  "console" [shape=invtrapezium]
  "parse-key-value" -> "console"
}
```
Using this configuration:
```yaml
api:
  enabled: true
  playground: false

sources:
  stdin:
    type: stdin

transforms:
  parse-syslog:
    type: remap
    inputs:
      - stdin
    drop_on_error: true
    reroute_dropped: true
    source: |-
      . = parse_syslog!(.message)
  parse-key-value:
    type: remap
    inputs:
      - parse-syslog
    drop_on_error: true
    reroute_dropped: true
    source: |-
      . = parse_key_value!(.message)

  logger:
    type: remap
    inputs:
      - '*.dropped'
    drop_on_error: true
    reroute_dropped: false
    source: |-
      host = string!(.host)
      message = string!(.message)
      component_id = string!(.metadata.dropped.component_id)
      log("component '" + component_id + "' dropped message from <" + host + ">: " + message, level: "warn")

sinks:
  console:
    type: console
    inputs:
      - parse-key-value
    encoding: json
```
