### ISSUE TITLE
[kubernetes_logs] Failed to annotate event with pod metadata.

### ISSUE THREAD

**Issue by anas-aso** [vectordotdev/vector#10122]
### Vector Version

```
0.17.3
```

### Vector Configuration File

```yaml
data_dir: "/vector-data-dir"

sources:
  kubernetes:
    type: kubernetes_logs

transforms:
  parse_logs:
    type: remap
    inputs:
      - kubernetes
    source: |-
      # Do some parsing (mostly parse_json(...))

sinks:
  elasticsearch:
    type: elasticsearch
    inputs:
      - parse_logs
    endpoint: http://<ES_SERVICE_NAME>.<NAMESPACE_NAME>.svc:<PORT>
    encoding:
      timestamp_format: rfc3339

```

### Debug Output
Example of failing log event returned with the mentioned error (redacted)
```
Log(LogEvent { fields: Map({"file": Bytes(b"/var/log/pods/my-namespace_my-pod-7956799d95-rf6h7_37a73b39-ac9c-42ad-a286-c084cd8dc775/my-container/0.log"), "message": Bytes(b"some json log line"), "source_type": Bytes(b"kubernetes_logs"), "timestamp": Timestamp(2021-11-19T14:45:00.014194282Z)}), metadata: EventMetadata { datadog_api_key: None, finalizers: EventFinalizers([]) } })

```

### Expected Behavior
The log events get enriched with Kubernetes metadata (container_name, pod_name, etc)

### Actual Behavior
The log event is not enriched (annotated?): none of the `.kubernetes_` fields exists and Vector keeps logging the error above.

### Example Data
See debug output above

### Additional Context
- This doesn't always happen, but given the amount of logs we process,  the absolute count of "broken" k8s events is too high (tens of millions per day)
- k8s have 300+ nodes
- runs on GKE
- 3000+ pods

I have tried the nightly build from yesterday (nightly-2021-11-18-debian) and set  [delay_deletion_ms](https://github.com/vectordotdev/vector/blob/24ea6de3a7646062df9639364776ff0ff298d3da/website/cue/reference/components/sources/kubernetes_logs.cue#L271) to a high value (1 hour!) and also excluded one namespace that was running 1400+ pod. This reduced the number of failures a bit, but they didn't vanish completely. 

I have checked many of the failing events, and they all seem valid and I expect them to at least have pass [this function](https://github.com/vectordotdev/vector/blob/0d0e7dc5a739993f4fa77bfe7296d9563043b8e5/src/sources/kubernetes_logs/path_helpers.rs#L36), so [this condition](https://github.com/vectordotdev/vector/blob/38d76d3b7f0050ce5218f0c10c1a9e1bf32d246c/src/sources/kubernetes_logs/mod.rs#L419) should never be true for them.

**Comment by svenmueller** [comment]
Here is configuration used for the Vector agents:


```
customConfig:
  data_dir: "/vector-data-dir"
  sources:
    kubernetes:
      type: kubernetes_logs
      max_line_bytes: 131072
      delay_deletion_ms: 3600000 
    internal_logs:
      type: internal_logs
    internal_metrics:
      type: internal_metrics

  transforms:
    parse_internal_logs:
      type: remap
      inputs:
        - internal_logs
      source: |-
        .cloud_provider.service = "vector"
        .host = "${HOSTNAME}"
  sinks:
    vector-aggregator:
      type: vector
      inputs:
        - kubernetes
        - parse_internal_logs
      address: vector-aggregator-haproxy.logging.svc:9080
      healthcheck:
        enabled: true
    prometheus-exporter:
      type: prometheus_exporter
      inputs:
        - internal_metrics
      address: 0.0.0.0:9090
```
