### ISSUE TITLE
Number of Internal Metric Events keeps growing for Vecter Agents w/ Kubernetes Source

### ISSUE THREAD

**Issue by svenmueller** [vectordotdev/vector#10147]
### Vector Version

```
0.18.0
```

### Vector Configuration File

```yaml
customConfig:
  data_dir: "/vector-data-dir"
  sources:
    kubernetes:
      type: kubernetes_logs
      max_line_bytes: 131072
      delay_deletion_ms: 3600000 
    internal_logs:
      type: internal_logs
    internal_metrics:
      type: internal_metrics

  transforms:
    parse_internal_logs:
      type: remap
      inputs:
        - internal_logs
      source: |-
        .cloud_provider.service = "vector"
        .host = "${HOSTNAME}"
  sinks:
    vector-aggregator:
      type: vector
      inputs:
        - kubernetes
        - parse_internal_logs
      address: vector-aggregator-haproxy.logging.svc:9080
      healthcheck:
        enabled: true
    prometheus-exporter:
      type: prometheus_exporter
      inputs:
        - internal_metrics
      address: 0.0.0.0:9090
```

### Expected Behavior

Number of events for internal metrics (Vector agent, Kubernetes source) not growing over time.

### Actual Behavior

Number of events for internal metrics (Vector agent, Kubernetes source) is growing over time. Currently the number of events only resets when the agent is restarted.

### Example Data

Graphing the exported Prometheus metric `vector_component_sent_events_total` (component_kind="source", component_id="kubernetes") for Vector agents results in the following observed behavior (see chart below). The number of events for `internal_metrics` grows over time (the reset was caused by restarting the Vector agents).

Query
```
sum(rate(vector_component_sent_events_total{component_kind="source"}[2m])) by (component_id)
```
Grafana Chart
<img width="1895" alt="Bildschirmfoto 2021-11-23 um 13 01 32" src="https://user-images.githubusercontent.com/131689/143021603-31936fc5-08cc-4702-9617-753291f37d0d.png">

### Additional Context

- Vector running K8s (GKE)
