### ISSUE TITLE
Investigate `http -> pipelines -> blackhole`

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#10144]
This issue is a record of and parent to the investigation of vector's performance when configured as in [this gist](https://gist.github.com/blt/a03197ce307917355754d1ad8ae19664#file-vector-toml). 

Inbound http_gen -- built from [lading](https://github.com/blt/lading/pull/119) at SHA 0da91906d56acc899b829cea971d79f13e712e21-- is configured like so:

```yaml
worker_threads: 1
prometheus_addr: "0.0.0.0:9001"

targets:
  vector:
    headers: {}
    target_uri: "http://localhost:8282/"
    bytes_per_second: "500 Mb"
    parallel_connections: 10
    block_sizes: ["1Kb", "2Kb"]
    method:
      post:
        maximum_prebuild_cache_size_bytes: "256 Mb"
        variant:
          static:
            static_path: "/home/blt/projects/com/github/timberio/vector/investigation/input.log"
```

Referenced `input.log` can be found [here](https://gist.github.com/blt/a03197ce307917355754d1ad8ae19664#file-input-log).
