### ISSUE TITLE
[UnitTest] unit tests not working with dropped events

### ISSUE THREAD

**Issue by mpucholblasco** [vectordotdev/vector#10167]
### Vector Version
```
vector 0.18.0 (x86_64-unknown-linux-musl c77e085 2021-11-18)
```

### Vector Configuration File

Located in `/tmp/vector.yaml`:
```yaml
sources:
  demo:
    type: demo_logs
    format: shuffle
    lines:
    - '{"message":"test1"}'

transforms:
  droptest:
    type: remap
    inputs: [demo]
    drop_on_error: true
    drop_on_abort: true
    reroute_dropped: true
    source: |-
      abort

  another:
    type: remap
    inputs: [droptest.dropped]
    source: |-
      . = parse_json!(.message)

sinks:
  console:
    type: console
    inputs:
      - another
    target: stdout
    encoding: json

tests:
  - name: test dropped event
    inputs:
      - type: log
        insert_at: droptest
        log_fields:
          message: '{ "message": "test1" }'
    outputs:
      - extract_from: another
        conditions:
          - type: vrl
            source: |-
              assert_eq!(., { "message": "test1" })
```

### Debug Output

Output is correct when vector executes normally:
```
vector -qq --config-yaml /tmp/vector.yaml
````
having the following output:
```json
{"message":"test1"}
{"message":"test1"}
{"message":"test1"}
{"message":"test1"}
```

However, the tests output is:
```
$ vector test /tmp/vector.yaml
Running tests
test test dropped event ... failed

failures:

test test dropped event:

check transform ComponentKey { id: "another", scope: Global } failed, no events received.
```

### Expected Behavior
Test should pass.

### Actual Behavior
Test is failing.
