### ISSUE TITLE
buffer_events of internal_metrics is always zero

### ISSUE THREAD

**Issue by flyingflo** [vectordotdev/vector#10174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector --version
vector 0.18.0 (x86_64-unknown-linux-gnu c77e085 2021-11-18)
```

### Vector Configuration File

```yaml
sinks:
  http:
    type: http
    inputs:
      - *
    uri: http://{{ fluentd_host }}:24226/{{ vector_fluent_influx_tag }}
    batch:
      timeout_secs: 15
    encoding:
      codec: json
```

### Expected Behavior
With #9327, sinks should report their buffer metrics. We observe `vector_buffer_events`, which should show the number of events stored in in-memory buffers. 
If I'm understand that correctly, when the http server is down, I would expect this to grow up to maximum size.
For comparison, we monitor `vector_events_in_total{component_name="http"} - vector_events_out_total{component_name="http"}`, which grows as expected.

### Actual Behavior
The `vector_buffer_events` is always zero.

**Comment by 001wwang** [comment]
Thanks for bringing this up, it's an interesting scenario. TL;DR: I don't think this is a buffer metrics bug but instead a somewhat counter-intuitive observation due to internal implementation details. 

Depending on how long you had this running, it's possible that the `vector_buffer_events` gauge was correctly `0`. The gauge is updated whenever events flow into and out of the buffer and emitted at an interval (every 2 seconds) for performance reasons. If the sink receives events quickly enough, `buffer_events` can appear as if it is always `0`.

The tricky part is: if my server is down, shouldn't the sink stop receiving events from the buffer and allow `buffer_events` to increase? Yes but not instantaneously. Even if the server backing the `http` sink is down, the sink can still receive events from the buffer, batch them, and then attempt to make (some limited number of) concurrent requests. After a while however, the failing requests will prevent further batches from being flushed, preventing events from flowing into the sink, and piling up events in the buffer. So, given time, you should see `buffer_events` reach max size.

You can observe this with a simple `demo_logs` source -> `http` sink Vector configuration like below (where the `http` sink server is down).
```toml
# Sources
[sources.internal_metrics]
type = "internal_metrics"

[sources.demo]
type = "demo_logs"
format = "syslog"
interval = 0.0 # Comment this out to slowly trickle events in, and buffer_events will read 0 for some time. 
# Otherwise, the sink's batching will be quickly flooded and you should see buffer_events reach max size.

# Sinks
[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "prometheus address"

# server is down the whole time
[sinks.http]
type = "http"
inputs = ["demo"]
uri = "http://insert-some-url-here" 
batch.timeout_secs = 15
encoding.codec = "json"
```  

Let me know if that makes sense, or if you're observing something different.

**Comment by jszwedko** [comment]
As another note, we have an issue to add instrumentation to sink batching that should help make it more visible where events are in Vector: https://github.com/vectordotdev/vector/issues/9719

**Comment by flyingflo** [comment]
Actually, the issue here might be, as @001wwang suggests, that we don't understand where our events are inside vector. 
I tried to add a sink with an invalid URL and a demo source to our setup, which does already have internal_metrics and a prometheus exporter:

```toml
[sources.demo]
type = "demo_logs"
format = "syslog"
interval = 0.0 # Comment this out to slowly trickle events in, and buffer_events will read 0 for some time. 
# Otherwise, the sink's batching will be quickly flooded and you should see buffer_events reach max size.

# server is down the whole time
[sinks.httpdemo]
type = "http"
inputs = ["demo"]
uri = "http://insert-some-url-here" 
batch.timeout_secs = 15
encoding.codec = "json"
```
The `buffer_events{component_name="httpdemo"}` metric of the httpdemo sink reaches 501.
For comparison I look at `vector_events_in_total{component_name="httpdemo"} - vector_events_out_total{component_name="httpdemo"}` which reaches 100625 (where the outgoing events are zero).

Compared to my previous test, where I stopped the HTTP service of a valid http sink with a file source, the buffer seems to fill here, which is not clear to me.

I need to understand where the events are, however, in order to understand, what happens if vector crashes or is shut down. What events do we loose in which situation and what kind of delivery can vector guarantee?
