### ISSUE TITLE
parse_key_value will not fail if value isn’t a properly formatted key/value string

### ISSUE THREAD

**Issue by pgrange** [vectordotdev/vector#10175]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.18.0 (x86_64-unknown-linux-musl c77e085 2021-11-18)
```

### Vector Configuration File

```toml
[transforms.kv_parser]
  inputs = ['nowhere']
  type = "remap"
  source = '''
    parsed, err = parse_key_value(.message)
    if err == null {
      . = parsed
    } else {
      .failed = true
    }
  '''

[[tests]]
  name = "parse_key_value should fail for not properly formatted key/value string"
  [[tests.inputs]]
    type = "log"
    insert_at = "kv_parser"
    log_fields.message = "this is not a kv message"
  [[tests.outputs]]
    extract_from = "kv_parser"
    [[tests.outputs.conditions]]
      type = "vrl"
      source = 'assert_eq!(.failed, true)'
```

### Debug Output

```
RUST_BACKTRACE=full vector -vvv test --config-toml=bug.toml

Running tests
test parse_key_value should fail for not properly formatted key/value string ... failed

failures:

test parse_key_value should fail for not properly formatted key/value string:

check transform 'kv_parser' failed conditions:
  condition[0]: source execution failed: 
error[E000]: function call error for "assert_eq" at (0:25): assertion failed: null == true
  ┌─ :1:1
  │
1 │ assert_eq!(.failed, true)
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^ assertion failed: null == true
  │
  = see language documentation at https://vrl.dev

payloads (events encoded as JSON):
   input: {"message":"this is not a kv message","timestamp":"2021-11-25T17:13:10.457028101Z"}
  output: {"a":true,"is":true,"kv":true,"message":true,"not":true,"this":true}
```

### Expected Behavior

The test should have succeeded. [Documentation of parse_key_value](https://vector.dev/docs/reference/vrl/functions/#parse_key_value) clearly states that:

> The parse_key_value function is fallible, which means that error handling is required for these errors:
> value isn’t a properly formatted key/value string

### Actual Behavior

The test fails. Eventhough the message is not a properly formatted string, the function parse_key_value does not fail. Actually, it returns an object containing one field per word which value is true. For instance for the exemple in the test, the function returns:

`{"a":true,"is":true,"kv":true,"message":true,"not":true,"this":true}`

### Example Data

See test above.

### Additional Context

no

### References

No matching issue found
