### ISSUE TITLE
Controlling log flow through group based collection

### ISSUE THREAD

**Issue by Pranjal-Gupta2** [vectordotdev/vector#10182]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

### Current Vector Version

```
vector 0.18.0 (x86_64-unknown-linux-gnu c77e085 2021-11-18)
```

### Use-cases

In the case of a big cluster with high log volume, we need to have a data flow control in the log collection process so that we can limit the collection rate based on the priority of application workloads in the cluster. 

### Attempted Solutions

Currently, `Kubernetes_logs` and `File` sources have `max_read_bytes` which will control how much data can be read from a single file at a given time. This parameter is useful for controlling the log flow in your data pipeline. However, `max_read_bytes` will give equal opportunity to all files included in a source. 

### Proposal

To control the flow of logs through our pipeline, we could add some group-based rate-limiting where each file member will be a part of a group with a group line limit and a time period in which that limit can be satisfied.

For example, in `Kubernetes_logs`, files could be grouped on the basis of namespace alone, pod name alone or using both namespace and pod names. 

```toml
[sources.kube]
    type = "kubernetes_logs"
    group_window_secs = "30s"

    # group using only namespace
    [[sources.kube.rule]]
        namespace = "logging"
        limit = 20000
        # 20000 line limit in 30s

    # group using only podname
    [[sources.kube.rule]]
        pod = "frontend"
        limit = 100
        # 100 line limit in 30s

    # group using both namespace and podname
    [[sources.kube.rule]]
        namespace = "website"
        pod = "backend"
        limit = 1500
        # 1500 line limit in 30s

```
