### ISSUE TITLE
Cannot read env variable that have dot char (.)

### ISSUE THREAD

**Issue by faroukelabady** [vectordotdev/vector#10185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
 V0.18.0
```

### Vector Configuration File

```toml
[sinks.elasticsearch]
type = "elasticsearch"
inputs = [ "modify" ]
endpoint = "${is.elastic.host}"
bulk.index = "vector-{{ application }}-%F"
mode = "bulk"
auth.user = "${is.elastic.user}"
auth.password = "${is.elastic.passowrd}"
auth.strategy = "basic"
```

### Expected Behavior

vector should be able to read env variables that contain dot chars (.) as these is common variables, especially in java properties files.

### Actual Behavior

vector wasn't able to understand is.elastic.host env variable, while in fluent-bit it was able to understand it.

### Example Data

```
export is.elastic.host=url_for_elastic
```
### Additional Context

running vector inside docker container

I believe the issue residee inside the following file
https://github.com/vectordotdev/vector/blob/master/src/config/vars.rs
the regex only checks for w+ (alphnumeric and underscore chars)
