### ISSUE TITLE
Blocking of the `kafka` consumer with large message

### ISSUE THREAD

**Issue by pbromb** [vectordotdev/vector#10199]
### Intro 

Hey, I've been using vector for a long time and it works great. 

The problem comes when I want to handle messages larger than 1MB. On the kafka broker side and on the message producers side I set the librdkafka_options."message.max.bytes" pameter and messages larger than 1MB get streamed. 

The problem occurs with the consumer, which is constantly blocked, and the process itself consumes 100% of CPU, there is no trace of the problem in the logs.

Any idea what could be causing the consumer to block?

### Vector Version

```
Testing on 0.15.2 - 0.18
```

### Vector Configuration File

```toml
[sinks.file_sink]
    type = "file"
    inputs = ["log_format_monolog2_t", "log_format_monolog2_split_t2"]
    compression = "none"
    path = "/tmp/vector-%Y-%m-%d.log"
    encoding.codec = "text"

[sources.kafka_src]
    bootstrap_servers = "127.0.0.1:9094"
    group_id = "vector-test"
    key_field = "logs"
    topics = ["logs"]
    type = "kafka"
    librdkafka_options."fetch.message.max.bytes" = "4242880"

[transforms.kafka_t]
    inputs = ["kafka_src"]
    source = """
. = parse_json!(.message)
"""
    type = "remap"

[transforms.log_format_monolog2_split_t]
    inputs = ["router.log_format_monolog2_split_t"]
    source = """
.message = parse_json!(.message)
.message.context.content = parse_json!(.message.context.payload)
del(.message.context.payload)
del(.message.context.httpStatusCode)
del(.message.context.response)
. = unnest!(.message.context.content)
"""
    type = "remap"

[transforms.log_format_monolog2_split_t2]
    inputs = ["log_format_monolog2_split_t"]
    source = """
eventTime = to_timestamp((.message.context.content.fixTimeEpoch / 1000000) ?? 0.0)
.message.context.eventTime = format_timestamp!(eventTime, "%Y-%m-%dT%T%.6f%:z")
.message.context.type = "event"
. = merge(., .message)
"""
    type = "remap"

[transforms.log_format_monolog2_t]
    inputs = ["router.log_format_monolog2_t"]
    source = """
structured, err = parse_json(.message)
if err == null {
. = merge(., structured) ?? {}
.timestamp = parse_timestamp(.datetime, "%Y-%m-%dT%H:%M:%S%.6f%:z") ?? now()
}
"""
    type = "remap"

[transforms.router]
    inputs = ["kafka_t"]
    type = "route"

[transforms.router.route]
    log_format_monolog2_split_t = ".log_format == \"monolog2_split\""
    log_format_monolog2_t = ".log_format == \"monolog2\""
...
```

### Debug Output

```
Nov 30 08:20:43 hostname vector[1902]: 2021-11-30T07:20:43.009621Z TRACE vector: Beep.
Nov 30 08:20:44 hostname vector[1902]: 2021-11-30T07:20:44.009764Z TRACE vector: Beep.
Nov 30 08:20:45 hostname  vector[1902]: 2021-11-30T07:20:45.009842Z TRACE vector: Beep.
Nov 30 08:20:46 hostname vector[1902]: 2021-11-30T07:20:46.010023Z TRACE vector: Beep.
Nov 30 08:20:47 hostname vector[1902]: 2021-11-30T07:20:47.010082Z TRACE vector: Beep.


strace: Process 1904 attached
strace: [ Process PID=1904 runs in x32 mode. ]
strace: [ Process PID=1904 runs in 64 bit mode. ]
mprotect(0x7f2a14129000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1412a000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1412b000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1412c000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1412d000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1412e000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1412f000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14130000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14131000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14132000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14133000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14134000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14135000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14136000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14137000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14138000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14139000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1413a000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1413b000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1413c000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1413d000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1413e000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1413f000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14140000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14141000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14142000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14143000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14144000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14145000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14146000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14147000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14148000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14149000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1414a000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1414b000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1414c000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1414d000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1414e000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1414f000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14150000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14151000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14152000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14153000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14154000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14155000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14156000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14157000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14158000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14159000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1415a000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1415b000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1415c000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1415d000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1415e000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a1415f000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f2a14160000, 4096, PROT_READ|PROT_WRITE) = 0

```
