### ISSUE TITLE
Require users to pick an output data type for components that output multiple data types

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#10248]
Recently we introduced the ability to target data types in component outputs (i.e., `<source_id>.logs`), but users aren't aware of that, and and most users do not specify a type in their configurations. For example:

```toml
[sources.agent]
type = "datadog_agent"

[transforms.process]
type = "remap"
inputs = ["agent"]
source = "..."
```

Most configuration look like that ^. Where users do not specify the data type as part of their `inputs`. This introduces a foot-gun when a customer starts receiving a new data type. Imagine a user that wrote the `process` transform with the assumption that it would be processing logs, and then they flipped on forwarding of metrics or traces to Vector. They would receive unexpected runtime errors since their remap script is designed for logs.

To solve this, I propose that we force users to explicitly choose the data type they want to operate on if a component outputs multiple types. So, in the above example, the user would be required to write this:

```toml
[sources.agent]
type = "datadog_agent"

[transforms.process]
type = "remap"
inputs = ["agent.logs"]
source = "..."
```

Or this if they want to operate on all data types:

```toml

```toml
[sources.agent]
type = "datadog_agent"

[transforms.process]
type = "remap"
inputs = ["agent.*"]
source = "..."
```

The `.*` is required if you want all types, forcing the user to opt-into all type.

cc @lukesteensen and @jszwedko
