### ISSUE TITLE
Docs for `log_to_metric` missing `[[..]]`

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#10344]
The [docs example](https://vector.dev/docs/reference/configuration/transforms/log_to_metric/) for `log_to_metric` suggest the following example:

```toml
[transforms.my_transform_id.metrics]
  field = "duration"
  name = "duration_total"
  namespace = "service"
  type = "counter"
```

The heading actually needs to be:

```toml
[[transforms.my_transform_id.metrics]]
```

Since it is possible to define multiple metrics for that transform.
