### ISSUE TITLE
Seeing rate limited warnings when using adaptive concurrency with Loki sink.

### ISSUE THREAD

**Issue by sam-mcbr** [vectordotdev/vector#10364]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.18.1
```

### Vector Configuration File

```yaml
vector:
          role: Stateless-Aggregator
          fullnameOverride: {{ .Values.vectorApplicationName}}
          image:
            repository: <repo>
            tag: 0.18.1-debian
          replicas: {{ int .Values.vectorNumReplicas }}
          resources: {{- toYaml .Values.vectorResources | nindent 12 }}
          serviceAccount:
            create: true
            annotations:
# ...
            automountToken: true
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
          tolerations: []
          podMonitor:
            enabled: true
            port: prometheus
            additionalLabels:
# ...
            metricRelabelings:
              {{- toYaml .Values.vectorMetricRelabelings | nindent 14 }}
          autoscaling:
            enabled: true
            minReplicas: {{ int .Values.vectorNumReplicas }}
            maxReplicas: 15
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 70
          customConfig:
            data_dir: /vector-data-dir
            api:
              enabled: true
              address: 0.0.0.0:8686
              playground: false
            sources:
              internal_metrics:
                type: internal_metrics
              {{- toYaml .Values.vectorSources | nindent 14 }}
            transforms:
# ...
            sinks:
              prometheus:
                type: prometheus
                inputs: [internal_metrics]
                address: 0.0.0.0:9090
              loki:
                type: loki
                inputs: [<from_our_transform>]
                endpoint: <endpoint>
                encoding:
                  codec: json
                batch:
                  max_bytes: 400000
                out_of_order_action: rewrite_timestamp
                labels:
# ...
                remove_label_fields: true
```

### Expected Behavior

On `0.16.0-nightly-2021-07-28`, we were just seeing pod logs like with warnings about rewriting timestamps. We do not configure any loki sink adaptive concurrency options. We upgraded to `0.18.1` and expected to continue seeing those warnings, but not warnings about rate limiting since this should be handled automatically.

### Actual Behavior

On `0.18.1`, we are now seeing additional warning logs about rate limiting the internal logs.

### Example Data

Logs on `0.16.0-nightly-2021-07-28`:
```
2021-12-08T20:30:35.509399Z  WARN sink{component_kind="sink" component_id=loki component_type=loki component_name=loki}: vector::internal_events::loki: Received out-of-order event, rewriting timestamp. internal_log_rate_secs=30
```

Logs on `0.18.1`:
```
2021-12-08T20:29:47.938987Z  WARN sink{component_kind="sink" component_id=loki component_type=loki component_name=loki}: vector::internal_events::loki: Received out-of-order event, rewriting timestamp. internal_log_rate_secs=30

2021-12-08T20:29:47.939024Z  WARN sink{component_kind="sink" component_id=loki component_type=loki component_name=loki}: vector::internal_events::loki: Internal log [Received out-of-order event, rewriting timestamp.] is being rate limited.

2021-12-08T20:30:35.509370Z  WARN sink{component_kind="sink" component_id=loki component_type=loki component_name=loki}: vector::internal_events::loki: Internal log [Received out-of-order event, rewriting timestamp.] has been rate limited 2982 times.
```

### Additional Context

[Discord thread.](https://discord.com/channels/742820443487993987/753400475545501836/917858955227717682)
