### ISSUE TITLE
Vector not releasing memory

### ISSUE THREAD

**Issue by sam-mcbr** [vectordotdev/vector#10372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.18.0
```

### Vector Configuration File

```yaml
vector:
          role: Stateless-Aggregator
          fullnameOverride: {{ .Values.vectorApplicationName}}
          image:
            repository: <repo>
            tag: 0.18.1-debian
          replicas: {{ int .Values.vectorNumReplicas }}
          resources: {{- toYaml .Values.vectorResources | nindent 12 }}
          serviceAccount:
            create: true
            annotations:
# ...
            automountToken: true
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
          tolerations: []
          podMonitor:
            enabled: true
            port: prometheus
            additionalLabels:
# ...
            metricRelabelings:
              {{- toYaml .Values.vectorMetricRelabelings | nindent 14 }}
          autoscaling:
            enabled: true
            minReplicas: {{ int .Values.vectorNumReplicas }}
            maxReplicas: 15
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 70
          customConfig:
            data_dir: /vector-data-dir
            api:
              enabled: true
              address: 0.0.0.0:8686
              playground: false
            sources:
              internal_metrics:
                type: internal_metrics
              {{- toYaml .Values.vectorSources | nindent 14 }}
            transforms:
              remap_to_json:
                type: remap
                inputs: [logging_service_s3_*]
                source: |-
                  parsed_json, err = parse_json(.message)
                  if err == null {
                    structured_json, err = object(parsed_json)
                    if err == null {
                      . = merge(., structured_json)
                    }
                  }
              parse_account_name:
                type: remap
                inputs: [remap_to_json]
                source: |-
                  account_name, err = split(.object, "/")[1]
                  if err == null {
                    .account_name = account_name
                  }
              parse_cluster_or_source_name:
                type: remap
                inputs: [parse_account_name]
                source: |-
                  cluster_or_source_name, err = split(.object, "/")[2]
                  if err == null && cluster_or_source_name == "eks-control-plane" {
                    .source_name = cluster_or_source_name
                  } else if err == null {
                    .cluster_name = cluster_or_source_name
                  }
              remap_timestamp:
                type: remap
                inputs: [parse_cluster_or_source_name]
                source: |-
                  if .source_name == "eks-control-plane" {
                    .timestamp, err = to_int(.timestamp) / 1000
                    if err != null {
                      .timestamp = now()
                    }
                  }
                  .timestamp = to_timestamp(.timestamp)
              add_host_label:
                type: remap
                inputs: [remap_timestamp]
                source: |-
                  .vector_host = get_hostname() ?? "unknown"
            sinks:
              prometheus:
                type: prometheus
                inputs: [internal_metrics]
                address: 0.0.0.0:9090
              loki:
                type: loki
                inputs: [add_host_label]
                endpoint: <endpoint>
                encoding:
                  codec: json
                batch:
                  max_bytes: 400000
                out_of_order_action: rewrite_timestamp
                labels:
# ...
                remove_label_fields: true
```

### Expected Behavior

We have a metric that tracks events in - events out. We had a larger increase in events in, which lead to an increase in our events in memory metric:

![](https://media.discordapp.net/attachments/753400475545501836/918261545908191232/unknown.png)

This caused an increase in the memory used:

![](https://media.discordapp.net/attachments/753400475545501836/918261709523800084/unknown.png)

We expected the memory footprint to decrease after the events had finished processing.

### Actual Behavior

As seen in the above graph, the memory footprint continued to be larger than expected till we restarted the deployment.

### Additional Context

[Discord discussion.](https://discord.com/channels/742820443487993987/753400475545501836/918154844907380796)
