### ISSUE TITLE
Vector starts consuming memory endlessly

### ISSUE THREAD

**Issue by loyd** [vectordotdev/vector#10378]
We have an event flow ~30k/s rate and want to deliver events to ClickHouse. This stream is auxiliary, so we want to tune Vector to insert batches once per ~10s to avoid redundant merges by ClickHouse.

With default settings, it works fine, but if we are playing with `batch.max_size`, the memory usage starts to increase endlessly. Sometimes immediately (with big `batch.max_size`), sometimes after some stable time. We've met OOM several times already.

This issue can be related to https://github.com/vectordotdev/vector/issues/10372.

## Vector Version
Vector version: `vector 0.18.1 (x86_64-unknown-linux-gnu c4adb60 2021-11-30)`

### Vector Configuration File
```toml
[sources.dumps]
type = "file"
include = ["..."]
read_from = "beginning"
acknowledgements = true

[transforms.prepare_dumps]
type = "remap"
inputs = ["dumps"]
source = "..."

[sinks.dump_log]
type = "clickhouse"
inputs = ["prepare_dumps"]
endpoint = "..."
database = "..."
table = "dump_log"
compression = "gzip"
healthcheck.enabled = true

request.concurrency = 5 # "adaptive" behaves similarly, but less stable for tests

buffer.type = "memory"
buffer.when_full = "block"
buffer.max_events = 100_000

batch.timeout_secs = 10
batch.max_bytes = VARYING # see graphs below
```

## Metrics
To illustrate the problem more clearly, we've collected some metrics, hope this will help the developers to fix the problem.
Numbers next to white lines are values of `batch.max_bytes`.

![trouble](https://user-images.githubusercontent.com/952180/145437299-fde1da68-ee29-4e40-ab8e-01c0ecb17e8f.png)

The last configuration (`max_size = 15_000_000`) has been stable for one hour after, but then start blowing up too.

### Expected Behavior
The memory usage is increasing up to some level and then remains stable.

### Actual Behavior
With some values of `batch.max_bytes` the memory usage is increasing endlessly.
