### ISSUE TITLE
`internal_logs` are not consistently decorated with host property

### ISSUE THREAD

**Issue by lstyles** [vectordotdev/vector#10403]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.18.1
```

### Vector Configuration File

```yaml
sources:
      internal_logs:
        type: internal_logs
sinks:
      elasticsearch_vector:
        type: elasticsearch
        inputs:
          - internal_logs
        endpoint: http://core-es.internal.xxxxxxxxxxxx.io:9200
        mode: bulk
        bulk:
          index: vector-%Y.%m
        compression: none
```

### Expected Behavior

I would expect all events sent to Elasticsearch to have the `host` property populated

### Actual Behavior

Some events have `host` property populated but others don't.

![image](https://user-images.githubusercontent.com/3707675/145713492-888db4d2-182e-489e-b2b4-ef390d26353c.png)
