### ISSUE TITLE
Vector panicked at "Duplicate output id in fanout" when reloads config

### ISSUE THREAD

**Issue by xdatcloud** [vectordotdev/vector#10412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.18.1 (x86_64-apple-darwin c4adb60 2021-11-30)
```

#### Origin Configuration

```toml
data_dir = "/tmp"

[sources.generator]
type = "generator"
format = "shuffle"
lines = ["Test message 1", "Test message 2"]

[transforms.add_tags_foo-0]
type = "remap"
inputs = ["generator"]
source = """
.foo = "tagged by add_tags_foo-0"
"""

[transforms.add_tags_foo-1]
type = "remap"
inputs = ["generator"]
source = """
.foo = "tagged by add_tags_foo-1"
"""

[transforms.add_tags_bar-0]
type = "remap"
inputs = ["add_tags_foo-0"]
source = """
.bar = "tagged by add_tags_bar-0"
"""

[transforms.add_tags_bar-1]
type = "remap"
inputs = ["add_tags_foo-1"]
source = """
.bar = "tagged by add_tags_bar-1"
"""

[sinks.console]
type = "console"
inputs = [
    "add_tags_bar-0",
    "add_tags_bar-1",
]
encoding = "json"
```

#### Configuration After Change

```toml
data_dir = "/tmp"

[sources.generator]
type = "generator"
format = "shuffle"
lines = ["Test message 1", "Test message 2"]

# [transforms.add_tags_foo-0]
# type = "remap"
# inputs = ["generator"]
# source = """
# .foo = "tagged by add_tags_foo-0"
# """

[transforms.add_tags_foo-0]
type = "remap"
inputs = ["generator"]
source = """
.foo = "tagged by add_tags_foo-1"
"""

# [transforms.add_tags_bar-0]
# type = "remap"
# inputs = ["add_tags_foo-0"]
# source = """
# .bar = "tagged by add_tags_bar-0"
# """

[transforms.add_tags_bar-0]
type = "remap"
inputs = ["add_tags_foo-0"]
source = """
.bar = "tagged by add_tags_bar-1"
"""

[sinks.console]
type = "console"
inputs = [
    "add_tags_bar-0",
    # "add_tags_bar-1",
]
encoding = "json"
```

### Debug Output

https://gist.github.com/xdatcloud/5ce84ea242df4fb8e0e0b62b4e0de2d5

### Expected Behavior

Vector reloads config and keep working.

### Actual Behavior

Vector crashed.

### Additional Context

Run vector with `--watch-config` enabled:

```
RUST_BACKTRACE=full vector -vvv -w true -c config.toml
```
