### ISSUE TITLE
[EnvVar Interpolation] Add support for empty string defaults

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#10420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
vector 0.18.1 (x86_64-unknown-linux-gnu c4adb60 2021-11-30)
```

### Use-cases

* Interpolation of environment variables into Vector configuration files.
* Interpolation of variables with defaults that can be empty strings, i.e. for declaring optional variables.

### Attempted Solutions

At the moment, Vector is unable to use the empty string as a default for interpolated environment variables.

Consider the following simple Vector pipeline configuration file in YAML:
```yaml
sources:
  logs:
    type: demo_logs
    format: syslog

sinks:
  http:
    type: http
    inputs:
      - logs
    uri: ${SINKS_HTTP_URI:-http://localhost:8080}
    proxy:
      enabled: ${SINKS_HTTP_PROXY_ENABLED:-true}
      http: ${SINKS_HTTP_PROXY_HTTP:-}
      https: ${SINKS_HTTP_PROXY_HTTPS:-}
      no_proxy: ${SINKS_HTTP_PROXY_NO_PROXY:-}
    encoding:
      codec: json
```

If you try to validate the above configuration, you get the following error:
```
$ vector validate vector.yaml
Failed to load ["vector.yaml"]
------------------------------
x sinks.http.proxy.no_proxy: invalid type: unit value, expected string or list of strings at line 17 column 5
```

The reason for this is because the environment variables were not interpolated to the default empty string with `${VAR:-}`, leading to the final interpolated YAML document to have a null node instead of an empty string node.

If we quote the variable that errors, we are able to force the interpolation to be of type string:
```yaml
no_proxy: '${SINKS_HTTP_PROXY_NO_PROXY:-}'
```

This time, the validation passes but there are warnings that the variables were not interpolated:
```
$ vector validate vector.yaml
Loaded with warnings ["vector.yaml"]
------------------------------------
~ Unknown env var in config. name = "SINKS_HTTP_PROXY_HTTP"
~ Unknown env var in config. name = "SINKS_HTTP_PROXY_HTTPS"
~ Unknown env var in config. name = "SINKS_HTTP_PROXY_NO_PROXY"
```

### Proposal

Other variable substitution systems such as the one in [Docker Compose files](https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution) do recognise empty strings as defaults.

I think Vector should also support this as it is a common way to make simple "optional" environment variables.

Probably the way to implement this in Vector would be to change the `+` qualifier to `*` in this regex:

https://github.com/vectordotdev/vector/blob/816d42c1e6f5718c531a12e2a71a11b6e6e8806b/src/config/vars.rs#L18

As a side note, I think implementing variable interpolation/substitution in the same way Docker Compose does it would be very handy/useful in Vector as well. In particular the syntax to specify mandatory variables:

> Similarly, the following syntax allows you to specify mandatory variables:
> ${VARIABLE:?err} exits with an error message containing err if VARIABLE is unset or empty in the environment.
> ${VARIABLE?err} exits with an error message containing err if VARIABLE is unset in the environment.
