### ISSUE TITLE
Kafka sink healthcheck is not working with templated topic

### ISSUE THREAD

**Issue by fpytloun** [vectordotdev/vector#10465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.18.1
```

### Vector Configuration File

```toml
    [sinks.out_fluent_kafka]
      type = "kafka"
      inputs = ["in_fluent"]
      encoding.codec = "json"
      bootstrap_servers = "kafka:9092"
      topic = "{{ _topic }}"
```

### Expected Behavior

Healthcheck should use some default topic. Either by adding new parameter, eg. `healthcheck.topic` or better by having parameter for default topic to catch events where templated topic doesn't match.

### Actual Behavior

```WARN vector::sinks::kafka::sink: Could not generate topic for healthcheck. error=Missing fields on event: ["_topic"]```
