### ISSUE TITLE
Vector panicked at '`async fn` resumed after completion'

### ISSUE THREAD

**Issue by xdatcloud** [vectordotdev/vector#10485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.18.1 (x86_64-apple-darwin c4adb60 2021-11-30)
```

#### Origin Configuration

```toml
data_dir = "/tmp"

[api]
enabled = true
address = "127.0.0.1:8686"

[sources.demo_logs]
type = "demo_logs"
format = "shuffle"
lines = ["hello", "world"]

[sinks.demo_logs_to_loki]
type = "loki"
inputs = [
    "demo_logs",
]
endpoint = "<endpoint>"
encoding.codec = "json"
batch.max_events = 10000
tenant_id = "<tenant_id>"
request.rate_limit_duration_secs = 1
request.rate_limit_num = 500

[sinks.demo_logs_to_loki.auth]
user = "<user>"
password = "<password>"
strategy = "basic"

[sinks.demo_logs_to_loki.labels]
host = "{{ host }}"
```

#### Configuration After Change (In order to trigger the panic)

```toml
data_dir = "/tmp"

[api]
enabled = true
address = "127.0.0.1:8686"

[sources.demo_logs]
type = "demo_logs"
format = "shuffle"
lines = ["hello", "world"]

[sinks.demo_logs_to_loki]
type = "loki"
inputs = [
    "demo_logs",
]
endpoint = "<endpoint>"
encoding.codec = "json"
batch.max_events = 10000
tenant_id = "<tenant_id>"
request.rate_limit_duration_secs = 1
request.rate_limit_num = 400 # this line modified, indeed any changes in config file will probably trigger the panic

[sinks.demo_logs_to_loki.auth]
user = "<user>"
password = "<password>"
strategy = "basic"

[sinks.demo_logs_to_loki.labels]
host = "{{ host }}"
```

### Debug Output

https://gist.github.com/xdatcloud/9af88c2652a283a693b942bf8d99f930

### Expected Behavior

Vector keep working.

### Actual Behavior

Vector exited due to the panic.

### Additional Context

Run vector with --watch-config enabled:

```
RUST_BACKTRACE=full vector -vvv -w true -c panic-test-config.toml
```

Please try to modify config file several times and the panic will probably occurred.
