### ISSUE TITLE
TLS and authentication support for nats sink

### ISSUE THREAD

**Issue by abh** [vectordotdev/vector#10533]
As mentioned in #8112 the nats sink doesn't support TLS or authentication, making it only useful for smaller/simpler use cases.

**Comment by bbigras** [comment]
Awesome.

Any release planned soon, so we'll be able to use it?

**Comment by jszwedko** [comment]
Hi @bbigras ,

Likely this or next week as 0.21.0.

**Comment by bbigras** [comment]
Is this valid? I get `authentication error - Nkey ""` on the nats side.

```toml
[sinks.sink_nats]
type = "nats"
inputs = [ "my_source_id" ]
url = "nats://nats:4222"
subject = "test_subject"
encoding.codec = "json"

  [sinks.sink_nats.auth]
  strategy = "nkey"
  nkey.nkey = "U_key"
  nkey.seed = "S_key"
```

I'll try with `auth.credentials_file, since vector has a unit test for it.
