### ISSUE TITLE
Investigate low performance of `http_to_http` soak test, with and without acknowledgements

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#10543]
The soak test performance numbers for `http_to_http_noack` and `http_to_http_acks` are significantly slower than expected:
1. The `noack` test runs slower than other soak tests that do much more work internally with transforms.
2. The `acks` test is running 4-5 times slower than the `noack` test, which does not reflect the minimal performance drop other soak tests with acknowledgements are exhibiting.

We need to investigate what is causing the reduced performance described above.

Ref #9877

**Comment by bruceg** [comment]
Here's where I'm at:

I have been unable to get minikube to work on my system due to my using btrfs for my partitions and some incompatibility with Kubernetes, so I have been running the soak tests manually outside of any container.

I have set up a script that creates an equivalent setup to the `http_to_http_*` soak tests, with `http_gen` and `http_blackhole` from `lading` and the(trivial) vector config, along with a Prometheus instance (in a container) monitoring metrics from each component. Configs are below.

All the data is running over the loopback interface. Running `iperf3` on that interface reports about 5GB/sec throughput. Running the `http_gen` directly into `http_blackhole` gets about 2GB/sec throughput. However, adding vector into the path drops that to 50MB/sec throughput, as measured by either the generator or the blackhole. Further, the graph for `bytes_received` on the `http_blackhole` runs at _exactly_ 50MB/sec except for the occasional brief spike up or down.

This 50MB/sec number does not change if the `http` sink within vector is replaced with a `blackhole` sink, nor if acknowledgements are turned off or on, nor with concurrency set to automatic or fixed at a high value, nor if the number of generator clients is increased to 100 or dropped to 2. It does decrease _slightly_ below 50MB with only one client, but not signifcantly.

When running with a significant number of clients, htop shows that vector is running across all of my CPU cores (8*2 threads), but only using about 200% CPU. I produced a few flame graphs from running this, and nothing seemed to stand out as being a large bottleneck (which is reflected by it not being CPU bound).

`http_blackhole.yaml`:
```yaml
worker_threads: 10
binding_addr: "127.0.0.1:8080"
prometheus_addr: "127.0.0.1:9081"
body_variant: "Nothing"
```

`http_gen_http_source.yaml`
```yaml
worker_threads: 2
prometheus_addr: "127.0.0.1:9082"

targets:
  vector:
    target_uri: "http://127.0.0.1:8282/"
    bytes_per_second: "6 Gb"
    parallel_connections: 10
    method:
      post:
        variant: "ascii"
        maximum_prebuild_cache_size_bytes: "256 Mb"
    headers: {}
```

`vector.toml`:
```toml
data_dir = "/var/lib/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.http_source]
type = "http"
acknowledgements = false
address = "127.0.0.1:8282"

##
## Sinks
##

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "127.0.0.1:9080"

#[sinks.blackhole]
#type = "blackhole"
#inputs = ["http_source"]

[sinks.http_sink]
type = "http"
inputs = ["http_source"]
uri = "http://127.0.0.1:8080"
encoding = "text"
healthcheck.enabled = false
buffer.type = "memory"
buffer.max_events = 100000
request.concurrency = 100
```

Startup script:
```sh
LADING=$HOME/Datadog/lading/target/release
VECTOR=$HOME/Datadog/vector/target/release
export VECTOR_LOG=warn

set -ex

trap '
  set +e
  kill $pid_http_gen
  kill $pid_blackhole
' EXIT

(
  cd ..
  cargo build --release --bin vector --no-default-features --features sources-http,sinks-console,sinks-blackhole,sinks-http,sources-internal_metrics,sinks-prometheus
)

$LADING/http_blackhole --config-path $PWD/http_blackhole.yaml &
pid_blackhole=$!

$LADING/http_gen --config-path $PWD/http_gen_http_source.yaml &
pid_http_gen=$!

$VECTOR/vector --quiet --config $PWD/vector.toml 
```

**Comment by blt** [comment]
@bruceg what SHA does your setup [here](https://github.com/vectordotdev/vector/issues/10543#issuecomment-998991493) work from?

**Comment by bruceg** [comment]
I have tried with a few different heads. I was using 9500436be and 350cc8ae4 when testing with tokio-console, and 21e252598 and ff0294aa8 before that.

**Comment by blt** [comment]
Working from 089fdabc8f442b1ef4bfb13bafc4bf02175b0193 and with your setup I've reproduced the behavior, although on my machine it tops out at 106MB/s. I have isolated vector to 4 CPUs and can confirm that vector is only using just under 2.

**Comment by blt** [comment]
As I mention over in #10550 I strongly suspect the decoder is our serialization point. In-rig we have a small number of incoming connections (10) pushing as fast as possible, so concurrency in the underlying warp http server are not motivated. Likewise when I fully comment out the internals of [`SimpleHttpSource::build_event`](https://github.com/vectordotdev/vector/blob/859d8ca9c80e5a660568971268496cff3e9379d2/src/sources/http.rs#L93) I achieve 2Gb/s throughput. I re-introduced everything but https://github.com/vectordotdev/vector/blob/859d8ca9c80e5a660568971268496cff3e9379d2/src/sources/http.rs#L120-L132 and throughput fell back to uncommented levels. Commenting https://github.com/vectordotdev/vector/blob/859d8ca9c80e5a660568971268496cff3e9379d2/src/sources/http.rs#L105-L130 climbs throughput back up to cap. 

I haven't fully digested how the decoder works yet, @lukesteensen and @pablosichert are the domain experts here. I do note that `next :: SmallVec<[Event; 1]>` and don't expect #10550 to show an outstanding improvement.

**Comment by pablosichert** [comment]
Has https://github.com/vectordotdev/vector/pull/10506 been taken into account here, that landed just two days ago?

**Comment by pablosichert** [comment]
Nevermind, I just noted you pointed to the `decode_eof` calls only. If that's using the `bytes` decoder, I agree that we shouldn't allow it to impact performance that much.

**Comment by blt** [comment]
I want to confirm that there's not something accidentally pokey in the decoder -- I'm still reading it -- but there's every possibility that we'll want to follow a similar approach as taken in #10506 if it can be motivated.

**Comment by bruceg** [comment]
While there might be something in the decoder causing an issue, I think I have found a bigger bottleneck. If I comment out the event send call in `Pipeline`, the throughput goes from a hard line at 50MB/sec to a more variable range around 650MB/sec, _and_ the CPU usage of that task raises from 200% to over 900%. Given that commenting out creation of events also drops this send process, this starts to point a very strong finger at the one-event-at-a-time channel serialization being a real bottleneck in higher concurrency loads at least.

Going further down the chain, commenting out just the send in `Fanout` produces a throughput of around 260MB/sec with a CPU usage around 650%. I got a little higher throughput if I replace forwarding events into the `Fanout` at the topology level for whatever that's worth.

**Comment by bruceg** [comment]
Remove the send in `Pipeline`:
```diff
--- a/src/pipeline.rs
+++ b/src/pipeline.rs
@@ -69,29 +69,9 @@ impl Pipeline {
             }
 
             let event_bytes = event.size_of();
-            match self.inner.start_send(event) {
-                Ok(()) => {
-                    // we good, keep looping
-                    sent_count += 1;
-                    sent_bytes += event_bytes;
-                }
-                Err(error) if error.is_full() => {
-                    // We only try to send after a successful call to poll_ready, which reserves
-                    // space for us in the channel. That makes this branch unreachable as long as
-                    // the channel implementation fulfills its own contract.
-                    panic!("Channel was both ready and full; this is a bug.")
-                }
-                Err(error) if error.is_disconnected() => {
-                    if sent_count > 0 {
-                        emit!(&EventsSent {
-                            count: sent_count,
-                            byte_size: sent_bytes,
-                        });
-                    }
-                    return Poll::Ready(Err(ClosedError));
-                }
-                Err(_) => unreachable!(),
-            }
+            // we good, keep looping
+            sent_count += 1;
+            sent_bytes += event_bytes;
         }
         if sent_count > 0 {
             emit!(&EventsSent {
```

Remove the send in `Fanout`:
```diff
--- a/lib/vector-core/src/fanout.rs
+++ b/lib/vector-core/src/fanout.rs
@@ -170,21 +170,12 @@ impl Sink<Event> for Fanout {
     fn start_send(mut self: Pin<&mut Self>, item: Event) -> Result<(), ()> {
         let mut i = 1;
         while let Some((_, sink)) = self.sinks.get_mut(i) {
-            if let Some(sink) = sink.as_mut() {
-                if sink.as_mut().start_send(item.clone()).is_err() {
-                    self.handle_sink_error(i)?;
-                    continue;
-                }
-            }
+            if let Some(sink) = sink.as_mut() {}
             i += 1;
         }
 
         if let Some((_, sink)) = self.sinks.first_mut() {
-            if let Some(sink) = sink.as_mut() {
-                if sink.as_mut().start_send(item).is_err() {
-                    self.handle_sink_error(0)?;
-                }
-            }
+            if let Some(sink) = sink.as_mut() {}
         }
 
         Ok(())
```

Replace forwarding events into the `Fanout`:
```diff
--- a/src/topology/builder.rs
+++ b/src/topology/builder.rs
@@ -167,7 +167,7 @@ pub async fn build_pieces(
         };
 
         let (output, control) = Fanout::new();
-        let pump = rx.map(Ok).forward(output).map_ok(|_| TaskOutput::Source);
+        let pump = rx.for_each(|_| async {}).map(|()| Ok(TaskOutput::Source));
         let pump = Task::new(key.clone(), typetag, pump);
 
         // The force_shutdown_tripwire is a Future that when it resolves means that this source
```

**Comment by jszwedko** [comment]
I was able to reproduce roughly the same magnitude of difference in the acks vs noacks HTTP soak tests on an AWS instance (`c5.4xlarge`) running Ubuntu 20.04. I generated a flamegraph that seems to show it spending a lot of time in `EventFinalizers::merge` (see below).

After reproducing within the soak test framework with:

```
./soaks/soak.sh --local-image --soak 'http_to_http_acks http_to_http_noack'  --baseline 5e04f1c7429f8947bc00eca7350f54b57fffdae9 --comparison 5e04f1c7429f8947bc00eca7350f54b57fffdae9
```

I then ran it outside of the soak test framework so I could profile using this diff:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index d95210620..8eabdced6 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -23,7 +23,7 @@ split-debuginfo = "unpacked" # Faster debug builds on macOS
 # This results in roughly a 5% reduction in performance when compiling locally vs when
 # compiled via the CI pipeline.
 [profile.release]
-debug = false # Do not include debug symbols in the executable.
+debug = true # Do not include debug symbols in the executable.
 
 [profile.bench]
 debug = true
diff --git a/soaks/common/configs/http_blackhole.yaml b/soaks/common/configs/http_blackhole.yaml
index d76f65cd2..0e252a32f 100644
--- a/soaks/common/configs/http_blackhole.yaml
+++ b/soaks/common/configs/http_blackhole.yaml
@@ -1,3 +1,3 @@
 worker_threads: 1
 binding_addr: "0.0.0.0:8080"
-prometheus_addr: "0.0.0.0:9090"
+prometheus_addr: "0.0.0.0:9092"
diff --git a/soaks/common/configs/http_gen_http_source.yaml b/soaks/common/configs/http_gen_http_source.yaml
index 1b478731d..0997efa99 100644
--- a/soaks/common/configs/http_gen_http_source.yaml
+++ b/soaks/common/configs/http_gen_http_source.yaml
@@ -1,9 +1,9 @@
 worker_threads: 2
-prometheus_addr: "0.0.0.0:9090"
+prometheus_addr: "0.0.0.0:9091"
 
 targets:
   vector:
-    target_uri: "http://vector:8282/"
+    target_uri: "http://localhost:8282/"
     bytes_per_second: "100 Mb"
     parallel_connections: 10
     method:
diff --git a/soaks/tests/http_to_http_acks/terraform/vector.toml b/soaks/tests/http_to_http_acks/terraform/vector.toml
index 48b7dc70f..46dac04a5 100644
--- a/soaks/tests/http_to_http_acks/terraform/vector.toml
+++ b/soaks/tests/http_to_http_acks/terraform/vector.toml
@@ -24,7 +24,7 @@ address = "0.0.0.0:9090"
 [sinks.http_sink]
 type = "http"
 inputs = ["http_source"]
-uri = "http://http-blackhole:8080"
+uri = "http://localhost:8080"
 encoding = "text"
 healthcheck.enabled = false
 buffer.type = "memory"
diff --git a/soaks/tests/http_to_http_noack/terraform/vector.toml b/soaks/tests/http_to_http_noack/terraform/vector.toml
index 1ab2890f3..58080a049 100644
--- a/soaks/tests/http_to_http_noack/terraform/vector.toml
+++ b/soaks/tests/http_to_http_noack/terraform/vector.toml
@@ -24,7 +24,7 @@ address = "0.0.0.0:9090"
 [sinks.http_sink]
 type = "http"
 inputs = ["http_source"]
-uri = "http://http-blackhole:8080"
+uri = "http://localhost:8080"
 encoding = "text"
 healthcheck.enabled = false
 buffer.type = "memory"
```

This allowed me to run lading generator and sink locally in docker:

```
docker run -it --net=host -v $PWD/common/configs:/etc/lading  -it ghcr.io/blt/lading:sha-0da91906d56acc899b829cea971d79f13e712e21 /http_gen --config-path /etc/lading/http_gen_http_source.yaml
```

```
docker run -it --net=host -v $PWD/common/configs:/etc/lading  -it ghcr.io/blt/lading:sha-0da91906d56acc899b829cea971d79f13e712e21 /http_blackhole --config-path /etc/lading/http_blackhole.yaml
```

While communicating with a Vector instance outside of Docker. I also ran prometheus locally with:

```
global:
  scrape_interval: 1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "input"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9091"]

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "output"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9092"]
```

To observe the throughput.

I then used `cargo-flamegraph` to generate the flame graphs (uploading as txt since Github doesn't allow SVG):

```
./target/release/vector --config soaks/tests/http_to_http_acks/terraform/vector.toml -v
```

[acks.svg.txt](https://github.com/vectordotdev/vector/files/7786427/acks.svg.txt)

Here we can see that `EventFinalizers::merge` features prominently.

I then ran a flamegraph of the noacks test for comparison:

```
~/.cargo/bin/flamegraph --no-inline  ./target/release/vector --config soaks/tests/http_to_http_noack/terraform/vector.toml -v
```

[noacks.svg.txt](https://github.com/vectordotdev/vector/files/7786424/noacks.svg.txt)

I also grabbed a perf capture of the acks test: 
[perf.data.txt](https://github.com/vectordotdev/vector/files/7786429/perf.data.txt)
