### ISSUE TITLE
Avoid enum deserialization for configuration

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10582]
Currently we leverage enums for configuration deserialization in a few places, but this can result in inscrutable error messages like:

```
data did not match any variant of untagged enum VectorConfig at line 36 column 9
```

As a user, it can be difficult to figure out why the config is invalid.

Related issues:

* https://github.com/vectordotdev/vector/discussions/10558
* https://github.com/vectordotdev/vector/issues/8138
* https://github.com/vectordotdev/vector/issues/8207
* https://github.com/vectordotdev/vector/issues/6800
* https://github.com/vectordotdev/vector/issues/2991
* https://github.com/vectordotdev/vector/issues/8589
* https://github.com/vectordotdev/vector/issues/9386

**Comment by tshepang** [comment]
I was puzzled getting the error, because the following looks correct (unless you squint)..

```toml
[sources.in]
 type = "vector"
 address = "0.0.0.0:1234"
 version = 2

[sinks.out]
 inputs = ["in"]
 type = "blackhole"
```
