### ISSUE TITLE
kafka sasl mechanisms not working in alpine docker image

### ISSUE THREAD

**Issue by abh** [vectordotdev/vector#10619]
When configuring the kafka sink with the following settings ("SCRAM-SHA-515" is one of the options in the documentation).

```
      sasl:
        enabled: true
        mechanism: "SCRAM-SHA-512"
        username: vector
        password: "${KAFKA_PASSWORD}"
```

I get an error that rdlibkafka isn't compiled with the necessary options / libraries: 

```
2021-12-29T04:19:19.206320Z ERROR vector::topology: Configuration error. error=Sink "kafka-geodns": creating kafka producer failed: Client creation error: No provider for SASL mechanism SCRAM-SHA-512: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN
```

I tried with 0.18.1-alpine and both the 2021-12-28-alpine nightly image. The -debian flavor of the image does work however.
