### ISSUE TITLE
Vector aggregator's transform bottleneck

### ISSUE THREAD

**Issue by namm2** [vectordotdev/vector#10622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.18.1
```

### Vector Configuration File

Vector agent
```yaml
customConfig:
  data_dir: "/vector-data-dir"
  sources:
    kubernetes_logs_agent:
      type: kubernetes_logs
      max_line_bytes: 131072
      delay_deletion_ms: 900000
      glob_minimum_cooldown_ms: 2000
      extra_field_selector: metadata.namespace=default
    internal_metrics_agent:
      type: internal_metrics
  sinks:
    vector_agent:
      type: vector
      inputs:
        - kubernetes_logs_agent
      address: vector-aggregator-haproxy.vector.svc:9080
      healthcheck:
        enabled: true
    prometheus_exporter_agent:
      type: prometheus_exporter
      inputs:
        - internal_metrics_agent
      address: 0.0.0.0:9090
```

Vector aggregator
```yaml
replicas: 1

haproxy:
  enabled: true
  replicaCount: 3
  resources:
    requests:
      cpu: 200m
      memory: 64Mi

customConfig:
  data_dir: "/vector-data-dir"
  timezone: Etc/UTC
  log_schema:
    message_key: vector_message
  sources:
    kubernetes:
      type: vector
      address: 0.0.0.0:9080
  # transform: {}
  sinks:
    blackhole_aggregator:
      type: blackhole
      inputs:
        - kubernetes
        # - <transform>
      print_interval_secs: 30
      rate: 100000
```
<details>
<summary>Logs generator manifest:</summary>

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dummy-logs-json
  labels:
    component: test
spec:
  parallelism: 5
  backoffLimit: 4
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        name: dummy-logs-json
    spec:
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
      containers:
      - name: flog
        image: mingrammer/flog
        imagePullPolicy: IfNotPresent
        command:
        - flog
        - -f
        - json
        - -b
        - "524288000"
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: dummy-logs-rfc3164
  labels:
    component: test
spec:
  parallelism: 5
  backoffLimit: 4
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        name: dummy-logs-rfc3164
    spec:
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
      containers:
      - name: flog
        image: mingrammer/flog
        imagePullPolicy: IfNotPresent
        command:
        - flog
        - -f
        - rfc3164
        - -b
        - "524288000"
      restartPolicy: Never

```
</details>

### Expected Behavior

Vector would use as much computing resources as possible

### Actual Behavior

Vector aggregator is limited at ~ 7 CPUs at 10k events/sec

### Example Data

Without any transfoms (vector source -> blackhole sink), vector processed very fast:
<img width="640" alt="Screen Shot 2021-12-29 at 16 43 46" src="https://user-images.githubusercontent.com/46129063/147679281-b0d35608-15fa-4a19-bee7-9a13c2306ce2.png">
<img width="640" alt="Screen Shot 2021-12-29 at 16 39 17" src="https://user-images.githubusercontent.com/46129063/147678944-87e40300-5364-45eb-a5b3-8ffb1799ad81.png">
<img width="640" alt="Screen Shot 2021-12-29 at 16 41 12" src="https://user-images.githubusercontent.com/46129063/147679026-34c74c69-3314-419d-b810-205a8aca5d37.png">

When some transforms VRL configs added, the processing power of aggregator pod is maxed at 7 CPUs at 10k events/sec
<img width="1305" alt="Screen Shot 2021-12-29 at 16 49 16" src="https://user-images.githubusercontent.com/46129063/147679784-8100db41-3ec9-4b39-ba9d-924a247f00eb.png">
<img width="1301" alt="Screen Shot 2021-12-29 at 16 49 52" src="https://user-images.githubusercontent.com/46129063/147679881-eb9e371d-d8f1-4fcf-a2e2-2484e9ae462a.png">

### Additional Context

I ran tests on an empty cluster with n1-standard-16 instances, so CPU & MEMORY resources are plenty. The topology is simple:
```
[ vector-agent ] ---> [ haproxy ] ---> [ vector aggregator ]
```

After tested with vector sending k8s source to blackhole sink directly, I added a 1000 lines of transforms block. But vector wouldn't use higher than 7 CPUs and events rate is stable at 10k events/sec that's sending to blackhole sink. Given plenty of resources doesn't seem matter. It looks like is there a bottleneck somewhere that limited vertical scaling?
