### ISSUE TITLE
bug(prometheus_exporter sink): distributions are not transformed into aggregated histograms/summaries

### ISSUE THREAD

**Issue by LeoQuote** [vectordotdev/vector#10635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.18.1 (x86_64-unknown-linux-musl c4adb60 2021-11-30)
```

### Vector Configuration File

```toml

data_dir = "/data/vector"


[sources.vector_source]
type = "vector"
address = "0.0.0.0:9000"
version = "2"


[sinks.prometheus_exporter]
  type = "prometheus_exporter"
  inputs = [ "vector_source" ]
  address = "0.0.0.0:9598"
  default_namespace = "nginx"
```

### Debug Output

not done yet, will do.

### Expected Behavior

runs normally for hours and days

### Actual Behavior

the response time of exporter will be greater and greater, from initially <1s to over 10s and finally prometheus cannot scrape it anymore. The memory usage is also increasing , from 200M to over 1000M

### Example Data

will append it later

### Additional Context

this service is run inside a container, dont know if there's any existing issue.

### References

* https://vector.dev/docs/reference/configuration/sinks/prometheus_exporter/#memory-usage
