### ISSUE TITLE
Loki sink results in error code 400 when pushing to Grafana Cloud Loki instance

### ISSUE THREAD

**Issue by codeandroid** [vectordotdev/vector#10642]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.0 (x86_64-unknown-linux-musl da60b55 2021-12-28)
```

### Vector Configuration File

```yaml

sources:
  in_auth:
    type: file
    include:
    - /var/log/auth.log
    ignore_older: 864000

transforms:
  x_timestamp:
    type: lua
    (...)

sinks:
  cloud:
    inputs:
    - x_timestamp
    type: loki
    endpoint: "https://logs-prod-eu-west-0.grafana.net"
    auth:
      strategy: "basic"
      user: "--sensitive--"
      password: "--sensitive--"
    encoding:
      codec: "json"
    healthcheck:
      enabled: false
    labels:
      forwarder: "vector"
    request:
      in_flight_limit: 1
```

full: https://gist.github.com/codeandroid/676a94b7b949f4583e3e89165e46c3bb

### Debug Output

https://gist.github.com/codeandroid/3250630db2121de213e2d480cd931182

### Expected Behavior

Successful push of event into Grafana Cloud Loki instance.

### Actual Behavior

HTTP request failed with status code 400.

```
vector_1  | 2021-12-31T00:01:37.745325Z DEBUG sink{component_kind="sink" component_id=cloud component_type=loki component_name=cloud}:request{request_id=0}:http: vector::internal_events::http_client: HTTP response. status=400 Bad Request version=HTTP/1.1 headers={"content-type": "application/json; charset=utf-8", "date": "Fri, 31 Dec 2021 00:01:37 GMT", "content-length": "137", "via": "1.1 google", "alt-svc": "clear"} body=[137 bytes]
vector_1  | 2021-12-31T00:01:37.745484Z ERROR sink{component_kind="sink" component_id=cloud component_type=loki component_name=cloud}:request{request_id=0}: vector_core::stream::driver: Service call failed. error=ServerError { code: 400 } request_id=0
```

I would've loved to dig deeper, unfortunately, I could not find a way to get vector to log the response body. It could contain important hints.

### Additional Context

Vector is being run in a docker container on a Synology NAS 918+.

Image:  timberio/vector:0.19.0-alpine
