### ISSUE TITLE
Disk buffering doesn't send events until more come in

### ISSUE THREAD

**Issue by mmelvin0** [vectordotdev/vector#10806]
When using disk buffering, the last N log events are not delivered via the Loki sink until more events come in.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.0 (x86_64-unknown-linux-gnu da60b55 2021-12-28)
```

#### sources/journal.toml

```toml
type = 'journald'
acknowledgements.enabled = false
batch_size = 1
current_boot_only = false
```

#### sinks/loki.toml

```toml
type = 'loki'
inputs = ['journal']
endpoint = 'https://loki.internal.home.arpa/'
labels.app = '{{src.app}}'
labels.file = '{{src.file}}'
labels.host = '{{src.host}}'
labels.src = '{{src.type}}'
encoding.codec = 'json'
auth.strategy = 'basic'
auth.user = '$LOKI_USER'
auth.password = '$LOKI_PASS'
batch.timeout_secs = 1
out_of_order_action = 'rewrite_timestamp'
buffer.type = 'disk'
buffer.max_size = 104900000
```

### Expected Behavior

Log events from the systemd journal are delivered to my Loki instance at `https://loki.internal.home.arpa/` within a few seconds of Vector reading them from the journal.

### Actual Behavior

With disk buffering, the last N events aren't delivered (seemingly at all) until more events are logged to the journal. For example, if I restart Vector (which itself is logging to the journal), I won't see any journal messages about the restart appear in Loki until the _second_ time I restart Vector... and then I will only see the first restart's events, not the second.

If I change the `buffer.*` options to those shown below, events are delivered more-or-less immediately.

```toml
buffer.type = 'memory'
buffer.max_events = 500
```

### Additional Context

Vector is running in Arch Linux in VMware Workstation. However I have seen the same thing happening on other hardware/OS combinations.

Loki is version 2.4.1 and running on Windows 10 Pro.

**Comment by cspargo-apptio** [comment]
I think i'm hitting the same issue. Also with vector 0.19.0 and disk buffer, but use the Splunk HEC sink.

I have multiple inputs to the sink:
- One of them only generates about 12 events every 5 minutes. Those events never appear to get to splunk, except if I restart vecto. At that point, it seems to forward the previous events (not new ones), which I assume were sitting in the disk buffer. 
- Another input has a higher event rate, and most, but not all of the events are forwarded to splunk. Again, restarting seems to cause them the missing ones to get flushed though.

I also observe a difference in the overall number of events in the metric "vector_buffer_received_events_total" versus "vector_buffer_sent_events_total".

If I change to the buffer type to memory, or downgrade to 0.18.0, I see normal behaviour again.

**Comment by spencergilbert** [comment]
@mmelvin0 does this behavior also change for you if you downgrade to `0.18.x`?

**Comment by mmelvin0** [comment]
@spencergilbert Yes indeed I just verified the disk buffer works as expected for me in `0.18.1`.

**Comment by spencergilbert** [comment]
Thanks! I'll investigate this some tonight and see if I can find any likely causes.

cc @tobz

**Comment by spencergilbert** [comment]
@cspargo-apptio would you be able to share the configuration you're using here? @tobz and I haven't been able to exactly reproduce with some more basic testing, still poking around at it

**Comment by cspargo-apptio** [comment]
the following is a much cut-down version of my configuration, that I tested hits the issue

there is a single agent with a single file source, that forwards to the aggregator

```
    api:
      enabled: false
    data_dir: /vector-data-dir
    sinks:
      sink_blackhole:
        inputs:
        - source_testapp
        print_interval_secs: 60
        type: blackhole
      sink_vector_agg:
        address: vector-aggregator-test.vector.svc.cluster.local:9000
        buffer:
          max_events: 500
          type: memory
        inputs:
        - trans_testapp
        type: vector
        version: "2"
    sources:
      source_testapp:
        include:
        - /var/log/testapp/testapp.log
        type: file
    transforms:
      trans_testapp:
        inputs:
        - source_testapp
        source: |
          .kubernetes.host = "${VECTOR_SELF_NODE_NAME}"
          .source_type = "testapp"
          del(.host)
        type: remap
```

the aggregator receives from the agent and sends to splunk hec

```
    api:
      enabled: false
    data_dir: /vector-data-dir
    log_schema:
      host_key: host
      message_key: message
      source_type_key: source_type
      timestamp_key: timestamp
    sinks:
      prom-exporter:
        address: 0.0.0.0:9090
        inputs:
        - source_internal_metrics
        type: prometheus_exporter
      sink_blackhole:
        inputs:
        - source_vector_agent
        print_interval_secs: 60
        type: blackhole
      sink_splunk_host_syslog:
        buffer:
          max_size: 5368709120
          type: disk
        compression: gzip
        encoding:
          codec: json
          except_fields:
          - source_type
          - splunk_source
          - splunk_index
        endpoint: https://address.of.splunkheavyforwarder
        host_key: kubernetes.host
        index: '{{ splunk_index }}'
        inputs:
        - trans_host_syslog_for_splunk
        source: '{{ splunk_source }}'
        sourcetype: '{{ source_type }}'
        tls:
          ca_file: /certs-ca/ca_cert.pem
        token: ${SPLUNK_HEC_TOKEN_KUBERNETES_APP}
        type: splunk_hec_logs
    sources:
      source_internal_metrics:
        type: internal_metrics
      source_vector_agent:
        address: 0.0.0.0:9000
        type: vector
        version: "2"
    transforms:
      trans_host_syslog_for_splunk:
        inputs:
        - source_vector_agent
        source: ".log = del(.message)\n.cluster=\"testcluster\"\n.splunk_source = .file
          \ndel(.file)\n.splunk_index = \"testapp\"\n"
        type: remap
```

The file that I noticed the issue with was written in 12 event bursts every 5 minutes (i.e. 12 events are all written at the same time, once every 5 minutes). I tried increasing the frequency of this to write 12 events every 60 seconds, and at that point I noticed that it did eventually forward the events to splunk after a delay.

The pattern I have subsequently observed is that the sink does not send any events until it accumulates 100 events in the buffer, and then it sends them all. Then we need to wait for another 100 events before it sends again.

The graph below is a graph of vector_buffer_received_events_total (green ) and vector_buffer_sent_events_total (yellow) for the splunk sink. In this case, the source is logging 12 events every 60 seconds. You can see the sent events total increases every time the received events reaches 100 events. 

![image](https://user-images.githubusercontent.com/78777058/149706137-ff6aab67-8936-4f18-b27d-b208a534b760.png)

The next graph is the same, except logging 12 events every 5 minutes. Again, it only sends after 100 events have been logged, which means a delay of 40 minutes before the events are sent to splunk.

![image](https://user-images.githubusercontent.com/78777058/149706162-efb41184-f624-400b-85e2-fc4fd834c5b0.png)

If I revert to vector 0.18.0 or use the memory buffer for the sink, the received and sent events graphs are identical (i.e. it's sending them to splunk immediately).

**Comment by tobz** [comment]
@cspargo-apptio Appreciate the minimized reproduction / configuration.  👍🏻 

We're pretty sure we know why this is happening, given the regression occurring in 0.19.x and the specifics around flushing at 100 events, etc.  We're still working through replicating your reproduction -- in truth, hopefully we can now reproduce it with this updated configuration -- and once we have that as a stable base, we should hopefully be able to fix it pretty quickly.

**Comment by spencergilbert** [comment]
Super minimal reproduction:

```toml
data_dir = "/tmp/vector/github-10806"

[sources.lines]
type = "demo_logs"
count = 75
format = "shuffle"
lines = ["one", "two", "three", "four", "five"]
interval = 1

[transforms.remap]
type = "remap"
inputs = ["lines"]
source = '''
  .
  '''

[sinks.blackhole]
type = "blackhole"
inputs = ["remap"]

[sinks.blackhole.buffer]
type = "disk"
max_size = 10000000 # Roughly 10MB.
```

The key is a transform component. Likely introduced here: https://github.com/vectordotdev/vector/pull/10265/files#diff-e76eab15ec40a1f8b5d8857a3c2a7ff87baf5641ae5e40f25e2e87e7c79cfa46L262
