### ISSUE TITLE
Fluentd events piling up

### ISSUE THREAD

**Issue by alexandv** [vectordotdev/vector#10818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

0.19

### Vector Configuration File

```yaml
api:
  enabled: true

sources:
  fluentd_agg:
    type: fluent
    address: 0.0.0.0:3900
  vector_metrics:
    type: internal_metrics

transforms:
  format:
    type: remap
    inputs:
    - fluentd_agg
    source: |-
      .message, err = to_string(.host) + " | " + to_string(.mes) + " | " + to_string(.val) 
      if err != null {
        log(err, level: "error")
      }

sinks:
  mtail_sink:
    type: socket
    inputs:
      - format
    mode: unix
    encoding:
      codec: text
    path: /out/out.socket
```

### Actual Behavior

Memory increases steadily until the container runs out of memory (it runs inside Kubernetes). The number of open connections also increase steadily and never goes down. The number of in events from `fluentd_agg` source increases much faster than the number of out events.

CPU usage is stable and low. The buffers for the socket sink look fine.

What could explain this behavior?

**Comment by spencergilbert** [comment]
Likely related: https://github.com/vectordotdev/vector/pull/10803

I suspect fluentbit/d is continuously opening new connections as Vector attempts to apply back pressure. As I understand it we've merged config support that can limit the max number of connections which could mitigate the issue.

cc @fuchsnj

**Comment by alexandv** [comment]
Yes fluentd is opening a new connection every second after flushing the current buffer. But the connection is properly closed at the TCP level before opening the new connection as far as I can see. 

That's the behavior we want to load balance between multiple vector pods exposed using a Kubernetes service.

**Comment by fuchsnj** [comment]
This is a known issue for TCP based sources, and `fluent` is particularly bad. 
https://github.com/vectordotdev/vector/pull/10491 was recently merged in which gives you a config option to set how many concurrent connections are handled by Vector. This _should_ work even if you are seeing the TCP connection itself close before a new one is opened. `fluentd` can send _very_ large requests, and those may sit around in memory after the connection is closed. This new setting will make sure that is fully flushed before processing more connections. However, this new config is off by default.

The RFC @spencergilbert linked is designed to fix this by default, but the connection limit is your best option right now.

**Comment by fuchsnj** [comment]
Closing as a duplicate of https://github.com/vectordotdev/vector/issues/8820. Please re-open if the connection limit settings do not work for you, or there is something else wrong here.

**Comment by alexandv** [comment]
Thanks @fuchsnj . I'll try to limit the number of TCP connections for this sink. 

One point that is not completely clear to me is why the sink was not able to keep up. We were receiving around 200 messages/sec on this sink at the time and CPU usage was pretty low.

**Comment by jszwedko** [comment]
@alexandv 

> Thanks @fuchsnj . I'll try to limit the number of TCP connections for this sink.
> 
> One point that is not completely clear to me is why the sink was not able to keep up. We were receiving around 200 messages/sec on this sink at the time and CPU usage was pretty low.

Hmm, yeah, that is lower I would have expected too. I did a quick benchmark with this config:

```toml
[sources.source0]
type = "stdin"

[sinks.sink0]
inputs = ["source0"]
mode = "unix"
path = "/tmp/test.sock"
type = "socket"
encoding.codec = "text"
```

Exercising with:

```
flog -l | pv | vector --config /tmp/tmp.toml -qqq
```

And, on the listening side:

```
nc -l -U /tmp/test.sock > /dev/null
```

I was able to get roughly 20 MiB / s. This largely depended on message sizes. I initially started with just `yes hello` for input and saw much lower throughput: ~2.5 MiB/s.

Testing with just:

```
flog -l | pv | nc -U /tmp/test.sock
```

Similarly saw ~20 MiB/s so Vector matches up there.

It could be worth benchmarking your specific setup some more. For example, maybe try swapping out the `socket` sink with a `blackhole` sink and see what sort of throughput you see. Feel free to open a Github Discussion if you want to chat about this further!
