### ISSUE TITLE
`vector tap` won't tap a `filter` transform in 0.19.0

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10833]
This appears to be a regression from `0.18.1`.

Config:

```toml
data_dir = "/var/lib/vector/"
api.enabled = true

[sources.source0]
max_length = 102400
type = "stdin"

[sources.source0.decoding]
codec = "bytes"

[sources.source0.framing]
method = "newline_delimited"

[transforms.transform0]
inputs = ["source0"]
type = "filter"
condition = "true"

[sinks.sink0]
inputs = ["transform0"]
type = "blackhole"
```

Running this with 0.18.1:

```
yes "{}" | vector --config /tmp/tmp.toml
```

And then running `vector tap transform0` gives the expected result:

```
{"host":"COMP-C02DV25MML87","message":"{}","source_type":"stdin","timestamp":"2022-01-13T00:06:54.476584Z"}
{"host":"COMP-C02DV25MML87","message":"{}","source_type":"stdin","timestamp":"2022-01-13T00:06:54.478606Z"}
{"host":"COMP-C02DV25MML87","message":"{}","source_type":"stdin","timestamp":"2022-01-13T00:06:54.483468Z"}
```

Running with 0.19.0 gives nothing.
