### ISSUE TITLE
Can no longer `vector tap` sources

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10847]
This appears to be an unreleased regression from `0.19.0`.

Config:

```toml
data_dir = "/var/lib/vector/"
api.enabled = true

[sources.source0]
max_length = 102400
type = "stdin"

[sources.source0.decoding]
codec = "bytes"

[sources.source0.framing]
method = "newline_delimited"

[transforms.transform0]
inputs = ["source0"]
type = "filter"
condition = "true"

[sinks.sink0]
inputs = ["transform0"]
type = "blackhole"
```

Running this with 0.19.0:

```
yes "{}" | vector --config /tmp/tmp.toml
```

And then running `vector tap source0` gives the expected result:

```
{"host":"COMP-C02DV25MML87","message":"{}","source_type":"stdin","timestamp":"2022-01-13T17:55:52.624184Z"}
{"host":"COMP-C02DV25MML87","message":"{}","source_type":"stdin","timestamp":"2022-01-13T17:55:52.624289Z"}
{"host":"COMP-C02DV25MML87","message":"{}","source_type":"stdin","timestamp":"2022-01-13T17:55:52.631233Z"}
{"host":"COMP-C02DV25MML87","message":"{}","source_type":"stdin","timestamp":"2022-01-13T17:55:52.635943Z"}
{"host":"COMP-C02DV25MML87","message":"{}","source_type":"stdin","timestamp":"2022-01-13T17:55:52.636023Z"}
```

Running with master as of 2c02b4742 gives nothing.
