### ISSUE TITLE
0.19.0 elasticsearch.index field fails tests

### ISSUE THREAD

**Issue by antonyc** [vectordotdev/vector#10842]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version
```
vector --version
vector 0.19.0 (x86_64-unknown-linux-gnu da60b55 2021-12-28)
```

### Vector Configuration File

Something like this (there are some template placeholders, sorry):

```yaml
elastic:
      type: elasticsearch  # https://vector.dev/docs/reference/configuration/sinks/elasticsearch/
      inputs:
        - log_presink_hook
      compression: gzip
      endpoint: "${elastic_endpoint}"
      index: log-controlplane-{{`{{ kubernetes.pod_namespace }}`}}-%Y-%m-%d
      healthcheck: # --require-healthy if need to stop
        enabled: true
      batch:
        max_bytes: 10490000  # 10 MiB
        timeout_secs: 1
      buffer:
        type: memory
        max_events: 500
        when_full: drop_newest
      bulk_action: index  # TODO: change to create and use data stream https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html
      auth:
        password: "${elasticuser_password}"
        user: "${elasticuser_name}"
        strategy: basic
      request:
        concurrency: adaptive  # https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#adaptive-request-concurrency-arc
        retry_initial_backoff_secs: 1
        timeout_secs: 60
```

### Expected Behavior

tests pass when I run `vector test --config-yaml ...`

### Actual Behavior

On versions `0.17.3`, `0.18.1`  they DO pass. But after trying to upgrade to `0.19.0` I get:

```
x sinks.elastic: unknown field `index`, expected one of `endpoint`, `doc_type`, `suppress_type_name`, `id_key`, `pipeline`, `mode`, `compression`, `encoding`, `batch`, `request`, `auth`, `query`, `aws`, `tls`, `bulk`, `data_stream`, `metrics` at line 78 column 9

error while running test check against chart in module.k8s_preprod_frankfurt.module.aggregating_vector
Makefile:8: recipe for target 'test' failed
make: *** [test] Error 1
```
