### ISSUE TITLE
parse_nginx_log can not parse log line

### ISSUE THREAD

**Issue by songleo** [vectordotdev/vector#10929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
$ k exec vector-fm7wx -- vector --version
vector 0.19.0 (x86_64-unknown-linux-gnu da60b55 2021-12-28)
```

### Vector Configuration File

```yaml
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      kubernetes_logs:
        type: kubernetes_logs
        extra_label_selector: "app.kubernetes.io/name=automation-controller"
    sinks:
      stdout:
        type: console
        inputs:
          - filter_id
          - remap_id_1
        encoding:
          codec: json
    transforms:
      remap_id:
        type: remap
        inputs:
          - kubernetes_logs
        source: . = .message
      filter_id:
        type: filter
        inputs:
          - remap_id
        condition: contains!(.message, "GET /api/v2/metrics HTTP/1.1")
      remap_id_1:
        type: remap
        inputs:
          - filter_id
        source: . = parse_nginx_log!(.message, "combined")
```

### Expected Behavior

should parse the log to a valid format.

### Actual Behavior
failed to parse the log line, and get this error:
```
2022-01-20T11:26:00.720321Z  WARN vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_nginx_log\" at (4:42): failed parsing log line" internal_log_rate_secs=30
```

### Example Data

this is my log line:

```
{"message":"10.244.0.227 - admin [20/Jan/2022:11:25:21 +0000] \"GET /api/v2/metrics HTTP/1.1\" 301 0 \"-\" \"Prometheus/2.26.1\" \"-\""}
{"message":"10.244.0.227 - admin [20/Jan/2022:11:25:21 +0000] \"GET /api/v2/metrics HTTP/1.1\" 301 0 \"-\" \"Prometheus/2.26.1\" \"-\""}
{"message":"10.244.0.227 - admin [20/Jan/2022:11:25:51 +0000] \"GET /api/v2/metrics HTTP/1.1\" 301 0 \"-\" \"Prometheus/2.26.1\" \"-\""}
```
