### ISSUE TITLE
enhancement(log_to_metric transform): allow specifying multiple field/name pairs in a given transformation

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#10934]
Currently, when using `log_to_metric`, a user must add a transformation "block" (can't think of a better name) for a given field to be mapped.  If a user has many fields that they want to convert, and many of them share the exact same transformation pattern -- same metric type, same aggregation mode, same tags, etc -- then this can become laborious and error-prone as they copy and paste the same block over and over.

It could potentially be useful to allow the `field` and `name` fields for a configured transformation be either a string or an array of strings, such that a user could specify multiple fields (and multiple names) in a single block.  For example:

```toml
# Current approach:
[[transforms.my_transform_id.metrics]]
type = "counter"
field = "status"
name = "response_total"
namespace = "service"

  [transforms.my_transform_id.metrics.tags]
  status = "{{status}}"
  host = "{{host}}"

[[transforms.my_transform_id.metrics]]
type = "counter"
field = "bytes_sent"
name = "bytes_sent_total"
namespace = "service"

  [transforms.my_transform_id.metrics.tags]
  status = "{{status}}"
  host = "{{host}}"

# Proposed enhancement:
[[transforms.my_transform_id.metrics]]
type = "counter"
field = ["status", "bytes_sent"]
name = ["response_total", "total_bytes_sent"]
namespace = "service"

  [transforms.my_transform_id.metrics.tags]
  status = "{{status}}"
  host = "{{host}}"
```

There would have to be some logic to verify that `field`/`name` had the same length, or maybe we'd want to switch to `fields`/`names`, or something, but I think the idea, regardless of implementation details, could help shrink the configuration size for some specific use cases.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
