### ISSUE TITLE
Azure SDK does not correctly parse connection_string for azure_blob storage

### ISSUE THREAD

**Issue by archoversight** [vectordotdev/vector#10979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.0 (x86_64-unknown-linux-gnu da60b55 2021-12-28)
```

### Vector Configuration File

```toml
[sinks.azure_storage_account]
type = "azure_blob"
connection_string = "myazureconnectionstring"
container_name = "azure-container-name"
blob_prefix = "logs/%F/"
compression = "gzip"
inputs = ["*__out"]
encoding.codec = "ndjson"
```

### Debug Output

```
2022-01-22T00:44:27.986705Z ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Unknown status code: 400 Bad Request component_kind="sink" component_type="azure_blob" component_id=azure_storage_account component_name=azure_storage_account
```

### Expected Behavior

Vector should work with a connection string containing a SAS token

### Actual Behavior

It fails

### Example Data

n/a

### Additional Context

This is mainly a tracking ticket so that vector can get a new release/fix version out as soon as https://github.com/Azure/azure-sdk-for-rust/pull/622 is merged, which fixes the parsing of the connection string.

### References

- https://github.com/Azure/azure-sdk-for-rust/pull/622
