### ISSUE TITLE
`aws_sqs` source is ignoring proxy settings

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#11020]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.0 (x86_64-unknown-linux-gnu da60b55 2021-12-28)
```

### Vector Configuration File

Consider the following example Vector configuration file

```yaml
sources:
  aws-sqs:
    type: aws_sqs
    region: MY_REGION
    queue_url: MY_QUEUE_URL
    auth:
      access_key_id: MY_ACCESS_KEY_ID
      secret_access_key: MY_SECRET_ACCESS_KEY
    proxy:
      enabled: true
      http: http://my-proxy-server:8080
      https: http://my-proxy-server:8080
    decoding:
      codec: json

sinks:
  console:
    type: console
    inputs:
      - aws-sqs
    encoding:
      codec: json
```

### Expected Behavior

We expect the proxy configuration to be used by the SQS client as [documented](https://vector.dev/docs/reference/configuration/sources/aws_sqs/#proxy).
Therefore, if for example we set a bogus proxy configuration like this:
```yaml
    proxy:
      enabled: true
      http: http://bogus:8080
      https: http://bogus:8080
```

Then we expect the SQS requests to never work because the proxy can't be reached.

### Actual Behavior

The `aws_sqs` source seems to be completely ignoring any proxy configuration and always connecting directly to the SQS queue URL. Proxy configuration is ignored either in the source itself (as in the above example), globally in the Vector configuration file or in environment variables such as `HTTP_PROXY` and `HTTPS_PROXY`.

Furthermore, if the machine has direct access to the AWS servers, and despite the bogus proxy configuration, the source is able to connect anyway to the SQS queue URL due to it not applying the bogus proxy configuration.

### Additional Context

I went to test other sources that have proxy configurations and they are applying these settings correctly:
* `aws_s3`
* `apache_metrics`
* `prometheus_scrape`

It is highly likely that `aws_sqs` is not applying the proxy configuration as an oversight in the implementation. At least I could not find any reference to proxy configurations in the [source code](https://github.com/vectordotdev/vector/tree/master/src/sources/aws_sqs).
