### ISSUE TITLE
Vector has no metrics processed_events_total and received_events_total after switched to vector API v2

### ISSUE THREAD

**Issue by namm2** [vectordotdev/vector#11036]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.18.1
```

and vector-aggregator helm chart v0.19.1

### Vector Configuration File

agent
```yaml
customConfig:
  sinks:
    vector-aggregator:
      type: vector
      version: "2"
      address: vector-aggregator.<namespace>.svc:9088
```

aggregatror:
```yaml
customConfig:
  sources:
    kubernetes:
      type: vector
      address: 0.0.0.0:9080
      version: "1"
    kubernetes_v2:
      type: vector
      address: 0.0.0.0:9088
      version: "2"
```

### Debug Output

Vector doesn't have metrics after switched to API v2

<img width="1288" alt="Screen Shot 2022-01-26 at 13 18 22" src="https://user-images.githubusercontent.com/46129063/151170213-f75b6db4-0ebe-4168-9a71-4348a7844250.png">

### Expected Behavior

Vector metrics show up with new component_id: kubernetes_v2

### Actual Behavior

Vector has no metrics of `processed_events_total` and `received_events_total` with v2 source

### Example Data

<img width="1288" alt="Screen Shot 2022-01-26 at 13 18 22" src="https://user-images.githubusercontent.com/46129063/151170494-0b09dc8c-ed1f-462d-b597-5f1bde3fde2e.png">

Is there anything I missed when configure vector source v2?
