### ISSUE TITLE
aws_ec2_metadata source fails silently

### ISSUE THREAD

**Issue by akasprzok** [vectordotdev/vector#11064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
v0.19.0
```

### Vector Configuration File

```toml
[sources.docker]
  type = "docker_logs"
  
[transforms.loki_docker_logs]
  type = "remap"
  inputs = ["docker"]
  source = '''
    del(.host) # will always be "vector", so not useful
    .task_definition = .label."com.amazonaws.ecs.task-definition-family"
    if (.task_definition == null && .container_name == "ecs-agent") {
	.task_definition = "ecs-agent"
    }
    del(.label) # contains all docker labels. Not super useful, omitting until proven otherwise
  '''

# Attempts to parse JSON out of the message, and logfmt if it's not JSON.
# If unsuccessful, it's a no-op.
[transforms.loki_structured_logs]
  type= "remap"
  inputs = ["loki_docker_logs"]
  source = '''
    structured =
      object(parse_json(.message) ?? null) ??
      parse_logfmt(.message) ??
      {}
    . = merge(., structured)
  '''
  
[transforms.loki_ec2_metadata]
  type = "aws_ec2_metadata"
  inputs = [ "loki_structured_logs" ]
  fields = [ "instance-id"]

[sinks.loki]
  type = "loki"
  inputs = [ "loki_ec2_metadata" ]
  # Determine the corresponding endpoint using the AWS_ENVIRONMENT env var.
  # This feels rather dirty, but will have to stay in place until we have a way to have env-specific Vector configs.
  endpoint = "http://loki-${AWS_ENVIRONMENT}.observability-prod.blockfi.com"
  encoding.codec = "json"
  # Rather than dropping out of order events, we have the sink rewrite the timestamp to the latest on that was pushed.
  # Otherwise Loki would not accept the events and drop them.
  out_of_order_action = "rewrite_timestamp"
  labels.service = "${PROJECT_NAME}"
  labels.instance_id = "{{ instance-id }}"
  labels.task_definition = "{{ task_definition }}" 
  remove_label_fields = true
```

### Debug Output

https://gist.github.com/akasprzok/f808919e61c24b938a6e8ad676528501

### Expected Behavior

Logs get happily shipped to Loki, with instance id as a label.

### Actual Behavior

Problem in the gist: Vector seems to lock up on the ec2 metadata transform. Everything works after that transform is removed. Metadata is enabled in the Launch Configuration, with 2 hop limit.

That's on one of our hosts. On other hosts we're seeing Vector work just fine for a few days, then silently cease to send logs to Loki without any logs on the Vector container that point to a problem. Again, removing the metadata transform fixes this.

### Additional Context

Vector is running as a container. The infrastructure is deployed on AWS EC2 via ECS. Vector has been working incredibly well for us minus the ec2 metadata transform.

We had previously debugged a similar issue with Jesse and thought it fixed.
