### ISSUE TITLE
Configuration error. error=sinks.my_sink_id: invalid type: unit value, expected string or map at line 19 column 9

### ISSUE THREAD

**Issue by base698** [vectordotdev/vector#11141]
Using the console sink https://vector.dev/docs/reference/configuration/sinks/console/ vector complains that type is not valid on startup.  Have tried `"console"` and `console`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
$ vector --version
vector 0.19.1 (x86_64-unknown-linux-gnu 3cf70cf 2022-01-25)
```

### Vector Configuration File

```yaml
---
data_dir: /tmp/vector-data-dir
api:
  enabled: true
  address: 0.0.0.0:8686
  playground: true

sources:
  my_source_id:
    type: http
    acknowledgements: false
    address: 0.0.0.0:4444
    encoding: text

sinks:
  my_sink_id:
    type: "console"
    inputs:
      - my_source_id
    target: stdout
    encoding: null
```

**Comment by base698** [comment]
The toml version works.
```toml
[sinks.my_sink_id]
encoding = "text"
type = "console"
inputs = [ "my_source_id" ]
target = "stdout"

```
