### ISSUE TITLE
gcp_stackdriver_metrics fails config check with "missing field `labels`" error

### ISSUE THREAD

**Issue by mloughran** [vectordotdev/vector#11157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.1 (x86_64-unknown-linux-gnu 3cf70cf 2022-01-25)
```

### Vector Configuration File

```toml
[sinks.gcp_metrics]
type = "gcp_stackdriver_metrics"
inputs = [ "my-source-or-transform-id" ]
credentials_path = "/path/to/credentials.json"
project_id = "vector-123456"
resource.type = "gce_instance"
resource.instance_id = "..."
resource.zone = "..."
```

### Debug Output

```
2022-02-02T19:18:03.059078Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace"
2022-02-02T19:18:03.059358Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
2022-02-02T19:18:03.060743Z ERROR vector::cli: Configuration error. error=missing field `labels` for key `sinks.gcp_metrics` at line 32 column 1
```

### Expected Behavior

Vector should start

### Actual Behavior

Vector exited with a non-obvious error message. I cannot get the `gcp_stackdriver_metrics` sink to work.

### Additional Context

The "example configuration" for https://vector.dev/docs/reference/configuration/sinks/gcp_stackdriver_metrics/ seems to be incomplete. Resource is listed as required (see https://vector.dev/docs/reference/configuration/sinks/gcp_stackdriver_metrics/#resource)

	[sinks.gcp_metrics]
	type = "gcp_stackdriver_metrics"
	inputs = [ "my-source-or-transform-id" ]
	credentials_path = "/path/to/credentials.json"
	project_id = "vector-123456"

	# Error:
	Configuration error. error=missing field `resource` for key `sinks.gcp_metrics`

When trying to add a resource, I get an error - "missing field `labels` for key `sinks.gcp_metrics`" which I do not understand:

	[sinks.gcp_metrics]
	type = "gcp_stackdriver_metrics"
	inputs = [ "my-source-or-transform-id" ]
	credentials_path = "/path/to/credentials.json"
	project_id = "vector-123456"
	resource.type = "global"

	# Error:
	Configuration error. error=missing field `labels` for key `sinks.gcp_metrics`

The same thing happens when attempting to specify resource.type as "gce_instance":

	[sinks.gcp_metrics]
	type = "gcp_stackdriver_metrics"
	inputs = [ "my-source-or-transform-id" ]
	credentials_path = "/path/to/credentials.json"
	project_id = "vector-123456"
	resource.type = "gce_instance"
	resource.instance_id = "..."
	resource.zone = "..."

	# Error:
	Configuration error. error=missing field `labels` for key `sinks.gcp_metrics`

I am using identical `resource` configuration for the [gcp_stackdriver_logs](https://vector.dev/docs/reference/configuration/sinks/gcp_stackdriver_logs/#resource) sink with no issues.

**Comment by spencergilbert** [comment]
Looking at our generated config (via `vector generate`), the metrics sink seems to require a config like:

```toml
[sinks.sink0]
inputs = ["source1"]
default_namespace = ""
project_id = ""
type = "gcp_stackdriver_metrics"

[sinks.sink0.resource]
type = ""

[sinks.sink0.resource.labels]

```

While the logs sink just needs:

```toml
[sinks.sink1]
inputs = ["source0"]
log_id = ""
project_id = ""
type = "gcp_stackdriver_logs"

[sinks.sink1.resource]
type = ""
```

I'll see if I can figure out why they're different, and at worst update the documentation to better reflect the requirements in configuration - hopefully this at least unblocks you @mloughran
