### ISSUE TITLE
Memory leak using `log_to_metric` transform

### ISSUE THREAD

**Issue by Zelpher** [vectordotdev/vector#11180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version
```
v0.19.0
```

### Vector Configuration File

```
---
sources:
  source-http-cdn:
    type: http
    address: 0.0.0.0:9090

transforms:
  transform-remap-from-source-http-cdn-to-json:
    type: remap
    inputs:
    - source-http-cdn
    source: |-
      . = parse_json!(string!(.message))
      .@timestamp = parse_timestamp!(.reqTimeSec, format: "%s%.3f")
      .property = .customField
      if (.cacheStatus == "0") {
        .cacheStatusString = "MISS"
      } else if (.cacheStatus == "1") {
        .cacheStatusString = "HIT"
      } else {
        .cacheStatusString = "UNKOWN"
      }
  transform-filter-to-elastic:
    type: filter
    inputs:
    - transform-remap-from-source-http-cdn-to-json
    condition: if match(.statusCode, r'^0|5[0-9]{2}$') { true } else { false }
  transform-logs2metrics-to-prom:
    type: "log_to_metric"
    inputs: ["transform-remap-from-source-http-cdn-to-json"]
    metrics:
    - type: "counter"
      field: "statusCode"
      name: "requests"
      tags:
        status: "{{statusCode}}"
        host: "{{reqHost}}"
        cpCode: "{{cp}}"
        cacheStatus: "{{cacheStatusString}}"
        property: "{{property}}"
    - type: "histogram"
      field: "reqEndTimeMSec"
      name: "requests_end_time"
      tags:
        host: "{{reqHost}}"
        cpCode: "{{cp}}"
        property: "{{property}}"
    - type: "histogram"
      field: "transferTimeMSec"
      name: "requests_transfer_time"
      tags:
        host: "{{reqHost}}"
        cpCode: "{{cp}}"
        property: "{{property}}"
    - type: "histogram"
      field: "turnAroundTimeMSec"
      name: "requests_turn_around_time"
      tags:
        host: "{{reqHost}}"
        cpCode: "{{cp}}"
        property: "{{property}}"
    - type: "histogram"
      field: "bytes"
      name: "requests_size"
      tags:
        host: "{{reqHost}}"
        cpCode: "{{cp}}"
        property: "{{property}}"

sinks:
  sink-prometheus-exporter:
    type: prometheus_exporter
    buckets: [30, 50, 70, 100, 200, 300, 500, 700, 1000, 2000, 3000, 11000, 31000]
    inputs:
    - transform-tag-cardinality-limit-to-internal-metrics
    - transform-logs2metrics-to-prom
    address: 0.0.0.0:9598
  sink-aws-s3:
    type: aws_s3
    [...]
  sink-elasticsearch-cdn:
    type: elasticsearch
    [...]
```

### Expected Behavior

We are currently using Vector (as Kubernetes pods) for collecting **http** access logs from a CDN provider. There's around ~ **900** incoming events per minutes, splitted among all the Vector pods (varying between **10** and **20** all the day).
These events are processed as below : 
- all events are archived to a S3 bucket,
- some (only errors) are sent to an Elasticsearch,
- and, finally, **metrics** are generated from these events and sent to a Prometheus exporter.

### Actual Behavior

It appears that there's a memory leak somewhere but we can't pinpoint precisely the component responsible of it. In fact, memory gets increasing continuously until reaching the pod memory limit and gets killed (corresponding to the peaks on the graph below) :

![vector_memory-leak_2](https://user-images.githubusercontent.com/3073431/152413172-b80bfc24-d90c-4391-87d5-845fff01928f.png)

We tried to increase memory (double from its base config) but pods keep get killed at slightly the same rate.

### Example Data
Here is the output of a `vector top` just before an OOM occurred :

![vector_memory-leak_1](https://user-images.githubusercontent.com/3073431/152413698-1df6f757-5db7-4a06-a69f-7f67dfbcddff.png)

### Additional Context
We observe this behavior only on production environment.

Disabling S3 or Elastisearch sink does not change anything.

At the moment, we are not sure if its the `log_to_metric`, `prometheus_exporter` or `http` source that is responsible of this memory leak.

**Comment by jszwedko** [comment]
Hi @Zelpher !

I think this might be the same issue that was fixed by #10741  . Would you want to try [the latest nightly version](https://packages.timber.io/vector/nightly/2022-02-03/) and see if it fixes it for you?

**Comment by Zelpher** [comment]
Hi @jszwedko 

Thank you for your response, I just tried the nightly version (2022-02-03) and seems to fix the memory leak !

![vector_memory-leak_6](https://user-images.githubusercontent.com/3073431/152639210-3a9b5374-4e1a-4fc4-9c18-f58efb802623.png)

However, I think there is a regression in bucket calculation (looks like the lower buckets are summed into the upper ones) : 

![vector_memory-leak_4](https://user-images.githubusercontent.com/3073431/152639260-927bd8b4-4f3f-438d-b456-1f2077276f6a.png)

Hoping this will be fixed before the next release !

**Comment by jszwedko** [comment]
Ah! Thanks @Zelpher . We'll look into this ahead of the next release.

**Comment by tobz** [comment]
@Zelpher Can you show me what series you're graphing there? Or at least the buckets/quantiles.  Ideally in table mode so that the amounts are shown.

Generally speaking, aggregated histogram buckets _should_ roll up.  That's by design.

**Comment by tobz** [comment]
Given that we've made many improvements to the `prometheus_exporter` sink since 0.18.0 -- #9769 and #10741 -- around flushing idle metrics and properly aggregating histograms, this scenario is now able to be controlled by users to suit their environment and needs.

**Comment by tobz** [comment]
(Mistakenly closed this after thinking I was responding on another issue.  Woops!)

**Comment by jszwedko** [comment]
I verified that 0.19 has the same expected behavior regarding histogram buckets: higher buckets will include the counts from lower buckets since each bucket is `le` or "less than".

**Comment by Zelpher** [comment]
Labels include kind of "sensitive" data, that's why I did not include them :/ 

The buckets graphed here are those defined in `sink-prometheus-exporter`, thus : `[30, 50, 70, 100, 200, 300, 500, 700, 1000, 2000, 3000, 11000, 31000]` (and `+inf`)

The main reason I think there's a regression is that when deploying the [nightly version](https://packages.timber.io/vector/nightly/2022-02-03/), 99th percentile response time calculated from buckets get wrong.

Here is the "same" graphed buckets with our actual Vector version (`0.19.0`)

![vector_memory-leak_7](https://user-images.githubusercontent.com/3073431/152842026-b5a32a55-789d-4565-96f8-9262cf91b2a8.png)

The upper buckets stay close each others, which is "normal" because they are far from the average values.

![vector_memory-leak_4](https://user-images.githubusercontent.com/3073431/152843273-fc32cbc6-6f7a-458d-a991-1b69989bcaf3.png)

Here the upper buckets seem to move away each others, which did not correspond to the distribution of the values received.

**Comment by jszwedko** [comment]
Thanks @Zelpher . I was able to reproduce different bucket calculations with this configuration:

```toml
[sources.source0]
type = "stdin"

[sources.source0.decoding]
codec = "json"

[sources.source0.framing]
method = "newline_delimited"

[transforms.transform0]
inputs = ["source0"]
type = "log_to_metric"

[[transforms.transform0.metrics]]
field = "bytes"
name = "requests_size"
type = "histogram"

[sinks.prometheus]
inputs = ["transform0"]
address = "0.0.0.0:9598"
buckets = [1000,5000,10000,20000,30000,40000]
flush_period_secs = 60
quantiles = [0.5, 0.75, 0.9, 0.95, 0.99]
type = "prometheus"
```

And this input file: 
[input.json.gz](https://github.com/vectordotdev/vector/files/8017825/input.json.gz)

I ran it like:

```
cat /tmp/input.json - | vector --config /tmp/tmp.toml
```

(the `cat -` part is just to keep stdin open so Vector doesn't shutdown).

I then `curl localhost:9598/metrics`.

With 0.19.1 I see:

```
requests_size_bucket{le="1000"} 3332 1644258353538
requests_size_bucket{le="5000"} 16620 1644258353538
requests_size_bucket{le="10000"} 33375 1644258353538
requests_size_bucket{le="20000"} 66597 1644258353538
requests_size_bucket{le="30000"} 100000 1644258353538
requests_size_bucket{le="40000"} 100000 1644258353538
requests_size_bucket{le="+Inf"} 100000 1644258353538
requests_size_sum 1501449791 1644258353538
requests_size_count 100000 1644258353538
```

With master (at 02bdaf0c0) I see:

```
requests_size_bucket{le="1000"} 3332 1644258282216
requests_size_bucket{le="5000"} 19952 1644258282216
requests_size_bucket{le="10000"} 53327 1644258282216
requests_size_bucket{le="20000"} 119924 1644258282216
requests_size_bucket{le="30000"} 219924 1644258282216
requests_size_bucket{le="40000"} 319924 1644258282216
requests_size_bucket{le="+Inf"} 100000 1644258282216
requests_size_sum 1501449791 1644258282216
requests_size_count 100000 1644258282216
```

In particular the new `+Inf` value seems not right, but we should also check that the other values are correct.

We'll dig into this more.
