### ISSUE TITLE
`encoding.only_fields` regressed on `elasticsearch` sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11196]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.1 (x86_64-apple-darwin 3cf70cf 2022-01-25)
```

### Vector Configuration File

```toml
[sources.in]
type = "stdin"

[sinks.tenant_log_es]
 type = "elasticsearch" # required
  inputs = ["parse_tenant_logs"] # required
  endpoint = "xxxxxxxxx" # required
  mode = "bulk"
  compression = "none"
  bulk.index = "sgrid-tenant-%F"
  encoding.only_fields = ["audit_file","consumed_capacity_gb","contracted_capacity_gb","tenant_id","tenant_name","timestamp","total_objectCount"]
```

### Debug Output

```
2022-02-04T18:14:24.868926Z ERROR vector::cli: Configuration error. error=invalid type: string "audit_file", expected a sequence for key `sinks.tenant_log_es` at line 4 column 1
```

### Expected Behavior

Starts

### Actual Behavior

Fails to start

### Additional Context

This last worked before 0.18. It appears to be due to 8f3e63a816 which includes changes from 676b42132b. It likely affects other rewritten sinks using `EncodingConfigFixed`.
