### ISSUE TITLE
log_to_metric error: invalid type: map, expected a sequence.

### ISSUE THREAD

**Issue by base698** [vectordotdev/vector#11256]
Using the example here: https://vector.dev/docs/reference/configuration/transforms/log_to_metric/#metrics the configuration doesn't load.  

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.1 (x86_64-unknown-linux-gnu 3cf70cf 2022-01-25)

```

### Vector Configuration File

From the docs:

```toml
[transforms.my_transform_id]
type = "log_to_metric"
inputs = [ "my-source-or-transform-id" ]

  [transforms.my_transform_id.metrics]
  field = "duration"
  kind = "incremental"
  name = "duration_total"
  namespace = "service"
  type = "counter"

    [transforms.my_transform_id.metrics.tags]
    host = "${HOSTNAME}"
    region = "us-east-1"
    status = "{{status}}"
```

### Expected Behavior

Configuration loads with example.

### Actual Behavior
```
2022-02-08T16:21:39.440088Z ERROR vector::cli: Configuration error. error=invalid type: map, expected a sequence for key `transforms.my_metric_id` at line 80 column 1
```
