### ISSUE TITLE
Source :: splunk_hec not accepting splunk logs

### ISSUE THREAD

**Issue by atbagan** [vectordotdev/vector#11292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.19.1
```

### Vector Configuration File

```toml
live infra test setup
[sources.splunk_hec]
  type = "splunk_hec"
  address = "0.0.0.0:8088"
  store_hec_token = true

[sinks.hec]
  inputs = ["splunk_hec"]
  type = "splunk_hec_logs"
  healthcheck = true
  endpoint = "_REDACTED_"
  host_key = ""

  default_token = "_REDACTED_"
  index = "{{index}}"
  encoding.codec = "json"
  compression = "none"


---------------------------
ec2 test setup
[sources.splunk_hec]
type = "splunk_hec"
address = "0.0.0.0:8080"

[sinks.hec]
  inputs = ["splunk_hec"]
  type = "splunk_hec_logs"
  healthcheck = true
  endpoint = "_REDACTED_"
  host_key = ""

  default_token = "_REDACTED_"
  index = "_REDACTED_"
  encoding.codec = "json"
  compression = "none"
```

### Debug Output
Full debug output shows nothing of note.

### Expected Behavior
```Logs sent via Universal Forwarder should have been correctly accepted by the vector source splunk_hec and then routed to our splunk endpoint using splunk_hec_logs sink.```

### Actual Behavior
```Vector source splunk_hec seems to not be properly accepting traffic from a Splunk UF```

### Additional Context
Full Context, and the scenarios tested:
Our actual live infrastructure for our obs pipeline is setup in AWS. Running in a ecs cluster on fargate.  The initial situation that made me aware of this is the following: 

I was sending logs via a Splunk Universal Forwarder (UF) through an application load balancer(ALB) that sits in front of the before mentioned infrastructure.  I know the traffic was correctly hitting the ALB from the metrics on the load balancer.  I kept receiving 4xx count increases so I checked with a curl and received a 404 error when trying to curl the ALB dns on the port that vector was listening on for the splunk source. In my case I bound it to 8088.  

To expand on testing I installed both vector and a UF on an ec2 instance. I setup vector with the splunk_hec source bound to localhost:8080 with its sink being our splunk hec endpoint directly (which I know works when I send logs from vector using other sources, i.e. socket).  I setup the UF to send `httpout` to `localhost:8080` and was met with the same results as in my live infrastructure.  Nothing picked up via vector, and no errors.  vector top showed N/A for all sources/sinks.  

To test once again I decided to just send a singular log via cURL to localhost:8080 where vector was listening with the splunk_hec source.  here is the output from that 

```
bout to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8080
> Accept: */*
> Authorization: Splunk _REDACTED_
> Content-Length: 78
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 78 out of 78 bytes
< HTTP/1.1 404 Not Found
< content-length: 0
< date: Thu, 10 Feb 2022 00:22:37 GMT
<
* Connection #0 to host 127.0.0.1 left intact
* 
```

The version of UF's used today were `8.1` and `8.2.4` I can try a pre 8 version tomorrow.

### Note
If you need more information I can provide whatever you need. 
Thanks,
AB
