### ISSUE TITLE
unit tests panic if consuming from non-existent input

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)
```

### Vector Configuration File

```yaml
sources:
  syslog:
    type: socket
    mode: tcp
    address: 0.0.0.0:9999

transforms:
  parse-syslog:
    type: remap
    inputs:
      - syslog
    drop_on_error: true
    source: |-
      host = string!(.host)
      message = string!(.message)
      ., err = parse_syslog(message)
      if err != null {
        log("invalid syslog message from <" + host + ">: " + message, level: "warn")
        abort
      }
      .host = host

sinks:
  console:
    type: console
    inputs:
      - parse-syslog
    encoding: json

tests:
  - name: crash
    inputs:
      - insert_at: parse-syslog
        type: log
        log_fields:
          host: test
          message: >-
            May 31 10:01:02 app LOG-MESSAGE
    outputs:
      - extract_from: parse-ssyslog  # typo in purpose!
        conditions:
          - type: vrl
            source: |-
              assert!(1 == 1)
```

### Debug Output

```
Running tests
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/config/mod.rs:648:65
stack backtrace:
   0:        0x1099e3206 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c059b532d34bdd
   1:        0x1090e63eb - core::fmt::write::hefb311138778afb5
   2:        0x1099e1d4a - std::io::Write::write_fmt::h0e0ed87b18ae870c
   3:        0x1099e2538 - std::panicking::default_hook::{{closure}}::h43f0e51e5825bd5b
   4:        0x1099e198f - std::panicking::rust_panic_with_hook::h0db3c4ba5fb4dc12
   5:        0x109a1728a - std::panicking::begin_panic_handler::{{closure}}::hc6d8c92efeef5a19
   6:        0x109a17229 - std::sys_common::backtrace::__rust_end_short_backtrace::h7ffb59e898e02a83
   7:        0x109a171e5 - _rust_begin_unwind
   8:        0x10bfae43f - core::panicking::panic_fmt::h7d73f67464d78916
   9:        0x10bfae567 - core::panicking::panic::h9721d5a8c5d33ad7
  10:        0x10b23d862 - vector::config::TestDefinition<alloc::string::String>::resolve_outputs::he6bb174a5e5ed961
  11:        0x10b628cd2 - vector::config::unit_test::build_unit_tests::{{closure}}::h5b4ed336422a10d4
  12:        0x10b5fcf48 - vector::app::Application::prepare_from_opts::{{closure}}::heb79e7d3c4f1467c
  13:        0x10b5f2e79 - vector::app::Application::prepare_from_opts::h6d58f6ce126bcfb6
  14:        0x108d30066 - vector::main::h9ae6803fb2955449
  15:        0x108d30006 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbaf3b8396009ee17
  16:        0x108d31da9 - _main
```

Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.

### Expected Behavior

Vector runs the tests.

### Actual Behavior

Vector panics.

### Additional Context

This worked in v0.19

**Comment by 001wwang** [comment]
Hi @hhromic, thanks for raising this, could you elaborate on issues you're seeing with the `route` transform with outputs not being recognized by the testing framework? An example config there would be great.

In general though, this is an interesting scenario I hadn't considered. It seems like (in `v0.19.3` at least) these examples used to pass. However, I'm not sure if that behavior is actually desirable given that the `extract_from`/`not_outputs_from` targets don't exist. I can see an accidental typo leading to a test passing without actually testing anything. Panicking here isn't ideal either, so I can see us adding informative errors instead.

**Comment by hhromic** [comment]
@001wwang sorry for the late reply, had to leave work earlier yesterday.
I investigated more and it turns out the `route` transform had nothing to do with one of the other crashes I was seeing.

Turns out the additional crash is being triggered by using wildcards `*` together with `no_outputs_from`. MRE:
```yaml
sources:
  logs:
    type: demo_logs
    format: syslog

transforms:
  xform-a:
    type: remap
    inputs:
      - logs
    source: assert!(1 == 1)

sinks:
  console:
    type: console
    inputs:
      - 'xform-*'
    encoding: json

tests:
  - name: crash
    inputs:
      - insert_at: xform-a
        type: log
        log_fields:
          message: Test message
    no_outputs_from:
      - 'xform-*'  # wildcard here causes Vector to crash
```

The crash backtrace is actually a bit different than the other crashes I reported:
```
Running tests
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/config/mod.rs:655:41
stack backtrace:
   0:     0x55b0473518fc - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b0473518fc - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b0473518fc - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b0473518fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b0473add0c - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x55b047341b45 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x55b0473549a0 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b0473549a0 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b0473549a0 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x55b047354555 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x55b047355194 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:     0x55b047354c42 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:500:13
  12:     0x55b047351da4 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55b047354bd9 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:     0x55b042aa2c31 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:     0x55b042aa2b7d - core::panicking::panic::h86fc01e270142a61
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
  16:     0x55b0440b193d - vector::config::TestDefinition<alloc::string::String>::resolve_outputs::hf56b50e0fb804516
  17:     0x55b044099dc1 - vector::config::unit_test::build_unit_tests::{{closure}}::h05dbcd2ae2a221c7
  18:     0x55b04415bf47 - vector::app::Application::prepare_from_opts::{{closure}}::hdb58741660fd0c76
  19:     0x55b044158c1e - vector::app::Application::prepare_from_opts::hbcf16fdeebe0a6d6
  20:     0x55b044157c90 - vector::app::Application::prepare::hdf68ef7d713020c9
  21:     0x55b042aa7d07 - vector::main::hf08a7d578da733ae
  22:     0x55b042aa7cb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h18b6ceb308431a3f
  23:     0x55b042aa7cc9 - std::rt::lang_start::{{closure}}::h6ead1d250160df82
  24:     0x55b0473514fb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7e688d7cdfeb7e00
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  25:     0x55b0473514fb - std::panicking::try::do_call::h4be824d2350b44c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  26:     0x55b0473514fb - std::panicking::try::h0a6fc7affbe5088d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  27:     0x55b0473514fb - std::panic::catch_unwind::h22c320f732ec805e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  28:     0x55b0473514fb - std::rt::lang_start_internal::{{closure}}::hd38309c108fe679d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  29:     0x55b0473514fb - std::panicking::try::do_call::h8fcaf501f097a28e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  30:     0x55b0473514fb - std::panicking::try::h20e906825f98acc1
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  31:     0x55b0473514fb - std::panic::catch_unwind::h8c5234dc632124ef
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  32:     0x55b0473514fb - std::rt::lang_start_internal::hc4dd8cd3ec4518c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  33:     0x55b042aa7da2 - main
  34:     0x7fc47e16a09b - __libc_start_main
  35:     0x55b042aa7bba - <unknown>
  36:                0x0 - <unknown>
```

I saw you alraady fixed the crashes for the other cases, nice! I wonder if your fix also addresses this other case?
Let me know if you need further debugging help.
