### ISSUE TITLE
`prometheus_scrape` source: add configuration for query parameters

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#11358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
vector 0.20.0 (x86_64-unknown-linux-gnu 2a706a3 2022-02-11)
```

### Use-cases

Regular Prometheus scrape jobs [can be configured](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) to send HTTP query parameters during the scrape request:
```
# Optional HTTP URL parameters.
params:
  [ <string>: [<string>, ...] ]
```

This functionality is particularly useful for the following use-cases:
1. For exporters such as the [Blackbox Exporter](https://github.com/prometheus/blackbox_exporter), where query parameters are used to [configure the underlying probe](https://github.com/prometheus/blackbox_exporter#prometheus-configuration).
2.  For Prometheus [Federation](https://prometheus.io/docs/prometheus/latest/federation/), where the query parameters are used for [configuring the data series to federate](https://prometheus.io/docs/prometheus/latest/federation/#configuring-federation) from an upstream Prometheus server being scraped.
3. More in general, any Prometheus exporter that supports HTTP parameters for on-the-fly/per-request configuration.

### Attempted Solutions

The `prometheus_scrape` source in Vector does not support the configuration of query parameters, however the `endpoints` configuration can be used to include query parameters. The major inconvenience being that one must URI-encode the parameters oneself.

For example, for use-case number 2 (federation, the motivating use-case for this issue) described above:
```yaml
sources:
  metrics:
    type: prometheus_scrape
    endpoints:
      - http://some-prometheus:9090/federate?match[]=%7Bjob%3D%22somejob%22%7D
    honor_labels: true
```

While this approach works, as can be seen it is not very readable, hard to maintain and very error prone if you don't use a third-party tool to URI-encode the query parameters. Specially when the query parameters become more complex.

### Proposal

Instead of having to manually URI-encode query parameters, Vector could instead provide support for specifying those query parameters in the same way that Prometheus itself does it:
```yaml
sources:
  metrics:
    type: prometheus_scrape
    endpoints:
      - http://some-prometheus:9090/federate
    query:
      match[]:
        - '{job="somejob"}'
        - '{__name__=~"job:.*"}'
    honor_labels: true
```

Vector then would automatically URI-encode these query parameters before performing the request.

I noticed that the existing [`elasticsearch` sink](https://vector.dev/docs/reference/configuration/sinks/elasticsearch/) already has this functionality implemented via the [`query`](https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#query) configuration, hence why I used this configuration name in the above example.
