### ISSUE TITLE
Elasticsearch sink drops messages if ES rejects execution

### ISSUE THREAD

**Issue by Thor77** [vectordotdev/vector#11359]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.1 (x86_64-unknown-linux-gnu 3cf70cf 2022-01-25)
```

### Vector Configuration File

```toml
[sinks.elasticsearch]
type = "elasticsearch"
inputs = [ "parse_topic",]
endpoint = "xxx"
id_key = "log_message_key"

[sinks.elasticsearch.auth]
strategy = "basic"
user = "xxx"
password = "xxx"

[sinks.elasticsearch.bulk]
index = "xxx-vector-{{ tenant }}_%Y-%m-%d"

[sinks.elasticsearch.request]
retry_attempts = 10
```

### Expected Behavior

Vector should retry the request to Elasticsearch

### Actual Behavior

Vector drops the batch and doesn't retry the reqeust

### Additional Context

Log output:
```
vector[18466]: 2022-02-13T23:40:34.682683Z ERROR sink{component_kind="sink" component_id=elasticsearch component_type=elasticsearch component_name=elasticsearch}:request{request_id=250713}: vector::sinks::util::retries: Not retriable; dropping the request. reason="error type: es_rejected_execution_exception, reason: rejected execution of org.elasticsearch.action.support.replication.TransportWriteAction$1@61890318 on EsThreadPoolExecutor[name = xxx/write, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@7d68775f[Running, pool size = 64, active threads = 64, queued tasks = 1743, completed tasks = 147419112]]"
```
