### ISSUE TITLE
Error decoding fluent message. error=UnexpectedValue

### ISSUE THREAD

**Issue by fpytloun** [vectordotdev/vector#11392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
0.20.0
0.19.3
master from 2022-02-15
```

### Vector Configuration File

```toml
    [sources.in_fluent]
      type = "fluent"
      address = "0.0.0.0:24224"

     # Happens even without these three options
      connection_limit = 2000
      keepalive.time_secs = 30
      receive_buffer_bytes = 1048576

      tls.enabled = true
      tls.verify_certificate = true
      tls.ca_file = "/secrets/identity/client_ca_with_fluent.crt"
      tls.crt_file = "/secrets/identity/server.crt"
      tls.key_file = "/secrets/identity/server.key"
```

### Actual Behavior

[debug.log](https://github.com/vectordotdev/vector/files/8073075/debug.log)
