### ISSUE TITLE
Journald source not sending logs to Splunk Log HEC Sink

### ISSUE THREAD

**Issue by rrs45** [vectordotdev/vector#11397]
**Versions**
Vector: 0.19.0
Splunk: 7.3.6

**Pipeline**
Source: Journald
Transform: Add fields using predifined contants
Sink: Splunk Logs HEC

I am getting this error from Vector 

`2022-02-09T01:02:42.087313Z ERROR sink{component_kind="sink" component_id=splunk_hec_infra component_type=splunk_hec_logs component_name=splunk_hec_infra}:request{request_id=0}: vector::sinks::util::retries: Not retriable; dropping the request. reason="response status: 400 Bad Request"`

I am able to see logs using console sink. I am able to send K8s source logs to the same splunk sink. 

**Config**
```toml
[sources.node_audittest_logs]
              type = "journald"
              current_boot_only = false
              batch_size = 5
              include_matches.SYSLOG_IDENTIFIER = ["audit"]
              journalctl_path = "/usr/bin/journalctl"
              journal_directory = "/var/log/journal"

[transforms.audit_logs_enrich]
              type = "remap"
              inputs = ["node_audittest_logs"]
              source = '''
              .cluster = "xxxx"
              .cluster_group = "xxxx"
              .az = "xxxx"
              .region = "xxxx"
              .project_id = "xxxx"
              .node = get_env_var!("VECTOR_SELF_NODE_NAME")


[sinks.splunk_hec_infra]
              type = "splunk_hec_logs"
              inputs = [ "node_audittest_logs" ]    
              endpoint = "https://xxxx:8088"
              encoding.codec = "json"
              index = "xxxx"
              token = "xxxx"
              source = "vector-obs"
              indexed_fields = ["az", "region", "cluster", "cluster_group"]

#Testing
[sinks.http_test]
              type = "http"
              inputs = [ "node_audittest_logs" ]
              uri = "http://localhost:9094"
              encoding.codec = "json"
```

The http sink is a local server created by running "nc -l 9094". Below are events it sees

```
nc -l 9094
POST / HTTP/1.1
content-type: application/json
user-agent: Vector/0.19.0 (x86_64-unknown-linux-gnu da60b55 2021-12-28)
accept-encoding: identity
host: localhost:9094
content-length: 3857

[{"SYSLOG_FACILITY":"4","SYSLOG_IDENTIFIER":"audit","_AUDIT_FIELD_NEW_ENABLED":"1","_AUDIT_FIELD_NEW_LOG_PASSWD":"0","_AUDIT_FIELD_OLD_ENABLED":"0","_AUDIT_FIELD_OLD_LOG_PASSWD":"0","_AUDIT_FIELD_OP":"tty_set","_AUDIT_FIELD_RES":"1","_AUDIT_ID":"232","_AUDIT_LOGINUID":"xxxxx","_AUDIT_SESSION":"4294967295","_AUDIT_TYPE":"1305","_AUDIT_TYPE_NAME":"CONFIG_CHANGE","_BOOT_ID":"xxxxx","_MACHINE_ID":"xxxxx","_PID":"4132496","_SELINUX_CONTEXT":"=unconfined","_SOURCE_REALTIME_TIMESTAMP":"1642181587513000","_TRANSPORT":"audit","_UID":"0","__MONOTONIC_TIMESTAMP":"583214953533","__REALTIME_TIMESTAMP":"1642181587515222","host":"xxxxx","message":"CONFIG_CHANGE pid=4132496 uid=0 auid=4294967295 ses=4294967295 subj==unconfined op=tty_set old-enabled=0 new-enabled=1 old-log_passwd=0 new-log_passwd=0 res=1","source_type":"journald","timestamp":"2022-01-14T17:33:07.513Z"},{"SYSLOG_FACILITY":"4","SYSLOG_IDENTIFIER":"audit","_AUDIT_FIELD_NEW_ENABLED":"0","_AUDIT_FIELD_NEW_LOG_PASSWD":"0","_AUDIT_FIELD_OLD_ENABLED":"1","_AUDIT_FIELD_OLD_LOG_PASSWD":"0","_AUDIT_FIELD_OP":"tty_set","_AUDIT_FIELD_RES":"1","_AUDIT_ID":"233","_AUDIT_LOGINUID":"xxxx","_AUDIT_SESSION":"4294967295","_AUDIT_TYPE":"1305","_AUDIT_TYPE_NAME":"CONFIG_CHANGE","_BOOT_ID":"xxxxxx","_MACHINE_ID":"xxxxxx","_PID":"4132496","_SELINUX_CONTEXT":"=unconfined","_SOURCE_REALTIME_TIMESTAMP":"1642181587538000","_TRANSPORT":"audit","_UID":"0","__MONOTONIC_TIMESTAMP":"583214977745","__REALTIME_TIMESTAMP":"1642181587539435","host":"xxxxxx","message":"CONFIG_CHANGE pid=4132496 uid=0 auid=4294967295 ses=4294967295 subj==unconfined op=tty_set old-enabled=1 new-enabled=0 old-log_passwd=0 new-log_passwd=0 res=1","source_type":"journald","timestamp":"2022-01-14T17:33:07.538Z"},{"SYSLOG_FACILITY":"4","SYSLOG_IDENTIFIER":"audit","_AUDIT_FIELD_NEW_ENABLED":"1","_AUDIT_FIELD_NEW_LOG_PASSWD":"0","_AUDIT_FIELD_OLD_ENABLED":"0","_AUDIT_FIELD_OLD_LOG_PASSWD":"0","_AUDIT_FIELD_OP":"tty_set","_AUDIT_FIELD_RES":"1","_AUDIT_ID":"234","_AUDIT_LOGINUID":"xxxxxxx","_AUDIT_SESSION":"4294967295","_AUDIT_TYPE":"1305","_AUDIT_TYPE_NAME":"CONFIG_CHANGE","_BOOT_ID":"xxxxx","_MACHINE_ID":"xxxxx","_PID":"1002260","_SELINUX_CONTEXT":"=unconfined","_SOURCE_REALTIME_TIMESTAMP":"1642203187538000","_TRANSPORT":"audit","_UID":"0","__MONOTONIC_TIMESTAMP":"604814976658","__REALTIME_TIMESTAMP":"1642203187538348","host":"xxxxx","message":"CONFIG_CHANGE pid=1002260 uid=0 auid=4294967295 ses=4294967295 subj==unconfined op=tty_set old-enabled=0 new-enabled=1 old-log_passwd=0 new-log_passwd=0 res=1","source_type":"journald","timestamp":"2022-01-14T23:33:07.538Z"},{"SYSLOG_FACILITY":"4","SYSLOG_IDENTIFIER":"audit","_AUDIT_FIELD_NEW_ENABLED":"0","_AUDIT_FIELD_NEW_LOG_PASSWD":"0","_AUDIT_FIELD_OLD_ENABLED":"1","_AUDIT_FIELD_OLD_LOG_PASSWD":"0","_AUDIT_FIELD_OP":"tty_set","_AUDIT_FIELD_RES":"1","_AUDIT_ID":"235","_AUDIT_LOGINUID":"xxxxxx","_AUDIT_SESSION":"4294967295","_AUDIT_TYPE":"1305","_AUDIT_TYPE_NAME":"CONFIG_CHANGE","_BOOT_ID":"3a4f8fa20f7d40c4aced2298f88d91f6","_MACHINE_ID":"1xxxxxx","_PID":"1002260","_SELINUX_CONTEXT":"=unconfined","_SOURCE_REALTIME_TIMESTAMP":"1642203187561000","_TRANSPORT":"audit","_UID":"0","__MONOTONIC_TIMESTAMP":"604814999924","__REALTIME_TIMESTAMP":"1642203187561613","host":"xxxxxxx","message":"CONFIG_CHANGE pid=1002260 uid=0 auid=4294967295 ses=4294967295 subj==unconfined op=tty_set old-enabled=1 new-enabled=0 old-log_passwd=0 new-log_passwd=0 res=1","source_type":"journald","timestamp":"2022-01-14T23:33:07.561Z"}]
```

**Comment by StephenWakely** [comment]
I have been able to intermittently reproduce this error, both with Version 7.3 of Splunk and with the latest version. I can't yet come up with a reliable set of steps as to how to get the error. It needs further investigation.

Possibly a first step could be to report the body of the Http response on an error. There are several different [errors that can return a 400](https://docs.splunk.com/Documentation/Splunk/8.2.4/Data/TroubleshootHTTPEventCollector#Possible_error_codes). It could be enlightening to discover which one is being produced here.

**Comment by StephenWakely** [comment]
Repro steps.

1. Run splunk in docker with: (change 7.3.6 to latest to test latest splunk)
```
 docker run -d -p 8000:8000 -p 8088:8088 -p 8089:8089 -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=norknork" --name splunk splunk/splunk:7.3.6
```

2. In the browser go to `http:localhost:8000`. Sign in with `admin`, password `norknork`
3. Go to menu `settings` -> `data inputs`. 
4. Choose `+ Add new` for `HTTP Event Collector`.
5. Give it a name of `Noog`. Sometimes choose `Enable indexer acknowledgement`, sometimes don't. Hit Next.
6. Sometimes `add all` for Select Allowed Indexes. Sometimes don't. (It is possible that the choices here are what can cause the problem - it doesn't seem to make a difference, but it's the only thing I can think of that is sometimes different between attempts.)
7. Review, then Sumbit. Copy the value in the `Token Value` field.
8. Go to menu `settings` -> `data inputs` again. Choose the  `HTTP Event Collecter` to list all the collectors. Hit `Global Settings`. Untick `Enable SSL` and save.
9. Create this config:

```toml
[sources.journald]
type = "journald"
batch_size = 1
current_boot_only = true

[sinks.splunk]
type = "splunk_hec_logs"
inputs = ["journald"]
endpoint = "http://localhost:8088"
encoding.codec = "json"
default_token = "<token>"
index = "main"
indexed_fields = ["az", "region", "cluster", "cluster_group"]
```

Paste the token you copied previously into the `default_token` field.

10. Run Vector with this config.
11. In another terminal run `systemd-cat`.  Type random stuff to send stuff to the journald logs.
12. At this point you will have either recieved a 300 error message to confirm the error or not. If you havent you can go to `http://localhost:8000/en-GB/app/launcher/search?q=search%20source%3D%22http%3ANoog%22&earliest=0&latest=&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&sid=1645573273.14` to search the entries that Vector has just successfully placed into Splunk. (You may need to replace the locale in that url with your own if you are not GB...)
