### ISSUE TITLE
[sources] add source id to emitted events

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#11544]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We need to identify from which configured source an event comes from for labelling and/or routing.
In our main use case, we have two socket sources configured on different listening ports and we need to add a label-field indicating from which port the event came from. This can extend to more than two in some other use cases.

### Attempted Solutions

At the moment, Vector does not provide any field to identify the source from which an event comes from. It only provides a `source_type` source-related field that is not useful. For example:
```json
{"host":"172.17.0.1","message":"hello world","source_type":"socket","timestamp":"2022-02-23T22:39:46.334288400Z"}
```

However, we can add `remap` transforms wired to each source to label the events and then merge. For example:
```yaml
sources:
  socket-8080:
    type: socket
    mode: tcp
    address: 0.0.0.0:8080
  socket-8081:
    type: socket
    mode: tcp
    address: 0.0.0.0:8081

transforms:
  label-8080:
    type: remap
    inputs:
      - socket-8080
    source: '.label = "FROM-8080"'
  label-8081:
    type: remap
    inputs:
      - socket-8081
    source: '.label = "FROM-8081"'

sinks:
  console:
    type: console
    inputs:
      - label-*
    encoding: json
```

Which produces the following output when sending sample data to each port:
```json
{"host":"172.17.0.1","label":"FROM-8080","message":"hello world","source_type":"socket","timestamp":"2022-02-23T22:47:03.000811600Z"}
{"host":"172.17.0.1","label":"FROM-8081","message":"hello world","source_type":"socket","timestamp":"2022-02-23T22:47:03.935660200Z"}
```

While this approach works, it has two drawbacks:
1. It needs a rather dummy transform for each source, i.e. lot of boiler-plate.
2. It degrades performance. In our tests we noticed a drop from 80K EPS to 76K EPS just by doing this labelling.

### Proposal

Instead of the approach described above, we think that the simplest solution would be to add a new `source_id` field to the event, similar to the existing `source_type` field, containing the id of the source that emitted the event. For example:
```json
{"host":"172.17.0.1","message":"hello world","source_id":"socket-8080","source_type":"socket","timestamp":"2022-02-23T22:47:03.000811600Z"}
{"host":"172.17.0.1","message":"hello world","source_id":"socket-8081","source_type":"socket","timestamp":"2022-02-23T22:47:03.935660200Z"}
```

This would make trivial to assign any labels in a single remapping transform together with other remappings necessary.

### Version

vector 0.20.0 (x86_64-unknown-linux-gnu 2a706a3 2022-02-11)

**Comment by jszwedko** [comment]
👍 that is a neat idea. I think, until we have a better situation for event metadata, that we'd want to introduce another [schema field](https://vector.dev/docs/reference/configuration/global-options/#log_schema) for this. We'd likely want to also make it opt-in so users aren't surprised by the new field when sending to sinks that have strict schemas.

**Comment by jszwedko** [comment]
As a separate issue, that we are working on aspects of, there really shouldn't have been such a performance regression adding the `remap` transform there.

**Comment by hhromic** [comment]
> 👍 that is a neat idea. I think, until we have a better situation for event metadata, that we'd want to introduce another [schema field](https://vector.dev/docs/reference/configuration/global-options/#log_schema) for this. We'd likely want to also make it opt-in so users aren't surprised by the new field when sending to sinks that have strict schemas.

That sounds like a good approach!

> As a separate issue, that we are working on aspects of, there really shouldn't have been such a performance regression adding the `remap` transform there.

This is how I tested this. First, I created some random data for testing:
```
cat /dev/urandom | tr -dc 'a-z A-Z' | tr ' ' '\n' | head -n 5000000 > data.test
```

Then, the **baseline** configuration is this:
```yaml
api:
  enabled: true

sources:
  logs:
    type: stdin

sinks:
  blackhole:
    type: blackhole
    inputs:
      - logs
```

Which I run like this with the testing data:
```
while true; do cat data.test; done | docker run --name vector --rm -i -v $PWD/vector.yaml:/vector.yaml:ro timberio/vector:0.20.0-distroless-libc -c /vector.yaml
```

On my computer, `vector top` reports an average of 88-90K EPS for the `blackhole` sink.

Now, the **labelling** configuration using `remap` is this:
```yaml
api:
  enabled: true

sources:
  logs:
    type: stdin

transforms:
  label:
    type: remap
    inputs:
      - logs
    source: '.label = "SOME"'

sinks:
  blackhole:
    type: blackhole
    inputs:
      - label
```
Which on the same computer, `vector top` reports an average of 82-83K EPS for the `blackhole` sink.

**Comment by jszwedko** [comment]
Ah, yes, sorry, I should have made it clearer in my comment that there is definitely known overhead in adding a `remap` transform; it is just larger than we would like for it to be. We are making improvements there though. For example rewriting [VRL's interpreter as a VM](https://github.com/vectordotdev/vector/blob/master/rfcs/2021-11-12-9811-vrl-vm.md).

That particular case could likely also be aided by removing one clone that happens due to VRL being an expression-based language so that `.label = "SOME"` itself returns a cloned "SOME" that in this case is being discarded. @JeanMertz do you know if we have an issue tracking that? I can't find anything.

Thanks for the perf reproduction case though 😄

**Comment by hhromic** [comment]
> Ah, yes, sorry, I should have made it clearer in my comment that there is definitely known overhead in adding a `remap` transform; it is just larger than we would like for it to be. We are making improvements there though. For example rewriting [VRL's interpreter as a VM](https://github.com/vectordotdev/vector/blob/master/rfcs/2021-11-12-9811-vrl-vm.md).

Ah yes, I have been looking forward to see that released!

Btw, I just remembered that there is an `add_fields` non-VRL transform that can be used as well:
```yaml
sources:
  socket-8080:
    type: socket
    mode: tcp
    address: 0.0.0.0:8080
  socket-8081:
    type: socket
    mode: tcp
    address: 0.0.0.0:8081

transforms:
  label-8080:
    type: add_fields
    inputs:
      - socket-8080
    fields:
      label: FROM-8080
  label-8081:
    type: add_fields
    inputs:
      - socket-8081
    fields:
      label: FROM-8081

sinks:
  console:
    type: console
    inputs:
      - label-*
    encoding: json
```

While the boilerplate code is pretty much the same, at least performance doesn't degrade that much as with `remap` :)

I just tested this using the configuration in my last comment and got 86-88K EPS using `add_labels`.
I do know that those transforms are getting deprecated and hence they are not documented anymore.

But for now I guess is good enough for us until the feature requested here manages to be implemented.

**Comment by hhromic** [comment]
After developing our use-case more, I actually think that a better feature request would be the ability to add a customisable "label" to each event emitted by a source. So instead of a `source_id` field, a configurable `source_label` one for example. It could be provided at the source configuration like this:
```yaml
sources:
  udp-socket:
    type: socket
    mode: udp
    address: 0.0.0.0:1514
    label: DATACENTER-1
  tcp-socket:
    type: socket
    mode: tcp
    address: 0.0.0.0:8080
    label: DATACENTER-2
```
If the `label` config is not provided (could be the default), then no `source_label` field is added and becomes opt-in.

The reason for this customisability is that we don't want to name our sources after the labels, which are placed inside the event to the next processing component instead.

**Comment by jszwedko** [comment]
👍 I wonder if we could just generalize this further and let you attach a VRL program to sources. It'd really just be syntax sugar over chaining a `remap` transform afterwards though. Granted, as you noted, we still need to improve the performance of `remap` over native code (it'll never be quite as fast, but can be closer).

**Comment by hhromic** [comment]
Hehe I wouldn't "over do it" either :)
As you say, it would be syntax sugar and I don't think simple things like labelling the source warrants a remap interpreter.
I would keep it simple as sources should be as performant as possible imho :)

**Comment by smitsr72** [comment]
The labeling solution would help my use case too. 
Another option would be to always include the metadata that is already collected when aborted/asserted. If we could opt in on the metadata to be always put in the message schema.

```
    "metadata": {
        "dropped": {
            "component_id": "transform_name",
            "component_kind": "transform",
            "component_type": "remap",
            "message": "function call error for \"assert\" at (29:86): custom assert message",
            "reason": "error"
        }
```

**Comment by eocron** [comment]
Any progress on this? I'm currently trying to add common metric `log_last_timestamp{source="$source$"}` to make further alerting on failed synchronizations between file events and destination system events (elastic).

**Comment by jszwedko** [comment]
Nothing yet. The workaround is pretty straight-forward though: add a `remap` transform after each source you want to add a label.

**Comment by eocron** [comment]
I have a * mask on all sources, so remap will not work for me.

**Comment by johnnybubonic** [comment]
@eocron it's unfortunate because it means you essentially have to duplicate every. single. source, but you could use a remap transform with a predictable prefix/pattern component ID.

Certainly not ideal, as the earlier suggestions of adding metadata directly to each source automatically is **significantly** preferred (I have a need for this as well, and would MUCH prefer avoiding the impractical, inelegant, and pipeline-complicating workaround of remapping simply to add some sort of source identifier), but this could be done via the following as a workaround for your use-case:

`/etc/vector/sources/a.yml`:
```yaml
type: collector_foo
# ...
```

`/etc/vector/sources/b.yml`:
```yaml
type: collector_bar
# ...
```

`/etc/vector/transforms/all_label_a.yml`:
```yaml
type: remap
inputs:
  - a
source: '.label = "a"'
```

`/etc/vector/transforms/all_label_b.yml`:
```yaml
type: remap
inputs:
  - b
source: '.label = "b"'
```

`/etc/vector/sinks/everything.yml`:
```yaml
type: sender_quux
inputs:
  # This is the important bit.
  - "all_label_*"
# ...
```
