### ISSUE TITLE
Events discarded while buffer not full

### ISSUE THREAD

**Issue by Stuzerain** [vectordotdev/vector#11557]
## Problem
Many (up to 1/5+) messages are being discarded, according to the `buffer_discarded_events_total` metric. Comparison between messages leaving source and in sink confirms this. 

No metrics indicate that the buffer is full, or filling at all. `buffer_events` always shows 0, and a more robust way to calculate buffer size: `buffer_sent_events_total - buffer_received_events_total` also always shows a value of 0. 

## Config
The source is a raw TCP socket. The source also notably produces a lot of messages, easily 3000+ per second. The sum of all `vector_utilization` metrics virtually never exceeds a value of 0.100, and the utilization for this specific sink never exceeds a value of 0.015. 

Because of the way incoming messages spike from the source, there has been a suggestion that the buffer _is_ filling, but that it fills and drains too fast for metrics to capture. The `internal_metrics` source uses the default 2s scrape resolution, and prometheus is using a 15s scrape resolution. 

```
[sources.appsrc]
    type = "socket"
    address = "0.0.0.0:19001"
    mode = "tcp"
    decoding.codec = "json"

[transforms.basics]
    type = "remap"
    inputs = ["appsrc"]
    source = '''
        .service.type = "clara"
        .service.environment = del(.serviceEnv)
        .service.name = del(.serviceName)
        .host.hostname = get_hostname!()
        .log.level = del(.level)
        del(.level_value)
        .java.thread = del(.thread_name)
        .java.class = del(.logger_name)
        .tracing.discoveryId = del(.discoveryId)
        .tracing.merlinEventId = del(.merlinEventId)
        .tracing.notificationType = del(.notificationType)
        .metrics.processingTime = del(.processingTime)
        .log.type = "service"
        del(.context)
        del(.source_type)
    '''
    
[sinks.daas]
    type = "elasticsearch"
    inputs = ["basics"]
    endpoint = "${ELK_URL}"
    bulk.index = "${INDEX_NAME}"
    bulk.action = "create"

    auth.strategy = "basic"
    auth.user = "${ELK_USERNAME}"
    auth.password = "${ELK_PASSWORD}"

    buffer.type = "memory"
    buffer.max_events = 15000
    buffer.when_full = "drop_newest"

    tls.verify_certificate = false
    tls.verify_hostname = false

[sources.vector_metrics]
    type = "internal_metrics"

[sinks.prometheus]
    type = "prometheus_exporter"
    inputs = ["vector_metrics"]
    address = "0.0.0.0:1953"
```

## Version
0.20.0

## Examples
![Screen Shot 2022-02-24 at 11 22 59 AM](https://user-images.githubusercontent.com/62074382/155566412-faec79d3-a30e-4747-ab9e-d7915df94b6c.png)
![Screen Shot 2022-02-24 at 11 21 56 AM](https://user-images.githubusercontent.com/62074382/155566414-08965918-f73e-4603-9c2a-cd9a48d1cdac.png)
![Screen Shot 2022-02-24 at 11 20 37 AM](https://user-images.githubusercontent.com/62074382/155566415-8e3f78b8-2d62-4574-a217-14e68a8f8bee.png)

**Comment by jszwedko** [comment]
This is pretty strange. It does seem to indicate an issue with the in-memory buffer metrics, but I wasn't able to reproduce it.

**Comment by Stuzerain** [comment]
The service producing all of these messages runs on the same instance as this vector...Would it look like this if vector just didn't have enough memory available for its buffer to work properly? I'm a little skeptical that it would never have any memory available to it, though.

**Comment by jszwedko** [comment]
@Stuzerain I tried to reproduce this today, but still wasn't able to. In my experiment the buffer was always full.  If there was insufficient memory, I believe Vector would simply try to consume it all and be OOM-killed so that behavior doesn't seem to match what you are seeing.

The config I was trying:

```toml
[sources.stdin]
type = "stdin"

[sinks.http]
inputs = ["stdin"]
type = "http"
uri = "http://127.0.0.01:9000/post"
encoding.codec = "json"

[sinks.http.buffer]
type = "memory"
max_events = 15000
when_full = "drop_newest"

[sources.metrics]
scrape_interval_secs = 2
type = "internal_metrics"

[sinks.prometheus]
type = "prometheus"
inputs = ["metrics"]
address = "0.0.0.0:9598"
```

I'm curious if v0.19.3 works for you?

**Comment by jszwedko** [comment]
Hi @Stuzerain !

I was able to reproduce this when I tried again today. We are working on a fix for it.

**Comment by jszwedko** [comment]
Writing up the reproduction steps here:

Start up Elasticsearch:

```
docker run --detach --name elasticsearch  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:8.1.0
```

Generate password:

```
docker exec -it elasticsearch /bin/sh
bin/elasticsearch-reset-password -u elastic
```

Copy password generated and export as `ELASTICSEARCH_PASSWORD`:

```
export ELASTICSEARCH_PASSWORD=...
```

Run Vector with the following config (export `DD_API_KEY` to get metrics in Datadog, otherwise use Prometheus locally):

```toml
[sources.stdin]
type = "stdin"

[transforms.basics]
    type = "remap"
    inputs = ["stdin"]
    source = '''
        .service.type = "clara"
        .service.environment = del(.serviceEnv)
        .service.name = del(.serviceName)
        # .host.hostname = get_hostname!()
        .log.level = del(.level)
        del(.level_value)
        .java.thread = del(.thread_name)
        .java.class = del(.logger_name)
        .tracing.discoveryId = del(.discoveryId)
        .tracing.merlinEventId = del(.merlinEventId)
        .tracing.notificationType = del(.notificationType)
        .metrics.processingTime = del(.processingTime)
        .log.type = "service"
        del(.context)
        del(.source_type)
    '''

[sinks.daas]
	type = "elasticsearch"
	inputs = ["basics"]
	endpoint = "https://localhost:9200"
	bulk.index = "foo"
	bulk.action = "create"

	suppress_type_name = true

	auth.strategy = "basic"
	auth.user = "elastic"
	auth.password = "${ELASTICSEARCH_PASSWORD}"

	buffer.type = "memory"
	buffer.max_events = 1500000
	buffer.when_full = "drop_newest"

	tls.verify_certificate = false
	tls.verify_hostname = false


[sources.metrics]
scrape_interval_secs = 2
type = "internal_metrics"
tags.host_key = "host"

[sinks.prometheus]
type = "prometheus"
inputs = ["metrics"]
address = "0.0.0.0:9598"

[sinks.datadog]
type = "datadog_metrics"
inputs = ["metrics"]
api_key = "${DD_API_KEY}"
default_namespace = "vector"
```

```
flog -l | vector --config /tmp/tmp.toml
```
