### ISSUE TITLE
flaky reported raw_bytes_collected from blackhole sink

### ISSUE THREAD

**Issue by anas-aso** [vectordotdev/vector#11582]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Blackhole sink reports flaky values for the raw collected bytes.
If I run vector with this config
```yaml
data_dir: "."

sources:
  demo_logs:
    count: 1000
    decoding:
      codec: json
    format: shuffle
    interval: 0.0
    lines:
    - '{"message":"log line"}'
    type: demo_logs

sinks:
  blackhole:
    inputs:
    - demo_logs
    print_interval_secs: 3600
    rate: 1000000000000
    type: blackhole
```

I get a stable reported value (`raw_bytes_collected=524048`): 
```
2022-02-25T17:20:59.839087Z  INFO vector::sinks::blackhole::sink: Total events collected events=1000 raw_bytes_collected=524048
```

Once I add a transform in the middle, the reported `raw_bytes_collected` becomes flaky (but I noticed that the reported  values are not completely random): 
```yaml
data_dir: "."

sources:
  demo_logs:
    count: 1000
    decoding:
      codec: json
    format: shuffle
    interval: 0.0
    lines:
    - '{"message":"{\"key\":\"val\"}"}'
    type: demo_logs

transforms:
  myTransform:
    inputs:
    - demo_logs
    type: remap
    source: |-
      . = parse_json!(.message)

sinks:
  blackhole:
    inputs:
    - myTransform
    print_interval_secs: 3600
    rate: 1000000000000
    type: blackhole
```
Running the config above in a while true loop: `while true; do vector --config cfg.yaml 2>&1 | tail -1 && sleep 1; done`
<img width="1792" alt="Screenshot 2022-02-25 at 18 23 34" src="https://user-images.githubusercontent.com/16538065/155759706-fc8545db-0ad8-4596-80e8-e51b41557a42.png">

PS: even if the transform is completely empty, the reported are flaky.

### Configuration

```text
See description above
```

### Version

vector 0.19.2
