### ISSUE TITLE
Unreachable transform error reached

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11649]
### Discussed in https://github.com/vectordotdev/vector/discussions/11646

<div type='discussions-op-text'>

<sup>Originally posted by **satscreate** March  2, 2022</sup>
I am running vector file like this,
` head some.jsonl | vector -c vector.yaml | jq`

Not always my sinks print console output. Only like 1 time or twice it prints the output in linux debian.
I have 3 json objects which is very small & i am sure vector config also works because i am passing same input all the time & prints output sometimes. any help?

**Version:**
`2022-03-02T14:07:38.930885Z  INFO vector: Vector has started. debug="false" version="0.19.0" arch="x86_64" build_id="da60b55 2021-12-28"`

**Error:**
`2022-03-02T14:07:45.815417Z ERROR sink{component_kind="sink" component_id=stdout component_type=console component_name=stdout}: vector::topology: An error occurred that vector couldn't handle.`

Sometimes: when i press ctrl+c
```
2022-03-02T14:16:46.653847Z  INFO vector::shutdown: All sources have finished.
2022-03-02T14:16:46.654136Z  INFO vector: Vector has stopped.
2022-03-02T14:16:51.337853Z  INFO vector: Vector has quit.
thread 'vector-worker' panicked at 'internal error: entered unreachable code: join error or bad poll', src/topology/builder.rs:581:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-03-02T14:16:51.341908Z ERROR transform{component_kind="transform" component_id=parse-failure-log component_type=remap component_name=parse-failure-log}: vector::topology: An error occurred that vector couldn't handle.
```</div>

**Comment by jszwedko** [comment]
Waiting on full Vector config.

**Comment by jszwedko** [comment]
From the user:

vector.yaml

```yaml
api:
  enabled: true
  address: 0.0.0.0:8687
  playground: false

sources:
  stdin:
    type: stdin
    decoding: 
      codec: json

transforms:
  
  parse-some-log:
    type: remap
    inputs:
      - stdin
    drop_on_error: true
    source: |-
      message = string!(.result.message)
      status = string!(.result.status)

  route-some-log-result:
    type: route
    inputs:
      - parse-some-log
    route:
      success-log-status: '.status == "SUCCESS"'
      fail-log-status: '.status == "FAILURE"'

  parse-success-log:
    type: remap
    inputs:
      - route-log-result.success-log-status
    drop_on_error: true
    source: |-
      . = {
        "somestuff": .status
      }

  parse-fail-log:
    type: remap
    inputs:
      - route-log-result.fail-log-status
    drop_on_error: true
    source: |-
      . = {
        "somestuff": .status
      }

  remap-fields:
    type: remap
    inputs:
      - parse-success-log
      - parse-fail-log
    drop_on_error: true
    source: |-
      .somestuff = .somestuff

sinks:
  stdout:
    type: console
    inputs:
      - remap-fields
    target: stdout
    encoding:
      codec: ndjson
      only_fields:
       - somestuff
```

some.jsonl:

```json
{"source": "first","result": {"status": "SUCCESS", "message": "Success..."}}
{"source": "second","result": {"status": "FAILURE", "message": "Failure..."}}
```
