### ISSUE TITLE
Improve VRL parsing error message for unexpected EOF

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11656]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

With config:

```toml
[sources.source0]
type = "stdin"

[transforms.transform0]
type = "filter"
inputs = [ "source0" ]
condition = """ match(string(.name) ?? "", r'(^(machine|apiserver|cluster:capacity|cluster:container|cluster:cpu|cluster:master|cluster:memory|cluster:nodes|cluster:node|container_cpu|container_fs|container_memory|container_network|kube_node|kube_pod_container|kube_pod|node|pod:container_cpu_usage:sum|pod:container_memory_usage_bytes:sum|pod:container)_.*|kube_resourcequota|ALERTS_FOR_STATE|cluster_version)'"""

[sinks.sink0]
inputs = ["transform0"]
type = "console"
encoding.codec = "json"
```

Vector outputs an "unexpected parse error":

```
error[E202]: syntax error
  ┌─ :1:1
  │
1 │  match(string(.name) ?? "", r'(^(machine|apiserver|cluster:capacity|cluster:container|cluster:cpu|cluster:master|cluster:memory|cluster:nodes|cluster:node|container_cpu|container_fs|container_memory|container_network|kube_node|kube_pod_container|kube_pod|node|pod:container_cpu_usage:sum|pod:container_memory_usage_bytes:sum|pod:container)_.*|kube_resourcequota|ALERTS_FOR_STATE|cluster_version)'
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unexpected error: unexpected parse error
  │
  = see language documentation at https://vrl.dev
```

Due to the lack of a closing `)`.

Seemingly we could do better here with something like `unexpected end-of-input, expected )`.

### References

https://discordapp.com/channels/742820443487993987/746070591097798688/948664679083966474

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)
