### ISSUE TITLE
Output warning for `dedupe` when key is not set

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11654]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

It'd be helpful if the `dedupe` transform output a warning if the field it is deduping on is not set in the event. Otherwise, it can be difficult to understand why the logs aren't deduping correctly.

I tested this with the following config (from the referenced discord link below):

```toml
[sources.source0]
type = "stdin"

[transforms.transform0]
type = "dedupe"
inputs = [ "source0" ]
fields.match = [ "msg" ]

[sinks.sink0]
inputs = ["transform0"]
type = "console"
encoding.codec = "json"
```

And the following input:

```
time="2022-01-31T13:16:37.939863157Z" level=info msg="Starting up"
time="2022-01-31T13:16:37.954569725Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2022-01-31T13:23:19.675005702Z" level=info msg="Configured log driver does not support reads, enabling local file cache for container logs" driver=awslogs
time="2022-01-31T13:24:25.696344115Z" level=info msg="Configured log driver does not support reads, enabling local file cache for container logs"  driver=awslogs
```

The output is simply the first message because the rest are deduped due to not actually having a `msg` key (since the logs are unparsed).

### References

https://discordapp.com/channels/742820443487993987/948586726446759977/948586729063997641

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)
