### ISSUE TITLE
Improve VRL's performance when used as conditions

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11688]
It has been observed that using `route` with VRL conditions causes a significant reduction in performance.

For example, a user had this configuration:

```yaml
api:
  enabled: true
  playground: false

sources:
  socket:
    type: socket
    mode: tcp
    address: 0.0.0.0:8080

transforms:
  partition:
    type: remap
    inputs:
      - socket
    drop_on_error: true
    source: |-
      .partition = to_unix_timestamp(now(), unit: "milliseconds") % 3

sinks:
  blackhole:
    type: blackhole
    inputs:
      - partition
```

And added a `route` transform as so:

```yaml
api:
  enabled: true
  playground: false

sources:
  socket:
    type: socket
    mode: tcp
    address: 0.0.0.0:8080

transforms:
  partition:
    type: remap
    inputs:
      - socket
    drop_on_error: true
    source: |-
      .partition = to_unix_timestamp(now(), unit: "milliseconds") % 3
  route:
    type: route
    inputs:
      - partition
    route:
      blackhole1: .partition == 0
      blackhole2: .partition == 1
      blackhole3: .partition == 2

sinks:
  blackhole:
    type: blackhole
    inputs:
      - route.*
```

Running:

```
$ while true; do cat data.txt; done | pv | socat -u -dd stdin tcp-connect:localhost:8080
```

(The data.txt file has 500K records (newline delimited) with an average of 1400 characters each.)

They saw:

The baseline throughput after running for 30 seconds is : 191MiB/s
The route-added throughtput after running for 30 seconds is : 113MiB/s

When swapping out the VRL conditions for analogous `check_fields` conditions:

```yaml
api:
  enabled: true
  playground: false

sources:
  socket:
    type: socket
    mode: tcp
    address: 0.0.0.0:8080

transforms:
  route:
    type: route
    inputs:
      - partition
    route:
      blackhole1:
        type: check_fields
        "partition.eq": 0
      blackhole2:
        type: check_fields
        "partition.eq": 1
      blackhole3:
        type: check_fields
        "partition.eq": 2

sinks:
  blackhole:
    type: blackhole
    inputs:
      - route.*
```

They did not see this throughput reduction.
