### ISSUE TITLE
An error occurred after the data source was changed to Kafka using the Vector Agent service installed at helm

### ISSUE THREAD

**Issue by king5211** [vectordotdev/vector#11706]
I found a very strange problem and need your help.
Vector installed using helm
`helm install vector vector/vector --namespace vector --create-namespace`
After the installation is complete, change the data source to Kafka, sink to Loki, and configMap as follows:
```
data:
   vector.yaml: |
     data_dir: /vector-data-dir
     api:
       enabled: true
       address: 127.0.0.1:8686
       playground: false
     sources:
       kafka:
         type: kafka
         acknowledgements: null
         bootstrap_servers: kafka-0.kafka-svc.default.svc.cluster.local:9092,kafka-1.kafka-svc.default.svc.cluster.local:9092,kafka-2.kafka-svc.default.svc.cluster.local:9092
         group_id: consumer-group-name-ventor
         topics:
          - ^(kube)-.+
     sinks:
       loki:
         type: loki
         inputs: [kafka]
         endpoint: loki.loki-stack.svc.cluster.local:3100
kind: ConfigMap
metadata:
   annotations:
     meta.helm.sh/release-name: vector
     meta.helm.sh/release-namespace: vector
   labels:
     app.kubernetes.io/component: Agent
     app.kubernetes.io/instance: vector
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/name: vector
     app.kubernetes.io/version: 0.20.0-distroless-libc
     helm.sh/chart: vector-0.6.0
   name: vector
   namespace: vector
```
Vector-0 POD startup failed and error logs are as follows:
```
2022-03-07T02:15:42.131211Z  INFO vector::app: Loading configs. paths=["/etc/vector"]
2022-03-07T02:15:42.133246Z ERROR vector::cli: Configuration error. error=sources.kafka: invalid type: unit value, expected bool or map at line 8 column 9
```
As for the error information, I really can not find the problem point, hope to get your help and solve the problem, thank you very much!

**Comment by king5211** [comment]
I tried to add the two fields of decoding encoding, and the error of "Invalid type: unit value, expected bool or map at line 8 Column 9" disappeared, but a new error content was generated  
```
2022-03-07T05:28:33.259479Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
2022-03-07T05:28:33.259652Z  INFO vector::app: Loading configs. paths=["/etc/vector"]
2022-03-07T05:28:33.285226Z ERROR vector::topology: Configuration error. error=Sink "loki": invalid format
```
configmap.yaml
```
apiVersion: v1
data:
   vector.yaml: |
     api:
       enabled: true
       address: 127.0.0.1:8686
       playground: false
     sources:
       kafka:
         type: "kafka"
         bootstrap_servers: kafka-0.kafka-svc.default.svc.cluster.local:9092,kafka-1.kafka-svc.default.svc.cluster.local:9092,kafka-2.kafka-svc.default.svc.cluster.local:9092
         group_id: consumer-group-name-ventor
         decoding:
             codec: "json"
         topics:
          - ^(kube)-.+
     sinks:
       loki:
         type: "loki"
         inputs: [kafka]
         endpoint: loki.loki-stack.svc.cluster.local:3100
         encoding:
             codec: "json"
         labels:
           forwarder: "vector"
           event: "{{ event_field }}"
kind: ConfigMap
metadata:
   annotations:
     meta.helm.sh/release-name: vector
     meta.helm.sh/release-namespace: vector
   labels:
     app.kubernetes.io/component: Agent
     app.kubernetes.io/instance: vector
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/name: vector
     app.kubernetes.io/version: 0.20.0-distroless-libc
     helm.sh/chart: vector-0.6.0
   name: vector
   namespace: vector
```
