### ISSUE TITLE
Support setting timestamp field value for unit tests

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11753]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

A user wants to test behavior of a `remap` transform on an incoming event with a `.timestamp` field of `timestamp` type, but it isn't possible to set the value of a field to a timestamp in the unit test configuration.

Example config:

```toml
[transforms.fix_timestamp]
type = "remap"
inputs = ["*_to_sink"]
source = """
    if (is_timestamp(.timestamp) && to_unix_timestamp(timestamp!(.timestamp)) < 0 ) {
        log( {
            "detail": "Replaced invalid timestamp with now()",
            "original_message": .
        }, level: "warn")
        .timestamp = now()
    }
"""

[[tests]]
name = "Transforms fail"

[[tests.inputs]]
insert_at = "fix_timestamp"
type = "log"

[tests.inputs.log_fields]
timestamp = # cannot set this to an actual timestamp

[[tests.outputs]]
extract_from = "fix_timestamp"

[[tests.outputs.conditions]]
type = "vrl"
source = '''
assert!(is_timestamp(.timestamp))
assert!(to_float(now()) - 1 < to_float!(.timestamp))
assert!(to_float(now()) + 1 > to_float!(.timestamp))
'''
```

### Attempted Solutions

The user was able to work around this by adding a dummy transform that parses the input into a timestamp and used that dummy transform as an input to the transform they actually want to test.

### Proposal

Allow setting timestamp values as unit test inputs.

This could mean just interpreting a RFC3999 string as a timestamp or requiring additional configuration to indicate that the field should be parsed as a timestamp for input.

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)
