### ISSUE TITLE
Template the `bucket` field for `GCP Cloud Storage` sink

### ISSUE THREAD

**Issue by FlorianGD** [vectordotdev/vector#11867]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We want to select the bucket to write to when using the `GCP Cloud Storage` sink based on the information in the logs. The field is not templated at the moment, so it is not possible.

### Proposal

Allowing this syntax would be very useful to us:

```yaml
gcs:
    type: gcp_cloud_storage
    inputs:
      - my_input
    bucket: "bucket-{{context.project.guid}}"
```

### Version

vector 0.20.0 (x86_64-unknown-linux-gnu 2a706a3 2022-02-11)
