### ISSUE TITLE
Update `pipelines` transform configuration to take an array of pipelines

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#11921]
After working on [a document that demonstrates a Datadog customer's configuration](https://whimsical.com/datadog-logs-customer-DwqsXBgfRrikJeTa5T94d5), I realized the `pipelines` transform configuration was very verbose and difficult to read. For example:

```toml
[transforms.pipelines]
  type = "pipelines"
  inputs = ["schema"]
  order = [
    "golang",
    "ruby"
  ]

[transforms.pipelines.logs.pipelines.golang]
  title = "Golang"
  filter.type = "datadog_search"
  filter.source = "source:go"

[[transforms.pipelines.logs.pipelines.golang.processors]]
  type = "remap"
  source = "..."

[transforms.pipelines.logs.pipelines.ruby]
  title = "Ruby"
  filter.type = "datadog_search"
  filter.source = "source:ruby"

[[transforms.pipelines.logs.pipelines.ruby.processors]]
  type = "remap"
  source = "..."
```

This is mostly due to each pipeline having its own ID. By removing this and using a standard array structure we can eliminate the following:

1. The root-level `order` key
2. The verbose namespacing for each pipeline and processors (i.e., `[[transforms.pipelines.logs.pipelines.<id>]]`).
3. The need to sync both the pipeline ID and its `title` (Datadog Logs does not require IDs for pipelines).

By removing the pipeline ID we end up with something like this:

```toml
[transforms.pipelines]
  type = "pipelines"
  inputs = ["schema"]

[[transforms.pipelines.logs]]
  title = "Golang"
  filter.type = "datadog_search"
  filter.source = "source:go"

[[transforms.pipelines.logs.processors]]
  type = "remap"
  source = "..."

[[transforms.pipelines.logs]]
  title = "Ruby"
  filter.type = "datadog_search"
  filter.source = "source:go"

[[transforms.pipelines.logs.processors]]
  type = "remap"
  source = "..."
```

## Caveats

Pipelines IDs were driven by the requirement to define each pipeline in its own file. This is unnecessary since most of these configurations will be automatically translated. I also think we can define naming strategies array structures that would allow each element to be defined in it's own file.
