### ISSUE TITLE
error when pass user name and password for elastic sinks

### ISSUE THREAD

**Issue by therus000** [vectordotdev/vector#11922]
i try to add elastic sinks but i got and error:
i try this way
```
sinks:
elasticsearch:
        type: elasticsearch
        inputs: [kubernetes_logs]
        endpoint: https://elastic-cluster-es-coordinator.elastic-system.svc.cluster.local:9200
        encoding:
          timestamp_format: rfc3339
        auth.user: "elastic"
        auth.password: "password"
        auth.strategy: basic
        tls.verify_certificate: false
        index: vector-%Y-%m-%d
        metrics: null
        mode: bulk
```
and try this 

```
sinks:
elasticsearch:
        type: elasticsearch
        inputs: [kubernetes_logs]
        endpoint: https://elastic-cluster-es-coordinator.elastic-system.svc.cluster.local:9200
        encoding:
          timestamp_format: rfc3339
        auth
           user: "elastic"
           password: "password"
           strategy: basic
        tls:
             verify_certificate: false
        index: vector-%Y-%m-%d
        metrics: null
        mode: bulk
```

may be someone help with the right pass k8s logs to elastic !!!

**Comment by spencergilbert** [comment]
Hi @therus000 - could you share the error message so I can be sure, but assuming you're using the latest versions of Vector you have deprecated and removed fields in your config: https://vector.dev/highlights/2021-12-28-0-19-0-upgrade-guide/#elasticsearch-sink-deprecated-fields

**Comment by therus000** [comment]
2022-03-21T16:51:56.501081Z INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
2022-03-21T16:51:56.507480Z INFO vector::app: Loading configs. paths=["/etc/vector"]
2022-03-21T16:51:56.549689Z ERROR vector::cli: Configuration error. error=sinks.elasticsearch: unknown field auth.user, expected one of endpoint, doc_type, suppress_type_name, id_key, pipeline, mode, compression, encoding, batch, request, auth, query, aws, tls, bulk, data_stream, metrics at line 31 column 9

**Comment by spencergilbert** [comment]
```yaml
data_dir: /tmp/vector
api:
  enabled: false
sources:
  kubernetes_logs:
    type: kubernetes_logs
sinks:
  elasticsearch:
    type: elasticsearch
    inputs: [kubernetes_logs]
    endpoint: https://elastic-cluster-es-coordinator.elastic-system.svc.cluster.local:9200
    encoding:
      timestamp_format: rfc3339
    auth:
       user: "elastic"
       password: "password"
       strategy: basic
    tls:
       verify_certificate: false
    bulk:
      action: bulk
      index: vector-%Y-%m-%d
```

The above config snippet `validate`s properly for me locally with Vector `0.20.0` - note the `bulk` object and there was a missing `:` in the snippet you shared.

**Comment by therus000** [comment]
error

**Comment by spencergilbert** [comment]
Please confirm the version of Vector you are running

**Comment by therus000** [comment]
image: "timberio/vector:0.20.0-distroless-libc"

**Comment by spencergilbert** [comment]
```yaml
data_dir: /tmp/vector
api:
  enabled: false
sources:
  kubernetes_logs:
    type: kubernetes_logs
sinks:
  elasticsearch:
    type: elasticsearch
    inputs: [kubernetes_logs]
    endpoint: https://elastic-cluster-es-coordinator.elastic-system.svc.cluster.local:9200
    encoding:
      timestamp_format: rfc3339
    auth:
       user: "elastic"
       password: "password"
       strategy: basic
    tls:
       verify_certificate: false
    bulk:
      action: bulk
      index: vector-%Y-%m-%d
```
```bash
☸ minikube (default) in /tmp/vector/11922
❯ vector --version
vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)

☸ minikube (default) in /tmp/vector/11922
❯ vector validate --config-yaml vector.yaml --no-environment
√ Loaded ["vector.yaml"]
------------------------
               Validated
```

Since it works for me locally, can you share the complete configurations you have under `/etc/vector`?
