### ISSUE TITLE
Make Vector aware of available memory

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11942]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We have had discussions floating around this in various issues, but I couldn't find a reference issue for it so creating this one.

Users have had issues in running Vector in memory constrained environments where it'd be better for Vector to apply back-pressure than increase memory usage when it is close to its cap, thus avoiding an OOM kill.

### Proposal

Vector is "memory capacity aware" and applies back-pressure rather than allocating when it is at risk of being OOM killed.

### References

* https://github.com/vectordotdev/vector/issues/11022

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)

**Comment by baiyibing123** [comment]
Is there no solution to this problem？

**Comment by baiyibing123** [comment]
No response？

**Comment by johnhtodd** [comment]
We have the same concerns, as we often hit OOM death issues with Vector. However, I'll say that the best solution for this would be contributions of code to solve the issue.

**Comment by jszwedko** [comment]
Agreed, this is likely to be a very large and invasive project that we unfortunately haven't been able to prioritize just yet. I realize it would be very useful.

**Comment by johnhtodd** [comment]
Perhaps the first thing to do would be aware in components, to make this more of a manage-able process.  Is it possible for each component to understand the memory that it is using?  Can this be exposed in an internal (prometheus) metric easily, or would that require significant work?  I would theorize that each aggregation at least could understand its memory space usage, since each metric has a easily understood size. Same for enrichments, which have fixed sizes once indexed.  Buffers in sinks. Lua. Reduce? I am not sure what other types of components would take up significant memory other than the memory required to thread N individual processing pipelines.  But I am guessing without knowing the code base at all. 

I think the biggest item would be aggregations (cardinality) and buffers in sinks - maybe start there?

**Comment by jszwedko** [comment]
> Perhaps the first thing to do would be aware in components, to make this more of a manage-able process. Is it possible for each component to understand the memory that it is using? Can this be exposed in an internal (prometheus) metric easily, or would that require significant work? I would theorize that each aggregation at least could understand its memory space usage, since each metric has a easily understood size. Same for enrichments, which have fixed sizes once indexed. Buffers in sinks. Lua. Reduce? I am not sure what other types of components would take up significant memory other than the memory required to thread N individual processing pipelines. But I am guessing without knowing the code base at all.
> 
> I think the biggest item would be aggregations (cardinality) and buffers in sinks - maybe start there?

We did actually take one stab at exposing allocations per-component in https://vector.dev/blog/tracking-allocations/. It's still experimental, currently.

I agree each component could make an attempt at managing its own memory but without a framework in place for this in Vector it may be a bit fraught to do it per-component. I think your sense is roughly right though: sinks tend to use memory creating concurrent requests and memory buffers, some transforms like `aggregate` maintain state, etc.

**Comment by johnhtodd** [comment]
Thanks for the note on the per-component beta framework.  I didn't know that existed, though the "~20% less throughput" comment is concerning.  It might be useful for debugging, but in places where we're at the edge of performance (hence the debugging) it may be a little troublesome.

**Comment by seilerre** [comment]
We are also running into this problem in a Kubernetes Cluster. When something goes wrong and vector is not able to sink as quick as the source sends, the memory rises. Ours was OOMKilled with 4Gi, which is also the limit. I wonder why this limit is reached. One event is max. 1000bytes in size and buffer.max_events is 500 in default. Why does Vector go to 4Gi?

Shouldnt one be able to set buffer.type = memory, buffer.when_full = block and buffer.max_events = 0 to switch off the buffer completely? All events are coming from Kafka anyway with acknowledgements.

**Comment by fwernert** [comment]
Hello,
Trying also to not get OOMKilled on the vector Agent. On my sandbox cluster which is not huge i have no problem but everytime i try to deploy it on our staging cluster it doesn't work -> OOMKilled.

Here is my ansible / k8s conf:

`vector_vars:
  resources:
    requests:
      memory: "64Mi"
      cpu: "10m" # recommanded : cpu: "500m"
    limits:
      memory: "1024Mi"
      # cpu: "6000m"  # recommanded : cpu: "6000m"

  role: "Agent"
  logLevel: "{{ vector_logLevel | default('info') }}"

  customConfig:
    data_dir: /vector-data-dir

    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false

    sources:
      kubernetes_logs:
        type: kubernetes_logs
        # Use extra_label_selector to exclude pods with environment=review
        # Need to have vector.dev/exclude: "true" -> label on pods -> CI
        extra_label_selector: "environment!=review"

    transforms:
      sort:
        type: remap
        inputs: ["kubernetes_logs"]
        source: |
          .labels = .kubernetes.pod_labels || {}
          .app = .labels."app.kubernetes.io/instance" || .labels.app || .labels."k8s-app" || .kubernetes.container_name || "unlabeled"
          .folder = .kubernetes.pod_namespace || "default"
          .pod = .kubernetes.pod_name || "unknown-pod"
          .container = .kubernetes.container_name || "unknown-container"
          .timestamp = now()

    sinks:
      stdout:
        type: console
        inputs: ["sort"]
        encoding:
          codec: json

      s3:
        type: aws_s3
        inputs: ["sort"]
        bucket: "{{ vector_aws_bucket }}"
        endpoint: "{{ vector_aws_endpoint_url }}"
        auth:
          access_key_id: "{{ vector_aws_s3_accesskey }}"
          secret_access_key: "{{ vector_aws_s3_secretkey }}"
          region: "{{ vector_aws_default_region }}"
        compression: gzip
        filename_append_uuid: false
        filename_extension: json.gz
        key_prefix: |-
          {{ 'logs/vector/{{ print "{{ folder }}" }}/{{ print "{{ app }}" }}/{{ print "{{ pod }}" }}-%Y-%m-%d-%H_' }}
        # buffer:  -----------------------------------> commented bc seems to not work
        #   max_size: 1073741824 # 1 GiB en bytes
        #   # type: disk -> prefer disk rather than memory for OOMKilled but didn"t work.
        #   # when_full: block 
        batch:
          timeout_secs: 86400 # 24 hours (86,400 seconds)
          max_bytes: 1073741824 # 1 GiB
          max_events: 10000000 # 10,000,000 Events
        encoding:
          codec: json`

**Comment by fwernert** [comment]
Hello,

I just updated my code to this, the goal here is to deploy 1 agent release and 1 aggregator release but same issue the aggregator got OMMKILLED in about few seconds.

```yaml
# Each role is created with the following workloads:
# Agent = DaemonSet
# Aggregator = StatefulSet
# Stateless-Aggregator = Deployment
# it would be preferable to set a label on the namespace vector.dev/exclude: "true"
# k label ns linkerd-jaeger velero cattle-fleet-system cattle-impersonation-system cattle-system cert-manager trivy-operator vector.dev/exclude="true"
vector_agent_vars:
  resources:
    requests:
      memory: "100Mi"
      cpu: "10m" # recommanded : cpu: "500m"
    limits:
      memory: 2Gi
      cpu: 1 # recommanded : cpu: 6

  role: "Agent"
  logLevel: "{{ vector_logLevel | default('info') }}"

  customConfig:
    data_dir: /vector-data-dir

    api:
      enabled: false
      address: 127.0.0.1:8686
      playground: false

    sources:
      kubernetes_logs:
        type: kubernetes_logs
        # Use extra_label_selector to exclude pods with environment=review
        # Need to have vector.dev/exclude: "true" -> label on pods -> CI
        extra_label_selector: "environment!=review"

    transforms:
      k8s_remap:
        type: remap
        inputs: ["kubernetes_logs"]
        source: |
          .labels = .kubernetes.pod_labels || {}
          .app = .labels."app.kubernetes.io/instance" || .labels.app || .labels."k8s-app" || .kubernetes.container_name || "unlabeled"
          .folder = .kubernetes.pod_namespace || "default"
          .pod = .kubernetes.pod_name || "unknown-pod"
          .container = .kubernetes.container_name || "unknown-container"
          .timestamp = now()

    sinks:
      vector_aggregator:
        type: vector
        inputs: ["k8s_remap"]
        address: "vector-aggregator:9000"
        buffer:
          type: disk
          max_size: 536870912 # 512 MiB
          when_full: block

vector_aggregator_vars:
  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: "4Gi"
      cpu: 2
  persistence:
    enabled: true
    size: "{{ vector_persistence_size | default('5Gi') }}"

  role: "Aggregator"
  logLevel: "{{ vector_logLevel | default('info') }}"

  customConfig:
    data_dir: /vector-data-dir

    api:
      enabled: false
      address: 127.0.0.1:8686
      playground: false

    sources:
      vector_agent:
        type: vector
        address: 0.0.0.0:9000

    sinks:
      stdout:
        type: console
        inputs: ["vector_agent"]
        encoding:
          codec: json

      s3:
        type: aws_s3
        inputs: ["vector_agent"]
        bucket: "{{ vector_aws_bucket }}"
        endpoint: "{{ vector_aws_endpoint_url }}"
        auth:
          access_key_id: "{{ vector_aws_s3_accesskey }}"
          secret_access_key: "{{ vector_aws_s3_secretkey }}"
          region: "{{ vector_aws_default_region }}"
        compression: gzip
        filename_append_uuid: false
        filename_extension: json.gz
        filename_time_format: "%H-%M-%S"
        key_prefix: |-
          {{ 'logs/vector/{{ print "{{ folder }}" }}/{{ print "{{ app }}" }}/{{ print "{{ pod }}" }}/%Y/%m/%d/' }}
        buffer:
          type: disk
          max_size: 4294967296 # 4 GiB
          when_full: block
        batch:
          timeout_secs: 3600 # 1 heure
          max_bytes: 536870912 # 512Mib
          max_events: 500000 # 500 000 événements
        encoding:
          codec: json

  # Create a Secret resource for Vector to use.
  secrets:
    generic:
      awsAccessKeyId: "{{ vector_aws_s3_accesskey }}"
      awsSecretAccessKey: "{{ vector_aws_s3_secretkey }}"

  # Variables d'environnement pour les creds AWS
  env:
    - name: AWS_ENDPOINT_URL
      value: "{{ vector_aws_endpoint_url }}"
    - name: AWS_DEFAULT_REGION
      value: "{{ vector_aws_default_region }}"
    - name: AWS_USE_PATH_STYLE_ENDPOINT
      value: "false"

```
