### ISSUE TITLE
errors not reported by `top`

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#11960]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Event annotation errors are not being reported in the errors column of `vector top`

### Configuration

```text
[default agent config](https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/configmap.yaml#L58-L86)


    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      kubernetes_logs:
        type: kubernetes_logs
      host_metrics:
        filesystem:
          devices:
            excludes: [binfmt_misc]
          filesystems:
            excludes: [binfmt_misc]
          mountPoints:
            excludes: ["*/proc/sys/fs/binfmt_misc"]
        type: host_metrics
      internal_metrics:
        type: internal_metrics
    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [host_metrics, internal_metrics]
        address: 0.0.0.0:9090
      stdout:
        type: console
        inputs: [kubernetes_logs]
        encoding:
          codec: json
```

### Version

master@f64798723e460fed2ad490be375bd5747d3bd66f

### Example Data

Start your `minikube`, run `tilt up` to deploy your vector agent. Run a `flog` pod to create a bunch of logs

```bash
kubectl create deployment flog --image=mingrammer/flog -- flog -l
```

After waiting a bit to let the logs build up, delete `flog`

```bash
kubectl delete deployments.apps flog
```

After ~60 seconds the metadata will be deleted and errors will be visible in Vector's output, but running `top` will not show any errors for the source:

```bash
kubectl exec -it daemonset/vector -- vector top
```

**Comment by jszwedko** [comment]
Just noting that the metric does seem to be incremented so I'm thinking this might be an issue with the API. I saw:

```
vector_component_errors_total{component_id="kubernetes_logs",component_kind="source",component_name="kubernetes_logs",component_type="kubernetes_logs",error_code="annotation_failed",error_type="reader_failed",stage="processing"} 216770 1648063922467
```

**Comment by jszwedko** [comment]
Yeah, I was able to reproduce this without the `kubernetes_logs` source. It seems like errors just generally aren't being reported to `vector top`.

I used the following config:

```toml
data_dir = "/var/lib/vector/"

[api]
enabled = true
playground = true

[sources.source0]
type = "stdin"

[transforms.transform0]
inputs = ["source0"]
type = "remap"
source = ". = parse_json!(.message)"

[sinks.sink0]
inputs = ["transform0"]
print_interval_secs = 1
type = "blackhole"

[sinks.sink0.healthcheck]
enabled = true

[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"

[sources.metrics]
scrape_interval_secs = 2
type = "internal_metrics"

[sinks.prometheus]
inputs = ["metrics"]
address = "0.0.0.0:9598"
type = "prometheus"
```

And fed it bogus input. 

The metric is correctly output:

```
vector_component_errors_total{component_id="transform0",component_kind="transform",component_name="transform0",component_type="remap",error_type="conversion_failed",stage="processing"} 1765220 1648064681315
```

But `vector top` does not report it.
