### ISSUE TITLE
New `recollect_fields` transform

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1200]
It would be nice to have a transform that, if a given field is not present in the event,
can insert this field with last observed value of this field from previous events.

Example configuration:

```toml
[transforms.recollect_fields]
inputs = ["in"]
fields = ["field1", "field2"]
```

Such a transform could have been implemented by a user with a stateful JavaScript transform (#721) as

```javascript
const fields = ["field1", "field2"];
const storedValues = {};

const handler = event => {
  for (const field of fields) {
    if (event.hasOwnProperty(field)) {
      storedValues[field] = event[field];
    } else if (storedValues.hasOwnProperty(field)) {
      event[field] = storedValues[field];
    }
  }
  return event;
}
```

As a bonus, this transform would allow to join multiple streams of events.

For example, for this config

```toml
[inputs.cpu_temp]
# produces events with field "cpu_temp"

[inputs.cpu_freq]
# produces events with field "cpu_freq"

[transforms.cpu_state]
type = "recollect_fields"
inputs = ["cpu_temp", "cpu_freq"]
fields = ["cpu_temp", "cpu_freq"]

[outputs.console]
type = "console"
inputs = ["recollect_fields"]
```

events containing both temperature and frequency would be printed.

In addition to the most basic form described above, we can add an optional configuration parameter `forget_time` which would prevent the field value from being recollected if it was produced earlier than the the current time minus timeout.
