### ISSUE TITLE
Improve error reporting in Lua transform if metric fields are incorrect

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#12052]
In the Lua transform if you set  `event.metric = something` and that something is a table that doesn't have a valid timestamp you get an error like:

```
ERROR transform{component_kind="transform" component_id=host_source_exec component_type=lua component_name=host_source_exec}: vector::internal_events::lua: Error in lua script; discarding event. error=RuntimeErrorHooksProcess { source: CallbackError { traceback: "stack traceback:\n\t[C]: in local 'emit'\n\t[string \"src/transforms/lua/v2/mod.rs:126:9\"]:4: in function <[string \"src/transforms/lua/v2/mod.rs:126:9\"]:1>", cause: FromLuaConversionError { from: "string", to: "table", message: None } } } internal_log_rate_secs=30
```

This really doesn't give a good indication as to what is causing the error.

These error reports could be greatly improved!

-------

Repro with this config:

```toml
[sources.stdin]
type = "stdin"

[transforms.parse_exec_json]
  type = "remap"
  inputs = [ "stdin" ]
  source = """
log(.)
. = parse_json!(.message)
.timestamp = ""
"""

[transforms.host_source_exec]
  type                      = "lua"
  inputs                    = ["parse_exec_json"]
  version                   = "2"
  hooks.process             = '''
function (event, emit)
  event.metric = event.log
  event.log = nil
  emit(event)
end
'''

[sinks.console]
type = "console"
inputs = ["host_source_exec"]
target = "stdout"
encoding.codec = "json"
```

Use the following input:

```
{"gauge": {"value": 2 }, "kind": "absolute", "namespace": "raid", "name": "deviceup", "tags": { "instance_id": "hathor", "zone_code": "au" }}
```
