### ISSUE TITLE
Vector stops processing http source requests after 12-24 hours of production run

### ISSUE THREAD

**Issue by diegolbx** [vectordotdev/vector#12068]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We are running Vector. latest 0.20 version, on ubuntu 22.04 lxd container. Vector is configured with 3 different types of sources (syslog + nginx + http) and 2 sinks (newrelic + humio). 

After 12-24 hours of continuous operation, about 6GB/day http log injection rate, Vector http source stops responding. Process is up and syslog+nginx source/sink are running perfectly.  We have about 20 clients concurrently connecting to vector http source at any moment. Factoring logging concurrency, there may be more than 100+ connections to http source at any moment.

We did a simple telnet port test on http source port and got disconnected immediately. Strace on vector while this telnet test is performed shows no activity within vector and likely a mutex deadlock?

```root@vector:~# strace -p  1172
strace: Process 1172 attached
futex(0x7f9a4ffdf040, FUTEX_WAIT_PRIVATE, 1, NULL
```

### Configuration

We are running several sources. 
1) Syslog udp
2) Nginx
3) Http ndjson

When http source stops responding, both syslog and nginx sources are working along with relevant sinks. The only issue is http source tcp acceptor appears to be deadlocked? and not responding to new requests.

Below is our http config, we stripped out working syslog/nginx configs.
-------------

```toml
[api]
enabled = true

[sources.http]
type = "http"
address = "0.0.0.0:8080"
encoding = "ndjson"

[transforms.http_parse_json]
type = "remap"
inputs = [ "http" ]
source = '''
del(.path)
del(.source_type)
del(.app)
'''

[sinks.new_relic]
  type = "new_relic_logs"
  inputs = ["http_parse_json"]
  license_key = "xxx"

[sinks.humio]
inputs = ["http_parse_json"]
type = "humio_logs"
encoding.codec = "json"
host = "https://cloud.community.humio.com"
token = "xxx"
```

### Version

0.20
