### ISSUE TITLE
Ability to specify all sources in the inputs option (i.e., inputs = ["sources.*"])

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#12083]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

As the owner of a shared Vector aggregator deployment, I want to ensure all `sources` used by my teams are routed into a shared pipeline as to normalize and secure my data stream.

I want to be able to add numerous `sources` depending on my users needs without worrying about the configuration overhead of adding them into downstream components.

cc @binarylogic 

### Attempted Solutions

The `inputs` option for components supports wildcards (`*`), however that applies to any `source` or `transform` (`sinks` have no output to use as an input) in the DAG - which can cause unintended consumption from downstream components, or components in the same "layer".  Take the following generated config:

```toml
data_dir = "/var/lib/vector/"

[sources.source0]
max_length = 102400
type = "stdin"

[sources.source0.decoding]
codec = "bytes"

[sources.source0.framing]
method = "newline_delimited"

[sources.source1]
count = 9223372036854775807
format = "json"
interval = 1.0
type = "demo_logs"

[sources.source1.decoding]
codec = "bytes"

[sources.source1.framing]
method = "bytes"

[transforms.transform0]
inputs = ["*"]
drop_on_abort = false
drop_on_error = false
reroute_dropped = false
timezone = "local"
type = "remap"
source = """
.
"""

[transforms.transform1]
inputs = ["transform0"]
drop_on_abort = false
drop_on_error = false
reroute_dropped = false
timezone = "local"
type = "remap"
source = """
.
"""

[sinks.sink0]
inputs = ["transform1"]
target = "stdout"
type = "console"

[sinks.sink0.encoding]
codec = "json"

[sinks.sink0.healthcheck]
enabled = true

[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"
```

This _almost_ does what we want it to but causes a cyclic dependency chain as `transform1` becomes an input for `transform0`. This is avoidable by carefully naming your `sources` to avoid mis-capturing `transforms`, but that's brittle and can cause some awkward naming schemes (`sources.source_syslog` + `sources.source_journald` + etc).

### Proposal

Allow `inputs` to be described with "fully qualified" component names. A component with configured with `inputs = ["sources.*"]` would take inputs from every configured `source`, likewise we could have `inputs = ["transforms.*"]` take inputs from every `transform` but that seems to have less usecases and causes more event duplication concerns.

This addition should be backward compatible, as we can assume any input provided without a `.`(dot) divider is the exact component name and the topology would be build as it is today.

Theoretically this also opens up naming possibilities not available today, as component names are global in the sense that a `source` and `transform` can't share the same name. With this feature we could allow that and require the input be "namespaced" (`component_kind.component_name`).

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)
