### ISSUE TITLE
What is the `field` attribute for `log_to_metric` transform ?

### ISSUE THREAD

**Issue by midnightexigent** [vectordotdev/vector#12118]
From [example](https://vector.dev/docs/reference/configuration/transforms/log_to_metric/#examples-counter). I am not sure I understand what it does 

```toml
[transforms.my_transform_id]
type = "log_to_metric"
inputs = [ "my-source-or-transform-id" ]

  [[transforms.my_transform_id.metrics]]
  type = "counter"
  field = "status" # I don't understand how it maps to the output 
  name = "response_total"
  namespace = "service"

    [transforms.my_transform_id.metrics.tags]
    status = "{{status}}"
    host = "{{host}}"
```
