### ISSUE TITLE
Config: `decoding` and `encoding` in sources/sinks are not fully validated

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#12127]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

A colleague noticed today that Vector is silently ignoring invalid `decoding` and `encoding` configurations in sources and sinks.
In particular, by mistake he had an `only_filds` configuration inside the `encoding` section of the sink, and was wondering why Vector was still emitting all the fields in the events being processed.

After careful examination, he realised the typo, and after correcting, Vector started to apply the `only_fields` configuration.
This prompted me to check more closely and indeed Vector seems to not be validating what is in the `decoding` and `decoding` configuration sections in sources/sinks. Well, actually _almost_. The only configuration that gets validated is `codec`, which, if missing, causes Vector to complain and exit.

For example, this configuration is marked as valid and Vector happily boots without any errors:
```yaml
sources:
  logs:
    type: demo_logs
    format: syslog
    decoding:
      codec: bytes
      yabba: dabba-doo

sinks:
  console:
    type: console
    inputs:
      - logs
    encoding:
      codec: json
      yabba: dabba-doo
      only_filds:
        - hello
```

### Version

vector 0.20.1 (x86_64-unknown-linux-gnu 38b806e 2022-04-07)

### References

Looks like highly related to https://github.com/vectordotdev/vector/issues/9115
