### ISSUE TITLE
Thread 'vector-worker' panicked at 'all branches are disabled and there is no else branch'

### ISSUE THREAD

**Issue by nicovak** [vectordotdev/vector#12245]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We upgraded to 0.21 on our K8S cluster and I can see this error in vector's agent logs.

```sh
thread 'vector-worker' panicked at 'all branches are disabled and there is no else branch', src/kubernetes/reflector.rs:26:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Configuration

```yaml
data_dir: /vector-data-dir
api:
  enabled: false
  address: '0.0.0.0:8686'
  playground: true
log_schema:
  host_key: host
  message_key: message
  source_type_key: source_type
  timestamp_key: timestamp
sources:
  kubernetes_logs:
    type: kubernetes_logs
  internal_metrics:
    type: internal_metrics
sinks:
  prom_exporter:
    type: prometheus_exporter
    inputs: [internal_metrics]
    address: 0.0.0.0:9090
  loki:
    type: loki
    inputs:
      - kubernetes_remove_label_istio
    endpoint: 'XXXXXXXXXXXXXXXX'
    tls:
      ca_file: /etc/vector/ca.crt
    encoding:
      codec: json
    labels:
      env: XXXXXXXXXXX
      k8s_pod_namespace: '{{ kubernetes.pod_namespace }}'
      k8s_pod_name: '{{ kubernetes.pod_name }}'
      k8s_container_name: '{{ kubernetes.container_name }}'
transforms:
  kubernetes_remove_label_istio:
    type: remove_fields
    inputs:
      - kubernetes_logs
    fields:
      - kubernetes.pod_labels.app
      - kubernetes.pod_labels.istio
```

### Version

0.21
