### ISSUE TITLE
Nkey authentication for nats sink causes authentication error

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#12262]
Is this valid? I get `authentication error - Nkey ""` on the nats side.

```toml
[sinks.sink_nats]
type = "nats"
inputs = [ "my_source_id" ]
url = "nats://nats:4222"
subject = "test_subject"
encoding.codec = "json"

  [sinks.sink_nats.auth]
  strategy = "nkey"
  nkey.nkey = "U_key"
  nkey.seed = "S_key"
```

I'll try with `auth.credentials_file, since vector has a unit test for it.

EDIT: same thing with a credentials_file. Here's a repo to reproduce https://github.com/bbigras/vector-nats-nkey

_Originally posted by @bbigras in https://github.com/vectordotdev/vector/issues/10533#issuecomment-1100734952_
