### ISSUE TITLE
VRL user-agent parsing is a bottleneck in http -> pipelines -> blackhole

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#12267]
This issue is part of the work ongoing in #10144. After #11849 reduced the topology related overhead of the HTTP -> pipelines -> blackhole soak we now have a clear CPU bottleneck in the VRL user agent parsing. Consider Vector at e1fceb79808998e0b7e6889a706d39fc4b8b6b76. Run a release build of Vector -- `RUSTFLAGS="-Cforce-frame-pointers=yes" CARGO_PROFILE_RELEASE_DEBUG=2 cargo build --release` -- under lading with the following config:

```yaml
generator:
  http:
    seed: [2, 3, 5, 7, 11, 13, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137]
    headers: {}
    target_uri: "http://localhost:8282/"
    bytes_per_second: "500 Mb"
    parallel_connections: 10
    method:
      post:
        maximum_prebuild_cache_size_bytes: "256 Mb"
        variant:
          static:
            static_path: "/home/blt/http_pipeline/bootstrap.log"
```

Where `bootstrap.log` is [this file](https://gist.github.com/blt/15269ffa36f4521bbae26e90ebdafe05). If you do a perf record -- `perf record --verbose --compression-level=22 --call-graph=dwarf --pid=`pidof vector` --output=/tmp/vector.perf.data` -- while this runs you can get a flamegraph with roughly three peaks:

![image](https://user-images.githubusercontent.com/3579/163889790-8606062d-351f-4d99-9cc3-2567eeaf3987.png)

Zooming in on the middle we see:

![image](https://user-images.githubusercontent.com/3579/163889820-92a04b99-95c4-47c7-99d2-e517003d0709.png)

Vector in the http -> pipelines -> blackhole soak configuration spends approximately 25% of execution time in  [`uaparser::UserAgentParser::parse_device`](https://docs.rs/uaparser/0.5.1/uaparser/struct.UserAgentParser.html#method.parse_device) and [`parse_user_agent`](https://docs.rs/uaparser/0.5.1/uaparser/struct.UserAgentParser.html#method.parse_user_agent). Performance issues with uaparser were noted when VRL support was [introduced into the project](https://github.com/vectordotdev/vector/issues/7077#issuecomment-859833619).

Reading the conversation in #7077 it does appear that uaparser maintains compatibility with overall Datadog user agent parsing and is desirable in that sense. Different, faster parsing options are discussed there as well and are present in the code still yet, but the soak is rigged to parse in "enriched" mode, which the introductory PR notes as being "Useful when the priority is to extract as much information as possible." At least in that soak it appears that user agent is subsequently read, although it's not clear to me that all extracted fields are nor if device information is.
