### ISSUE TITLE
Decouple `internal_logs` from log configuration

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12399]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

A user is interested in disabling all logs sent to `stderr` (`VECTOR_LOG=off`) but still have these logs go through `internal_logs`.

Currently the relationship between configured log level and what `internal_logs` receives is unclear.

https://vector.dev/docs/reference/configuration/sources/internal_logs/#logs-are-limited-by-startup-options mentions the same options should apply, but running:

```toml
data_dir = "/var/lib/vector/"

[sources.source0]
type = "internal_logs"

[sinks.sink0]
inputs = ["source0"]
type = "console"
encoding.codec = "json"

[sources.demo]
format = "json"
interval = 1.0
type = "demo_logs"

[sinks.blackhole]
inputs = ["demo"]
print_interval_secs = 1
type = "blackhole"
```

With `vector -qq` still results in the `INFO` messages being picked up by `internal_logs`.

However it seemed like when I added a `remap` transform that logged at `log("hello", level: "trace", rate_limit_secs: 0)`, this one was _not_ picked up by `internal_logs`. I'm thinking it might be defaulting to `info` there.

### Version

vector 0.21.1
