### ISSUE TITLE
[Feature Request] Support k8s pod logs

### ISSUE THREAD

**Issue by caibirdme** [vectordotdev/vector#12425]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

kubernates_logs can only collect the stdout/stderr log from pods, but most applications record their logs in user-defined file rather than stdout/stderr. So could kubernates_logs support us to matching workloads and then configure the filepath on the pods in that  workloads

### Proposal

config may look something like below:
```yaml
selector:
  labels:
    app=worldpress
  annotations:
    k8s/partof: blog-system
log_path:
  - /a/b/c.log
  - /c/e/([a-z]+).txt
```

### Version

v0.21.1
