### ISSUE TITLE
Mock `now()` for vector tests.

### ISSUE THREAD

**Issue by sam-mcbr** [vectordotdev/vector#12490]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I have a transform that does some basic timestamp validation on logs. This validation involves some comparisons of the log's timestamp to `now()`. The main issue is when trying to write test cases for these validation, I have to end up writing a lot of test-specific logic in the transform since the test inputs are constant but `now()` keeps changing (eventually breaking the tests).

### Attempted Solutions

My approach to solving this with Vector's existing features is to create special `log_fields` keys in the test which will trigger different code paths, such as comparing the input timestamp to a hard-coded one instead of `now()`. This makes the transform logic much more bloated than it otherwise would be if I just ignored test cases.

### Proposal

Maybe some kind of key in the input dictionary, possibly like below:
```yaml
- name: Test against now()
  inputs:
  - type: log
    insert_at: my_transform
    log_fields:
      <...>
    mock:
      now: 2022-04-29T00:00:00Z
```

### Version

0.21.1
