### ISSUE TITLE
Empty warning messages emitted

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#12526]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Loading the following configuration generates 2 empty warnings. This was bisected down, and was introduced in dcc7bd215ad087927017e3200316eff2c45fb218

The example was taken from https://github.com/vectordotdev/vector/issues/12522

```text
2022-05-02T16:37:11.831091Z  WARN vector::transforms::remap: VRL compilation warning. warnings=
2022-05-02T16:37:11.831151Z  WARN vector::transforms::remap: VRL compilation warning. warnings=
```

### Configuration

```toml
[sources.input_file]
type = "file"
include = ["/root/log"]
read_from = "end"

[transforms.t_json]
type = "remap"
inputs = [ "input_file" ]
source = """
. = parse_json!(.message)
"""

[transforms.t_lua]
type = "lua"
inputs = [ "t_json" ]
version = "2"
source = '''
-- LIBRARIES

function process(event, emit)
        emit(event)
end
'''
hooks.process = "process"

[transforms.t_encrypt]
type = "remap"
inputs = ["t_lua"]
source = '''
. = .
'''

[sinks.serverout]
type = "console"
inputs = ["t_encrypt"]
target = "stdout"
encoding.codec = "json"
```

### Version

master / dcc7bd215ad087927017e3200316eff2c45fb218
