### ISSUE TITLE
Incompatibility with LUA Transform and Clickhouse Arrays

### ISSUE THREAD

**Issue by sinkingpoint** [vectordotdev/vector#12577]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

This might be a bit esoteric, but I have a Clickhouse table, like this:

```
CREATE TABLE IF NOT EXISTS (
    tags Array(String)
)
```

and I want to insert into it with a Vector instance. For reasons (Mostly https://github.com/vectordotdev/vector/blob/master/rfcs/2021-08-29-8381-vrl-iteration-support.md), I can't use a VRL transform so I am using LUA:

```
function (event, emit)
   output = {}
   table.insert(output, "test_tag")
   emit({log=output})
end
```

Because LUA encodes arrays as hashtables in the backend however, these come out as a dictionary in the request to Clickhouse, and thus Clickhouse complains (as it was expecting an array):

```
WARN sink{component_kind="sink" component_id=clickhouse component_type=clickhouse component_name=clickhouse}:request{request_id=0}: vector::sinks::util::retries: Retrying after response. reason=Code: 130. DB::Exception: Array does not start with '[' character: (while reading the value of key tags): (at row 1)
: While executing ParallelParsingBlockInputFormat. (CANNOT_READ_ARRAY_FROM_TEXT) (version 22.1.3.7 (official build))
```

And the insert fails. I understand that this might just be a limitation of LUA, but is there any work around for this?

### Version

vector 0.21.1 (x86_64-unknown-linux-gnu 18787c0 2022-04-22)

**Comment by sinkingpoint** [comment]
Deep. I guess that was a big in my example - my point is that tags isn't actually an array - it's a table (and thus gets outputted to Clickhouse as a dictionary)

**Comment by jszwedko** [comment]
No worries. I think I'm still not seeing the issue though. Vector does seem to correctly handle Lua tables that represent arrays. Given the following config:

```toml
[sources.source0]
type = "stdin"

[transforms.transform0]
inputs = ["source0"]
type = "lua"
version = "2"
hooks.process = """
function (event, emit)
  tags = {"test_tag"}
  output = {}
  output["tags"] = tags
  emit({log=output})
end
"""

[sinks.sink0]
inputs = ["transform0"]
target = "stdout"
type = "console"
encoding.codec = "json"
```

Running `echo hello | vector --config /tmp/tmp.toml` I get:

```
{"tags":["test_tag"]}
```

Which has the `tags` field as an array.

Maybe I'm missing something though? Is it possible you refined your Lua example too far and it is missing the behavior that triggers the issue?

**Comment by sinkingpoint** [comment]
Sigh... Yeah I did a bit more digging into this. It's actually an issue with _empty_ arrays:

```
[sources.source0]
type = "stdin"

[transforms.transform0]
inputs = ["source0"]
type = "lua"
version = "2"
hooks.process = """
function (event, emit)
  output = {}
  output["tags"] = {}
  emit({log=output})
end
"""

[sinks.sink0]
inputs = ["transform0"]
target = "stdout"
type = "console"
encoding.codec = "json"
```

LUA can't tell that we're wanting an array and not an empty dict. Sorry for barking up the wrong tree

**Comment by jszwedko** [comment]
Aaah, interesting, yeah, that seems likely to be because Lua just has tables rather than separate data types for arrays and dictionaries. I'll leave this open to see if there is anything we can do here when converting the Lua type back to Vector's native value types. A workaround would be to have a subsequent `remap` transform map empty objects to arrays like:

```toml
[sources.source0]
type = "stdin"

[transforms.transform0]
inputs = ["source0"]
type = "lua"
version = "2"
hooks.process = """
function (event, emit)
  output = {}
  output["tags"] = {}
  emit({log=output})
end
"""

[transforms.remap]
type = "remap"
inputs = ["transform0"]
source = """
if is_empty(.tags) ?? true {
  .tags = []
}
"""

[sinks.sink0]
inputs = ["remap"]
target = "stdout"
type = "console"
encoding.codec = "json"
```
