### ISSUE TITLE
Vector log_to_metric transform ignorning metric timestamps

### ISSUE THREAD

**Issue by atibdialpad** [vectordotdev/vector#12697]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

It seems Vector is resetting the timestamp of any metric derived from logs via the log_to_metric transform to the current time as opposed to the '.timestamp' field set in the transform.

Config :  
LOG : 
`2022-05-11 05:12:12.897 INFO Initiating rackman server`

Before the log_to_metric tanform the log event looks like this. Note that the timestamp field has been extracted from the log line and processed via "parse_timestamp("<>", format: "%F %T %.f")" to ensure its of type 'timestamp'
```
{"timestamp":"2022-05-11T05:12:12.897Z", "loglevel":"INFO", "message":"Initiating rackman server"}
```

TO METRIC TRANSFORM
```
[transforms.log_to_metric]
  type = "log_to_metric"
  inputs = ["pre_process_metric"]
  [[transforms.log_to_metric.metrics]]
    type = "counter"
    increment_by_value = true
    name = "fsm.logline"
    tags.level = "{{ loglevel }}"
    timestamp = "{{ timestamp }}" <--- Hoping this sets the metric timestamp to be the timestamp from the log line
```

However the final metric has the timestamp form when Vector processed this event rather than one derived from the log and explicitly set in the log_to_metric transform.

Before metric creation, the log event looks like 
```
{"loglevel":"INFO","message":"Initiating rackman server","timestamp":"2022-05-11T05:12:12.897Z"}
```
After metric creation, the metric event looks like (Note the timestamp has changed.)
```
{"name":"fsm.logline","tags":{"level":"INFO"},"counter":{"value":1.0},"timestamp":"2022-05-11T05:12:20.010025656Z","kind":"incremental",}
```
@jszwedko 

### Configuration

```text
Added in description
```

### Version

latest

### Debug Output

```text
Added
```

### Additional Context

Its important to have the correct timestamp in metrics for cases when Vector is backlogged or is restarted after a delay and is catching up on older logs.

**Comment by zifot** [comment]
I see similar behavior on vector 0.21.2. With the exception that setting a new timestamp on a message (overwriting the original one that reflects time of ingesting by a source) causes metric created afterwards not to have timestamp field at all (at least it looks like this after pushing it to console sink).

**Comment by zifot** [comment]
BTW, @atibdialpad, I believe there is no "timestamp" field under metric object, at least none is mentioned at https://vector.dev/docs/reference/configuration/transforms/log_to_metric/.

**Comment by atibdialpad** [comment]
@zifot yup, the log_to_metric transform doesn't. The Metric Data Model has a notion of 'timestamp' which makes me think its just a matter of making that field writable at the transform stage.

**Comment by atibdialpad** [comment]
@jszwedko @spencergilbert thoughts ?

**Comment by jszwedko** [comment]
Thanks for this report @atibdialpad !

Looking at the source, it looks like the `log_to_metric` transform always attempts to read the `timestamp` field from the incoming log event (or whatever is configured as [`log_schema.timestamp_key`](https://vector.dev/docs/reference/configuration/global-options/#log_schema.timestamp_key).

You are correct in noting that it will only set it if the `timestamp` is an actual timestamp type though. Your format string above doesn't match the input timestamp format, so it's possible it isn't being parsed correctly. Running with the following configuration seems to work:

```toml
[sources.source0]
type = "stdin"
decoding.codec = "json"

[transforms.pre_process_metric]
type = "remap"
inputs = ["source0"]
source = """
.timestamp = parse_timestamp!(.timestamp, format: "%FT%T %.fZ")
"""

[transforms.log_to_metric]
  type = "log_to_metric"
  inputs = ["pre_process_metric"]
  [[transforms.log_to_metric.metrics]]
    type = "counter"
    field = "message"
    name = "fsm.logline"
    tags.level = "{{ loglevel }}"

[sinks.sink0]
inputs = ["log_to_metric"]
type = "console"
encoding.codec = "json"
```

With:

```
echo '{"timestamp":"2022-05-11T05:12:12.897Z", "loglevel":"INFO", "message":"Initiating rackman server"}' | vector-0.21.1 --config /tmp/tmp.toml
```

Yields:

```json
{"name":"fsm.logline","tags":{"level":"INFO"},"timestamp":"2022-05-11T12:12:12.897Z","kind":"incremental","counter":{"value":1.0}}
```

You can see there the timestamp was taken from the log event.
