### ISSUE TITLE
Fallible predicate (parse_json+merge+contains)

### ISSUE THREAD

**Issue by akshaal** [vectordotdev/vector#12802]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Everything works "fine" with vector 0.19.1. Here is a mini-version of a real config I am trying to run:
```toml
[sources.generator]
  type = "generator"
  format = "syslog"
  
[transforms.remap]
  type = "remap"
  inputs = ["generator"]
  source = '''
  structured, err = parse_json(.message)
  if err == null {
    . = merge(structured, .) ?? .
  }
  .message = to_string(del(.msg)) ?? ""
  if contains(.message, "xxx") {
    .x = "y"
  }
  // [.... many more uses of .message... all of them fail to "typecheck" .... ]
  '''
  
[sinks.console]
  type = "console"
  inputs = ["remap"]
  encoding = "json"
```

Results in:

```
error[E111]: fallible predicate
  ┌─ :6:6
  │
6 │   if contains(.message, "xxx") {
  │      ^^^^^^^^^^^^^^^^^^^^^^^^^
  │      │
  │      this predicate can result in runtime error
  │      handle the error case to ensure runtime success
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = see language documentation at https://vrl.dev
```

But If I change the code like this, then it works...
```toml
  source = '''
  structured, err = parse_json(.message)
  if err == null {
    . = merge(structured, .) ?? .
  }
  if contains(to_string(del(.msg)) ?? "", "xxx") {
    .x = "y"
  }
  '''
```

It also compiles fine without parse_json:
```toml
  source = '''
  .message = to_string(del(.msg)) ?? ""
  if contains(.message, "xxx") {
    .x = "y"
  }
  '''
```
But as soon as I add that weird 'merge', then everything fails. 

(another problem is that 'merge' is marked as infallible in the documentation https://vector.dev/docs/reference/vrl/functions/#merge while the "typechecker" insists that "this expression is fallible" in the ". = merge(structured, .)" )

### Version

0.21.2

### References

- https://github.com/vectordotdev/vector/issues/7429
- https://github.com/vectordotdev/vector/issues/7402
