### ISSUE TITLE
Review condition component concept

### ISSUE THREAD

**Issue by Jeffail** [vectordotdev/vector#1281]
For the purpose of implementing unit tests (https://github.com/timberio/vector/issues/232) I added a new component type called a condition. Unit test functionality is in beta stage right now and so it's a good opportunity to experiment with a practical use case for condition types.

## Why?

The purpose of conditions is to allow users to define logical expressions for events that resolve to either `true` or `false` and can be reused throughout their topology. Conditions will most likely only appear in unit tests and a future `filter` transform (https://github.com/timberio/vector/issues/882), and therefore we could easily get away with not having a new component type at all.

However, I think it's beneficial to bring these in as a component type for two main reasons.

### 1. It enables reuse

In many cases a user is likely to build an expression to filter data that might be sensitive so that it isn't aggregated somewhere inappropriate. However, when doing so a very logical next step would be to direct the sensitive traffic elsewhere, so that it isn't lost entirely.

With a condition type that user would need to write their logic out twice, once as a `this is sensitive` detector, and secondly as a `this is NOT sensitive` detector. When editing an expression in the future it would fall on that user to ensure that the other expression remains the exact opposite. As expressions get larger this becomes riskier and more difficult to ensure.

With conditions a user can define their `this is sensitive` condition and add a second condition referencing the logical NOT of the original condition, it'd look something like this:

```toml
[conditions.is_thing]
  type = "check_fields"
  "status.eq" = 500
  "bar.contains" = "giraffe"

[conditions.not_is_thing]
  type = "not"
  child = "is_thing"

[transforms.filter_things]
 type = "filter"
  condition = "is_thing"

[transforms.filter_not_things]
  type = "filter"
  condition = "not_is_thing"

[sinks.things]
  type = "foo"
  inputs = [ "filter_things" ]

[sinks.not_things]
  type = "bar"
  inputs = [ "filter_not_things" ]
```

You would also be able to break large logical blocks into smaller conditions and aggregate them with some kind of expression condition:

```toml
[conditions.stuff]
  type = "expression"
  value = "(foo and bar) or baz"
```

### 2. It's open to expansion

If a condition is just another component type then we can keep adding new ones as/when the need arises (`mentions_greg_anywhere`, `check_overall_size`, `json_schema`, etc), just like with transforms currently.

Documenting these conditions would be easier as we wouldn't need to describe the entirety of it in a single page.

### Initialization

Since conditions might refer to other sibling conditions we will need to ensure whilst building a topology that they are provided the necessary context. This would most likely require two stages:

1. Build each condition into a `IndexMap<String, Arc<Condition>>`.
2. Call some sort of `init(siblings: IndexMap<String, Arc<Condition>>) -> crate::Result<()>` on each condition

Would we be happy with that?

### API

It would be useful if under certain circumstances a condition could be queried such that it provides context as to why it failed (or succeeded?) This would mostly be useful in unit tests, where the more information the user has about why their test failed the better.

The API currently returns `true` or `false`: `fn check(&self, e: &Event) -> bool;`. We could accompany this method with something like `fn check_with_context(&self, e: &Event) -> Result<(), String>;`.

Returning context will have a performance impact and so would be used sparingly. Is it worth adding this method to the condition trait?

### Documentation

Where should they appear in our documentation?
Does it make sense to allow them to be generated with `vector generate`?

**Comment by binarylogic** [comment]
@Jeffail things have changed since you wrote this so I want to make sure it's still relevant/accurate. Could you review this and clarify your intent? From what I understand, you're proposing that `conditions` can be applied to any transform as a global way to filter data?

**Comment by Jeffail** [comment]
This issue would allow us to reuse conditions in places where the logic is complex to maintain, so for example if we have a swimlanes transform that is choice between one lane or another where the condition is large:

```toml
[transforms.splitting_gerrys]
  inputs = [ "somewhere" ]
  type = "swimlanes"
  
  [transforms.splitting_gerrys.lanes.only_gerrys]
    type = "check_fields"
    "host.eq" = "boo"
    "doc.type.eq" = "buz"
    "message.contains" = ["a thing","and this"]
    "something.and.this.exists" = true

  [transforms.splitting_gerrys.lanes.no_gerrys]
    type = "check_fields"
    "host.neq" = "boo"
    "doc.type.neq" = "buz"
    "message.not_contains" = ["a thing","and this"]
    "something.and.this.exists" = false
```

If the logic determining whether an event is a gerry changes over time it's possible that the condition for `no_gerrys` might deviate from a true representation of not `is_gerry`, resulting in lost events.

But with this issue implemented we could instead create a shared condition object and reuse it by configuring conditions as a string value:

```toml
[conditions.is_gerry]
  type = "check_fields"
  "host.eq" = "boo"
  "doc.type.eq" = "buz"
  "message.contains" = ["a thing","and this"]
  "something.and.this.exists" = true

[transforms.splitting_gerrys]
  inputs = [ "somewhere" ]
  type = "swimlanes"
  
  [transforms.splitting_gerrys.lanes]
    only_gerrys = "is_gerry"

  [transforms.splitting_gerrys.lanes.no_gerrys]
    type = "not"
    not = "is_gerry"
```

This would still be useful in a world where we offer the new mapping language as a condition, as it's more about conveniently referencing a globally defined condition in multiple places.
