### ISSUE TITLE
configuration: formally consider `null` values as "option not provided"

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#12832]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We extensively use environment variables in all of our Vector pipelines to accomodate for different deployment cases. However, for optional configuration options, the user experience is not consistent. For example, consider the following YAML configuration:
```yaml
sources:
  source:
    type: stdin
sinks:
  sink:
    type: http
    inputs: ["source"]
    uri: ${HTTP_URI:-http://localhost:8080}
    encoding:
      codec: ndjson
    batch:
      max_bytes: ${HTTP_BATCH_MAX_BYTES:-null}
      max_events: ${HTTP_BATCH_MAX_EVENTS:-null}
      timeout_secs: ${HTTP_BATCH_TIMEOUT_SECS:-null}
    buffer:
      type: memory
      max_events: ${HTTP_BUFFER_MAX_EVENTS:-500}
    request:
      concurrency: ${HTTP_REQUEST_CONCURRENCY:-adaptive}
    tls:
      enabled: ${HTTP_TLS_ENABLED:-false}
      ca_file: ${HTTP_TLS_CA_FILE:-null}
      crt_file: ${HTTP_TLS_CRT_FILE:-null}
      key_file: ${HTTP_TLS_KEY_FILE:-null}
    proxy:
      enabled: ${HTTP_PROXY_ENABLED:-false}
      http: ${HTTP_PROXY_HTTP:-null}
      https: ${HTTP_PROXY_HTTPS:-null}
```

The above configuration allows us to easily and cleanly configure most of the sink operational parameters without having to modify the pipeline configuration itself. Neat!

However, as can be seen, we are unofficially _abusing_ the `null` value to indicate "use the Vector default here". This works for some options but not for everything. The `buffer.max_events` and `request.concurrency` options are good examples of this. In that case, we simply hard-code the Vector default in the variable expansion default.

Hard-coding Vector defaults like that is not always convenient. For example, the `batch.max_events` default is `usize::max_value()` from what [I could find](https://github.com/vectordotdev/vector/blob/623b18263ff4281c6c42cb9635a5403eb3991747/src/sinks/util/batch.rs#L246-L254) in the source code. This default looks very ugly as a variable expansion default: `18446744073709551615`. Luckily Vector accepts `null` as "use the default" in that case :)

Unfortunately, some other options do not like `null` for this purpose. An example is `proxy.no_proxy` (which we are not using in the above example configuration).

Moreover, since the release of Vector `0.21.x`, some options stopped accepting `null` as values. Notably, this is the case for the `tls.*` options. This breaks our deployments where we do not need TLS options configured. If we default to a dummy value such as `/path/to/file` it does not work because `tls.enabled=false` still tries to read any configured `*_file` option. We also tried defaulting to `/dev/null`, but still does not work because it still tries to read `/dev/null` and finds an invalid X509 certificate (which is quite expected). For this reason, we had to halt migrating to Vector `0.21.x` for the moment.

### Attempted Solutions

As described in the Use-case section, our best attempted solution to deal with optional configuration options is to abuse the `null` value as variable expansion default. However this does not work consistently and since Vector `0.21.x`, this does not work anymore in some options.

### Proposal

We think that a good solution would be to formally accept `null` values as a "use the Vector default value" for all single-unit configuration options, i.e. options that take booleans, integers, floats, strings, etc.

In other words, we propose that any `null` option value is functionally equivalent to not providing such option. We believe that something like this would be a nice UX improvement for Vector.
