### ISSUE TITLE
Add Axiom sink

### ISSUE THREAD

**Issue by bahlo** [vectordotdev/vector#12882]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

People that use [Axiom](https://axiom.co) often want to send logs from existing services to our service (cloud or self-hosted). The end goal is having an easy-to-configure log sink for Axiom to send logs and events to.

### Proposal

Add an Axiom log sink. I imagine it to be similar to the [Honeycomb implementation](https://github.com/vectordotdev/vector/blob/master/src/sinks/honeycomb.rs).

An example `vector.toml` could look like this:
```toml
[sources.demo_logs]
type = "demo_logs"
format = "shuffle"
lines = [
    "foo",
    "bar"
]

[sinks.axiom]
inputs = ["demo_logs"]
type = "axiom"
token = "[redacted]"
dataset = "vector-dev"
```
