### ISSUE TITLE
Incorrect type def regressions with conditionals in VRL

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12948]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The config:

```toml
[sources.in]
type = "stdin"
decoding.codec = "json"

[transforms.remap]
type = "remap"
inputs = ["in"]
source = '''
if .platform == "Apache2" || .platform == "Nginx" {
  apache2 = del(.apache2)
  if is_null(apache2) { apache2 = {} }
  .http = merge(object!(apache2), {})
}
'''

[sinks.out]
type = "console"
inputs = ["remap"]
encoding.codec = "json"
```

Fails to load in 0.22.0 with:

```
error[E620]: can't abort infallible function
  ┌─ :9:17
  │
9 │   .http = merge(object!(apache2), {})
  │                 ^^^^^^- remove this abort-instruction
  │                 │
  │                 this function can't fail
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = see language documentation at https://vrl.dev
```

### Configuration

```text
[sources.in]
type = "stdin"
decoding.codec = "json"

[transforms.remap]
type = "remap"
inputs = ["in"]
source = '''
if .platform == "Apache2" || .platform == "Nginx" {
  apache2 = del(.apache2)
  if is_null(apache2) { apache2 = {} }
  .http = merge(object!(apache2), {})
}
'''

[sinks.out]
type = "console"
inputs = ["remap"]
encoding.codec = "json"
```

### Version

vector 0.22.0

### References

Reported by user in Discord: https://discord.com/channels/742820443487993987/764187584452493323/981878372814717031
