### ISSUE TITLE
vector to vector transfer broken

### ISSUE THREAD

**Issue by ahsandar** [vectordotdev/vector#13114]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

is there some vector-vector breaking changes from 0.19.x to 0.2X.X ? using TLS on my end 0.19.3 setup works perfectly but 0.2X.X seems it fails to work or has some connection issue or event out rate is too slow either way it feels to be a regression. Tried 0.21.2 and 0,22.1 both having same issue. Neither adding compression or batch.max_bytes helped as in the warn log message. It seems I am able to update vector on the sink config without breaking the vector-vector communication but if I use vector above 0.19.3 on source side the communication falls apart

### Configuration

```text
`vector:0.22.1-alpine`

[sinks.kakashi]
  type = "vector"
  inputs = [ "openresty_log", "obliviator_request", "stream"]
  address = "${KAKASHI_VECTOR_SINK}"
  version = "2"
[sinks.kakashi.tls]
  enabled = true
  ca_file = "/opt/vector/tls/server_cert.crt"
  crt_file = "/opt/vector/tls/client_cert.crt"
  key_file = "/opt/vector/tls/client_key.key"


vector:0.19.3-alpine

[sources.vector]
  type = "vector"
  address = "0.0.0.0:19092"
  version = "2"
  shutdown_timeout_secs = 30
[sources.vector.tls]
  enabled = true
  ca_file = "/opt/vector/tls/client_cert.crt"
  crt_file = "/opt/vector/tls/server_cert.crt"
  key_file = "/opt/vector/tls/server_key.key"
  verify_certificate = true
```

### Version

0.22.1

### Debug Output

```text
WARN sink{component_kind="sink" component_id=kakashi component_type=vector component_name=kakashi}:request{request_id=0}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing batch.max_bytes and/or using compression if applicable. Alternatively request.timeout_secs can be increased
```

### Additional Context

running vector in docker using docker compose

### References

https://discord.com/channels/742820443487993987/973851109154246676

**Comment by ahsandar** [comment]
`Working`
0.22.1 -> 0.19.3 
0.22.1 -> 0.20.1
0.22.1 -> 0.22.1 - works now 

`Not Working`
0.21.1 -> 0.21.1
0.22.1 -> 0.21.2

on `0.21.1` I was originally seeing the `request time out` warning in logs and nothing received in source vector using `vector top`. On `0.21.2` I can see data received on source vector using `vector top` but beyond that the transforms and sinks not working. 

my current full configuration for on vector source side is as below

``` toml
#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
# data_dir = "/var/lib/vector"

data_dir = "/opt/vector/data"

[api]
  enabled = true

# Ingest data by tailing one or more files
[sources.vector]
  type = "vector"
  address = "0.0.0.0:19092"
  version = "2"
  shutdown_timeout_secs = 30
[sources.vector.tls]
  enabled = true
  ca_file = "/opt/vector/tls/client_cert.crt"
  crt_file = "/opt/vector/tls/server_cert.crt"
  key_file = "/opt/vector/tls/server_key.key"
  verify_certificate = true


[sources.openresty_access_log]
  type = "file"
  include = [ "/var/log/server-access.log" ] # Specify file or files to be tailed
  ignore_older = 3600 # Ignore events older than 1 hour
  file_key = "openresty-access-log" # Add filename to log events
  host_key = "${NRIA_DISPLAY_NAME}" # Add hostname to log events

[sources.kyubi_request_log]
  type = "file"
  include = [ "/var/log/kyubi_request.log" ] # Specify file or files to be tailed
  ignore_older = 3600 # Ignore events older than 1 hour
  file_key = "kyubi-request-log" # Add filename to log events
  host_key = "${NRIA_DISPLAY_NAME}" # Add hostname to log events


[transforms.remap_vector]
  type = "remap"
  inputs = [ "vector" ]
  source = """
  . = parse_json!(.message)
  """

[transforms.condition]
  type = "route"
  inputs = [ "remap_vector" ]
[transforms.condition.route]
  openresty-access-log = 'exists(.log) && .log.name == "openresty" && .log.type == "nginx"'
  obliviator-request-log = 'exists(.log) && .log.name == "obliviator" && .log.type == "request"'
  dns-stream = 'exists(.log) && .log.name == "obliviator" && .log.type == "dns_stream"'

[transforms.jarvis_encode_openresty_access_log]
  type = "remap"
  inputs = [ "condition.openresty-access-log" ]
  source = """
  . = encode_json(.)
  """

[transforms.encode_obliviator_request_log]
  type = "remap"
  inputs = [ "condition.obliviator-request-log" ]
  source = """
  . = encode_json(.)
  """


[transforms.remap_kakashi_openresty_access_log]
  type = "remap"
  inputs = [ "openresty_access_log" ]
  source = """
  . = parse_json!(.message)
  """

[transforms.remap_kakashi_kyubi_request_log]
  type = "remap"
  inputs = [ "kyubi_request_log" ]
  source = """
  . = parse_json!(.message)
  """

# Configure sink to forward events to New Relic Logs
[sinks.new_relic_logs]
  # REQUIRED
  type = "new_relic_logs" # must be: "new_relic_logs"
  inputs = [ "remap_kakashi_openresty_access_log", "condition.openresty-access-log"] # example - value must be one or more source IDs
  license_key = "${NRIA_LICENSE_KEY}"
  region = "eu" # Enum, must be one of: "us" "eu" depending on your New Relic Logs account region
  compression = "gzip"
  # OPTIONAL
  healthcheck = true # default

[sinks.logdna_kakashi_openresty]
  type = "logdna"
  inputs = [ "openresty_access_log" ]
  api_key = "${LOGDNA_API_KEY}"
  hostname = "${KAKASHI_HOST}"
  default_app = "${KAKASHI_HOST}-openresty"
  default_env = "${KAKASHI_HOST}-vector"

[sinks.logflare_kakashi_openresty]
  type = "http"
  inputs = ["remap_kakashi_openresty_access_log"]
  uri = "https://api.logflare.app/logs/json?source=af80d029-2cf7-45e2-bb99-837c1917098e"
  compression = "none"
[sinks.logflare_kakashi_openresty.request]
  headers = {"X-API-KEY"= "${LOGFLARE_API_KEY}"}
[sinks.logflare_kakashi_openresty.encoding]
  codec = "json"

[sinks.logdna_kakashi_kyubi]
  type = "logdna"
  inputs = [ "remap_kakashi_kyubi_request_log" ]
  api_key = "${LOGDNA_API_KEY}"
  hostname = "${KAKASHI_HOST}"
  default_app = "${KAKASHI_HOST}-kyubi"
  default_env = "${KAKASHI_HOST}-vector"

[sinks.logflare_kakashi_kyubi]
  type = "http"
  inputs = ["remap_kakashi_kyubi_request_log"]
  uri = "https://api.logflare.app/logs/json?source=92565eea-6a76-4ecb-bab7-edb905b1cdb0"
  compression = "none"
[sinks.logflare_kakashi_kyubi.request]
  headers = {"X-API-KEY"= "${LOGFLARE_API_KEY}"}
[sinks.logflare_kakashi_kyubi.encoding]
  codec = "json"

[sinks.logdna_jarvis_openresty]
  type = "logdna"
  inputs = [ "jarvis_encode_openresty_access_log" ]
  api_key = "${LOGDNA_API_KEY}"
  hostname = "${KAKASHI_HOST}"
  default_app = "jarvis-openresty"
  default_env = "${KAKASHI_HOST}-vector"

[sinks.logflare_jarvis_openresty]
  type = "http"
  inputs = ["condition.openresty-access-log"]
  uri = "https://api.logflare.app/logs/json?source=21642209-f258-49a0-ab73-6fd1fe4d34f6"
  compression = "none"
[sinks.logflare_jarvis_openresty.request]
  headers = {"X-API-KEY"= "${LOGFLARE_API_KEY}"}
[sinks.logflare_jarvis_openresty.encoding]
  codec = "json"

[sinks.logdna_jarvis_obliviator]
  type = "logdna"
  inputs = [ "encode_obliviator_request_log" ]
  api_key = "${LOGDNA_API_KEY}"
  hostname = "${KAKASHI_HOST}"
  default_app = "jarvis-obliviator"
  default_env = "${KAKASHI_HOST}-vector"

[sinks.logflare_jarvis_obliviator]
  type = "http"
  inputs = ["condition.obliviator-request-log"]
  uri = "https://api.logflare.app/logs/json?source=be61db0c-7cf6-459e-8f24-105e61219d9d"
  compression = "none"
[sinks.logflare_jarvis_obliviator.request]
  headers = {"X-API-KEY"= "${LOGFLARE_API_KEY}"}
[sinks.logflare_jarvis_obliviator.encoding]
  codec = "json"

[sinks.redpanda_dns_stream]
  type = "kafka"
  inputs = [ "condition.dns-stream" ]
  bootstrap_servers = "${KAFKA_BROKERCONNECT}"
  topic = "dns-stream"
  compression = "gzip"
[sinks.redpanda_dns_stream.buffer]
  type = "disk"
  max_size = 104900
[sinks.redpanda_dns_stream.encoding]
  codec = "json"

[sinks.minio_dns_stream]
  type = "aws_s3"
  inputs = [ "condition.dns-stream" ]
  bucket = "kakashi-dns-stream"
  endpoint = "http://minio:9000"
  region = "us-east-1"
  acl = "private"
  filename_append_uuid = true
  filename_extension = "log.gz"
  filename_time_format = "%H_%M_%s"
  key_prefix = "date=%Y%m%d/"
  compression = "gzip"
[sinks.minio_dns_stream.auth]
  access_key_id = "${MINIO_ROOT_USER}"
  secret_access_key = "${MINIO_ROOT_PASSWORD}"
[sinks.minio_dns_stream.buffer]
  type = "disk"
  when_full = "block"
  max_size = 1049000
[sinks.minio_dns_stream.encoding]
  codec = "ndjson"

[sinks.filebase_dns_stream]
  type = "aws_s3"
  inputs = [ "condition.dns-stream" ]
  bucket = "kakashi-dns-stream"
  endpoint = "${FILEBASE_ENDPOINT}"
  region = "us-east-1"
  acl = "private"
  filename_append_uuid = true
  filename_extension = "log.gz"
  filename_time_format = "%H_%M_%s"
  key_prefix = "date=%Y%m%d/"
  compression = "gzip"
[sinks.filebase_dns_stream.auth]
  access_key_id = "${FILEBASE_ACCESS_KEY}"
  secret_access_key = "${FILEBASE_SECRET_KEY}"
[sinks.filebase_dns_stream.buffer]
  type = "disk"
  when_full = "block"
  max_size = 1049000
[sinks.filebase_dns_stream.encoding]
  codec = "ndjson"

```
