### ISSUE TITLE
Can't pass complex object with nested fields as unit test input

### ISSUE THREAD

**Issue by marcojck** [vectordotdev/vector#13421]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector test command fails with a internal error when passing a complex object with nested fields as unit test input using the `log_fields` field.

This input will work:

```yaml
tests:
  - name: My test 1
    inputs:
      - insert_at: my-transform
        type: log
        log_fields:
          a: 1
          b: 2
```

But with this input Vector will fail with a internal error because field `c` has the `c1` nested field:

```yaml
tests:
  - name: My test 2
    inputs:
      - insert_at: my-transform
        type: log
        log_fields:
          a: 1
          b: 2
          c: 
            c1: 3
```

### Configuration

```text
transforms:
    my-transform:
      type: remap
      inputs: [my-source]
      source: |-
        if (exists(.c.c1)) {
          .c.c2 = 4
        }

tests:
  - name: My test 1
    inputs:
      - insert_at: my-transform
        type: log
        log_fields:
          a: 1
          b: 2

    outputs:
      - extract_from: my-transform
        conditions:
          - type: vrl
            source: |-
              assert_eq!(1, .a)
              assert_eq!(2, .b)
              assert!(!exists(.c.c2))

  - name: My test 2
    inputs:
      - insert_at: my-transform
        type: log
        log_fields:
          a: 1
          b: 2
          c: 
            c1: 3

    outputs:
      - extract_from: my-transform
        conditions:
          - type: vrl
            source: |-
              assert_eq!(1, .a)
              assert_eq!(2, .b)
              assert_eq!(3, .c.c1)
              assert_eq!(4, .c.c2)
```

### Version

vector 0.22.3 (x86_64-unknown-linux-gnu)

### Debug Output

```text
Running tests
2022-07-03T00:27:57.769618Z ERROR vector::unit_test: Failed to execute tests:
data did not match any variant of untagged enum TestInputValue for key `tests.inputs.log_fields.c`.
```
