### ISSUE TITLE
Vector components should not fail to start-up due to connectivity issues

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#13525]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

There's been a general idea floating around that Vector shouldn't fail to start because a component cannot connect to an external system. Right now, this happens, ad hoc, depending on the component. For example, the `redis` sink fails to initialize if it cannot connect at start, even though it can tolerate connection issues later, and causes Vector to exit. On the other hand, sinks that are request-oriented like the `http` sink require the ability to connect to the configured endpoint to start-up.

This means Vector fails to start when there is a, possibly temporary, connection issue.

### Proposal

In general, Vector should be tolerant of connectivity issues and:

* Retry indefinitely
* Not fail to initialize, causing Vector to exit

### References

- https://github.com/vectordotdev/vector/issues/13514

### Version

vector 0.23.0

**Comment by Jerrimikkihvatai** [comment]
Hey! Any updates there? I've encountered a problem with one kafka source and socket + elasticsearch sinks. If socket sink fails, the kafka source stops consuming logs and elasticsearch sink stops working too.
Tried this config but to no avail
```yaml
sources:
  src_mysrc:
    type: kafka
    bootstrap_servers: "${KAFKA_SERVER}"
    group_id: "${KAFKA_CONSUMER_GROUP}"
    topics:
      - kafka-topic
    tls:
      enabled: $KAFKA_SRC_VERIFY_TLS
### transform ommited
sinks:
  sink_alerts:
    type: socket
    healthcheck: false
    acknowledgements:
      enabled: false
    inputs:
      - mytransform
    encoding:
        codec: "json"
    address: cooladdress.com:5000
    mode: "tcp"
  sink_log:
    batch:
      max_size: 100000000
    type: elasticsearch
    api_version: v7
    inputs:
      - mytransform
    endpoints:
      - "${OPENSEARCH_SERVER}"
    auth:
      strategy: basic
      user: "${OPENSEARCH_USER}"
      password: "${OPENSEARCH_PASS}"
    tls:
      verify_certificate: $OPENSEARCH_SINK_VERIFY_TLS
    bulk:
      action: create
      index: "log-%Y.%m"
    id_key: message_id
    mode: bulk
    buffer:
      type: disk
      max_size: 1073741824
      when_full: block
```
