### ISSUE TITLE
Support sending OpenTelemetry logs

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#13622]
Subtasks:

- [ ] Support gRPC to the OpenTelemetry collector
- [ ] Support HTTP (binary-encoded Protobuf format) to the OpenTelemetry collector
- [ ] Integration tests

gRPC can be modeled after the [`vector` (v2)](https://github.com/vectordotdev/vector/tree/master/src/sinks/vector/v2) sink.
HTTP can refer to the [`datadog`](https://github.com/vectordotdev/vector/tree/master/src/sinks/datadog) sinks.

Ref: https://opentelemetry.io/docs/reference/specification/protocol/exporter/
Ref: https://opentelemetry.io/docs/reference/specification/protocol/otlp/

**Comment by spencergilbert** [comment]
One outstanding question that needs to be answered is how we want to model the configuration for the sink, allowing for either HTTP or gRPC based sending. Perhaps something like:

```yaml
otel:
  type: opentelemetry
  inputs: ["source0"]
  address: http://otelcol2:4318
  protocol: grpc # grpc OR http
  http:
    path: "/custom/logs" # changing from the default "/v1/logs" path
  tls:
    # ...
```

Generally want to ensure it's clear what options are valid for http vs grpc, or for both, as well as staying similar/familiar with other sinks.

**Comment by spencergilbert** [comment]
> And there's another question, how to fulfill the opentelemetry proto object by vector Event model?

We have some inflight work that can help ease the translation between data models, but I think we'd start with something similar to our [gelf encoder](https://github.com/vectordotdev/vector/blob/master/lib/codecs/src/encoding/format/gelf.rs).

**Comment by pront** [comment]
### Implementation plan

* Implement conversion from Vector events to the [OTEL proto format](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.15.0/specification/logs/data-model.md)
  * See https://github.com/vectordotdev/vector/blob/master/lib/opentelemetry-proto/src/convert.rs#L201
* If user sets the protocol to `http`, then do something similar to the HTTP sink
  * I can evaluate how much code will be reused but this is a minor concern 
* If the user sets the protocol to `grpc`, then do something similar to the Vector sink
  * See https://github.com/vectordotdev/vector/blob/f799d49aff1b8ebabd4e58beb0d760eef9405aff/src/sinks/vector/service.rs#L67

### Config

```
# ...
sinks: 
  sink0:
    type: opentelemetry
    protocol: grpc # or "http"
    grpc:
      # ... like the OTEL source
    # other common sink config params 
```
