### ISSUE TITLE
Implement `vrl` codec

### ISSUE THREAD

**Issue by pablosichert** [vectordotdev/vector#13634]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Being able to use VRL as a codec, e.g. when decoding

```toml
[sources.···]
# ···
decoding.codec = "vrl"
decoding.source = '''
    parse_json(.) ??
    parse_syslog(.) ??
    abort "invalid format"
'''
# ···
```

or encoding

```toml
[sinks.···]
# ···
encoding.codec = "vrl"
encoding.source = '''
    encode_json(.)
'''
# ···
```

would give users greater flexibility to account for their specific data format.

### Attempted Solutions

This can be accomplished today by adding a separate `remap` transform to the topology.

### Proposal

Implement a codec that exectues a VRL program.

### Version

vector 0.23.0
