### ISSUE TITLE
Allow config timezone when parse timestamps for output path

### ISSUE THREAD

**Issue by linshaoyong** [vectordotdev/vector#1365]
I have some log like this
test.com [11/Dec/2019:16:47:01 +0800]  "GET http://test.com/video/1.mp4"

I want to save this log to sink-20191211-1647.log, but it's been saved to sink-20191211-0847.log because of vector parse timestamp as UTC.

here're some configuration

`[transforms.test_transform]`
    `regex = "^(?P<domain>.*) \\[(?P<timestamp>.*)\\] (?P<others>.*)$"`
   `[transforms.test_transform.types]`
       `timestamp = "timestamp|%d/%b/%Y:%T %z"`

`[sinks.my_sink_id]`
    `type = "file"`
    `inputs = ["test_transform"]`
    `path = "sink-%Y%m%d-%H%M.log"`

**Comment by a-rodin** [comment]
Hi @linshaoyong, thank you for reporting this!

Could you please clarify what do you think would be the expected behavior in case if source contained log events with different timezones?

For example, if input contained two lines, one

```
 test.com [11/Dec/2019:16:47:01 +0800] "GET http://test.com/video/1.mp4"
```

and another

```
 test.com [11/Dec/2019:16:47:01 -0800] "GET http://test.com/video/1.mp4"
```

which of the choices would you expect

* both events go to `sink-20191211-1647.log`
* first event go to `sink-20191211-0847.log` and second event go to `sink-20191211-0047.log`

?

**Comment by linshaoyong** [comment]
hi @a-rodin, thanks for the quick answer

I expect the first event go to sink-20191211-1647.log and second event go to sink-20191211-0047.log

something like this, when using elasticsearsh 
[10/Dec/2019:08:00:00 -0800]
[10/Dec/2019:16:00:00 +0000] 
[11/Dec/2019:00:00:00 +0800]
all write to index-2019.12.11 

my company has thousands of devices with different timezones and datacenter timezone is GMT+8
I want to use this timezone to parse output path
I will use aws_s3 sink in production, so I except vector can support this, not only file sink, thank you!

**Comment by a-rodin** [comment]
While we haven't implemented setting timezone explicitly, I think for this particular use case it is possible to modify the regex and timestamp specifier to just ignore the offset when parsing timestamp:

```toml
[transforms.test_transform]
regex = "^(?P<domain>.*) \\[(?P<timestamp>.*) (?P<utc_offset>.*)\\] (?P<others>.*)$"
[transforms.test_transform.types]
timestamp = "timestamp|%d/%b/%Y:%T"

[sinks.my_sink_id]
type = "file"
inputs = ["test_transform"]
path = "sink-%Y%m%d-%H%M.log"
```

This would parse the offset as a separate field and the timestamp would be parsed as `2019-12-11T16:47:01Z` (assuming that the timezone for the machine is UTC).

So the output file should be `sink-20191211-1647.log` with this config.
