### ISSUE TITLE
[opentelemetry source] Incorrect `message` when `body` is an `ArrayValue`

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#13926]
When running the otel-col and vector locally with the following configs...

opentelemetry-collector:
```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:9876

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://localhost:4318
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging,otlp,otlphttp]
```

vector:
```toml
data_dir = "/var/lib/vector/"

[api]
enabled = true

[sources.otel]
type = "opentelemetry"

[sources.otel.acknowledgements]

[sources.otel.grpc]
address = "0.0.0.0:4317"

[sources.otel.http]
address = "0.0.0.0:4318"

[sources.internal_metrics]
type = "internal_metrics"

[sinks.console]
inputs = ["otel.logs"]
target = "stdout"
type = "console"

[sinks.console.encoding]
codec = "json"

[sinks.console.healthcheck]
enabled = true

[sinks.console.buffer]
type = "memory"
max_events = 500
when_full = "block"

[sinks.metrics]
type = "prometheus_exporter"
inputs = [ "internal_metrics" ]
address = "0.0.0.0:9090"
```

Curling this input to the collector results in dropped values from the `body`, this behavior is seen both in Vector and the `logging` exporter from the otel-collector.

Input:
```json
{
  "resource_logs": [
    {
      "scope_logs": [
        {
          "log_records": [
            {
              "body": {
                "array_value": {
                  "values": [
                    {
                      "string_value": "string",
                      "int_value": 42,
                      "bool_value": true
                    }
                  ]
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

Output:
```json
{
  "dropped_attributes_count": 0,
  "message": [42],
  "observed_timestamp": "2022-08-10T20:06:01.143133Z",
  "timestamp": "2022-08-10T20:06:01.143133Z"
}
```
