### ISSUE TITLE
parse_key_value gets confused by brackets

### ISSUE THREAD

**Issue by tshepang** [vectordotdev/vector#13944]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When a value has a bracket, `parse_key_value` treats it like a key.

### Configuration

```toml
data_dir = "/tmp"

[sources.in]
 type = "file"
 include = ["/tmp/bar"]

[transforms.parse]
 inputs = ["in"]
 type = "remap"
 source = '''
   . = parse_key_value!(.message)
 '''

[sinks.out]
 inputs = ["parse"]
 type = "console"
 encoding.codec = "ndjson"
```

### Version

vector 0.23.3 (x86_64-unknown-linux-gnu af8c9e1 2022-08-10)

### Example Data
input
```
vlan_id="" ether_type=Unknown (0x0000) bridge_name="" bridge_display_name="" in_interface="Port8"
vlan_id="" ether_type=Unknown [0x0000] bridge_name="" bridge_display_name="" in_interface="Port8"
vlan_id="" ether_type=Unknown {0x0000} bridge_name="" bridge_display_name="" in_interface="Port8"
```
output
```json
{"":true}
{"":true}
{"(0x0000)":true,"bridge_display_name":"","bridge_name":"","ether_type":"Unknown","in_interface":"Port8","vlan_id":""}
{"[0x0000]":true,"bridge_display_name":"","bridge_name":"","ether_type":"Unknown","in_interface":"Port8","vlan_id":""}
{"bridge_display_name":"","bridge_name":"","ether_type":"Unknown","in_interface":"Port8","vlan_id":"","{0x0000}":true}
```
