### ISSUE TITLE
Allow reading of access_key in VRL for `aws_kinesis_firehose` source

### ISSUE THREAD

**Issue by tim-klarna** [vectordotdev/vector#14107]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Firehose access tokens can contain JWT or other authorization encoded information.

When multiple different Firehose's send data to vector clusters, we may need to differentiate between these, driving decisions such as where to route data, or how to parse it. We need to be able to read & parse the access_key to do so.

### Proposal

This feature is already available in the `splunk_hec` source: https://vector.dev/docs/reference/configuration/sources/splunk_hec/#store_hec_token

We propose to add it here too, making it consistent with the above.

### References

- Also related to #14106

**Comment by marcel-puchol-jt** [comment]
I tried to access to the `access_key` information using the following configuration:
```yaml
  sources:
    firehose:
      type: aws_kinesis_firehose
      address: 0.0.0.0:80
      access_keys: ["access1", "access2"]
      store_access_key: true
  transforms:
    parse_firehose:
      type: remap
      drop_on_abort: true
      drop_on_error: true
      inputs: ["firehose"]
      source: |
        .access_key = get_secret("aws_kinesis_firehose_access_key")
  sinks:
    console:
      type: console
      encoding:
        codec: native_json
      inputs:
        - parse_firehose
      target: stdout
```
but `access_key` is always `null`. Am I doing something wrong?
