### ISSUE TITLE
Timezone of path template

### ISSUE THREAD

**Issue by alippai** [vectordotdev/vector#14160]
### Problem

Maybe I just need to update my `vector` version, but using 0.16.1 when I want to use templated `path` settings for a file sink (https://vector.dev/docs/reference/configuration/sinks/file/#path) then it uses UTC instead of the local timezone.

I don't have a workaround yet, I didn't see VRL like `timezone = .t as Asia/Seoul` where `t` is the timestamp in the message (but I would prefer using the local system time+date, at least the possibility of `timezone = now() as Asia/Seoul` if you don't want to change the default behavior).

### Version

vector 0.16.1 unknown linux gnu

### References

- https://github.com/vectordotdev/vector/issues/14160

### Additional Context

Running vector in non-UTC environment, using template variables (date %Y%m%d)

**Comment by spencergilbert** [comment]
Have you tried setting https://vector.dev/docs/reference/configuration/global-options/#timezone?

**Comment by alippai** [comment]
Isn't the local timezone the default? I'll try it regardless

**Comment by spencergilbert** [comment]
Should take local 👍, curious if it makes a difference though.

**Comment by ahsandar** [comment]
> https://github.com/vectordotdev/vector/issues/14160#issuecomment-1231615711

this doesn't take affect , facing same issue the path is always set to UTC regardless of what the local TZ is

**Comment by Jazznight** [comment]
> https://github.com/vectordotdev/vector/issues/14160#issuecomment-1231615711
 
0.25.1 facing the same issue. global option `timezone` not take effect for path template of `sinks/file` even if I set specific `Asia/Singapore` instead default `local`

**Comment by ahsandar** [comment]
any update on this , it stops us from migrating fully from fluentd to vector

**Comment by easayliu** [comment]
> 您是否尝试过设置https://vector.dev/docs/reference/configuration/global-options/#timezone？

set timezone: Asia/Shanghai
but it does not work .time also is UTC.
```yaml
timezone: Asia/Shanghai
sources:
  kubernetes_logs:
    type: kubernetes_logs
    timezone: Asia/Shanghai
```

**Comment by easayliu** [comment]
> > 您是否尝试过设置[https://vector.dev/docs/reference/configuration/global-options/#timezone？](https://vector.dev/docs/reference/configuration/global-options/#timezone%EF%BC%9F)
> 
> 设置时区：亚洲/上海 但它不起作用。时间也是UTC。
> 
> ```yaml
> timezone: Asia/Shanghai
> sources:
>   kubernetes_logs:
>     type: kubernetes_logs
>     timezone: Asia/Shanghai
> ```

```yaml
  my_sink_id:
    type: clickhouse
    inputs:
      - kubernetes_logs
    database: ***
    endpoint: ***
    table: ***
    compression: gzip
    skip_unknown_fields: true
    auth:
      user: ***
      password: ***
      strategy: basic
    encoding: 
      timestamp_format: unix
```

 change the setting ,i got the right time. but the time is 2023-01-11 11:15:38.0
