### ISSUE TITLE
Regression in metrics in `vector top` 

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#14228]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

There appears to be a regression in the metrics reported by `vector top` after 579d49882775d00b5297a41adb5faaac2ba2898a. The metrics increment once, but then stay static. I did see the rates go negative sometimes so I'm wondering if the metrics were incremented but immediately decremented.

The `prometheus_exporter` sink appears to be reporting the correct metrics, so this may be something specific to how `vector top` queries them.

### Configuration

```text
[api]
enabled = true

[sources.source0]
type = "internal_metrics"

[sinks.sink0]
inputs = ["source0"]
target = "stdout"
type = "console"
encoding.codec = "json"

[sinks.sink1]
inputs = ["source0"]
type = "prometheus_exporter"
address = "0.0.0.0:9898"
```

### Version

579d49882

### References

* 579d49882775d00b5297a41adb5faaac2ba2898a

**Comment by 3g0r** [comment]
It also affects the processing of metrics from the source `internal_metrics`.

example:
```
sources:
  internal_metrics_src:
    type: 'internal_metrics'
    
  kafka_src:
    type: "kafka"
    bootstrap_servers: "kafka-service"
    group_id: test
    auto_offset_reset: earliest
    topics:
      - test
      
transforms:

  filter_main_output_activity_metrics:
    type: filter
    inputs: ['internal_metrics_src']
    condition: .tags.component_id == "blackhole" && (.name == "component_received_events_total" || .name == "component_sent_events_total")

  map_main_output_metrics_to_logs:
    type: metric_to_log
    inputs: ['filter_main_output_activity_metrics']

  route_main_output_activity:
    type: route
    inputs:
      - map_main_output_metrics_to_logs
    route:
      incoming: .name == "component_received_events_total"
      outgoing: .name == "component_sent_events_total"

  throttle_main_output_incoming_activity:
    type: throttle
    inputs: ['route_main_output_activity.incoming']
    threshold: 1
    window_secs: 10

  throttle_main_output_outgoing_activity:
    type: throttle
    inputs: ['route_main_output_activity.outgoing']
    threshold: 1
    window_secs: 10

sinks:
  file_sink:
    type: file
    inputs:
      - throttle_main_output_incoming_activity
      - throttle_main_output_outgoing_activity
    compression: none
    idle_timeout_secs: 5
    encoding:
      codec: json
      only_fields:
        - counter.value
    path: /tmp/{{name}}-%H-%M-%S
    
  blackhole:
    type: blackhole
    inputs: ['kafka_src']
```
