### ISSUE TITLE
Update approach for pass-thru Datadog API keys to rely on event metadata

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#14380]
Currently the pass-thru approach for Datadog API keys for events received by the `datadog_agent` source and sent by a `datadog_*` sink is to:

* Store the API key that was sent with the events received by the `datadog_agent` source in event metadata, unless `store_api_key` is set to `false`
* If the event metadata has a stored API key, use this key in the `datadog_*` sinks, otherwise fall back to the configured `default_api_key`

This is confusing to users as they often don't realize that it is using the API key sent by the Datadog Agent, by default, and then struggle to override it in Vector.

Instead, it would be clearer to:

* Always store the Datadog API key in the event metadata in the `datadog_agent` source (deprecate and drop `store_api_key`)
* Add a new templatable `api_key`  option to `datadog_*` sinks. If users want to use the stored API key, they can set this to `{{ %datadog_agent.api_key }}` to use the one added to the event metadata by the source
* Deprecate and drop `default_api_key` from these sinks, making `api_key` a required option

Thus a full config might look like:

```toml
[sources.source0]
type = "datadog_agent"
address = "0.0.0.0:8080"
multiple_outputs = true

[sinks.sink0]
type = "datadog_logs"
inputs = ["source0.logs"]
api_key = "{{ %datadog_agent.api_key }}"
```
