### ISSUE TITLE
Batch sizing for aws_s3 sink  does not work

### ISSUE THREAD

**Issue by rmehlitz** [vectordotdev/vector#14416]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector pushes only small files to s3 and the configuration of the buffer and batch properties seem to have no effect. 

**Expectation**: If the 'batch.max_events' and 'batch.timeout_secs' properties are set, I expect vector to push files to s3 having that max_event size or wait until the timeout is reached. 

What I experience is, that it does not matter what I configure here, there are hundreds of files pushed every minute and they have a size of 300-500KB including 400-600 records per file. I tried to increase and decrease the batch properties and also the buffer properties but nothing changed. 

We consume the data from a Kafka topic that has 60 partitions. Does the batching maybe depend on the Kafka partitioning?

Please see the config below. If this is not a bug but I made a configuration mistake please let me know.
Thanks for your help.

### Configuration

```text
data_dir = "/data/vector"
[sources.kafka_in_aiven]
type = "kafka"
topics = ["testTopic"]
bootstrap_servers = "some-bootstrap-servers"
group_id = "kafka-test-ingester"
auto_offset_reset = "latest"
tls.enabled = true
... security configs ...
decoding.codec = "json"
             
[transforms.timestamp_to_ingestion]
type = "remap"
inputs = ["kafka_in_aiven"]
source = '''
    .timestamp = now()
'''

[sinks.s3]
type = "aws_s3"
inputs = [ "timestamp_to_ingestion" ]
encoding.codec = "json"
bucket = "some-bucket-path"
key_prefix = "data-path/year=%Y/month=%m/day=%d/hour=%H/"
auth.assume_role = "aws-arn"
filename_extension = "json.gz"
storage_class = "ONEZONE_IA"
batch.timeout_secs = 120
batch.max_events = 25000
buffer.max_events = 50000
framing.method = "newline_delimited
```

### Version

with k8s and docker: timberio/vector:0.24.0-distroless-libc

**Comment by fuchsnj** [comment]
> Does the batching maybe depend on the Kafka partitioning?

Batching shouldn't depend on the Kafka partitioning. It should be just the batch settings you set, and it's partitioned by the `key_prefix` you set, but that seems to only change once per hour.

I did notice you aren't setting the `max_bytes`, which defaults to 10Mb for the S3 sink. You are seeing files that are 300-500 KB, but this setting is the  _uncompressed_ size, and what you are seeing is the gzip compressed size, so you are likely hitting the size limit here.

Try setting the `max_bytes` to a higher value, if that doesn't help we can keep investigating what might be going on here.

**Comment by shomilj** [comment]
I'm also having a similar issue and can't seem to resolve it despite setting all there parameters (timeout_secs, max_bytes, max_events) to very large numbers. Here's my config:

```
  aws_s3:
    type: aws_s3
    inputs:
      - application_logs
    batch:
      timeout_secs: 1800 # 30 Minutes
      max_bytes: 31457280 # 30 MB
      max_events: 100000000 # 100,000,000 Events
    bucket: '${VECTOR_DATA_BUCKET}'
    key_prefix: '${VECTOR_LOG_STORAGE_PREFIX}{{ file }}/'
    compression: gzip
    encoding:
      codec: text
    region: '${VECTOR_AWS_REGION}'
    healthcheck:
      enabled: true
```

Any indication as to whether this is an internal bug or a configuration error?
