### ISSUE TITLE
Add count configuration to Reduce transform

### ISSUE THREAD

**Issue by SefiShalom** [vectordotdev/vector#14498]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

When using reduce transform, we would like to have the ability to collapse every N log events into one log event after`group_by`.

i.e. consider this Reduce configuration:
```
transforms:
  my_transform_id:
    type: reduce
    inputs:
      - my-source-or-transform-id
    group_by:
      - request_id
```

After grouping events by `request_id`, when reaching the maximum amount of event in that group, complete the event and flush it.

### Attempted Solutions

I was suggested to use another transform to count the events which will affect the performance.

### Proposal

Similar to `expire_after_ms`, count a maximum or certain amount of events for a combined event to be considered complete.
