### ISSUE TITLE
Zero config metric parsing

### ISSUE THREAD

**Issue by Jeffail** [vectordotdev/vector#1471]
It would be very neat if we were able to document a structured log format that when parsed by an empty `log_to_metric` transform would result in properly parsed metrics. For some users it will be just as easy for them to format their log output to play nice with our spec than it would be to configure Vector to parse a custom format, and makes the configuration much cleaner.

If we were to settle on a log format, perhaps for counters it would look something like:

```json
{
  "type": "counter",
  "name": "foo_total",
  "value": 21,
  "tags": {
    "host": "bar",
    "environment": "prod"
  }
}
```

Then we could change `log_to_metric` so that if the field `metrics` is left empty then we refer to the field `type` and automatically parse out a metric based on that. Failures can be dropped with a debug or trace level log.

That way in our docs we can give the option of configuring Vector to work with the format you already have versus structuring your logs to have it work automatically.

If we go down this route then we should probably have a long hard think about the format we standardize on. The future I want to live in would accommodate this:

```toml
[sources.plain_logs]
  type = "stdin"

[transforms.parse_metrics]
  type = "log_to_metric"
  inputs = ["plain_logs"]
  # Automatically drops any logs that don't fit the default spec

[transforms.parse_spans]
  type = "log_to_span" # Maybe one day
  inputs = ["plain_logs"]
  # Automatically drops any logs that don't fit the default spec

[transforms.sample_logs]
  type = "sampler"
  inputs = ["plain_logs"]
  rate = 10

[sinks.logs]
  type = "kafka"
  inputs = ["sample_logs"]
  bootstrap_servers = ["10.14.22.123:9092", "10.14.23.332:9092"]
  key_field = "id"
  topic = "foo"
  encoding = "json"

[sinks.metrics]
  type = "prometheus"
  inputs = ["parse_metrics"]
  address = "0.0.0.0:9598"
  namespace = "foo"

[sinks.dist_tracing]
  type = "jaeger"
  inputs = ["parse_spans"]
  namespace = "foo"
  address = "localhost:6831"
```

Maybe food for thought as well is the possibility that any sink that only supports metrics might automatically behave this way when given a log, making it even simpler:

```toml
[sources.plain_logs]
  type = "stdin"

[transforms.sample_logs]
  type = "sampler"
  inputs = ["plain_logs"]
  rate = 10

[sinks.logs]
  type = "kafka"
  inputs = ["sample_logs"]
  bootstrap_servers = ["10.14.22.123:9092", "10.14.23.332:9092"]
  key_field = "id"
  topic = "foo"
  encoding = "json"

[sinks.metrics]
  type = "prometheus"
  inputs = ["plain_logs"]
  address = "0.0.0.0:9598"
  namespace = "foo"

[sinks.dist_tracing]
  type = "jaeger"
  inputs = ["plain_logs"]
  namespace = "foo"
  address = "localhost:6831"
```
