### ISSUE TITLE
Unit testing : YAML object not working as expected (data did not match any variant of untagged enum TestInputValue)

### ISSUE THREAD

**Issue by RaphaelLEMAS** [vectordotdev/vector#14729]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm am trying to unit test a simple filter using yaml test file. However its seems that my input log is not parsed correctly and I get this error (that I don't understand well) : 

<img width="875" alt="image" src="https://user-images.githubusercontent.com/52014731/194031909-ac8ffd82-4707-47ce-b7be-e05d133cfffc.png">

I precise that the filter works perfectly in a real use case.

### Configuration

```text
- Configuration file:

log_level_filter:
  type: filter
    inputs:
      - log_router.my_route
    condition: to_int!(.json_log.level) >= 20


- Test file : 
```Yaml
tests:
  - name: log should be dropped if level < 20
    inputs:
      - insert_at: "log_level_filter"
        type: "log"
        log_fields:
          json_log:
            level: 10 
    no_outputs_from:
      - "log_level_filter"

  - name: log should be forwarded if level >= 20
    inputs:
      - insert_at: "log_level_filter"
        type: "log"
        log_fields:
          json_log:
            level: 30 
    outputs: 
      - extract_from: "log_level_filter"
```
```


### Version

vector 0.24.1 (x86_64-apple-darwin 8935681 2022-09-12)

### Debug Output

```text
Running tests
2022-10-05T09:59:34.421286Z ERROR vector::unit_test: Failed to execute tests:
data did not match any variant of untagged enum TestInputValue for key `tests.inputs.log_fields.json_log`.
```

**Comment by jszwedko** [comment]
Hi @RaphaelLEMAS !

I think you are running into: https://github.com/vectordotdev/vector/issues/9386

You can use this as a workaround:

```yaml
transforms:
  log_level_filter:
    type: filter
    inputs:
      - log_router.my_route
    condition: to_int!(.json_log.level) >= 20
tests:
- name: log should be dropped if level < 20
  inputs:
    - insert_at: "log_level_filter"
      type: "log"
      log_fields:
        "json_log.level": 10
  no_outputs_from:
    - "log_level_filter"

- name: log should be forwarded if level >= 20
  inputs:
    - insert_at: "log_level_filter"
      type: "log"
      log_fields:
        "json_log.level": 30
  outputs:
    - extract_from: "log_level_filter"
```

I'll close this out as a duplicate of the other issue, but let me know if that doesn't work.
