### ISSUE TITLE
change sink healthchecks to retry multiple times, giving time for downstream services to start

### ISSUE THREAD

**Issue by cdepillabout** [vectordotdev/vector#15038]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I have a simple `vector.toml` with a single `loki` sink:

```toml
...

[sinks.loki_output]
type = "loki"
inputs = ["my_transform"]  
endpoint = "http://localhost:3100"
encoding.codec = "json"
healthcheck = true
labels.bar = "{{ bar }}"
labels.foo = "{{ foo }}"
```

Sometimes when I run `vector`, `loki` isn't finished starting up.  So the healthcheck for vector's loki sink fails.

I'd like to be able to start `vector` and `loki` at the same time, and for `vector` to wait a little bit for `loki` to finish starting up, instead of just immediately giving up on the `loki` healthchecks.

### Attempted Solutions

I have just disabled the healthchecks for the loki sink, but this is not ideal.  I _do_ want the healthchecks, but I just want a little leeway before the healthchecks finally fail.

### Proposal

It would be nice if `vector` would retry the health check a few times (ideally with some sort of exponential backoff), before fully failing.

### Version

vector 0.24.1 (x86_64-unknown-linux-gnu)
