### ISSUE TITLE
[Epic] `log_to_metric` polishing

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#15332]
# Summary:

The `log_to_metric` transform continues to be a strong option for users wanting to reduce and control costs while still surfacing useful information in a more cost efficient way. However, the current UX of the transform is lacking and frequently raised as a point of confusion or overly verbose configuration.

A recent example of redundant tagging configuration:

> I have to add the tags for each metric I extract, where it would be useful to have the tags added for all metrics extracted in the block.

```toml
[transforms.elb_to_metric]
type = "log_to_metric"
inputs = [ "split_on_status.ok" ]

  [[transforms.elb_to_metric.metrics]]
  type = "counter"
  field = "elb_status_code"
  name = "response_code_total"
  namespace = "elb"

    [transforms.elb_to_metric.metrics.tags]
    elb = "{{elb}}"
    user_agent = "{{user_agent}}"

  [[transforms.elb_to_metric.metrics]]
  type = "counter"
  field = "client_host"
  name = "client_host_total"
  namespace = "elb"

    [transforms.elb_to_metric.metrics.tags]
    elb = "{{elb}}"
    user_agent = "{{user_agent}}"
```

# Related issues:

- https://github.com/vectordotdev/vector/issues/7565
- https://github.com/vectordotdev/vector/issues/10934
- https://github.com/vectordotdev/vector/issues/14744
