### ISSUE TITLE
Gelf codec encoder send timestamp as integer but graylog expects float

### ISSUE THREAD

**Issue by stavcev** [vectordotdev/vector#15362]
### Vector Version
vector 0.26.0 (x86_64-unknown-linux-musl 5d610b6 2022-11-25)

### Example Data
For example, my test message:
```
{
  "host": "host",
  "short_message": "short message",
  "timestamp": "2022-11-25T13:10:56.962200925Z",
  "version": "1.1"
}
```

### Problem
As part of https://github.com/vectordotdev/vector/issues/4868 , PR https://github.com/vectordotdev/vector/pull/13333 submitted GELF encoding support.

I want to send logs contains timestamp field to graylog using encondig.gelf. 

To send this timestamp in graylog i need to do one of the following:
1.  Configure encoder parameter in socket sink
`encoding.timestamp_format: "unix"`
2. Parse timestamp field with vrl: 
```
  transforms:
    gelf:
      type: remap
      inputs: ["kubernetes_logs"]
      source: |-
        .timestamp = to_unix_timestamp!(.timestamp)
```

In this cases logs sends correctly, but **without milliseconds**:
-   Stdout: ` "timestamp": 1669381856,`
-   Graylog shows this filed:  `timestamp: 2022-11-25T13:10:56.000Z `

**I don't want to lose milliseconds** and i tried vrl parsings:
1. `.timestamp = to_unix_timestamp!(.timestamp, unit: "milliseconds")`
In this case graylog can't recognize and skipping logs.
2. `.timestamp = to_float(to_timestamp!(.timestamp))` - it must be true way, but it fails.
In this case i get vector ERRORs:
`2022-11-28T10:57:11.468111Z ERROR sink{component_kind="sink" component_id=gelf_out component_type=socket component_name=gelf_out}: vector::internal_events::codecs: Failed serializing frame. error=LogEvent contains a value with an invalid type. field = "timestamp" type = "float" expected type = "timestamp or integer" error_type="encoder_failed" stage="sending" internal_log_rate_limit=true `

### What's Happening
Gelf docs: https://docs.graylog.org/docs/gelf
**Quote** gelf docs : _**"timestamp - number with optional decimal places for milliseconds"**_ - I.e float.

Sending to graylog ` "timestamp": 1669381856.123,` - works correctly
And graylog shows this field `timestamp: 2022-11-25T13:10:56.123Z `

But encoder check this field as int:
https://github.com/vectordotdev/vector/blob/d2f2ff3a667f7e027754d156fe4b1e369038fdf5/lib/codecs/src/encoding/format/gelf.rs#L178-L181

I think it's necessary to chage is_integer() to is_float() or just add is_float() 

### Expected Behavior
When i parse timestamp as float encoder.gelf not fails.

**Comment by jszwedko** [comment]
Hi @stavcev !

Thanks for this report. As a workaround you can convert the timestamp to Vector's internal timestamp representation via `to_timestamp` in your `remap` transform. This should correctly encode, including the milliseconds.

**Comment by stavcev** [comment]
Hello @jszwedko!
This workaround not working for me.
My conf:
```
  transforms:
    gelf:
      type: remap
      inputs: ["kubernetes_logs"]
      source: |-
        .timestamp_from_log = to_string!(.timestamp)
        .timestamp=to_timestamp!(.timestamp)
  sinks:
    gelf_out:
      type: "socket"
      inputs: ["gelf"]
      address: "ip:port"
      mode: "tcp"
      framing:
        method: "character_delimited"
        character_delimited:
          delimiter: "\0"
      encoding:
        codec: 'gelf'
```
In this case we have different timestamps in graylog:

> timestamp: 2023-01-10T13:15:30.**092**Z
> timestamp_from_log: 2023-01-10T13:15:30.**056**055461Z

It happening beacause graylog expects timestamp as "number with optional decimal places for milliseconds" if field not number graylog set new timestamp.

**Comment by jszwedko** [comment]
Ah, interesting, thanks @stavcev . It seems like we should be truncating the timestamp to milliseconds then, before sending it to Greylog. As an additional workaround I think you could truncate the string:

```
to_timestamp!(truncate("2023-01-10T13:15:30.056055461Z", 23) + "Z")
```

Which would return a timestamp with only millisecond resolution which Greylog should be able to accept.

**Comment by jszwedko** [comment]
Hrm, that's weird. Does that mean it cannot receive timestamps with milliseconds? Can you give an example of a valid timestamp that is accepted by Graylog?

**Comment by stavcev** [comment]
From my first message:
To send this timestamp in graylog i need to do one of the following:
1.  Configure encoder parameter in socket sink
`encoding.timestamp_format: "unix"`
2. Parse timestamp field with vrl: 
```
  transforms:
    gelf:
      type: remap
      inputs: ["kubernetes_logs"]
      source: |-
        .timestamp = to_unix_timestamp!(.timestamp)
```

In this cases logs sends correctly, but **without milliseconds**:
-   Stdout: ` "timestamp": 1669381856,`
-   Graylog shows this filed:  `timestamp: 2022-11-25T13:10:56.000Z `
