### ISSUE TITLE
Omitting Kubernetes fields in source

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#15489]
### Discussed in https://github.com/vectordotdev/vector/discussions/15485

<div type='discussions-op-text'>

<sup>Originally posted by **ottramst** December  7, 2022</sup>
Hey all!

When upgrading from 0.24 to 0.26, we seemed to have lost the option to omit specific fields in the `kubernetes_logs` source.

In 0.24 it was possible to omit like so:
```
sources:
  kubernetes_logs:
    type: kubernetes_logs
    namespace_annotation_fields:
      namespace_labels: ""
```

In 0.26 it gives the next error
```
"Configuration error.","error":"Invalid field path \"\" for key `sources.kubernetes_logs`"
```

I would want to avoid implementing a remap for this, because it will just raise the resource cost on the Vector agent in Kubernetes.

Any advice here?

Many thanks!</div>
