### ISSUE TITLE
Using Grafana Mimir as a `prometheus_remote_write` sink fails health chekc

### ISSUE THREAD

**Issue by runiq** [vectordotdev/vector#15664]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm currently using Grafana Mimir as a remote write destination for metrics. Its remote write endpoint is [`/api/v1/push`](https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#remote-write) and its healthcheck endpoint is [`/ready`](https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#readiness-probe).

When I configure the endpoint that enables remote write, the Mimir sink fails Vector's healthcheck, because Vector simply appends `/ready` to the configured endpoint (resulting in `/api/v1/push/ready`). When I don't use a path, the Mimir sink passes the health check, but remote writes don't work.

So I can have either working healthchecks with Mimir, or a functioning remote write endpoint, but not both at the same time. :upside_down_face: 

### Configuration

```yaml
sources:
  internal_metrics:
    type: "internal_metrics"
    scrape_interval_secs: 15

sinks:
  mimir:
    inputs:
      - "internal_metrics"
    type: "prometheus_remote_write"
    # This works as a remote write endpoint, but not for health checks...
    endpoint: http://localhost:9009/api/v1/push
    # ...while this works for health checks, but not as a remote write endpoint
    #endpoint: http://localhost:9009
```

### Version

vector 0.26.0 (x86_64-unknown-linux-gnu c6b5bc2 2022-12-05)
