### ISSUE TITLE
include container image_id in kubernetes_logs event metadata

### ISSUE THREAD

**Issue by mmerickel** [vectordotdev/vector#15808]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

The container image_id field contains the actual sha of the image used, not just the tag. Note below the container id, and image fields are both recorded right now by vector but not the imageID.

```yaml
  containerStatuses:
  - containerID: containerd://8ab1634e42f9adff74fa6919873701902065afb651b1b0bd871a3d8ff65a2a52
    image: gcr.io/istio-release/pilot:1.14.1
    imageID: gcr.io/istio-release/pilot@sha256:1e7b63c09af457b93c17d25ef4e6aee96b5bb95f087840cffd7c4bb2fe8ae5c6
    lastState: {}
    name: discovery
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-12-22T23:27:12Z"
```

### Proposal

Add `kubernetes.container_image_id` to the event metadata.

### Version

0.26.0
