### ISSUE TITLE
Enabling disk buffers also caused back pressure to the edge

### ISSUE THREAD

**Issue by namm2** [vectordotdev/vector#15900]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I've tried to enable Vector aggregator's blackhole disk with disk buffers but it poses an unexpected behavior: Whenever there are container logs generated, Vector Agent's buffer at Vector sink had a lot of events in buffer, even when disk buffer at Vector aggregator's blackhole sink isn't full yet. In contrast, when Vector aggregator's blackhole sink uses memory buffers this behavior didn't show up.

If I understand correctly, it means Vector aggregator applied back pressure to the edge (Vector agent's Vector sink in this case), but it should do this _only_ when Vector aggregator's disk buffer is full and `buffer.when_full` is block. My expectation with disk buffers would be fast and _not_ causing back pressure to the edge like this

### Configuration

```text
Development system:
- GKE v1.24
- node specs: t2d-standard-8 (8 CPUs, 32GB memory)
- persistent volume: 100GiB pd-ssd

Vector Helm chart values

<details>
<summary>Vector Agent configs</summary>


customConfig:
  data_dir: "/vector-data-dir"
  expire_metrics_secs: 3600
  api:
    enabled: true
    address: 0.0.0.0:8686
    playground: false
  sources:
    kubernetes:
      type: kubernetes_logs
      max_line_bytes: 131072
      delay_deletion_ms: 3600000  # value in millis => 1 hour
      glob_minimum_cooldown_ms: 2000  # value in millis

  sinks:
    vector-aggregator:
      type: vector
      acknowledgements:
        enabled: false
      compression: false
      buffer:
        max_events: 100000
      inputs:
        - kubernetes
      address: vector-aggregator.vector.svc.cluster.local:9088

</details>

<details>
<summary>Vector aggregator configs</summary>

```yaml
persistence:
  enabled: true
  size: "100Gi"

customConfig:
  data_dir: "/vector-data-dir"
  api:
    enabled: true
    address: 0.0.0.0:8686
    playground: false
  timezone: Etc/UTC
  sources:
    kubernetes_v2:
      type: vector
      address: 0.0.0.0:9088

  sinks:
    blackhole:
      type: blackhole
      inputs:
        - kubernetes_v2
      acknowledgements:
        enabled: false
      buffer:
        type: disk
        max_size: 80000000000 # 80GB
        when_full: drop_newest
      rate: 100000
      print_interval_secs: 0
```
</details>

Create a k8s job to generate random logs:
<details>
<summary>Dummy logs job</summary>

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dummy-logs-json
  labels:
    component: test
spec:
  parallelism: 3
  backoffLimit: 1
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        name: dummy-logs-json
    spec:
      containers:
      - name: flog
        image: mingrammer/flog
        imagePullPolicy: IfNotPresent
        command:
        - flog
        - -f
        - json
        - -b
        - "524288000"
        - -s
        - "300ms"
      restartPolicy: Never
```
</details>
```


### Version

0.24.2

### Debug Output

_No response_

### Example Data

Prometheus metrics: ```sum(vector_buffer_events) by (pod)``` 
<img width="1596" alt="Screenshot 2023-01-11 at 08 27 41" src="https://user-images.githubusercontent.com/46129063/211757794-39114c60-afc5-4e5d-9bc8-d18a4bbf1e53.png">

Vector events out metrics: ```sum(rate(vector_component_sent_events_total{component_kind="sink", }[$__rate_interval])) by (component_id)```
<img width="1596" alt="Screenshot 2023-01-11 at 08 27 09" src="https://user-images.githubusercontent.com/46129063/211758157-37f04cc9-2672-4cc8-89d1-ee6be537920f.png">

Vector persistent volume metrics:
<img width="1597" alt="Screenshot 2023-01-11 at 08 26 31" src="https://user-images.githubusercontent.com/46129063/211758426-8d07155f-708d-4755-8f1b-94a61c2f0b5c.png">

Persistent volume IOPS:
<img width="1589" alt="Screenshot 2023-01-11 at 08 50 52" src="https://user-images.githubusercontent.com/46129063/211760810-8bf65b78-a0b2-4364-8101-a057de2d448d.png">


### Additional Context

Topology:

```
[Kubernetes logs] -> [Vector Agent] ----> [Vector Aggregator] -> [Blackhole]
```

### References

_No response_
