### ISSUE TITLE
How can i have GeoIP city and ASN together ?

### ISSUE THREAD

**Issue by mhf-ir** [vectordotdev/vector#15935]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

```toml
[enrichment_tables.geoip_table]
type = "geoip"
path = "/path/to/GeoLite2-City.mmdb" 

# How can i add ASN also
```

### Attempted Solutions

Ignore one of them, you lost ASN info or City info !

### Proposal

Add ASN and City in different path.

### Version

timberio/vector:0.26.0-alpine

**Comment by spencergilbert** [comment]
Hey @mhf-ir,

Today you should be able to create two tables like:

```toml
[enrichment_tables.city]
type = "geoip"
path = "/path/to/GeoLite2-City.mmdb" 

[enrichment_tables.asn]
type = "geoip"
path = "/path/to/GeoLite2-ASN.mmdb" 
```

Then enrich with both enrichment tables.
