### ISSUE TITLE
Support Loki label expansion without prefix

### ISSUE THREAD

**Issue by zigmund** [vectordotdev/vector#15990]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently Vector support label expansion, but prefix have to be set: https://vector.dev/docs/reference/configuration/sinks/loki/#label-expansion

But we need to set bunch of pre-unknown labels to Loki labels. Something like that:
source:
```
labels: {
  foo: "bar",
  unknown: "baz"
}
```
to Loki labels:
```
labels:
  foo: "bar"
  unknown: "baz"
```

### Attempted Solutions

Tried this with no luck:
```yaml
      loki:
        type: loki
        labels:
          "*": "{{ labels }}"
```

### References

#9549

### Version

vector 0.26.0 (aarch64-unknown-linux-musl c6b5bc2 2022-12-05)

**Comment by spencergilbert** [comment]
I thought I remembered discussing some reason this wasn't support in https://github.com/vectordotdev/vector/pull/12041 but there's nothing there 🤔 

My immediate concerns would be accidental cardinality for Loki if an event came through with _way_ more labels than you anticipated. Perhaps more control is needed than just a `*` wildcard, I don't know if regex would be feasible here - but maybe something to consider?

Regardless, I'll add it to our backlog and we're always happy to guide a contributor PR!

**Comment by zigmund** [comment]
I don't think that filter logic is needed on sink side, since all that can be done on transform stage with remap, including regex.

**Comment by zigmund** [comment]
Also, with or without prefix - possibility of high cardinality is the same, I think.

**Comment by spencergilbert** [comment]
Yeah, today the risk exists but it's probably _less_ risky to match on a specific subset (`pod_*`) vs _anything_. 

> 
I don't think that filter logic is needed on sink side, since all that can be done on transform stage with remap, including regex.

Wouldn't that be true today, use a `remap` to append all the labels you'd want to use and then use the existing expansion option? Maybe I'm misunderstanding.

**Comment by spencergilbert** [comment]
Sorry, I think I misunderstood one of your previous messages with regards to filtering at the source. It could be handy as a "shortcut" but not strictly necessary to resolve this specific issue.

I don't have any reservations on expanding the existing support as-is so it can take `*` without any prefix - but I'm still keen on avoiding footguns wherever possible.

**Comment by zigmund** [comment]
OK, may be you can advice the method to solve the case? Expand object (few unknown at config time labels) to Loki labels without prefix.

**Comment by spencergilbert** [comment]
I don't think the prefix-less labels are possible with the current code. In case I'm misunderstanding, do you have some examples of "before and after" for how you wanted to see them read and included?

**Comment by zigmund** [comment]
We use "namespaced" labels in Kubernetes:
```json
{
  "org.company.branch.name": "feature-foo",
  "org.company.deploy.release": "release-2",
  "org.company.unknown.label": "bar-baz"
}
```

All that labels exposed in logs, metrics, traces, etc without `org.company.` and `.` replaced with `_`.
For example, metrics:
`kube_pod_labels{branch_name="feature-foo", deploy_release="release-2", unknown_label="bar-baz"}`

Same in Loki:
`{branch_name="feature-foo", deploy_release="release-2", some_unknown_label="bar-baz"}`

We are trying to replace Promtail, where Kubernetes to Loki label mapping looks like this:
```
          - action: labelmap
            regex: __meta_kubernetes_pod_label_org_company_(.+)
```

Also, apart from Loki we are using Graylog, and that's how remap looks for that case:
```
          for_each(keys!(.kubernetes.pod_labels)) -> |i, label| {
            if starts_with(label, "org.company.") {
              out = set!(out, [replace(replace(label, "org.company.", ""), ".", "_")], get!(.kubernetes.pod_labels, [label]))
            }
          }
```

**Comment by spencergilbert** [comment]
Ah yeah - understood, I don't think there are any workarounds I can think of that don't require ahead-of-time knowledge of what all the labels would be.

**Comment by hargut** [comment]
Hello together,

I've prepared a PR to allow the usage of `*` within the labels section. This allows, for example, to solve dynamic tagging when reading Azure Diagnostic Logs from Eventhubs through Kafka. For testing a `http` source was used.

[Reference](https://github.com/grafana/loki/issues/7782) related Loki/Fluentd issue.

```toml
[sources.http]
type = "http_server"
address = "0.0.0.0:7000"
encoding = "json"

[transforms.dynamic_label]
type = "remap"
inputs = ["http"]
#.id = "/subscriptions/0000000-0000-0000-0000-00000000000/resourceGroups/super-special-infra/providers/Microsoft.Web/sites/with-incredible-function"
source = '''
id_arr, err = split(.id, "/")
if err != null {
  id_arr = []
}

.dynamic_labels = {}
for_each(id_arr) -> |idx, list_val| {
  if contains(to_string(idx / 2), ".5") {
    result_val, err = get(id_arr, [idx + 1])
    if err != null {
      .error.get = err
    }
    res, err = set(.dynamic_labels, [list_val], result_val)
    if err != null {
        .error.set = err
    }
    .dynamic_labels = res
  }
}
'''

[sinks.loki]
type = "loki"
inputs = [ "dynamic_label" ]
endpoint = "http://localhost:3100"
remove_label_fields = true
```
