### ISSUE TITLE
Replace with capture groups not working

### ISSUE THREAD

**Issue by r4zr1** [vectordotdev/vector#16048]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi!

The Replace function with capture groups is not working as intended.
I attempted to follow the example provided in the documentation (https://vector.dev/docs/reference/vrl/functions/#replace-examples-replace-with-capture-groups), but the value in `.test` key is empty.

### Configuration

```text
[sources.my_source_id]
type = "stdin"

[transforms.extend]
type = "remap"
inputs = ["my_source_id"]
source = '''
	.test = replace!(.message, r'foo(?P<num>\d+)bar', "$num")
'''

[sinks.file]
type = "file"
inputs = [ "extend" ]
compression = "none"
path = "/tmp/test-%Y-%m-%d.log"
  [sinks.file.encoding]
  codec = "json"
```

### Version

0.27.0

### Example Data

input: `foo123bar`
output: `{"host":"4084986710ea","message":"foo123bar","source_type":"stdin","test":"","timestamp":"2023-01-20T16:12:53.055189258Z"}`

**Comment by spencergilbert** [comment]
Hey @r4zr1 - it looks like `$num` is being interpolated as an environment variable. You should see the following log from Vector as it starts (at least I do on my system)

```text
023-01-20T16:34:06.716109Z  WARN vector::config::loading: Unknown env var in config. name = "num"
```

You can escape that behavior with an additional `$`

```toml
[sources.my_source_id]
type = "stdin"

[transforms.extend]
type = "remap"
inputs = ["my_source_id"]
source = '''
    .test = replace!(.message, r'foo(?P<num>\d+)bar', "$$num")
'''

[sinks.file]
type = "file"
inputs = [ "extend" ]
compression = "none"
path = "/tmp/test-%Y-%m-%d.log"
  [sinks.file.encoding]
  codec = "json"
```

As an aside it works directly in VRL because there's no environment variable interpolation prior to running, that only happens when Vector is loading the config - so running `vector vrl` the example works:

```shell
$ replace(.message, r'foo(?P<num>\d+)bar', "$num")
"123"
```

Please let me know if this doesn't solve your problem!

[Ref](https://vector.dev/docs/reference/configuration/#escaping)
