### ISSUE TITLE
VRL: strange filter behaivor

### ISSUE THREAD

**Issue by inatale** [vectordotdev/vector#16214]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi team!
We are using vector to filter high severity events  (warning, error) from other events stream. Filter works correcly for filtering high severity events:
`[transforms.critical_logs]
type = "filter"
inputs = [ "vector"]
condition = '.source_type == "syslog" && includes(["err", "warning"], .severity)'`

But not applying to filter stream excluding warning and error:
`[transforms.info_logs]
type = "filter"
inputs = [ "vector"]
condition = '.source_type == "syslog" && includes(["err", "warning"], .severity)'`
or we tried even:
`[transforms.info_logs]
type = "filter"
inputs = [ "vector" ]
condition = '.source_type == "syslog" && .severity != "warning"'`

but with no luck. We could see warning\errors messages in ClickHouse Info database that we use as output sink. But in Critical ClickHouse database there are only error\warning logs so 1st filter works.

Thank you for any advice.

### Configuration

```text
[transforms.critical_logs]
type = "filter"
inputs = [ "vector"]
condition = '.source_type == "syslog" && includes(["err", "warning"], .severity)'

[transforms.info_logs]
type = "filter"
inputs = [ "vector"]
condition = '.source_type == "syslog" && includes(["err", "warning"], .severity)'

[sinks.clickhouse_info]
type = "clickhouse"
inputs = ["info_logs"]
endpoint = "http://clickhouse-info:8123"
database = "vector"
auth.strategy = "basic"
table = "logs"
encoding.timestamp_format = "unix"
skip_unknown_fields = true

[sinks.clickhouse_critical]
type = "clickhouse"
inputs = ["critical_logs"]
endpoint = "http://clickhouse-critical:8123"
database = "vector"
auth.strategy = "basic"
table = "logs"
encoding.timestamp_format = "unix"
skip_unknown_fields = true
```

### Version

vector 0.27.0 (x86_64-unknown-linux-musl 5623d1e 2023-01-18)

### Example Data

{"INFO":{},"appname":"salt-minion","facility":"daemon","host":"monitor","hostname":"monitor","message":"Running scheduled job: __master_alive_dc1.test.lan with jid 20230131150016745785","procid":1894,"severity":"info","source_id":"127.0.0.1","source_type":"syslog","timestamp":"2023-01-31T15:00:16Z"}

**Comment by davidhuie-dd** [comment]
There might've been a typo in your original report, so the two transform configs appear identical to me. 

Here are a couple of alternatives to try:
```
[transforms.info_logs]
type = "filter"
inputs = [ "vector"]
condition = '.source_type == "syslog" && .severity == "info"'
```

Then, you can also try:
```
[transforms.info_logs]
type = "filter"
inputs = [ "vector"]
condition = '.source_type == "syslog" && !includes(["err", "warning"], .severity)'
```

You can always use the console sink as well to see if your setup is working correctly. That'll make logs appear in the vector stdout. This will help you rule out any issues with ClickHouse.

**Comment by inatale** [comment]
@davidhuie-dd , thank you for the response. Yes, it was a typo in the question (not in the config). Actual config is:
`[transforms.info_logs]
type = "filter"
inputs = [ "vector"]
condition = '.source_type == "syslog" && !includes(["err", "warning"], .severity)'`

But filter doesn't work. Yes, we use vector tap or console output to view logs and with "negative" include  (!include()) it doesn't work.

**Comment by jszwedko** [comment]
Hi @inatale !

I'm tried to reproduce this but am having a bit of trouble. With the following config:

```toml
data_dir = "/var/lib/vector/"

[sources.source0]
max_length = 102400
type = "stdin"

[sources.source0.decoding]
codec = "json"

[transforms.transform0]
inputs = ["source0"]
# correctly filters
condition = '.source_type == "syslog" && !includes(["err", "warning"], .severity)'
# correctly does not filter
# condition = '.source_type == "syslog" && includes(["err", "warning"], .severity)'
type = "filter"

[sinks.sink0]
inputs = ["transform0"]
target = "stdout"
type = "console"

[sinks.sink0.encoding]
codec = "json"
```

And running:

```
 echo '{"INFO":{},"appname":"salt-minion","facility":"daemon","host":"monitor","hostname":"monitor","message":"Running scheduled job: __master_alive_dc1.test.lan with jid 20230131150016745785","procid":1894,"severity":"err","source_id":"127.0.0.1","source_type":"syslog","timestamp":"2023-01-31T15:00:16Z"}' | vector --config /tmp/tmp.toml
```

I correctly see the line in the output. If I toggle to the other condition, it gets filtered as expected.

Would you be able to provide a full reproduction case I could run?
