### ISSUE TITLE
kubernetes_logs without API server access

### ISSUE THREAD

**Issue by yvespp** [vectordotdev/vector#16237]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We want to user `kubernetes_logs` but without the access to the Kubernetes API server.
All the information we need is already included in the file path of the container log and we don't need any additional information from Kubernetes.

We had issues in the past where our API server was overloaded with request during a Kubernetes update (fluentd had a big part in that) so we try to minimise the the tools that query the API server. 

### Attempted Solutions

We currently use the `file` source together with `remap` transform to achieve this:

```yaml
sources:
  kubernetes_logs:
    type: file
    include:
      - /var/log/containers/*.log
transforms:
  kubernetes_transform:
    type: remap
    inputs:
      - kubernetes_logs
    source: |
      . |= parse_regex!(.message, r'^(?P<timestamp>.+) (?P<LogSource>stdout|stderr) [FP] (?P<LogMessage>.*)?$')
      . |= parse_regex!(.file, r'^/var/log/containers/(?P<PodName>[^_]+)_(?P<PodNamespace>[^_]+)_(?P<ContainerName>.+)-(?P<ContainerID>.+)\.log$')
      del(.message)
      del(.file)
      del(.source_type)
````

This works but we have to maintain this ourselves and we can't take advantage of/contribute to all the optimizations in the `kubernetes_logs` source.

### Proposal

Ideas:
* Option to disable API server access in the existing `kubernetes_logs` source. When it's disabled pod info will be parsed form filename only.
* Create a new source `kubernetes_cri` which handles path and file parsing, reuse that in the existing `kubernetes_logs` source.
* Move the parser of the log into `parse_cri` vrl function and reuse this in the `kubernetes_logs` source.

### Version

v0.27.0
