### ISSUE TITLE
log_schema no longer allows nested fields to be specified

### ISSUE THREAD

**Issue by WilliamApted-Org** [vectordotdev/vector#16385]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In Vector configuration files you can specify the log schema, which defines the keys to use for certain fields. Such as the source type, timestamp, etc. This is described here in the Vector documentation https://vector.dev/docs/reference/configuration/global-options/#log_schema

In version `0.25.2` and prior, it was possible to specify nested keys such as `log.forwarder.source.type` and it would structure the log fields as `"log":{"forwarder":{"source":{"type":"example"}}}`.

With version `0.26.0` and up this has changed, so that the above specified log schema would instead produce a log field `{"log.forwarder.source.type":"example"}`. This lacks the correct nesting and breaks existing configuration pipelines which depend on the source type, or any other properties defined in the log_schema.

### Configuration

Demo configuration to showcase log_schema issue:
```yaml
log_schema:
  source_type_key: log.forwarder.source.type
  timestamp_key: event.created

sources:
  demo_logs:
    type: demo_logs
    format: syslog
    
sinks:
  console:
    encoding:
      codec: json
    inputs:
      - demo_logs
    type: console
```

### Version

vector 0.26.0< 

### Debug Output

Versions 0.25.2 and prior:
`{"event":{"created":"2023-02-10T14:32:15.010770Z"},"log":{"forwarder":{"source":{"type":"demo_logs"}}},"message":"<109>1 2023-02-10T14:32:15.010Z some.net meln1ks 3246 ID659 - Pretty pretty pretty good"}`

Versions 0.26.0 and higher (including 0.27.0):
`{"event.created":"2023-02-10T14:28:59.858055600Z","log.forwarder.source.type":"demo_logs","message":"<176>2 2023-02-10T14:28:59.857Z some.de jesseddy 1885 ID519 - There's a breach in the warp core, captain"}`
