### ISSUE TITLE
Route percentage of logs through different pipelines

### ISSUE THREAD

**Issue by joscha-alisch** [vectordotdev/vector#16432]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Our use-case are experimental changes to our vector pipelines. We would like to route a percentage of logs through some new transform/sink, and keep the remaining logs in the usual flow. e.g. 80% of logs go through our normal transforms, while 20% get some other treatment. Kind of like an A/B testing approach.

### Attempted Solutions

We tried to implement this via the `Sample` transform, but unfortunately the "unsampled" logs are silently dropped, so we can't route them further.

We also tried the "Route" transform, but given that it has no state we can't route based on some percentage of logs. 

### Proposal

Some initial ideas:

- Provide "reroute_dropped" on the "Sample" transform
- Provide a second output on the "Sample" transform
- Provide a setting on the "route" transform to route based on percentage
- Provide a new transform for this exact use case

### Version

0.27.0

**Comment by jszwedko** [comment]
Hey @joscha-alisch !

Thanks for this request! In line with one of your proposals, I think we will resolve this by adding the ability to route dropped events from a `sample` transform. We have an [RFC](https://github.com/vectordotdev/vector/pull/14708) that outlines a proposed approach. I'll link this issue there.

**Comment by spencergilbert** [comment]
Could work around this today by mirroring the original output:

```mermaid
graph TD;
  source-->sample;
  source-->normal_transforms;
  sample-->experimental_transforms;
  normal_transforms-->sink;
  experimental_transforms-->sinks;
```

(final sink could be the same component depending on your needs)

**Comment by joscha-alisch** [comment]
The sampled logs would be duplicated in the final sink though, unless I'm misunderstanding something @spencergilbert ?

i.e. all logs go through the `normal_transforms`, not just the "not-sampled" logs

**Comment by spencergilbert** [comment]
Ah, mhmm.. yes good point - if the final sink is the same you'd end up with duplicates unless your backend could dedupe (say ElasticSearch's IDs).

Getting _more_ complicated... and more difficult to get an exact percent, routing based on something like `mod()` _then_ sampling one side of it, and finally joining them back at the sink?

100% is a feature we should add to `sample` 😅

**Comment by hhromic** [comment]
This could be also done if VRL had a random function in the range `[0,1)` like many other languages have. I only found byte- and UUIDv4-generating functions under the "Random Functions" section of the docs.

For example:
```yaml
sources:
  source: ...

transforms:
  assign-route-path:
    type: remap
    inputs: [source]
    source: |
      .route_path = if rand() > 0.20 { "A" } else { "B" }
  route:
    type: route
    inputs: [assign-route-path]
    route:
      A: '.route_path == "A"'
      B: '.route_path == "B"'
sinks:
  A:
    inputs: [route.A]
  B: ...
    inputs: [route.B]
```

I think such random generator function could be very handy in VRL :)
