### ISSUE TITLE
Inconsistency prometheus records of sent_events_total and received_events_total of source component

### ISSUE THREAD

**Issue by zoechou** [vectordotdev/vector#16523]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Want to clarify if there's any loss records through entire log processing pipeline,
but found event if pure `component_kind="source"`, the number of vector_component_sent_events_total and vector_component_received_events_total was not consistent

how we check the data over same time range

we fixed the time at `2023-02-21 05:23:00` and using the following command to retrieve the event count
```
sum by(component_kind, component_type, component_name)(increase(vector_component_received_events_total{component_kind="source"}[5m]))
```

```
sum by(component_kind, component_type, component_name)(increase(vector_component_sent_events_total{component_kind="source",}[5m]))
```

### Configuration

```text
sources:
  file_visenze_logs_pattern:
    type: file
    multiline:
      mode: halt_before
      start_pattern: "^([A-Za-z0-9-_]+:[A-Za-z0-9-_]+( - |  ))"
      condition_pattern: "^([A-Za-z0-9-_]+:[A-Za-z0-9-_]+( - |  ))"
      timeout_ms: 1000
    max_line_bytes: 10485760 #10MiB
    max_read_bytes: 104857600 #100MiB
    include:
      - ***
```
```
sources:
  kubernetes_logs:
    type: kubernetes_logs
    max_line_bytes: 10485760 #10MiB
    max_read_bytes: 104857600 #100MiB
    extra_label_selector: common-logging=true
    exclude_paths_glob_patterns:
      - "**/*.gz"
      - "**/*.tmp"
      - "**/istio*/*.log"
```

### Version

vector 0.25.1 (x86_64-unknown-linux-gnu 9125a99 2022-11-07)
