### ISSUE TITLE
Internal Metrics Hangs Forever

### ISSUE THREAD

**Issue by smitthakkar96** [vectordotdev/vector#16561]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello there, 

We (Delivery Hero) are in process of adopting Vector. We deployed Vector on our staging environment and started load testing it. We noticed that the `internal_metrics` stops updating when the pods get saturated. We use the datadog_metrics sink to send internal_metrics to Datadog. Running vector top shows that internal metrics are not flushing more metrics, whereas other sinks like Datadog Logs and S3 used to ship k8s logs to Datadog and S3 keep working fine. The impact is a lack of `internal_metrics` until Vector is restarted.  Attached is the screenshot of our monitoring dashboard. As you can see, logs from Vector keep coming, but panels that use internal metrics are blank. 

![image](https://user-images.githubusercontent.com/10204970/220863154-614adba5-3cd2-49f2-af82-8d24f483dd77.png)

Possible duplicate of https://github.com/vectordotdev/vector/issues/13718 however I am not sure. 

## How did you generate the load?

We ran the load test on an EKS cluster running `c6g.xlarge` with 3 Vector pods having requests and limits of `2000m`. To generate load, we deployed another 120-150 pods running Vector `demo_logs` source with `stdout` sink. These demo_logs was tailed by Datadog Agent and later forwarded to Vector.

### Version

0.27.0

**Comment by jszwedko** [comment]
Hi @smitthakkar96 !

Thanks for this report! Could you provide the configuration file you are using? That would be helpful in reproducing.

**Comment by smitthakkar96** [comment]
Here is the configuration, sorry I forgot to put it earlier. Please let me know if you need anything else :) 

`vector.toml`

``` toml
data_dir = "/vector-data-dir"

[api]
enabled = true
address = "127.0.0.1:8686"
```

`sources/datadog_agents.toml`
``` toml
type = "datadog_agent"
address = "[::]:8080"
multiple_outputs = false
```

`sources/internal_logs.toml`
``` toml
type = "internal_logs"
```

`transforms/remap_enrich_internal_metrics_with_static_tags.toml`

``` toml
type = "remap"
inputs = [ "internal_metrics" ]
source = """
.tags.foo = "bar"
.tags.foo1 = "bar1"
"""
```

`transforms/remap_logs_for_datadog.toml`
``` toml
type = "remap"

inputs = [ "datadog_agents" ]

source = """

.host = del(.hostname)

.ddtags = parse_key_value!(.ddtags, key_value_delimiter: ":",
field_delimiter: ",")

.ddtags.vector_aggregator = get_hostname!()

.ddtags.env = "staging"

# Re-encode Datadog tags as a string for the `datadog_logs` sink

.ddtags = encode_key_value(.ddtags, key_value_delimiter: ":",
field_delimiter: ",")

# Datadog Agents pass a "status" field that is stripped when ingested

del(.status)
"""

```

`sinks/datadog_logs.toml`

``` toml
type = "datadog_logs"
inputs = [ "remap_logs_for_datadog", "internal_logs" ]
default_api_key = "${DATADOG_API_KEY}"
site = "datadoghq.eu"
buffer.type = "disk"
buffer.max_size = 268435488
```

`sinks/datadog_metrics.toml`

``` toml
type = "datadog_metrics"
inputs = [ "remap_enrich_internal_metrics_with_static_tags" ]
default_api_key = "${DATADOG_API_KEY}"
site = "datadoghq.eu"
buffer.type = "disk"
buffer.max_size = 268435488
```
