### ISSUE TITLE
Make `vector generate` prettyprint 

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#1685]
Right now, `vector generate` produces pretty ugly output.

```bash
❯ vector generate "stdin|json_parser|console"
data_dir = '/var/lib/vector/'
dns_servers = []
[sources.source0]
max_length = 102400
type = 'stdin'
[transforms.transform0]
inputs = ['source0']
drop_field = true
drop_invalid = false
type = 'json_parser'
[sinks.sink0]
healthcheck = true
inputs = ['transform0']
type = 'console'

[sinks.sink0.buffer]
type = 'memory'
max_events = 500
when_full = 'block'
```

Not the prettiest!

It'd be really nice if the output was cleanly and consistently formatted.

For example:

```toml
data_dir = '/var/lib/vector/'
dns_servers = []

[sources.source0]
type = 'stdin'
max_length = 102400

[transforms.transform0]
type = 'json_parser'
inputs = [
  'source0'
]
drop_field = true
drop_invalid = false

[sinks.sink0]
type = 'console'
inputs = [
  'transform0'
]
healthcheck = true

[sinks.sink0.buffer]
type = 'memory'
max_events = 500
when_full = 'block'
```

As you can see, we already do prettyprint:

https://github.com/timberio/vector/blob/ba7a11caaac2c3c1812e3de6f0cb831a73c573dc/src/generate.rs#L206-L215
