### ISSUE TITLE
`kafka_produced_messages_bytes_total` doesn't have a `component_id` label in Prometheus

### ISSUE THREAD

**Issue by almarcotte** [vectordotdev/vector#16912]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We have the `kafka_produced_messages_bytes_total` metric available in Prometheus and it doesn't have a `component_id` label. Our Vector configuration looks like this:

```toml
# Read some logs so we have something to publish to Kafka
[sources.log_reader]
type = "file"
include = [ "/path/to/logs/**/*.log" ]
read_from = "end"
ignore_older_secs = 600
ignore_not_found = true
fingerprint.strategy = "device_and_inode"

[sinks.publish_to_kafka]
type = "kafka"
inputs = [ "log_reader" ]
bootstrap_servers = "kafka-bootstrap-servers.example.com:9092"
topic = "our-kafka-topic"
compression = "gzip"
encoding.codec = "json"
sasl.enabled = true
sasl.username = "kafka-username"
sasl.password = "kafka-password"
sasl.mechanism = "SCRAM-SHA-512"
librdkafka_options."message.max.bytes" = "1000000"
librdkafka_options."security.protocol" = "sasl_ssl"

# Then let's get the internal metrics and write those to Prometheus
[sources.internal_metrics]
type = "internal_metrics"
namespace = "vector"
scrape_interval_secs = 60

[sinks.log_reader_prometheus_remote_write]
type = "prometheus_remote_write"
inputs = [ "internal_metrics" ]
tenant_id = "my-tenant-id"
endpoint = "https://prometheus-remote-writer.example.com"
default_namespace = "vector"
buffer.type = "memory"
buffer.when_full= "block"
request.retry_attempts = 3
request.retry_initial_backoff_secs = 5
request.rate_limit_num = 5
tls.ca_file = "/path/to/certs/vector-ca.pem"
tls.crt_file = "/path/to/certs/client.pem"
tls.key_file = "/path/to/certs/client-key.pem"
tls.verify_certificate = false
healthcheck.enabled = false
```

Then in Grafana when looking at the metric:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/175920/226926474-8b1fd93f-7676-479f-9960-9bbd1d58a9ef.png">

### Version

0.28.0
