### ISSUE TITLE
Datadog source - in and out event count mismatch

### ISSUE THREAD

**Issue by datsabk** [vectordotdev/vector#17006]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hey there, 
We are facing a weird issue where the metric events going into DD agent source is not matching the events going out. Please see the screenshot - Shows the rate of events per second going into a vector agent pod running in K8s cluster 

Moreover, we have a transform that has only DD agent source as input and still the events coming in is more than event out of DD agent source. 

Are the metrics not working right? What could be causing this ? 

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/16060349/228850965-1e547823-38f4-495d-8615-3c6688e6f0f1.png">

### Configuration

```yaml
customConfig:
          data_dir: /data/vector
          api:
            enabled: true
            address: 0.0.0.0:8686
            playground: false
          sources:
            datadog_agent:
              address: 0.0.0.0:8282
              type: datadog_agent
              disable_logs: true
              disable_traces: true
              multiple_outputs: false
            pods:
              type: kubernetes_logs
          transforms:
            modify_tags_for_veneur_metrics:
              type: remap
              inputs:
                - datadog_agent
              source: |-
                .tags.cluster_name = "prodobs"
            filter_for_vector_sink:
              type: filter
              inputs:
                - modify_tags_for_veneur_metrics
              condition:
                type: vrl
                source: |-
                  true
          sinks:
            vector_monitoring_sink:
              type: vector
              acknowledgements:
                enabled: false
              inputs:
                - filter_for_vector_sink
              address: metrics-ingest.segment.local:9000
              compression: true
              batch:
                max_events: 250
```

### Version

0.25.0
