### ISSUE TITLE
Improve logging in the `azure_blob_storage` sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#17021]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

A user was trying to run Vector with the `azure_blob_storage` sink and wasn't receiving any data in the sink, but also wasn't seeing any logs indicating the sink was attempting to make requests. I was able to reproduce this by not providing any Azure credentials to Vector so it seemed to be making requests that would fail and be retried but there were no logs indicating this until I `SIGTERM`'d, even at the debug level.

Configuration:

```toml
data_dir = "/tmp/data-dir"

[api]
enabled = false

[sources.spark_logs]
type         = "file"
include      = ["/tmp/tmp.log"]

[sinks.cloud_storage]
inputs          = ["spark_logs"]

type             = "azure_blob"
container_name   = "jszwedkotestcontainer"
storage_account  = "jszwedkovectortest"
blob_append_uuid = false
blob_prefix      = "test/"

compression     = "gzip"
framing.method  = "newline_delimited"
encoding.codec  = "json"
batch.max_bytes = 1000000 # 1mb uncompressed
```

### Proposal

Add debug logging of HTTP requests being made and their responses.

### Version

vector 0.28.0
