### ISSUE TITLE
vector add '/' to the beginning of the field of ipv4 date type, backend is Clickhouse

### ISSUE THREAD

**Issue by patrickdung** [vectordotdev/vector#17028]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Backend is Clickhouse

Using helm chart
```
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false
  sources:
    source_k8s_logs:
      type: kubernetes_logs
      pod_annotation_fields:
        pod_ip: kubernetes_pod_ip
        pod_ips: kubernetes_pod_ips
        pod_name: kubernetes_pod_name
        pod_namespace: kubernetes_pod_namespace
        pod_node_name: kubernetes_pod_node_name
 sinks:
   vector_to_clickhouse:
      type: clickhouse
      inputs:
        - source_k8s_logs
      endpoint: http://ch1.ch.svc.cluster.local:8123
      healthcheck:
        enabled: false
      database: logdb
      table: vector_k8s_logs_v2
      auth:
        strategy: basic
        user: logdb
        password: removed
      skip_unknown_fields: true
      buffer:
        max_events: 5000
      batch:
        timeout_secs: 40
      encoding:
        timestamp_format: rfc3339
```

Here's CH schema
```
CREATE TABLE IF NOT EXISTS
  logdb.vector_k8s_logs
(
   `timestamp` String,
   `parsed_timestamp` DateTime64(9) DEFAULT
      parseDateTime64BestEffort(timestamp, 9) CODEC(Delta(2), ZSTD(1)),
   `file` String,
   `kubernetes_pod_ip` IPv4,
   `kubernetes_pod_ips` Array(IPv4),
   `kubernetes_pod_labels` Map(LowCardinality(String), String),
   `kubernetes_pod_name` LowCardinality(String),
   `kubernetes_pod_namespace` LowCardinality(String),
   `kubernetes_pod_node_name` LowCardinality(String),
   `message` String,
   `source_type` LowCardinality(String),
   `stream` Enum('stdout', 'stderr')
)
ENGINE MergeTree
PARTITION BY toDate(parsed_timestamp)
ORDER BY parsed_timestamp;
```

After the record is inserted into CH, for kubernetes_pod_ip and kubernetes_pod_ips, there is a leading / (backlash or forwardlash, I could not remember) in front of the IP address.

Not sure if it is a vector or CH problem.
For CH, if I use String data type instead of IPv4, it is fine.

### Version

0.28.1-debian in container

### Additional Context

Yes, vector is running in kubernetes.
Because the source data is kubernetes_logs.
