### ISSUE TITLE
Support setting buckets on a per-metric-basis in "prometheus_exporter" sink

### ISSUE THREAD

**Issue by phihos** [vectordotdev/vector#17202]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Given the following pipeline we can only set a single array of buckets:

```toml
# ...

[transforms.to_metrics]
type = "log_to_metric"
inputs = [ "some-source" ]

  [transforms.to_metrics.request_header_size]
  type = "histogram"
  # ...
  [transforms.to_metrics.request_duration_seconds]
  type = "histogram"
  # ...

[sinks.prometheus]
type = "prometheus_exporter"
inputs = [ "to_metrics" ]
buckets = [ 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10 ]
```

Obviously setting the same buckets for metrics like `request_header_size` and `request_duration_seconds` does not make sense. Looking at the code there is currently no way to set different buckets for different metrics.

### Attempted Solutions

Not a solution, but a workaround: Use multiple sinks with different buckets and route metrics accordingly.

### Proposal

Maybe something like this:

```toml
[sinks.prometheus]
type = "prometheus_exporter"
inputs = [ "to_metrics" ]
buckets = [ 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10 ]

[sinks.prometheus.bucket_overrides]
request_header_size = [ 100, 500, 1000, 10000 ]
```

### Version

vector 0.29.0 (x86_64-unknown-linux-gnu 33b3868 2023-04-11 22:19:54.512366263)
