### ISSUE TITLE
Support ingesting OpenTelemetry metrics

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#17309]
Ref: https://github.com/vectordotdev/vector/issues/16121

**Comment by arendjr** [comment]
I was just trying out Vector for a PoC and was bumped to see it didn't support OTLP metrics yet, but now I'm happy to see you self-assigned, @pront :) Does this mean we can look forward to this soon?

**Comment by pront** [comment]
Hi @arendjr, yes, I will be working on this in the following weeks!

**Comment by pront** [comment]
Quick update, unfortunately this has been put on hold for now. We will update this issue if something changes.

**Comment by arendjr** [comment]
Too bad. Do you think it’s something that could be reasonably picked up by an outside contributor? If you have some pointers, I might have a chance to look at it.

**Comment by gaby** [comment]
Any updates or alternatives for this?

**Comment by gaby** [comment]
@pront Any updates on this?

**Comment by pront** [comment]
> @pront Any updates on this?
Hi @gaby, no. Nothing from me. I don't expect to be working on this since I am focusing on logs only at the moment. 

RFCs and contributions are most welcome.

**Comment by mayanksingh2298** [comment]
Why can't I simply use the http sink in vector to send json encoded data to otel http endpoint?

**Comment by gaby** [comment]
@mayanksingh2298 I think you can as long as both sides support OTEL via HTTP ?

**Comment by mayanksingh2298** [comment]
otel definitely does: https://github.com/open-telemetry/opentelemetry-proto/blob/main/examples/README.md

I can configure my source to do so.
For some reason I'm getting a 400 Bad request in vector http sink.

Any tips on debugging this?

**Comment by gaby** [comment]
Probably something with the encoding, I havent tried this this yet. Default method is POST in Vector

**Comment by mayanksingh2298** [comment]
I used tcpdump to analyze the requests. Turns out vector sends an array [{},...] of jsons but otel collector expects a single json

**Comment by mayanksingh2298** [comment]
In summary this is my workaround config to send otel traces (also works with other telemetry) to an otel collector.
```
sinks:
  sink_internal_otel_collector:
    type: http
    request:
      headers:
        Content-Type: application/json
    encoding:
      codec: json
    uri: http://localhost:4318/v1/traces
    batch:
      max_size: 1
    framing:
      method: newline_delimited
    inputs:
    - source_FluentD_log_httpnew 

sources:
  source_FluentD_log_httpnew:
    address: 0.0.0.0:49153
    decoding:
      codec: json
    framing:
      method: bytes
    type: http_server
```

Hopefully this helps someone
