### ISSUE TITLE
Unbounded memory growth for high throughput kubernetes_logs

### ISSUE THREAD

**Issue by aashery-square** [vectordotdev/vector#17313]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We're seeing this behavior for vector 0.29.1 on EKS 1.24. We are load testing vector by running it as a daemonset against pods writing files via the `json-file` log driver for containerd. There's 32 pods writing 100 logs/s each, so we're pushing 3200 logs/s through the vector daemon on the node. Log sizes vary from 1.25K-128K, with mostly smaller writes. We see unbounded memory growth consistently even when setting a blackhole sink. Based on log throughput and EKS' rotation size I'd imagine that we're rotating through a ton of files, so we believe that Vector is probably hoarding open file handles.

# Setup
## Chart.yaml
```yaml
apiVersion: v2
name: service
type: application
version: 1.0.0
dependencies:
  - name: vector
    version: 0.21.1
    repository: "https://helm.vector.dev"
```

## Values.yaml
```yaml
podLabels:
  tags.datadoghq.com/version: 0.29.1
resources:
  limits:
    cpu: 3000m
    memory: 1Gi
  requests:
    cpu: 3000m
    memory: 1Gi
```

## Vector Config
The redacted remaps below are just adding additional static tags.
```yaml
data_dir: /vector-data-dir
expire_metrics_secs: 60

api:
  enabled: true
  address: 127.0.0.1:8686
  playground: false

sources:
  internal_logs:
    type: internal_logs
  internal_metrics:
    type: internal_metrics
    scrape_interval_secs: 30
    tags:
      host_key: host
  k8s_logs:
    type: kubernetes_logs
    glob_minimum_cooldown_ms: 15000

transforms:
  vector_tagging:
    type: remap
    inputs:
      - internal_metrics
    source: |
      .tags.region = get_env_var!("AWS_REGION")
      ...(REDACTED)...
  log_tagging:
    type: remap
    inputs:
      - internal_logs
    source: |
      .service = "vector-daemonset"
      ...(REDACTED)...
sinks:
  datadog_metrics:
    type: datadog_metrics
    inputs:
      - vector_tagging
    default_api_key: ${DATADOG_API_KEY}
  datadog_logs:
    type: datadog_logs
    inputs:
      - log_tagging
    default_api_key: ${DATADOG_API_KEY}
  null_out:
    type: blackhole
    inputs:
      - k8s_logs
```

### Version

0.29.1

### Example Data

![image](https://user-images.githubusercontent.com/102249205/236337375-d26f94e0-a05b-428b-a812-4102c77d7d48.png)

### References

#14750

**Comment by spencergilbert** [comment]
It seems likely this could be a combination of file handles, as well as internal metrics.

To confirm it's 32 pods to the single Vector pod collecting their logs?

**Comment by aashery-square** [comment]
@spencergilbert ah actually 30, not 32. But yes, all 30 pods are colocated on the same node as the vector daemon, and are logging to file via the `json-file` log driver. Here's what that looks like:

![339B6C72-8747-43E1-8DCF-9345BB701014_1_201_a](https://user-images.githubusercontent.com/102249205/236480313-e55410b9-05ab-49bc-804c-3a79f052def0.jpeg)

Each deployment is labeled according to the size of logs it's producing. They each are emitting 100 logs/s except for the 128K deployment, which emits 1 log/s. I believe EKS has a default rotation size of 10MB, so the (estimated) rate at which we'd see file rotations should be `((1250 * 4 * 100) + (3000 * 20 * 100) + (10000 * 3 * 100) + (15000 * 2 * 100) + (128000 * 1 * 1)) / 10000000 = 1.2628` rotations/s.

**Comment by legigor** [comment]
I found the internal metrics events rate is constantly growing around the vectors fleet 

<img width="1105" alt="CleanShot 2023-05-11 at 10 56 54@2x" src="https://github.com/vectordotdev/vector/assets/117076/17bab10b-1f79-4728-90b7-18d760d4bc92">

**Comment by aashery-square** [comment]
@spencergilbert any updates here?

**Comment by jszwedko** [comment]
This sounds like it could partially be being caused by the known issue around runaway internal metric cardinality for the `kubernetes_logs` source which tags some of its metrics with `file` (ref: https://github.com/vectordotdev/vector/issues/15426). I see you are already setting https://vector.dev/docs/reference/configuration/global-options/#expire_metrics_secs to expire the internal metrics but maybe something isn't working there. You could monitor https://vector.dev/docs/reference/configuration/sources/internal_metrics/#internal_metrics_cardinality to see if that is always increasing or if it resets when metrics are expired.

Separately if it is that Vector has a lot of open file handles (have you confirmed this using `lsof` or something else?). You could try tweaking some of the settings to see if you can improve the performance of that source. Users have seen success increasing https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#max_read_bytes to a higher value so that Vector reads more from each file before moving on.

Do you have a rough sense of the volume of logs per node?

**Comment by aashery-square** [comment]
@jszwedko thanks for the extra info! re internal metrics cardinality I'm including what we captured there:

![image](https://github.com/vectordotdev/vector/assets/102249205/23abb63b-baff-44aa-a22e-f1938dc62adf)

I haven't actually investigated open file handle counts yet, do you know if there's an easy way to run `lsof` using the native vector chart? I will also look into playing with `max_read_bytes`.

**Comment by spencergilbert** [comment]
> I haven't actually investigated open file handle counts yet, do you know if there's an easy way to run `lsof` using the native vector chart? I will also look into playing with `max_read_bytes`.

If you're using the distroless image you'd need to use an ephemeral container, otherwise I expect `lsof` would be available on the other images.

**Comment by scMarkus** [comment]
I am seeing a similar behavior with a Docker source on Kubernetes. I am still running `vector 0.29.0 (x86_64-unknown-linux-gnu 33b3868 2023-04-11 22:19:54.512366263)` at the moment.
The Image shows two pods which grew memory usage until hitting Kubernetes limit of 196Mi and got restarted. The other two are for reference and not growing as fast (). This set of 4 is a selection out of a cluster with about 30 nodes where vector is running as a daemonset.
![image](https://github.com/vectordotdev/vector/assets/55751061/49511ff8-a3e1-4b4e-baeb-3012c331eebb)

vector-config.yaml
```yaml
    api:
      enabled: true
      playground: false
    data_dir: /opt/vector/data/
    enrichment_tables:
    ... TWO CSV ENRICHTMENTS ...
    sources:
      docker:
        type: docker_logs
        multiline:
          mode: continue_through
          start_pattern: "^[^\\s]"
          condition_pattern: "^[\\s]+"
          timeout_ms: 2000
      host_journal:
        type: journald
        current_boot_only: true
        since_now: true
        journal_directory: /var/log/journal/
    transforms:
    ... QUITE A BIT OF TRANSFORMATIONS ...
    sinks:
      prometheus:
        type: prometheus_exporter
        inputs:
          - vector_in
          - vector_out
        address: 0.0.0.0:9100
      graylog:
        type: socket
        inputs:
          - unified
          - unified.dropped
        address: graylog:12201
        mode: tcp
        encoding:
          codec: gelf
        buffer:
          type: disk
          max_size: 536870912 # 512 Mb
        framing:
          method: character_delimited
          character_delimited:
            delimiter: "\0"
```

At the moment all of them have similar memory consumption and similar amount of file descriptors. I will monitor the memory consumption and report back if a correlation with amount of file descriptors becomes apparent.

**Comment by scMarkus** [comment]
I double checked my assumption of the vector pods growing memory usage faster when many containers are started on there nodes. The following picture shows an aggregation per node (one vector instance running on each) counting how many distinct container ids did log something on them over the past 7 days.

![image](https://github.com/vectordotdev/vector/assets/55751061/8435bb72-d346-4ec7-b836-2b373d1a0811)

The first two which bars are significantly higher then the others are exactly the two nodes where the vector pods got restarts from my earlier post https://github.com/vectordotdev/vector/issues/17313#issuecomment-1559534415. File descriptors checked with lsof are increasing as well. But confusingly the fd counts are only in the hundreds. I would have assumed multiple thousands before those becom an issue?

**Comment by eddy1o2** [comment]
Hi folks, I have upgraded new vector's version `0.33.0` and it looks like `internal_metrics_cardinality_total` has been decrease to `0` but I still got memory OOM issue. That means this issue does not resolve, @jszwedko ?
![image](https://github.com/vectordotdev/vector/assets/35984720/d7d87e8a-b118-4d53-8e43-afd9141ee06e)
![image](https://github.com/vectordotdev/vector/assets/35984720/b6192e08-ce9e-46bb-91fb-fe78881ff652)

My vector's spec:
- spamming 100 logs/second
```yaml
vector.yaml: |
  api:
    enabled: true
  sources:
    kubernetes_logs:
      type: kubernetes_logs
      glob_minimum_cooldown_ms: 500
      max_read_bytes: 2048000
      oldest_first: true
...
cpu:
  request: 50m
  limit: 100m
memory:
  request: 1000Mib
  limit: 1000Mib
```
