### ISSUE TITLE
[file sources] Checkpoint writer stopped quietly when the number of file sources greater than 512

### ISSUE THREAD

**Issue by honganan** [vectordotdev/vector#17360]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

**Background**
We deployed vector as an agent to collect logs on a physical machine which has thousands of log files to tail. These days I found the checkpoint file not updated even if there are logs sinking normally.

I tried to reproduce it locally, and found the checkpoint writer threads not work when file sources number greater than 512. 

**How to reproduce**
1. Add a info log in https://github.com/vectordotdev/vector/blob/5d3f619ef3295180657529ad5bd44d837cb123b5/lib/file-source/src/file_server.rs#LL431C1-L431C1 
```rust
info!(message = "========I am running================");
```
2. Generate more than 512 `source` like below: (You may need a script to generate so many, just change the source name like: source_test2_log, source_test3_log)
```yaml
sources:
  source_test1_log:
    type: file
    include:
    - /home/docker/logs/apps/test1/*/info.log
    ignore_older_secs: 3600
    host_key: host
    file_key: filename
    fingerprint:
      strategy: device_and_inode
    max_line_bytes: 1024000
    max_read_bytes: 2048
    remove_after_secs: 172800
    encoding:
      charset: utf-8
```

`transforms` and `sinks` like:
```yaml
transforms:
  trans_test_log:
    type: remap
    inputs:
    - source_*
    source: |-
      .source = del(.filename)
      path_array, err = split(.source, "/")
      if err == null {
          .pod.name = get!(value: path_array, path: [6])
      }
      del(.timestamp)
sinks:
  my_sink_id:
    type: blackhole
    inputs:
      - trans*
    print_interval_secs: 3
    rate: 1000
```
In my case I created 512 `sources` and `transforms` and 1 `sinks` to blackhole, but I think number of `transforms` does not matter.

3. Start vector using above configs.
I am using Goland IDE and the command config is 
`run --package vector --bin vector -- --config /Users/xxx/vector-agent/vector.yml --config-dir /Users/xxx/vector-agent/configs`

vector.yml contains transforms and sinks, and all the sources files in `/Users/xxx/vector-agent/configs` directory.

4. Wait a moment and count the added logs above, We can found when number of `sources` greater than 512, the log `I am running` only appears 512 times then stopped(log tails is still working).
5. Remove some `sources` and make sure the number less than 512, restart like above steps and observe the log, We will find that it keeps outputting the `I am running` logs.

After retrying many times I found the critical number of `sources` is 512.

`tokio` had some similar issue that it may have 512 threads limit: https://github.com/tokio-rs/tokio/issues/2309, but it should panic when exceeding the limit and had been fixed, I am not sure if it's `spawn_blocking`'s problem.

**Expect**
No matter how many `sources` the checkpoint writer should work normally.

### Version

0.29.1
