### ISSUE TITLE
Fluent source ack wrong format

### ISSUE THREAD

**Issue by ChezBunch** [vectordotdev/vector#17427]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

As mentioned in https://github.com/vectordotdev/vector/issues/7533#issuecomment-1532751631, the ACK format returned by the fluent source is not understood by fluent-bit, and generates an error:
`[error] [output:forward:forward.0] ACK response not MAP (type:2)`

Indeed, when the ack was implemented, https://github.com/vectordotdev/vector/pull/10176 mentioned that the ack format was not very clear, and was implemented as plain JSON, while in fact fluent-bit expects a msgpack format.

**The issue as initially described in https://github.com/vectordotdev/vector/issues/7533#issuecomment-1532751631:**

Hello. Yes, I have some problems.
I using Vector as an aggregator and fluent-bit as a log collector, but in fluent-bit logs, I see errors like this:
```
[error] [engine] chunk '96-1683047707.895527211.flb' cannot be retried: task_id=0, input=tail.0 > output=forward.0
[error] [output:forward:forward.0] ACK response not MAP (type:2)
```
Vector deployed via Helm chart version: 0.20.1 with these options:
```
customconfig:   
  acknowledgements:
      enabled: true
image:
  tag: "0.29.1-distroless-libc"
```
Vector configuration is:
```
vector:
  address: 0.0.0.0:9000
  type: fluent
  receive_buffer_bytes: 1048576
  connection_limit: 2000
  keepalive:
     time_secs: 30
```
fluent-operator deployed via Helm chart 2.2.0, also tried 2.1.0
```
fluent-bit:
  image:      
    repository: "kubesphere/fluent-bit"
    tag: "v2.0.11"
  forward:    
    host: vector.fluent.svc    
    port: 9000    
    requireAckResponse: true
```
If you need more details, I can provide it.
Thank you

### Version

0.30.0

### References

https://github.com/vectordotdev/vector/pull/10176
https://github.com/vectordotdev/vector/issues/7533
