### ISSUE TITLE
Avoid "Missing fields on event" errors by setting a default

### ISSUE THREAD

**Issue by grosser** [vectordotdev/vector#17442]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We want to generate metrics for an optional field `kubernetes.container_name`,
by using 
```
  log_count:
    type: log_to_metric
    inputs:
      - logs
    metrics:
      - type: "counter"
        name: "log_count"
        field: log_via
        tags:
          kube_container_name: "{{kubernetes.container_name}}"
```
but now vector fails with
```
Missing fields on event: ["kubernetes.container_name"]
```

We'd want this to either come out as `""` or `N/A` or be able to set `"{{kubernetes.container_name:missing}}"`

### Version

0.28.2
