### ISSUE TITLE
Don't fail when config is missing with `--watch-config`

### ISSUE THREAD

**Issue by igor-nikiforov** [vectordotdev/vector#17557]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We are using Vector with [git-sync](https://github.com/kubernetes/git-sync) to able update automatically all configs of our Vector instances when config changes merged in master branch. So we are using `--watch-config` argument to reflect on any changes fetched by git-sync container.

Problem here that to avoid Vector container restarts due to missing config **on init stage** (when git-sync is not fetched config yet) it is required to define **the same git-sync config** in `initContainers` additionally to `extraContainers`.

### Attempted Solutions

We came to this but want to avoid using `initContainers` at all:

```
initContainers:
  - name: git-sync-init
    image: registry.k8s.io/git-sync/git-sync:v3.6.6
    volumeMounts:
      - name: vector-config
        mountPath: /data
    env:
      - name: GIT_SYNC_REPO
        value: "https://bitbucket.org/xxx/vector-configs.git"
      - name: GIT_SYNC_USERNAME
        valueFrom:
          secretKeyRef:
            name: vector-autodiscovery
            key: user
      - name: GIT_SYNC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vector-autodiscovery
            key: token
      - name: GIT_SYNC_BRANCH
        value: "master"
      - name: GIT_SYNC_ROOT
        value: /data
      - name: GIT_SYNC_DEST
        value: "vector-configs"
      - name: GIT_SYNC_DEPTH
        value: "1"
      - name: GIT_SYNC_ONE_TIME
        value: "true"

extraContainers:
  - name: git-sync
    image: registry.k8s.io/git-sync/git-sync:v3.6.6
    volumeMounts:
      - name: vector-config
        mountPath: /data
    env:
      - name: GIT_SYNC_REPO
        value: "https://bitbucket.org/xxx/vector-configs.git"
      - name: GIT_SYNC_USERNAME
        valueFrom:
          secretKeyRef:
            name: vector-autodiscovery
            key: user
      - name: GIT_SYNC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vector-autodiscovery
            key: token
      - name: GIT_SYNC_BRANCH
        value: "master"
      - name: GIT_SYNC_ROOT
        value: /data
      - name: GIT_SYNC_DEST
        value: "vector-configs"
      - name: GIT_SYNC_DEPTH
        value: "1"
      - name: GIT_SYNC_PERIOD
        value: "60"
```

### Proposal

If `--watch-config` is defined don't fail and print to stdout warning/error message due missing config file.

### Version

v0.30.0
