### ISSUE TITLE
Multiple prometheus_scrape endpoints not scraped in parallel

### ISSUE THREAD

**Issue by wjordan** [vectordotdev/vector#17659]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am using Vector to scrape metrics from a large number (thousands) of instances using the [`prometheus_scrape`](https://vector.dev/docs/reference/configuration/sources/prometheus_scrape/) source component.

I expected the URLs set in the [`endpoints`](https://vector.dev/docs/reference/configuration/sources/prometheus_scrape/#endpoints) config to be scraped in parallel, but it appears to be scraping sequentially. This is not very useful since a single slow or broken endpoint prevents all other endpoints from being scraped properly. Other Prometheus agents scrape the provided endpoints in parallel.

A workaround is to create a separate `prometheus_scrape` component for each endpoint, but creating a large number (thousands) of components creates heavy CPU load and seems to go against Vector's design.

### Configuration

Here's a minimal configuration that reproduces the issue:

```toml
[sources.internal_src]
type = "internal_metrics"

[transforms.internal]
type = "filter"
inputs = ["internal_src"]
condition = '.name == "component_sent_bytes_total"'

[sinks.prom_export]
type = "prometheus_exporter"
inputs = ["internal"]
address = "0.0.0.0:9598"

[sources.prom_scrape]
type = "prometheus_scrape"
endpoints = [
    "http://172.0.0.0/metrics",
    "http://127.0.0.1:9598/metrics"
]
endpoint_tag = "endpoint"

[sinks.console]
type = "console"
inputs = ["prom_scrape"]
encoding.codec = "text"
```

### Version

vector 0.30.0 (x86_64-unknown-linux-gnu 38c3f0b 2023-05-22 17:38:48.655488673)
