### ISSUE TITLE
Panic when writing log files to ClickHouse

### ISSUE THREAD

**Issue by majkinetor** [vectordotdev/vector#17652]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I tried the log tutorial given [officially](https://clickhouse.com/docs/en/integrations/vector). This is the config I use:

```toml
[sources.nginx_logs]
type = "demo_logs"
format = "shuffle"
lines = [
    '192.168.208.1 - - [12/Oct/2021:03:31:44 +0000] \"GET / HTTP/1.1\" 200 615 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36\"',
    '192.168.208.1 - - [12/Oct/2021:03:31:44 +0000] \"GET /favicon.ico HTTP/1.1\" 404 555 \"http://localhost/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36\"',
    '192.168.208.1 - - [12/Oct/2021:03:31:49 +0000] \"GET / HTTP/1.1\" 304 0 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36\"'
]

[sinks.clickhouse]
type = "clickhouse"
inputs = ["nginx_logs"]
endpoint = "http://localhost:8123"
database = "nginxdb"
table = "access_logs"
skip_unknown_fields = true
```

Its basically unchanged. However, I get the following error:
```
> vector --config-toml .\vector.toml
2023-06-08T21:48:31.448193Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,lapin=info,kube=info"
2023-06-08T21:48:31.449065Z  INFO vector::app: Loading configs. paths=["vector.toml"]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: X509SystemParseError { source: ErrorStack([Error { code: 219029725, library: "asn1 encoding routines", function: "c2i_ibuf", reason: "illegal padding", file: "crypto\\asn1\\a_int.c", line: 187 }, Error { code: 218640442, library: "asn1 encoding routines", function: "asn1_template_noexp_d2i", reason: "nested asn1 error", file: "crypto\\asn1\\tasn_dec.c", line: 646, data: "Field=serialNumber, Type=X509_CINF" }, Error { code: 218640442, library: "asn1 encoding routines", function: "asn1_template_noexp_d2i", reason: "nested asn1 error", file: "crypto\\asn1\\tasn_dec.c", line: 646, data: "Field=cert_info, Type=X509" }]) }', lib\vector-core\src\tls\settings.rs:277:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

ClickHouse works OK and I am connected to it. I tried various `tls` options without success.

### Configuration

```text
[sources.nginx_logs]
type = "demo_logs"
format = "shuffle"
lines = [
    '192.168.208.1 - - [12/Oct/2021:03:31:44 +0000] \"GET / HTTP/1.1\" 200 615 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36\"',
    '192.168.208.1 - - [12/Oct/2021:03:31:44 +0000] \"GET /favicon.ico HTTP/1.1\" 404 555 \"http://localhost/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36\"',
    '192.168.208.1 - - [12/Oct/2021:03:31:49 +0000] \"GET / HTTP/1.1\" 304 0 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36\"'
]

[sinks.clickhouse]
type = "clickhouse"
inputs = ["nginx_logs"]
endpoint = "http://localhost:8123"
database = "nginxdb"
table = "access_logs"
skip_unknown_fields = true
```

### Version

vector 0.30.0 (x86_64-pc-windows-msvc 38c3f0b 2023-05-22 17:38:48.655488673)

### Debug Output

```text
2023-06-08T21:54:53.123864Z DEBUG vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2023-06-08T21:54:53.124104Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,lapin=trace,kube=trace"
2023-06-08T21:54:53.124817Z  INFO vector::app: Loading configs. paths=["vector.toml"]
2023-06-08T21:54:53.125451Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2023-06-08T21:54:53.126478Z DEBUG vector::topology::builder: Building new source. component=nginx_logs
2023-06-08T21:54:53.126962Z DEBUG vector::topology::builder: Building new sink. component=clickhouse
2023-06-08T21:54:53.128146Z DEBUG vector_core::tls::settings: Fetching system root certs.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: X509SystemParseError { source: ErrorStack([Error { code: 219029725, library: "asn1 encoding routines", function: "c2i_ibuf", reason: "illegal padding", file: "crypto\\asn1\\a_int.c", line: 187 }, Error { code: 218640442, library: "asn1 encoding routines", function: "asn1_template_noexp_d2i", reason: "nested asn1 error", file: "crypto\\asn1\\tasn_dec.c", line: 646, data: "Field=serialNumber, Type=X509_CINF" }, Error { code: 218640442, library: "asn1 encoding routines", function: "asn1_template_noexp_d2i", reason: "nested asn1 error", file: "crypto\\asn1\\tasn_dec.c", line: 646, data: "Field=cert_info, Type=X509" }]) }', lib\vector-core\src\tls\settings.rs:277:41
stack backtrace:
   0:     0x7ff67fb3b393 - onig_get_capture_tree
   1:     0x7ff67efd2bab - <unknown>
   2:     0x7ff67fb1a641 - onig_get_capture_tree
   3:     0x7ff67fb4038b - onig_get_capture_tree
   4:     0x7ff67fb3ff57 - onig_get_capture_tree
   5:     0x7ff67fb40e8b - onig_get_capture_tree
   6:     0x7ff67fb408c6 - onig_get_capture_tree
   7:     0x7ff67fb40819 - onig_get_capture_tree
   8:     0x7ff67fb40804 - onig_get_capture_tree
   9:     0x7ff68320b295 - onig_unicode_define_user_property
  10:     0x7ff68320b666 - onig_unicode_define_user_property
  11:     0x7ff682a5a927 - onig_get_capture_tree
  12:     0x7ff682a68a92 - onig_get_capture_tree
  13:     0x7ff68002cc9a - onig_get_capture_tree
  14:     0x7ff6804f1cbd - onig_get_capture_tree
  15:     0x7ff6820f2c36 - onig_get_capture_tree
  16:     0x7ff681e9c474 - onig_get_capture_tree
  17:     0x7ff681e80a36 - onig_get_capture_tree
  18:     0x7ff681e797b2 - onig_get_capture_tree
  19:     0x7ff681e5307d - onig_get_capture_tree
  20:     0x7ff68278f478 - onig_get_capture_tree
  21:     0x7ff682780a96 - onig_get_capture_tree
  22:     0x7ff681e1b86d - onig_get_capture_tree
  23:     0x7ff67e9b129f - <unknown>
  24:     0x7ff67e9b1006 - <unknown>
  25:     0x7ff67e9b176f - <unknown>
  26:     0x7ff6831b1a3c - onig_unicode_define_user_property
  27:     0x7ffdabd0269d - BaseThreadInitThunk
  28:     0x7ffdaccca9f8 - RtlUserThreadStart
```

### Additional Context

OS Name:                   Microsoft Windows 11 Pro N
OS Version:                10.0.22621 N/A Build 22621
