### ISSUE TITLE
Elasicsearch autodetect version doesn't support OpenSearch versions

### ISSUE THREAD

**Issue by arve0** [vectordotdev/vector#17690]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Seems like vector to 0.30.0 broke elasticsearch version detection for OpenSearch endpoints. Our upgrade was from 0.29.1 to 0.30.0. Endpoint is running OpenSearch 2.5.0.

Error log is: 

```
2023-06-14T08:04:31.859502Z ERROR sink{component_kind="sink" component_id=logs_domstol_no component_type=elasticsearch component_name=logs_domstol_no}:request{request_id=1}: vector::sinks::util::retries: Not retriable; dropping the request. reason="client-side error, 400 Bad Request: {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Action/metadata line [1] contains an unknown parameter [_type]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Action/metadata line [1] contains an unknown parameter [_type]\"},\"status\":400}" internal_log_rate_limit=true
```

### Configuration

```text
We are deploying vector with helm chart version v0.22.0 (vector 0.30.0) or v0.21.1 (vector 0.29.1). Only image version changes was detected on upgrade:


-          image: "timberio/vector:0.30.0-distroless-libc"
+          image: "timberio/vector:0.29.1-distroless-libc"
```

Settings to vector are:

```yaml
  logs_domstol_no:
    api_version: auto
    auth:
      password: $LOG_COLLECTOR_PASSWORD
      strategy: basic
      user: log-collector
    bulk:
      action: create
    compression: none
    data_stream:
      dataset: '{{ kubernetes.pod_labels.logs_domstol_no }}'
      namespace: '{{ kubernetes.pod_namespace }}'
      type: logs
    endpoints:
    - https://opensearch:9200
    inputs:
    - ecs_parsing
    - eventrouter_parsing
    - filter._unmatched
    mode: data_stream
    tls:
      verify_certificate: false
      verify_hostname: false
    type: elasticsearch
```

### Version

vector 0.30.0 (aarch64-unknown-linux-gnu 38c3f0b 2023-05-22 17:38:48.655488673)
