### ISSUE TITLE
Valid configuration doesn't pass validation

### ISSUE THREAD

**Issue by nmiculinic** [vectordotdev/vector#17702]
### Problem

I have issue getting vector validation for valid config to pass

### Configuration

```text
# https://vector.dev/docs/reference/configuration/global-options/#expire_metrics_secs
expire_metrics_secs: 3600   # If metric hasn't been seen for over an hour, drop it
data_dir: /vector-data-dir
acknowledgements: true
api:
  # https://vector.dev/docs/reference/api/
  enabled: true
  address: 0.0.0.0:8686
  # enables graphQL playground
  playground: true
sources:
  internal_metrics:
    type: internal_metrics
  vector:
    type: vector
    address: 0.0.0.0:7171
  fluent:
    type: fluent
    address: 0.0.0.0:9000
  otel:
    type: opentelemetry
    grpc:
      address: 0.0.0.0:4317
    http:
      address: 0.0.0.0:4318
sinks:
  prom_exporter:
    type: prometheus_exporter
    inputs:
    - internal_metrics
    address: 0.0.0.0:9090
  blackhole:
    type: blackhole
    inputs:
      - otel
      - vector
      - fluent
```

### Version

vector 0.30.0 (x86_64-apple-darwin 38c3f0b 2023-05-22 17:38:48.655488673)

### Debug Output

```text
2023-06-16T15:18:52.000193Z DEBUG vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2023-06-16T15:18:52.000240Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,lapin=trace,kube=trace"
Failed to load ["base/aggregator/config"]
-----------------------------------------
x Input "otel" for sink "blackhole" doesn't match any components.
```

**Comment by pomarec** [comment]
I'm having the same problem.
I don't understand what is the "otel.logs" solution. Can you help me out ?

```
sources:
  opentelemetry_logs:
    type: opentelemetry
    grpc:
      address: 0.0.0.0:4317
    http:
      address: 0.0.0.0:4318

sinks:
  loki:
    type: loki
    inputs:
      - opentelemetry_logs
    endpoint: "redacted"
    encoding:
      codec: json
    labels:
      env: dev
      ```

Logs :
```
 ERROR vector::cli: Configuration error. error=Input "opentelemetry_logs" for sink "loki" doesn't match any components.
```
