### ISSUE TITLE
Cannot receive logs from docker

### ISSUE THREAD

**Issue by aido93** [vectordotdev/vector#17747]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm trying to collect logs from docker containers, but I'm getting errors like:
```
ERROR source{component_kind="source" component_id=docker_logs component_type=docker_logs component_name=docker_logs}: vector::internal_events::docker_logs: Received out of order log message. error_type="condition_failed" stage="receiving" container_id="795327b7a459bb1bffb30d5e287c726c27c7d6282cddf3d1eb2a25abae1e83e5" timestamp="2023-06-23T21:03:12.255522961Z" internal_log_rate_limit=true
ERROR source{component_kind="source" component_id=docker_logs component_type=docker_logs component_name=docker_logs}: vector::internal_events::docker_logs: Internal log [Received out of order log message.] is being suppressed to avoid flooding.
```
I expect that docker logs can be collected successfully.

### Configuration

```text
[sources.docker_logs]
type = "docker_logs"
auto_partial_merge=false
exclude_containers = [
  "vector",
  "openobserve"
]
```

### Version

0.30.0

### Debug Output

```text
https://gist.github.com/aido93/2aeb512d2e77c8796bda08d773967514
```

### Example Data

You can run some services in docker and see what's happening. Here is example docker-compose.yml that runs openobserve behind traefik. So when openobserver webpage is reloaded traefik writes to accesslog. I expect to see this accesslog in vector at first and in openobserve afterwards.
```
version: '3.7'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api=true"
      - "--api.insecure=true"
      - "--accesslog=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`proxy.corp.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - openobserve
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openobserve.rule=Host(`logs.corp.com`)"
      - "traefik.http.routers.openobserve.entrypoints=web"
      - "traefik.http.services.openobserve.loadbalancer.server.port=5080"
    environment:
      ZO_ROOT_USER_EMAIL: "root@corp.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
      ZO_LOCAL_MODE: "true"
      ZO_LOCAL_MODE_STORAGE: disk
    network_mode: "host"
    volumes:
      - openobserve-data:/data

  vector:
    image: timberio/vector:0.30.0-alpine
    container_name: vector
    command: -vvv
    environment:
      RUST_BACKTRACE: full
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    depends_on:
      - openobserve

volumes:
  openobserve-data:
```

### Additional Context

Error message is from `src/sources/docker_logs/mod.rs:1013`
