### ISSUE TITLE
source/address field: support hostname

### ISSUE THREAD

**Issue by softlion** [vectordotdev/vector#17896]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

It looks like vector does not resolve hostnames for sockets.

I have a docker network with 2 containers, I wanted to use the docker version of vector with a source port on the other container.
I can not rely on IPs as docker may change them.

```
[sources.some]
type = "socket"
address = "somehost.local:30001"
```

### Attempted Solutions

-

### Proposal

see above

### References

https://github.com/vectordotdev/vector/discussions/17866

### Version

vector 0.30.0 (aarch64-unknown-linux-musl 38c3f0b 2023-05-22 17:38:48.655488673)

**Comment by neuronull** [comment]
Confirmed with

```toml
[sources.in]
type = "socket"
mode = "tcp"
address = "localhost:5555"
decoding.codec = "json"

[sinks.out]
type = "blackhole"
inputs = [ "in" ]
```

error reported:

```
2023-07-24T23:11:55.700307Z ERROR vector::cli: Configuration error. error=Must be a valid IPv4/IPv6 address with port, or start with "systemd"
```
