### ISSUE TITLE
Support cloudwatch destination for AWS Cloudwatch Logs

### ISSUE THREAD

**Issue by AvihaiSam** [vectordotdev/vector#17944]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

[cloudwatch logs destination](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CreateDestination.html) is a feature that allows sending cross-account logs.
In short - cloudwatch destination is a logical representation of log group which has an AWS ARN in the form `arn:aws:logs:<REGION>:<ACCOUNT_ID>:destination:<NAME>`

vector, currently, does not support this type of endpoint for cloudwatch logs

### Attempted Solutions

aws cloudwatch logs sink doesn't any option that can suggest sending data to a different account (no account-id, destination-ARN)

### Proposal

add `destination_arn`/`cw_logs_arn` option that can take destination ARN.
this option is mutually exclusive with `group_name` and `region` options.

examples:
```
sinks:
  cw:
    cw_logs:
      type: aws_cloudwatch_logs
      inputs: 
        - logs
      destination_arn: arn:aws:logs:<REGION>:<ACCOUNT_ID>:destination:<NAME>
```

```
sinks:
  cw:
    cw_logs:
      type: aws_cloudwatch_logs
      inputs: 
        - logs
      group_name: group1
      region: us-east-1
```
