### ISSUE TITLE
when using `kafka` as source, `timestamp_key` only has miliseconds precision

### ISSUE THREAD

**Issue by s-at-ik** [vectordotdev/vector#17951]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using `kafka` as source and specifying a `timestamp_key`, the timestamp generated only has millisecond precision whilst it registers nanoseconds when using `file` as source.

If I tap the kafka source on the processor (see config below), the log events look like this:

```
{
...
  "timestamp": {
    "harvester": "2023-07-12T14:20:50.395855142Z",
    "processor": "2023-07-12T14:20:50.395Z"
  },
...
}

```

### Configuration

On the harvester:

```
log_schema:
  timestamp_key: timestamp.harvester
sources:
  some_file:
     type: file
     include:
       - /tmp/some_file.log
sinks:
  kafka:
    type: kafka
    inputs:
      - some_file
    bootstrap_servers: localhost:9093
    encoding:
      codec: json
    topic: a-topic
```

On the processor:

```
log_schema:
  timestamp_key: timestamp.processor
sources:
  kafka:
    type: kafka
    bootstrap_servers: localhost:9093
    decoding:
      codec: json
    topics:
      - a-topic
```

### Version

timberio/vector:0.31.0-debian

### Additional Context

The processor and the harvester are both running in kubernetes.
