### ISSUE TITLE
support custom directory for kubernetes_log of vector sources

### ISSUE THREAD

**Issue by YuWan1117** [vectordotdev/vector#18009]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

When I set the `source type` to `kubernetes_log`, after deploying the `vector` as an `agent` role, I observe that the log information collected by the `vector` pod is the log content under the /var/log/pods/ directory ( the /var/log/pods/XXXXXXXX/XXXX/0.log or /var/log/pods/XXXXXXXX/init-only/0.log.), and will not collect our service logs under the /data/logs/ directory.

So I hope:  Support the custom directory where logs are collected when the `source type` to be of the `kubernetes_log` type.

Similar to: [include](https://vector.dev/docs/reference/configuration/sources/file/#include) field when source type is [file](https://vector.dev/docs/reference/configuration/sources/file/). 

If `vector` is supported and I don't find out, I'm sorry and hope to get your advice.
If vector is not yet supported, look forward to seeing the discussion of this feature.

### Version

0.31.0

**Comment by jszwedko** [comment]
Hi @YuWan1117 !

Thanks for opening this. To confirm, in your Kubernetes setup, are pod logs being created in the `/data/logs` directory? Or are these other sorts of logs?

**Comment by YuWan1117** [comment]
> Hi @YuWan1117 !
> 
> Thanks for opening this. To confirm, in your Kubernetes setup, are pod logs being created in the `/data/logs` directory? Or are these other sorts of logs?

Yes. the logs in the `/data/logs` directory are pod logs.  These logs are written by the `hostPath`.

## Example
```yaml
volumeMounts:
    name: service-log
    mountPath: /data/logs/
    subPathExpr: $(SERVICE_NAME_UNIQUE)_$(NAMESPACE)/$(POD_NAME)
```

**Comment by YuWan1117** [comment]
Hi @jszwedko 
Thanks for your reply. 
I have made a supplementary answer here and I need your help.  Thank you very much😊
              
> Q1:To confirm, in your Kubernetes setup, are pod logs being created in the /data/logs directory?

**See the previous comment.** [Link](https://github.com/vectordotdev/vector/issues/18009#issuecomment-1641264210)

> Q2: Are these other sorts of logs?

Here is the service logs for /data/logs/${myServiceName}/${myServiceName}.log
For example: /data/logs/hello-admin/hello-admin.log
![image](https://github.com/vectordotdev/vector/assets/7919137/62b06185-3db6-4f4c-8fb0-80773325dede)


Looking forward to more community students participating in the discussion of this feature.

**Comment by jszwedko** [comment]
Thanks for the additional details @YuWan1117 .

If I'm understanding this correctly:

- You are mounting a directory into a pod
- The pod is writing files to this directory
- You would like to read those files with Vector

This is in contrast to the log files that Kubernetes itself creates from pods logging to `stdout` / `stderr`.

Am I understanding correctly?

**Comment by YuWan1117** [comment]
Thanks for your reply firstly @jszwedko .

Currently we are using Filebeat to collect k8s logs. And the paths for filebeat config like this:
```yaml
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            - condition:
                has_fields: ["kubernetes.labels.kafkaTopic"]
              config:
                - type: log
                  enabled: true
                  tail_files: false
                  paths:
                    - /data/logs/${data.kubernetes.labels.service}-${data.kubernetes.labels.cluster}_${data.kubernetes.namespace}/${data.kubernetes.pod.name}/*/*.log
```

Thanks again😊
