### ISSUE TITLE
Gaps in data when using log_to_metric

### ISSUE THREAD

**Issue by alexf101** [vectordotdev/vector#18128]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When collecting metric data with Prometheus, we generally expect clients to report their metrics consistently rather than having gaps in the data.

However, we're observing that Vector will return no data for particular metrics on most scrapes.

I know it's scraping successfully because of the `up` metric:
<img width="619" alt="Screenshot 2023-08-01 at 3 33 39 pm" src="https://github.com/vectordotdev/vector/assets/2832017/51ab7019-271c-4927-a69f-f79d5cbd0a81">
For the same time period however, our application metric `rds_log_count` is only reported sporadically.
<img width="599" alt="Screenshot 2023-08-01 at 3 32 42 pm" src="https://github.com/vectordotdev/vector/assets/2832017/6a09cd2c-6945-460d-b122-09592ffaa09b">

The metric is configured as a counter with log_to_metric (as shown in Configuration section).

I'd readily believe that due to some form of upstream batching, our application only processes logs sporadically. However, I do expect that it's processing logs every few minutes at least.

The behaviour I'd expect from Vector is that even if it hasn't observed a change in the count, the metric continues to be reported, so the metric doesn't "disappear".

### Configuration

```text
[transforms.rds_log_metrics]
type = "log_to_metric"
inputs = ["rds_all_finished"]
[[transforms.rds_log_metrics.metrics]]
type = "counter"
# I don't think this does anything for counters, but it needs to be specified and the field needs
# to exist, so use logapp_name WLOG
field = "logapp_name"
name = "rds_log_count"
tags.role = "{{.rds.role}}"
tags.engine = "{{.rds.engine_type}}"
tags.type = "{{.rds.log_type}}"
tags.id = "{{.rds.id}}
```

### Version

vector 0.31.0 (x86_64-unknown-linux-gnu 0f13b22 2023-07-06 13:52:34.591204470)

**Comment by djrodgerspryor** [comment]
I work with @alexf101 at Sitle. One extra wrinkle in the case is that this metric is being generated by one vector instance and then sent to another vector instance before being exported to prometheus - I wonder if something in the vector source/sink components is stopping the metrics from being consistently exported?

Below are the full vector.toml files.

This one generates the original metric:
```toml
log_schema.host_key = "vector_docker_host"
acknowledgements.enabled = true
# Where vector keeps track of its internal state
data_dir = "${VECTOR_DATA_PATH:?VECTOR_DATA_PATH must be specified for vector to run!}"

# We use the API for a container healthcheck
[api]
enabled = true
address = "127.0.0.1:8686"

[sources.vector_internal_logs]
type = "internal_logs"

[sources.rds_logfiles_default]
type = "file"
include = [
	"${LOG_DESTINATION_PATH:?LOG_DESTINATION_PATH must be specified for vector to run!}*/**/*"
]
# These need special handling
exclude = ["**/PrePatchCompatibility.log*"]
file_key = "logfile_path"
read_from = "beginning"
# The log shipper won't move or recreate any files, so this is the safest deduplication method
fingerprint.strategy = "device_and_inode"
# Vector will remove log files after they've been read, if no new data has been
# written in the last 5 minutes. This is safe because the log shipper will just
# re-create the file and put any new data in it if data is written after that point.
# This stops us from running out of disk space.
remove_after_secs = 300

# Increase the chunk size to help vector keep up with quickly growing audit log files
max_read_bytes = 1085760 # 1 MiB

[sources.rds_logfiles_pre_patch_compatibility]
type = "file"
include = [
	"${LOG_DESTINATION_PATH:?LOG_DESTINATION_PATH must be specified for vector to run!}**/PrePatchCompatibility.log*"
]

# Really dumb multi-line handling to just suck the whole file into a single log
multiline.condition_pattern = ".*"
multiline.mode = "continue_through"
multiline.start_pattern = "^Executing Compatibility Checks"
multiline.timeout_ms = 180000 # Wait 3 mins for new lines before ingesting

# Same config as rds_logfiles_default
file_key = "logfile_path"
read_from = "beginning"
fingerprint.strategy = "device_and_inode"
remove_after_secs = 300

[transforms.vector_internal_logs_finished]
type = "remap"
inputs = ["vector_internal_logs"]
source = """
# Downcase all keys
. = map_keys(.) -> |key| { downcase(key) }

.logapp_name = "rds-log-shipper"
.service = "vector"
.level_name = .metadata.level
"""

[transforms.rds_metadata]
type = "remap"
inputs = ["rds_logfiles_default", "rds_logfiles_pre_patch_compatibility"]
source = """
.logapp_name = "rds"

# Assert that this exists
.logfile_path = string!(.logfile_path)

.rds = {}

# Our log shipper appends an RFC3339 timestamp to each logfile it creates. We can remove that to get the original file name back
logfile_path_without_suffix = replace(.logfile_path, r'\\.\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d+(Z|\\+[0-9:a-zA-Z]+)$', "")
relative_logfile_path_without_suffix = replace(logfile_path_without_suffix, "${LOG_DESTINATION_PATH:?LOG_DESTINATION_PATH must be specified for vector to run!}", "")

# Extract the RDS instance id from the logfile path
.rds.id = replace(relative_logfile_path_without_suffix, r'^(?P<db_id>[^/]+)/.*$', "$$db_id")

# Recreate the original path as shown in the RDS console
.rds.original_logfile_path = replace(relative_logfile_path_without_suffix, .rds.id + "/", "")

# Guess the database type and role based on its name
if match(.rds.id, r'^live-db.*-replica.*') {
	.rds.engine_type = "mysql"
	.rds.role = "replica"
} else if match(.rds.id, r'^live-db.*') {
	.rds.engine_type = "mysql"
	.rds.role = "primary"
} else if match(.rds.id, r'^named-lock.*') {
	.rds.engine_type = "mysql"
	.rds.role = "named-locks"
} else if match(.rds.id, r'^corp-.*') {
	.rds.engine_type = "postgres"
	.rds.role = "corp"
}
"""

# Split up the logs based on type so that we can parse each type separately
[transforms.rds_log_type]
type = "route"
inputs = ["rds_metadata"]

[transforms.rds_log_type.route]
audit = { type = "vrl", source = """match(string!(.rds.original_logfile_path), r'audit/.*')""" }
error = { type = "vrl", source = """match(string!(.rds.original_logfile_path), r'error/.*')""" }
upgrade = { type = "vrl", source = """match(string!(.rds.original_logfile_path), r'mysqlUpgrade')""" }
pre_patch_compatibility = { type = "vrl", source = """match(string!(.rds.original_logfile_path), r'PrePatchCompatibility.log')""" }

# Handles logs from the MariaDB audit plugin which RDS supplies for use with MySQL DBs
[transforms.finished_mysql_mariadb_audit_logs]
type = "remap"
inputs = ["rds_log_type.audit"]
source = """
.rds.log_type = "audit"

# See: https://mariadb.com/kb/en/mariadb-audit-plugin-log-format/
# Format is:
#   [timestamp],[serverhost],[username],[host],[connectionid],[queryid],[operation],[database],[object],[retcode]
parsed_message, err = parse_regex(.message, r'^(?P<year>\\d{4})(?P<month>\\d{2})(?P<day>\\d{2})\\s(?P<time>\\d{2}:\\d{2}:\\d{2}),(?P<database_server_host>[^,]*),(?P<database_user>[^,]*),(?P<connection_source_address>[^,]*),(?P<connection_id>[^,]*),(?P<query_id>[^,]*),(?P<operation_type>[^,]*),(?P<database_schema>[^,]*),(\\'(?P<sql_query>.*)\\')?,(?P<return_code>\\d*),(?P<protocol>[^,]*),?$')
if err == null {
	. |= parsed_message
	del(.message)

	# Format the timestamp as RFC3339
	.timestamp = string!(del(.year)) + "-" + string!(del(.month)) + "-" + string!(del(.day)) + "T" + string!(del(.time)) + "+00:00"

	# Try to extract the global correlation id from the SQL query (which we include as a comment at the start of the query)
	parsed_query, err = parse_regex(.sql_query, r'^\\s*/\\*\\s*(\\d+\\s+)?(?P<global_correlation_id>[a-f0-9\\-]{36})\\s*\\*/(?P<remaining_sql_query>.*?)$')
	if err == null {
		.global_correlation_id = parsed_query.global_correlation_id
		.sql_query = parsed_query.remaining_sql_query
	}

	# Unescape SQL
	if is_string(.sql_query) {
		.sql_query = replace(replace(string!(.sql_query), "\\\\n", "\n"), "\\\\'", "'")
	}

	.connection_id = parse_int(.connection_id) ?? .connection_id
	.query_id = parse_int(.query_id) ?? .query_id
	.return_code = parse_int(.return_code) ?? .return_code
}

# These are all info messages
.level = 6
.level_name = "INFO"
"""

[transforms.finished_mysql_error]
type = "remap"
inputs = ["rds_log_type.error"]
source = """
.rds.log_type = "error"

# Default. This should be overridden when we parse the message below. .level will be filled in by the main (host) vector instance when we send the message to it
.level_name = "ERROR"

# See: https://dev.mysql.com/doc/refman/8.0/en/error-log-format.html
# Format is:
#   time thread [label] [err_code] [subsystem] msg
. |= parse_regex(.message, r'^(?P<timestamp>\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{6}(Z|\\+[0-9:a-zA-Z]+))\\s+(?P<thread_id>[^ ]*)\\s+\\[(?P<level_name>[^\\]]*)\\]\\s+\\[(?P<error_code>[^\\]]*)\\]\\s+\\[(?P<subsystem>[^\\]]*)\\]\\s+(?P<message>.*)$') ?? .
"""

[transforms.finished_mysql_upgrade]
type = "remap"
inputs = ["rds_log_type.upgrade"]
source = """
.rds.log_type = "upgrade"

.level = 6
.level_name = "INFO"

# Format looks like:
#   time msg
parsed_message, err = parse_regex(.message, r'^(?P<date>\\d{4}-\\d{2}-\\d{2})\\s+(?P<time>\\d{2}:\\d{2}:\\d{2})\\s+(?P<message>.*)$')

if err == null {
	. |= parsed_message

	# Format the timestamp as RFC3339
	.timestamp = string!(del(.date)) + "T" + string!(del(.time)) + "+00:00"
}
"""

[transforms.finished_mysql_pre_patch_compatibility]
type = "remap"
inputs = ["rds_log_type.pre_patch_compatibility"]
source = """
.rds.log_type = "pre_patch_compatibility"

.level = 6
.level_name = "INFO"

# No parsing. These are actually just a big multi-line blob of text, but we can leave it as is line-by-line
"""

[transforms.finished_unknown]
type = "remap"
inputs = ["rds_log_type._unmatched"]
source = """
.rds.log_type = "unknown"

# No parsing to do: just leave the message as-is
"""

[transforms.rds_all_finished]
type = "remap"
inputs = ["finished_*"]
source = """
if is_string(.timestamp) {
	.timestamp = to_timestamp(.timestamp) ?? .timestamp
}
engine_type = .rds.engine_type || "unknown"
db_role = .rds.role || "unknown"
log_type = .rds.log_type || "unknown"
.service = "{{engine_type}}-{{db_role}}-{{log_type}}" ?? "unknown"
"""

# Collect internal metrics and forward them to the host vector instance for export
[sources.vector_internal_metrics]
type = "internal_metrics"

# Make a metric to explicitly count all the RDS logs, grouped by DB and type
[transforms.rds_log_metrics]
type = "log_to_metric"
inputs = ["rds_all_finished"]
[[transforms.rds_log_metrics.metrics]]
type = "counter"
# I don't think this does anything for counters, but it needs to be specified and the field needs
# to exist, so use logapp_name WLOG
field = "logapp_name"
name = "rds_log_count"
tags.role = "{{.rds.role}}"
tags.engine = "{{.rds.engine_type}}"
tags.type = "{{.rds.log_type}}"
tags.id = "{{.rds.id}}"

# Comment this sink out for local testing
[sinks.host_vector]
type = "vector"
inputs = ["rds_all_finished", "vector_internal_logs_finished", "vector_internal_metrics", "rds_log_metrics"]
# 44255 is a random port that I've decided to use for vector. The host
# vector instance will be listening on that port.
address = "172.17.0.1:44255"
# # Uncomment this sink for local testing
# [sinks.local_test_output]
# type = "file"
# inputs = ["rds_all_finished", "vector_internal_logs_finished"]
# path = "test_output.ndjson"
# encoding.codec = "json"
```

And this one accepts logs and metics from the top one and exposes them to prometheus:

```toml
### Global config ###
log_schema.host_key = "vector_host"
acknowledgements.enabled = true
# Where vector keeps track of its internal state
# This is the default, but let's be explicit
data_dir = "/var/lib/vector"

# TODO: I couldn't get this working (see: https://github.com/vectordotdev/vector/issues/15414)
# so we use an ugly systemd wrapper script instead. We should switch back to the secret backend
# when this bug gets fixed.
# # We use vector's 'secret' config feature to get the delivery stream name dynamically
# # from a script, even though it's not actually secret
# [secret]
# [secret.imds]
# type = "exec"
# command = ["/etc/vector/get_dynamic_log_data.rb"]
### Sources ###
[sources.vector_internal_logs]
type = "internal_logs"

[sources.cloud_init_logs]
type = "file"
include = ["/var/log/cloud-init-output.log"]
read_from = "beginning"

# All host and kernel logs
[sources.journald]
type = "journald"
current_boot_only = true

[sources.syslog_socket]
type = "syslog"
max_length = 134217728 # 128MiB
mode = "unix"
# We make an extra socket that can be easily mounted into docker containers (because it's not
# in /dev) which some containers want to use.
# Our base image will also symlink /dev/log to this for anything on the host which wants to
# write there.
path = "/var/run/rsyslog/log.sock"

[sources.syslog_localhost_tcp]
type = "syslog"
address = "127.0.0.1:514"
max_length = 134217728 # 128MiB
mode = "tcp"

[sources.syslog_localhost_udp]
type = "syslog"
address = "127.0.0.1:514"
max_length = 134217728 # 128MiB
mode = "udp"

[sources.syslog_docker_bridge_tcp]
type = "syslog"
address = "172.17.0.1:514"
max_length = 134217728 # 128MiB
mode = "tcp"

[sources.syslog_docker_bridge_udp]
type = "syslog"
address = "172.17.0.1:514"
max_length = 134217728 # 128MiB
mode = "udp"

# Meilisearch doesn't write logs to a file annoyingly, so we pull them out of stdout with docker
[sources.docker_meilisearch_logs]
type = "docker_logs"
# Include the container by either name or label
include_containers = ["compose_meilisearch_"]
include_labels = ["SERVICE_TAGS=progname__meilisearch"]

# Allow data from another vector instance from inside a docker container to send us logs
[sources.vector_docker_bridge]
type = "vector"
# 44255 is a random port that I've decided to use for vector
address = "172.17.0.1:44255"

# Allow data from another vector instance from anywhere on this box
[sources.vector_host]
type = "vector"
# 44255 is a random port that I've decided to use for vector
address = "127.0.0.1:44255"

# Split out logs and metrics, otherwise vector will try to run both of them through our remap
# transforms, which really doesn't work
[transforms.vector_split]
type = "route"
inputs = ["vector_docker_bridge", "vector_host"]
route.logs = { type = "is_log" }
route.metrics = { type = "is_metric" }

### Transforms ###
[transforms.tagged_vector]
type = "remap"
inputs = ["vector_split.logs"]
source = """
# Expect logapp name and service to come with each message
"""

[transforms.tagged_docker_meilisearch_logs]
type = "remap"
inputs = ["docker_meilisearch_logs"]
source = """
# Best effort to parse the log message
. |= parse_regex(.message, r'\\[(?P<timestamp>[^ ]*)\\s+(?P<level_name>[^ ]*)\\s+(?P<source_code_module>[^ ]*)\\]\\s+(?P<remote_host>[^ ]*)\\s+"(?P<method>[^ ]*)\\s+(?P<path>[^ ]*)\\s+(?P<protocol>[^ ]*)"\\s+(?P<status>[^ ]*)\\s+(?P<response_size_bytes>[^ ]*)\\s+(?P<host>[^ ]*)\\s+"(?P<user_agent_raw>.*?)"\\s+(?P<response_time>\\d.\\d+)') ?? .

# Remap nested fields
.source_code.module = del(.source_code_module)
.user_agent.raw = del(.user_agent_raw)

# Cast types
.timestamp = to_timestamp(.timestamp) ?? now()
.status = to_int(.status) ?? .status
.response_size_bytes = to_int(.response_size_bytes) ?? .response_size_bytes
.response_time = to_float(.response_time) ?? .response_time

# Add metadata
.logapp_name = "meilisearch"
.service = "meilisearch"
"""

[transforms.tagged_vector_internal_logs]
type = "remap"
inputs = ["vector_internal_logs"]
source = """
# Downcase all keys
. = map_keys(.) -> |key| {
    downcase(key)
}

.logapp_name = "host"
.service = "vector"
.level_name = .metadata.level

# Convert internal log levels into a syslog like numerical level field
if .level_name == "TRACE" {
    .level = 7
} else if .level_name == "DEBUG" {
    .level = 6
} else if .level_name == "INFO" {
    .level = 6
} else if .level_name == "WARN" {
    .level = 4
} else if .level_name == "ERROR" {
    .level = 3
}

"""

[transforms.tagged_cloud_init_logs]
type = "remap"
inputs = ["cloud_init_logs"]
source = """
# Downcase all keys
. = map_keys(.) -> |key| {
    downcase(key)
}

.logapp_name = "host"
.service = "cloud-init"
"""

[transforms.tagged_journald]
type = "remap"
inputs = ["journald"]
source = """
# Downcase all keys and remove a leading underscore from them (which kernal logs like to include for some reason)
. = map_keys(.) -> |key| {
    replace(downcase(key), r'^_', "", 1)
}

.logapp_name = "host"
.service = .syslog_identifier || .systemd_unit || .comm

# Convert syslog fields to a log 'level' key which is what we commonly use for filtering
if .syslog_facility == null {
    .syslog_facility = del(.syslogfacility)
}
.level = .level || .syslog_severity || .syslogseverity || .priority
"""

[transforms.tagged_syslog]
type = "remap"
inputs = ["syslog_*"]
source = """
if .appname == "rabbitmq" {
    # Remove the connection id at the start of the message so that we can parse it as JSON
    .message = replace(.message, r'^\\s*<[^>]*>\\s*-\\s*\\{', "{") ?? .message
}

# If the message is a valid JSON object, then merge it into the main log object.
# Stileapp and Rabbit both pass JSON into syslog like this
parsed_message, err = object(parse_json(.message) ?? null)
if err == null {
    # Merge parsed message into root
    . = merge(., parsed_message)
}

# Fix legacy camelCasing
if .request_log == null { .request_log = del(.requestLog) }
if .amqp_routing_key == null { .amqp_routing_key = del(.amqpRoutingKey) }
if .user_agent == null { .user_agent = del(.userAgent) }
if .content_length == null { .content_length = del(.contentLength) }
if .client_ip_address == null { .client_ip_address = del(.clientIpAddress) }
if .client_local_forwarded_for_ip_addresses == null { .client_local_forwarded_for_ip_addresses = del(.clientLocalForwardedForIpAddresses) }
if .client_tab_id == null { .client_tab_id = del(.clientTabId) }
if .is_internal_admin_request == null { .is_internal_admin_request = del(.isInternalAdminRequest) }
if .content_length_header == null { .content_length_header = del(.contentLengthHeader) }
if .global_correlation_id == null { .global_correlation_id = del(.globalCorrelationId) }
if .is_internal_admin_request == null { .is_internal_admin_request = del(.isInternalAdminRequest) }
if .open_trace_id == null { .open_trace_id = del(.openTraceId) }
if .view_trace_link == null { .view_trace_link = del(.viewTraceLink) }

# Simply downcase all remaining keys
. = map_keys(.) -> |key| {
    downcase(key)
}

# Convert syslog fields to a log 'level' key which is what we commonly use for filtering
if .syslog_facility == null {
    .syslog_facility = del(.syslogfacility)
}
.level = .level || .syslog_severity || .syslogseverity || .severity || .priority

# Set a timestamp field
.timestamp = to_timestamp(.timestamp || .time || .ts_utc || .@timestamp) ?? now()

# Pick the first non-empty, non-null value
.logapp_name = compact([.logapp_name, .appname, .service, .program, .facility, .progname, "unknown-syslog"])[0]

# Consul prepends @ to various fields for some reason
if .logapp_name == "consul" {
    if is_string(.@message) { .message = del(.@message) }
    if is_string(.@level) { .level = del(.@level) }
    if is_timestamp(to_timestamp(.@timestamp) ?? null) { .timestamp = del(.@timestamp) }
    if is_string(.@module) { .consul_module = del(.@module) }
}

# Rabbit has it's own weird field names
if .logapp_name == "rabbitmq" {
    if is_string(.msg) { .message = del(.msg) }
    if is_timestamp(to_timestamp(.time) ?? null) { .timestamp = del(.time) }
}
"""

[transforms.all_logs]
type = "remap"
inputs = ["tagged_*"]
source = """
# Ensure that .level is an integer. Otherwise, move it to .level_name
if .level != null {
    level_int, err = to_int(.level)

    if err == null {
        .level = level_int
    } else {
        .level_name = del(.level)
    }
}

# Normalise level name
if is_string(.level_name) {
    .level_name = upcase(.level_name) ?? .level_name

    # Canonicalize some level names
    if .level_name == "WARNING" {
        .level_name = "WARN"
    } else if .level_name == "CRITICAL" || .level_name == "CRIT" {
        .level_name = "FATAL"
    } else if .level_name == "PANIC" {
        .level_name = "EMERG"
    }
}

# Convert level name to level if level isn't set
if .level == null && .level_name != null {
    # Try converting the level name back into an integer log level
    if .level_name == "TRACE" || .level_name == "DEBUG" {
        .level = 7
    } else if .level_name == "INFO" {
        .level = 6
    } else if .level_name == "NOTICE" {
        .level = 5
    } else if .level_name == "WARN" {
        .level = 4
    } else if .level_name == "ERROR" {
        .level = 3
    } else if .level_name == "FATAL" {
        .level = 2
    } else if .level_name == "ALERT" {
        .level = 1
    } else if .level_name == "EMERG" {
        .level = 0
    }
}

# Add cannonical level names if they're not already set
if .level != null && .level_name == null {
    if .level == 7 {
        .level_name = "DEBUG"
    } else if .level == 6 {
        .level_name = "INFO"
    } else if .level == 5 {
        .level_name = "NOTICE"
    } else if .level == 4 {
        .level_name = "WARN"
    } else if .level == 3 {
        .level_name = "ERROR"
    } else if .level == 2 {
        .level_name = "FATAL"
    } else if .level == 1 {
        .level_name = "ALERT"
    } else if .level == 0 {
        .level_name = "EMERG"
    }
}

# Ensure as much AWS metadata as we can
if .aws == null {
    .aws == {}
}
if .aws.availability_zone == null {
    .aws.availability_zone = "${AVAILABILITY_ZONE:?AWS availability zone must be provided for this environment!}"
}
if .aws.region == null {
    .aws.region = "${REGION:?AWS region must be provided for this environment!}"
}
if .aws.instance_id == null {
    .aws.instance_id = "${INSTANCE_ID:?AWS instance id must be provided for this environment!}"
}
if .aws.instance_type == null {
    .aws.instance_type = "${INSTANCE_TYPE:?AWS instance type must be provided for this environment!}"
}
if .aws.account_id == null {
    .aws.account_id = "${ACCOUNT_ID:?AWS account id must be provided for this environment!}"
}

# Ensure as much host metadata as we can
if !is_object(.host) {
    .host == {}
}
if .host.ip_address == null {
    .host.ip_address = "${IP_ADDRESS:?IP address must be provided for this environment!}"
}
if .host.public_ip_address == null {
    public_ip = "${PUBLIC_IP_ADDRESS}"
    if !is_empty(public_ip) {
        .host.public_ip_address = public_ip
    }
}
if .host.hostname == null {
    hostname, err = get_hostname()

    if err == null {
        .host.hostname = hostname
    }
}

# Ensure stack id
if .stack_id == null {
    # Get it from the envrironment (provided by the init.sh script via get_dynamic_log_data.rb)
    stack_id = "${STACK_ID}"
    if !is_empty(stack_id) {
        .stack_id = stack_id
    }
}

# Sanity check the timestamp field
.timestamp = timestamp(.timestamp) ?? now()
if (.timestamp > now() ?? true) || (.timestamp < to_timestamp(to_unix_timestamp(now()) - 2592000, "seconds") ?? true) {
    if .testonly_dont_change_timestamp != true {
        # Sometimes tests stub time and produce crazy timestamp values in the future or the
        # distant past, so we correct those to the current time. 2592000 is the number of seconds in
        # a month.
        .timestamp = now()
    }
}

# Ensure that we have a logapp_name
.logapp_name = string(.logapp_name) ?? "unknown"

# Normalise the logapp name to be only lower case letters, numbers and dashes
.logapp_name = replace(downcase(.logapp_name), r'(?i)[^a-z0-9\\-\\.]+', "-")

# Normalise the name of error log fields
if .error == null && is_object(.exception) && is_string(.exception.message) {
    .error = del(.exception)
}
if .error == null && is_object(.e) && is_string(.e.message) {
    .error = del(.e)
}

# Make a nice link to all requests with the same GCID
if .global_correlation_id != null {
    # Convert the log TS to unix to make it easy to manipulate
    unix_timestamp = to_unix_timestamp(.timestamp)
    .link_request_logs = join([
        "https://stile.chaossearch.io/#/analytics?pathname=%252Fkibana%252Fapp%252Fdiscover&kibana=%2523%252F%253F_g%253D(filters%253A!()%252CrefreshInterval%253A(pause%253A!t%252Cvalue%253A0)%252Ctime%253A(from%253A'",
        # From one hour ago.
        # Use a custom format string so that we can replace colons with the double-uri escaped colons (%253A) which kibana expects
        format_timestamp(to_timestamp(unix_timestamp - 3600) ?? .timestamp, format: "%Y-%m-%dT%H%%253A%M%%253A%S%.3fZ") ?? .timestamp,
        "'%252Cto%253A'",
        # To one hour in the future
        # Use a custom format string so that we can replace colons with the double-uri escaped colons (%253A) which kibana expects
        # Chose the correct index for the environment based on ACCOUNT_SHORTNAME.
        # When we get secrets working, use this rather than the ACCOUNT_SHORTNAME env var: SECRETTODO[imds.account_shortname]
        format_timestamp(to_timestamp(unix_timestamp + 3600) ?? .timestamp, format: "%Y-%m-%dT%H%%253A%M%%253A%S%.3fZ") ?? .timestamp,
        "'))%2526_a%253D(columns%253A!(_source)%252Cfilters%253A!()%252Cindex%253A${ACCOUNT_SHORTNAME:?AWS account shortname must be provided for this environment! It should look like dev|corp|prod etc.}-all-logs-view%252Cinterval%253Aauto%252Cquery%253A(language%253Alucene%252Cquery%253A'global_correlation_id%253A%252522",
        .global_correlation_id,
        "%252522')%252Csort%253A!())"
    ], "") ?? null
}

# Useful admin tools links
if (.principal || .principal_name) != null {
    .link_admin_tool_user = join(["https://stileapp.com/auinternal/internalAdmin/users/", (.principal || .principal_name)]) ?? null
}
if .institution_id != null {
    .link_admin_tool_institution = join(["https://stileapp.com/auinternal/internalAdmin/institutions/", to_string(.institution_id) ?? ""]) ?? null
}
if .subject_id != null {
    .link_admin_tool_subject = join(["https://stileapp.com/auinternal/internalAdmin/subjects/", to_string(.subject_id) ?? ""]) ?? null
}
if (.activity_id || .lesson_item_id) != null {
    .link_admin_tool_activity = join(["https://stileapp.com/auinternal/internalAdmin/activities/", to_string(.activity_id || .lesson_item_id) ?? ""]) ?? null
}
"""

### Sinks ###
[sinks.firehose_logs]
type = "aws_kinesis_firehose"
inputs = ["all_logs"]
# TODO: use secrets instead of a wrapper script providing an env variable as soon as the bug is fixed (see: https://github.com/vectordotdev/vector/issues/15414)
# stream_name = 'SECRETTODO[imds.delivery_stream_name]'
stream_name = "${DELIVERY_STREAM_NAME:?Firehose stream name must be provided for this environment! It should look like 'delivery-stream-logs-<dev|corp|prod etc.>-apse2'}"
encoding.codec = "json"

# [sinks.debug]
# type = "file"
# inputs = ["all_logs"]
# compression = "none"
# path = "/tmp/vector.log"
# encoding.codec = "json"
#
### Metrics ###
[sources.vector_internal_metrics]
type = "internal_metrics"

# We already have the prometheus node exporter, but I'm interested to see if we can replace it with vector, so
# let's collect the host metrics too
[sources.host_metrics]
type = "host_metrics"
scrape_interval_secs = 15

# Define a prometheus scrape endpoint
[sinks.prometheus_export]
type = "prometheus_exporter"
inputs = [
    "vector_internal_metrics",
    "host_metrics",
    # Include any metrics forwarded from another vector instance
    "vector_split.metrics"
]
address = "0.0.0.0:9111" # Chose 9111 as the canonical port for vector metrics on each instance
buffer.when_full = "drop_newest" # Don't let metrics pile-up
```
