### ISSUE TITLE
Low metrics throughput to Datadog

### ISSUE THREAD

**Issue by ghost** [vectordotdev/vector#18163]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Sending metrics to datadog does not keep up with input, filling up buffers and eventually dropping them. The same VictoriaMetrics sink does not encounter the same issue.

See the config below, the victoriametrics sink ingests more metrics and yet the buffer does not fill up.

This is about 65k events/s

Potentially related to https://github.com/vectordotdev/vector/issues/18123

### Configuration

```text
datadog_metrics:
      type: datadog_metrics
      inputs:
        - limit_datadog_metric_cardinality
      default_api_key: {omitted}
      request:
        concurrency: adaptive
      buffer:
        type: disk
        max_size: 34360000000
        when_full: block
      batch:
          # Datadog will just close the connection on too large payloads
          # Datadog payload limits are 5242880 bytes raw, 512000 compressed,
          # but vector calculates sizes before serialization and compression
          # https://docs.datadoghq.com/api/latest/metrics/#submit-metrics
          max_events: 4000

    victoriametrics:
      inputs:
        - internal_metrics
        - route_metrics.datadog
      endpoint: {my_endpoint}
      type: prometheus_remote_write
      request:
        concurrency: adaptive
      buffer:
        type: disk
        # 8 GiB
        max_size: 8589934592
        when_full: block
```
```


### Version

vector 0.31.0 (aarch64-unknown-linux-musl 0f13b22 2023-07-06 13:52:34.591204470)

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by pierlucg1047** [comment]
I did a "binary search" to find a batch size that would reduce the ration of events_in/events_out in the buffer below 1, and that number is 250. 

So with
```
batch:
          max_events: 250
```
the buffer stops filling up and DD is able to ingest our metrics. Why is that number so low?

**Comment by dsmith3197** [comment]
Hey @pierlucg1047,

I'm sorry to hear that you are experiencing this issue, but I do think this is a different issue than the one linked. Could you clarify which buffers are filling up? Is it the `datadog_metrics `'s disk buffer or another buffer?

**Comment by pierlucg1047** [comment]
@dsmith3197 yes the `datadog_metrics` buffer fills up very fast unless `max_events` is set to 250 (and even then, the in/out ratio is close to 1)

**Comment by pierlucg1047** [comment]
Even with a low max_events, memory fills up very fast (limit is 12GiB) and CPU usage is very high (hits a 4vCPU cap)

Full config:
```yaml
api:
  address: "[::[]:8686"
  enabled: true
  playground: true
data_dir: /vector-data-dir
sinks:
  datadog_logs:
    buffer:
      max_size: 68720000000
      type: disk
      when_full: block
    compression: gzip
    default_api_key: ${DD_API_KEY}
    inputs:
      - datadog_logs_route._unmatched
      - datadog_logs_filter_info
    request:
      concurrency: adaptive
    type: datadog_logs
  datadog_metrics:
    batch:
      max_events: 500
    buffer:
      max_size: 34360000000
      type: disk
      when_full: block
    default_api_key: ${DD_API_KEY}
    inputs:
      - route_metrics.datadog
    request:
      concurrency: adaptive
    type: datadog_metrics
  datadog_metrics_internal:
    default_api_key: ${DD_API_KEY}
    inputs:
      - internal_metrics
    request:
      concurrency: adaptive
    type: datadog_metrics
  datadog_traces:
    buffer:
      max_size: 68720000000
      type: disk
      when_full: block
    compression: gzip
    default_api_key: ${DD_API_KEY}
    inputs:
      - datadog_agent.traces
    request:
      concurrency: adaptive
    type: datadog_traces
  victoriametrics:
    buffer:
      max_size: 8589934592
      type: disk
      when_full: block
    endpoint: http://grafana-mgmt-vm-vminsert.grafana:8480/insert/0/prometheus
    inputs:
      - internal_metrics
      - route_metrics.datadog
    request:
      concurrency: adaptive
    type: prometheus_remote_write
sources:
  datadog_agent:
    address: "[::[]:80"
    multiple_outputs: true
    type: datadog_agent
  internal_metrics:
    scrape_interval_secs: 5
    type: internal_metrics
transforms:
  datadog_logs_filter_info:
    condition: |
      .message.level != "info"
    inputs:
      - datadog_logs_remap_filter
    type: filter
  datadog_logs_remap:
    inputs:
      - datadog_agent.logs
    source: |
      # Datadog agents pass a "status" field that is normally stripped when ingested
      # directly by the Datadog backend
      del(.status)
    type: remap
  datadog_logs_remap_filter:
    inputs:
      - datadog_logs_route.to_filter
    source: |
      .message = parse_json!(.message)
      .message.level = downcase(string!(.message.level))
    type: remap
  datadog_logs_route:
    inputs:
      - datadog_logs_remap
    route:
      to_filter: |
        .service == "background-controller" || .service == "operator"
    type: route
  route_metrics:
    inputs:
      - datadog_agent.metrics
    route:
      datadog: "true"
    type: route
```
