### ISSUE TITLE
Loadbalance data between sinks

### ISSUE THREAD

**Issue by saeed-mcu** [vectordotdev/vector#18164]
### A note for the community

load balance input/source between multiple sink

### Use Cases

For example, I have one source (socket) and two sinks (kafka).
Input rate is 2K/s and I want to load balance between 2 sinks (each one 1K/s)

If I change the input of sinks to use the same source, the input is duplicated on both sinks and they have 2k/s, but I want them to have 1k  (round robin load balancing)

I want something like this:
```
                                    1K/s
                     +------------------------------+
                     |                           [sink]------------>
2K/s----->[source]---+                              |
                     |                           [sink]----------->
                     +-----------------------------+
                                     1 K/s
```

But vector output is something like this : 
```
                                    2K/s
                     +------------------------------+
                     |                           [sink]------------>
2K/s----->[source]---+                              |
                     |                           [sink]----------->
                     +-----------------------------+
                                     2 K/s
```

**Comment by hhromic** [comment]
We have the same use case and we implemented a Vector load balancing pipeline like this:
```yaml
api:
  enabled: true

sources:
  input:
    type: demo_logs
    format: syslog

transforms:
  partition:
    type: remap
    inputs: ["input"]
    drop_on_error: true
    source: |
      .partition = mod(to_int!(.timestamp), 2)
  route:
    type: route
    inputs: ["partition"]
    route:
      output1: '.partition == 0'
      output2: '.partition == 1'

sinks:
  output1:
    type: blackhole
    inputs: ["route.output1"]
    print_interval_secs: 0
  output2:
    type: blackhole
    inputs: ["route.output2"]
    print_interval_secs: 0
```
Basically we use a partitioner transform based on the modulo of the event timestamp and a router to distribute. This gives us a fairly uniform distribution of input events across N output sinks.

You can run the above pipeline and use `vector top` to see it distributing the load in real-time. We have been using the above approach for some time now and it performs quite well for us, specially in latest versions of Vector.

I do agree that it would still be great if Vector could implement simple load-balancing natively for maximum throughput.
