### ISSUE TITLE
Cannot read a Avro blob in Azure Blob Storage

### ISSUE THREAD

**Issue by tgib23** [vectordotdev/vector#18192]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm testing to sink blobs to Azure Blob Storage with `avro` encoding.
I'm already aware of [header issue](https://github.com/vectordotdev/vector/issues/16994), so I provide header file as shown below, but I still see `Not an Avro data file.` exception.

```
$ java -jar ./avro-tools-1.11.2.jar tojson --pretty 1690975950-1276951f-0e91-4524-a7d9-2b4431869261.log --reader-schema-file ./avro-test.avsc
23/08/02 20:56:40 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" org.apache.avro.InvalidAvroMagicException: Not an Avro data file.
        at org.apache.avro.file.DataFileStream.validateMagic(DataFileStream.java:115)
        at org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:123)
        at org.apache.avro.file.DataFileStream.<init>(DataFileStream.java:90)
        at org.apache.avro.tool.DataFileReadTool.run(DataFileReadTool.java:93)
        at org.apache.avro.tool.Main.run(Main.java:67)
        at org.apache.avro.tool.Main.main(Main.java:56)
```

I use kafka for the source and use transforms to extract only the value of `message` field. The blob is uploaded to Azure, but it doesn't seem appropriate avro file.

### Configuration

```text
sources:
      kafka_sink:
        type: "kafka"
        bootstrap_servers: "kafka-team-cluster-kafka-bootstrap.kafka-team.svc:9092"
        group_id: "vector-group"
        topics: [ "test-topic" ]
      vector_metrics:
        type: "internal_metrics"
    transforms:
      extract_message:
        type: remap
        inputs:
          - kafka_sink
        source: |-
          . = parse_json!(.message)
    sinks:
      azure_blob:
        type: azure_blob
        connection_string: xxxxx
        inputs: 
          - extract_message
        blob_prefix: "satoshi_vector_test/year=%Y/month=%m/day=%d/"
        batch:
          timeout_secs: 60
        encoding:
          codec: "avro"
          avro:
            schema: "{ \"type\": \"record\", \"namespace\": \"com.example\", \"name\": \"avrotest\", \"fields\": [ { \"name\": \"time\", \"type\": \"string\" }, { \"name\": \"name\", \"type\": \"string\" }, { \"name\": \"color\", \"type\": \"string\" } ] }"
        buffer:
          when_full: block
        compression: "none"
```

### Version

timberio/vector:0.31.0-distroless-libc

### Example Data

We see the following data when I consume message from kafka. For `name` and `color` part, I just made random strings.

```
{"time":"2023-08-09_09:26:35","name":"PVWhiK0cN4tMDGV90pxRKOCfacuCaN5hMg50PiHqYwggLRRtvItzmk6BKjXZko2SwqtXlnHqvPR6jjuC","color":"7xozv7Br9Rxbk3Lb1bZm7H8MOreezUsJviCxTJAziqpOtNuL7Sr6v0Ylt375HcxZDo5sJG2FyRm45WHI"}
```

### References

#16994

**Comment by tgib23** [comment]
Attaching avro file uploaded to Azure.

[1690975950-1276951f-0e91-4524-a7d9-2b4431869261.log](https://github.com/vectordotdev/vector/files/12300731/1690975950-1276951f-0e91-4524-a7d9-2b4431869261.log)

Also the content of the schema file (`avro-test.avsc` above) is as follows (I cannot attach because of the extension)
```
{"type":"record","namespace":"com.example","name":"avrotest","fields":[{"name":"time","type":"string"},{"name":"name","type":"string"},{"name":"color","type":"string"}]}
```

**Comment by pront** [comment]
Hi @tgib23, I tried to reproduce locally with a simpler configuration:

```
data_dir: "/Users/pavlos.rontidis/CLionProjects/vector/pront_tests/vector/sources/"

sources:
  my_file:
    type:      file
    include:
      - "/Users/pavlos.rontidis/CLionProjects/vector/pront_tests/vector/sources/avro_bug.txt"
    read_from: beginning
  vector_metrics:
    type: internal_metrics

transforms:
  extract_message:
    type:   remap
    inputs:
      - my_file
    source: |-
            . = parse_json!(.message)      

sinks:
  my_console_sink:
    type: console
    inputs:
      - extract_message
    encoding:
      codec: "avro"
      avro:
        schema: "{ \"type\": \"record\", \"namespace\": \"com.example\", \"name\": \"avrotest\", \"fields\": [ { \"name\": \"time\", \"type\": \"string\" }, { \"name\": \"name\", \"type\": \"string\" }, { \"name\": \"color\", \"type\": \"string\" } ] }"
```

The above didn't reproduce the bug you mentioned.

If you hookup your kafka source and replace your sink with `my_console_sink`, do you still see a crash?
