### ISSUE TITLE
`sample` component overwrite `sample_rate` field from the original events

### ISSUE THREAD

**Issue by richardfan1126** [vectordotdev/vector#18215]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The `sample` component will add a field `sample_rate` into the log event.

If the original event has the field with the same name, it will be overwritten, which cause data loss.

### Configuration

```yaml
sources:
  http:
    type: http_server
    address: 0.0.0.0:8080

transforms:
  unwrap:
    type: remap
    inputs:
      - http
    source: |
      . = parse_json!(string!(.message))
  sample:
    type: sample
    inputs:
      - unwrap
    rate: 1

sinks:
  console:
    type: console
    inputs:
      - sample
    encoding:
      codec: json
```

### Version

0.31.0

### Example Data

Input data:

```json
{"foo":"bar","sample_rate":"testing"}
```

Output data:
```json
{"foo":"bar","sample_rate":"1"}
```

**Comment by richardfan1126** [comment]
Duplicate with https://github.com/vectordotdev/vector/issues/18098

**Comment by jszwedko** [comment]
Hi @richardfan1126 !

This is an issue we are hoping to address through a new opt-in feature we released in v0.31.0 to have Vector add its metadata fields to a separate namespace. See https://vector.dev/blog/log-namespacing/ for a description of how this works and how to enable it. Would you want to try that out and see how it works for you? You can leave any feedback on it here: https://github.com/vectordotdev/vector/issues/17796.

**Comment by richardfan1126** [comment]
@jszwedko Thanks for the suggestion, Log Namespacing is a great feature. 

However, it seems like only apply to source and have no effect on `sample` component.

Here's my testing:

* Configuration:
   ```yaml
   data_dir: $DATA_DIR
   schema:
     log_namespace: true
   
   sources:
     http:
       type: http_server
       address: 0.0.0.0:8080
   
   transforms:
     unwrap:
       type: remap
       inputs:
         - http
       source: |
         . = parse_json!(string!(.message))
     sample:
       type: sample
       inputs:
         - unwrap
       rate: 1
   
   sinks:
     console:
       type: console
       inputs:
         - sample
       encoding:
         codec: json
   ```

* Input:
   ```json
   {"foo":"bar","sample_rate":"testing"}
   ```

* Output
   ```json
   {"foo":"bar","sample_rate":"1"}
   ```
