### ISSUE TITLE
Support advanced prometheus scrape settings

### ISSUE THREAD

**Issue by benjaminhuo** [vectordotdev/vector#18304]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Drop or keep specific metrics when scraping Prometheus metrics to avoid collecting too many unused data.

### Proposal

Add similar configuration like [OpenTelemetry Prometheus Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver):
```yaml
receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: k8s
            ......
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              regex: "true"
              action: keep
            metric_relabel_configs:
            - source_labels: [__name__]
              regex: "(request_duration_seconds.*|response_duration_seconds.*)"
              action: keep
```

### References

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
https://opentelemetry.io/docs/collector/configuration/#receivers
