### ISSUE TITLE
`native_json` codec is not serializing/deserializing `EventMetadata`.

### ISSUE THREAD

**Issue by neuronull** [vectordotdev/vector#18570]
Discovered while adding to the Vector protobuf definition for the native codec, as part of https://github.com/vectordotdev/vector/pull/18405.

Doing so necessitated regenerating the fixture files used in the native codec unit tests.
This led to a test failure in `current_native_decoding_matches` , which compares the Event that is created by deserializng a json fixture file with a proto fixture file, that should have been encoded with the same Event when the files were generated.

The offending bits are that the `EventMetadata.value` is not being handled by the `native_json` codec, but it is being handled by the `native` (protobuf) codec. This boils down to the fact that the EventMetadata is being skipped by the serde deserialize/serialize for the Event structs. This could largely be due to the fact that not skipping that field means that the `EventMetadata` must satisfy the trait requirements of `configurable_component`.

There are basically three problems here:

1. the `native_json` codec it seems _should_ be handling the `value` field of `EventMetadata`.
2. the unit test `current_native_decoding_matches` fails on master due to 1
3. methodology we are using to perform the unit tests around the native codecs, is clearly currently prone to errors, as it involves applying a patch file, which inherently gets out of date over time and if we don't regenerate the data files often enough, we can get into a situation such as this, where we've had multiple releases containing this inconsistency.

**Comment by dsmith3197** [comment]
This would be fixed by https://github.com/vectordotdev/vector/issues/18779

**Comment by thomasqueirozb** [comment]
This is still reproducible with Vector 0.58.0.

I added a value to `EventMetadata.value` with a remap transform and encoded the event using `native_json`:

```yaml
sources:
  input:
    type: stdin

transforms:
  add_metadata:
    type: remap
    inputs:
      - input
    source: |
      %issue_18570.probe = "preserve-me"

sinks:
  output:
    type: console
    inputs:
      - add_metadata
    encoding:
      codec: native_json
```

The encoded event did not contain the metadata:

```json
{"log":{"host":"COMP-MD7RLJ4PMV","message":"hello","source_type":"stdin","timestamp":"..."}}
```

I then passed that output through a `native_json` decoder and copied the decoded metadata into the event:

```yaml
sources:
  input:
    type: stdin
    decoding:
      codec: native_json

transforms:
  inspect_metadata:
    type: remap
    inputs:
      - input
    source: |
      .decoded_metadata = %

sinks:
  output:
    type: console
    inputs:
      - inspect_metadata
    encoding:
      codec: json
```

Command:

```sh
printf 'hello\n' \
  | vector --quiet --config vector-18570-encode.yaml \
  | vector --quiet --config vector-18570-decode.yaml
```

Result:

```json
{"decoded_metadata":{},"host":"COMP-MD7RLJ4PMV","message":"hello","source_type":"stdin","timestamp":"..."}
```

The `%issue_18570.probe` value does not survive the `native_json` round trip.
