### ISSUE TITLE
kafka source and aws s3 sink not work 

### ISSUE THREAD

**Issue by waney316** [vectordotdev/vector#18658]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

My vector version is 0.32.1. When I use kafka as the source and AWS S3 as the sink, it doesn't seem to work because the number of kafka consumer groups is 0. I suspect that this is due to the use of buffer.type=disk in the sink。

```toml
    [sources.input-backup]
    type = "kafka"
    bootstrap_servers = "${KAFKA}"
    group_id = "group"
    topics = [ "^xxxx.*"]
    decoding.codec="json"
    auto_offset_reset = "latest"

    [sinks.bak]
    type = "aws_s3"
    healthcheck.enabled = false
    inputs = [ "input-backup" ]
    auth.access_key_id = "xxxxxxxxxx"
    auth.secret_access_key = "xxxxx"
    endpoint = "xxxxx"
    key_prefix = "{{ topic }}/%Y/%m/%d/"
    bucket = "xxx"
    region = "xxxxx"
    compression = "gzip"
    encoding.codec="json"
    framing.method   = "newline_delimited"    
    filename_time_format = "%Y%m%d%H%M%S%3f_archive"

    batch.max_bytes = 2073741824
    batch.timeout_secs = 3600
    buffer.type = "disk"
    buffer.max_size = 268435488 
    buffer.when_full  = "block"
```

### Version

0.32.1

**Comment by jszwedko** [comment]
Hi @waney316 !

Can you clarify what you mean by "doesn't work". Are you seeing events consumed from Kafka (you could use `vector tap` or the internal metrics to check this). Is it attempting to send events to AWS S3? Your batch configuration is such that you may need to wait 10 minutes to see that flushing.

It should be unrelated, but given you are using Kafka I do think adding a disk buffer to the `aws_s3` sink only introduces downsides and no upsides given Kafka is already providing durability.

Also, could you also add the debug logs here?

**Comment by waney316** [comment]
> Hi @waney316 !
> 
> Can you clarify what you mean by "doesn't work". Are you seeing events consumed from Kafka (you could use `vector tap` or the internal metrics to check this). Is it attempting to send events to AWS S3? Your batch configuration is such that you may need to wait 10 minutes to see that flushing.
> 
> It should be unrelated, but given you are using Kafka I do think adding a disk buffer to the `aws_s3` sink only introduces downsides and no upsides given Kafka is already providing durability.
> 
> Also, could you also add the debug logs here?

tks ，It seems like you're encountering an issue where, under buffer.type = "disk", the buffer size remains unchanged. Additionally, Vector's top command shows that there are no incoming events from the Kafka source (source=input-kafka-backup), and the sink (Sinks=bak-to-cos) is not updating. What is the issue here? The following is a snippet of my configuration. 

```toml
[sources.input-kafka-backup]
type = "kafka"
bootstrap_servers = "${KAFKA}"
group_id = "xxxxxx"
topics = [ "^xxxxxx.*" ]
decoding.codec="json"
auto_offset_reset = "latest"

[sinks.bak-to-cos]
type = "aws_s3"
healthcheck.enabled = false
inputs = [ "input-kafka-backup" ]
auth.access_key_id = ""
auth.secret_access_key = ""
endpoint = "https://xxxxx.com"
key_prefix = "{{ topic }}/%Y/%m/%d/"
bucket = "xxxxxx"
region = "xxxxx"
compression = "gzip"
encoding.codec="json"
framing.method   = "newline_delimited"    
filename_time_format = "%Y%m%d%H%M%S%3f_archive"

batch.max_bytes = 209715200 
batch.timeout_secs = 900
buffer.type = "disk"
buffer.max_size = 734003200 
buffer.when_full = "block"
request.concurrency= "adaptive"
```

![image](https://github.com/vectordotdev/vector/assets/23314093/3133b7b0-3e50-4e17-9966-cc711535ce71)
![image](https://github.com/vectordotdev/vector/assets/23314093/eb608031-77dd-4fb2-9a95-00045d82de18)
