### ISSUE TITLE
Add timeout option for flushing buffers

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#187]
Any sink that builds a buffer should support a configurable timeout to ensure the buffer is flushed within the specified interval. For example, the HTTP sink:

```toml
[sink.out]
  type = "http"
  max_linger_time = 2
```

- Should there be a global default or should each sink choose a default? My choice is the latter since the default is depending on the sink.
- By updating the HTTP sink will any HTTP wrapper sink inherit this option?
