### ISSUE TITLE
datadog_logs sink doesn't use agent api key when buffer type is disk

### ISSUE THREAD

**Issue by slovci** [vectordotdev/vector#18700]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm not sure if this is by design or a bug, but I couldn't find any documentation regarding this behavior. Given the below configuration when the sink buffer.type is set to disk the default_api_key value is used to send the request to datadog rather than the stored api key from the incoming event.

```
sources:
  ddagent_input:
    type: datadog_agent
    address: 0.0.0.0:9000
    store_api_key: true

sinks:
  ddagent_log_output:
    type: datadog_logs
    inputs:
      - ddagent_input
    default_api_key: ${DD_API_KEY}
    buffer:
      type: disk
      max_size: 2147483648
```

### Version

0.30.0

### Example Data

With buffer.type left with the default value
```
Sending HTTP request. uri=https://http-intake.logs.datadoghq.com/api/v2/logs method=POST version=HTTP/1.1 headers={"content-type": "application/json", "dd-evp-origin": "vector", "dd-evp-origin-version": "0.30.0 (x86_64-unknown-linux-musl 38c3f0b 2023-05-22 17:38:48.655488673)", "dd-api-key": "agent-dd-api-key", "content-length": "437", "user-agent": "Vector/0.30.0 (x86_64-unknown-linux-musl 38c3f0b 2023-05-22 17:38:48.655488673)", "accept-encoding": "identity"}
```

With buffer.type set to disk
```
Sending HTTP request. uri=https://http-intake.logs.datadoghq.com/api/v2/logs method=POST version=HTTP/1.1 headers={"content-type": "application/json", "dd-evp-origin": "vector", "dd-evp-origin-version": "0.30.0 (x86_64-unknown-linux-musl 38c3f0b 2023-05-22 17:38:48.655488673)", "dd-api-key": "vector-default-api-key", "content-length": "437", "user-agent": "Vector/0.30.0 (x86_64-unknown-linux-musl 38c3f0b 2023-05-22 17:38:48.655488673)", "accept-encoding": "identity"}
```
