### ISSUE TITLE
Allow use of session name on AWS sinks/sources when using assume_role

### ISSUE THREAD

**Issue by agustin-munoz** [vectordotdev/vector#18717]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

When you need to access 3rd AWS account, or use a role instead of a user to access AWS services the assume_role mechanism is used. So far (v0.33.0) you can configure it by using:

```yaml
sinks:
  option1:
    type: aws_s3
    auth:
      assume_role: ${AWS_ASSUME_ROLE_ARN}
  option2:
    type: aws_s3
    auth:
      assume_role: ${AWS_ASSUME_ROLE_ARN}
      external_id: ${AWS_ASSUME_ROLE_EXTERNAL_ID}
```

So among the ARN of the role you want to assume you can also specify external_id. Taking in mind in AWS you can add a trust policy document in which you can restrict who can assume role limiting the use of specific external_id string, but also session_name (that's our case) it would be a nice feature to be able to set the name of session to use as a parameter or environment variable

### Proposal

Add the posibility to declare property auth.session_name on AWS sources/sinks, for example:

```yaml
sinks:
  option1:
    type: aws_s3
    auth:
      assume_role: ${AWS_ASSUME_ROLE_ARN}
  option2:
    type: aws_s3
    auth:
      assume_role: ${AWS_ASSUME_ROLE_ARN}
      external_id: ${AWS_ASSUME_ROLE_EXTERNAL_ID}
      session_name: ${AWS_ASSUME_ROLE_SESSION_NAME}
```

### References

#18689

### Version

vector 0.33.0 (x86_64-unknown-linux-gnu 89605fb 2023-09-27 14:18:24.180809939)
