### ISSUE TITLE
batch.max_bytes incompatible with Prometheus remote write sink

### ISSUE THREAD

**Issue by a26nine** [vectordotdev/vector#18960]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The `Prometheus remote write sink` [document](https://vector.dev/docs/reference/configuration/sinks/prometheus_remote_write/#batch) says that `batch.max_bytes` works with the sink, but it seems incompatible:
```
2023-10-25T17:00:37.231123Z ERROR vector::topology: Configuration error. error=Sink "ne_sink_vm_prod": This sink does not allow setting `max_bytes`
```

### Configuration

```
sinks:
  ne_sink_vm_prod:
    type: prometheus_remote_write
    healthcheck: false
    endpoint: xxx
    auth:
      strategy: basic
      user: xxx
      password: xxx
    batch:
      max_bytes: 5242880
      timeout_secs: 3
```

### Version

0.33.0

**Comment by neuronull** [comment]
Hello and thanks for filing this report.

Would you mind including your configuration for the sink?

**Comment by a26nine** [comment]
> Hello and thanks for filing this report.
> 
> Would you mind including your configuration for the sink?

Added.

```
sinks:
  ne_sink_vm_prod:
    type: prometheus_remote_write
    healthcheck: false
    endpoint: xxx
    auth:
      strategy: basic
      user: xxx
      password: xxx
    batch:
      max_bytes: 5242880
      timeout_secs: 3
```
