### ISSUE TITLE
CPU increase when saving vector config as secret instead of configmap

### ISSUE THREAD

**Issue by tomer-epstein** [vectordotdev/vector#18980]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello Vector team 
We have implemented "save vector config as secret".
But now we see **CPU increasement** and a **memory leak** in one of the agent pods.
Is that a bug? or did we configure it wrong?

**vector/values.yaml**
```yaml
role: "Agent"
vector:
  secretConfigEnabled: true # save values as secret instead of configmap
  extraVolumes: # should be set only if ugwSecretConfigEnabled is true
    - name: secret-volume
      secret:
        secretName: vector-values
  extraVolumeMounts: # should be set only if secretConfigEnabled is true
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
  args:
  - -w # watch for changes to config
  - --config-dir
  - /etc/secret-volume/ # if secretConfigEnabled is false then config-dir should be /etc/vector/ 
  - --log-format
  - json
```

**vector/templates/values-secret.yaml**
```yaml
{{- if and .Values.vector.customConfig (eq .Values.vector.secretConfigEnabled true) }}
apiVersion: v1
kind: Secret
metadata:
  name:  vector-values
type: Opaque
data:
  vector.yaml: |
{{ tpl (toYaml .Values.vector.customConfig) . | b64enc | indent 4 }}
{{- end }}
```

**vector/charts/vector/templates/configmap.yaml**
```yaml
{{- if not .Values.existingConfigMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vector.fullname" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
data:
  {{- if and (.Values.customConfig) (not .Values.secretConfigEnabled) }}
  vector.yaml: |
{{ tpl (toYaml .Values.customConfig) . | indent 4 }}
  {{- else if or (eq .Values.role "Aggregator") (eq .Values.role "Stateless-Aggregator") }}

```

![image](https://github.com/vectordotdev/vector/assets/57438361/033b16e4-a933-4432-8405-704057afc08b)

### Version

0.32.1-distroless-libc
