### ISSUE TITLE
object mapping for [kubernetes.labels.app] tried to parse field [app] as object, but found a concrete value #4386

### ISSUE THREAD

**Issue by DekelDevunet** [vectordotdev/vector#19136]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Im running vector for the first time to export logs from our kubernetes cluster. But I am getting the following error from the vector (agent mode)

> object mapping for [kubernetes.labels.app] tried to parse field [app] as object, but found a concrete value 

I saw that fluent-bit (https://github.com/fluent/fluent-bit/issues/4386) had workaround for it and wanted to check if there is any workaround that I need to setup with vector to overcome this error. 

I am running vector using helm chart (v0.28.0)

### Configuration

```text
role: "Agent"

env: 
  - name: ELASTIC_USER
    value: elastic
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-es-elastic-user
        key: elastic
service: 
  enabled: false
customConfig:
  data_dir: /var/lib/vector
  api:
    enabled: false
  sources:
    kubernetes_logs:
      type: kubernetes_logs
  transforms:
    kubernetes_logs_dedupe:
      type: dedupe
      inputs:
        - kubernetes_logs
  sinks:
    elasticsearch:
      type: elasticsearch
      inputs:
        - kubernetes_logs_dedupe
      compression: none
      auth: 
        strategy: basic
        user: ${ELASTIC_USER}
        password: ${ELASTIC_PASSWORD}
      endpoints:
        - https://elasticsearch-es-http.monitoring.svc:9200
      id_key: id
      tls:
        verify_certificate: false
      mode: data_stream
```

### Version

v0.28.0

**Comment by bruceg** [comment]
The error here appears to be coming from Elasticsearch and not the Kubernetes source. This suggests that this might be same issue as #8058. Could you confirm, @DekelDevunet?

**Comment by DekelDevunet** [comment]
I added the following and it worked, but in the docs it's mentioned to not use lua script as it's 60% than remap. I wonder if I would be able to achive the same with remap. If so I will add it here.
```
role: "Agent"

env: 
  - name: ELASTIC_USER
    value: elastic
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-es-elastic-user
        key: elastic
        
service: 
  enabled: false
  
customConfig:
  data_dir: /var/lib/vector
  
  api:
    enabled: false
    
  sources:
    kubernetes_logs:
      type: kubernetes_logs
      
  transforms:
    kubernetes_logs_dedupe:
      type: dedupe
      inputs:
        - kubernetes_logs
        
    dedot_labels:
      type: lua
      inputs: 
        - kubernetes_logs
      version: "2"
      hooks:
        process: process
      source: |-
        function process(event, emit)
            if event.log.kubernetes == nil then
                return
            end
            dedot(event.log.kubernetes.pod_labels)
            emit(event)
        end

        function dedot(map)
            if map == nil then
                return
            end
            local new_map = {}
            local changed_keys = {}
            for k, v in pairs(map) do
                local dedotted = string.gsub(k, "%.", "_")
                if dedotted ~= k then
                    new_map[dedotted] = v
                    changed_keys[k] = true
                end
            end
            for k in pairs(changed_keys) do
                map[k] = nil
            end
            for k, v in pairs(new_map) do
                map[k] = v
            end
        end

  sinks:
    elasticsearch:
      type: elasticsearch
      inputs:
        - dedot_labels
      compression: none
      auth: 
        strategy: basic
        user: ${ELASTIC_USER}
        password: ${ELASTIC_PASSWORD}
      endpoints:
        - https://elasticsearch-es-http.monitoring.svc:9200
      id_key: id
      tls:
        verify_certificate: false
      mode: data_stream

```

**Comment by DekelDevunet** [comment]
My final setup if someone in the future will need example for Kubernetes

```
role: "Agent"

env: 
  - name: ELASTIC_USER
    value: elastic
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-es-elastic-user
        key: elastic
service: 
  enabled: false
customConfig:
  # The directory used for persisting Vector state, such as on-disk buffers, file checkpoints, and more. Please make sure the Vector project has write permissions to this directory.
  data_dir: /var/lib/vector
  #https://vector.dev/docs/reference/api/
  api:
    enabled: false
  sources:
    # https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/
    kubernetes_logs:
      type: kubernetes_logs
      namespace_annotation_fields:
        namespace_labels: ""
      node_annotation_fields:
        node_labels: ""
      pod_annotation_fields:
        pod_annotations: ""

  transforms:
    drop_empty_containers:
      type: filter
      inputs:
        - kubernetes_logs
      condition: |-
        !(.kubernetes.container_name == null)
    drop_empty_message:
      type: filter
      inputs:
        - drop_empty_containers
      condition: |-
        !(strip_whitespace!(.message) == "") || !(.kubernetes.container_name == null)
    dedot_transform:
      type: remap
      inputs:
        - drop_empty_message
      source: |-
        . = map_keys(., recursive: true) -> |key| { replace(key, ".", "_") }
    drop_fields:
      type: remap
      inputs:
        - dedot_transform
      drop_on_abort: true
      source: |-
        del(.kubernetes.node_labels)
        del(.kubernetes.container_image_id)
        del(.kubernetes.namespace_labels)
        del(.kubernetes.pod_ip)
        del(.kubernetes.pod_ips)
        del(.kubernetes.pod_uid)
        del(.kubernetes.pod_labels.pod-template-hash)  
        del(.kubernetes.pod_labels.app_kubernetes_io/managed)  
        del(.kubernetes.pod_labels.app_kubernetes_io/instance)  
        del(.kubernetes.pod_labels.app_kubernetes_io/instance)  
  sinks:
    # https://vector.dev/docs/reference/configuration/sinks/elasticsearch
    elasticsearch:
      type: elasticsearch
      inputs:
        - drop_fields
      compression: none
      auth: 
        strategy: basic
        user: ${ELASTIC_USER}
        password: ${ELASTIC_PASSWORD}
      endpoints:
        - https://elasticsearch-es-http.monitoring.svc:9200
      id_key: id
      tls:
        verify_certificate: false
      mode: data_stream
```
