### ISSUE TITLE
Support json_lines encoding for s3 sink

### ISSUE THREAD

**Issue by kimxogus** [vectordotdev/vector#19170]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Write json files in newline delimited json.

```yaml
    sinks:
      s3:
        type: aws_s3
        inputs:
          - INPUT
        bucket: BUCKET
        key_prefix: PREFIX
        encoding:
          codec: json_lines
```

### Attempted Solutions

I tried `json` encoding, but it wrote json in json array in one line.

### Proposal

Implement `json_lines` encoding just like `json_lines` codec in [logstash](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json_lines.html)

### References

- https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json_lines.html

### Version

0.33.1

**Comment by hhromic** [comment]
Vector can do JSON lines encoding (we use it all the time). Try the `framing` option like this:
```yaml
encoding:
  codec: json
framing:
  method: newline_delimited
```
