### ISSUE TITLE
protobuf encoding not working

### ISSUE THREAD

**Issue by scMarkus** [vectordotdev/vector#19230]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Recently a protobuf encoder was added to the sinks. I wanted to use it to send protobuf messages via nats. Failing to do so I created a minimal example of what I am trying to do. Confusingly using the protobuf encoder makes the event not appear at all in the sinks `vector top` view. Looking at prometheus metrics of said sink the events passes through the buffer but does not appear in the actual component. Maybe its just me miss configuring it?

The minimal example can be reproduced by putting following files in the current directory and executing `run.sh` (podman required - in case of using docker simply replacing the `podman` command with `docker`)
**message.proto**
```proto
syntax = "proto3";
package test;

message SessionEvent {
  string event = 1;
}
```
**vector,yaml**
```yaml
---
api:
  enabled: true
sources:
  in:
    type: demo_logs
    format: apache_common
    lines:
    - line1
transforms:
  out:
    type: remap
    inputs: [in]
    source: ".event = .message"
sinks:
  tty_proto:
    type: console
    inputs: [out]
    encoding:
      codec: protobuf
      protobuf:
        desc_file: /message.desc
        message_type: test.SessionEvent
  tty_json:
    type: console
    inputs: [out]
    encoding:
      codec: json
```
**run.sh**
```sh
#!/bin/sh

protoc -I ./ -o message.desc ./message.proto

podman run --rm -it \
	-v ./message.desc:/message.desc \
	-v ./vector.yaml:/etc/vector/vector.yaml \
	docker.io/timberio/vector:0.34.1-debian
```

Changing the encoding in `tty_proto` sink does create 2 output events per input as expected. Maybe @goakley can help?

### Version

vector 0.34.1 (x86_64-unknown-linux-gnu 86f1c22 2023-11-16 14:59:10.486846964)
