### ISSUE TITLE
Azure Blob Storage Sink should respect the extension of the generated file depending on the encoding

### ISSUE THREAD

**Issue by ogarcia** [vectordotdev/vector#19250]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Basically, it is about being able to recognise the file format by its extension and not having to download and open it to find out what format it contains. In addition, there are tools that only support a specific type of extension, so if it does not have the correct extension, the tool does not understand the file.

### Attempted Solutions

There is not much that can be done right now. I have gone through all the documentation and I don't see any way to address the problem.

### Proposal

Right now when you use Azure Blob Storage Sink with a configuration similar to the following.
```yaml
azure:
  compression: none
  connection_string: DefaultEndpointsProtocol=https...(etc)
  container_name: vector
  encoding:
    codec: json
  inputs: [kubernetes_logs]
  type: azure_blob
```

The file it generates has a `.log` extension, from my point of view if the encoding you are using is `json` the file generated should have a `.json` extension instead of `.log`. 

Another option would be to let you set the extension you want for the file (default `log` but that you can configure it).

### Version

0.34.1
