### ISSUE TITLE
The librdkafka_options option does not comply well with the YAML standard

### ISSUE THREAD

**Issue by ogarcia** [vectordotdev/vector#19289]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When configuring a kafka sink (and possibly also with a kafka source) to specify the contents of `librdkafka_options` it is necessary that the keys are in quotes, this is not fully compatible with the YAML standard and makes several tools such as Helm remove these quotes which ends up producing that the system does not understand the `librdkafka_options` (see the issues detailed below).

### Configuration

```text
This is the configuration that works:

role: Agent
service:
    enabled: false
serviceHeadless:
    enabled: false
customConfig:
    data_dir: /vector-data-dir
    api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false
    sources:
        kubernetes_logs:
            type: kubernetes_logs
    sinks:
        kafka:
            type: kafka
            inputs:
                - kubernetes_logs
            bootstrap_servers: the.kafka.server:9093
            topic: aprettytopic
            encoding:
                codec: json
            sasl:
                enabled: true
                mechanism: PLAIN
                username: user
                password: pass
            librdkafka_options:
                "security.protocol": sasl_ssl


However, tools like Helm remove the quotation marks from `"security.protocol": sasl_ssl` leaving the final part like this:
```yaml
            sasl:
                enabled: true
                mechanism: PLAIN
                username: user
                password: pass
            librdkafka_options:
                security.protocol: sasl_ssl
```

This causes Vector to misinterpret that option.
```


### Version

0.34.1

### Debug Output

```text
In this case it is not necessary since it simply does not work without quotation marks.
```

### References

https://github.com/vectordotdev/helm-charts/issues/349
https://github.com/helm/helm/issues/12606

**Comment by jszwedko** [comment]
Hi @ogarcia !

Per https://github.com/helm/helm/issues/12606#issuecomment-1849212564 I don't think it actually matters if the keys with `.`s are quoted or not. Either way they are interpreted as a flat key. I tested with this `values.yaml`:

```yaml
role: Agent
service:
    enabled: false
serviceHeadless:
    enabled: false
customConfig:
    data_dir: /vector-data-dir
    api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false
    sources:
        kubernetes_logs:
            type: kubernetes_logs
    sinks:
        kafka:
            type: kafka
            inputs:
                - kubernetes_logs
            bootstrap_servers: the.kafka.server:9093
            topic: aprettytopic
            encoding:
                codec: json
            sasl:
                enabled: true
                mechanism: PLAIN
                username: user
                password: pass
            librdkafka_options:
                security.protocol: sasl_ssl
```

And saw the following:

```
2023-12-11T13:12:14.912178Z ERROR librdkafka: librdkafka: FAIL [thrd:sasl_ssl://the.kafka.server:9093/bootstrap]: sasl_ssl://the.kafka.server:9093/bootstrap: Failed to resolve 'the.kafka.server:9093': Name or service not known (after 38ms in state CONNECT, 1 identical error(s) suppressed)
```

The failure to resolve is expected since I don't have a Kafka instance running at that address, but note that it is using `sasl_ssl` as expected based on the configured `security.protocol: sasl_ssl`.

Are you seeing something different?
