### ISSUE TITLE
Vector agent helm chart doesn't working as expected with journald source 

### ISSUE THREAD

**Issue by kadhriesh** [vectordotdev/vector#19325]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have installed vector agent using helm chart.following values are my customised I am passing when i am installing helm chart on kubernetes

```
role: Agent
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false
  sources:
    journald_source:
      type: journald
  sinks:
   testout:
      type: console
      inputs:
        - journald_source
      target: stdout
      encoding:
        codec: text
```
`
Note : 
vector agent running as DaemonSet with root user and it's part of systemd-journal group 
with the above configuration I am having this issue. its looks like vector agent not able to find journalctl command on node but it actually has 

`vector::internal_events::journald: Error starting journalctl process. error=journalctl failed to execute: No such file or directory (os error 2) error_type="command_failed" stage="receiving" internal_log_rate_limit=true `

In node journalctl command found on the below path **/bin/journalctl**

pod describe

Normal  Scheduled  2m29s  default-scheduler  Successfully assigned vector/vector-ff4kj to kind-local-control-plane
  Normal  Pulled     2m30s  kubelet            Container image "timberio/vector:0.34.1-distroless-libc" already present on machine
  Normal  Created    2m30s  kubelet            Created container vector
  Normal  Started    2m30s  kubelet            Started container vector

### Version

 Image:         timberio/vector:0.34.1-distroless-libc

**Comment by jszwedko** [comment]
Hi @kadhriesh ,

Vector needs access to the `journalctl` command. This is mentioned here: https://vector.dev/docs/reference/configuration/sources/journald/#communication-strategy.

**Comment by kadhriesh** [comment]
@jszwedko yes it has access to execute but it not able to find. after I made changes in the above configuration 

```
`extraVolumes:
- name: bin
  hostPath:
    path: "/bin/"
extraVolumeMounts:
- name: bin
  mountPath: "/bin/"
  readOnly: true
`
```

I am getting following error

**INFO source{component_kind="source" component_id=journald_source component_type=journald}: vector::sources::journald: Starting journalctl.
journalctl: error while loading shared libraries: libsystemd-shared-247.so: cannot open shared object file: No such file or directory
2023-12-06T18:16:21.637726Z  WARN source{component_kind="source" component_id=journald_source component_type=journald}: vector::sources::journald: Journalctl process stopped.**

**Comment by jszwedko** [comment]
> journalctl: error while loading shared libraries: libsystemd-shared-247.so: cannot open shared object file: No such file or directory

It looks like you need to mount that shared library too since it is dynamically linked.

**Comment by kadhriesh** [comment]
@jszwedko can you help me how to do that which path i need to mount Here its is my pod description 

 **Mounts:
      /bin/ from bin (ro)
      /etc/vector/ from config (ro)
      /host/proc from procfs (ro)
      /host/sys from sysfs (ro)
      /var/lib from var-lib (ro)
      /var/lib/ from docker (ro)
      /var/log/ from var-log (ro)
      /var/run/docker.sock from docker-sock (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-n2bhl (ro)
      /vector-data-dir from data (rw)**

**Comment by kadhriesh** [comment]
@jszwedko  Thanks for jump on. below values working for me it started journalctl subprocess 

```
role: Agent
extraVolumes:
- name: bin
  hostPath:
    path: "/bin/"
- name: lib
  hostPath:
    path: "/lib/"
- name: usr
  hostPath:
    path: "/usr/lib/"
extraVolumeMounts:
- name: bin
  mountPath: "/bin/"
  readOnly: true
- name: lib
  mountPath: "/lib/"
  readOnly: true
- name: usr
  mountPath: "/usr/lib/"
  readOnly: true
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false
  sources:
    journald_source:
      type: journald
  sinks:
    cnap:
      type: console
      inputs:
      - journald_source
      target: stdout
      encoding:
        codec: text

```
but its not reading logs and printing in terminal 
Here is my pod logs

```
k logs vector-6wxn4            
2023-12-06T18:50:21.713080Z  INFO vector::app: Log level is enabled. level="info"
2023-12-06T18:50:21.714091Z  INFO vector::app: Loading configs. paths=["/etc/vector"]
2023-12-06T18:50:21.718288Z  INFO vector::topology::running: Running healthchecks.
2023-12-06T18:50:21.718381Z  INFO vector::topology::builder: Healthcheck passed.
2023-12-06T18:50:21.718413Z  INFO vector: Vector has started. debug="false" version="0.34.1" arch="aarch64" revision="86f1c22 2023-11-16 14:59:10.486846964"
2023-12-06T18:50:21.718934Z  INFO source{component_kind="source" component_id=journald_source component_type=journald}: vector::sources::journald: Starting journalctl.
2023-12-06T18:50:21.719645Z  INFO vector::internal_events::api: API server running. address=127.0.0.1:8686 playground=off
➜  ~ k exec -it vector-6wxn4 -- /bin/sh  
# journalctl 
No journal files were found.
-- No entries --
# journalctl -u kubelet
No journal files were found.
-- No entries --
# 
```

**Comment by jszwedko** [comment]
Awesome! Good to hear. I'll close this out but hopefully this issue helps others as well.

**Comment by dongho-jung** [comment]
Using journald requires the image to be tagged as *-debian tag (e.g. latest-debian).

```yaml
vector-agent:
...
  image:
    tag: latest-debian  # for journald binary
```
