### ISSUE TITLE
Unused output warning for `datadog_agent` source when output is disabled

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#19370]
With the following source config:

```yaml
sources:
  datadog_agent_in:
    type: datadog_agent
    address: 127.0.0.1:9125
    multiple_outputs: true
    disable_traces: true
```

Vector will output the following at startup:

```
2023-12-12T21:34:07.388726Z  WARN vector::config::loading: Source "datadog_agent_in.traces" has no consumers
```

As a user, I would expect that source output not to exist when it is explicitly disabled.
