### ISSUE TITLE
New `grep` transform

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#1939]
A while ago, when I integrated ELK stack for the first time, I was asked a simple question: "how do I grep with this?". The need for that was only temporary, but I think it would be cool to provide the same old grep feel for folks who are just adopting a structured logging approach.

I propose to add a transform that would act as close as possible to what grep does, and also to support grep features/flags as good as possible. Basically, drop all messages that don't match the regex pattern, but also `-v`, `-i` and so on.

**Comment by binarylogic** [comment]
@MOZGIII thanks for filing this. Could explain how this is different than https://vector.dev/docs/reference/transforms/filter/? Would it make more sense to add grep like functionality as a condition?

**Comment by MOZGIII** [comment]
To put simply: a transform that takes configuration in the form of `grep` command invocation.

Like: `grep -v TRACE` would ignore all the trace level logs, etc.
In the config:

```toml
[transforms.mygrep]
type = "grep"
...
command = "grep -v TRACE"
```

**Comment by sniperking1234** [comment]
Any progress on that issue?

**Comment by StephenWakely** [comment]
We are highly unlikely to implement this. As alluded to this can be worked around using a [filter transform](https://vector.dev/docs/reference/configuration/transforms/filter/) with the [`match`](https://vector.dev/docs/reference/vrl/functions/#match) VRL function.

```yml
transforms:
  my_transform_id:
    type: filter
    inputs:
      - my-source-or-transform-id
    condition: match(.message,  r'REGEX PATTERN')
```
