### ISSUE TITLE
ZStd compression should allow the configuration and use of custom dictionaries

### ISSUE THREAD

**Issue by mattb-nn** [vectordotdev/vector#19435]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

ZStd compression allows for the training of custom dictionaries on bespoke data sets.  Once trained, using these dictionaries substantially speeds up compression and decompression of data.

Vector should allow the use of custom, pre-trained dictionaries (training is out of scope) should the user supply one in the configuration.

### Proposal

The current behaviour of using no custom dictionary should continue but allow configuration of a dictionary within the `compression:` section of the config.

e.g.

```
sinks:
  my_sink_id:
    type: aws_s3
    inputs:
      - my-source-or-transform-id
    acl: authenticated-read
    bucket: my-bucket
    compression: zstd
      dictionary: /path/to/my/dictionary
```
