### ISSUE TITLE
Tremor sink

### ISSUE THREAD

**Issue by Licenser** [vectordotdev/vector#1944]
Hi! Greetings from the tremor team :)

today tremor and vector can talk over TCP with a configuration as mentioned below (excuse the yaml and toml salad)

```yaml
onramp:
  - id: vector
    type: tcp
    codec: string
    preprocessors:
      - lines
    config:
      host: 127.0.0.1
      port: 5000

binding:
  - id: vector
    links:
      '/onramp/vector/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/system::stdout/{instance}/in' ]

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
    links:
      in: [ out ]


mapping:
  /binding/vector/01:
    instance: "01"
```

and

```toml
# Input data.
[sources.in]
  type = "stdin"

# Output data
[sinks.out]
  type = "socket"
  inputs   = ["in"]
  address = "127.0.0.1:5000"
  mode = "tcp" 
  encoding = "text"
```

The socket sink in text mode uses a new line delimiter which tremors can accept via the `line` preprocessor - that is awesome, huzza standards! But it might be worth considering adding a tremor specific sink to use size prefixed encoding (or size delimited encoding, depending on what you want to call it). Tremor currently supports this via the `size-prefixed` preprocessor that decodes the first 64bit of every message in network byte order (big-endian) to determine the number of bytes the message contains.
