### ISSUE TITLE
Add support for global variable

### ISSUE THREAD

**Issue by jwislakPG** [vectordotdev/vector#19543]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We have logs from files etc. and we add extra information to stream of this logs. This information can be acquired from command by diffrent source type exec. How to add information from command to the stream of logs in other source.

Below example with adding kernel version to the streams of logs.
```
sources:
  dummy_logs:
    type: "demo_logs"
    format: "syslog"
    interval: 1
  kernel_version:
    type: exec
    command: [
      "uname",
      "-r"
    ]
    # default executed every 60s
    mode: scheduled

# Parse Syslog logs
# See the Vector Remap Language reference for more info: https://vrl.dev
transforms:
  parse_version:
    type: "remap"
    inputs:
      - kernel_version
    source: |
      version = string!(.message)
  add_version:
    type: "remap"
    inputs:
      - parse_version
      - dummy_logs
    source: |
      . |= parse_key_value!("kernel_version="+version)

sinks:
  print:
    type: "console"
    inputs:
      - "parse_version"
      - "add_version"
    encoding:
      codec: "json"
```

when I try to execute it I got following error:
```
2024-01-08T15:24:57.559847Z ERROR vector::topology::builder: Configuration error. error=Transform "add_version":
error[E701]: call to undefined variable
  ┌─ :1:41
  │
1 │ . |= parse_key_value!("kernel_version="+version)
  │                                         ^^^^^^^
  │                                         │
  │                                         undefined variable
  │                                         did you mean "true"?
  │
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples
```

### Proposal

Add support for global variables or something else that will be to pass value from one transform block to another.

### Version

0.34.2

**Comment by jszwedko** [comment]
Hi @jwislakPG !

The only way to feed that sort of data into Vector at the moment is either [environment variables](https://vector.dev/docs/reference/configuration/#environment-variables) at start-up or [secrets](https://vector.dev/highlights/2022-07-07-secrets-management/). I'd recommend something like:

```
KERNEL_VERSION=$(uname -r) vector --config ...
```

Then you can use:

```
. |= parse_key_value!("kernel_version="+${KERNEL_VERSION})
```

in the config. Would that work for you?

**Comment by jwislakPG** [comment]
Yes, I also wondering about similar solution. But I wanted to avoid declare environment variable in system and scraping this variable every transform block execution.
This command was example. The target command will be scraping version and build of application and this value will be changed frequently. This need create some of cron job to update value of this environment variable. That's is what I wanted to avoid and have all logic inside Vector config.

**Comment by DePinto** [comment]
I was looking for global variables as a way to help simplify tagging metrics.  What I was hoping to do is
```
transforms:
  parse-json:
    type: remap
    inputs:
      - source-json
    source: | 
      . = parse_json!(.message)
  set-variables:
    type: remap
    inputs:
      -parse-json
    source: |
      foo_global = .fooSource
  log-to-metric:
    type: log_to_metric
    inputs:
      - set-variables
    metrics:
      - type: gauge
        field: bar
        name: bar
      - type: gauge
        field: zaz
        name: zaz
  tag-metric:
    type: remap
    inputs:
      - log-to-metric
    source: | 
          .tags.foo= foo_global
```

What I'm trying to avoid (and posting here in case there's a better way without global variables)
```
transforms:
  parse-json:
    type: remap
    inputs:
      - source-json
    source: | 
      . = parse_json!(.message)
  log-to-metric:
    type: log_to_metric
    inputs:
      - parse-json
    metrics:
      - type: gauge
        field: bar
        name: bar
        tags:
          foo: '{{fooSource}}'
      - type: gauge
        field: zaz
        name: zaz
        tags:
          foo: '{{fooSource}}'
```
Which doesn't scale too great when you have a large number of metrics and tags.
