### ISSUE TITLE
prometheus_remote_write error invalid socket address syntax

### ISSUE THREAD

**Issue by Myasnik2000** [vectordotdev/vector#19588]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hey Vector team!
I'm trying to use vector inside my k8s cluster and I have configured Prometheus source like this 
```
sources:
  prometheus:
    type: prometheus_remote_write
    address: http://monitoring-stack-server.prometheus.svc:9090
```
In the address field, I'm using the k8s DNS address of the Prometheus service, but I'm getting this error 
` Configuration error. error=invalid socket address syntax`

### Configuration

```text
sources:
  prometheus:
    type: prometheus_remote_write
    address: http://monitoring-stack-server.prometheus.svc:9090
```
```


### Version

helm chart version: 0.30.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_
