### ISSUE TITLE
Enrichment table regex type support

### ISSUE THREAD

**Issue by srstrickland** [vectordotdev/vector#19725]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I would like to be able to configure some regexes in an enrichment table, and access them without having to call `to_regex()` on a enrichment field string every time (which vector warns me is expensive and will affect throughput).  If the data in the enrichment table could live as a regex in the first place, then I wouldn't have to do that.

I have several types of rules that I want to manage based on configuration.  The simplest is a set of rules for dropping incoming logs based on some regexes.  I would like to define a CSV with three columns: log-group (string), field-name (string), match-regex (regex).  As logs come in, I look up the rules based on log-groups, and if any of them match, I drop the record.  We get custom requests from teams (owners of particular log groups) to drop certain records based on basic field matching, and this would be a convenient way to express those without having to modify code every time (instead it's just a block of generic code looking at rules).

### Attempted Solutions

1. Write specific code for every log group (this becomes cumbersome to manage and error prone)
2. Use enrichment tables to manage the rules, but coerce the regex string to a regex via `to_regex()` on every use, which is expensive.

### Proposal

Support a `regex` type in the [enrichment table schema](https://vector.dev/docs/reference/configuration/global-options/#enrichment_tables.file.schema) which handles the creation of a regex once.

### Version

vector 0.35.0 (x86_64-unknown-linux-gnu e57c0c0 2024-01-08 14:42:10.103908779)

**Comment by jszwedko** [comment]
👍 thanks for opening this @srstrickland . I agree that the schema could be updated to allow for regular expressions to be compiled when Vector starts up.

**Comment by johnhtodd** [comment]
I very much like this idea.  Can you provide an example of how this would look in the way you envision it, in both a config file and in your code logic?  I'm not sure I'm following the example.  I, too, need regexp matching in enrichment files, but I was thinking an enrichment file that looked more like this (we do DNS work so I'm going to use DNS examples.)  The first line of the CSV file is the descriptions of the fields, as usual.

/etc/vector/domain-match.regexps:

```
matchDomainRegexp,ruleIdentifier
^(www|webserver|webhost|web\d)\.,website
^(smtp|post|mail\d)\.,mailserver
```

Then the enrichment configuration and transform VRL would look like this:
```

enrichment_tables:
  domain_match:
    type: "file"
    file:
      path: "/etc/vector/domain_match.regexps"
      encoding:
        type: "regexp"
    schema:
      matchDomainRegexp: "regexp"
      ruleIdentifier: "string"

transforms:
  . . .
  .DNSRecordCategory, err = get_enrichment_table_record("domain_match", { "MatchDomainRegexp": .responseData.question[0].etld.etld_plus })   
 . . .
```


So, if .responseData.question[0].etld.etld_plus  was equal to "www.example.com" then the result would be:

`"DNSRecordCategory.ruleIdentifier": "website"`



There are other questions, like "what if multiple rules match"?  I'd suggest that the first one in the config file would win.  I don't see how it would be possible to index a set of regular expression rules, and iteratively running through the whole list of rules to find ALL matches and then find the most specific (if that can even be defined!) seems somewhat expensive and un-necessary.

I suspect that regular expression rules would have to be a whole new type of enrichment, since they don't have the indexing component.
