### ISSUE TITLE
Vector not processing real time data

### ISSUE THREAD

**Issue by zhaoxinxin123** [vectordotdev/vector#19957]
**Problem**

>  "I want to real-time monitor my log file test.log. When I start Vector, it should work properly and collect all logs. However, when I continue writing logs to test.log, Vector doesn't continue to collect logs although it remains in a running state."

**Configuration**

```
sources:
  in:
    type: "file"
    include:
       - /root/*.log
    glob_minimum_cooldown_ms: 1000
    #ignore_older_secs: 10000
    fingerprint:
      strategy: "checksum"
      ignored_header_bytes: 0
      lines: 20
transforms:
  modify:
    type: remap
    inputs:
      - in
    source: |
      . = parse_json!(.message)
      .timestamp = parse_timestamp!(.timestamp, format: "%+")
      if is_timestamp(.timestamp) {
              .timestamp = to_unix_timestamp(.timestamp)
      }
      ., err = merge(., .alert)
      ., err = merge(., .flow)
      .proto_info=encode_json(.http)

sinks:
  out:
    inputs:
      - "modify"
    type: "clickhouse"
    endpoint: http://172.16.13.76:8123
    database: "alarm"
    table: "alert_info"
    skip_unknown_fields: true
```

**Version**
`0.36.0`
