### ISSUE TITLE
Support for loading secrets from AWS Secrets Manager

### ISSUE THREAD

**Issue by DarkAtra** [vectordotdev/vector#19990]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We recently wanted to resolve secrets for our vector configuration from AWS Secrets Manager and noticed that it's quite complicated to do so using [secret.exec](https://vector.dev/docs/reference/configuration/global-options/#secret.exec).

### Attempted Solutions

For context: we're running in EKS.

Our solution involved setting up an additional initContainer (so that we have access to the aws cli), using the aws cli to retrieve the secret and write them to disk (which is ugly), and then loading them:
```
secret:
  test:
    type: "exec"
    command: ["/usr/bin/cat", "/secrets/my-secret.json"]
```

### Proposal

It would be great to have this functionality built into vector itself.

```
secret:
  test:
    type: "aws_secretsmanager"
    secret_id: my-fancy-test-secret
```

### Version

0.35.0
