### ISSUE TITLE
Content-Type is not dictated by Compression Scheme as Docs Claim

### ISSUE THREAD

**Issue by hillmandj** [vectordotdev/vector#20012]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We had the following sink defined:

```
type: aws_s3
inputs:
  - outbound_router.redacted_route
bucket: ${S3_BUCKET_NAME}
key_prefix: [REDACTED]
compression: gzip
filename_extension: json.gz
region: ${S3_BUCKET_REGION}
encoding:
  codec: json
healthcheck:
  enabled: false
batch:
  # See this issue for more information: https://github.com/vectordotdev/vector/issues/14416
  # When upgrading vector from now on, we should ALWAYS check if there is a change to this behavior.
  #
  # 600 MB chunks, actually results in about 9MB compressed file sizes with the standard timeout.
  max_bytes: 600000000
  timeout_secs: 300
buffer:
  type: disk
  max_size: ${ZORG_LOGS_BUFFER_SIZE}
  when_full: block
```

The aws_s3 [content_type](https://vector.dev/docs/reference/configuration/sinks/aws_s3/#content_type) docs state:

> If not specified, the compression scheme used dictates this value. When compression is set to none, the value text/x-log is used.

However our objects do have `text/x-log` as the `Content-Type`, when from what I can tell it should be `application/gzip` based on the compression scheme.

<img width="1313" alt="Screenshot 2024-03-05 at 12 53 21 PM" src="https://github.com/vectordotdev/vector/assets/2695263/7a79675d-4d90-42fa-b8b5-f7af61ebc421">

We can add the `Content-Type` header, but this behavior seems to not be documented correctly so thought I'd point it out.

### Version

0.34.2
