### ISSUE TITLE
Additional metrics for tag cardinality limit to track metrics / tags limitation 

### ISSUE THREAD

**Issue by kaarolch** [vectordotdev/vector#20084]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently, the `tag_cardinality_limit` transforms do not provide any information about which metrics and tags have been limited. Introducing a counter to track limiting occurrences per tag and metric would be extremely valuable.

```
type: counter 
name: cardinality_rejections
    tags:
       metric_name: "{{ metric_name }}"
       tag_key: "{{ tag_key }}"
```

### Attempted Solutions

Currently we try to catch Rejection events and convert them to metrics: 

```
{"host":"d884473526aa","internal_log_rate_limit":true,"message":"Rejecting tag after hitting configured 'value_limit'.","metadata":{"kind":"event","level":"DEBUG","module_path":"vector::internal_events::tag_cardinality_limit","target":"vector::internal_events::tag_cardinality_limit"},"metric_name":"cardinality_metric_gauge_11","pid":1,"source_type":"internal_logs","tag_key":"cardinality","tag_value":"\"11\"","timestamp":"2023-09-11T15:16:06.924084943Z","vector":{"component_id":"metrics_cardinality_limit","component_kind":"transform","component_name":"metrics_cardinality_limit","component_type":"tag_cardinality_limit"}}
```
As you can see logs events already expose `"metric_name":"cardinality_metric_gauge_11"` and `"tag_key":"cardinality"` which could be use as tags. 

```
transforms: 
  internal_logs_filter_rejection:
    type: filter
    inputs:
      - vector_internal_logs
    condition: 'exists(.internal_log_rate_limit) && contains!(.message, "Rejecting tag after hitting configured")'
  internal_logs_add_count:
    type: remap
    inputs:
      - internal_logs_filter_rejections
    source: |
      .count = 1
  log_to_metrics_rejections:  
    type: log_to_metric
    inputs:
      - internal_logs_add_count
    metrics:
      - type: counter
         field: count
         name: cardinality_rejections
         tags:
            metric_name: "{{ metric_name }}"
            tag_key: "{{ tag_key }}"
            env: "${RUNTIME_ENVIRONMENT}"
```

Unfortunately during heavy spikes log events could be rate limited and our metric is not always very precise but allow to have  general overview which metrics are block by transformation. 

### Proposal

Cardinality limit transformation should emit telemetry metric: 
```
type: counter 
name: cardinality_rejections
    tags:
       metric_name: "{{ metric_name }}"
       tag_key: "{{ tag_key }}"
```

### Version

0.34.2
