### ISSUE TITLE
tests: allow to test the number of events emitted by a transform

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#20278]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Vector transforms have the ability to emit multiple events per input event if an array is assigned to the root `.` event:
```yaml
sources:
  logs:
    type: demo_logs
    format: syslog

transforms:
  remap:
    type: remap
    inputs: [logs]
    drop_on_error: true
    source: |
      . = split(string!(.message), pattern: s',')
```

However, there seems to be no way to test the expected numbers of events emitted:
```yaml
tests:
  - name: remap-test
    inputs:
      - insert_at: remap
        type: log
        log_fields:
          message: a,b,c
    outputs:
      - extract_from: remap
        conditions:
          - type: vrl
            source: |
              # there is no way here to test how many events were emitted by the transform
```

In our opinion, testing the number of events emitted by a transform is an important testing condition as well.

### Attempted Solutions

There does not seem to be a way to test the number of events emitted by a transform.

### Proposal

We propose to add an extra keyword to the `outputs` elements. For example:
```yaml
tests:
  - name: remap-test
    inputs:
      - insert_at: remap
        type: log
        log_fields:
          message: a,b,c
    outputs:
      - extract_from: remap
        number_of_events: 3
        conditions:
          - type: vrl
            source: |
              assert!(.message != "d")
```
For most use cases, `number_of_events` will typically be `1`. However, to fully preserve backwards compatibility, there should be no default and this check enforced only if `number_of_events` is present or non null.

### Version

vector 0.36.1 (x86_64-unknown-linux-gnu 2857180 2024-03-11 14:32:52.417737479)

**Comment by jszwedko** [comment]
Agree! This would be nice enhancement.

**Comment by jszwedko** [comment]
> After looking at the source code of the unit tests framework, maybe is not that hard for me to add this. Let me know if anybody in Team Vector is already planning on addressing this, or if you would like me to take a stab at this. If the latter, let me know what option name you would prefer for this.

It's in the backlog, but I'm not sure when we'll get to it so if it'd scratch an itch for you, have at it :) I would call it `expected_event_count`.

**Comment by davidcpell** [comment]
Something like this would be very useful for us bc we use Vector transforms for a lot of targeted load-shedding and it would be nice to have more reliable unit tests.

For `throttle` would all of the `inputs` be considered "received" by the transform within whatever time window is specified?

**Comment by saitonakamura** [comment]
Maybe instead of using specific fields to test for number of events we could have a vrl condition that works with the array of events directly? It might be beneficial for a couple of reasons
1. it would make testing for the length trivial: `assert_eq!(length(.), 5)`
2. it would allow to workaround https://github.com/vectordotdev/vector/issues/20277 because you would be able to test all the items in one condition
```
item1 = get(., [0])
assert_eq(item1.field, "value1")
item2 = get(., [1])
assert_eq(item2.field, "value2")
```
3. Frankly it's quite unclear that unit tests would behave the current way if multiple events are present (i.e. execute condition for each event separately), it's not mentioned in the docs, etc.

The drawback is that is that to be backwards-compatible it would either have to be a separate such conditions or the vector would have to come up with some way to make it partially backwards-compatible (like if there's only one event it would still pass the event itself, and not the array, but then it would make awkward to test that it's actually a single event and so on)

So I think I would prefer to see something like this

```
sources:
  logs:
    type: demo_logs
    format: syslog

transforms:
  remap:
    type: remap
    inputs: [logs]
    drop_on_error: true
    source: |
      . = split(string!(.message), pattern: s',')

tests:
  - name: remap-test
    inputs:
      - insert_at: remap
        type: log
        log_fields:
          message: a,b,c
    outputs:
      - extract_from: remap
        conditions:
          - type: vrl
            combine_events_into_array: true # naming is arbitrary
            source: |
              assert_eq(length(.), 3)
              assert_eq!(get!(., [0]), "a")
              assert_eq!(get!(., [1]), "b")
              assert_eq!(get!(., [2]), "c")
```
