### ISSUE TITLE
secret type aws_secrets_manager not working with a sequence of numbers as string value

### ISSUE THREAD

**Issue by sdomme** [vectordotdev/vector#20489]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi. I'm using the new secret type _aws_secrets_manager_. It seems not to cast string secret values correctly. Especially if the value is a sequence of numbers set as string.

For example having the following AWS secret as JSON:

```
{
  "username":"12345",
  "password":"abc"
}
```

With the following configuration

```
secret:
  loki:
    secret_id: "arn:aws:secretsmanager:....."
    type: "aws_secrets_manager"
sink:
  loki:
    auth:
      password: "SECRET[loki.password]"
      user: "SECRET[loki.username]"
      strategy: "basic"
    type: "loki"
```

I get the following error at vector startup:

```
2024-05-13T15:32:54.549469Z ERROR vector::cli: Configuration error. error=invalid type: integer `12345`, expected a string
```

### Version

0.38.0

**Comment by junaidk** [comment]
I had similar issue when using Helm to deploy.
Double quotes are removed from created configmap for vector config. 
This results in config values without quotes like this .

```
      auth:
        strategy: basic
        password: SECRET[loki.password]
        user: SECRET[loki.username]
``` 
If value is numeric and without quote it will be parsed as number.

You can define your username like this to render double quotes so that it is parsed as string by vector.

```
      auth:
        strategy: basic
        password: "SECRET[loki.password]"
        user: '{{ print "SECRET[loki.username]" }}
```
