### ISSUE TITLE
transforms configuration is not working correctly

### ISSUE THREAD

**Issue by oxxenix** [vectordotdev/vector#20573]
### Problem

The following configuration does not work. According to the documentation, it should work [https://vector.dev/highlights/2021-02-16-reduce-transform-remap-support/](2021-02-16-reduce-transform-remap-support)

### Configuration

```text
transforms:
  merge_stack_trace:
    type: reduce
    inputs:
      - files
    starts_when:
      type: remap
      source: |
        match(string!(.message), r'^\w.*') && .severity == "info"
    merge_strategies:
      message: "concat_newline"
```

### Version

vector 0.35.0

### Debug Output

`ERROR vector::cli: Configuration error. error=data did not match any variant of untagged enum AnyCondition`

**Comment by jszwedko** [comment]
Thanks for this report @oxxenix . There does seem to be a bug or documentation issue. This works:

```
transforms:
  merge_stack_trace:
    type: reduce
    inputs:
      - files
    starts_when: match(string!(.message), r'^\w.*') && .severity == "info"
    merge_strategies:
      message: "concat_newline"
```

That is, only the short-hand of providing a VRL condition works. You can't provide type/source.
