### ISSUE TITLE
Unable to suppress pod metadata with log_namespace: true

### ISSUE THREAD

**Issue by Anton0C** [vectordotdev/vector#20682]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have the following configuration in the Vector agent:

```
schema:
    log_namespace: true
...
sources:
    source_kubernetes:
      type: kubernetes_logs
      pod_annotation_fields:
        container_id: ""
        container_image_id: ""
        pod_labels: ""
        pod_owner: ""
...
    transform_namespace:
      type: remap
      inputs:
        - source_kubernetes
      source: |
        .event_data = .
        .meta_data = %
```

However, the pod_annotation_fields are still present, and the suppression doesn’t work as expected according to the documentation: https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#node_annotation_fields

What is wrong with the configuration, and how can I suppress these fields?

### Version

0.38.0-debian
