### ISSUE TITLE
end to end acknowledgement not supported in kubernetes_log source

### ISSUE THREAD

**Issue by ShahroZafar** [vectordotdev/vector#20752]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We are using `kubernetes_log` source with `kafka` sink. We initially started with disk buffer but we see that it has multiple issues especially [this](https://github.com/vectordotdev/vector/issues/18336). 
So we thought of shifting to memory buffer and rely on end to end ack feature of vector to ensure delivery. However, it seems that its not supported for `kubernetes_logs` even though it is supported for file source. Although kubernetes_logs source is based on `file` source, I wonder why its not supported in `kubernetes_log`.

### Attempted Solutions

```
customConfig:
  sources:
    kubernetes_logs:
      type: kubernetes_logs
      glob_minimum_cooldown_ms: 1000
      ingestion_timestamp_field: "ingest_timestamp"
  transforms:
    dedot_keys:
      type: remap
      inputs:
        - kubernetes_logs
      source: |
        . = map_keys(., recursive: true) -> |key| { replace(key, ".", "_") }
  sinks:
    kafka:
      type: kafka
      inputs:
        - dedot_keys
      bootstrap_servers: kafka:9092
      topic: vector
      encoding:
        codec: json
      compression: zstd
      batch:
        timeout_secs: 0.5
        max_bytes: 1000000
        max_events: 1000
      librdkafka_options:
        client.id: "vector"
        request.required.acks: "1"
      message_timeout_ms: 0
      buffer:
        type: memory
        when_full: block
        max_events: 500
```
### Proposal

Support end to end acknowledgements with kubernetes_log source

### Version

0.39.0
