### ISSUE TITLE
Strftime specifiers in template syntax should have support for log namespaces

### ISSUE THREAD

**Issue by tronboto** [vectordotdev/vector#20785]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The [documentation for strftime specifiers](https://vector.dev/docs/reference/configuration/template-syntax/#strftime-specifiers) in template syntax mentions:

> The value is derived from the timestamp field and the name of this field can be changed via the global timestamp_key option.

But this doesn't make sense in the context of log namespacing. The log namespacing docs suggest that you should be able to use the `set_semantic_meaning` function for this, but it doesn't seem to have any effect.

### Configuration

```text
sinks:
  my_sink_id:
    type: elasticsearch
    inputs:
      - mysource
    bulk:
      index: "{{ app_name }}-%Y-%m-%d"
...
```

### Version

0.38.0

**Comment by jszwedko** [comment]
It should use the timestamp indicated by `set_semantic_meaning`. Can you share a full config including the use of `set_semantic_meaning` that reproduces this issue?

**Comment by tronboto** [comment]
Here's a full config that should help reproduce this:

```
schema:
  log_namespace: true

sources:
  source_socket_tcp_json:
    type: socket
    address: 0.0.0.0:5555
    mode: tcp
    decoding:
      codec: json

transforms:
  transform_remap_set_timestamp:
    type: remap
    inputs:
      - source_socket_tcp_json
    source: |
      if exists(.@timestamp) {
        .@timestamp = parse_timestamp!(.@timestamp, "%+")
      }
      set_semantic_meaning(.@timestamp, "timestamp")

sinks:
  sink_elasticsearch:
    type: elasticsearch
    inputs:
      - transform_remap_set_timestamp
    endpoints: ["http://eshost:9200"]
    api_version: v7
    bulk:
      action: index
      index: "{{ app_name }}-%Y.%m.%d"
```

Then send an event like:

```
echo '{"app_name":"myapp","@timestamp":"2024-07-07T14:53:30.155226012Z"}' | nc localhost 5555
```

And the event will end up in `myapp-<today>` instead of `myapp-2024.07.07`
