### ISSUE TITLE
Default configuration file for deb and rpm package should use the journald source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2100]
To simplify installation for users using the Vector `.deb` and `.rpm` packages, I propose that we include a default configuration such as the following:

```toml
# ...

[sources.in]
  type = "journald"

[sources.out]
  inputs = ["in"]
  type = "console"
```
