### ISSUE TITLE
Timestamp Mismatch when Ingesting logs to Loki

### ISSUE THREAD

**Issue by shiblisec** [vectordotdev/vector#21054]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have been gathering data from multiple sources and then using vector to transform the data, I have remaped the `timestamp` fields for all my data sources, so now only one key identifier exisits `timestamp` for all my data sources. When I am ingesting the transformed logs into loki using the following sink configuration.

```
  loki:
     type: loki
     inputs: ["source1", "source2", "source3"]
     endpoint: http://localhost:3100
     encoding:
       codec: json
     labels:
      "source": "vector"
``` 

I am getting the following results on Grafana, as we can observe the Grafana is showing a different timestamp while the actual timestamp on the log mentions a different time.

![Screenshot 2024-08-12 at 4 28 52 PM](https://github.com/user-attachments/assets/1de26e50-0bc6-4a5c-bb03-baa40e20bbba)
![Screenshot 2024-08-12 at 4 29 24 PM](https://github.com/user-attachments/assets/e8232857-d51c-44e1-b75a-83e048dcf83d)

### Version

vector 0.40.0 (x86_64-apple-darwin 1167aa9 2024-07-29 15:08:44.028365803)
