### ISSUE TITLE
export shows N/A for income events for syslog:udp

### ISSUE THREAD

**Issue by mhbitman** [vectordotdev/vector#21206]
### A note for the community

To have better observability over vector I need to monitor input load but I am not able to count input events into syslog:udp

### Problem

in vector top and exporter I see N/A for input events while I can see their messages as output events for the same component.

![Screenshot 2024-08-30 at 13 53 56](https://github.com/user-attachments/assets/e1fc05e1-4d2a-4e17-a4c5-3706b853195f)

### Configuration

```text
sources:
  internal-metrics:
    type: internal_metrics
    namespace: vector
    scrape_interval_secs: 60
  syslog_udp:
    type: syslog
    mode: udp
    address: 0.0.0.0:514
```

### Version

vector 0.30.0 (x86_64-unknown-linux-gnu 38c3f0b 2023-05-22 17:38:48.655488673)

**Comment by 440hz** [comment]
### Version:
vector 0.44.0 (x86_64-unknown-linux-musl 3cdc7c3 2025-01-13 21:26:04.735691656)

### config:

```
data_dir: /vector-data-dir
api:
  enabled: true
  address: 0.0.0.0:8686
  playground: true
sources:
  vector-metrics:
    type: internal_metrics
    scrape_interval_secs: 30
  syslog-9000:
    address: 0.0.0.0:9000
    max_length: 1024000
    mode: udp
    type: syslog
sinks:
  metrics:
    type: prometheus_exporter
    inputs:
    - vector-metrics
    address: 0.0.0.0:9090
  clickhouse:
    type: clickhouse
    inputs:
      - syslog-9000
    database: syslogdb
    endpoint: http://dev-vector-clickhouse.unix.tensor.ru:8123
    table: access_logs
    auth:
      strategy: "basic"
      password: "iiS"
      user: "service_user"
```

### Problems:

N/A Events in and BytesIn

No metrics syslog in 
vector_component_received_events_total
vector_component_received_event_bytes_total

![Image](https://github.com/user-attachments/assets/ed39b8a0-77fc-4b87-80fe-c3fe97475b0d)
