### ISSUE TITLE
Read configuration from remote

### ISSUE THREAD

**Issue by PalanQu** [vectordotdev/vector#21326]
### Use Cases

For now Vector read configuration from local file, there is one scenario as follows

There are many kubernetes clusters and I setup a daemonset for each cluster, each node have many labels, like zone, region, I want to use some label to group Vector agents and assign different config.

Is this feature in the plan?

**Comment by jszwedko** [comment]
I'm not _super_ familiar with k8s, but wouldn't there be a way to apply different config maps in that scenario?

Could you describe a bit more what you would want from "remote configuration" loading? Where would it load it from? Using what transports, protocols, etc.?

**Comment by PalanQu** [comment]
@jszwedko  Thanks for your quick response, Maybe like following

Vector send a request to `Config server` for configuration

Request like following
```
# Vector1
curl http://xx:9000/config?region=foo1&zone=bar1

# Vector2
curl http://xx:9000/config?region=foo2&zone=bar2

# Vector3
curl http://xx:9000/config?region=foo3&zone=bar3&other=kar
```

Response

```
data_dir: "/var/lib/vector"
sources:
  apache_logs:
    type: "file"
    include:
      - "/var/log/apache2/*.log"
    ignore_older_secs: 86400
```

<img width="541" alt="image" src="https://github.com/user-attachments/assets/bdce5f4b-9786-4839-bc41-450196e5f931">


People can using Config server to group the Vector agents using envs, for example, zone=bar2 use kafka1 cluster as sink, others use kafka2 cluster as sink.

**Comment by jszwedko** [comment]
There is actually undocumented support for fetching configs over HTTP that you could try. You can configure it like:

```yaml
providers:
  type: http
  http:
    url: "some url"
```

Maybe that would be sufficient for you?

**Comment by jszwedko** [comment]
Err, sorry, it should be like:

```yaml
provider:
  type: http
  url: "some url"
```
