### ISSUE TITLE
The timestamp in InfluxDB is not using the event time from the record.

### ISSUE THREAD

**Issue by chnhao0723** [vectordotdev/vector#21503]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Our access logs come from AWS ALB and are stored in S3 as log files every 5 minutes. We process these S3 files and write them into Kafka.

We are experiencing an issue where the timestamp recorded in our log events is not correctly written to InfluxDB when processed by Vector.

- Log Event Timestamp:  
> 2024-10-14T06:17:41.859967Z
- Timestamp of Kafka Extraction and InfluxDB Insertion: 
> 2024-10-14 06:20:15 UTC

The timestamp stored in InfluxDB does not match the event timestamp.

### Configuration

```text
schema:
  log_namespace: true

sources:
  kafka-consumer:
    type: kafka
    auto_offset_reset: largest
    metrics:
      topic_lag_metric: true
    bootstrap_servers: ...
    group_id: kafka-consumer
    topics:
      - raw_slislo
    decoding:
      codec: json
    tls:
      enabled: true
      verify_certificate: true

sinks:
  stdout:
    type: console
    inputs:
      - kafka-consumer
    encoding:
      codec: json
    target: stdout
  influxdb:
    type: influxdb_logs
    inputs:
      - kafka-consumer
    org: ...
    endpoint: ...
    token: ...
    bucket: ...
    measurement: log.http
    tags:
      - t_method
      - t_status_code
      - t_http_group
    encoding:
      only_fields:
        - t_method
        - t_status_code
        - t_http_group
        - v_rts
        - v_host
        - v_path
```

### Version

0.38.0-distroless-static

### Example Data

**Log event from Kafka**

`
{
	"protocol": "https",
	"t_http_group": "__default__",
	"t_method": "GET",
	"t_status_category": 5,
	"t_status_code": 500,
	"t_team": "ipp",
	"timestamp": "2024-10-14T06:17:41.859967Z",
	"v_host": "10.1.217.58",
	"v_path": "/internal/ipp/v1/error",
	"v_query": "",
	"v_rts": 0.467
}
`

InfluxDB

<img width="1277" alt="Screenshot 2024-10-14 at 2 20 30 PM" src="https://github.com/user-attachments/assets/38af8b2e-a56f-4f50-9aff-7c894d2f079f">

**Comment by chnhao0723** [comment]
Thank you for the suggestion! I tried adding the remap transform with .timestamp = parse_timestamp!(.timestamp, "%+"), but unfortunately, the result is still the same.

```
 sources:
    kafka-consumer:
       ...
     
 transforms:
    operate:
      type: remap
      inputs:
        - kafka-consumer
      source: |-
        .timestamp = parse_timestamp!(.timestamp, "%+")
 
  sinks:
    influxdb:
        ...
```

**Comment by jszwedko** [comment]
Hmm, did you make sure to update the `inputs` for the sink?

**Comment by jszwedko** [comment]
Thanks @chnhao0723 . This is strange. I am able to reproduce with:

```yaml
sources:
  source0:
    type: stdin
    decoding:
      codec: bytes
transforms:
  transform0:
    inputs:
    - source0
    type: remap
    source: |
      .timestamp = from_unix_timestamp!(1729230377)
sinks:
  sink0:
    inputs:
    - transform0
    bucket: test
    endpoint: http://localhost:8086/
    org: test
    tags: []
    token: xxx
    type: influxdb_logs
    measurement: message
```

And then running:

```
echo hello | vector --config /tmp/vector.yaml
```

The timestamp shown in InfluxDB shows current time rather than the timestamp I set. What is weird is that if I add a debug message the line sent to InfluxDB seems to have the correct timestamp:

```
[src/sinks/influxdb/logs.rs:319:9] &output = b"message,host=xxx,metric_type=logs,source_type=stdin message=\"hello\" 1729230377000000000\n"
```

So I'm a bit of a loss why InfluxDB isn't using it 🤔

**Comment by jszwedko** [comment]
Actually, no, I was looking at an old measurement I sent. It does seem to be using the timestamp from the event.

**Comment by jszwedko** [comment]
With:

```yaml
sources:
  source0:
    type: stdin
    decoding:
      codec: bytes
transforms:
  transform0:
    inputs:
    - source0
    type: remap
    source: |
      .timestamp = from_unix_timestamp!(1729230377)
sinks:
  sink0:
    inputs:
    - transform0
    bucket: test
    endpoint: http://localhost:8086/
    org: test
    tags: []
    token: xxx
    type: influxdb_logs
    measurement: message2
```

And

```
echo hello | vector --config /tmp/vector.yaml
```

I see:

<img width="1324" alt="Screenshot 2024-10-18 at 4 07 52 PM" src="https://github.com/user-attachments/assets/15438495-edfa-41c7-8dfe-2be47aa427be">

Which has the expected timestamp.

Notably I am using the latest release of Vector and InfluxDB 2.
