### ISSUE TITLE
When terminating the vector of the S3 source, the imported message is terminated without completely processing it.

### ISSUE THREAD

**Issue by lhgwoo2** [vectordotdev/vector#21657]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We are using the vector to get the log from the s3 source and send it to Kafka sink.

However, when the vector is terminated, the data imported from the s3 source is not completely processed and is terminated.

Looking at the code, it seems that when a shutdown signal comes to the select statement, the existing processing work is dropped.

I wonder if this is the intended action.

We are hoping to send all the data and end it.

I look forward to your reply and thank you in advance.

---

src/sources/aws_s3/sqs.rs

```
async fn run(mut self) {
        let shutdown = self.shutdown.clone().fuse();
        pin!(shutdown);

        loop {
            select! {
             _ = &mut shutdown => break,
             _ = self.run_once() => {},
          }
        }
 }
```

### Version

0.41.1

**Comment by jszwedko** [comment]
Hi @hikhvar !

This is intended behavior. The message is marked as "consumed" as soon as Vector receives it, by default. To have Vector wait to mark the message as consumed until it has been successfully processed you can look set `acknowledgements.enabled` to `true`. See https://vector.dev/docs/about/under-the-hood/architecture/end-to-end-acknowledgements/ for more details. I hope this helps!

**Comment by lhgwoo2** [comment]
Hi @jszwedko 
Thank you for your advice
However, even though we added the value acknowledge.enabled=true, it still ends without processing all the values of the messages that have been read.

I share the contents of our config value and test data.

```
1 message - 1 object file (10000 row logs in 1 object)

We set up to import one message at a time.

When stopped in the middle of a vector run, 
expected : 10000 or 20000 or 30000...

but actual : 13729 or 26430 ...


------
api:
    enabled: true

timezone: "UTC"

acknowledgements:
    enabled: true


sources:
 
    s3_logs: 
        type: aws_s3
        compression: auto
        acknowledgements:
            enabled: true
        ...
        sqs:
            max_number_of_messages: 1
            ...

sinks:
    logs_kafka_out:
        type: "kafka"
        ...
        acknowledgements:
            enabled: true
        encoding:
            codec: "json"
        buffer:
            type: "memory"
            max_events: 1000
            when_full: "block" 
        ...
```
