### ISSUE TITLE
prometheus_scrape source's query doesn't add the [] to mapping list

### ISSUE THREAD

**Issue by valleedelisle** [vectordotdev/vector#22049]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Result:

```
2024-12-18T03:55:00.342027Z DEBUG source{component_kind="source" component_id=src-metrics-prod-proxy component_type=prometheus_scrape}:http: vector::internal_events::http_client: Sending HTTP request. uri=https://myprometheus/federate?match=%7Bjob%3D%something%22%7D method=GET version=HTTP/1.1 headers={"accept": "text/plain", "user-agent": "Vector/0.43.1 (x86_64-unknown-linux-musl e30bf1f 2024-12-10 16:14:47.175528383)", "accept-encoding": "identity"} body=[empty]
```

### Configuration

```text
Sample config:


      src-metrics-prod-proxy:
        endpoints:
        - "https://myprometheus/federate"
        honor_labels: true
        scrape_interval_secs: 60
        scrape_timeout_secs: 45
        query:
          match:
            - '{job="something"}'
        tls:
          verify_certificate: false
          verify_hostname: false
        type: prometheus_scrape
```

### Version

vector 0.43.1 (x86_64-unknown-linux-musl e30bf1f 2024-12-10 16:14:47.175528383)

**Comment by jszwedko** [comment]
HI @valleedelisle !

I think I'm missing the issue here. Could you describe the expected behavior?

**Comment by sainad2222** [comment]
I tried by modifying your source config to include [] after match, something like this and it's working after that

```yaml
Sample config:


      src-metrics-prod-proxy:
        endpoints:
        - "https://myprometheus/federate"
        honor_labels: true
        scrape_interval_secs: 60
        scrape_timeout_secs: 45
        query:
          match[]:
            - '{job="something"}'
        tls:
          verify_certificate: false
          verify_hostname: false
        type: prometheus_scrape
```

But if we want to make it easier, I created a [PR](https://github.com/vectordotdev/vector/pull/22085) to replace `match` key with `match[]` at source while building url
