### ISSUE TITLE
Error with kafka source when specifying password via sasl (Vector 0.43.0)

### ISSUE THREAD

**Issue by hartfordfive** [vectordotdev/vector#22208]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm attempting to connect to a secured Kafka cluster with the appropriate username and password.   From my understanding, this is done via the `sasl` Kafka source configuration.

When starting a vector instances (in Kubernetes) with a Kafka sink such as this one:
```
src_kafka:
  type: kafka
  boostrap_servers: kafka01:9092,kafka02:9092,kafka03:9092
  commit_interval_ms: 2000
  auto_offset_reset: latest
  session_timeout_ms: 14000
  group_id: vector
  topics:
    - logs-topic-1
    - logs-topic-2
    - logs-topic-3
  sasl:
    enabled: true
    username: ${KAFKA_USER:?err}
    password: ${KAFKA_PASS:?err}
  librdkafka_options:
    heartbeat.interval.ms: "3500"
    fetch.max.bytes: "2097152"
    max.partition.fetch.bytes: "1048576" 
    queued.max.message.kbytes: "2048"
```

I observe the following error message:
```
ERROR vector::topology::builder: Configuration error.  error=source "src_kafka": Could not create kafka consumer: Client creation error: Invalid sasl.kerberos.kinit.cmd value: Property not available: "sasl.kerberos.keytab"
```

I don't see anything in the current Vector kafka source [documentation](https://vector.dev/docs/reference/configuration/sources/kafka/#sasl) (on 2025-01-14) about this `sasl.kerberos` parameter although I do see it in the [librdkafka client configuration](https://docs.confluent.io/platform/current/clients/librdkafka/html/md_CONFIGURATION.html).   I assume the librdkafka client configuration is being automatically built with the default value?   What can I do to resolve this issue as I'm currently blocked and can't consume form this cluster.

I appreciate the help.

### Version

0.43.0-distroless-libc
