### ISSUE TITLE
Missing documentation for secrets

### ISSUE THREAD

**Issue by satellite-no** [vectordotdev/vector#22234]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Missing fields in documentation for secrets.   The documentation [here](https://vector.dev/docs/reference/configuration/global-options/#secret) is vary vague around the setup of using secrets and does not mention "type" at all which when you try to run is a required field seen in below message.

```text
2025-01-17T15:00:57.456331Z ERROR vector::cli: Configuration error. error=missing field `type`
in `secret.aws_secrets_manager`
```

### Configuration

```text
secret:
  aws_secrets_manager:
    type: aws_secrets_manager
    secret_id: 'vector/my-secret'
```

### Version

vector 0.43.0 (aarch64-apple-darwin 88e017f 2024-12-03 22:44:54.502541095)

### Debug Output

```text

```

**Comment by pront** [comment]
Hi @satellite-no, I am going to add a sample config here in case it helps:

```
secret:
  test_backend:
    type: "test"
    replacement: "this_is_a_secret_value"

  exec_backend:
    type: "exec"
    command:
      - "./target/debug/secret-backend-example"

  file_backend:
    type: "file"
    path: "tests/data/secret-backends/file-secrets.json"

  directory_backend:
    type: "directory"
    path: "tests/data/secret-backends/directory-secrets"
    remove_trailing_whitespace: true

```

The docs are generated from code. I understand `type` can be unexpected without looking at the code: 
https://github.com/vectordotdev/vector/blob/aaa54ec9bb3052bd676f8baa2fb8d97324533c30/src/secrets/mod.rs#L21-L22

This is another example where `type` is required: https://vector.dev/docs/reference/configuration/transforms/log_to_metric/#metrics.type

I will take a look why the `SecretBackends` config is missing that.
