### ISSUE TITLE
Logs with level=DEBUG Not Collected in EKS Using Datadog Agent 7.57.2

### ISSUE THREAD

**Issue by neeltom92** [vectordotdev/vector#22262]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

**Description:**

I am using the Datadog Agent (version 7.57.2) to collect logs from my EKS clusters and send them to a Vector instance. Below is the relevant portion of my Helm chart values configuration:

```

  datadog:
    networkMonitoring:
      enabled: true
    confd:
      network.yaml: |-
        init_config:
        instances:
          - collect_aws_ena_metrics: true
    kubeStateMetricsCore:
      enabled: true
      annotationsAsTags:
        job:
          notification-channel: notification_channel
    logs:
      containerCollectAll: true
      enabled: true
    podAnnotationsAsTags:
      "log*": "%%label%%"
    podLabelsAsTags:
      "*": "%%label%%"

  agents:
    customAgentConfig:
      vector:
        logs:
          enabled: true
          url: "http://vector<endpoint>:8282"
    useConfigMap: true
    useHostNetwork: true
    containers:
      agent:
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

```
**Issue Details:**

For all my applications running in EKS clusters, logs with log level == DEBUG are not being collected by the Datadog Agent.
This issue occurs only in my production environment. In my development environment, the same setup collects debug logs without any issues.
The Agent is correctly forwarding logs to the configured Vector endpoint for other log levels.

**Additional Information:**

Datadog Agent version: 7.57.2
DD agent Helm chart configuration: As provided above.

**_I did Vector tap and checked and noticed that the logs for level=Debug is not even reaching Vector_**

**Observations:**

The `containerCollectAll` setting is enabled, and logs at other levels (e.g., INFO, WARN, ERROR) are being collected successfully.
The issue seems specific to DEBUG logs in production.

**Expected behavior:** 
The Datadog Agent should collect all logs, including DEBUG level, as it does in the development environment.

### Configuration

```text

```

### Version

0.36

### Debug Output

```text

```
