### ISSUE TITLE
Configuration Errors in YAML when encountering null value

### ISSUE THREAD

**Issue by nomalord** [vectordotdev/vector#22327]
When configuring vector in YAML, if a null value is encountered, a non indicative error is raised.
Basic example using amqp source (generated by the generate command):
```yaml
sinks:
  output:
    inputs: [test]
    connection_string: amqp://localhost:5672/%2f
    exchange: test
    routing_key: /
    type: amqp
    encoding:
      codec: json
    healthcheck:
      enabled: true
      uri: null
    buffer:
      type: memory
      max_events: 500
      when_full: block
```
The error returned is:
```bash
invalid type: unit value, expected any valid TOML value
```
