### ISSUE TITLE
Allow VRL expressions in Routing name fields.

### ISSUE THREAD

**Issue by satellite-no** [vectordotdev/vector#22427]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Allow for Dynamic routing to account for new and changing log sources.  Especially when using vector sinks to vector sources to split out the data flows back into a similar sources for downstream inputs.

```yaml
type: exclusive_route
inputs:
  - vector
route:
  - name: "{{ .source }}"
  	condition:
  		type: vrl
  		source: exists(.source)
```

### Attempted Solutions

NA

### Proposal

Allow for dynamic routing "VRL Expressions" in name field of exclusive routes.  Would require some guardrails but would be very handy.

### References

https://github.com/vectordotdev/vector/discussions/22423

### Version

vector 0.43.0
