### ISSUE TITLE
AWS Managed Opensearch Sink IAM Auth from ECS trying to auth to dashboards uri

### ISSUE THREAD

**Issue by tfmm** [vectordotdev/vector#22442]
### Discussed in https://github.com/vectordotdev/vector/discussions/22422

<div type='discussions-op-text'>

<sup>Originally posted by **tfmm** February 11, 2025</sup>
We have an aws-managed Opensearch cluster which is setup to auth via IAM and SSO (Okta) for humans.  When setting up the elasticsearch sink, it receives an auth error from opensearch that makes it seem like it is trying to auth to the dashboards endpoint.

Sink config: 
```
sinks:
  es_cluster:
    inputs:
      - alb_xform
    type: elasticsearch
    endpoints:
      - https://SUB_OS_URL:443
    bulk:
      index: "SUB_INDEX-%Y-%m-%d" # daily indices
    aws:
      region: SUB_REGION
    api_version: auto
    opensearch_service_type: managed
    healthcheck:
      enabled: false
```

Error:
```
2025-02-11T17:24:44.166755Z ERROR sink{component_kind="sink" component_id=es_cluster component_type=elasticsearch}:request{request_id=2}: vector::sinks::elasticsearch::service: Response contained errors. error_code="http_response_401" response=Response { status: 401, version: HTTP/1.1, headers: {"date": "Tue, 11 Feb 2025 17:24:44 GMT", "content-type": "text/plain; charset=UTF-8", "content-length": "0", "connection": "keep-alive", "access-control-allow-origin": "*", "www-authenticate": "X-Security-IdP realm=\"OpenSearch Security\" location=\"https://OKTA_URL\" requestId=\"REDACTED\""}, body: b"" }
```

The Endpoint does not have the /_dashboards uri appended to it, and is used successfully by other IAM-based tools to interface with opensearch. </div>

As I mentioned in the discussion, if I update the sink to have an AWS Auth section, then I get Signing errors: 

```
2025-02-14T13:45:12.656517Z ERROR sink{component_kind="sink" component_id=es_cluster component_type=elasticsearch}:request{request_id=1}: vector::sinks::util::retries: Not retriable; dropping the request. reason="client-side error, 403 Forbidden: {\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\\n\\nThe Canonical String for this request should have been\\n'POST\\n/_bulk\\ntimeout=60s\\ncontent-type:application/x-ndjson\\nhost:redacted.us-east-2.es.amazonaws.com\\nx-amz-date:20250214T134512Z\\nx-amz-security-token:TOKEN_REDACTED\\n\\ncontent-type;host;x-amz-date;x-amz-security-token\\nREDACTED'\\n\\nThe String-to-Sign should have been\\n'AWS4-HMAC-SHA256\\n20250214T134512Z\\n20250214/us-east-2/es/aws4_request\\nREDACTED'\\n\"}" internal_log_rate_limit=true
```

Is the elasticsearch sink unable to do awsv4 signing for managed opensearch? (Not serverless.) 

Current sink config, but I've tested many iterations/options. 

```
sinks:
  es_cluster:
    inputs:
      - alb_xform
    type: elasticsearch
    endpoints:
      - https://redacted.es.amazonaws.com:443
    bulk:
      index: "logs-%Y-%m-%d" # daily indices
    auth:
      strategy: aws
      region: us-east-2
    aws:
      region: us-east-2
    api_version: v8
    opensearch_service_type: managed
    healthcheck:
      enabled: false
```
