### ISSUE TITLE
Invalid netlink buffer length

### ISSUE THREAD

**Issue by zapdos26** [vectordotdev/vector#22487]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Getting the following error for the new TCP metric:
 
2025-02-20T22:54:35.389172Z ERROR source{component_kind="source" component_id=host_metrics component_type=host_metrics}: vector::internal_events::host_metrics: Failed to load tcp connection info. error=Could not parse netlink response: Decode error occurred: invalid netlink buffer: length field says 524293 the buffer is 4008 bytes long error_type="reader_failed" stage="receiving" internal_log_rate_limit=true

### Configuration

```text
sources:
  host_metrics:
    type: host_metrics

sinks:
  console:
    type: file
    path: host_metrics-text.log
    inputs:
      - host_metrics
    encoding:
      codec: json
~
```

### Version

vector 0.45.0-custom-ae84bcd9d (x86_64-unknown-linux-gnu debug=full)

### Debug Output

```text

```

**Comment by dontlaugh** [comment]
I am getting this same error with a very similar config. Here is the output of `uname -a`

> Linux desktop 6.9.3-76060903-generic #202405300957~1736980680~22.04~44ea8a9~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux

I installed vector via the .deb package instructions from your website. Vector version:

> % vector --version
vector 0.45.0 (x86_64-unknown-linux-gnu 063cabb 2025-02-24 14:52:02.810034614)

<details>
<summary>configuration file</summary>

```toml
[sources.system_metrics]
type = "host_metrics"

[transforms.metrics_to_logs]
type = "metric_to_log"
inputs = ["system_metrics"]

[transforms.format_logs]
type = "remap"
inputs = ["metrics_to_logs"]
source = '''
  .timestamp = now()
  .host, _ = get_hostname()
'''

[sinks.csv_output]
type = "file"
inputs = ["format_logs"]
path = "/tmp/stats/stats.json"
compression = "none"
encoding.codec = "json"

[sinks.csv_output.buffer]
type = "disk"
max_size = 268435488
```

</details>
