### ISSUE TITLE
[Metrics]:  remap skipped if namespace not set

### ISSUE THREAD

**Issue by akutta** [vectordotdev/vector#22500]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Context:

Scraping a prometheus endpoint exposed by Temporal with no name transformations provides a set of metrics with varying names.  One of which is `temporal_workflow_active_thread_count.`

We noticed that all remapping specifically around tags were being ignored; however, the metric was still showing up at the destination and I could tap the transformation and see the unmodified event exiting.

Wrote the following Test:

```
  - name: tags metrics without namespaces properly
    inputs:
      - insert_at: "host_metrics_tag"
        type: "metric"
        metric:
          name: "agent.aggregator.event"
          kind: "absolute"
          gauge:
            value: 0.077
          tags:
            kube_namespace: "foo"
    outputs:
      - extract_from: "host_metrics_tag"
        conditions:
          - type: "vrl"
            source: |-
              assert_eq!(.tags.service, "foo")
```

and got the following result:

```
test tags metrics without namespaces properly ... failed

check[0] for transforms ["host_metrics_tag"] failed conditions:

  condition[0]: source execution failed: 
error[E000]: function call error for "assert_eq" at (0:32): assertion failed: null == "foo"
  ┌─ :1:1
  │
1 │ assert_eq!(.tags.service, "foo")
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ assertion failed: null == "foo"
  │
  = see language documentation at https://vrl.dev/
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples


output payloads from ["host_metrics_tag"] (events encoded as JSON):
  {"name":"agent.aggregator.event","tags":{"kube_namespace":"foo"},"kind":"absolute","gauge":{"value":0.077}}
```

Raw event logged from tap (some tags removed):

```
{
  "name": "temporal_worker_task_slots_available",
  "tags": {
    "activity_type": "none",
    "endpoint": "http://10.179.182.135:9090/metrics",
    "exception": "none",
    "image_tag": "latest",
    "kube_app_instance": "stable",
    "pod_phase": "running",
    "worker_type": "WorkflowWorker",
    "workflow_type": "none"
  },
  "timestamp": "2025-02-12T01:02:47Z",
  "kind": "absolute",
  "gauge": {
    "value": 5998.0
  }
}
```

### Configuration

```text
sources:
  host_metrics:
    type: "datadog_agent"
    address: "0.0.0.0:8000"
    disable_logs: true
    disable_traces: true

transforms:
  host_metrics_tag:
    type: "remap"
    inputs:
      - "host_metrics"
    source: |-
      if is_nullish(.tags.service) && !is_nullish(.tags.kube_namespace) {
        .tags.service = .tags.kube_namespace
      }
      .tags.infrastructure_type = "aws"
      .tags = compact(.tags)

sinks:
  host_metrics_to_datadog:
    type: "datadog_metrics"
    inputs:
      - "host_metrics_tag"
    default_api_key: "${DD_API_KEY}"
```

### Version

0.44.0

### Debug Output

```text

```

### Additional Context

Unit Tests:

```
  - name: Set service tag to kube_namespace if service tag is absent
    inputs:
      - insert_at: "host_metrics_tag"
        type: "metric"
        metric:
          name: "agent.aggregator.event"
          namespace: "envoy"
          kind: "absolute"
          counter:
            value: 1
          tags:
            kube_namespace: "test-namespace"
    outputs:
      - extract_from: "host_metrics_tag"
        conditions:
          - type: "vrl"
            source: |-
              assert_eq!(.tags.service, "test-namespace")
  - name: tags metrics without namespaces properly
    inputs:
      - insert_at: "host_metrics_tag"
        type: "metric"
        metric:
          name: "agent.aggregator.event"
          kind: "absolute"
          gauge:
            value: 0.077
          tags:
            kube_namespace: "foo"
    outputs:
      - extract_from: "host_metrics_tag"
        conditions:
          - type: "vrl"
            source: |-
              assert_eq!(.tags.service, "foo")
```
