### ISSUE TITLE
Can the write function of internal metrics be made public?

### ISSUE THREAD

**Issue by czd890** [vectordotdev/vector#22584]
### A note for the community

When doing some complex transformations and filtering via remap, may want to record some metrics for inspection.

```
transforms:
  my_transform:
    type: remap
    source: |
      metric_counter_inc("processed_events", 1)
```
