### ISSUE TITLE
prometheus exporter seems not work as expected

### ISSUE THREAD

**Issue by idrissneumann** [vectordotdev/vector#22594]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

According to [this documentation](https://vector.dev/docs/reference/configuration/sinks/prometheus_exporter/) if we manage to transform data into this kind of JSON payloads:

```json
{
  "metric": {
    "gauge": {
      "value": 1.5
    },
    "kind": "absolute",
    "name": "memory_rss",
    "namespace": "app",
    "tags": {
      "host": "my-host.local"
    }
  }
}
```

The prometheus exporter should automatically transform this into openmetrics format printed on an http endpoint that can be scrapped by prometheus instances.

However, we tried this configuration of sinks:

```yaml
sinks:
  out:
    type: "console"
    inputs:
       - remap_nagios_metrics
    encoding:
      codec: "json"
    target: "stdout"
  nagios_metrics:
    type: "prometheus_exporter"
    inputs:
      - remap_nagios_metrics
    address: 0.0.0.0:9598
    default_namespace: "ems"
    buffer:
      type: "memory"
```

The stdout output seems to comply with the expected payload format:

```shell
$ docker-compose up --force-recreate
vector  | {"metric":{"gauge":{"value":3.0},"kind":"absolute","name":"my_alert","tags":{"file":"/data/nagios.log","host":"xxxxxx","kind":"SERVICE ALERT","status":"OK","type":"SOFT","vector_host":"yyyyyyy"}}}
vector  | {"metric":{"gauge":{"value":1.0},"kind":"absolute","name":"my_alert","tags":{"file":"/data/nagios.log","host":"xxxxxx","kind":"SERVICE ALERT","status":"WARNING","type":"HARD","vector_host":"yyyyyyy"}}}
vector  | {"metric":{"gauge":{"value":1.0},"kind":"absolute","name":"my_alert","tags":{"file":"/data/nagios.log","host":"xxxxxx","kind":"SERVICE ALERT","status":"WARNING","type":"SOFT","vector_host":"yyyyyyy"}}}
vector  | {"metric":{"gauge":{"value":2.0},"kind":"absolute","name":"my_alert","tags":{"file":"/data/nagios.log","host":"xxxxxx","kind":"SERVICE ALERT","status":"WARNING","type":"SOFT","vector_host":"yyyyyyy"}}}
vector  | {"metric":{"gauge":{"value":3.0},"kind":"absolute","name":"my_alert","tags":{"file":"/data/nagios.log","host":"xxxxxx","kind":"SERVICE ALERT","status":"OK","type":"SOFT","vector_host":"yyyyyyy"}}}
```

But when I reach the `http://localhost:9598/metrics` route, I have an empty response without any metrics.

Thanks for your help

### Configuration

```text
sinks:
  out:
    type: "console"
    inputs:
       - remap_nagios_metrics
    encoding:
      codec: "json"
    target: "stdout"
  nagios_metrics:
    type: "prometheus_exporter"
    inputs:
      - remap_nagios_metrics
    address: 0.0.0.0:9598
    default_namespace: "ems"
    buffer:
      type: "memory"
```

### Version

timberio/vector:0.44.0-distroless-libc

**Comment by pront** [comment]
Hi @idrissneumann, we need more info here like the full config. Do you see any error logs on Vector or on the other side? Anything strange on the Vector debug logs? 

Take a look at our debugging guide on what tools we offer: https://vector.dev/guides/developer/debugging/debugging/

**Comment by idrissneumann** [comment]
Hi @pront, sorry for the late answer. Nothing strange on the debug log, just an empty response for the prometheus sink http endpoint.
As you can see the console sink is also pretty ok and you have the JSON payload which is the output of the remap function.

I'll give you more config tomorrow. In the meantime your guide is responding 404.

Thanks for your help

**Comment by sabmirsad** [comment]
@idrissneumann  if you are using remap type in your transformer you are probably passing logs to prometheus_exporter, try using the `log_to_metric` type for transformer

**Comment by pront** [comment]
> [@idrissneumann](https://github.com/idrissneumann) if you are using remap type in your transformer you are probably passing logs to prometheus_exporter, try using the `log_to_metric` type for transformer

Thanks @sabmirsad, good point. @idrissneumann please confirm (or share your config)

**Comment by MozeBaltyk** [comment]
@sabmirsad  you are right, it the remap respect the data-model describe [here](https://vector.dev/docs/about/under-the-hood/architecture/data-model/metric/) 

@idrissneumann if you can confirm on your side ?

eg. :

```json
      . = map_values(metrics) -> |m| {
        {
          "timestamp": .timestamp,
          "name": "m.name",
          "kind": "absolute",
          "gauge": {
            "value": m.value
          },
          "tags": {
            "id": extract.id,
            "file": .tmp.file,
            "host": extract.host,
            "kind": extract.kind,
            "type": m.type,
            "status": m.status,
            "job": "vector",
            "instance": .host,
            "severity": m.severity,
            "raw": .tmp.message,
          }        
        }
```

then I can convert it with `log_to_metrics` in my `transforms:`:

```yaml
  convert_metrics:
    type: log_to_metric
    inputs:
      - remap_nagios_metrics
    all_metrics: true
    metrics: []
```

then it can be exported in a `sink` :

```yaml
  nagios_metrics:
    type: "prometheus_exporter"
    inputs:
      - convert_metrics
    address: 0.0.0.0:9598
    buffer:
      type: "memory"
```

then `http://localhost:9598/metrics` returning promql metrics ...
