### ISSUE TITLE
Redis doesn't resubscribe/reconnect to channel

### ISSUE THREAD

**Issue by andreyvital** [vectordotdev/vector#22615]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Apparently this has been recently implemented by redis-rs: https://github.com/redis-rs/redis-rs/pull/1408/files and I am not sure if it's handled by vector already.

However, the problem is: in case of a connection disruption, it doesn't automatically resubscribe.

```toml
[sources.production-beacons]
type = "redis"
data_type = "channel"
key = "events:(...)"
url = "redis://(...)"
```

Just an example of my config 👆🏻 

### Configuration

```text

```

### Version

0.45

### Debug Output

```text

```
