### ISSUE TITLE
Configure header on Prometheus Remote Write sink

### ISSUE THREAD

**Issue by Shuricky** [vectordotdev/vector#22613]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Problem
Currently on the [prometheus remote write sink](https://vector.dev/docs/reference/configuration/sinks/prometheus_remote_write/#tenant_id) there is no way to stamp custom HTTP headers. The only header that you can stamp is `X-Scope-OrgID` using the tenant_id config.

For comparison, the [HTTP sink ](https://vector.dev/docs/reference/configuration/sinks/http/) does allow configuring custom headers.

## Solution
Create a new field on the prometheus remote write sink called `headers` that will contain one or more header name to header value mappings. For example:
```
sinks:
  my_sink_id:
    type: prometheus_remote_write
    inputs:
      - my-source-or-transform-id
    tenant_id: my-domain
    header:
      "header-name": header-value
```
