### ISSUE TITLE
Add a jitter or schedule option to http_client source

### ISSUE THREAD

**Issue by mugen6** [vectordotdev/vector#22634]
I am using the `http_client` source to query 20 endpoints but there is currently no option for a schedule or jitter, so they are all called at once:
 ```
  endpoint1:
    type: http_client
    endpoint: http://endpoint1
    method: GET
    scrape_interval_secs: 600

  endpoint2:
    type: http_client
    endpoint: http://endpoint2
    method: GET
    scrape_interval_secs: 600
```

Adding a `jitter` option would  probably be easy to implement and it would greatly help to avoid a "thundering herd" situation when making multiple requests to an API.
```
  endpoint1:
    type: http_client
    endpoint: http://endpoint1
    jitter_secs: 5-10
```
Where `jitter_secs: 5-10` would mean sleep for a random time between 5 and 10 seconds before making the request.

or perhaps:
```
  endpoint2:
    type: http_client
    endpoint: http://endpoint2
    jitter_min: 5
    jitter_max: 10
```
Where both min and max are required.

Or if `jitter` is the wrong word:
    `wait_secs_min: 15`
    `wait_secs_max: 30`

I expect implementing a full cron syntax would be a lot more work and probably unnecessary.

### Version
0.45.0

**Comment by pront** [comment]
Hi @mugen6, this addition makes sense to me. I would probably also allow durations less than 1 second.

**Comment by mugen6** [comment]
I had another thought about this - what about multiple endpoints in one source? I noticed that other source types like `file` can take multiple inputs, so what about:
```
 endpoints_1_to_3:
   type: http_client
   endpoint:
     - http://endpoint1
     - http://endpoint2
     - http://endpoint3
   method: GET
   scrape_interval_secs: 600
```
Where the endpoints are queried sequentially. The use case would be for querying multiple endpoints on a REST API, so possibly want to enforce a rules that says the base URL has to be the same. The equivalent curl would be:

`curl http://endpoint1 --next http://endpoint2 --next http://endpoint3`

So that the http session (and SSL) is reused.

This is relevant to the discussion because it helps prevent REST API rate limiting. It also makes the config file a lot less verbose, because 80% of the source block is repeated code.
