### ISSUE TITLE
Splunk HEC source requires channel with acknowledgement disabled

### ISSUE THREAD

**Issue by objectbased** [vectordotdev/vector#22653]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When testing a basic Splunk HEC source I've noticed that when a payload is sent to the `/services/collector/raw` endpoint without a `X-Splunk-Request-Channel` you get the below response back.

`{ "text": "Data channel is missing", "code": 10 }`

Enabling or disabling `acknowledgments.enabled` does not change the results

The documentation linked below mentions that a request channel is **only** required when acknowledgement is enabled, but in Vector it looks like this is required for any payloads sent to the "raw" endpoint regardless if acknowledgement is enabled or not.

https://docs.splunk.com/Documentation/Splunk/9.4.1/Data/AboutHECIDXAck#About_channels_and_sending_data

When testing this setup against a Splunk HEC listener on a Splunk Enterprise System (v9.2.4) against the `/services/collector/raw`  endpoint with NO `X-Splunk-Request-Channel` header provided data is successfully collected and the below response is provided.

 `{ "text": "Success", "code": 0 }`

Therefore,  I would expect that this header/parameter is **optional** and only required when `acknowledgments.enabled = true`

### Configuration

```text
The below is my test configuration for Vector that I have setup which includes acknowledgment being disabled.

:
  hec_8088:
    type: splunk_hec
    address: 0:0:0:0:8088
    acknowledgements:
      enabled: false
    valid_tokens:
      - abc123
```

### Version

vector 0.44.0 (x86_64-unknown-linux-gnu)

### Debug Output

```text

```

**Comment by pront** [comment]
Hi @objectbased, can you also disabling acks like so `acknowledgements: false`? Let me know if that fixes the issue.

**Comment by objectbased** [comment]
> Hi [@objectbased](https://github.com/objectbased), can you also disabling acks like so `acknowledgements: false`? Let me know if that fixes the issue.

Sure, I switched out my config to be the below for testing (note I wrote these configs in YAML so if anything looks off please let me know!)

```
source:
  hec_8088:
    type: splunk_hec
    address: 0:0:0:0:8088
    acknowledgements: false
    valid_tokens:
      - abc123
```

I sent a test event to the `raw` endpoint and received the same error

{ "text": "Data channel is missing", "code": 10 }

**Comment by pront** [comment]
That's a build error for you right? 

```
sources:
  src0:
    type: splunk_hec
    address: 0.0.0.0:8088
    acknowledgements: false
    valid_tokens:
      - abc123

sinks:
  sink0:
    inputs:
      - src0
    target: stdout
    type: console
    encoding:
      codec: json
      json:
        pretty: true
```

I cannot repro with the above configuration.
