### ISSUE TITLE
kubernetes_logs multiline

### ISSUE THREAD

**Issue by romkimchi1002** [vectordotdev/vector#22689]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hi!
i have a pod in kubernetes that writes multiline logs. unlike other vector sources such as "file" source, k8s_input does not support multiline logs

### Use Cases

This feature will be very helpful for multiline logs in k8s

### Proposal

i imagine a configuration that looks similar to file multiline cofiguration:
  ```
   type: 'kubernetes_logs'
   extra_field_selector: "metadata.container_name=my_namespace"
   multiline:
      start_pattern: "^\\d"
      mode: 'continue_through'
      condition_pattern: "^\\D"
      timeout_ms: 1000
```

### Version

0.45.0
