### ISSUE TITLE
Socket sink is not providing TTL for tcp session

### ISSUE THREAD

**Issue by pkruk** [vectordotdev/vector#22700]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm using vector to deliver logs to logstash with using a socket sink tcp

```
sinks:
      logstash:
        type: socket
        inputs: ["parse_json"]
        mode: "tcp"
        address: "my_domain:5045"
        encoding:
          codec: json
```

But on logstash we observed that traffic is not distributed evenly. It's looks like one ip is resolved from a host and all is sent to this one endpoint. Right now we observed that one node of our logstash is receiving a traffic and the rest is on zero. There is any option to set a TTL in socket sink? 

The other option I see right now is to resolve the dns to list and take a random ip from it.

### Configuration

```text
sinks:
      logstash:
        type: socket
        inputs: ["parse_json"]
        mode: "tcp"
        address: "my_domain:5045"
        encoding:
          codec: json
```

### Version

0.42.0

### Debug Output

```text

```
