### ISSUE TITLE
Transform to switch on field

### ISSUE THREAD

**Issue by sclu1034** [vectordotdev/vector#22769]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Writing a route transform like below in _Attempted Solutions_ that's essentially a switch-case on a field value works, but is tedious to type out. And probably not as efficient as possible, similar to how an `if-elseif-else` chain is generally worse in most programming languages than a `switch-case`.

### Attempted Solutions

```yaml
    route-docker:
        type: exclusive_route
        inputs: ["docker"]
        routes:
            - name: a
              condition: |
                  containers = [
                      "container_a",
                      "container_b",
                      # ...
                  ]
              includes(containers, string!(.container_name))
            - name: b
              condition: .container_name == "container_c"
            - name: c
              condition: .container_name == "container_d"
```

### Proposal

Create a new type of transform that acts as a switch-case on a given field:

```yaml
transforms:
  route-docker:
    type: switch
    path: .container_name
```

In this basic configuration, each value of `.container_name` would create its separate stream, e.g. `inputs: ["route-docker.container_a"]`.

Additional, optional features could be:

- Mapping:

```yaml
transforms:
  route-docker:
    type: switch
    path: .container_name
    routes:
      container_a: foo
      container_b:
        - foo
        - bar
      container_c: baz
```

This would allow renaming streams, as well as mapping multiple values to the same stream, or a value to multiple streams.

- `null` catch: `<transform_id>._null` could be created implicitly for events where the field is missing or `null`

### Version

0.45.0
