### ISSUE TITLE
Influxdb encoder

### ISSUE THREAD

**Issue by nionata** [vectordotdev/vector#22838]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I would like to configure a sink with the influxdb line protocol as the metric encoding.

```yml
sources:
  influx_in:
    type: "socket"
    address: "127.0.0.1:1337"
    mode: "udp"
    decoding:
      codec: "influxdb"

sinks:
  influx_out:
    type: "socket"
    address: "127.0.0.1:1338"
    mode: "udp"
    encoding:
      codec: "influxdb"
    inputs:
      - influx_in
```

### Attempted Solutions

A decoder was requested in #11337 and added in #19637. An encoder was left out, https://github.com/vectordotdev/vector/issues/11337#issuecomment-2276295101

### Proposal

An encoder should be able to be added within the codecs framework. The same influx line protocol library that is used for the decoder can be used for the encoder. The transformation should be as symmetrical as possible.
