### ISSUE TITLE
HTTP sink stopping after reloading TLS certificates

### ISSUE THREAD

**Issue by cah-rayan-chehab** [vectordotdev/vector#22900]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
In version 0.46.0, `crt_file` and `key_file` from `http` sinks are watched when --watch_config is enabled, causing Vector to reload when those files change.

### What currently happens
When running Vector with `--watch-config` enabled and an `http` sink with `crt_file` and `key_file` provided, changing certificates will reload Vector, except that events will not be received by the `http` sink anymore.

Based on the debug output, it seems like the `http` sink does not restart/resume after Vector reloads. This can further be confirmed after changing the certificates again, causing Vector to panic and shutdown due to the following error:
![Image](https://github.com/user-attachments/assets/246cd832-0d1c-4efe-95c4-68ee1ad159a8)

vector top:
![Image](https://github.com/user-attachments/assets/368ec0b9-0b67-4b28-9739-0ed3234d181e)

### What is expected to happen
Upon changing certificate and key, Vector's `http` sink should properly reload and be able to receive events again, sending them to the http endpoint using the new certificate and key.

### Reproduction Steps
1. Setup an `http` sink in the configuration with `crt_file` and `key_file` specified, as well as a source to be able to send events to the `http` sink.
   - For a quick setup, use the `demo_logs` source (provided in the configuration)
2. Start Vector
   -  ```
      vector --watch-config
      ```
3. Send an event
   - If monitored through `vector top`, this event will be received by the `http` sink
4. Generate a new certificate
   - In my case, I used the following commands:
      ```
      openssl genpkey -algorithm RSA -out client.key && \
      openssl req -new -key client.key -out client.csr -subj "/CN=YourCNHere" && \
      openssl x509 -req -in client.csr -CA ca.crt -CAkey ca.key.nopass -CAcreateserial -out  client.crt -days 365 -sha256
      ```
5. After Vector reloads, send another event
   - If monitored through `vector top`, the `http` will not receive said event
6. Generate another new certificate
   - Vector panics and shuts down here due to the following error:
      ```
      Pausing nonexistent sink is not valid: http_sink
      ```

### Configuration

```text
api:
  enabled: true

sources:
  demo_source:
    type: demo_logs
    format: shuffle
    sequence: true
    lines:
      - Hello World!
    interval: 10

sinks:
  http_sink:
    type: http
    inputs:
      - demo_source
    uri: https://localhost:8443
    encoding:
      codec: json
    batch:
      max_events: 1
      timeout_secs: 1
    tls:
      ca_file: /home/rayan.chehab/vector-client/ca.crt
      crt_file: /home/rayan.chehab/vector-client/client.crt
      key_file: /home/rayan.chehab/vector-client/client.key
```

### Version

0.46.1

### Debug Output

```text
https://gist.github.com/cah-rayan-chehab/2172660e733c9375bc2899efe7737a71
```

### References
 - https://github.com/vectordotdev/vector/pull/22539
 - https://github.com/vectordotdev/vector/pull/22678
 - https://github.com/vectordotdev/vector/issues/10877

**Comment by pront** [comment]
Thank you for the providing the reproduction steps @cah-rayan-chehab!

This might be a regression introduced here: https://github.com/vectordotdev/vector/pull/22539 
cc @gllb (in case you want to take a look)

There's open PR https://github.com/vectordotdev/vector/pull/22678 that we might be able to use to fix forward.

**Comment by gllb** [comment]
Hi @cah-rayan-chehab,

Is this issue always happening ? 
I've tested multiple setup, including yours but I wasn't able to reproduce. 

I wonder if the fact you have multiple command that change different file could cause vector to reload with the cert.key before the next command have finish, could you try to run the command on different file and then replace the file used in configuration altogether ?

**Comment by gllb** [comment]
Sure, 

vector.yaml: 
```
# Random Syslog-formatted logs
sources:
  dummy_logs:
    type: "demo_logs"
    format: "syslog"
    interval: 1

# Parse Syslog logs
# See the Vector Remap Language reference for more info: https://vrl.dev
transforms:
  parse_logs:
    type: "remap"
    inputs: ["dummy_logs"]
    source: |
      . = parse_syslog!(string!(.message))

# Print parsed logs to stdout
sinks:
  http:
    type: "http"
    inputs:
      - parse_logs
    encoding:
      codec: "json"
    uri: "https://localhost:8484"
    tls:
      crt_file: /home/gleblanc/test/cert.pem
      key_file: /home/gleblanc/test/key.pem
```

launch vector with : ` ./vector -v -c ./config/vector.yaml --watch-config`
renew the certificate with : `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"`

As Im not able to reproduce its hard to really figure out the reason for your crash, but Ive found a comment that make me think it *could* be related (https://github.com/vectordotdev/vector/blob/master/lib/vector-core/src/fanout.rs#L134 Im not that familiar with that part of the code btw). 

However the trace you shared point that its on a `send()` that the panic occurs, so it could be that it try to send to the old sink, if so it shouldnt be difficult to reproduce 🤔
