### ISSUE TITLE
reduce error=InvalidPathSyntax

### ISSUE THREAD

**Issue by hznor** [vectordotdev/vector#22925]
### Problem

I get this error:
```
2025-04-22T17:20:28.604166Z ERROR transform{component_kind="transform" component_id=kubernetes_pods_reduce_transform component_type=reduce}: vector::internal_events::reduce: Event field could not be reduced. path=KeyString("ExceptionDetail.Errors.10_0_199_64:9042.Data") error=InvalidPathSyntax { path: "ExceptionDetail.Errors.10_0_199_64:9042.Data" } error_type="condition_failed" stage="processing" internal_log_rate_limit=true
```

### Configuration

```
      kubernetes_pods_reduce_transform:
        expire_after_ms: 15000
        flush_period_ms: 500
        inputs:
        - kubernetes_pods_fix_message
        max_events: 1000
        type: reduce
```

### Version

0.42.0

**Comment by pront** [comment]
I cannot reproduce this with the latest Vector version:

```yaml
transforms:
  transform0:
    type: reduce
    inputs:
      - my_input
    group_by:
      - id
    expire_after_ms: 2000
    max_events: 500
    merge_strategies:
      foo: array
tests:
  - name: map_transform0.space
    inputs:
      - type: vrl
        insert_at: transform0
        source: |
          . = {
            "ExceptionDetail.Errors.10_0_199_64:9042.Data": 1
          }
      - type: vrl
        insert_at: transform0
        source: |
          . = {
            "ExceptionDetail.Errors.10_0_199_64:9042.Data": 1
          }
    outputs:
      - extract_from: transform0
        conditions:
          - type: vrl
            source: |
              assert_eq!(., {"ExceptionDetail.Errors.10_0_199_64:9042.Data": 2 })
```

Result:
```
cargo run --color=always --profile dev -- test tests/reduce.yaml
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.72s
     Running `target/debug/vector test /tests/reduce.yaml`
Running tests
test map_transform0.space ... passed

Process finished with exit code 0
```

Please try using a more recent Vector version.
