### ISSUE TITLE
E900 error after latest version

### ISSUE THREAD

**Issue by A-BenMao** [vectordotdev/vector#22948]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

After updating to latest vector version I now see an error that wasn't there before:

```
# vector validate -C /etc/vector/ 
√ Loaded ["/etc/vector"]
2025-04-25T09:46:30.557889Z  WARN transform{component_kind="transform" component_id=cb-log-golang-trans-1 component_type=remap}: vector::transforms::remap: VRL compilation warning. warnings=
warning[E900]: unused variable `err`
   ┌─ :11:12
   │
11 │ .hostname, err=get_hostname()
   │            ^^^ help: use the result of this expression or remove it
   │
   = this expression has no side-effects
   = see language documentation at https://vrl.dev
   = try your code in the VRL REPL, learn more at https://vrl.dev/examples

√ Component configuration
```
Has there been a change that could cause this in latest version?

### Configuration

```text

```

### Version

 vector 0.46.1 (x86_64-unknown-linux-gnu 9a19e8a 2025-04-14 18:36:30.707862743)

### Debug Output

```text

```

### MY Data
```
  .hostname, err=get_hostname()
  if err != null {
      log("Failed to get get_hostname: " + err, level: "error")
      .nodename=.host
  } else {
      .nodename=.hostname
  }
  if exists(.hostname) {
      del(.hostname)
  }
```

**Comment by pront** [comment]
Hi @A-BenMao, I cannot reproduce this, are you sure you are running on the latest version?

My Vector config:
```yaml
api:
  enabled: true

sources:
  demo_logs_1:
    type: demo_logs
    format: json
    interval: 60

transforms:
  t0:
    type: remap
    inputs:
      - demo_logs_1
    source: |
      .hostname, err=get_hostname()
      if err != null {
          log("Failed to get get_hostname: " + err, level: "error")
          .nodename=.host
      } else {
          .nodename=.hostname
      }
      if exists(.hostname) {
          del(.hostname)
      }

sinks:
  console:
    type: console
    inputs: [ "t0" ]
    encoding:
      codec: json
      json:
        pretty: true
```

```
√ Loaded ["./hostname_remap.yaml"]
√ Component configuration
√ Health check "console"
-----------------------------------------------------------------------------------------
                                                                                Validated

Process finished with exit code 0
```
