### ISSUE TITLE
reduce transform sums up numeric fields even when they are in the group_by list

### ISSUE THREAD

**Issue by pm5** [vectordotdev/vector#22945]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In `reduce`, numerical fields listed in the `group_by` setting will get merged using the default `sum` strategy, causing the value to change in the output.

If the `group_by` setting of a `reduce` transform is

```yaml
    group_by:
      - host
      - pid
      - tid
```

and the values in `pid` and `tid` fields are numerical, these values will be added up when `reduce` merges several logs.

If however the merge strategies are specified for these fields:

```yaml
merge_strategies:
  pid: retain
  tid: retain
```

then they won't be added up.  But this is unclear from the documentation.

### Configuration

Take the example of [merging Ruby exception](https://vector.dev/docs/reference/configuration/transforms/reduce/#examples-merge-ruby-exceptions) in the documentation (I removed the last line in the inputs to force checking on the merged output):

```yaml
transforms:
  my_transform_id:
    type: reduce
    inputs:
      - my-source-or-transform-id
    group_by:
      - host
      - pid
      - tid
    merge_strategies:
      message: concat_newline
    starts_when: match(string!(.message), r'^[^\s]')

tests:
  - name: check_merge_ruby_exceptions
    inputs: [
      {
        insert_at: my_transform_id,
        type: log,
        log_fields: {
          "host": "host-1.hostname.com",
          "message": "foobar.rb:6:in `/': divided by 0 (ZeroDivisionError)",
          "pid": 1234,
          "tid": 5678,
          "timestamp": "2020-10-07T12:33:21.223543Z"
        }
      },
      {
        insert_at: my_transform_id,
        type: log,
        log_fields: {
          "host": "host-1.hostname.com",
          "message": "    from foobar.rb:6:in `bar'",
          "pid": 1234,
          "tid": 5678,
          "timestamp": "2020-10-07T12:33:21.223543Z"
        }
      },
      {
        insert_at: my_transform_id,
        type: log,
        log_fields: {
          "host": "host-1.hostname.com",
          "message": "    from foobar.rb:2:in `foo'",
          "pid": 1234,
          "tid": 5678,
          "timestamp": "2020-10-07T12:33:21.223543Z"
        }
      },
      {
        insert_at: my_transform_id,
        type: log,
        log_fields: {
          "host": "host-1.hostname.com",
          "message": "    from foobar.rb:9:in `<main>'",
          "pid": 1234,
          "tid": 5678,
          "timestamp": "2020-10-07T12:33:21.223543Z"
        }
      }
    ]

    outputs:
      - extract_from: my_transform_id
        conditions:
          - type: vrl
            source: |
              assert_eq!(.pid, 1234)
              assert_eq!(.tid, 5678)
```

The test will fail:

```text
Running tests
test check_merge_ruby_exceptions ... failed

failures:

test check_merge_ruby_exceptions:

check[0] for transforms ["my_transform_id"] failed conditions:

  condition[0]: source execution failed: 
error[E000]: function call error for "assert_eq" at (0:22): assertion failed: 4936 == 1234
  ┌─ :1:1
  │
1 │ assert_eq!(.pid, 1234)
  │ ^^^^^^^^^^^^^^^^^^^^^^ assertion failed: 4936 == 1234
  │
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples


output payloads from ["my_transform_id"] (events encoded as JSON):
  {"host":"host-1.hostname.com","message":"foobar.rb:6:in `/': divided by 0 (ZeroDivisionError)\n    from foobar.rb:6:in `bar'\n    from foobar.rb:2:in `foo'\n    from foobar.rb:9:in `<main>'","pid":4936,"tid":22712,"timestamp":"2020-10-07T12:33:21.223543Z"}
```

This clearly is not the intended output as given in the documentation:

```text
[{"log":{"host":"host-1.hostname.com","message":"foobar.rb:6:in `/': divided by 0 (ZeroDivisionError)\n    from foobar.rb:6:in `bar'\n    from foobar.rb:2:in `foo'\n    from foobar.rb:9:in `\u003cmain\u003e'","pid":1234,"tid":5678,"timestamp":"2020-10-07T12:33:21.223543Z"}},{"log":{"host":"host-1.hostname.com","message":"Hello world, I am a new log","pid":1234,"tid":5678,"timestamp":"2020-10-07T12:33:22.123528Z"}}]
```

### Version

vector 0.46.1 (x86_64-unknown-linux-musl 9a19e8a 2025-04-14 18:36:30.707862743)

### Debug Output

```text

```

### Example Data

Provided above in the test configuration.
