### ISSUE TITLE
Convert incremental to absolute counter values for statsd source

### ISSUE THREAD

**Issue by GreyLilac09** [vectordotdev/vector#23018]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

- Back-filling old data--we have a use case where we need to save metrics data on device A and back-fill that data on  device B to Prometheus. Back-filling incremental counters is problematic because incremental counters rely on the previous value to get the next value, so they must be read sequentially. But:
  - old metrics might be out of order (newer values already exist for the same metric)
  - the metrics might be being back-filled in parallel (eg we have many files of back-filled being read at the same time with the same timestamps)
  - we use the file sink to save data on device A, and the file sink doesn't appear to save data sequentially, only in the order in which the file sink received data.

### Proposal

Two potential solutions:
- Add a `transform` which converts incremental to absolute counters
```
// aggregate counters, ignore gauges 
transforms:
 aggregate_counters:
   type: aggregate_counters
   counter_cache_bytes: 10000000
```
- Create an option for statsd to read all counters as absolute
```
statsd:
  type: statsd
  **aggregate_counters: true**
  **counter_cache_bytes: 10000000**
```

I can contribute to both options if this feature is likely to get merged in. Open to alternative config namings/suggestions

**Comment by GreyLilac09** [comment]
Also open to hearing alternative approaches to the problem problem

`we have a use case where we need to save metrics data on device A and back-fill that data on device B to Prometheus`

It doesn't appear that this is a supported workflow at the moment, as none of the file write codecs are aggregated.

**Comment by GreyLilac09** [comment]
@pront Which option do you feel would work best for this? Options:

- adding an optional incremental -> absolute conversion with expiring interval in statsd
- on the file output plugin by adding a new codec that does incremental -> absolute conversions, or adding the option to existing codecs
- adding a new transform entirely that just does incremental -> absolute conversions with optional expire_metrics_secs

**Comment by pront** [comment]
Transform sounds like the most flexible option (works with any sources and sink). Codec support is also a good option.

**Comment by GreyLilac09** [comment]
My proposal here would be a new aggregate_counters transform with an expire_metrics_secs
```
transforms:
  cumulative_aggregate:
    type: cumulative_aggregate
    expire_metrics_secs: 120s (default)
```

One alternative we have is to work it into the existing `aggregate` transform, eg 
```
transforms:
  cumulative_aggregate:
    type: aggregate
    mode: CumulativeCount (new mode)
    interval_ms: 10000 (now equivalent to expire_metrics_secs)
```
Which one do you think would be optimal?

**Comment by GreyLilac09** [comment]
hm, actually I think the behavior we want is slightly different

In aggregate, we are emitting the count values every interval period, while for the new transform, we want to emit the new value every time we receive the new count value. Thus "aggregate" might not be the best syntax here.

```
transforms:
  incremental_to_absolute:
    type: incremental_to_absolute
    expire_metrics_secs: 120s (default)
```

Something like this makes more sense syntax-wise
