### ISSUE TITLE
Splunk HEC sink should omit empty string values for metadata fields

### ISSUE THREAD

**Issue by milas** [vectordotdev/vector#23041]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The Splunk HEC sink allows specifying various per-event metadata through a mix of field path & template fields:
* [`host_key`](https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#host_key)
* [`index`](https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#index)
* [`source`](https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#source)
* [`sourcetype`](https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#sourcetype)
* [`timestamp_key`](https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#host_key)

Within the encoder, these are all skipped for serialization if `None` w/ `#[serde(skip_serializing_if = "Option::is_none")]`: https://github.com/vectordotdev/vector/blob/9129d95c56ad530989c238dd0d380de6a0c95ca8/src/sinks/splunk_hec/logs/encoder.rs#L25-L40

However, in the case that the value is `Some("")`, it will be serialized.

In particular, this can cause problems with `index`: unrestricted tokens will silently fallback to the default index, while tokens that can only write to certain indexes will get a `400`.

Arguably, both `None` & `""` should skip serialization.

### Configuration

```yaml
sources:
  demo:
    type: demo_logs
    format: bsd_syslog

transforms:
  remap:
    type: remap
    inputs: [demo]
    source: .index = ""

sinks:
  hec:
    type: splunk_hec_logs
    inputs: [remap]
    endpoint_target: event
    endpoint: http://splunk.example.com
    default_token: xxx
    index: "{{ index }}"
    encoding:
      codec: json
      except_fields:
        - index
```

### Version

0.46.1

### Debug Output

Debug logging isn't super helpful, but sending to an HTTP echo server to see the request sent to Splunk HEC reveals:

```json
{
  "event": "<93>May 13 18:19:43 some.ga auth[6359]: Take a breath, let it go, walk away",
  "fields": {},
  "time": 1747160383.762,
  "host": "localhost",
  "index": ""
}
```

(n.b. I prettified the JSON for legibility)

Notice "index": "".

### Additional Context

This is exacerbated by the inability to use `null` to get to `None` for the `Option<String>` (see referenced issue).

### References
* #23040
