### ISSUE TITLE
Slow memory leak in vector aggregate

### ISSUE THREAD

**Issue by czd890** [vectordotdev/vector#23093]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

There is a slow memory leak in vector aggregate. The service has 2 sources, vector and http source, and sends logs and metrics to DD via datadog_log and datadog_metric.

There seems to be nothing unusual in internal log and metric. How should I start investigating this issue?

![Image](https://github.com/user-attachments/assets/8862ca5e-0417-4711-bb49-09ae37a3acae)

### Configuration

```text

```

### Version

vector_0.44.0_x86_64-unknown-linux-musl_3cdc7c3_2025-01-13_21:26:04.735691656

### Debug Output

```text

```

**Comment by czd890** [comment]
Hi @pront, After upgrading to 0.48.0, and set up the ALLOCATION_TRACING = true. a route transform component has the memory usage of more than 273mb. 

```
sources:
  vector_receiver:
    type: vector
    address: 0.0.0.0:6000

transforms:
  route_vector_receiver:
    type: route
    inputs:
      - vector_receiver
    route:
      logMiddEvents:
        type: is_log
      metricMiddEvents:
        type: is_metric
    reroute_unmatched: false
```

<img width="1848" height="870" alt="Image" src="https://github.com/user-attachments/assets/178ac4d9-db65-4d15-a11a-eb70070eb6fe" />

<img width="1576" height="468" alt="Image" src="https://github.com/user-attachments/assets/f0458329-0ea8-4e75-bf45-d79de9209b8d" />
