### ISSUE TITLE
Healthcheck settings are ignored for connections to the database in Postgres sink

### ISSUE THREAD

**Issue by simplepad** [vectordotdev/vector#23111]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I noticed that setting `healthcheck.enabled` to `false` doesn't prevent vector from exiting with an error if the endpoint specified in the `endpoint` doesn't exist when it starts up. That is, if vector starts up earlier than postgres, it will exit with an error regardless of the `healthcheck.enabled` setting.

### Configuration

```yaml
sources:
  stdin:
    type: stdin

sinks:
  postgres:
    type: postgres
    table: test
    endpoint: "psql://127.0.0.1:9000" # invalid when vector starts
    healthcheck:
      enabled: false # the important bit
    inputs:
      - stdin
```

### Version

0.47.0

### Debug Output

```text

```

### References

https://github.com/vectordotdev/vector/pull/21248#issuecomment-2910373131
