### ISSUE TITLE
tls.enable is not valid. validator and vector think it's valid without error message.

### ISSUE THREAD

**Issue by ForkingFrenzy** [vectordotdev/vector#23145]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi team,
This should throw an error. However it doesn't. 
```
tls:
  enable: true 
```

The valid one is 
```
tls:
  enabled: true
```

### Configuration

```text

```

### Version

vector 0.45.0 (x86_64-unknown-linux-gnu 063cabb 2025-02-24 14:52:02.810034614)

### Debug Output

```text

```

**Comment by ForkingFrenzy** [comment]
```
sources:
  http_json:
    type: http_server
    address: 0.0.0.0:8080
    method: POST
    strict_path: false
    encoding: "json"
    tls:
      enable: true
      ca_file: "/opt/mycrt.key"
      crt_file: "/opt/mycrt.crt"
      key_file: "/opt/mycrt.key"

sinks:
  print:
    type: "console"
    inputs:
      - http_json
    encoding:
      codec: "json"
      json:
        pretty: true


```

` sudo /usr/bin/vector validate config.yaml`
