### ISSUE TITLE
Warn on unknown fields

### ISSUE THREAD

**Issue by thomasqueirozb** [vectordotdev/vector#23188]
### A note for the community

Currently unknown fields are just completely ignored which might lead to client misconfiguration. Ideally we'll add `#[serde(deny_unknown_fields)]` in all config structs but this would likely break existing users. Before doing that we should start logging a warning to alert users that the field they're using does nothing and this will eventually stop working.

### Implementation details

Possibly useful crate to implement this: https://crates.io/crates/serde-ignored-fields

Changes should be made to `compiler.rs` and/or to the `configurable` macro. Hopefully this is something that can be done without touching macro code

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### References

Related to #23145

**Comment by target-san** [comment]
Sorry for interfering but it seems current vector.dev already errors on unknown fields.
Thing is, it prevents use of things like YAML anchors, though I now understand it's not true YAML.
If you ask me why I needed YAML anchors, I'll gladly answer - to reuse transformer which remaps JSON produced by Rust's `tracing` into something compatible with OpenTelemetry. Namely, flatten spans and merge their attributes into main record attributes. No, unfortunately not all programs written in Rust will allow modify their logs format.
Sorry for a long rant🤷

**Comment by thomasqueirozb** [comment]
> Sorry for interfering but it seems current vector.dev already errors on unknown fields.

I don't think Vector warns ever on  unknown fields, but for some fields it refuses to run with an incorrect configuration and with others it doesn't.

Doesn't run:
```
...
sources:
  in:
    type: "file"
    include:
      - "/tmp/in/*.log"
    aaaa: 123
    fingerprinting:
      strategy: "device_and_inode"
      ignored_header_bytes: 0
...
```

Runs and doesn't warn:
```
...
sources:
  in:
    type: "file"
    include:
      - "/tmp/in/*.log"
    fingerprinting:
      strategy: "device_and_inode"
      ignored_header_bytes: 0
      aaaa: 123
...
```

> Thing is, it prevents use of things like YAML anchors, though I now understand it's not true YAML.

If you want to talk about usage of YAML anchors, which is not related to this issue, please open a [discussion](https://github.com/vectordotdev/vector/discussions)
