### ISSUE TITLE
"Poison" Datadog API gums up log sink (but not metrics!)

### ISSUE THREAD

**Issue by byronwolfman** [vectordotdev/vector#23299]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We have an observability pipeline that services multiple Datadog-based environments, some with different Datadog API keys. This morning a key was mistakenly revoked for one of these environments. Because we set the [store_api_key](https://vector.dev/docs/reference/configuration/sources/datadog_agent/#store_api_key) param to `true`, our expectation is that all observability data using the bad API key will fail to deliver, and all observability data using the good API key will be successfully delivered. The last time this issue was discussed, I was pointed towards the [partitioner](https://github.com/vectordotdev/vector/blob/6ad09472e986833b7a5b48776767cfe916d03726/src/sinks/datadog/logs/sink.rs#L24-L31) which ensures logs with different API keys are batched separately.

Instead, as soon as the poison key was introduced, all log delivery failed with HTTP 403.

|![Image](https://github.com/user-attachments/assets/01df1543-9e34-432a-8632-60eae653b53c)|
|-|

The graph shows `vector.http_client_responses_total` by status for our Datadog Logs component. What the graph can't show is that not all logs entering into the pipeline had the same API key, so _some_ should have been successfully delivered, but instead all failed.

Interestingly this isn't our first rodeo with poison keys; in https://github.com/vectordotdev/vector/issues/21402 we received some very useful recommendations to disable ARC, which at our time of testing, resolved future issues. That was using Vector 0.40.2 though and we upgrade regularly; currently we are on 0.45.0 for this pipeline.

Interestingly, we didn't lose metric delivery during this incident -- the "poison" key only affected logs. Some callouts:

* We use e2e acks for logs but not metrics
* We have static request concurrency on both, not ARC
* We are gzipping our logs and not our metrics (but we probably _should_ gzip the latter)

Something not shown in the config below is that in some _limited_ conditions we will do `set_secret("datadog_api_key", "...")` for certain events. The API key set by this function will be used regardless of what `store_api_key` says, and regardless of what the sink's default key is. In fact, during mitigation, we set `store_api_key` to false to use our known-good fallback key, which mostly worked until a log event showed up that could meet the conditions to execute `set_secret()`, at which point all log delivery began failing.

### Configuration

```toml
[sources.datadog]
type             = "datadog_agent"
address          = "0.0.0.0:8080"
disable_traces   = true
multiple_outputs = true
parse_ddtags     = true
store_api_key    = true


# ...
# We have a lot of components, which I can't really share!
# ...

[sinks.datadog_logs]
type                = "datadog_logs"
inputs              = ["terminal_datadog_logs"]
compression         = "gzip"
default_api_key     = "${DATADOG_FALLBACK_API_KEY:-none}"
healthcheck.enabled = false

# Apply backpressure to ensure log delivery
acknowledgements.enabled = true

# Use static concurrency so bad payloads don't cause Vector to scale concurrency to zero
request.concurrency = 10

[sinks.datadog_metrics]
type                = "datadog_metrics"
inputs              = ["terminal_datadog_metrics"]
default_api_key     = "${DATADOG_FALLBACK_API_KEY:-none}"
healthcheck.enabled = false

# Do not enable unless you have measured all round trip latency _very_ carefully
acknowledgements.enabled = false

# Use static concurrency so bad payloads don't cause Vector to scale concurrency to zero
request.concurrency = 10
```

### Version

vector 0.45.0 (x86_64-apple-darwin 063cabb 2025-02-24 14:52:02.810034614)

### Debug Output

```text

```

### Additional Context

(I have retrieved the version from my local development environment, but in production we run arm64 on Linux.)

### References

https://github.com/vectordotdev/vector/issues/21402

In that issue, it was recommended that we disable ARC and use static concurrency, which we did at the time.
