### ISSUE TITLE
Ability to set global defaults for `encoding.only_fields` and `encoding.except_fields`

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2343]
This, effectively, allows users to specify which fields are used for metadata purposes only. The options would look like:

```toml
[log_schema]
  encoding.only_fields = ["message"]
  encoding.except_fields = ["_meta"]
```

The above would have the same outcome as:

```toml
[sinks.print]
  type = "console"
  encoding.only_fields = ["message"]
  encoding.except_fields = ["_meta"]
```

Users should not be specifying both, but I wanted to be clear in my examples.
