### ISSUE TITLE
Panic if miscellaneous files in checkpoint directory

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#3343]
Vector appears to panic if there are any non-checkpoint files in the checkpoint directory. A user ran into this because OSX created a `.DS_Store` in the directory, but I was able to verify that putting any non-checkpoint files in there causes the issue.

I'm not sure exactly what the behavior should be here. My initial hunch is that vector should just ignore (and maybe log a warning) for any files it finds that are not checkpoint files.

### Vector Version

`v0.10.0`

### Vector Configuration File

```toml
data_dir = "/tmp/vectordata"
[sources.plain]
  include = ["/tmp/files/*"]
  type = "file"
  fingerprinting.strategy = "device_and_inode"
[sinks.console]
  inputs = ["plain"]
  type = "console"
  encoding.codec = "json"
```

### Debug Output

https://gist.github.com/jszwedko/48e69082579fe662e9b7d36b55fc5239

### Expected Behavior

Vector should have processed the files in `/tmp/files`

### Actual Behavior

Vector paniced.

### Example Data

```
 cat /tmp/files/a 
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
2020-08-04 10:10:10,123 hello
```

### Additional Context

```
 ls -la /tmp/vectordata/plain/checkpoints                   
total 8
drwxr-xr-x 2 CORP\jesse CORP\domain users   23 Aug  4 10:19 .
drwxr-xr-x 3 CORP\jesse CORP\domain users   25 Aug  4 10:10 ..
-rw-r--r-- 1 CORP\jesse CORP\domain users 6148 Aug  4 10:19 .DS_Store
```
