### ISSUE TITLE
New `http_scrape` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3532]
Like the current `http` source, but instead of being an HTTP server, it would be an HTTP client, making requests to a configurable endpoint on an interval.

Should support the following configuration options, courtesy of https://github.com/vectordotdev/vector/issues/3532#issuecomment-1088691713

```yaml
sources:
  myapi:
    type: http_scrape
    endpoint: http:://somehost:8080/api/v1/events
    query:
      param: value
      anotherparam[]:
        - value1
        - value2
    decoding:
      framing:
        method: newline_delimited
      codec: json
    auth:
      strategy: a-strategy  # for example: basic, bearer, oauth2
      basic:
        user: username
        password: password
      bearer: a-bearer-token  # this is sent using an 'Authorization: Bearer TOKEN' header
      oauth2:
        grant_type: an-oauth2-flow  # for example: client_credentials, see https://oauth.net/2/grant-types/
        authorize_endpoint: http://myauthserver:8081/oauth2/authorize
        token_endpoint: http://myauthserver:8081/oauth2/token
        client_id: a-client-id-for-client-credentials
        client_secret: a-client-secret-for-client-credentials
    request:
      headers:
        header: value # removed multi-value header support since this can be done as a separate enhancement
    poll_interval: 15
```

OAuth support can be broken off into another issue to reduce scope if needed.

**Comment by DK26** [comment]
If I may, and you may find it useful, please allow me to suggest you the name `http_request` ;-) 
As it is very straight forward about what it does: proactively requests using HTTP <3

**Comment by hhromic** [comment]
Hello! Our use cases are becoming more and more in need for this type of source (HTTP client instead of server).
At the moment, we circumvent the lack of such source by using the `exec` source coupled with `curl` as the command.
While this works pretty well, it forces us to build and maintain custom Vector Docker images that bundle `curl` so Vector can use it inside its own container (we deploy Vector 100% using Docker in production).

Would the Vector team be interested on moving forward with this type of source? I think we could help but I don't think we have sufficient Rust/Vector-code-base experience to do a proper implementation unfortunately.

**Comment by jszwedko** [comment]
Hey @hhromic ! Yes, this source is high up on the list for this next quarter (Q2). I agree that much of it could be generalized from the `prometheus_scrape` source. I'd expect to see this land in the next few months.

**Comment by hhromic** [comment]
@jszwedko ah that's so good news to read! Thanks a lot for keeping it in the roaster!
I think the recent work to add the `query` parameter will fit very well with this HTTP client source 😄.
Let me know if you want help testing, developing. I am feeling more confident the more I program with Rust :)

**Comment by hhromic** [comment]
Hello, I wanted to leave a note for the future of this source :)

An (important) consideration for this future source is to support OAuth2 authentication flows. Many modern REST APIs use OAuth2 to obtain tokens, for example using client id/secret pairs. I expect a significant number of use-cases for an HTTP Client source to require OAuth2 support.

A potential configuration block could be like this (inspired by the prometheus scrape source and elasticsearch sink):
```yaml
sources:
  myapi:
    type: http_client
    endpoint: http:://somehost:8080/api/v1/events
    query:
      param: value
      anotherparam[]:
        - value1
        - value2
    auth:
      strategy: a-strategy  # for example: basic, oauth2
      basic:
        user: username
        password: password
      oauth2:
        grant_type: an-oauth2-flow  # for example: client_credentials, see https://oauth.net/2/grant-types/
        client_id: a-client-id-for-client-credentials
        client_secret: a-client-secret-for-client-credentials
    request:
      headers:
        header: value
        another-header:  # the HTTP spec also allows for multivalued headers
          - value1
          - value2
    poll_interval: 15
```

For Vector use-cases I think the most commonly used grant type will be client credentials, so I would start with that one first.
I found this crate that could be handy for this support: https://docs.rs/oauth2/latest/oauth2/
