### ISSUE TITLE
Files are not being deleted properly by vector on ubuntu linux

### ISSUE THREAD

**Issue by amitw-vmware** [vectordotdev/vector#3592]
### Vector Version
```
vector 0.9.2 (v0.9.2 x86_64-unknown-linux-musl 2020-06-09)
```

### Vector Configuration File
```toml
# Configuration for the Vector shipper for Logz Agent
data_dir = "/var/lib/vector"

# /var/log
[sources.var_log]
  type                = "file"
  include             = ["/var/log/syslog", "/var/log/dmesg", "/var/log/*.log"]

[sources.mnt_logs_sunnylabs]
  type                = "file"
  include             = ["/mnt/logs/*.log"]
  exclude             = ["*-gc*", "/mnt/logs/buffercopy.log"]
  [sources.mnt_logs_sunnylabs.multiline]
    start_pattern = "^[^\\s]"
    mode = "halt_before"
    condition_pattern = "^(SEVERE|WARNING|INFO|CONFIG|FINE|FINER|FINEST|WARN|DEBUG) "
    timeout_ms = 1000




[sources.app]
  type                = "file"
  include             = ["/mnt/logs/nginx/error.log"]


[transforms.mnt_logs_sunnylabs_filter_sampled]
  type = "swimlanes"
  inputs = ["mnt_logs_sunnylabs"]

  [transforms.mnt_logs_sunnylabs_filter_sampled.lanes.null_pointer]
    "message.contains" = "NullPointer"

  [transforms.mnt_logs_sunnylabs_filter_sampled.lanes.info]
    "message.regex" = "^INFO  \\[[0-9-:, ]+\\] (SLDB:|sldb.planner).*"

[transforms.mnt_logs_sunnylabs_unsampled]
  type = "lua"
  inputs = ["mnt_logs_sunnylabs"]
  version = "2" # required
  hooks.process = """
  function (event, emit)
    if not string.match(event.log.message, "NullPointer") then
      if not string.match(event.log.message, "INFO") then
          if not string.match(event.log.message, "FINE") then
              if not string.match(event.log.message, "POST") then
                  if not string.match(event.log.message, "GET") then
                    emit(event)
                  end
              end
          end
      end
    end
  end
  """

[transforms.mnt_logs_sunnylabs_sampled]
  type = "sampler"
  inputs = ["mnt_logs_sunnylabs_filter_sampled.null_pointer", "mnt_logs_sunnylabs_filter_sampled.info"]
  rate = 10 # sample 10 %


[transforms.mnt_logs_sunnylabs_and_bcs_parsed_1_log4jfmt]
  type = "regex_parser"
  inputs = ["mnt_logs_sunnylabs_sampled", "mnt_logs_sunnylabs_unsampled"]
  drop_field = false
  regex = "^(?P<severity>.*)\\s\\s\\[(?P<log_timestamp>.*)\\]\\s(?P<class>.*):\\s(?P<log_message>.*)$"
  # Types
  types.severity = "string"
  types.log_timestamp = "string"
  types.class = "string"
  types.log_message = "string"

[transforms.mnt_logs_sunnylabs_and_bcs_parsed_2_ipfmt]
  type = "regex_parser"
  inputs = ["mnt_logs_sunnylabs_and_bcs_parsed_1_log4jfmt"]
  drop_field = false
  regex = "^(?P<ip>\\S*)\\s-\\s-\\s\\[(?P<log_timestamp>.*)\\]\\s\"(?P<method>\\S*)\\s(?P<url>\\S*)\\s(?P<protocol>\\S*)\"\\s(?P<code>\\S*)\\s(?P<extra>.*)$"

  # Types
  types.ip = "string"
  types.log_timestamp = "string"
  types.method = "string"
  types.url = "string"
  types.protocol = "string"
  types.code = "string"
  types.extra = "string"

[transforms.mnt_logs_sunnylabs_and_bcs_parsed_3_reporting]
  # General
  type = "regex_parser"
  inputs = ["mnt_logs_sunnylabs_and_bcs_parsed_2_ipfmt"]
  drop_field = false
  regex = "^Reporting\\s(?P<reporting_status>.*)\\sto:\\s(?P<reporting_message>.*)$"

  # Types
  types.reporting_status = "string"
  types.reporting_message = "string"

[transforms.aws_tags]
  type                = "add_fields"
  inputs              = ["var_log", "mnt_logs_sunnylabs_and_bcs_parsed_3_reporting", "app"]
  fields.cluster        = "vmwareprod"
  fields.role           = "app"
  
  fields.mirror         = "primary"
  
  fields.region         = "us-west-2"
  

[sinks.logzio]
# https://app.logz.io/#/dashboard/data-sources/Vector
  type            = "http"
  inputs          = ["aws_tags"]
  encoding        = "ndjson"
  uri             = "https://listener.logz.io:8071?token=gZwCpjcDVKYrMtpsLvGXnNpLYudkjJwN&type=vector"
  compression     = "gzip"

  request.in_flight_limit = 100
  request.rate_limit_num = 10000
  request.rate_limit_duration_secs = 10

  [sinks.logzio.buffer]
  type            = "disk"
  when_full       = "block"
  max_size        = 104900000

##
```

### Debug Output
```
RUST_BACKTRACE=full vector -vvv <rest of commands>
NA
```
### Expected Behavior
File should have been deleted but it wasn't truly deleted (vector seems to have been holding onto a file handle)

### Actual Behavior
File is holding onto file handles that are deleted in ubuntu.

### Example Data
NA

### Additional Context
```
ubuntu@vmwareprod-2c-app35-i-0047aa864e26682dc:~$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1   20G   18G  1.5G  93% /

ubuntu@vmwareprod-2c-app35-i-0047aa864e26682dc:~$ sudo lsof +L1 | awk '{ print $1 }' | sort | uniq
COMMAND
vector

0047aa864e26682dc:~$ sudo service vector stop
ubuntu@vmwareprod-2c-app35-i-0047aa864e26682dc:~$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1   20G  9.0G   11G  47% /

Here is an example from another machine

ubuntu@vmwareprod-2c-app22-i-08900aff15c77a051:~$ sudo lsof +L1
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NLINK   NODE NAME
java     7168   ubuntu   46w   REG  259,1 10486093     0 538119 /mnt/vol1/logs/externalservices.log.9 (deleted)
java     7421   ubuntu   46w   REG  259,1 10486052     0 538126 /mnt/vol1/logs/collector.log.9 (deleted)
java     7544   ubuntu   46w   REG  259,1 10486111     0 538132 /mnt/vol1/logs/dataingester.log.9 (deleted)
fluentd 46319 td-agent    7w   REG  259,1  2289813     0 538034 /var/log/td-agent/td-agent.log.1 (deleted)
ruby    46326 td-agent   18r   REG  259,1 10485765     0 534074 /mnt/vol1/logs/externalservices.log.9 (deleted)
```
### References
NA
