### ISSUE TITLE
Kafka to google bucket get stuck after some messages

### ISSUE THREAD

**Issue by jonathanendy** [vectordotdev/vector#3820]
### Vector Version

```
nightly-2020-09-09-alpine
```

### Vector Configuration File

```toml
[sources.kafka-cloud]
  type = "kafka" # required
  bootstrap_servers = "${KAFKA_BOOTSTRAP_SERVERS}" # required
  group_id = "${KAFKA_TOPIC}-to-gcs-${BUCKET_NAME}" # required
  topics = ["${KAFKA_TOPIC}"] # required
  librdkafka_options."sasl.password" = "${KAFKA_PASSWORD}"
  librdkafka_options."sasl.username" = "${KAFKA_USERNAME}"
  librdkafka_options."sasl.mechanism" = "PLAIN"
  librdkafka_options."security.protocol" = "SASL_SSL"

[sinks.gcp]
  type = "gcp_cloud_storage" # required
  inputs = ["kafka-cloud"] # required
  credentials_path = "/etc/vector/gcs.json"
  bucket = "${BUCKET_NAME}"
  healthcheck = true

  batch.max_events = 1

  filename_append_uuid = false
  filename_extension = "json"
  filename_time_format = ""

  key_prefix="test/{{ run_uuid }}"

  # Encoding
  encoding.codec = "ndjson" # required

  buffer.type = "disk"
  buffer.max_size = 1049000
  buffer.when_full = "block"
```

### Actual Behavior

I'm sending messages one by one from kafka to gcs, every message is an object (not batch)
After a few seconds vector stopped with the beep message, only 128 messages pass to gcs.
restarting the container give the same results

If you need full logs please tell me
