### ISSUE TITLE
"unable to get local issuer certificate" from within systemd

### ISSUE THREAD

**Issue by khionu** [vectordotdev/vector#3868]
### Summary

Running on a fresh Ubuntu 20.04 LTS VM, through systemd, the following error is consistently ran into after trying to healthcheck GCS.

```
Sep 14 16:36:30 vector-cert-error-repro vector[3157]: Sep 14 16:36:30.700 ERROR vector::topology::builder: Healthcheck: Failed Reason: error trying to connect: the handshake failed: error:1
```

On the same system, running Vector outside of systemd does not yield the error. After that test, the issue is still reproducible from within systemd.

### Version
vector 0.11.0 (g50a9c3a x86_64-unknown-linux-gnu 2020-09-10)

### Vector Configuration File

```toml
data_dir = "/var/lib/vector"

[sources.pokes]
  type     = "http"
  address  = "0.0.0.0:80"
  encoding = "json"

[sources.internal]
  type = "internal_metrics"

[transforms.count_pokes]
  type   = "log_to_metric"
  inputs = ["pokes"]

  [[transforms.count_pokes.metrics]]
    type  = "counter"
    field = "host"

  [[transforms.count_pokes.metrics]]
    type  = "counter"
    field = "msg_inc"

[sinks.prom]
  type      = "prometheus"
  inputs    = ["internal", "count_pokes"]
  address   = "0.0.0.0:9090"
  namespace = "vector"

[sinks.gcs]
  type = "gcp_cloud_storage"
  inputs = ["pokes"]
  bucket = "<SNIP>"
  encoding.codec = "text"
```
