### ISSUE TITLE
Break sink-level `encoding` options across `batch` and `stream` namespaces

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4058]
This is a follow up to https://github.com/timberio/vector/pull/3852#issuecomment-692901687, #3454, #3453.

To prevent confusion, and provide more control over how data is encoded within Vector, I propose that we move the `encoding` option under the `batch` and `stream` namespaces.

### Batching

```toml
[sinks.aws_s3]
  type = "aws_s3"
  batch.encoding.codec = "json"
  # batch.encoding.only_fields = ...
  # batch.encoding.except_fields = ...
  # batch.encoding.timestamp_format = ...
```

### Streaming

```toml
[sinks.aws_s3]
  type = "aws_s3"
  stream.encoding.codec = "json"
  stream.encoding.delimiter = "\n"
  # stream.encoding.only_fields = ...
  # stream.encoding.except_fields = ...
  # stream.encoding.timestamp_format = ...
```
