### ISSUE TITLE
Source-level decoding options to match sink-level encoding options

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4059]
In #4058 we proposed moving the `encoding` option under `batch` and `stream`. This made me realize we do not have a source-level equivalent. Therefore, I propose that we add both `batch.decoding` and `stream.decoding` within each source.

## Examples

For clarity, a batching source receives many events in a batched fashion (`http` source) and a streaming source receives one event at a time (`socket` source).

### Batching

```toml
[sources.http]
  type = "http"
  batch.decoding.codec = "json"
```

### Streaming

```toml
[sources.socket]
  type = "socket"
  batch.decoding.codec = "json"
  batch.decoding.delimiter = "\n"
```

## Requirements

- [ ] `file` source
- [ ] `http` source
- [ ] `kafka` source
- [ ] `socket` source
- [ ] `stdin` source

Notice that I did not include `docker`, `generator`, `journald`, `prometheus`, etc. The decoding strategy is baked into these sources and should not have a configuration option for it.
