### ISSUE TITLE
New remap inspired `swimlanes` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4397]
Now that the new remap language is approaching completion, we should think about the `swimlanes` transform and how it fits within the presence of this language. There's quite a bit of overlap between this transform and remap's conditional statements. Remap's conditional statements are quite a bit more expressive and robust; and it'd benefit everyone to align the two.

## Proposal

```toml
[transforms.swimlanes]
type = "swimlanes"
lanes.debug = '.level == "debug"'
lanes.info = '.level == "info"'
lanes.warn = '.level == "warn"'
lanes.error = '.level == "error"'
```
