### ISSUE TITLE
Add `drop_field` option in `regex_parser` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#442]
Just like the `json_parser` transform, we need to add a `drop_field` option to the `regex_parser` transform. This simply drops the target field after parsing it.

For example:

```
{
  "message": "58.176.24.234 - - [03/06/2019:16:35:55 -0400] "DELETE /sticky" 200 26497"
}
```

With this `transform` configuration:

```toml
[transforms.apache_common_parser]
  inputs = ["json_parser"]
  type   = "regex_parser"
  field  = "msg"
  drop_field = true
  regex  = '^(?P<host>[\w\.]+) - (?P<user>[\w]+) (?P<bytes_in>[\d]+) \[(?P<timestamp>.*)\] "(?P<method>[\w]+) (?P<path>.*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+)$'
```

Notice the `drop_field` attribute. The result, after processing through this transform would be:

```
{
  "host": "58.176.24.234",
  ...
}
```

Notice that the `"message"` key has been dropped as a result.

Requirements:

- [x] The `drop_field` option defaults to `false`.
- [ ] If the regex extracts a field with the same name as the target field, it should _NOT_ remove the extracted field. The field dropping should happen before merge. Please add a test for this.
