### ISSUE TITLE
file source slow when handling millions of gzipped files over EBS

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#4434]
A user reported that they found the file source unexpectedly slow while ingesting files with the file source to the s3 source.

```toml
data_dir = "/var/lib/vector"

[sources.files_from_ebs_s3]
  type = "file"
  include = ["LOGDIR/*.json.gz"]
  oldest_first = true
  fingerprinting.strategy = "device_and_inode"
  remove_after = 1
```

The user is running on AWS and the log files are accessed via EBS. (by the name, seems s3 somehow?)

The user has approximately 1 million files. They are gzipped and approximately 1gb.

The user states these are in cloudtrail format.

The user states the config *works* but is slow, processing only around 600mb over the course of days.

The user states that they may move `LOGDIR` and place a new folder at `LOGDIR` periodically, with new files to read. The user states this happens when Vector has finished removing (consuming) all the logs.
