### ISSUE TITLE
grok parser: Support patterns loaded from files

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#4460]
### Current Vector Version

Latest

### Use-cases

* User wishes to convert from Logstash to Vector, makes use of the grok parser with their existing patterns in https://github.com/hpcugent/logstash-patterns.
* `grok_parser` use at a complex enough level would likely suggest this use case of loading patterns from files.
* This functionality exists in similar projects.

### Attempted Solutions

* The user attempted to use the pattern they had directly but this did not work since these patterns were not available.
* The user checked our supported grok patterns and did not find what they needed.

### Proposal

I propose adding a `pattern_sources = ['/usr/share/grok/**']` to the `grok_parser` source.

```toml
[transforms.my_transform_id]
  # General
  type = "grok_parser" # required
  inputs = ["my-source-or-transform-id"] # required
  drop_field = true # optional, default
  field = "message" # optional, default
  pattern_sources = ['/usr/share/grok/**'] # optional, default
  pattern = "%{SSH_MSG}" # modified, example

  # Types
  types.status = "int" # example
  types.duration = "float" # example
  types.success = "bool" # example
  types.timestamp = "timestamp|%F" # example
  types.timestamp = "timestamp|%a %b %e %T %Y" # example
  types.parent.child = "int" # example
```

### References

* https://github.com/hpcugent/logstash-patterns

User logstash config fragment:

```logstash
grok {
            break_on_match => true
            named_captures_only => true
            patterns_dir => [ "/usr/share/grok" ]
            match => {
                "message" => ["%{SSH_MSG}","%{MODULECMD_MSG}","%{LMOD_MSG}","%{NFS_MSG}","%{CEPH_MSG}","%{OPENNEBULA_MSG}","%{JUBE_MSG}","%{KEYVALUE_MSG}","%{QUATTOR_MSG}","%{SNOOPY_MSG}","%{RSYSLOGCUSTOM}"]
            }
        }
```

Some example `lmod` messages:

```grok
LMOD_GENERAL (?:- lmod::)\s*username=%{USERNAME_PAT}, cluster=%{DATA:cluster}, jobid=%{DATA:jobid}
LMOD_USERLOAD (?:yes|no)
LMOD_LOAD userload=%{LMOD_USERLOAD:userload}, module=%{DATA:module_name}/%{DATA:module_version}, fn=%{GREEDYDATA:module_path}
LMOD_CMD cmd=%{DATA:command}, args=%{GREEDYDATA:arguments}
LMOD_MSG %{LMOD_GENERAL}, (?:%{LMOD_LOAD}|%{LMOD_CMD})
```
