### ISSUE TITLE
Ability to set the `_id` field in the `elasticsearch` sink (deduping events)

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4479]
Elasticsearch has a reserved [`_id` field](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html) that is used to uniquely identify documents. As such, Elasticsearch will not allow multiple events to be ingested with the same `_id` value. By default, Elasticsearch sets this field to a random UUID, but users can set it themselves in a way that would prevent duplicates.

To achieve this, Vector should provide a means to derive the value of the `_id` field from the event data. This would effectively prevent duplicates from being ingested into Elasticsearch.

## Proposal

The solution to this problem is a little fuzzy due to ongoing work in #3910. So, to keep things flexible, Vector should use the value of a known "id" field according to the event's schema and if this field does not exist Vector can then apply a default.

Therefore, I propose that we solve this with #4477:

```toml
[sinks.es]
type = "elasticsearch"
encoding.schema._id = '{{ get_schema_value("id") }}' # default
# ...
```

This gives the user the flexibility to use their own `_id` value and override it accordingly. For example, if their events do not have an "id" field they could set it with another remap function:

```toml
[sinks.es]
type = "elasticsearch"
encoding.schema._id = '{{ fingerprint() }}' # default
# ...
```

See #4478.
