### ISSUE TITLE
Compose the `syslog` source with the `socket` and `remap` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4502]
Once the work described in https://github.com/timberio/vector/pull/4427 is complete, we should rebuild our `syslog` source in a way that takes advantage of these new changes. The result should be the same as:

```toml
[sources.socket]
type = "socket"
# ...

[transforms.remap]
type = "remap"
inputs = ["socket"]
source = """
parse_syslog(.message)
"""
```

## Requirements

- [ ] Log a warning when parsing fails, like we do now.
- [ ] Ensure that all syslog keys are in the root of the event.
