### ISSUE TITLE
Add `else` lane to `route` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4644]
We need a "catch-all" lane that catches events that did not fall into a defined lanes. Taking the example from #4643:

```toml
[transforms.route]
type = "route"
lanes.debug = '.level == "debug"'
lanes.info = '.level == "info"'
lanes.else = true

[sinks.exceptions]
type = "elasticsearch"
inputs = ["route.else"]

[sinks.debug_logs]
type = "aws_s3"
inputs = ["route.debug"]
```

I'm open to better ways of doing this, but I like the explicitness of defining the lane, otherwise I think it'll go unnoticed.
