### ISSUE TITLE
Proposed config interface change for the `log_to_metric` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#493]
The [`log_to_metric` transform](https://github.com/timberio/vector/blob/master/src/transforms/log_to_metric.rs) is responsible for converting [`log` events](https://github.com/timberio/vector/blob/93f367cee5f8fee3661a5ae5578da8cd245b35d3/src/event/mod.rs#L25) to [`metric` events](https://github.com/timberio/vector/blob/93f367cee5f8fee3661a5ae5578da8cd245b35d3/src/event/mod.rs#L26). Currently, it's very limited, only supporting counters and gauges, which should make the following proposed change much simpler. In the future, we'd like to support more metrics types like histograms (https://github.com/timberio/vector/issues/384).

This issue is proposing a change to the [input configuration](https://github.com/timberio/vector/blob/93f367cee5f8fee3661a5ae5578da8cd245b35d3/src/transforms/log_to_metric.rs#L8). Currently, it accepts input like the following:

```toml
[transforms.log_to_metric]                                 
  inputs = ["in"]                                  
  type = "log_to_metric"                           
  counters = [{field = "foo", parse_value = false}]
  gauges = ["bar", "baz"]
```

While this is a great start I find it be mildly confusing. We'd like to update the interface be:

```toml
[transforms.log_to_metric]                                 
  inputs = ["in"]                                  
  type = "log_to_metric"

  [[transforms.log_to_metric.metrics]]
    type = "counter"
    field = "foo"
    name = "foo_total" # default

  [[transforms.log_to_metric.metrics]]
    type = "gauge"
    field = "bar"
    name = "bar" # default

  [[transforms.log_to_metric.metrics]]
    type = "gauge"
    field = "baz"
    name = "baz" # default
```

## Use Cases / Examples

To further explain, here are a few real-world use cases:

### 1. Count HTTP status codes

Given a `"status"` field that is an `int`, we want to count how many logs of each status occur:

```toml
[transforms.log_to_metric]
  type = "log_to_metric"
  
  [[transforms.log_to_metric.metrics]]
    type = "counter"
    field = "status"
    name = "status_total" # default
    labels.status = "#{event.status}" 
    labels.host = "#{event.host}"
```

### 2. Count exceptions 

Given a `"backtrace"` field (could be any type), we want to count how many exceptions we see.

```toml
[transforms.log_to_metric]
  type = "log_to_metric"
  
  [[transforms.log_to_metric.metrics]]
    type = "counter"
    field = "backtrace"
    name = "exception_total"
    labels.host = "#{event.host}"
```

* Any event that _does_ have a `"backtrace"` will be counted.
* Any event that does _not_ have a `"backtrace"` will _not_ be counted.

### 3. Histogram response times

I know we don't support histograms yet, but felt we should provide an example so we make room for this when we do support it.

Given a `response_time` field that is a `float`, we want to create a histogram of values:

```toml
[transforms.log_to_metric]
  type = "log_to_metric"
  
  [[transforms.log_to_metric.metrics]]
    type = "histogram"
    buckets = {type = "exponential", base = 100, exponent = 1.2, count = 3} # this is still being discussed
    field = "response_time"
    name = "response_time_seconds" # default?
    labels.host = "#{event.host}"
```
* If the field is not a number it will be ignored.

### 4. Memory usage guage

Given a `memory_rss` field that is an `int`, we want to create a guage representing current memory usage.

```toml
[transforms.log_to_metric]
  type = "log_to_metric"
  
  [[transforms.log_to_metric.metrics]]
    type = "guage"
    field = "memory_rss"
    name = "memory_rss_bytes" # default?
    labels.host = "#{event.host}"
```

### 5. Sum order amounts

Given a `amount` field that is a `float`, I want to sum values over time. In other words, increment a counter by it's value.

```toml
[transforms.log_to_metric]
  type = "log_to_metric"
  
  [[transforms.log_to_metric.metrics]]
    type = "counter"
    field = "amount"
    increment_by_value = true # default is false
    name = "amount_total" # default?
    labels.host = "#{event.host}"
```

## Requirements

- [ ] Accept a `metrics` list of tables
- [ ] Only support `counter` and `gauge` for the `type` field (for now, we'll want to add more later)
- [ ] Default the `name` to `{field}_total` for counters and `{field}` for gauges.
- [ ] Support a `increment_by_value` option for counters.
