### ISSUE TITLE
Hefty message loss for syslog source

### ISSUE THREAD

**Issue by suvl** [vectordotdev/vector#5017]
Hey guys I'm measuring that "best effort" thingie for the `syslog` source and I'm getting quite bad results under heavy load...

For instance, I'm sending 1302657600 log messages over a period of 30 minutes (and letting kubernetes scale Vector based on CPU load as I have no better metric) and I'm seeing heavy losses:

* Over TCP+TLS only 203166694 messages are processed ( **84.4% loss** ) and it slows the clients sending those logs
* Over UDP only 44020058 messages are processed ( **96.6% loss** )

These are quite heavy losses and we cannot keep using Vector while this does not go away.

Version: `vector 0.10.0 (g0f0311a x86_64-unknown-linux-musl 2020-07-22)`

Relevant configs:

```
    [sources.tls]
      type = "syslog"
      address = "0.0.0.0:6514"
      mode = "tcp"
      shutdown_timeout_secs = 5
      tls.enabled = true
      tls.crt_file = "/cert/tls.crt"
      tls.key_file = "/cert/tls.key"
      tls.ca_file = "/crt/ca.pem"
      tls.verify_certificate = false
      max_length = 10240000

    [sources.plain]
      type = "syslog"
      address = "0.0.0.0:514"
      mode = "udp"
      max_length = 10240000

    [sinks.kafka]
      type = "kafka"
      inputs = ["tls","plain"]
      bootstrap_servers = "kafka-all-broker.kafka.svc.cluster.local:29092"
      compression = "none"
      healthcheck = true
      key_field = "host"
      topic = "syslog-raw"
      encoding.codec = "json"
      buffer.type = "memory"
      buffer.when_full = "drop_newest"
      buffer.max_events = 100000
```

**Comment by jamtur01** [comment]
Hi @suvl - that loss isn't great. Could you try the latest nightly builds and see if there is a difference?

Also we'd love to see how you're generating the load and your K8s config so we can try to replicate ourselves. Thanks!

**Comment by jszwedko** [comment]
Some conversation in discord: https://discord.com/channels/742820443487993987/746070591097798688/776816312969723975

My hunch here is that the issue is `buffer.when_full = "drop_newest"` on the Kafka sink. If the Syslog source is ingesting data faster than it can publish to Kafka, we'll see Vector drop messages. I think a better route here is to let the Kafka sink apply back-pressure to the source. For UDP, we'll still see message loss, but TCP should result in Vector not accepting more messages.

**Comment by suvl** [comment]
I've now changed the Kafka sink configuration to:

```
      buffer.type = "memory"
      buffer.when_full = "block"
      buffer.max_events = 2147483647
      librdkafka_options."socket.timeout.ms" = "5000"
      librdkafka_options."retries" = "1"
      librdkafka_options."queue.buffering.max.messages" = "10000000"
      librdkafka_options."linger.ms" = "25"
```

And I've observed similar results, give or take.

**Of the setup**

I have some load test containers that replay 24h of logs from the past in our system at a given speed. This is intended to evaluate the capability the system has to scale and take all the data.
To measure the number of messages that go through I use a Kafka subscriber that's pushing those messages to a SQL table. It's just a matter of counting the number of inserted rows in a period. I am making sure that this client is not being OOMKilled or anything.

The system does have an HPA in place, scaling on CPU. I'm using 2 threads (`--threads=2`) and I've set the CPU limit for each vector pod to `2000m`. The HPA will scale when above 85% average usage of this CPU value. Not sure this is the right metric to scale from, but I cannot see a better one from here (I did try to find a linear relationship on performance based on vector's `service_events_processed` but couldn't reach a conclusion).

From the time compression I'm using at the load test containers, all 1302657600 messages representing the 24-hour log sample should be sent in just above 32 minutes. So I'm trying to upload about 3 gigabytes of logs in that time, what seems to be quite manageable.

The deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  namespace: vector
  labels:
    app: vector
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool : cpu-pool
      tolerations:
      - key: purpose
        operator: Equal
        value: cpu-intensive
        effect: NoSchedule
      containers:
      - image: timberio/vector:0.10.0-alpine
        imagePullPolicy: IfNotPresent
        name: vector
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 28Mi
        args:
        - "--threads=2"
        - "--require-healthy=true"
        ports:
        - containerPort: 514
          name: udp-plain
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/vector/vector.toml
          subPath: vector.toml
        livenessProbe:
          httpGet:
            port: 9598
            path: /metrics
        readinessProbe:
          httpGet:
            port: 9598
            path: /metrics
      volumes:
      - name: config-volume
        configMap:
          name: config
```

HPA:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: vector
  namespace: vector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vector
  minReplicas: 4
  maxReplicas: 300
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85
```

**Comment by suvl** [comment]
![image](https://user-images.githubusercontent.com/6018083/99564003-cd04c180-29c1-11eb-9073-85f069b09a18.png)

We're observing that there are too many RcvbufErrors at anecdotical throughputs (less than 30 kbps) while using too small of a receiving buffer (64MiB while I've set a max of 2GiB).

```
~$ grep Udp /proc/net/snmp
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
Udp: 653277009 21890889 145418581 194 143350293 0 0 0
```

**Comment by lukesteensen** [comment]
@suvl Thank you for the detailed report! I am going to run some experiments today to see if I can reproduce this locally.

One thing I am noticing is that your top graph appears to be kilo-_packets_ per second, not bits, which implies quite a bit higher throughput. I assume these packets are roughly the size of a normal log line (e.g. hundreds of bytes)?

**Comment by suvl** [comment]
@lukesteensen yeah I read that graph way to fast.... indeed, it's packets per second and it's by no means anecdotical throughput.

As a benchmark, this is what I'm being able to pull out of rsyslog:
![image](https://user-images.githubusercontent.com/6018083/99693976-d48c9f00-2a83-11eb-9a21-7873c7bbcbc2.png)

![image](https://user-images.githubusercontent.com/6018083/99694055-e8380580-2a83-11eb-9315-337170a0ab58.png)
(I'm guessing the SSDs attached to these machines are the next culprit, writing to `/dev/null` yields no packet loss)

**Comment by lukesteensen** [comment]
@suvl does the throughput improve if you remove the lua transform?

**Comment by suvl** [comment]
@lukesteensen it doesn't seem to...

![image](https://user-images.githubusercontent.com/6018083/99714927-16c2da00-2a9e-11eb-8718-0ec1d6aad8d8.png)

**Comment by lukesteensen** [comment]
@suvl 

> We're observing that there are too many RcvbufErrors at anecdotical throughputs (less than 30 kbps) while using too small of a receiving buffer (64MiB while I've set a max of 2GiB).

Are you setting `net.core.rmem_max`? We don't currently have a way to set our own socket recv buffer size (I will open an issue for this), but you should be able to work around this by also setting `net.core.rmem_default` (this will affect all other udp listeners, so make sure that is acceptable).

> this is what I'm being able to pull out of rsyslog

Am I reading this correctly as ~900Mb/s? I am curious what your target is and what you are currently seeing Vector do before you start to see the `RcvbufErrors` number go up.

**Comment by suvl** [comment]
@lukesteensen I was setting `net.ipv4.udp_mem` only. After setting `sysctl -w net.core.rmem_default=2048000000` and `sysctl -w net.core.rmem_max=2048000000` it improved a bit, but still with many `RcvbufErrors`:

![image](https://user-images.githubusercontent.com/6018083/99959993-ecb23600-2d83-11eb-9148-d522a2542a89.png)

And yep, that's about 900Mb/s or full NIC speed in Azure. We're building a central syslog ingestion system for 2 million home gateways, 3 or 4 million set-top boxes, and then if this is a success there'll be thousands of cell sites, millions of mobile apps and whatnot. So we need to take all we can from the NIC to save infra costs.

**Comment by suvl** [comment]
One week of using rsyslog and we have an absolute zero on those `RcvbufErrors`:

```
❯ k get po -o name | parallel -Ipod kubectl exec -t pod -- cat /proc/net/snmp | grep Udp:
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
Udp: 843171279 0 0 266 0 0 0 0
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
Udp: 1747889198 81891 0 618 0 0 0 0
```

(not under loadtest, these are numbers for our current load; vector would have about half of those `InDatagrams` become `RcvbufErrors`)

**Comment by lukesteensen** [comment]
Thanks for the update @suvl! That is certainly an impressive level of performance. To be honest, I do not expect Vector to match that right now. I have been looking into some optimizations for our UDP syslog source, and I do think that we can get there, but it will take a bit of work.

**Comment by jszwedko** [comment]
Closing this in-lieu of some issues we have to improve UDP processing performance: 


https://github.com/vectordotdev/vector/issues/8518
https://github.com/vectordotdev/vector/issues/12452

**Comment by rafamiga** [comment]
Just my 2 cents on this. I had the same problem with getting syslog UDP logs from a CDN streaming at more than 1 Tbit/s. Above 400 Mbit/s, I was getting 80-90k UDP messages a second, and the kernel's buffers filled up, resulting in those dreadful UDP receive errors like this:

```
netstat -us
[…]
Udp:
    4238193412 packets received
    752926213 packets to unknown port received
    838001262 packet receive errors
```

The CDN was only able to send logs via UDP syslog. We lost a lot of logs and had to re-ingest them later from the CDN's raw log files.

I arranged with the CDN engineers to configure their syslogs to send to 4 ports instead of one. They managed to do this by pointing the syslog destination to a random port from the range 32000…32003 across all 50+ nodes they ran. Sadly, there was no Vector in this CDN; it was syslog-based "like it's 1999".

Nevertheless, it helped a lot – not a single UDP error has happened since we arranged this. So, for those looking for better UDP source performance: if you can arrange for data to be sent to a random port within a certain range, Vector delivers, even with one thread per UDP listening socket. Even with 100k+ UDP datagrams per second.

This is my example configuration on one of my 4 receiver nodes:
```
sources:
  cdn_32000_logs:
    type: syslog
    address: 0.0.0.0:32000
    mode: udp
  cdn_32001_logs:
    type: syslog
    address: 0.0.0.0:32001
    mode: udp
  cdn_32002_logs:
    type: syslog
    address: 0.0.0.0:32002
    mode: udp
  cdn_32003_logs:
    type: syslog
    address: 0.0.0.0:32003
    mode: udp

transforms:
  cdn_composite_logs:
    type: remap
    inputs:
      - cdn_32000_logs
      - cdn_32001_logs
      - cdn_32002_logs
      - cdn_32003_logs
    source: |
      . = . # just hands it off for later processing
```
The idea here is to spread the UDP receive load across more than one thread. It seems that Vector handles each UDP source single-threaded; with just one source, we weren't able to process more than 80k UDP messages per second, even on a 28-core VM.
