### ISSUE TITLE
Ability to select `internal_metrics` metrics

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5164]
The ability to select which metrics the `internal_metrics` source emits will give users finer grain control over the metrics they want. This is similar to the `host_metrics` source with its various domains (`disk`, `memory`, etc).

## Example

```toml
[sources.internal_metrics]
type = "internal_metrics"
kinds = ["core", "sources", "transforms", "sinks"] # defaults to all
sources = ["my-source-id"] # defaults to all
transforms = ["my-transform-id"] # defaults to all
sinks = ["my-sink-id"] # defaults to all
```
