### ISSUE TITLE
Elasticsearch sink logs credentials in debug mode

### ISSUE THREAD

**Issue by djensen1997** [vectordotdev/vector#5684]
### Vector Version

```
0.11.1
```

### Vector Configuration File

```toml
# Set global options
    data_dir = "/var/lib/vector"

    # inputs
    [sources.input]
    type = "kafka"

    [sources.metrics]
    type = "internal_metrics"


    # in place mutations
    [transforms.parse_input]
    type = "json_parser"
    inputs = ["input"]
    drop_invalid = true


    # outputs
    [sinks.elasticsearch]
    type = "elasticsearch"
    inputs = ["parse_input"]
    index = "logstash-input-%Y.%m.%d"
    host = "https://elasticsearch-master:9200"
    [sinks.elasticsearch.batch]
    max_size = 5490000
    timeout_secs = 1
    [sinks.elasticsearch.auth]
    strategy = "basic"
    password = "${ELASTIC_PASSWORD}"
    user = "${ELASTIC_USERNAME}"

    [sinks.metrics_out]
    type = "prometheus_exporter"
    inputs = ["metrics"]
    address = "0.0.0.0:8080"
    default_namespace = "detections"
```

### Expected Behavior

I believe that the elasticsearch sink should have sanitized the header "authorization": "Basic <my_credentials_base_64_encoded>" in debug mode.

### Actual Behavior

It logged the entire header which included my credentials for my elasticsearch cluster

### Example Data

```
DEBUG http: vector::internal_events::http_client: Sending HTTP request. uri=https://elasticsearch-master:9200/_cluster/health method=GET version=HTTP/1.1 headers={"authorization": "Basic <my_credentials>", "user-agent": "Vector/0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)", "accept-encoding": "identity"} body=[empty]
```
