### ISSUE TITLE
Vector consuming 100% CPU on a core sending to 124 AWS Cloudwatch Log Streams

### ISSUE THREAD

**Issue by CovertIII** [vectordotdev/vector#5837]
I'm using vector as an agent and central aggregator in AWS.  I have a Kafka cluster in the middle.  The agent is on 124 "worker" (t2.nano) VMs sending data to kafka (using AWS MSK).  The aggregator is on a c5.xlarge ec2 instance pulling the data out of Kafka.  I want the aggregator to send Cloudwatch logs and send to a separate log stream for each worker (in the same log group), but I'm running into performance issues.  The vector aggregator process uses 100% of one of the cores and eventually slows down and stops working.  I also get rate limit errors from AWS. If I send the logs to all one log stream, then vector only uses around 2% CPU and I don't get any rate limit errors.  I plan to update to 0.11 soon.  Sending the logs from the worker vms doesn't work as there isn't enough resources to send to Cloud Watch (we ran into performance issues doing that as well).  We don't want to update to a micro instance on the workers because that would increase our costs.  Right now I'm sending the logs to all one stream and we just search the logs by worker host in AWS, but ideally I'd like each worker to have it's own stream.  Any ideas to get around the performance issues?  Are there any other options I could consider?

I'm guessing this happens because of the rate limiting code for each stream.  

### Vector Version

In between 0.10 and 0.11 - commit hash `18a4001ae40194739f29c566a11319fa9112a000`.

### Vector Configuration File

Agent: 

```toml
data_dir = "/var/lib/vector"

[sources.journald_logs]
  type = "journald"
  include_units = [ "workerProcess" ]

[sinks.kafka_stream]
  type = "kafka"
  inputs = ["journald_logs"]
  bootstrap_servers = "xxxxx"
  healthcheck = truetopic = "Prod-logs"
  encoding.codec = "json"
```

Aggregator: 

```toml
data_dir = "/var/lib/vectorWorker"

[sources.plat_syncers]
  type = "kafka"
  bootstrap_servers = "xxxxx"
  group_id = "production-logger-consumer"
  topics = ["Prod-logs"]

[transforms.json_syncer_transform]
  type = "json_parser"
  inputs = ["plat_syncers"]
  drop_field = true
  drop_invalid = true
  overwrite_target = true
  field = "message"

[sinks.cloudwatch_syncer_logs]
  type = "aws_cloudwatch_logs"
  inputs = ["json_syncer_transform"]
  group_name = "production/workers"
  create_missing_group = true
  create_missing_stream = true
  healthcheck = true
  region = "us-east-1"
  stream_name = "{{host}}"
  encoding.codec = "text"
  encoding.only_fields = ["timestamp","message"]
```

### Expected Behavior

Vector runs as normal.

### Actual Behavior

Vector consumes 100% of the CPU on the core. 

### Additional Context

I'm managing vector via NixOS.
