### ISSUE TITLE
Curly braces in file source exclude patterns not supported

### ISSUE THREAD

**Issue by pablosichert** [vectordotdev/vector#5936]
### Vector Version

```
vector 0.12.0
```

### Vector Configuration File

```toml
[sources.files]
  type = "file"
  include = ["*.log"]
  exclude = ["{foo,bar}.log"]

[sinks.console]
  inputs = ["files"]
  type = "console"
  encoding.codec = "text"
```

### Expected Behavior

The vector file source ignores `foo.log` and `bar.log`.

### Actual Behavior

Files `foo.log` and `bar.log` are ingested.

### Additional Context

The `exclude_patterns` currently relies on [`glob::Pattern`](https://docs.rs/glob/0.3.0/glob/struct.Pattern.html) which does not support curly-brace patterns. The `globwalk` crate used for `include_patterns` doesn't provide any means to just pattern match without walking the FS.

Proposed approach:

`GlobWalker` internally [uses](https://github.com/Gilnaa/globwalk/blob/master/src/lib.rs#L347) `ignore::Override`, and supports [adding](https://github.com/Gilnaa/globwalk/blob/master/src/lib.rs#L197) `patterns` to the `ignore::overrides::OverrideBuilder`. The `OverrideBuilder` supports [negating matches](https://github.com/BurntSushi/ripgrep/blob/a6d05475fb353c756e88f605fd5366a67943e591/crates/ignore/src/overrides.rs#L130-L133) by prepending the glob with a `!`.

### References

- #5003
- #5927
