### ISSUE TITLE
gcp_stackdriver_logs: Allow specifying a log_id_key

### ISSUE THREAD

**Issue by kamalmarhubi** [vectordotdev/vector#6009]
### Current Vector Version
```
vector 0.12.0 (gfece636 x86_64-unknown-linux-musl 2021-01-12)
```

### Use-cases
I'm running containers on GCE, and attempting to use Vector to collect their logs. The log name can only be set at the sink level, and cannot be modified to include any identifying information for the containers. Google's fluentd-based logging agent will pull the name from fluentd's log tag, which can be set up to include this information.

### Attempted Solutions
From code, it looks like there's no workaround possible here.

### Proposal
Add a key similar to enable pulling this out of the event remapping, similar to the [`severity_key`](https://vector.dev/docs/reference/sinks/gcp_stackdriver_logs/#severity_key) setting.

Configuration could look like this:

```toml
[sinks.my_sink_id]
  # General
  type = "gcp_stackdriver_logs" # required
  inputs = ["my-source-or-transform-id"] # required
  log_id_key = "gcpLogId"
  project_id = "vector-123456" # required
  resource.type = "gce_instance"
```

and it would result in this input

```json
{
  "message": "HI",
  "gcpLogId": "vector-logs-1"
}
```

being sent to GCP Cloud Logging as

```json
{
    "entries": [
        {
            "severity": 0,
            "jsonPayload": {
                "message": "HI"
            }
        }
    ],
    "log_name": "projects/vector-123456/logs/vector-logs-1",
    "resource": {
        "type": "gce_instance"
    }
}
```

### References
None for now.
