### ISSUE TITLE
add_fields component panics when a referenced field contains a "%" character.

### ISSUE THREAD

**Issue by ClemArt** [vectordotdev/vector#6051]
Hi Vector team, thank you for the amazing product.

### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-gnu 2020-12-17)
```

### Vector Configuration File

Note that this configuration contains the strict minimum to reproduce the bug with a unit test.
```toml
data_dir = "/var/lib/vector/"

# We add the year in front of the message 
[transforms.add_year]
  # General
  type = "add_fields"
  inputs = [] 
  # Fields
  fields.message_timed = "%Y {{message}}"

# This test will pass
[[tests]]
  name = "Template issue message without %"

  [[tests.inputs]]
    insert_at = "add_year"
    type = "log"
    log_fields.message = "I am a message without a percentage"
  [[tests.outputs]]
    extract_from = "add_year"
  [[tests.outputs.conditions]]
    type = "check_fields"
    "message_timed.eq" = "2021 I am a message without a percentage"

# This test will panic
[[tests]]
  name = "Template issue message"

  [[tests.inputs]]
    insert_at = "add_year"
    type = "log"
    log_fields.message = "I am a message with a sneaky percentage %"
  [[tests.outputs]]
    extract_from = "add_year"
  [[tests.outputs.conditions]]
    type = "check_fields"
    "message_timed.eq" = "2021 I am a message with a sneaky percentage %"

```

### Debug Output

Available here: https://gist.github.com/ClemArt/f69a545769c7e4ad31c9eb7e888d9daa

### Expected Behavior

I expect the message to contain the new field created from the original message and formated date.

The unit test in the configuration above validates this behaviour.

### Actual Behavior

When the add_fields component encounters a message with a '%', it does one of 2 things:
- best case: It interprets the % and outputs a piece of templated string
- worst case: it panics and shutdowns vector. This is what happens with the configuration above

Note: It happens only because I use a date format operand (*%Y*) along with the reference to the field *{{message}}* in the add_fields component. If I remove either the reference to *{{message}}* or the date *%Y*, it works fine.

### Example Data

```
I am a message with a sneaky percentage %
I am another sneaky %percentage that will get interpreted
Jan  2 06:35:08 rbxweb1 postfix/scache[4663]: statistics: domain lookup hits=5 miss=8 success=38%
```
### Additional Context

like said above, this only happens when I use `fields.message_new = "%Y {{message}}"` to add a new field by both using a date format and a reference to the message. Then the error happens when the message contains a **%**.

My best guess is that this setup leads to an interpretation of the message's **%**, whereas it should only be treated as a string.
