### ISSUE TITLE
Infinite looping when garbage sent to Vector port

### ISSUE THREAD

**Issue by nepeat** [vectordotdev/vector#6064]
### Vector Version
```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)
```

### Vector Configuration File
```toml
[sources.vector]
type = "vector"
address = "0.0.0.0:9000"

[sinks.out]
type = "console"
inputs = [ "vector" ]
encoding.codec = "json"
```

### Debug Output
https://gist.github.com/nepeat/d681f5248a06eb2cdc83d7a4cbdeafd1

### Expected Behavior
Vector ignores the garbage message and logs a warning message.

### Actual Behavior
Infinite loop of
`Jan 15 00:06:38.260  WARN source{component_kind="source" component_name=vector component_type=vector}:connection{peer_addr=[PEER IP]}: vector::sources::util::tcp: Failed to read data from TCP source. error=frame size too big`

### Example Data
Telnet into port 9000 of the listening Vector server and hit enter a few times.

### Additional Context
Vector running on Docker
