### ISSUE TITLE
Source: InfluxDB Line Protocol

### ISSUE THREAD

**Issue by Walther** [vectordotdev/vector#6100]
### Current Vector Version

```
vector 0.11.1 (v0.11.1 aarch64-unknown-linux-musl 2020-12-17)
```

### Use-cases

[InfluxDB Line Protocol](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/) is a fairly simple line format to write multiple metrics in a single line. It is one option for application authors to write metrics from their app to e.g. stdout, socket, or other, for further collection and processing (by e.g. Telegraf).

See e.g. https://github.com/lautis/ruuvitag-listener

```
ruuvi_measurement,mac=XX:XX:XX:XX:XX:XX,name=XX:XX:XX:XX:XX:XX acceleration_x=-0.064,acceleration_y=-0.056,acceleration_z=0.976,battery_potential=2.953,humidity=12.43,measurement_sequence_number=16995,movement_counter=228,pressure=101.867,temperature=21.12,tx_power=4 1610810549185317646
```

### Attempted Solutions

Given `ruuvitag-listener` running with `systemd` with `ExecStart = /bin/sh -c 'ruuvitag-listener | netcat -q0 -U /tmp/telegraf-ruuvitag.sock'`,

Trying to use a socket listener for the 
```toml
[sources.ruuvitag_source]
  type = "socket" # required
  mode = "unix" # required
  path = "/tmp/vector-ruuvitag.sock" # required, required when mode = `unix`

[sinks.ruuvitag_sink]
  # General
  type = "influxdb_metrics" # required
  inputs = ["ruuvitag_source"] # required
  bucket = "office" # required
  endpoint = "http://localhost:8086/" # required
```

results in
```
ERROR vector::cli: Configuration error. error=Data type mismatch between ruuvitag_source (Log) and ruuvitag_sink (Metric)
```

Currently, it seems like using https://vector.dev/docs/reference/transforms/log_to_metric/ would require explicitly configuring every individual field of the output. This could be possible, but also rather inconvenient - especially considering the InfluxDB Line Format is supposed to have all the necessary information already.

### Proposal

Native support in Vector for InfluxDB Line Protocol as a source or a transform, in a way that an stdin / socket / other source can be processed and sent to an InfluxDB sink by vector in a convenient way, without a need for another application (like Telegraf).
