### ISSUE TITLE
Enhancement Request - Update Prometheus Remote Write Sink to support authentication and authorization for use with Amazon Managed Service for Prometheus (AMP)

### ISSUE THREAD

**Issue by ryn9** [vectordotdev/vector#6204]
### Current Vector Version

0.11.1

### Use-cases

Update Prometheus Remote Write Sink to support authentication and authorization for use with Amazon Managed Service for Prometheus (AMP)

### Attempted Solutions

N/A

### Proposal

Update Prometheus Remote Write Sink to support authentication and authorization for use with Amazon Managed Service for Prometheus (AMP)

This should largely look like the AWS auth mechanism provided in the aws_* sinks or the Elasticsearch Sink (though they do get configured slightly differently) 

### References

https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-secure-metric-ingestion.html

https://vector.dev/docs/reference/sinks/prometheus_remote_write/
https://vector.dev/docs/reference/sinks/aws_cloudwatch_logs/
https://vector.dev/docs/reference/sinks/aws_cloudwatch_metrics/
https://vector.dev/docs/reference/sinks/aws_kinesis_firehose/
https://vector.dev/docs/reference/sinks/aws_kinesis_streams/
https://vector.dev/docs/reference/sinks/aws_s3/
https://vector.dev/docs/reference/sinks/aws_sqs/
https://vector.dev/docs/reference/sinks/elasticsearch/

**Comment by conblem** [comment]
This is also needed for Grafana Cloud Prometheus

**Comment by wperron** [comment]
I can look into it 👍

**Comment by wperron** [comment]
Now that I look at the docs, Grafana Cloud uses basic auth with username & password, that's already supported is it not?

**Comment by ryn9** [comment]
> Now that I look at the docs, Grafana Cloud uses basic auth with username & password, that's already supported is it not?

If it is - its not in the docs - https://vector.dev/docs/reference/sinks/prometheus_remote_write/

**Comment by wperron** [comment]
was looking at source not the sink 🤦 forget I said anything

**Comment by bruceg** [comment]
While PR #6281 does add authentication support, it does not cover AWS SIGv4 authentication that was required by the original post, according to the OP, so I am reopening this. https://github.com/timberio/vector/pull/6281#issuecomment-773476399

**Comment by wperron** [comment]
given the specificities of the aws sinks, I think it's worth asking whether or not Amazon Managed Prometheus should be a completely new sink or not

**Comment by jszwedko** [comment]
Requested by user in discord: https://discord.com/channels/742820443487993987/759154784309215252/852319630780399636

**Comment by antonyc** [comment]
Got this problem too. Not a vector-guru, but probably authentication is just an independent layer on top of remote write. So a simple prom-remote-write sink with custom auth seems to be an OK solution to me.

**Comment by antonyc** [comment]
but there might be a workaround with IAM policies, setting up aggregator to send from VM with correct iam role, isn't is? I am just guessing, cause I am still didn't solve the problem mentioned in the issue.

**Comment by antonyc** [comment]
I came to idea of setting up dedicated envoy, serving as a proxy with SA role of writing to AMP, it is capable of signing sigv4 correctly. And vector sending http requests to envoy. prom remote write seems to be http, so this should probably be easy. https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_request_signing_filter

**Comment by ocrlgv** [comment]
> I came to idea of setting up dedicated envoy, serving as a proxy with SA role of writing to AMP, it is capable of signing sigv4 correctly. And vector sending http requests to envoy. prom remote write seems to be http, so this should probably be easy. https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_request_signing_filter

you got a working config, I gave it a try but envoy configuration was confusing and error'd on me. I really need to move off prometheus_exporter as a way to scrape the metrics. needs to be pushed.

**Comment by markmartirosian** [comment]
envoy configuration:

```yaml
static_resources:
  listeners:
    - address:
        socket_address:
          protocol: "TCP"
          address: 127.0.0.1
          port_value: 8888
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: aps-workspaces
                strip_any_host_port: true
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: aps-workspaces
                      domains: ['*']
                      routes:
                        - name: aps-workspaces
                          match:
                            prefix: /
                          route:
                            cluster: aps-workspaces
                http_filters:
                  - name: envoy.filters.http.aws_request_signing
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning
                      service_name: aps
                      region: us-east-1
                      host_rewrite: aps-workspaces.us-east-1.amazonaws.com
                  - name: envoy.filters.http.router
                    typed_config: {}
  clusters:
    - name: aps-workspaces
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      lb_policy: ROUND_ROBIN
      transport_socket:
        name: envoy.transport_sockets.tls
      load_assignment:
        cluster_name: aps-workspaces
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: aps-workspaces.us-east-1.amazonaws.com
                      port_value: 443

```
