### ISSUE TITLE
New config unit tests interface

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6261]
This has been a long time coming but has not been a priority over other work. Given the new Remap support in Vector's "conditions" and the change in #6255, it's time to reconsider the unit tests interface.

## The problem

The [unit tests interface](https://master.vector.dev/docs/reference/configuration/tests/) was hastily designed before Remap existed. The initial version served as a proof of concept and, at this point, we can deem it a useful feature, but it suffers from many of the same problems that our fundamental transforms did:

1. A very clunky, verbose TOML syntax.
2. Hard to read and write.
3. Very limited set of conditions for assertions.
3. Poor error and failure messages.

For example:

```toml
[transforms.foo]
  type = "regex_parser"
  regex = "^(?P<timestamp>[\\w\\-:\\+]+) (?P<level>\\w+) (?P<message>.*)$"

[[tests]]
  name = "foo test" # required

  [[tests.inputs]]
    insert_at = "foo"
    type = "raw"
    value = "2020-02-01T04:23:22.232223Z INFO Hello, World!"

  [[tests.outputs]]
    extract_from = "foo" # required
    conditions.type = "check_fields"
    conditions."level.eq" = "INFO"
    conditions."message.eq" = "Hello, World!"
```

## Proposal

Given that we are deprecating `check_fields` in #4791, we should consider a radically simpler interface that leverages Remap:

### Single event

```toml
[transforms.foo]
  type = "regex_parser"
  regex = "^(?P<timestamp>[\\w\\-:\\+]+) (?P<level>\\w+) (?P<message>.*)$"

[tests.foo_success]
  source = '''
    .message = "2020-02-01T04:23:22.232223Z INFO Hello, World!"
    output = transform!(insert_at: "foo", extract_from: "foo")
    assert!(output.level == "INFO")
    assert!(output.message == "Hello, World!")
    '''
```

### Multiple events

```toml
[transforms.foo]
  type = "regex_parser"
  regex = "^(?P<timestamp>[\\w\\-:\\+]+) (?P<level>\\w+) (?P<message>.*)$"

[tests.foo_success]
  source = '''
    # Event 1
    .message = "2020-02-01T04:23:22.232223Z INFO Hello, World!"
    output = transform!(insert_at: "foo", extract_from: "foo")
    assert!(output.level == "INFO")
    assert!(output.message == "Hello, World!")
  
    # Event 2
    .message = "2020-02-01T04:23:23.382872Z INFO Hello, World, Again!"
    output = transform!(insert_at: "foo", extract_from: "foo")
    assert!(output.level == "INFO")
    assert!(output.message == "Hello, World, Again!")
    '''
```

## Implementation

I find the `[tests.foo_success]` syntax much nicer. It follows the same pattern as defining components and requires each test to have a unique identifier. Therefore, we can use this to support the new structure. If `tests` is an array, then we know it's using the old structure, if it's a map then we know it's using the new structure.

**Comment by JeanMertz** [comment]
The biggest disadvantage of using VRL right now is that its error messages aren't tailored to being used in test-cases.

Nothing we can't handle, but worth considering as we refine this proposal further.

Ideally, we'd be able to leverage the same diagnostic style error messages that we use in the compilation step of VRL programs, to make it abundantly clear what's causing the test failure.

Also, I'm not sure how annoying it will be if VRL starts complaining about fallible expressions etc when you are writing a test. I guess it's a trade-off because if we don't, then your test might fail in unexpected ways, but it's again something to consider.

**Comment by jszwedko** [comment]
Just noting that it is possible to use `remap` condition checks now for unit tests. It does suffer the drawbacks that @JeanMertz mentioned though.

**Comment by jszwedko** [comment]
I started digging into this a bit today.

Proposed changes:

* Deprecate returning a boolean as the final expression to fail the unit test. Instead, document how to use `assert` and `assert_eq` to induce a failure that will cause the script to exit and report the failure.
* Alias `vrl` to `remap` for condition `type`. This is more in-line with separating the transform, `remap`, with the language, `vrl`.
* Update the VRL output to include the line number and text of the expression that failed.
* A nice-to-have goal is to run the entire script even if an assertion fails so you can see all failing assertions at the end rather than just the first one. I'm unsure exactly how invasive a change this would be though.

For example:

```toml
[transforms.remap]
  inputs = []
  type = "remap"
  source = """
    .five = 5
    .six = 6
  """
[[tests]]
  name = "remap"
  [tests.input]
    insert_at = "remap"
    type = "log"
    [tests.input.log_fields]
      message = ""
  [[tests.outputs]]
    extract_from = "remap"
    [[tests.outputs.conditions]]
      type = "remap"
      source = """
      foo = 1
      assert!(.five == .six)
      bar = 2
      """
```

When run as a test, currently outputs:

```
test remap ... failed

failures:

test remap:

check transform 'remap' failed conditions:
  condition[0]: source execution failed: function call error for "assert" at (6:25): assertion failed
payloads (events encoded as JSON):
   input: {"message":"","timestamp":"2021-06-17T22:46:09.121405Z"}
  output: {"five":5,"message":"","six":6,"timestamp":"2021-06-17T22:46:09.121405Z"}
```

I would have it output something closer to what we have for the diagnostic errors during compilation:

```
test remap ... failed

failures:

test remap:

check transform 'remap' failed conditions:
  condition[0]: failed
    2 │ assert!(.five == .six)
      │ ^^^^^^^^^^^^^^^^^^^^^^
      | |
      | function call error for "assert" at (6:25): assertion failed
payloads (events encoded as JSON):
   input: {"message":"","timestamp":"2021-06-17T22:46:09.121405Z"}
  output: {"five":5,"message":"","six":6,"timestamp":"2021-06-17T22:46:09.121405Z"}
```
