### ISSUE TITLE
Loki Sink Documentation: Better clarify labels

### ISSUE THREAD

**Issue by rlabrecque** [vectordotdev/vector#6435]
There's been a few topics running into this already, but the documentation around labels could use some improvement. It should work out of the box.
https://github.com/timberio/vector/issues/6381

https://vector.dev/guides/integrate/sinks/loki/

```
labels.event = "{{ event_field }}" # example

labels.* = "vector"
labels.* = "{{ event_field }}"
```

There's just a lot of uncertainty around this. Notably:
1. Is `{{ event_field }}` special or meant as a place holder?
2. I think `.*` should be replaced with something like `.yourlabelhere`

**Comment by rlabrecque** [comment]
```

sinks:
  loki_sink:
    type: loki
    inputs:
      - "kubernetes_logs"
    rawConfig: |
      endpoint = "http://loki.prod.svc.cluster.local:3100"
      encoding.codec = "json"

      # Labels
      labels.job                        = "{{ source_type }}"
      labels.kubernetes_container_name  = "{{ kubernetes.container_name }}"
      labels.kubernetes_pod_labels_app  = "{{ kubernetes.pod_labels.app }}"
      labels.kubernetes_pod_namespace   = "{{ kubernetes.pod_namespace }}"
```

This is what I have now. Was easy to figure out once I seen some real-world usages of this. Like `{{ kubernetes.container_name }}` was more useful to me than {{ event_field }}

**Comment by jszwedko** [comment]
@lucperkins just assigning this to you since you self-assigned https://github.com/timberio/vector/issues/6496 and it feels pretty similar.

**Comment by jszwedko** [comment]
Hi @randomchance ! Not currently. I thought we had a tracking issue for that, but I'm not seeing it. Would you want to open one if it'd be useful to you?

**Comment by randomchance** [comment]
Hi @jszwedko, I could create one, however I want to make sure I understand the existing usage because I am second guessing myself ... it would make it harder to debug incorrect labels.

Sorry for all the questions, but I'm _very_ new to vector, I guess it shows another possible "opportunity" for the documentation!

Would the existing solution be to have the sink duplicated?

```toml
[sinks.loki-app]
type = "loki"
inputs = [ "log-stuff" ]

[sinks.loki-app.labels]
application = "{{downcase(string!(.Application)) }}"
computer = "downcase(string!(.HostMachineName))"

[sinks.loki-svr]
type = "loki"
inputs = [ "log-stuff" ]

[sinks.loki-svr.labels]
region = "{{downcase(string!(.Region)) }}"
computer = "downcase(string!(.HostMachineName))"

```
