### ISSUE TITLE
Documentation for swimlane/route transform uses confusing `*` placeholder

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6496]
The docs on https://master.vector.dev/docs/reference/configuration/transforms/route/#state and https://vector.dev/docs/reference/transforms/swimlanes/ use `*` as a placeholder to indicate that users should choose their own value but I don't think this is very apparent at all.

The example config:

```toml
[transforms.my_transform_id]
  # General
  type = "route" # required
  inputs = ["my-source-or-transform-id", "prefix-*"] # required

  # Route
  route."*" = '.status_code != 200 && !includes(["info", "debug"], .severity)' # example
```

Is invalid. Users need to replace the `*` with a name for the route.

I think we should update the doc to use an actual name there or otherwise indicate that it is a placeholder and should be replaced by the user. For example, something like:

```toml
[transforms.my_transform_id]
  # General
  type = "route" # required
  inputs = ["my-source-or-transform-id", "prefix-*"] # required

  # Route
  route.my_custom_route_name = '.status_code != 200 && !includes(["info", "debug"], .severity)' # example
```

Would be more clear.

This also tripped up a user in the `loki` sink: https://github.com/timberio/vector/issues/6435
