### ISSUE TITLE
Optimize syslog aggregator integration benchmark

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6511]
Once #6510 is complete we should start to optimize the included benchmarks, starting with the simplest first. Among those simple use cases is the Syslog aggregator use case, where Vector receives data from upstream Syslog agents, aggregates the data, and forwards it downstream.

## Setup

The config for this benchmark should look something like this:

```toml
[sources.syslog]
type = "syslog"
mode = "tcp"
# ...

[sinks.socket]
type = "socket"
mode = "tcp"
# ...
```

A few things to note:

1. The `syslog` source embeds Syslog parsing.
2. We've used our [`tcp_test_server`](https://github.com/timberio/tcp_test_server) tool for the `socket` sink in other tests.
3. I am open to swapping out the `socket` sink with an `http` sink. We should eventually optimize both.

## Goals

To reclaim 80% of the throughput lost since Vector 0.2.0.
