### ISSUE TITLE
Improve buckets for http_client_response internal metric

### ISSUE THREAD

**Issue by alexgavrisco** [vectordotdev/vector#6546]
### Current Vector Version

```
0.11.1
```

### Use-cases

Currently the `http_client_response_rtt` metric has precision in `ns` while the biggest bucket (besides `+Inf`) is `10`, thus for the wast majority of requests RTT will be counted as `+Inf`.
This basically renders the histogram useless.

### Proposal

Ideally it should be possible to configure/override default buckets, since real-world RTT will be quite different from client to client.
However a good start would be defining buckets with a big enough step so the max value is at least 10s.

**Comment by jszwedko** [comment]
Thanks for the report @Alexx-G !

I'd argue this is a bug since it is very likely to not result in correct behavior.

To clarify, it looks like it is the `prometheus` sinks that are doing the bucketing with a default bucket strategy:

https://github.com/timberio/vector/blob/c6fb969b51b24df2270d2983cf16d8ae4093567e/src/sinks/prometheus/mod.rs#L5-L9

This is configurable at the sink level, but I believe we should be bucketing more intelligently as it is hard to imagine a case where a static set of buckets is appropriate across all histogram metrics. Each histogram set will have its own range.

**Comment by jszwedko** [comment]
I validated this using the following config:

```toml
[sources.in]
type = "stdin"

[sources.metrics]
type = "internal_metrics"

[sinks.prometheus]
type = "prometheus"
address = "127.0.0.1:9000"
inputs = ["metrics"]

[sinks.out]
type = "http"
uri = "http://127.0.0.1:8000"
inputs = ["in"]
encoding.codec = "json"
```
