### ISSUE TITLE
Swimlanes verification

### ISSUE THREAD

**Issue by aragastmatb** [vectordotdev/vector#6557]
### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-apple-darwin 2020-12-17)
```

### Vector Configuration File

```toml
[sources.my_source_id]
  type = "socket"
  address = "0.0.0.0:9000"
  max_length = 102400
  mode = "tcp"
[transforms.my_transform_id]
  type = "swimlanes"
  inputs = ["my_source_id"]
  lanes.highlevel.type = "check_fields"
  lanes.highlevel."level.eq" = "foo"

  [sinks.tf]
    inputs = ["my_transform_id.highlevel"]
    type = "file"
    path = "/path/to_file"
```
```yaml
---
sources:
  my_source_id:
    type: socket
    address: 0.0.0.0:9000
    max_length: 102400
    mode: tcp
transforms:
  my_transform_id:
    type: swimlanes
    inputs:
    - my_source_id
    lanes:
      highlevel.type: check_fields
      highlevel."level.eq": "foo"
sinks:
  tf:
    inputs: ["my_transform_id.highlevel"]
    type: "file"
    path: "/path/to_file"
```

### Debug Output

```bash
RUST_BACKTRACE=full vector -vvv validate anot_conf.toml 
√ Loaded ["anot_conf.toml"]
```
```bash
RUST_BACKTRACE=full vector -vvv validate exmp_conf.yml
Failed to load ["exmp_conf.yml"]
--------------------------------
x transforms.my_transform_id: data did not match any variant of untagged enum AnyCondition at line 10 column 9
```
### Expected Behavior

Successful validate toml and yaml configuration file.
### Actual Behavior

Got error on yaml configuration file, but toml got successful run validator.
### Additional Context

I am not sure, what this is a bug, but on a page with document about [swimlanes](https://vector.dev/docs/reference/transforms/swimlanes/) when you click on "Edit this page" or "View Source" get 404 error. And i can't find some source code swimlanes transform in GitHub repository.

**Comment by jszwedko** [comment]
Hi @aragastmatb ,

The YAML syntax for the swimlanes transform is actually a little different from the docs. I'd opened #6578 to clear that up.

For your example, something like:

```
---
sources:
  my_source_id:
    type: socket
    address: 0.0.0.0:9000
    max_length: 102400
    mode: tcp
transforms:
  my_transform_id:
    type: swimlanes
    inputs:
    - my_source_id
    lanes:
      highlevel:
        type: check_fields
        "level.eq": "foo"
sinks:
  tf:
    inputs: ["my_transform_id.highlevel"]
    type: "file"
    path: "/path/to_file"
    encoding:
      codec: "ndjson"
```

Should do the trick. Notice the translation of TOML tables into YAML maps (also adding the `encoding` option to the sink).
