### ISSUE TITLE
route/swimlane transform YAML example is misleading

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6578]
User ran into this in discord trying to migrate their config to YAML: https://discord.com/channels/742820443487993987/746070591097798688/815735053048610839

The YAML example on https://vector.dev/docs/reference/transforms/swimlanes/ is:

```yaml
---
transforms:
  my_transform_id:
    type: swimlanes
    inputs:
    - my-source-or-transform-id
    lanes:
      "*.type": check_fields
      '*."message.eq"': foo
      '*."message.not_eq"': foo
      '*."message.exists"': true
      '*."message.not_exists"': true
      '*."message.contains"': foo
      '*."message.not_contains"': foo
      '*."message.ends_with"': foo
      '*."message.not_ends_with"': foo
      '*."message.ip_cidr_contains"': 10.0.0.0/8
      '*."message.not_ip_cidr_contains"': 10.0.0.0/8
      '*."message.regex"': " (any|of|these|five|words) "
      '*."message.not_regex"': " (any|of|these|five|words) "
      '*."message.starts_with"': foo
      '*."message.not_starts_with"': foo
```

When really it should be something like:

```yaml
---
transforms:
  my_transform_id:
    type: swimlanes
    inputs:
    - my-source-or-transform-id
    lanes:
      lane1:
         type: check_fields
        "message.eq": foo
      lane2:
         type: check_fields
        "message.not_eq": foo
```

That is, a YAML map should be used rather than the `.` syntax. I also removed the wildcard in my example as that has also led to confusion: https://github.com/timberio/vector/issues/6435
