### ISSUE TITLE
Set @timestamp field automatically when use elasticsearch data streams

### ISSUE THREAD

**Issue by ethinx** [vectordotdev/vector#6592]
### Vector Version

```
vector 0.12.0 (gfc7c788 x86_64-unknown-linux-gnu 2021-03-02)
```

### Vector Configuration File

```toml
[sources.tcp]
  type = "socket"
  address = "0.0.0.0:29000"
  mode = "tcp"

[transforms.tcp_regex_parser]
  type="regex_parser"
  inputs = ["tcp"]
  field = "message"
  drop_field = false
  patterns = [
        '^(?P<log_ts>\d+.*) \[(?P<loglevel>\w+)\] <\S+:\d+> (?P<category>\S+) - (?P<namespace>\S+) (?P<service>\S+)-\S+-\S+',
        ]

[transforms.es_time_transformer]
  type = "remap" # required
  inputs = ["tcp_regex_parser"] # required
  source = '''
  .timestamp, _ = parse_timestamp(string!(.log_ts), "%F %H:%M:%S%.f")
  .@timestamp = .timestamp
  '''

[sinks.elasticsearch]
  type = "elasticsearch" # required
  inputs = ["es_time_transformer"] # required
  compression = "none" # optional, default
  endpoint = "http://example.com:9200" # required
  index = "stream-log"
  bulk_action = "create"
  auth.user = "vector"
  auth.password = "vector"
  auth.strategy = "basic"
```

### Expected Behavior
Log can be streamed to elasticsearch data streams, without additional transformer.

### Actual Behavior
We need to use a remap transformer and add additional `@timestamp` field 

### Example Data
```
2021-02-08 23:37:06.989305 [INFO] <vector.go:1> vector - vector-ns vector-service-654ff4cd76-hpqwz - msg:hello world!
```

### References
https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html

>Every document indexed to a data stream must contain a @timestamp field, mapped as a date or date_nanos field type. If the index template doesn’t specify a mapping for the @timestamp field, Elasticsearch maps @timestamp as a date field with default options.
