### ISSUE TITLE
Sink into Clcikhouse datetime value

### ISSUE THREAD

**Issue by aragastmatb** [vectordotdev/vector#6618]
### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)
```

#### Vector near FoundationDB
```toml
[sources.fdb_log]
  type = "file"
  include = ["/fdb/log/fdbserver/4500/*.json"]

[transforms.parse_fdb_log]
  type = "json_parser"
  inputs = ["fdb_log"]
  drop_invalid = false
  drop_field = false
[transforms.add_nodename_log]
  type = "add_fields"
  inputs = ["parse_fdb_log"]
  fields.host = "hostname"

[sinks.send_log]
  type = "vector"
  inputs = ["add_nodename_log"]
  address = "http://clickhouse-server-name:9092"
```
#### Vector near Clickhouse
```toml
[sources.log]
  type = "vector"
  address = "0.0.0.0:9092"

[sinks.clickhouse_fdb_logs]
  inputs = ["log"]
  type = "clickhouse"
  host = "http://localhost:8123"
  database = "fdb"
  table = "fdb_logs"
  healthcheck = true
  encoding.only_fields = ["host", "message", "Time", "OriginalTime", "Type", "Machine", "timestamp"]
  auth.strategy = "basic"
  auth.user = "user"
  auth.password = "pass"
  batch.max_bytes = 10490000
  batch.max_events = 100000
  batch.timeout_secs = 6
  buffer.max_events = 100000
  buffer.max_size = 104900000
  buffer.type = "memory"
  buffer.when_full = "block"
  request.in_flight_limit = 5
  request.rate_limit_duration_secs = 1
  request.rate_limit_num = 5
  request.retry_attempts = 100000
  request.retry_initial_backoff_secs = 1
  request.retry_max_duration_secs = 10
  request.timeout_secs = 30
  compression = "gzip"
```

### Debug Output

```
Mar 04 12:49:53.182 ERROR sink{component_kind="sink" component_name=clickhouse_fdb_logs component_type=clickhouse}:request{request_id=4}: vector::sinks::util::sink: Response wasn't successful. response=Response { status: 400, version: HTTP/1.1, headers: {"date": "Thu, 04 Mar 2021 09:49:53 GMT", "connection": "Keep-Alive", "content-type": "text/tab-separated-values; charset=UTF-8", "x-clickhouse-server-display-name": "clickhouse-server-name", "transfer-encoding": "chunked", "x-clickhouse-query-id": "951af9ff-f64b-4fb2-85c1-d1c066f96e41", "x-clickhouse-format": "TabSeparated", "x-clickhouse-timezone": "Europe/Moscow", "x-clickhouse-exception-code": "27", "keep-alive": "timeout=3", "x-clickhouse-summary": "{\"read_rows\":\"0\",\"read_bytes\":\"0\",\"written_rows\":\"0\",\"written_bytes\":\"0\",\"total_rows_to_read\":\"0\"}"}, body: b"Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected '\"' before: '.891392\",\"Type\":\"LayerStatusFetcher\",\"host\":\"hostname\",\"message\":\"{  \\\\\"Severity\\\\\": \\\\\"10\\\\\", \\\\\"Time\\\\\": \\\\\"1614851386.891392\\\\\", \\\\\"Type\\\\\": \\\\\"LayerStatusFetcher\\\\\"': (while reading the value of key Time): (at row 1)\n (version 20.12.3.3 (official build))\n" }
```

### Expected Behavior

Normal paste data in clickhouse DB

### Actual Behavior

Vector ask me to paste "\\" before "." in "Time" value

### Example Data

Original log FDB (except machine ip) below:
```json
{  "Severity": "10", "Time": "1614840493.654739", "OriginalTime": "1614689289.332166", "Type": "Role", "ID": "0e42b4df86763b33", "As": "Coordinator", "Transition": "Begin", "Origination": "Recruited", "OnWorker": "0000000000000000", "Machine": "0.0.0.0.:4500", "LogGroup": "default", "Roles": "CD,SS,TL", "TrackLatestType": "Rolled" }
{  "Severity": "10", "Time": "1614840493.654739", "OriginalTime": "1614689289.382261", "Type": "Role", "ID": "1fb126a3fab600f3", "As": "ClusterController", "Transition": "Begin", "Origination": "Recruited", "OnWorker": "0000000000000000", "Machine": "0.0.0.0.:4500", "LogGroup": "default", "Roles": "CC,CD,SS,TL", "TrackLatestType": "Rolled" }
```

### Additional Context

Some information about scheme:
1. Several FoundationDB and Clickhouse service deployed in different server. 
2. Nearby FoundationDB service I've deployed Vector with config (example above), just get *.json log-file, parse, add filed and transmit on Vector near Clickhouse. 
3. FDB send datetime in float format, which  succesfully transform into date with clickhouse-client query (INSERT INTO tablename) into table with DateTime64 format. But when I try to send it through Vector - I've got the error.
