### ISSUE TITLE
From datadog metrics to prometheus

### ISSUE THREAD

**Issue by aragastmatb** [vectordotdev/vector#6619]
### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)
but indifferent to version
```

#### Config what I expected
```toml
[sources.wallet]
  type = "statsd"
  address = "0.0.0.0:6768"
  mode = "udp"

[transforms.add_proper]
  type = "add_tags"
  inputs = ["change_symbol"]
  tags.exported_instance = "wallet-instance"
  tags.application_name = "merchant_wallet"

[sinks.application_metric]
  inputs = ["add_proper"]
  type = "prometheus_exporter"
  address = "0.0.0.0:9599"
```

#### Workaround config
```toml
[sources.wallet]
  type = "statsd"
  address = "0.0.0.0:6768"
  mode = "udp"
[transforms.change_symbol]
  inputs = ["wallet"]
  type = "lua"
  version = "2"
  hooks.process = """
function(event, emit)
  event.metric.name = string.gsub(event.metric.name, '%.', '_')
  emit(event)
end
"""
[transforms.add_proper]
  type = "add_tags"
  inputs = ["change_symbol"]
  tags.exported_instance = "wallet-instance"
  tags.application_name = "wallet"

[sinks.add_proper]
  inputs = ["application_filter"]
  type = "prometheus_exporter"
  address = "0.0.0.0:9599"
```

### Expected Behavior

Automatically transformed datadog-fromat metric to prometheus format.

### Actual Behavior

I've got dot-named label in metric: it's OK to datadog format but ERROR for prometheus (only [a-zA-Z0-9:_]])
