### ISSUE TITLE
prometheus_remote_write healthcheck failure when sending to cortex

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6706]
Reported by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/819397101787938826

It looks like, when using the `prometheus_remote_write` sink with cortex, the healthcheck fails:

```
405 Method Not Allowed component_kind="sink" component_type="prometheus_remote_write" component_name="output"
```

```
vector --version
vector 0.12.0 (v0.12.0 x86_64-unknown-linux-gnu 2021-03-10)
```

Config:

```yaml
vectorSource:
  enabled: false
sources:
  input:
    type: "prometheus_remote_write"
    rawConfig: |
      address = "0.0.0.0:9090"
transforms:
  modify:
    type: "add_tags"
    inputs: ["input"]
    rawConfig: |
      overwrite = false
      tags.kubernetes_namespace = "infra-estaleiro"
sinks:
  output:
    type: "prometheus_remote_write"
    inputs: ["modify"]
    rawConfig: |
      endpoint = "http://storage-cortex-distributor:8080/api/prom/push"
      healthcheck = true
      tenant_id = "{{ tags.kubernetes_namespace }}"
  prometheus:
    type: "prometheus_exporter"
    inputs: ["internal_metrics"]
    rawConfig: |
      address = "0.0.0.0:9598"
```
