### ISSUE TITLE
Configuration on https://vector.dev/docs/reference/configuration/tests/ doesn't run

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6728]
```toml
[transforms.foo]
  type = "regex_parser"
  regex = "^(?P<timestamp>[\\w\\-:\\+]+) (?P<level>\\w+) (?P<message>.*)$"

[[tests]]
  # Inputs
  [[tests.inputs]]
    insert_at = "foo" # required
    type = "raw" # required
    value = "some message contents" # required, required when type = "raw"

  # General
  name = "foo test" # required

  # Outputs
  [[tests.outputs]]
    # Conditions
    conditions.type = "check_fields" # optional, default
    conditions."message.eq" = "this is the content to match against" # example
    conditions."message.eq" = ["match this", "or this"] # example
    conditions."message.contains" = "foo" # example
    conditions."message.contains" = ["foo", "bar"] # example
    conditions."environment.ends_with" = "-staging" # example
    conditions."environment.ends_with" = ["-staging", "-running"] # example
    conditions."message.regex" = " (any|of|these|five|words) " # example
    conditions."environment.starts_with" = "staging-" # example
    conditions."environment.starts_with" = ["staging-", "running-"] # example

    # General
    extract_from = "foo" # required
```

Error:

```
missing field `inputs` for key `transforms.foo` at line 16 column 3.
```
