### ISSUE TITLE
vector stopped to read log file (file -> s3)

### ISSUE THREAD

**Issue by mikhno-s** [vectordotdev/vector#6776]
Hi there,
I'm debugging issue with losing event from vector. 

Simple approach: vector in k8s as daemon-set -> reads log files -> does some transforms -> sends event to s3

Pods have memory limitation - 3GB. And most of the pods are being killed by OOM, because for some reason vector starts - eats all memory and die without sending nothing.
And I think it's connected - the amount of .ldb grows in `/var/lib/vector/s3_logs_buffer`
Also, file /var/log/envoy/ingress.log weight around 1GB. (but it's still less, than pod mem limit)

### Vector Version
```
version="0.12.0" git_version="v0.12.0" released="Wed, 10 Mar 2021 15:03:01 +0000" arch="x86_64"
```

### Vector Configuration File

 envoy-logs.toml:
```toml
    [sources.in_envoy_logs]
      type = "file"
      include = ["/var/log/envoy/ingress.log"]
      exclude = ["*gz"]
      glob_minimum_cooldown = 1000
      ignore_older = 86400
      max_read_bytes = 4096

      fingerprinting.strategy = "checksum"
      fingerprinting.ignored_header_bytes = 0

    [sinks.s3_logs]
      inputs = ["in_envoy_logs"]
      type   = "aws_s3"
      bucket = "some_bucket"
      region = "us-east-1"
      encoding.codec = "ndjson"
      key_prefix = "test/${DC}/${NODE_NAME}/%Y/%m/%d/%H/%M/%S/"
      compression = "gzip"
      content_encoding = "gzip"
      buffer.when_full = "block"
      buffer.type = "disk"  
      buffer.max_size = 10049000000
      batch.max_bytes = 10000000
      batch.timeout_secs = 30
```
vector.toml:
```toml
    data_dir = "/var/lib/vector"
    [api]
      enabled = true
    [sources.internal_metrics]
      type = "internal_metrics"
    [sinks.prometheus_exporter]
      type = "prometheus_exporter"
      inputs = ["internal_metrics"]
      address = "0.0.0.0:9598"
```

### Debug Output

```
 /usr/bin/vector -vvv -t "2" -c /etc/vector/*.toml
```
https://gist.github.com/mikhno-s/30d01c27bc57f9f02f879606b83d50ed

memory usage pattern:

![image](https://user-images.githubusercontent.com/13031076/111312966-7f931b00-8668-11eb-8def-8feb49d7cffa.png)

### Expected Behavior

vector should not consume a lot of memory, even when vector reads big log files from the start.

### Actual Behavior

- vector killed by OOM in 30s after start (3GB Limit)
- vector sends nothing to s3
- amount of ldb files in /var/lib/vector is increases 

### Additional Context

After cleaning up the log file `/var/log/envoy/ingress.log` and ldb files in data dir - it works. 
Looks like memory leak, when vector needs to read big file.
