### ISSUE TITLE
Cloudwatch metrics sink batches more than 150 values for a single MetricDatum object.

### ISSUE THREAD

**Issue by streeck** [vectordotdev/vector#6940]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Vector issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://chat.vector.dev.
-->

### Vector Version

From inside the docker image: `timberio/vector:0.12.1-alpine`
```
vector 0.12.1 (v0.12.1 x86_64-unknown-linux-musl 2021-03-12)
```

### Vector Configuration File

```toml
[sources.application_metrics]
  type = "statsd"
  address = "0.0.0.0:8125"
  mode = "udp"

[sinks.metrics_out]
  type = "aws_cloudwatch_metrics"
  inputs = ["application_metrics"]
  default_namespace = "namespace"
  region = "us-west-1"

  compression = "gzip"

  batch.max_events = 20
  batch.timeout_secs = 5
```

### Debug Output

Debug output ended up being way too verbose for this, I think the error message should suffice, let me know if that's not the case.

```
ERROR sink{component_kind="sink" component_name=metrics_out component_type=aws_cloudwatch_metrics}:request{request_id=21309}: vector::sinks::util::sink: Request failed. error=The collection MetricData.member.2.Values must not have a size greater than 150.
```

**Edit:** Debug output with relevant lines [here](https://gist.github.com/streeck/a7bdd742a14107ec1aaea43191028cc5).

### Expected Behavior

Vector should keep the batches of values for a single `MetricDatum` object under 150, as per Cloudwatch [docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html).

### Actual Behavior

It creates a list of values containing more than 150 values causing the request to fail and metrics being lost, since it's a non-retriable error.

### Additional Context

No additional context.

### References

No references at the moment.
