### ISSUE TITLE
Disconnected while requesting ApiVersion (Kafka)

### ISSUE THREAD

**Issue by celador** [vectordotdev/vector#7129]
### Vector Version

❯ vector --version
vector 0.12.2 (v0.12.2 x86_64-apple-darwin 2021-03-30)

### Vector Configuration File

```toml
[sources.in]
  type = "stdin"

[sinks.kafka_log]
  type = "kafka"
  inputs = ["in"]
  bootstrap_servers = "pkc-4yyd6.us-east1.gcp.confluent.cloud:9092"
  key_field = ""
  topic = "TEST"
  group_id = "vector"
  sasl.enabled = true
  sasl.mechanism = "PLAIN"
  sasl.password = "*"
  sasl.username = "*"
  security.protocol = "SASL_SSL"
  encoding.codec = "json" # required
```

### Debug Output

> echo 'Hello World!' | vector --config ./kafka.toml

```
Apr 14 17:20:39.627 ERROR rdkafka::client: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): sasl_plaintext://pkc-4yyd6.us-east1.gcp.confluent.cloud:9092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 38ms in state APIVERSION_QUERY)
```

### Expected Behavior

Message should be sent to Kafka

### Actual Behavior

Vector cannot connect to the Kafka Broker

### Example Data

Trying to run the following command to get a message into my test topic
`echo 'Hello World!' | vector --config ./kafka.tomlech`

### Additional Context

This is a default starter cluster from Confluent.  I have multiple services connecting to this cluster, both from my local machine and in some deployed containers.  I searched and there's a few pieces of code that mention Confluent, so I think it's a supported platform.  I talked with @jszwedko in the Discord channel, and they suggested I open an issue.
