### ISSUE TITLE
Allow map to be specified as input for unit tests

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7247]
Currently unit tests require flat key/value pairs for inserting data, like:

```toml
log_fields.message = "foo"
log_fields."kubernetes.container_id" = "foo"
```

However, for nested data, this is a bit tedious to flatten out all of the keys. It would be nice to support specifying a map like:

```toml
log_fields = { message = "foo", kubernetes = { container_id = "foo" } }
```

This advantage is even more apparent when using YAML (or JSON):

```yaml
log_fields:
  message: "foo"
  kubernetes:
    container_id: "foo"
```
