### ISSUE TITLE
Performance regression of kafka -> clickhouse in 0.13

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7348]
A [user in discord](https://discord.com/channels/742820443487993987/746070591097798688/839518431191891978) is seeing a roughly 50% decrease in throughput for their config which looks like:

```toml
log_schema.timestamp_key = "@timestamp"

#[api]
  #enabled = true

#[sinks.monitoring_exporter]

  #type = "prometheus_exporter"
  #inputs = ["internal_metrics_app"]
  #address = "0.0.0.0:9598"

#[sources.internal_metrics_app]
  #type = "internal_metrics"

#[sources.kafka_source]
  #type = "stdin"

[sources.kafka_source]
  type = "kafka"
  bootstrap_servers = "127.0.0.1:9092"
  group_id = "ch-test-10-consumer-group"
  topics = ["new_topic"]
  auto_offset_reset = "beginning"

[transforms.copy_original_message]
  type = "remap"
  inputs = ["kafka_source"]
  source = '''
  .original_message, err = to_string(.message)
  '''

[transforms.json_parser_app]
  type = "json_parser"
  inputs = ["copy_original_message"]
  drop_field = true
  drop_invalid = true
  field = "message"

[transforms.to_downcase_app]
  type = "remap"
  inputs = ["json_parser_app"]
  source = '''
  .component_type, err = downcase(.component_type)
  .log_type, err = downcase(.log_type)
  '''

[transforms.regex_component]
  type = "regex_parser"
  inputs = ["to_downcase_app"]
  drop_failed = true
  drop_field = false
  field = "component_type"
  patterns = ['^[\w]{3,}$']

[transforms.regex_log_type]
  type = "regex_parser"
  inputs = ["regex_component"]
  drop_failed = true
  drop_field = false
  field = "log_type"
  patterns = ['^[\w]{3,}$']

[transforms.clickhouse_event_preparation]
  type = "remap"
  inputs = ["regex_log_type"]
  source = '''
  .timestamp = format_timestamp!(now(), format: "%s")
  .timestamp_unix = format_timestamp!(now(), format: "%s")
  .log_source = .type
  if (!exists(.log_level)){
    if (exists(.level)){
      .log_level = .level
    } else {
      .log_level = "undefined"
    }
  }
  del(.tags)
  del(.headers)
  flatten(.)
  '''

#[sinks.output_clickhouse]
  #inputs = ["clickhouse_event_preparation"]
  #type = "blackhole"
  #encoding.codec = "json"

[sinks.output_clickhouse]
  inputs = ["clickhouse_event_preparation"]
  type = "clickhouse"
  compression = "gzip"
  database = "elk_logs"
  endpoint = "http://localhost:8123" # required
  table = "unified_logs"

  batch.max_bytes = 1049000
  batch.timeout_secs = 5

  #buffer.max_events = 5000000 # optional, default, events, relevant when type = "memory"
  #buffer.max_size = 104900000000 # required, bytes, required when type = "disk"
  #buffer.type = "memory"
  #buffer.when_full = "block"

  encoding.only_fields = ["timestamp", "timestamp_unix", "component_type", "log_type", "log_level", "log_source", "original_message"]
  encoding.timestamp_format = "rfc3339" # optional, default | "unix" as an alternative

  healthcheck.enabled = true
```

0.12.2:

<img width="1700" alt="Screenshot_2021-05-05_at_17 57 18" src="https://user-images.githubusercontent.com/316880/117179986-b7355e00-ada1-11eb-9b1a-a43ece4411f1.png">

0.13.1:

<img width="1702" alt="Screenshot_2021-05-05_at_18 02 10" src="https://user-images.githubusercontent.com/316880/117180053-c4524d00-ada1-11eb-9941-041a196162c7.png">

I tried to reproduce locally following the same process in https://github.com/timberio/vector/issues/7258#issue-869177095, running both kafka and clickhouse locally.

However, my throughput numbers looked roughly the same for both versions: around ~5k/s.

I think we could add this to the https://github.com/timberio/vector-test-harness as a test case to try it in a more "real world" setup.
