### ISSUE TITLE
Unrecognized Literal Hostname in bootstrap_servers

### ISSUE THREAD

**Issue by ccarcaci** [vectordotdev/vector#7376]
### Vector Version
I'm using the official dockerhub image: https://hub.docker.com/layers/timberio/vector/0.13.X-alpine/images/sha256-d686fa29ab6bd6c5990d9546ae030cdb215cb39ec3aae13d90dc170a1038fcf6?context=explore

```
/ # vector --version
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-musl 2021-04-29)
```

### Vector Configuration File
```toml
[sources.dummy_log_files]
  type = "file"
  include = ["/var/log/**/*.log"]
  read_from = "end"

[sinks.to_kafka]
  type = "kafka"
  inputs = ["dummy_log_files"]
  bootstrap_servers = "kafka:9092"
  key_field = "dummy_logs"
  topic = "dummies"
  encoding.codec = "json"
```

### Debug Output
Debug output: https://gist.github.com/ccarcaci/125ade33de4406dea9f107b62da36b68

### Expected Behavior
Vector is expected to connect to ```kafka:9092```.

Ping command to ```kafka``` hostname from within vector.dev running container is:
```
GISULCL5WHTD8:configs-speeder-edge carcacx$ shell vector
/ # ping kafka
PING kafka (192.168.0.3): 56 data bytes
64 bytes from 192.168.0.3: seq=0 ttl=64 time=0.144 ms
64 bytes from 192.168.0.3: seq=1 ttl=64 time=0.318 ms
64 bytes from 192.168.0.3: seq=2 ttl=64 time=0.128 ms
^C
--- kafka ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.128/0.196/0.318 ms
```

### Actual Behavior
Vector is trying to connect to ```localhost:9092```.
