### ISSUE TITLE
vector panics if you attempt to use a sink as an input to another sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7444]
Reported by [user in discord](https://discord.com/channels/742820443487993987/746070591097798688/842393165578764289)

```
vector 0.13.0 (v0.13.0 x86_64-apple-darwin 2021-04-21)
```

I was able to reproduce this with:

```
sources:
  my_source_id:
    type: stdin
sinks:
  to_vector:
    type: vector
    inputs:
      - my_source_id
    address: "http://localhost:8080"
  hello:
    type: vector
    inputs:
      - to_vector
    address: "http://localhost:8080"
```

```
➜  stdlib git:(master) RUST_BACKTRACE=1 vector --config /tmp/tmp.yaml
May 13 09:47:54.837  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info"
May 13 09:47:54.837  INFO vector::app: Loading configs. path=[("/tmp/tmp.yaml", None)]
thread 'main' panicked at 'internal error: entered unreachable code', src/config/validation.rs:238:74
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: vector::config::compiler::compile
   4: vector::config::loading::load_from_paths
   5: vector::app::Application::prepare_from_opts::{{closure}}
   6: vector::app::Application::prepare_from_opts
   7: vector::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
