### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by alpiua** [vectordotdev/vector#7525]
In my situation, Vector is filtering up to 1000 messages per second with regexp filter.
In some cases, it leads to huge memory consumption and holding memory even after load is over, in idle state.
If I reload vector service, it will back to normal ~0,5-1% of memory usage

```
vector 0.13.0 (v0.13.0 x86_64-unknown-linux-gnu 2021-04-21)
```

### Vector Configuration File

<!--
Paste the relevant parts of your `vector.toml` configuration between the ``` marks below.

!! If your config files contain sensitive information please remove it !!
-->

```toml
[api]                                                                                                                                                                                                                                                                                       
  enabled = true                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
[sources.journal]                                                                                                                                                                                                                                                                           
  type = "journald"                                                                                                                                                                                                                                                                         
  exclude_units = ["kernel","vector","telegraf","chronyd","crond","init.scope","dnf-makecache.service","rsyslog"]                                                                                                                                                                           
                                                                                                                                                                                                                                                                                            
[sources.app_std]                                                                                                                                                                                                                                                                         
  type = "file"                                                                                                                                                                                                                                                                             
  include = ["/opt/app/*/logs/stdout.log"]                                                                                                                                                                                                                                           
  fingerprint.strategy = "device_and_inode"                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                            
  [sources.app_std.multiline]                                                                                                                                                                                                                                                             
    start_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'                                                                                                                                                                                                                                           
     mode = "halt_before"                                                                                                                                                                                                                                                                   
     condition_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'                                                                                                                                                                                                                                      
     timeout_ms = 999999999                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                            
[sources.app]                                                                                                                                                                                                                                                                             
  type = "file"                                                                                                                                                                                                                                                                             
  include = ["/opt/app/*/logs/*/*.log"]                                                                                                                                                                                                                                              
  fingerprint.strategy = "device_and_inode"                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                            
  [sources.app.multiline]                                                                                                                                                                                                                                                                 
     start_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'                                                                                                                                                                                                                                          
     mode = "halt_before"                                                                                                                                                                                                                                                                   
     condition_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'                                                                                                                                                                                                                                      
     timeout_ms = 999999999                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
[transforms.app_filter]                                                                                                                                                                                                                                                                   
  type = "filter"                                                                                                                                                                                                                                                                           
  inputs = ["app"]                                                                                                                                                                                                                                                                        
  condition.type = "check_fields"                                                                                                                                                                                                                                                           
  condition."message.not_contains" = "NOT_FOUND - no exchange"                                                                                                                                                                                                                              
  condition."message.not_regex" = " (INFO|DEBUG|TRACE) "                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
[sinks.app_prod]                                                                                                                                                                                                                                                                          
  type = "vector"                                                                                                                                                                                                                                                                           
  inputs = ["app_filter","app_std"]                                                                                                                                                                                                                                                     
  address = "server:5001"                                                                                                                                                                                                                                                    
  healthcheck = true                                                                                                                                                                                                                                                                        
#  buffer.max_size = 10100000                                                                                                                                                                                                                                                               
#  buffer.type = "disk"                                                                                                                                                                                                                                                                     
#  buffer.when_full = "block"                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                            
[sinks.system]                                                                                                                                                                                                                                                                              
  type = "vector"                                                                                                                                                                                                                                                                           
  inputs = ["journal"]                                                                                                                                                                                                                                                                      
  address = "server:5000"                                                                                                                                                                                                                                                    
  healthcheck = true                                                                                                                                                                                                                                                                        
#  buffer.max_size = 10100000                                                                                                                                                                                                                                                               
#  buffer.type = "disk"                                                                                                                                                                                                                                                                     
#  buffer.when_full = "block"
```
### Expected Behavior

Vector releasing memory 

### Actual Behavior

Consuming resources in idle state

![image](https://user-images.githubusercontent.com/14225967/118947329-e500d200-b95f-11eb-8812-c464fcd55ed2.png)


### Example Data

For now I leave this instance untouched and can try to provide an additional info with your request, while vector holding the memory.


### References

- #7246 
- #7159
