### ISSUE TITLE
Add acknowledgement support to `fluent` source

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7533]
As part of #419 we are adding a `fluent` source, but chose not to include Fluent's acknowledgement support in the initial implementation due to the additional work it will require. This issue represents that work.

Please leave a 👍 or comment below if you would find this support useful.

**Comment by zamazan4ik** [comment]
@jszwedko could you please rename the issue? From "sink" to "source" :)

**Comment by jszwedko** [comment]
> @jszwedko could you please rename the issue? From "sink" to "source" :)

Done. Thanks for the prompt!

**Comment by zamazan4ik** [comment]
Thanks for the fix!

However, I found these lines of code in the `fluent` source: https://github.com/vectordotdev/vector/blob/master/src/sources/fluent/mod.rs#L529

Does it implement some kind of ack-ing for `fluent`? According to the [PR](https://github.com/vectordotdev/vector/pull/10176)  - acknowledgment support is already implemented.

In the local Vector-related Telegram chat I found a user with a problem with the current ACK implementation.

**Comment by stanislavdip** [comment]
@zamazan4ik @jszwedko 
Hello. Yes, I have some problems.
 I using Vector as an aggregator and fluent-bit as a log collector, but in fluent-bit logs, I see errors like this:

```
[error] [engine] chunk '96-1683047707.895527211.flb' cannot be retried: task_id=0, input=tail.0 > output=forward.0
[error] [output:forward:forward.0] ACK response not MAP (type:2)

```
Vector deployed via Helm chart version: 0.20.1 with these options:
```
customconfig:   
  acknowledgements:
      enabled: true
image:
  tag: "0.29.1-distroless-libc"
```

Vector configuration is:
```
vector:
  address: 0.0.0.0:9000
  type: fluent
  receive_buffer_bytes: 1048576
  connection_limit: 2000
  keepalive:
     time_secs: 30
```

fluent-operator deployed via Helm chart 2.2.0, also tried 2.1.0
```
fluent-bit:
  image:      
    repository: "kubesphere/fluent-bit"
    tag: "v2.0.11"
  forward:    
    host: vector.fluent.svc    
    port: 9000    
    requireAckResponse: true
```
If you need more details, I can provide it.
Thank you
