### ISSUE TITLE
data_dir not writeable should be a fatal error. 

### ISSUE THREAD

**Issue by rrichardson** [vectordotdev/vector#7547]
### Vector Configuration File

```toml
[sources.journald]
type = "journald"

[sinks.processor]
type = "socket"
inputs = ["journald"]
mode = "tcp"
address = "processor.mydomain:4000"
encoding.codec = "json"
healthcheck.enabled = true
```

### Debug Output

```
May 18 19:42:54 myhost vector[951]: May 18 19:42:54.050 ERROR journald-server: vector::sources::journald: Unable to open checkpoint file. path="/var/lib/vector/journald/checkpoint.txt" error=Permission denied (os error 13)
```

### Expected Behavior
Instead of just printing an error that it is going to fail to do its primary job, the entire process should abort. 

### Actual Behavior

Vector logged the above error, then continued operating, though not actually doing anything, because the journald source failed. 

### Example Data

Startup in a system where `/var/lib/vector` or `/var/lib/vector/journald` is not writable. 

### Additional Context

This probably only effects components that need to checkpoint or use on-disk working memory.  However, for those components, failing to write to the directory means that those streams will likely fail.  
It might be a bit tricky, considering a vector which uses a config which doesn't require the data_dir shouldn't care if the data_dir isn't writeable.  However, if the config contains something like `journald` then its critical that it succeed, (or fail very loudly)
