### ISSUE TITLE
(sink) Splunk HEC Sink fails to send any other field than message when using the text encoding

### ISSUE THREAD

**Issue by jerome-kleinen-kbc-be** [vectordotdev/vector#7613]
### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
```

### Vector Configuration File

```toml
[sources.in]
  type = "generator"
  format = "syslog"
  
[transforms.remap]
  type = "remap"
  inputs = ["in"]
  source = '.msg = .message'

[sinks.splunk]
  type = "splunk_hec"
  inputs = ["remap"]
  compression = "none"
  endpoint = "${SPLUNK_HEC_ENDPOINT}"
  host_key = "host"
  index = "testindex"
  sourcetype = "test"
  token = "${SPLUNK_HEC_TOKEN}"

  # Encoding
  encoding.codec = "text"
  encoding.only_fields = ["msg"]

  # Healthcheck
  healthcheck.enabled = true  
```

### Expected Behavior

vector takes the value of the `msg` field and puts it in the `event` key of the json body to send to Splunk

### Actual Behavior

vector seems to be sending empty events, leading to the following error:

```
ERROR sink{component_kind="sink" component_name=splunk component_type=splunk_hec}:request{request_id=11}: vector::sinks::util::sink: Response wasn't successful. response=Response { status: 400, version: HTTP/1.1, headers: {"date": "Thu, 27 May 2021 08:21:49 GMT", "content-type": "application/json; charset=UTF-8", "x-content-type-options": "nosniff", "content-length": "73", "vary": "Authorization", "connection": "Keep-Alive", "x-frame-options": "SAMEORIGIN", "server": "Splunkd"}, body: b"{\"text\":\"Event field cannot be blank\",\"code\":13,\"invalid-event-number\":0}" }
```

To make matters worse, when I am starting from the kafka source the behavior seems to be different. In this case vector seems to be sending _something_ and therefore does not throw any errors. Splunk responds with a http 200 status code and shows no errors whatsoever in the monitoring console, and it even says it is receiving valid requests and events. In reality, no data is being indexed. However, on kafka side, the consumer offsets are being confirmed, because from vector's point of view everything was sent correctly. Of course this latter part seems to be an issue on Splunk side that I will chase separately.

### Additional Context

I am guessing this has to do with https://github.com/timberio/vector/blob/master/src/sinks/splunk_hec.rs#L206 in the sense that after applying the encoding option of `only_fields` the event is stripped from all fields except the ones you mention in this configuration option, but the `message_key()` is not reflecting this and it still returns `"message"`. As a consequence, the only field name you can actually use in combination with `only_fields` seems to be "message".
