### ISSUE TITLE
parse_logfmt parse empty fields incorrectly

### ISSUE THREAD

**Issue by joulaud** [vectordotdev/vector#7634]
### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
```

### Vector Configuration File
```yaml
---
transforms:
  main_transform:
    type: remap
    inputs:
    - main_filter
    source: |
      .parsed = parse_logfmt(.message) ?? {}

tests:
- name: empty_logfmt
  inputs:
  - insert_at: main_transform
    type: log
    log_fields:
      message: level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0
       desiredPolicyRevision=0 endpointID=1 identity=1 ipv4= ipv6=
       subsys=endpoint
  outputs:
  - extract_from: main_transform
    conditions:
    - .parsed.level                  == "info"
    - .parsed.msg                    == "Waiting for endpoint to be generated"
    - .parsed.containerID            == ""
    - .parsed.datapathPolicyRevision == "0"
    - .parsed.desiredPolicyRevision  == "0"
    - .parsed.endpointID             == "1"
    - .parsed.identity               == "1"
    - .parsed.ipv4                   == ""
    - .parsed.ipv6                   == ""
    - .parsed.subsys                 == "endpoint"
```

### Expected Behavior

`parse_logfmt` correctly detects empty values and generate fields containing empty strings and in this case the test above should pass.

### Actual Behavior

`parse_logfmt` don't parse correctly the empty values and conflates them with the next entry.

```
$ vector test reproduce_empy_logfmt.yml
Running tests
test empty_logfmt ... failed

failures:

test empty_logfmt:

check transform 'main_transform' failed conditions:
  condition[2]: source execution resolved to false
  condition[3]: source execution resolved to false
  condition[7]: source execution resolved to false
  condition[8]: source execution resolved to false
payloads (events encoded as JSON):
   input: {"message":"level=info msg=\"Waiting for endpoint to be generated\" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1 identity=1 ipv4= ipv6= subsys=endpoint","timestamp":"2021-05-28T14:44:54.128179170Z"}
  output: {"message":"level=info msg=\"Waiting for endpoint to be generated\" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1 identity=1 ipv4= ipv6= subsys=endpoint","parsed":{"containerID":"datapathPolicyRevision=0","desiredPolicyRevision":"0","endpointID":"1","identity":"1","ipv4":"ipv6=","level":"info","msg":"Waiting for endpoint to be generated","subsys":"endpoint"},"timestamp":"2021-05-28T14:44:54.128179170Z"}
```
