### ISSUE TITLE
`vector tap` doesn't receive the ctrl-c events

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7757]
### Vector Version

```
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector Configuration File

```toml
# Random Syslog-formatted logs
[sources.dummy_logs]
type = "generator"
format = "syslog"
interval = 1

# Parse Syslog logs
# See the Vector Remap Language reference for more info: https://vrl.dev
[transforms.parse_logs]
type = "remap"
inputs = ["dummy_logs"]
source = '''
. = parse_syslog!(string!(.message))
'''

# Print parsed logs to stdout
[sinks.print]
type = "console"
inputs = ["parse_logs"]
encoding.codec = "json"

# Vector's GraphQL API (disabled by default)
# Uncomment to try it out with the `vector top` command or
# in your browser at http://localhost:8686
[api]
enabled = true
address = "127.0.0.1:8686"
```

### Expected Behavior

When running `vector tap` via `docker exec` into a running vector container, using CTRL-C should stop the process.

### Actual Behavior

`vector tap` does not appear to receive signals.

### Reproduce

- ` docker run -it --name vector -v /tmp/vector.toml:/etc/vector/vector.toml  timberio/vector:0.14.X-debian`
- `docker exec -it vector vector tap`
- Observe events
- Type ctrl-c
- Observe that the process does not quit

**Comment by jszwedko** [comment]
This looks like it might not be limited to docker. I saw the same behavior locally on OSX where `ctrl-c` wouldn't stop it.

**Comment by spencergilbert** [comment]
A user also reproduced running on ec2

**Comment by leebenson** [comment]
> I saw the same behavior locally on OSX where ctrl-c wouldn't stop it.

Interesting. I can't repro. on macOS locally. Is it under certain conditions? Or all the time?

In any case, I think a general solution could be to utilise `&signal_handler` in the subcommand handling block, which executes (and returns) before the topology handling loop.

**Comment by jszwedko** [comment]
For me, it is all the time locally on OSX (Catalina) using this config:

```toml
[api]
enabled = true

[sources.in]
type = "stdin"

[transforms.split]
type                      = "route"
inputs                    = ["in"]
route.event_metric        = 'exists(.name) && (exists(.counter) || exists(.gauge))'
route.event_log           = 'exists(.message) || exists(.logEvents)'
route.event_unknown       = '!(exists(.message) || exists(.logEvents) || exists(.counter) || exists(.gauge))'

[sinks.out]
type = "console"
inputs = ["split.event_log"]
encoding.codec = "json"

[sources.metrics]
type = "internal_metrics"

[sinks.prometheus]
inputs = ["metrics"]
type = "prometheus"
address = "0.0.0.0:19999"
```
