### ISSUE TITLE
[UnitTest] Tests with `no_outputs_from` and a non-existent transform should not pass

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#7821]
### Vector Version

```
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Bug Description

Consider the following (incomplete to run but complete to test) Vector configuration:
```yaml
transforms:
  my-transform:
    type: remap
    inputs:
      - no-source
    source: |-
      .message = "hello"

tests:
  - name: expected-output
    inputs:
      - insert_at: my-transform
        type: log
        log_fields: {}
    outputs:
      - extract_from: my-transform
        conditions:
          - .message == "hello"
  - name: no-output
    inputs:
      - insert_at: my-transform
        type: log
        log_fields: {}
    no_outputs_from:
      - non-existent
```

Note the following points about the above configuration:
* There are no `sources` or `sinks` defined. This configuration is not valid to run, but still can be used to run unit tests.
* The second unit test `no-output` declares that it expects no output from a `non-existent` stage (which does not exist).

Now consider the following workflows:
```
$ vector validate test.yaml
Failed to load ["test.yaml"]
----------------------------
x No sources defined in the config.
x No sinks defined in the config.
x Input "no-source" for transform "my-transform" doesn't exist.
```
What we expected to see in this workflow?
* There should be at least a warning that a unit test is trying to interact with a transform that does not exist.

```
$ vector test test.yaml
Running tests
test expected-output ... passed
test no-output ... passed
```
What we expected to see in this workflow?
* The second test `no-output` should have not passed as there is no `non-existent` transform defined.

While the first expectancy is rather "soft" (informative), we think that the second one is quite important because the passing test is misleading us to think that the `no-output` test is correct when in fact is not testing what we wanted.

We got into this issue recently when we refactored one of our Vector configurations and forgot to rename the transform down in the unit tests section. Because the test with `no_outputs_from` is still passing, we never noticed it was using the wrong transform name as input.

It can be argued that passing a test when `no_outputs_from` a non-existent transform is correct (because a non-existent transform in fact produces no output), however we believe that it can lead to unnoticed mistakes in tests too :(
