### ISSUE TITLE
Yaml documentation examples should use yaml multiline strings

### ISSUE THREAD

**Issue by apollo13** [vectordotdev/vector#7906]
To increase the readability of https://vector.dev/docs/reference/configuration/transforms/remap/
```
---
transforms:
  my_transform_id:
    type: remap
    inputs:
    - my-source-or-transform-id
    - prefix-*
    source: "  . = parse_json!(.message)\n  .new_field = \"new value\"\n  .status
      = to_int!(.status)\n  .duration = parse_duration!(.duration, \"s\")\n  .new_name
      = del(.old_name)\n  "
```

it would be great if the example could get reformatted to say:
```
---
transforms:
  my_transform_id:
    type: remap
    inputs:
    - my-source-or-transform-id
    - prefix-*
    source: |
      . = parse_json!(.message)
      .new_field = "new value"
      .status = to_int!(.status)
      .duration = parse_duration!(.duration, "s")
     .new_name = del(.old_name)
```
I am not sure how flexible the doc system is, and whether that needs to be done on a case per case basis or could be done generally for strings containing a newline
