### ISSUE TITLE
Sink from several sources not working with disk buffer enabled.

### ISSUE THREAD

**Issue by alpiua** [vectordotdev/vector#7942]
### Vector Version
`vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)`

### Vector Configuration File
```toml
[sources.app_log_std]
  type = "file"
  include = ["/opt/app/test/*/logs/std*.log"]
  fingerprint.strategy = "device_and_inode"

  [sources.app_log_std.multiline]
     start_pattern = '^[^\s]'
     mode = "continue_through"
     condition_pattern = '(?m)^[\s].*$|(?m)^Caused.+$|(?m)^\}.*$'
     timeout_ms = 1000000000

[sources.app_log_common]
  type = "file"
  include = ["/opt/app/test/*/logs/*/*.log"]

  [sources.app_log_common.multiline]
     start_pattern = '^[^\s]'
     mode = "continue_through"
     condition_pattern = '(?m)^[\s].*$|(?m)^Caused.+$|(?m)^\}.*$'
     timeout_ms = 1000000000

[transforms.app_parse_common]
   type = "remap"
   inputs = ["app_log_common"]
   source = '''
      . |= parse_regex!(.message,r'^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) (?P<level>\w+) (?s)(?P<message>.*$)')
      .timestamp = parse_timestamp(.timestamp,"%Y-%m-%d %H:%M:%S.%3f") ?? now()

      path_segments, err = split(.file, "/")
      .app_name = path_segments[4]
      .source = "common logs"
   '''
[transforms.app_parse_std]
   type = "remap"
   inputs = ["app_log_std"]
   source = '''
      . |= parse_regex!(.message,r'^(?P<time>\d{2}:\d{2}:\d{2},\d{3}) \|-(?P<level>\w+) (?s)(?P<message>.*$)')
      path_segments, err = split(.file, "/")
      .app_name = path_segments[4]
      .source = "std logs"
   '''

[sinks.test]
  type = "vector"
  inputs = ["app_parse_std", "app_parse_common"]
  address = "server:5000"
  healthcheck = true
  buffer.max_size = 10100000
  buffer.type = "disk"
  buffer.when_full = "block"
```

### Debug Output
This is just a part of the output showing that Vector is not trying to send anything to the sink. 
No errors during the startup.

> Jun 19 22:28:36.205 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app1/logs/stdout.log" bytes=97                                                                                            Jun 19 22:28:36.205 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app1/logs/stdout.log" bytes=99                                                                                            Jun 19 22:28:36.205 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app1/logs/stdout.log" bytes=108                                                                                           Jun 19 22:28:36.205 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app1/logs/stdout.log" bytes=84                                                                                            Jun 19 22:28:36.208 TRACE source{component_kind="source" component_name=app_log_std component_type=file}: vector::internal_events::file::source: Receiv
> ed one event. file=/opt/app/test/app-app3/logs/stdout.log byte_size=73                                                                                 Jun 19 22:28:36.208 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app3/logs/stdout.log" bytes=87                                                                                            Jun 19 22:28:36.208 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app4/logs/stdout.log" bytes=87                                                                                          Jun 19 22:28:36.208 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app1/logs/stdout.log" bytes=87                                                                                            Jun 19 22:28:36.208 TRACE source{component_kind="source" component_name=app_log_std component_type=file}: vector::internal_events::file::source: Receiv
> ed one event. file=/opt/app/test/app-app3/logs/stdout.log byte_size=33                                                                                 Jun 19 22:28:36.208 DEBUG sink{component_kind="sink" component_name=test4 component_type=vector}: vector::internal_events::tapp1: Connected. peer_addr=
> 172.27.5.138:5004                                                                                                                                      Jun 19 22:28:36.208 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app3/logs/stdout.log" bytes=73                                                                                            Jun 19 22:28:36.208 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app3/logs/stdout.log" bytes=33                                                                                            Jun 19 22:28:36.208 DEBUG sink{component_kind="sink" component_name=test4 component_type=vector}: vector::utilization: utilization=0.4577723448276073
> Jun 19 22:28:36.208 TRACE source{component_kind="source" component_name=app_log_std component_type=file}:file_server: file_source::file_server: Read by
> tes. path="/opt/app/test/app-app3/logs/stdout.log" bytes=249    

### Expected Behavior
Vector sending events from both sources to sink 'test' with buffer enabled

### Actual Behavior
Vector is not sending events to sink 'test' when buffer is enabled and sending with disabled buffer

**Comment by jszwedko** [comment]
Hi @alpi-ua !

Would you be able to provide some example logs that match the multiline and parsing config you have here? I tested with a simplified config:

```toml
data_dir = "/tmp/vector2/"

[sources.app_log_std]
  type = "file"
  include = ["/tmp/a/*.log"]
  fingerprint.strategy = "device_and_inode"

[sources.app_log_common]
  type = "file"
  include = ["/tmp/b/*.log"]

[sinks.test]
  type = "vector"
  inputs = ["app_log_*"]
  address = "localhost:5000"
  healthcheck = true
  buffer.max_size = 10100000
  buffer.type = "disk"
  buffer.when_full = "block"
```

But wasn't able to reproduce (the logs are sent through fine).

Looking at your debug logs, it does seem like the source is emitting events and I don't see any errors indicating events are being dropped (though maybe those appear later?).

Would it be possible to add the following to the config?

```toml
[sources.metrics]
type = "internal_metrics"

[sinks.out]
type = "console"
inputs = ["metrics"]
encoding.codec = "json"
```

And copy the reported internal metrics here? It will report them on an interval. That should help narrow down where events are being held up.
