### ISSUE TITLE
prometheus_remote_write healthcheck fails with 405

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#7998]
## Log
```
Jun 22 20:18:58.714 ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Unexpected status: 405 Method Not Allowed component_kind="sink" component_type="prometheus_remote_write" component_name="remote_write"
```

## Config
```toml
[sources.host_metrics]
  type = "host_metrics"

[transforms.remap]
  type = "remap"
  inputs = ["host_metrics"]
  source = '''
  .tags.stack_id = "GitLabInfra"
  .tags.account_id = "63000000000"
  .tags.instance_id = "i-0ffa18535aaaaaaaa"
  '''

[sinks.remote_write]
  type = "prometheus_remote_write"
  inputs = ["remap"]
  endpoint = "http://localhost:8087/"
```
```toml
[sources.remote_write]
  type = "prometheus_remote_write"
  acknowledgements = false
  address = "0.0.0.0:8087"

[sinks.out]
  type = "console"
  inputs = ["remote_write"]
  encoding.codec = "text"
```

**Comment by hhromic** [comment]
Just stumbled upon the same issue on my side (using a sink):
```
Jul 02 02:36:56.939 DEBUG http: vector::internal_events::http_client: HTTP response. status=405 Method Not Allowed version=HTTP/1.1 headers={"allow": "OPTIONS, POST", "content-type": "text/plain; charset=utf-8", "x-content-type-options": "nosniff", "date": "Fri, 02 Jul 2021 02:36:56 GMT", "content-length": "19"} body=[19 bytes]
Jul 02 02:36:56.939 ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Unexpected status: 405 Method Not Allowed component_kind="sink" component_type="prometheus_remote_write" component_name="prometheus"
```

Note that I'm testing with a real Prometheus server started like this:
```
docker run --rm -p 9090:9090 \
  prom/prometheus:v2.28.0 \
    --config.file=/etc/prometheus/prometheus.yml \
    --storage.tsdb.path=/prometheus \
    --web.console.libraries=/usr/share/prometheus/console_libraries \
    --web.console.templates=/usr/share/prometheus/consoles \
    --enable-feature=remote-write-receiver
```

The `vector.yaml` configuration I'm using for testing (using Docker Desktop for Windows):
```yaml
sources:
  metrics:
    type: internal_metrics

sinks:
  prometheus:
    type: prometheus_remote_write
    inputs:
      - metrics
    endpoint: http://host.docker.internal:9090/api/v1/write
```

Note that despite the healthcheck failing, the metrics seems to be being sent no problem anyway.
