### ISSUE TITLE
Memory leak when merge is used

### ISSUE THREAD

**Issue by mr-karan** [vectordotdev/vector#8004]
### Vector Version

```
$ vector -V  
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector Configuration File

```toml
[sources.logstash_logs]
type = "http"
address = "0.0.0.0:1234"
encoding = "json"

# Route logs for parsing based on tags.
[transforms.parse_routes]
type = "route"
inputs = ["logstash_logs"]
route."http_logs" = 'includes!(.tags, "http_logs")==true'

[transforms.format_http_logs]
type = "remap" 
inputs = ["parse_routes.http_logs"] 
source = '''

# Store logstash metadata.
meta._hostname = .host."name"
meta._host_ip = .beat."hostname"
meta._source = .source

# Parse all the extra query params in the HTTP body and merge with
# above metadata.
http_extra_params = parse_query_string!(.http_extra_params)
params = merge(http_extra_params,meta)
http_body = encode_json(params)

# Prepare the full event payload.
. = {
    "http_body": http_body,
}
'''

[sinks.blackhole]
type = "blackhole"
inputs = ["format_http_logs"]
```

### Expected Behavior

No memory leak should happen.

### Actual Behavior

Memory leak happens as seen in the below graph

![image](https://user-images.githubusercontent.com/5689132/123136365-7a681800-d470-11eb-8c4b-a263133e9232.png)

### Additional Context

I split the config into different parts and after eliminating each part of the config, I found the memory leak happens because of:

```
params = merge(http_extra_params,meta)
```

![image](https://user-images.githubusercontent.com/5689132/123136697-d92d9180-d470-11eb-910b-c37ccd9bae29.png)

If I don't have this `merge`, there's no memory leak. In the above graph:

1: Added `merge()`
2:  Removed `merge()`

As soon as this `merge` is introduced, memory starts to leak.

- Baseline when I just have the `input.http` and `sink.blackhole` is ~700MB.
- When I add the above transformation without `merge` it hovers around ~700-900MB.
- When I add `merge(http_extra_params,meta)` memory keeps on increasing until OOM killed.

- So far it looks like `.params = merge(http_extra_params,meta)` and `.params = {"http_extra_params": http_extra_params, "meta": .meta}` both are culprits for increasing memory. So this in fact could be something to do with the payload? There's a `parse_query_string` in the above line which might be involved in this too.

- Interestingly `del(.params)` didn't have an effect on reducing the memory.

Happy to provide additional details if required.
