### ISSUE TITLE
`default_namespace` not working for `datadog_metrics` sink

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#8056]
It appears the `default_namespace` field doesn't work for the `datadog_metrics` sink.

I tried the following config, that didn't produce the expected results:

```toml
[sources.internal_metrics]
  type = "internal_metrics"

[sinks.datadog]
  type = "datadog_metrics"
  inputs = ["internal_metrics"]
  api_key = "..."
  default_namespace = "test"
```

Doing this did not actually change the metric keys to include the provided namespace. Instead, I had to use the `remap` transform to set the correct namespace:

```toml
[sources.internal_metrics]
  type = "internal_metrics"

[transforms.namespace]
  type = "remap"
  inputs = ["internal_metrics"]
  source = '.namespace = "test"'

[sinks.datadog]
  type = "datadog_metrics"
  inputs = ["namespace"]
  api_key = "..."
```

@prognant mentioned he also ran into this issue before.
