### ISSUE TITLE
Prometheus metric data contains the constant trailing value 1624890168363 

### ISSUE THREAD

**Issue by xgcssch** [vectordotdev/vector#8057]
### Vector Version
```
vector 0.14.0 (x86_64-pc-windows-msvc 5f3a319 2021-06-03)
```
Same behavior in 0.13.1 and 0.12.2
### Vector Configuration File

```toml
[sources.smac_prometheus]
  type = "prometheus"
  endpoints = ["http://127.0.0.1:9091/metrics" ]
  scrape_interval_secs = 60

[sinks.smac_prometheus_exporter]
  type = "prometheus_exporter"
  address = "0.0.0.0:9999"
  inputs = ["smac_prometheus"]
```

### Expected Behavior
The exposed metric data lines should not contain any trailing data.

### Observed Behavior 
The metrics exposed by vector contains a constant trailing value 1624890168363 in every data line:

```
curl http://127.0.0.1:9999/metrics
# HELP worker_thread_total worker_thread_total
# TYPE worker_thread_total gauge
worker_thread_total{state="active"} 0 1624890168363
worker_thread_total{state="busy"} 0 1624890168363
worker_thread_total{configured="minimum"} 1 1624890168363
worker_thread_total{configured="maximum"} 30 1624890168363
...
```
The original metric data endpoint gives the correct data:
```
curl http://127.0.0.1:9091/metrics
# HELP worker_thread_total Number of worker threads
# TYPE worker_thread_total gauge
worker_thread_total{state="active"} 0.00000000000000000
worker_thread_total{state="busy"} 0.00000000000000000
worker_thread_total{configured="minimum"} 1.00000000000000000
worker_thread_total{configured="maximum"} 30.00000000000000000
...
```
Best regards
Soenke
