### ISSUE TITLE
docs: unit tests example doesn't work

### ISSUE THREAD

**Issue by mr-karan** [vectordotdev/vector#8104]
### Vector Version

```
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector Configuration File

```toml
[sources.logs]
type = "journald"

[[tests]]
  # Inputs
  [[tests.inputs]]
    insert_at = "foo" # required
    type = "raw" # required
    value = "some message contents" # required, required when type = "raw"

  # General
  name = "foo test" # required

  # Outputs
  [[tests.outputs]]
    # Conditions
    conditions.type = "check_fields" # optional, default
    conditions."message.eq" = "this is the content to match against" # example
    conditions."message.eq" = ["match this", "or this"] # example
    conditions."message.contains" = "foo" # example
    conditions."message.contains" = ["foo", "bar"] # example
    conditions."environment.ends_with" = "-staging" # example
    conditions."environment.ends_with" = ["-staging", "-running"] # example
    conditions."message.regex" = " (any|of|these|five|words) " # example
    conditions."environment.starts_with" = "staging-" # example
    conditions."environment.starts_with" = ["staging-", "running-"] # example

    # General
    extract_from = "foo" # required
```

### Debug Output

```
Running tests
Jul 01 19:13:12.616 ERROR vector::unit_test: Failed to execute tests:
unknown field `name`, expected one of `insert_at`, `type`, `value`, `log_fields`, `metric` for key `tests.inputs` at line 228 column 3.
```

### Expected Behavior

Tests should run

### Actual Behavior

The above error message

### Additional Context

This is an example from the docs that I copied as is: https://vector.dev/docs/reference/configuration/tests/
