### ISSUE TITLE
Unit testing metrics fails

### ISSUE THREAD

**Issue by stribb** [vectordotdev/vector#8105]
### Vector Version

0.14.0-alpine Docker image:

```
vector 0.14.0 (x86_64-unknown-linux-musl 5f3a319 2021-06-03)
```

### Vector Configuration File
```toml
data_dir = "/var/lib/vector"

[healthchecks]
  require_healthy = true

[api]
  enabled = true
  address = "127.0.0.1:8686"
  playground = true

[log_schema]
  host_key = "host"
  message_key = "message"
  source_type_key = "source_type"
  timestamp_key = "timestamp"


#### Logs

# Log messages created by Vector itself.
[sources.internal_logs]
  type = "internal_logs"

[transforms.noop]
  type="remap"
  inputs = ["internal_logs"]
  source = '.'

#### Metrics

# Emit internal Vector metrics.
[sources.internal_metrics]
  type = "internal_metrics"

[transforms.ooo_filter]
  type = "filter"
  inputs = ["internal_logs"]
  condition = "match!(.msg, r'out-of-order')"

[transforms.ooo_counter]
  type = "log_to_metric"
  inputs = ["ooo_filter"]
  metrics = [
    {type = "counter", name = "dropped_out_of_order_total", field = "msg"},
  ]

# Expose metrics for scraping in the Prometheus format.
[sinks.prometheus_sink]
  type = "prometheus_exporter"
  address = "0.0.0.0:9090"
  inputs = ["internal_metrics", "ooo_counter"]
```

### Unit tests

```yaml
tests:
  # This test fails when I claim it should succeed.
  - name: count_ooo
    inputs:
      - insert_at: ooo_filter
        type: log
        log_fields:
          msg: "Received out-of-order event; dropping event."
    outputs:
      # When the test fails, we are told that this is the output:
      #
      # {"name":"dropped_out_of_order_total",
      #  "timestamp":"...",
      #  "kind":"incremental",
      #  "counter": {"value":1.0}}
      - extract_from: ooo_counter
        conditions:
          - type: check_fields
            name.exists: true
            name.eq: dropped_out_of_order_total
            counter.value.eq: 1.0

  # This test succeeds.
  - name: count_ooo_negative
    inputs:
      - insert_at: ooo_filter
        type: log
        log_fields:
          msg: "Some other message"
    no_outputs_from:
      - ooo_filter
      - ooo_counter

  # This test attempts to recreate the conditions of `count_ooo`
  # and, despite having broadly the same `output`, succeeds.
  - name: noop
    inputs:
      - insert_at: noop
        type: log
        log_fields:
          name: dropped_out_of_order_total
          timestamp: "2021-07-01T13:00:34.227987404Z"
          kind: "incremental"
          counter.value: 1.0
    outputs:
      - extract_from: noop
        conditions:
          - type: check_fields
            name.exists: true
            name.eq: dropped_out_of_order_total
            counter.value.eq: 1.0
```

### Test Output

```
# RUST_BACKTRACE=full vector -vvv test *.toml *.yaml
Running tests
Jul 01 13:47:09.641  WARN vector::conditions::check_fields: The `check_fields` condition is deprecated, use `remap` instead.
Jul 01 13:47:09.641  WARN vector::conditions::check_fields: The `check_fields` condition is deprecated, use `remap` instead.
test count_ooo ... failed
test count_ooo_negative ... passed
test noop ... passed

failures:

test count_ooo:

check transform 'ooo_counter' failed conditions:
  condition[0]: predicates failed: [ name.exists: true, name.eq: "dropped_out_of_order_total", counter.value.eq: 1.0 ]
payloads (events encoded as JSON):
   input: {"message":"","msg":"Received out-of-order event; dropping event.","timestamp":"2021-07-01T13:47:09.641110997Z"}
  output: {"name":"dropped_out_of_order_total","timestamp":"2021-07-01T13:47:09.641110997Z","kind":"incremental","counter":{"value":1.0}}
```

### Expected Behavior

I was expecting the conditions in `count_ooo` to succeed.

### Actual Behavior

They all failed even the `.exists` check!

### Additional Context

This is a Vector instance running in a Docker image as a test harness.

**Comment by bruceg** [comment]
This is unfortunately a current limitation of the `check_fields` conditions, which are unable to do much with comparisons against metrics. In particular, the predicates can only test tag values. The second test case succeeds because it is test a log instead of a metric. Throwing in an extra `metric_to_log` transform and testing against its output makes the tests pass. Alternately, you can use VRL conditions instead, as `check_fields` is deprecated:
```
      - extract_from: to_log
        conditions:
          - type: "vrl"
            source: ' .name == "dropped_out_of_order_total" && .counter.value == 1.0 '
```
