### ISSUE TITLE
Keepalive config not being parsed

### ISSUE THREAD

**Issue by mr-karan** [vectordotdev/vector#8207]
### Vector Version

```
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector Configuration File

```toml
[sources.vector_aggregator]
  type = "vector" # required
  acknowledgements = false # optional, default
  address = "0.0.0.0:9000" # required
  keepalive = 5
  shutdown_timeout_secs = 30
```

or

```toml
[sinks.agent_out]
  # General
  type = "vector" # required
  inputs = ["format_app_logs"]
  address = "1.1.1.1:5000"
  healthcheck.enabled = false
  keepalive = 5
```

### Expected Behavior

Vector should run normally since this config key is documented [here](https://vector.dev/docs/reference/configuration/sources/vector/#keepalive) and [here](https://vector.dev/docs/reference/configuration/sinks/vector/#keepalive)

### Actual Behavior

```
$ vector
Jul 09 15:36:18.284 ERROR vector::cli: Configuration error. error=data did not match any variant of untagged enum VectorConfig for key `sources.vector_aggregator` at line 25 column 1
```

Same error for `sink.agent_out`.

**Comment by spencergilbert** [comment]
I suspect this may be the same as #8138 where it was documented but implemented, and should be added. I'll check it out.

**Comment by spencergilbert** [comment]
Actually @mr-karan it is implemented, it's just under a subkey: https://vector.dev/docs/reference/configuration/sources/vector/#time_secs

```toml
[sources.vector_aggregator]
  type = "vector" # required
  acknowledgements = false # optional, default
  address = "0.0.0.0:9000" # required
  keepalive.time_secs = 5
  shutdown_timeout_secs = 30
```
