### ISSUE TITLE
wasm compile error

### ISSUE THREAD

**Issue by lichuan6** [vectordotdev/vector#8230]
I follow the guide to add wasm support to vector but compiling failed with this error on macOS.

```

   Compiling darling v0.10.2
   Compiling darling v0.12.3
error: failed to run custom build command for `openssl-sys v0.9.65`

Caused by:
  process didn't exit successfully: `/Users/lichuan/Documents/__git__/timberio/vector/target/release/build/openssl-sys-86afc51c7096714d/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_NO_VENDOR
  X86_64_APPLE_DARWIN_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  running "perl" "./Configure" "--prefix=/Users/lichuan/Documents/__git__/timberio/vector/target/release/build/openssl-sys-a86656f13a472cf4/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "darwin64-x86_64-cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
  Configuring OpenSSL version 1.1.1k (0x101010bfL) for darwin64-x86_64-cc
  Using os-specific seed configuration
  Creating configdata.pm
  Creating Makefile

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL file first)         ***
  ***                                                                ***
  **********************************************************************
  running "make" "depend"
  running "make" "build_libs"
  perl "-I." -Mconfigdata "util/dofile.pl" \
            "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h

  --- stderr
  make: *** read jobs pipe: Resource temporarily unavailable.  Stop.
  make: *** Waiting for unfinished jobs....
  thread 'main' panicked at '


  Error building OpenSSL:
      Command: "make" "build_libs"
      Exit status: exit status: 2


      ', /Users/lichuan/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.15.0+1.1.1k/src/lib.rs:471:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
⏎

```

Anyone can help?

Thanks

**Comment by lichuan6** [comment]
After running `export OPENSSL_DIR=/usr/local/Cellar/openssl@1.1/1.1.1k`, the code compiles.

But vector runs with a panic:

```
Jul 12 05:48:22.571  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info" enable_datadog_tracing=false
Jul 12 05:48:22.572  INFO vector::app: Loading configs. paths=["v.toml"]
Jul 12 05:48:22.577  INFO vector::sources::stdin: Capturing STDIN.
Jul 12 05:48:22.577  INFO vector::internal_events::wasm::compilation: WASM Compilation via `lucet`. state="beginning" role="transform" elapsed_micros=0
Jul 12 05:48:24.585 ERROR vector::topology: Configuration error. error=Transform "transform0": Ld error: ld of /var/folders/gd/jc_f138s46g320dnyf4z2yz40000gn/T/lucetc2NycSE/tmp.o failed: Undefined symbols for architecture x86_64:
  "_config", referenced from:
      _trampoline_config in tmp.o
      _lucet_function_manifest in tmp.o
  "_config_size", referenced from:
      _trampoline_config_size in tmp.o
      _lucet_function_manifest in tmp.o
  "_emit", referenced from:
      _trampoline_emit in tmp.o
      _lucet_function_manifest in tmp.o
  "_hostcall_wasi_snapshot_preview1_environ_get", referenced from:
      _trampoline_hostcall_wasi_snapshot_preview1_environ_get in tmp.o
      _lucet_function_manifest in tmp.o
  "_hostcall_wasi_snapshot_preview1_environ_sizes_get", referenced from:
      _trampoline_hostcall_wasi_snapshot_preview1_environ_sizes_get in tmp.o
      _lucet_function_manifest in tmp.o
  "_hostcall_wasi_snapshot_preview1_fd_write", referenced from:
      _trampoline_hostcall_wasi_snapshot_preview1_fd_write in tmp.o
      _lucet_function_manifest in tmp.o
  "_hostcall_wasi_snapshot_preview1_proc_exit", referenced from:
      _trampoline_hostcall_wasi_snapshot_preview1_proc_exit in tmp.o
      _lucet_function_manifest in tmp.o
  "_hostcall_wasi_snapshot_preview1_random_get", referenced from:
      _trampoline_hostcall_wasi_snapshot_preview1_random_get in tmp.o
      _lucet_function_manifest in tmp.o
  "_lucet_vmctx_current_memory", referenced from:
      _sbrk_421 in tmp.o
      _lucet_function_manifest in tmp.o
  "_lucet_vmctx_grow_memory", referenced from:
      _sbrk_421 in tmp.o
      _lucet_function_manifest in tmp.o
  "_main", referenced from:
     implicit entry/start for main executable
  "_register", referenced from:
      _trampoline_register in tmp.o
      _lucet_function_manifest in tmp.o
ld: symbol(s) not found for architecture x86_64

```

Here's the vector config file:

```toml
data_dir = "/tmp/var/lib/vector/"

[sources.source0]
max_length = 102400
type = "stdin"

[transforms.transform0]
inputs = ["source0"]
type = "wasm"
module = "target/wasm32-wasi/release/add_fields.wasm"
artifact_cache = "cache/"
options.new_field = "new_value"
options.new_field_2 = "new_value_2"

[sinks.sink0]
healthcheck = true
inputs = ["transform0"]
type = "console"
encoding = "json"
buffer.type = "memory"
buffer.max_events = 500
buffer.when_full = "block"

```

**Comment by jszwedko** [comment]
Hi @lichuan6 ,

We are actually going to be dropping WASM support in Vector in the near future (#8036) due to lack of our investment and user interest. We may bring it back in the future though. I'm curious what you were planning on using it for so we could suggest an alternative.

I've also never been able to compile the WASM support on OSX; only Linux. I think I saw the same errors you see.

**Comment by lichuan6** [comment]
Currently, I'm trying to investigate the best way for log processing in complicated use cases. For example, shipping logs from k8s in the specified namespace to the corresponding pulsar topic. Let's say I have pods running in 3 different k8s namespaces, `biz1`, `biz2`, `biz3`, I want to parse all logs in pods running in k8s namespace and sink them to pulsar topics: logs in `biz1` namespace to pulsar topic `public/logging/biz1`, `biz2` to `public/logging/biz2` and `biz3` to `public/logging/biz3`, etc. 

I was considering using [Lua transform](https://vector-backup.netlify.app/docs/reference/configuration/transforms/lua/) , but I'm worried about the performance of for complicated logic.

I thought the vector plugin system using WASM is the best choice. Sadly to hear that WASM will not be supported in the near future.

**Comment by spencergilbert** [comment]
Are you looking to parse them differently or just route them differently @lichuan6 ?

**Comment by lichuan6** [comment]
I'm looking to route logs from different k8s namespaces to different pulsar topics. Is there any way to do that?

**Comment by spencergilbert** [comment]
It would be a lot simpler if the pulsar sink's topic option took a template rather than a literal, but without that enhancement (which should be pretty easy) you can do it today (with some duplication)

```toml
[sources.kubernetes_logs]
  type = "kubernetes_logs"

[transforms.router]
  type = "route"
  inputs = ["kubernetes_logs"]

  route.biz1 = '.kubernetes.pod_namespace == "biz1"'
  route.biz2 = '.kubernetes.pod_namespace == "biz2"'
  route.biz3 = '.kubernetes.pod_namespace == "biz3"'

[sinks.pulsar_biz1]
  type = "pulsar"
  inputs = ["router.route.biz1"] # required
  endpoint = "pulsar://127.0.0.1:6650"
  topic = "biz1" # required

  encoding.codec = "text"

[sinks.pulsar_biz2]
  type = "pulsar"
  inputs = ["router.route.biz2"] # required
  endpoint = "pulsar://127.0.0.1:6650"
  topic = "biz2" # required

  encoding.codec = "text"

[sinks.pulsar_biz3]
  type = "pulsar"
  inputs = ["router.route.biz3"] # required
  endpoint = "pulsar://127.0.0.1:6650"
  topic = "biz3" # required

  encoding.codec = "text"
```

**Comment by lichuan6** [comment]
Thanks, @spencergilbert.

In reality, we don't know how many k8s namespaces we have, it could be three or 100. It's hard to manage 100 lines or more `route.{pulsar_topic} = ''.kubernetes.pod_namespace == "{namespace}"` in `[transforms.router]`. 

Does `transforms.router` support pattern or prefix or something like dynamic config, that I can just write one line in the config:

```toml
[transforms.router]
  type = "route"
  inputs = ["kubernetes_logs"]

  route.biz_prefix = '.kubernetes.pod_namespace == "biz*"' // <---- Can I do this?
  route.otherbiz_prefix = '.kubernetes.pod_namespace == "otherbiz*"' // <---- Can I do this?

[sinks.pulsar_biz_prefix]
  type = "pulsar"
  inputs = ["router.biz_prefix"] # required
  endpoint = "pulsar://127.0.0.1:6650"
  topic = "biz_prefix" # required

  encoding.codec = "text"

[sinks.pulsar_otherbiz_prefix]
  type = "pulsar"
  inputs = ["router.otherbiz_prefix"] # required
  endpoint = "pulsar://127.0.0.1:6650"
  topic = "otherbiz_prefix" # required

  encoding.codec = "text"

```

**Comment by spencergilbert** [comment]
@jszwedko check me here, but I don't think we support such dynamic control in the `route` transform.

I suspect the easiest fix would be to make the `topic` option template-able so the sink config could be:

```toml
[sinks.pulsar_otherbiz_prefix]
  type = "pulsar"
  inputs = ["indput"]
  endpoint = "pulsar://127.0.0.1:6650"
  topic = "{{ kubernetes.pod_namespace }}"

  encoding.codec = "text"
```

And each event would be written to a topic matching the namespace - similar to the kafka sink
