### ISSUE TITLE
Failed healthcheck doesn't give reason of failure

### ISSUE THREAD

**Issue by fpytloun** [vectordotdev/vector#8260]
### Vector Version

```
vector 0.14.0 (x86_64-unknown-linux-musl 5f3a319 2021-06-03)
```

### Vector Configuration File

```toml
...
    [sinks.out_kafka_audit_s3]
      type = "aws_s3"
      inputs = ["remap_kafka_audit"]
      bucket = "my-logs"
      region = "us-west-2"
      key_prefix = "topics/{{ _topic }}/year=%Y/month=%m/day=%d/hour=%H/"
      # Write at least every 10 minutes
      batch.timeout_secs = 600
      request.concurrency = "adaptive"
      buffer.type = "memory"
      buffer.max_events = 3000    # default 500 with memory buffer
      batch.max_bytes = 31470000  # 30MB (default 10MB)
      encoding.codec = "ndjson"
      encoding.except_fields = ["_index", "_topic", "_topic_template", "_partition", "_offset"]
      compression = "gzip"
      filename_extension = "json.gz"
...
```

### Expected Behavior

Log output should contain useful information about why healthcheck failed. In this case, it failed due some network issue (eg. DNS resolution failure).

### Actual Behavior

```
Jul 13 14:35:35.058 ERROR vector::topology::builder: msg="Healthcheck: timeout." component_kind="sink" component_type="aws_s3" component_name="out_kafka_access_s3"
```
