### ISSUE TITLE
VRL function parse_key_value parses incorrectly when quoted value contains key/value pairs & newline

### ISSUE THREAD

**Issue by djablonski-moia** [vectordotdev/vector#8311]
### Vector Version

```
vector 0.14.0 (x86_64-apple-darwin 5f3a319 2021-06-03)
```

### Vector Configuration File

```yaml
sources:
  logs:
    type: file
    include:
      - "sample.log"
    read_from: beginning

transforms:
  parse_key_value:
    type: remap
    inputs:
      - logs
    source: |
      . |= parse_key_value(.message) ?? {}

sinks:
  stdout:
    type: console
    inputs:
      - parse_key_value
    encoding: json

tests:
  - name: check_key_value_parsing
    input:
      insert_at: parse_key_value
      type: log
      log_fields:
        message: 'problematicField="something key1 = a \n key2 = b"'
    outputs:
      - extract_from: parse_key_value
        conditions:
          - type: remap
            source: |
              !exists(.key1)
```

### Debug Output

For debug output from `RUST_BACKTRACE=full vector -vvv --config-yaml vector.yaml`, please see https://gist.github.com/djablonski-moia/49fe5208c461a474d4d39b901340bbde

### Expected Behavior

The field `problematicField` should be the only one (except the standard fields), and the unit test should succeed.

```json
{
  "file":"sample.log",
  "host":"localhost",
  "message":"problematicField=\"something key1 = a \\n key2 = b\"",
  "problematicField":"something key1 = a \n key2 = b",
  "source_type":"file",
  "timestamp":"2021-07-15T09:11:27.166952Z"
}
```

### Actual Behavior

Although the field value is properly quoted, the content is still parsed, resulting in additional fields `key1` and `key2` in the output. Furthermore, the value of `problematicField` is incomplete (truncated).

```
{
  "\\n key2":"b\"",
  "file":"sample.log",
  "host":"localhost",
  "key1":"a",
  "message":"problematicField=\"something key1 = a \\n key2 = b\"",
  "problematicField":"\"something",
  "source_type":"file",
  "timestamp":"2021-07-15T09:11:27.166952Z"
}
```

### Example Data

```
problematicField="something key1 = a \n key2 = b"
```

### Additional Context

Running the unit test generates the following output:

```
Running tests
test check_key_value_parsing ... failed

failures:

test check_key_value_parsing:

check transform 'parse_key_value' failed conditions:
  condition[0]: source execution resolved to false
payloads (events encoded as JSON):
   input: {"message":"problematicField=\"something key1 = a \\n key2 = b\"","timestamp":"2021-07-15T08:41:48.894551Z"}
  output: {"\\n key2":"b\"","key1":"a","message":"problematicField=\"something key1 = a \\n key2 = b\"","problematicField":"\"something","timestamp":"2021-07-15T08:41:48.894551Z"}
```

The issue only occurs in this specific combination. If the leading `something` would be multiple words, it might not trigger, also if there is no newline, or no other key/value-like text in second line.

**Comment by jszwedko** [comment]
Hey @djablonski-moia ! Thanks for the report. This actually appears to be fixed in `master`; we had a number of small tweaks to that function to fix edge cases like that recently.

This should work in the current nightly build, but we are also aiming for a stable release this week which will include the changes too.

**Comment by djablonski-moia** [comment]
Thank you @jszwedko,

I can confirm that the issue is fixed in the current nightly build. Only thing I realized is that the test now seems to have an invalid syntax, so there might be an incompatible change. Dunno if this is intended 🤔 

Should I close this issue now, or should it be closed only when "officially" released?

**Comment by jszwedko** [comment]
@djablonski-moia oh yes, there is a small breaking change that renamed the `type` for `remap` conditions to `vrl`.

```yml
tests:
  - name: check_key_value_parsing
    input:
      insert_at: parse_key_value
      type: log
      log_fields:
        message: 'problematicField="something key1 = a \n key2 = b"'
    outputs:
      - extract_from: parse_key_value
        conditions:
          - type: vrl
            source: |
              !exists(.key1)
```

Should work for you. That will be noted in the release notes for 0.15.0. We plan to release that this week.

You can also leave out `type` and use short-hand:

```yml
tests:
  - name: check_key_value_parsing
    input:
      insert_at: parse_key_value
      type: log
      log_fields:
        message: 'problematicField="something key1 = a \n key2 = b"'
    outputs:
      - extract_from: parse_key_value
        conditions:
          - "!exists(.key1)"
```

If you prefer.

I'll close this out, but I have been thinking about workflow changes that would have us mark issues as "will be closed" in the next release to not close them until the changes are actually released. For now, I'll keep with the current workflow though.

Thanks for testing!
