### ISSUE TITLE
"annotate event with pod metadata" on removed pod

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#8345]
### Vector Version

```
0.14.0
```

### Vector Configuration File

```toml
[sources.kubernetes_logs]
  type = "kubernetes_logs"
...
[sources.k8s_logs]
  extra_label_selector = "logging.<redacted>.com/enabled = true"
  type = "kubernetes_logs"
```

NOTE: possibly related to the accidental inclusion of two `kubernetes_logs` sources, but I'm not sure how it would have manifested. -- Seems unlikely, the user redeployed removing the default provided source and still sees the issue

### Actual Behavior

We seem to be continuing to try and annotate an(multiple?) event from a pod that's been removed and failing to do so

### References

Reported in discord: https://discord.com/channels/742820443487993987/753400475545501836/865570923007442944

> However if I ls /var/log/pods on all the vectors pods I can't see that particularly directory.  I can see the directories for the other pods that are working.
>
> Also, grabbing the pod ID from the log files, I can see that the failing one does not exist, while the working one does
>
> Failing log name:
/var/log/pods/<appname>-production<app_name>-cd99bddf6-ps4m7_f5432555-1009-463a-ae4b-27d5fba26992/web/0.log
>
> Working log name:
/var/log/pods/<appname>-production<app_name>-6cb57bc586-95cx4_1364e042-34f5-4578-be64-cd4e306a92a3/web/0.log

> Looks like they (failed annotation events) started months ago just in very low volume, ~600 a day.  Last 24 hours is ~12.3M

**Comment by spencergilbert** [comment]
Vector is running on https://kinvolk.io/lokomotive-kubernetes/

**Comment by jszwedko** [comment]
I was able to reproduce this by:

* Deploying vector using the vector-agent helm chart with `values.yaml` file:
```yaml
customConfig:
    data_dir: "/vector-data-dir"
    sources:
      host_metrics:
        type: host_metrics
        filesystem:
          devices:
            excludes: ["binfmt_misc"]
          filesystems:
            excludes: ["binfmt_misc"]
          mountpoints:
            excludes: ["*/proc/sys/fs/binfmt_misc"]
      internal_metrics:
        type: internal_metrics
      kubernetes_logs:
        type: kubernetes_logs
    sinks:
      stdout:
        type: blackhole
        inputs: ["kubernetes_logs"]
        print_amount: 1000
        rate: 100
      prometheus_sink:
        type: prometheus_exporter
        inputs: ["host_metrics", "internal_metrics"]
        address: 0.0.0.0:9090
```
* Running flog as a deployment via:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flog-deployment
  labels:
    app: flog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flog
  template:
    metadata:
      labels:
        app: flog
    spec:
      containers:
      - name: flog
        image: mingrammer/flog
        command: ['/bin/flog', '-l']
```
* Observing logs flowing through the vector container
* Stopping the flog pod `kubectl delete -f flog.yaml`
* After < 60s passed, observe the error messages

This appears to occur because Vector continues processing log files for a pod after it has been deleted, but if we've dropped it from our internal metadata cache (as part of pod deletion) then we can no longer annotate it.

Proposed solution:

When a pod is deleted, mark the entry in the metadata cache as deleted, but don't actually delete it until we haven't observed logs from that pod for X amount of time.

This could still fail in extreme cases, but should be much less likely to be seen. A more robust solution would likely require rearchitecting a bit so that the `kubernetes_logs` source could be aware of which pod log files are still being consumed and only delete the metadata after they finish.
