### ISSUE TITLE
Datadog logs sink does not appear to populate `component_name` label

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#8368]
### Vector Version

3c77722763f13b7762d4306ce474205df33e44b1

### Vector Configuration File

```toml
data_dir = "/tmp/data/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.datadog_logs]
type = "datadog_logs"
acknowledgements = false
address = "0.0.0.0:8282"

##
## Sinks
##

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"

[sinks.dd_logs_egress]
type = "datadog_logs"
inputs = ["datadog_logs"]
default_api_key = "DEADBEEF"
encoding.codec = "json"
endpoint = "http://localhost:8080/v1/input"
```

### Expected Behavior

The `component_name` label should be populated by the datadog logs sink on metric `vector_processed_bytes_total`. 

### Actual Behavior

It isn't. See [this issue comment](https://github.com/timberio/vector/issues/8263#issuecomment-882721186) for more details of my setup.
