### ISSUE TITLE
no memory_total_bytes metric in metrics endpoint

### ISSUE THREAD

**Issue by dylankyc** [vectordotdev/vector#8399]
Hi,

I setup `internal_metrics` source in config but find no `memory_total_bytes` metric by querying metrics endpoint: `curl localhost:8889/metrics`

```
# HELP vector_api_started_total api_started_total
# TYPE vector_api_started_total counter
vector_api_started_total 1 1626855338247
# HELP vector_events_in_total events_in_total
# TYPE vector_events_in_total counter
vector_events_in_total{component_kind="sink",component_name="console",component_type="console"} 1531 1626855338247
vector_events_in_total{component_kind="sink",component_name="prometheus",component_type="prometheus_exporter"} 1531 1626855338247
vector_events_in_total{component_kind="source",component_name="vector_metrics",component_type="internal_metrics"} 0 1626855338247
# HELP vector_events_out_total events_out_total
# TYPE vector_events_out_total counter
vector_events_out_total{component_kind="source",component_name="vector_metrics",component_type="internal_metrics"} 1531 1626855338247
vector_events_out_total{component_kind="sink",component_name="console",component_type="console"} 1531 1626855338247
vector_events_out_total{component_kind="sink",component_name="prometheus",component_type="prometheus_exporter"} 1531 1626855338247
# HELP vector_internal_metrics_cardinality_total internal_metrics_cardinality_total
# TYPE vector_internal_metrics_cardinality_total counter
vector_internal_metrics_cardinality_total 14 1626855338247
# HELP vector_processed_bytes_total processed_bytes_total
# TYPE vector_processed_bytes_total counter
vector_processed_bytes_total{component_kind="sink",component_name="console",component_type="console"} 188110 1626855338247
# HELP vector_processed_events_total processed_events_total
# TYPE vector_processed_events_total counter
vector_processed_events_total{component_kind="source",component_name="vector_metrics",component_type="internal_metrics"} 1531 1626855338247
vector_processed_events_total{component_kind="sink",component_name="console",component_type="console"} 1531 1626855338247
vector_processed_events_total{component_kind="sink",component_name="prometheus",component_type="prometheus_exporter"} 1531 1626855338247
# HELP vector_started_total started_total
# TYPE vector_started_total counter
vector_started_total 1 1626855338247
# HELP vector_uptime_seconds uptime_seconds
# TYPE vector_uptime_seconds gauge
vector_uptime_seconds 220 1626855338247
```

`vector.toml`

```toml
data_dir = "/tmp/var/lib/vector"

[sources.vector_metrics]
type = "internal_metrics"

[sinks.console]
type = "console"
encoding = "text"
inputs = ["vector_metrics"]

[sinks.prometheus]
type = "prometheus_exporter" # required
inputs = ["vector_metrics"] # required
address = "0.0.0.0:8889" # required

[api]
enabled = true
address = "127.0.0.1:8686"
```
