### ISSUE TITLE
Compression between vector and ElasticSearch is not working for egress traffic

### ISSUE THREAD

**Issue by okorolov** [vectordotdev/vector#8439]
### Vector Version
```
0.15.0
```

### Vector Configuration File

```toml
    [sinks.es]
      type = "elasticsearch"
      inputs = ["es_timestamp"]
      healthcheck.enabled = true

      auth.strategy = "basic"
      auth.user = "---"
      auth.password = "---"
      endpoint = "---:9200"
      mode = "data_stream"
      data_stream.auto_routing = false
      data_stream.sync_fields = false
      data_stream.type = "---"
      data_stream.dataset = "logs"
      data_stream.namespace = "ds"

      compression = "gzip"

      batch.max_bytes = 50000000
      batch.timeout_secs = 1
      buffer.max_events = 10000000
      buffer.type = "memory"
      buffer.when_full = "block"

```

### Expected Behavior
When we configure compression = "gzip" for ElasticSearch sink it is expected that compression is applied in both directions - ingress and egress.
### Actual Behavior
Compression is applied only to ingress traffic.

### Workaround

Custom headers applied on the vector side fix the situation and the return traffic is also compressed.

```toml
    [sinks.es]
      compression = "gzip"
      # response compression
      request.headers.Accept-Encoding = "gzip"

```

### Additional Context

ES version - 7.13.1
Also tested with vector - 0.12.2

Compression is clearly enabled on all ES nodes.

It might be that vector is not configuring its headers correctly when compression is enabled. 
It seems that ES is expecting to receive specific headers that will instruct it for using compression on the reply traffic (egress)
https://discuss.elastic.co/t/http-compression-enabled-but-response-not-compressed/103513/7

Ingress Traffic Rates when we apply Compression
![inbound_traffic_es](https://user-images.githubusercontent.com/31506341/126802657-326dafb4-6a79-4ffb-82b6-ee690129ab95.png)
Egress Traffic Rates when we apply Compression
![outbound_traffic_es](https://user-images.githubusercontent.com/31506341/126802674-232c5308-138f-461c-9fb0-4733a8bf43f0.png)
Egress Traffic Rates when we apply custom Headers and Compression
![outbound_traffic_es_headers](https://user-images.githubusercontent.com/31506341/126802686-df246e1a-48a7-4701-af0d-c0e15cea70ae.png)
