### ISSUE TITLE
AWS firehose sink support for delivery stream ARN

### ISSUE THREAD

**Issue by ocrlgv** [vectordotdev/vector#8562]
Setting up vector to send logs to kinesis firehose I noticed the parameters only contain "stream_name" https://vector.dev/docs/reference/configuration/sinks/aws_kinesis_firehose/#stream_name

This then only supports the local account, supporting AWS ARNs in every resource where possible allows for cross account/region support as long as permissions are set.

Adding another kinesis in local account/region to forward to primary instance does not scale as you would need to configure every account/region to push to the same kinesis observability instance.

Suggest adding ability to provide a delivery_stream_arn allows to send anywhere.

**Comment by jszwedko** [comment]
Hey @ocrlgv !

Could you explain a bit more how you would you are looking for here?

Vector can already "send anywhere" by configuring the region on the `aws_kinesis_firehose` sink like:

```toml
[sinks.my_sink_id]
type = "aws_kinesis_firehose"
inputs = [ "my-source-or-transform-id" ]
stream_name = "my-stream"
compression = "none"
region = "us-east-1" # change to another region to publish to `my-stream` in that region
```
