### ISSUE TITLE
Console sink example doesn't work

### ISSUE THREAD

**Issue by jdrouet** [vectordotdev/vector#8564]
Hi!
When we take the console sink example and copy paste it, it doesn't work because the `encoding` field is missing

```toml
# what we have
[sinks.my_sink_id]
type = "console"
inputs = [ "my-source-or-transform-id" ]
target = "stdout"
# what we should have
[sinks.my_sink_id]
type = "console"
inputs = [ "my-source-or-transform-id" ]
encoding.codec = "json"
target = "stdout"
```

Also, would be great to have an explicit list of possible codecs.
