### ISSUE TITLE
Regex parsing errors on K8S

### ISSUE THREAD

**Issue by ArtemTrofimushkin** [vectordotdev/vector#8606]
Hi there

### Vector Version

```
vector 0.15.0 (x86_64-unknown-linux-musl 994d812 2021-07-16)
```

### Vector Configuration File

```yaml
api:
  address: 0.0.0.0:8686
  enabled: true
  playground: true
data_dir: /vector-data-dir
healthchecks:
  enabled: true
  require_healthy: true
log_schema:
  host_key: host
  message_key: message
  source_type_key: source_type
  timestamp_key: timestamp
sinks:
  azure_blob:
    batch:
      max_bytes: 33554432
      max_events: 10240
      timeout_secs: 30
    blob_append_uuid: true
    blob_prefix: kubernetes/{{ metadata.cluster }}/{{ kubernetes.node.name }}/
    blob_time_format: "%F-%T"
    connection_string: ${SINK_AZURE_BLOB_CONNECTION_STRING}
    container_name: ${SINK_AZURE_BLOB_CONTAINER_NAME}
    encoding: ndjson
    inputs:
      - kubernetes_logs_transform
    type: azure_blob
  prometheus_sink:
    address: 0.0.0.0:9090
    inputs:
      - internal_metrics
    type: prometheus_exporter
sources:
  internal_metrics:
    type: internal_metrics
  kubernetes_logs:
    auto_partial_merge: true
    exclude_paths_glob_patterns:
      - "**/*.gz"
      - "**/*.tmp"
    fingerprint_lines: 1
    glob_minimum_cooldown_ms: 250
    max_line_bytes: 32768
    type: kubernetes_logs
transforms:
  kubernetes_logs_transform:
    inputs:
      - kubernetes_logs
    source: |
      # capture metadata to single object
      metadata = {
        "_id": replace(uuid_v4(), "-", ""),
        "file": del(.file),
        "source_type": del(.source_type),
        "stream": del(.stream),
        "cluster": get_env_var("SOURCE_CLUSTER_NAME") ?? ""
      }

      # replace original message with structured/unstructured pattern
      message = del(.message)
      structured = parse_json(message) ?? ""

      # reformat kubernetes metadata (join flat properties to object)
      kubernetes = del(.kubernetes)

      # deal with labels (replace . with _ in some label names)
      kubernetes_labels = encode_json(kubernetes.pod_labels)
      kubernetes_labels = replace(kubernetes_labels, "app.kubernetes.io", "app_kubernetes_io")
      kubernetes_labels = replace(kubernetes_labels, "helm.sh", "helm_sh")

      # build output object
      .metadata = metadata
      .structured = structured
      .unstructured = if is_nullish(structured) { message } else { "" }
      .kubernetes = {
        "container": {
          "image": kubernetes.container_image,
          "name": kubernetes.container_name
        },
        "node": {
          "name": kubernetes.pod_node_name
        },
        "pod": {
          "name": kubernetes.pod_name,
          "uid": kubernetes.pod_uid,
          "ip": kubernetes.pod_ip
        },
        "namespace": kubernetes.pod_namespace,
        "labels": parse_json!(kubernetes_labels)
      }
    type: remap
...
```

### Expected Behavior

Vector not fail to parse logs from kubernetes_log_source

### Actual Behavior

Vector sometimes fail to parse logs from kubernetes_log_source and write following messages in output (for several applications):

```
Aug 05 17:35:26.643  WARN source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::internal_events::regex_parser: Regex pattern failed to match. field="2021-08-05T17:35:26.640507539Z stdout P {\"@timestamp\":\"[...]" internal_log_rate_secs=30
Aug 05 17:35:26.644  WARN source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::internal_events::regex_parser: Internal log [Regex pattern failed to match.] is being rate limited.

```
### Additional Context

Kubernetes version: 1.20.7 (Azure Kubernetes Service)

After some investigation I found the following details:

1. Logs from container stdout captured by log driver and persists on filesystem in following format:

```
<Timestamp> <Stream> <Multiline Tag> <Message>
```

2. Application logs may contain unicode characters (each symbol may be encoded with two or more bytes)

3. Several of our applications write huge logs (more than 8k bytes), thus log messages divided in lines, each 8k bytes length (with `P` multiline tag)

4. Sometimes this can happen in the middle of unicode character (which is greater than 1 byte). In this case, unicode character combines with `0a` byte (probably by log driver?) and becomes malformed

5. Vector [uses regex](https://github.com/timberio/vector/blob/master/src/sources/kubernetes_logs/parser/cri.rs#L37) to parse CRI logs, which fails when line contains malformed unicode symbols. 

6. Vector discards log line from processing pipeline

Screenshoot from worker node (in this example I try to capture hex representation of such log line with timestamp `2021-08-05T19:01:11.610842717Z`) :

![Screenshot 2021-08-05 at 22 01 44](https://user-images.githubusercontent.com/13941667/128406556-9ef5124a-c11d-4e5f-93e7-c525a761dd5d.png)

With decoded hex :

```
00003fb0  81 d0 b8 d0 b8 5c 22 2c  5c 22 6d 65 74 61 44 65  |.....\",\"metaDe|
                             "  ,   \  "  m  e  t  a  D  e
00003fc0  73 63 72 69 70 74 69 6f  6e 5c 22 3a 5c 22 d0 9f  |scription\":\"..|
           s  c  r  i  p  t  i  o   n  \  "  :  \  "   П
00003fd0  d0 b8 d1 86 d1 86 d0 b0  20 d0 be d1 82 20 32 34  |........ .... 24|
            и     ц     ц     а         о     т       2  4
00003fe0  35 20 d1 80 d1 83 d0 b1  d0 bb d0 b5 d0 b9 2e 20  |5 ............. |
           5      р     у     б      л     е     й    .
00003ff0  d0 91 d1 8b d1 81 d1 82  d1 80 d0 b0 d1 8f 20 d0  |.............. .|
            Б     ы     с     т      р     а     я       б
00004000  b1 d0 b5 d1 81 d0 bf d0  bb d0 b0 d1 82 d0 bd d0  |................|
               е     с     п      л     а     т     н    а
00004010  b0 d1 8f 20 d0 b4 d0 be  d1 81 d1 82 d0 b0 d0 b2  |... ............|
               я        д     о      с     т     а     в
00004020  d0 ba d0 b0 20 d0 b4 d0  0a                       |.... ....|
            к     а        д     ??
00004029
```

In this example the last two bytes are not valid unicode symbol and vector fails to parse log line with output:

![image](https://user-images.githubusercontent.com/13941667/128410580-d289c875-c06a-4364-bbba-d55a23d1d824.png)

If it helps, I wrote simple [example](https://gist.github.com/ArtemTrofimushkin/f57fda7460101d5c3814746109e145d5) to demonstate specified behavior. 

If it helps, I wrote tiny k8s app, which continially write huge logs with unicode characters (these log lines captured from one of our testing environments). 

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: infra-vector-test-long-lines
    app.kubernetes.io/name: infra-vector-test-long-lines
  name: infra-vector-test-long-lines
spec:
  containers:
    - image: artemtrofimushkin/vector-test-long-logs:2.2
      name: app
      resources:
        limits:
          cpu: 250m
          memory: 200Mi
  terminationGracePeriodSeconds: 60
```  

Vector fail to parse some log messages

![Screenshot 2021-08-05 at 22 58 42](https://user-images.githubusercontent.com/13941667/128413228-aa4fb703-c616-4ce3-b9d6-c8fcb5f0e1f9.png)
