### ISSUE TITLE
Investigate `fluent` -> `remap` -> `kinesis` 

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#8610]
This issue is a record of and parent to the investigation of vector's performance when configured like so:

```toml
data_dir = "/tmp/data/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.fluent]
type = "fluent"
address = "0.0.0.0:24225"

##
## Transforms
##

[transforms.remap]
type = "remap"
inputs = ["fluent"]
source = """
event = del(.event)
# set event to message fields, dropping any existing fields
. = {}
.event = object!(event)
"""

##
## Sinks
##

[sinks.firehose-sink]
type = "aws_kinesis_firehose"
inputs = [ "remap" ]
stream_name = "LT-SplunkFirehosePOC-NOLAMBDA"
region = "us-east-1"
healthcheck.enabled = false
compression = "none"
encoding = "json"

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"
```

This investigation is similar to #8512 and #8263 in approach. Vector is run like so:

```
> firejail --noprofile --rlimit-as=2g --cpu=1,2,3,4,5,6,7,8 ./target/release/vector --config ~/projects/us/troutwine/lading/configs/vector-fluent-remap-kinesis.toml
```

**Comment by blt** [comment]
In https://github.com/blt/lading/pull/77 we have introduced the ability to generate TCP / fluent from lading, allow the `http_blackhole` to respond with kinesis response bodies.  The `tcp_gen` configuration is, until otherwise stated:

```toml
worker_threads = 2
prometheus_addr = "0.0.0.0:9003"

[targets.simple]
addr = "0.0.0.0:24225"
variant = "Fluent"
bytes_per_second = "500 Mb"
maximum_prebuild_cache_size_bytes = "1 Gb"
```

We run `tcp_gen` like so:

```
>  firejail --rlimit-as=8g --cpu=11,12 --noprofile ./target/release/tcp_gen --config-path configs/tcp_gen.toml
```

The `http_blackhole` command string is, until otherwise stated:

```
> firejail --rlimit-as=2g  --noprofile ./target/release/http_blackhole --worker-threads 16 --concurrent-requests-max 512 --binding-addr "0.0.0.0:8080" --prometheus-addr "0.0.0.0:9002" --body-variant kinesis
```

Altering the kinesis sink to 

```toml
[sinks.firehose-sink]
type = "aws_kinesis_firehose"
inputs = [ "remap" ]
stream_name = "LT-SplunkFirehosePOC-NOLAMBDA"
endpoint = "http://localhost:8080/"
healthcheck.enabled = false
compression = "none"
encoding = "json"
```

allows vector to target the local blackhole rather than external AWS kinesis. We find:

| SHA | `tcp_gen` generation Mb/s | `aws_kinesis_firehose` bytes processed Mb/s | `http_blackhole` receipt Mb/s |
| ------ | ------------------------------------ | -------------------------------------------------- | --------------------------------------- |
|  32e8f8fab6be121e4c2b85e22d54dd1c4f705ce8 | 53.2 | n/a | 37.5 |

The kinesis sink does not appear to instrument the ` ﻿vector_processed_bytes_total`. As we control both sides of the rig we can see incoming versus outgoing throughput well enough. Note that the drop here is expected considering the configured transform. Vector's inbound capacity on the measurement system against a nearly do-nothing kinesis target is just north of 50Mb/s.

**Comment by blt** [comment]
Of note if I remove the remap step in the middle of the pipeline ingress throughput does not change, though output throughput naturally rises. This suggests that remap here is not a primary bottleneck.

**Comment by blt** [comment]
If I directly pipe `fluent` into the blackhole _sink_ inbound throughput is 79Mb/s, suggesting that we lose 26Mb/s going into the `remap -> kinesis` stage of the configuration given above.

**Comment by blt** [comment]
Consider this vector configuration:

```toml
data_dir = "/tmp/data/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.fluent]
type = "fluent"
address = "0.0.0.0:24225"

##
## Sinks
##

[sinks.blackhole]
type = "blackhole"
inputs = ["fluent"]
print_amount = 100000

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"
```

This drops fluent directly into the blackhole. If we spin up our experiment and run vector under perf we find that the top function call with 14% of cycles is `core::unicode::printable::check`, driven by:

![Screenshot from 2021-08-05 16-12-28](https://user-images.githubusercontent.com/3579/128432889-271590f9-b530-44ba-aac5-a5ee84f4c32c.png)

We presently coerce messagepack map keys through `format!`:

https://github.com/timberio/vector/blob/32e8f8fab6be121e4c2b85e22d54dd1c4f705ce8/src/sources/fluent.rs#L426-L431

Unfortunately the `Display` implementation for `rmpv::Value` is marked as cold:

https://github.com/3Hren/msgpack-rust/blob/5bf2c24203ad422233cf35b7b7bfad9f7e811814/rmpv/src/lib.rs#L1185-L1229

We are repeatedly calling a cold function in our hot path.
