### ISSUE TITLE
`log_to_metric` documentation gives incorrect syntax

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#8753]
Consider that our present documentation gives the following as an example of how to configure the transform [here](https://vector.dev/docs/reference/configuration/transforms/log_to_metric/):

```toml
[transforms.my_transform_id]
type = "log_to_metric"
inputs = [ "my-source-or-transform-id" ]

  [transforms.my_transform_id.metrics]
  field = "duration"
  name = "duration_total"
  namespace = "service"
  type = "counter"

    [transforms.my_transform_id.metrics.tags]
    host = "${HOSTNAME}"
    region = "us-east-1"
    status = "{{status}}"
```

The inner map is missing a set of brackets.
