### ISSUE TITLE
"$"  character is not escaped properly in paths

### ISSUE THREAD

**Issue by anas-aso** [vectordotdev/vector#8886]
### Vector Version

```
vector 0.15.1 (x86_64-unknown-linux-gnu c5e4732 2021-07-27)
```

### Vector Configuration File

```yaml
myTramsform:
    type: remap
    inputs:
      - somewhere
    source: |-
      . = parse_json!(.)
      .timestamp = del(.t."$date")
```

### Expected Behavior
Considering the VRL above, if I passed this event to it 
```json
{"s":"I","t":{"$date":"2021-08-25T22:14:26.557+00:00"}}
```
I expect to get 
```json
{"s":"I","timestamp":"2021-08-25T22:14:26.557+00:00"}
```

### Actual Behavior
Instead, I get this 
```json
{"s":"I","t":{"$date":"2021-08-25T22:14:26.557+00:00"},"timestamp":null}
```
The path `.t."$date"` fails to resolve silently, as a result the `.timestamp` field is set to `null`
