### ISSUE TITLE
vector v2 sink sets the default address scheme to http while tls is enabled

### ISSUE THREAD

**Issue by cnkk** [vectordotdev/vector#8898]
### Vector Version

```
vector 0.16.0 (x86_64-unknown-linux-gnu 9e4174d 2021-08-25)
```

### Vector Configuration File

```toml
[sinks.vector]
type = "vector"
version = "2"
inputs = [ "input" ]
address = "log-collector:5000"
  [sinks.vector.tls]
  enabled = true

  [sinks.vector.healthcheck]
  enabled = false
```

### Expected Behavior

Logs should be sent to the given address `log-collector:5000` which has a vector source configured and also has tls enabled.
This worked with the previous version `v0.15.2`

### Actual Behavior

Logs are not accepted by the destination server and are also send in plain.
It looks like that it does not even start a tls connection.

### Additional Context

I looked into the code and found the [comment](https://github.com/timberio/vector/blob/f71427e9cd5ca7fddafb903208ddf17b3f1adf72/src/sinks/vector/v2.rs#L53-L54) which helped.
After setting the scheme to https the sink was able to send logs to the log-collector:
```toml
address = "https://log-collector:5000"
````

I think we should either document this or set the scheme to https automatically when tls is enabled.
