### ISSUE TITLE
Missing open_connections output for internal_metrics when using vector v2 source

### ISSUE THREAD

**Issue by cnkk** [vectordotdev/vector#8903]
### Vector Version

```
vector 0.16.0 (x86_64-unknown-linux-gnu 9e4174d 2021-08-25)
```

### Vector Configuration File

```toml
[sources.vector]
type = "vector"
version = "2"
address = "0.0.0.0:5000"

  [sources.vector.tls]
  enabled = true
  crt_file = "/etc/ssl/services/cert.pem"
  key_file = "/etc/ssl/private/key.pem"

[sinks.file]
type = "file"
inputs = [ "vector" ]
compression = "none"

path = "/var/log/log.log"
encoding.codec = "text"

[sinks.prometheus_exporter]
type = "prometheus_exporter"
inputs = ["vector_metrics"]
address = "0.0.0.0:9598"
default_namespace = "service"

[sources.vector_metrics]
type = "internal_metrics"
```

### Expected Behavior

The number of current open connections(`open_connections`) to Vector should be shown when browsing `http://localhost:9598/metrics` 

### Actual Behavior

The metric `open_connections` does not change from `0` although there are connected hosts.

### Additional Context

This does not work with the v2 of the vector source.
When using the v1 vector source, the metric for `open_connections` is displayed correctly.
