### ISSUE TITLE
 YAML examples shows null for maps like healthcheck and encoding

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#8909]
https://vector.dev/docs/reference/configuration/sinks/datadog_logs/

```yaml
---
sinks:
  my_sink_id:
    type: datadog_logs
    inputs: my-source-or-transform-id
    default_api_key: ${DATADOG_API_KEY_ENV_VAR}
    compression: gzip
    encoding: null
    healthcheck: null
```
