### ISSUE TITLE
Provide built-in field-based routing

### ISSUE THREAD

**Issue by lucperkins** [vectordotdev/vector#8943]
Enabling users to specify Boolean conditions for routing using [Vector Remap Language](https://vrl.dev) was, in my estimation, a major improvement over the previous configuration-driven system. But while VRL is quite handy for more fine-grained routing cases—e.g. "route `bopper` is for all logs where the value of `.field1` is `"foo"` and the value of `.field2` is 427"—I wonder if it's maybe overkill for simpler use cases. One example I have in mind is routing based on tags. Here's an example configuration:

```toml
[transforms.route_by_tag]
type = "route"

[transforms.route_by_tag.route]
one = '.tag == "one"'
two = '.tag == "two"'
three = '.tag == "three"'
four = '.tag == "four"'
five = '.tag == "five"'
six = '.tag == "six"'
```

And so on. In this case you essentially want the value of a field to serve as the routing criterion. Imagine if you could do this instead:

```toml
[transforms.route_by_tag]
type = "route"
field = "tag"

# or nested fields
field = "user.metadata.subscription_type"
```

In this case, a route is created for each encountered value of `.tag`. That could have its own problems (unchecked route proliferation comes to mind) but I think the approach is worth considering.
