### ISSUE TITLE
enabled the memory buffer causes high memory usage

### ISSUE THREAD

**Issue by wgb1990** [vectordotdev/vector#8998]
### Vector Version

```
0.16.1
```

### Vector Configuration File

```toml
[api]
enabled = true
address = "0.0.0.0:8686"

[sources]

  [sources.metrics]
  type = "internal_metrics"
  scrape_interval_secs = 2.0

  [sources.apps_log]
  type = "kafka"
  bootstrap_servers = ""
  group_id = "dw-log-forward-vector-gid"
  topics = [
    "dw-log-forward"
  ]

[transforms]

  [transforms.remap_message]
  type = "remap"
  inputs = [
    "apps_log"
  ]
  source = ". = parse_json!(string!(.message))\n.eventTime = to_int!(.timestamp)\n"

  [transforms.output_loki]
  type = "remap"
  inputs = [
    "remap_message"
  ]
  source = ".aggregator = get_env_var!(\"POD_NAME\")\ndel(.domain)\ndel(.eventTime)\n"

  [transforms.output]
  type = "route"
  inputs = [
    "remap_message"
  ]

    [transforms.output.route]
    java_gc_log = ".collectorType == \"gc\""
    java_error_log = ".level == \"ERROR\""

[sinks]

  [sinks.prometheus_exporter]
  type = "prometheus_exporter"
  inputs = [
    "metrics"
  ]
  address = "0.0.0.0:9598"
  default_namespace = "service"

  [sinks.kafka_gc]
  type = "kafka"
  inputs = [
    "output.java_gc_log"
  ]
  bootstrap_servers = ""
  compression = "gzip"
  topic = "java_gc_log"

    [sinks.kafka_gc.encoding]
    codec = "json"
    timestamp = "unix"

    [sinks.kafka_gc.healthcheck]
    enabled = true

  [sinks.kafka_error]
  type = "kafka"
  inputs = [
    "output.java_error_log"
  ]
  bootstrap_servers = ""
  compression = "gzip"
  topic = "exception_log_prd"

    [sinks.kafka_error.encoding]
    codec = "json"
    timestamp = "unix"

    [sinks.kafka_error.healthcheck]
    enabled = true

  [sinks.loki]
  type = "loki"
  inputs = [
    "output_loki"
  ]
  endpoint = ""
  tenant_id = "{{ tenantId }}"
  remove_label_fields = true
  out_of_order_action = "rewrite_timestamp"

    [sinks.loki.batch]
    max_bytes = 30490000
    max_events = 7000
    timeout_secs = 1

    [sinks.loki.buffer]
    type = "memory"
    max_events = 10240000

    [sinks.loki.request]
    concurrency = 10240000

    [sinks.loki.labels]
    service = "{{ service }}"
    hostname = "{{ hostname }}"
    level = "{{ level }}"
    collectorType = "{{ collectorType }}"
    aggregator = "{{ aggregator }}"

    [sinks.loki.encoding]
    codec = "json"
    timestamp_format = "rfc3339"

    [sinks.loki.healthcheck]
    enabled = true
```

### Expected Behavior
memory consumption is within the normal range, and events can be sent to Loki storage normally

### Actual Behavior
events accumulate in the buffer and eventually cause the pod to run out of memory and restart

### Example Data
Vector I play the role of aggregator and have three nodes to process about 6000 events per second

### Additional INFO

memory begins to grow at some point. It should be that the memory buffer accumulates a large number of events, which eventually causes Loki to stop sending.
![image](https://user-images.githubusercontent.com/7124162/131774194-d1fb8097-8110-449e-87e4-8691ef14eec8.png)

![image](https://user-images.githubusercontent.com/7124162/131774687-35ef19f6-fb33-4f79-91e2-edc81ac7757d.png)
