### ISSUE TITLE
Support Clickhouse's TCP interface

### ISSUE THREAD

**Issue by seanjoe** [vectordotdev/vector#9000]
### Vector Version

```
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
```

### Vector Configuration File

```toml
[sources.kfk_in]
type = "kafka"
bootstrap_servers = "10.1.0.17:9092"
group_id = "vector"
topics = [ "CVAPI-SIT" ]

[sinks.click]
  type = "clickhouse"
  inputs = [ "kfk_in" ]
  database = "mydatabase"
  endpoint = "tcp://10.xx.xx.xx:9000"
  table = "vector_test"
  compression = "gzip"

[sinks.out]
    inputs = ["kfk_in"]
    type = "console"
    encoding = "text"
```

### Expected Behavior
ok, http or tcp 

### Actual Behavior

vector::topology::builder: msg="Healthcheck: Failed Reason." error=Unexpected status: 400 Bad Request component_kind="sink" component_type="clickhouse"
