### ISSUE TITLE
Unexpected memory growth with end-to-end acknowledgements enabled

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#9113]
### Vector Version

Current master

### Vector Configuration File

```yaml
sources:
  kafka_in:
    type: kafka
    acknowledgements: true
    auto_offset_reset: largest
    bootstrap_servers: localhost:9092
    group_id: foo-$RANDOM
    topics:
      - events
  vector-metrics:
    type: internal_metrics
    scrape_interval_secs: 2
transforms:
  # Drop the timestamp so the prometheus metric is as of "now" and not the
  # timestamp on the message.
  ts_to_now:
    type: remap
    inputs:
      - kafka_in
    source: |-
      .timestamp = now()
  kafka_offset_metric:
    type: log_to_metric
    inputs:
      - ts_to_now
    metrics:
      - field: offset
        name: last_offset
        namespace: vec_kafka_client
        tags:
          partition: "{{partition}}"
          topic: "{{topic}}"
        type: counter
sinks:
  prom:
    type: prometheus_exporter
    inputs:
      - vector-metrics
      - kafka_offset_metric
    address: 0.0.0.0:9500
```

### Expected Behavior

Flat memory use, as is seen when the `acknowledgements` flag is not set.

### Actual Behavior

![consumed](https://user-images.githubusercontent.com/333505/132928280-dbd783c0-6afd-4774-a58e-38c6f897c4a1.png)

![flame](https://user-images.githubusercontent.com/333505/132928284-2c27025e-9cf0-43b7-9b19-25f62d22b126.png)

Something within `run_finalizer` seems to be accumulating data in a `BinaryHeap`, but I'm not sure exactly where. We don't use one explicitly anywhere I can find in Vector, and most of the `rdkafka` calls seem to proxy pretty directly to `librdkafka`.

The finalizer passed by the `kafka` source is here:

https://github.com/timberio/vector/blob/6b06da49831ac7686ed00a83b25c43ba187ac8ae/src/sources/kafka.rs#L255-L266
