### ISSUE TITLE
`datadog_agent` source doesn't respect `log_schema` config

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#9159]
### Vector Version

```
version="0.16.1" arch="x86_64" build_id="739e878 2021-08-26"
```

### Vector Configuration File

```yaml
  api:
    enabled: true
    address: 0.0.0.0:8686
  sources:
    datadog_agents:
      type: datadog_agent
      acknowledgements: true
      address: 0.0.0.0:8080
    internal_metrics:
      type: internal_metrics
  transforms:
    remap:
      type: remap
      inputs:
        - datadog_agents
      source: |
        .ddtags = parse_key_value!(.ddtags, key_value_delimiter: ":", field_delimiter: ",")
        .ddtags.sender = "vector"
        .ddtags.vector_aggregator = get_hostname!()
        .ddtags = encode_key_value(.ddtags, key_value_delimiter: ":", field_delimiter: ",")

        parsed =
          parse_json(.message) ??
          parse_syslog(.message) ??
          {}
        . = merge(., object!(parsed))
```

### Expected Behavior

All logs should have the fields defined by `log_schema`'s defaults: `host`, `message`, `source_type`, `timestamp`

### Actual Behavior

Logs coming out of the `datadog_agent` source appear to be missing `host` and just using `hostname` from the datadog payload.

```json
{
  "ddsource": "flog",
  "ddtags": "container_id:a9ec4a1fda8ac79d1ae900149099b70115474d350a1e4199ec610129ec68f1c2,container_name:k8s_flog-syslog_flog-syslog_default_efee244c-b841-44c5-a656-adb0461c8e1a_0,dirname:/var/log/pods/default_flog-syslog_efee244c-b841-44c5-a656-adb0461c8e1a/flog-syslog,display_container_name:flog-syslog_flog-syslog,docker_image:mingrammer/flog:latest,filename:0.log,image_name:mingrammer/flog,image_tag:latest,kube_container_name:flog-syslog,kube_namespace:default,pod_name:flog-syslog,pod_phase:running,sender:vector,short_image:flog,vector_aggregator:vector-78749b54cb-qqcrx",
  "hostname": "i-02faa07041610f38c",
  "message": "<35>2 2021-09-15T17:19:17.979Z internalrelationships.name sunt 7276 ID668 - You can't navigate the monitor without bypassing the 1080p PCI bus!",
  "service": "flog",
  "source_type": "datadog_agent",
  "status": "info",
  "timestamp": 1631726368142
}
```
