### ISSUE TITLE
Vector high memory usage / memory leak

### ISSUE THREAD

**Issue by sdryga** [vectordotdev/vector#9207]
### Vector Version

```
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
```

### Vector Configuration File

```toml
data_dir = "/var/lib/vector"
healthchecks.enabled = true
healthchecks.require_healthy = false

[api]
  enabled = true
  address = "127.0.0.1:8686"

[sources.in_docker_logs]
  type = "docker_logs"
  docker_host = "/var/run/docker.sock"
  auto_partial_merge = true
  retry_backoff_secs = 1
  multiline.mode = "halt_before"
  multiline.start_pattern = "^\\d{4}-\\d{2}-\\d{2}[\\t\\v ]\\d{2}:\\d{2}:\\d{2},\\d{3}[\\t\\v ]\\S+"
  multiline.condition_pattern = "^\\d{4}-\\d{2}-\\d{2}[\\t\\v ]\\d{2}:\\d{2}:\\d{2},\\d{3}[\\t\\v ]\\S+"
  multiline.timeout_ms = 500

[sinks.out_vector]
  type = "vector"
  inputs = ["in_docker_logs"]
  address = "1.2.3.4:8080"
  buffer.type = "disk"
  buffer.max_size = 10_000_000_000
  buffer.when_full = "block"
  version = "2"

[sources.in_vector_metrics]
  type = "internal_metrics"
  scrape_interval_secs = 15

[sinks.out_prometheus_exporter]
  type = "prometheus_exporter"
  inputs = [ "in_vector_metrics" ]
  address = "0.0.0.0:8687"
  default_namespace = "service"
  flush_period_secs = 60
```

On vector sink side "acknowledgements" is set to "false".
```
[sources.in_vector]
  type = "vector"
  address = "0.0.0.0:8080"
  acknowledgements = false
  shutdown_timeout_secs = 10
  version = "2"
```

### Expected Behavior

Expected that vector memory consumption will be less then 2GB.

### Actual Behavior

Vector consumes more then 10GB of the RAM.

![vector_top](https://user-images.githubusercontent.com/47857056/133736260-5a672036-0f3a-4728-912e-25a87f635a19.png)

### Additional Context

Top by threads:

![vector_top_H](https://user-images.githubusercontent.com/47857056/133736484-d071c0e5-2321-445c-b18b-6aa79b6a42aa.png)

Vector utilization:

![vector_utilization](https://user-images.githubusercontent.com/47857056/133736835-14926039-8a09-47a5-a9c4-ddc2eebffd16.png)

Rate of the out-events emitted by the vector sink component:

![vector_out_event_rate](https://user-images.githubusercontent.com/47857056/133736964-bcde2cd2-5e0c-4952-806a-51402158fc62.png)

Vector buffers:
```
du -h --max-depth=2 /var/lib/vector/
1.1G    /var/lib/vector/out_vector_buffer
1.1G    /var/lib/vector/
```
```
ls -lha /var/lib/vector/out_vector_buffer/
total 1.1G
drwxr-xr-x 2 vector vector  197 Sep 17 09:46 .
drwxr-xr-x 3 vector root     31 Sep 10 16:23 ..
-rw-r--r-- 1 vector vector 2.1M Sep 17 09:46 4114847.ldb
-rw-r--r-- 1 vector vector 2.1M Sep 17 09:46 4114848.ldb
-rw-r--r-- 1 vector vector 6.8K Sep 17 09:46 4114849.ldb
-rw-r--r-- 1 vector vector 3.5M Sep 17 09:46 4114850.log
-rw-r--r-- 1 vector vector 4.0M Sep 17 09:46 4114851.ldb
-rw-r--r-- 1 vector vector 2.1M Sep 17 09:46 4114852.ldb
-rw-r--r-- 1 vector vector   17 Sep 10 16:23 CURRENT
-rw-r--r-- 1 vector vector    0 Sep  6 13:05 LOCK
-rw-r--r-- 1 vector vector 637M Sep 17 09:46 LOG
-rw-r--r-- 1 vector vector  357 Sep 10 16:23 LOG.old
-rw-r--r-- 1 vector vector 160M Sep 17 09:46 MANIFEST-1202143
```
Vector uptime ~7 days (since Fri 2021-09-10 16:23:51 EEST).
