### ISSUE TITLE
Data lag during traffic spikes

### ISSUE THREAD

**Issue by pm5** [vectordotdev/vector#9229]
(This is not really a bug per se but some observations to the performance of Vector during traffic spikes.  Our own use case does require Vector to catch up with sudden big traffic as soon as possible so I'm filing this issue with some details of our experiments in hope for some advice.)

### Vector Version

```
vector 0.16.0 (x86_64-unknown-linux-gnu 9e4174d 2021-08-25)
```

### Vector Configuration File

```toml
[sources.kafka_data]
type = "kafka"
bootstrap_servers = "...,...,..."
group_id = "vector"
sasl.enabled = true
sasl.mechanism = "..."
sasl.password = "..."
sasl.username = "..."
tls.enabled = true
tls.ca_file = "..."
topics = ["^data.*"]
auto_offset_reset = "largest"
key_field = "message_key"
topic_key = "topic"
partition_key = "partition"
offset_key = "offset"
headers_key = "headers"
```

### Expected Behavior

I'm using Vector to consume from Kafka.  Normally the data stream would have about 500k msg/minute from about 200 Kafka topics, each has 10 partitions, and Vector is handling that pretty well.  However, we expect we would occasionally get a 10x-15x spike of messages, and we want Vector to catch up on those as soon as possible (hopefully no more than 10 seconds).  Any suggestions on how we might achieve that?

The pipeline I'm working on consists of Kafka->Vector->ClickHouse.  I've been tweaking Vector configurations while monitoring the time difference between a Kafka message was created and when it arrived at Vector.  I can sort of simulate the traffic spikes by stopping Vector for a few seconds, let the Kafka messages accumulate, and then restart Vector.

For a steady stream of 8k-10k msg/sec, that time lag is usually 0.5 to 1 sec.  After restarting Vector the time lag will of course go up immediately.  I'd hope I can get the time lag back to under 1 sec within a 10 second period of time after we see spikes.

### Actual Behavior

In one of the tests, I stopped Vector for 60 seconds, built up a reservoir of about 500k-600k messages, and started Vector again to see how fast can it get the delay back to normal range.  It took about 100 seconds, which theoretically translates to a maximum consumption rate of 16k msg/sec.  I'm looking for advices to raise that max rate, given that occasional spike traffic is anticipated.

There were still a lot of CPU and memory to use, and the network wasn't saturated either during that time.
