### ISSUE TITLE
vector gets stuck, doesn't forward logs from kafka to loki anymore after a while and can't be stopped unless kill -9

### ISSUE THREAD

**Issue by SLoeuillet** [vectordotdev/vector#9251]
### Vector Version

vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
vector 0.17.0 (x86_64-unknown-linux-gnu 5339525 2021-09-20) <= same with nighly

### Vector Configuration File

```
---
sinks:
  loki_sink:
    encoding:
      codec: "json"
    endpoint: "http://loki.logs.ovh.int.kaiko.com:3100"
    inputs: ["loki_parse_message"]
    type: loki
    out_of_order_action: rewrite_timestamp
    labels:
      go_version: "{{ kfk_attr.src_attr_json.go_version }}"
      host: "{{ kfk_attr.host }}"
      image: "{{ kfk_attr.image }}"
      level: "{{ kfk_attr.src_attr_json.level }}"
      name: "{{ kfk_attr.src_attr_json.name }}"
      pkg_source: "{{ kfk_attr.src_attr_json.source }}"
      source_type: "{{ kfk_attr.source_type }}"
      syslog_facility: "{{ kfk_attr.SYSLOG_FACILITY }}"
      syslog_id: "{{ kfk_attr.SYSLOG_IDENTIFIER }}"
      syslog_priority: "{{ kfk_attr.PRIORITY }}"
      version: "{{ kfk_attr.src_attr_json.version }}"

sources:
  loki_kafka_src:
    bootstrap_servers: "kafka00.logs.ovh.int.kaiko.com,kafka01.logs.ovh.int.kaiko.com"
    group_id: "vector_log_consumer"
    topics: ["logs_docker"]
    type: kafka

transforms:
  loki_parse_message:
    inputs: ["loki_kafka_src"]
    type: remap
    source: |
      .kfk_attr,err = parse_json(string!(.message))
      if err == null
      {
        del(.message)
      } else {
        del(.kfk_attr)
      }
      del(.message_key)
      del(.offset)
      del(.partition)
      del(.source_type)
      del(.topic)
      del(.ts)
      del(.tsNs)

api:
  enabled: true

sinks:
  prometheus:
    address: "127.0.0.1:9598"
    inputs: ["internal"]
    type: "prometheus_exporter"

sources:
  internal:
    type: "internal_metrics"
```

### Debug Output

Would try to run vector in full debug mode once I have tested 0.17.0 nightly doesn't fix my issue

### Expected Behavior

Kafka to Loki log streaming never ends

### Actual Behavior

After a while, no more logs flowing

### Additional Context

Ubuntu 20.04 on bare-metal
remote kafka node using v2.8.0 as source
local loki v2.3.0 as sink
Logs coming from docker, containers running Go code mainly, hashicorp nomad as scheduler
