### ISSUE TITLE
Ability to extract schema agnostic values from events (service, level, host, etc.)

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9256]
The ability to extract schema agnostic values from events unlocks powerful use cases. For example, the ability for a user to route events based on the origin service, regardless of where that value lives. This could  be exposed through simple `get_*` VRL methods:

```toml
[transforms.route]
type = "route"
routes.api = "get_service() == 'api'"
```

This is dependent on the upcoming schema work, and the end result is no different than translating an arbitrary schema to a known schema.
