### ISSUE TITLE
Rename all condition fields to `condition`

### ISSUE THREAD

**Issue by lucperkins** [vectordotdev/vector#9303]
I've notified that in our unit testing suite, you specify an `ends_when` condition using a `source` field, e.g.:

```toml
[transforms.my_transform.ends_when]
type = "vrl"
source = "exists(.some_field)
```

I think it'd be more intuitive to use `condition` and thereby bring unit testing in line with the `route` and `filter` transforms. This is the only place I've seen this but there may be others, and I'd recommend updating all of them.
