### ISSUE TITLE
Random crash with Syslog to Loki

### ISSUE THREAD

**Issue by agrosjea** [vectordotdev/vector#9320]
### Vector Version
0.16.1
runned from docker container
timberio/vector:latest-alpine@sha256:1f51e653aae335073c4d1337acbbe16e9f32b4bde837762886854d1121f94f9a

### Vector Configuration File

```toml
[sources.in]
  type = "syslog" # required
  address = "0.0.0.0:1514" # required, required when mode = "tcp" or mode = "udp"
  mode = "udp" # required

[sinks.out]
  # General
  type = "loki" # required
  inputs = ["in"] # required
  endpoint = "http://localhost:3100" # required
  encoding = "json"

  # Labels
  labels.vector = "arnaud" # example
  labels.vectorHost = "{{ host }}" # example
```

### Debug Output

```
Starting vector_514 ... done
Attaching to vector_514
vector_514 | Sep 23 16:35:40.888  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info" enable_datadog_tracing=false
vector_514 | Sep 23 16:35:40.912  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
vector_514 | Sep 23 16:35:41.260  INFO vector::topology::running: Running healthchecks.
vector_514 | Sep 23 16:35:41.267  INFO vector::topology::running: Starting source. id=in
vector_514 | Sep 23 16:35:41.271  INFO vector::topology::running: Starting sink. id=out
vector_514 | Sep 23 16:35:41.276  INFO vector: Vector has started. debug="false" version="0.16.1" arch="x86_64" build_id="739e878 2021-08-26"
vector_514 | Sep 23 16:35:41.276  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
vector_514 | Sep 23 16:35:41.301  INFO source{component_kind="source" component_id=in component_type=syslog component_name=in}: vector::sources::syslog: Listening. addr=0.0.0.0:1514 type="udp"
vector_514 | Sep 23 16:35:41.438  INFO vector::topology::builder: Healthcheck: Passed.
vector_514 | Sep 23 16:43:27.419  WARN sink{component_id=out component_kind="sink" component_type=loki component_name=out}: vector::sinks::util::buffer::loki: msg="Received out-of-order event; dropping event." internal_log_rate_secs=30
vector_514 | thread 'vector-worker' panicked at 'Batch is empty', src/sinks/util/buffer/loki.rs:233:46
vector_514 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
vector_514 | Sep 23 16:43:28.473 ERROR sink{component_id=out component_kind="sink" component_type=loki component_name=out}: vector::topology: An error occurred that vector couldn't handle.
vector_514 | Sep 23 16:43:28.480  INFO vector: Vector has stopped.
vector_514 | Sep 23 16:43:28.487  INFO source{component_kind="source" component_id=in component_type=syslog component_name=in}: vector::sources::syslog: Finished sending.
vector_514 | Sep 23 16:43:28.492  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="in, out" time_remaining="59 seconds left"
vector_514 exited with code 0
```

### Expected Behavior

Even if syslog input is badly formatted, Vector shouldn't crash and just ignore...

### Actual Behavior

It crashes !

### Example Data

```
<128>Sep 23 12:54:57 PC-AAA NODE-RED[0]: This is a extended NEWLOG from NR
```
