### ISSUE TITLE
Make `vector` less opinionated: allow customization of the "shape" of expected/outputted events for "generic" sources/sinks

### ISSUE THREAD

**Issue by midnightexigent** [vectordotdev/vector#9347]
### Current Vector Version

`0.16.1` 

### Use-cases

What I call "generic" sources/sinks here are sources/sinks that do not impose any restrictions on the data-format (`http`, `s3`, `file`, `kafka`, etc.), the main example that will be used here is `kafka` because this feature request was initially motivated by #5809

First some examples: 

- `vector` expects that events read from sources like `kafka` are logs, what if they are something else ? 
- `vector` uses its internal format to write events to sinks like `kafka`, what if we don't want that ? 

Currently, for "generic" sinks/sources (eg. `kafka`, `file`, etc.), vector makes the assumption on what sort of events (logs/metrics) will be read from the sources, and uses its internal format to write to the sinks. That behavior is opinionated and results in cases such as [comment](https://github.com/vectordotdev/vector/issues/5809#issuecomment-754013510) where `vector` can't read the metrics it wrote in kafka. 

### Attempted Solutions

For sources: accepting the events as logs and doing some sort of transformation (eg. `vrl`) that puts them in the right shape works for some cases, but is kind of awkward

For sinks: no solution available

### Proposal

This proposal attempts to solve initial issue where metrics written in `kafka` as metrics by taking a general approach and making `vector` less opinionated.  

Add a parameter (let's call it `shape` for now) that describes the format of the data and its mapping with a `vector` event type. That parameter can be set in a `sink` or `source` definition and `vector` can use it to map the foreign data into one of the internal event types (log/metric). This parameter only makes sense for generic sources/sinks 

The best thing is that this seems like a generalization of what is already implemented: let's say for now that this `shape` attribute is an enum where each variant is the name of a known data format:
```toml
[sources.kafka]
type = "kafka"
expected_shape = "vector_logs | vector_metrics | prometheus_remote_write | syslog | etc."
``` 

Then,

```toml
[sources.prom_remote_write]
type = "prometheus_remote_write"
``` 

Would be a shortcut for

```toml
[sources.prom_remote_write]
type = "http"
expected_shape = "prometheus_remote_write"
``` 

Furthermore, a "super" generalization would allow the definition of a `shape` where `shape` is a data-structure that contains all of the necessary information required to map a foreign object into a `vector` event. Example for illustrative purposes 

```toml
[sources.bar]
expected_shape.encoding="json | protobuf | text | prometheus | etc." 
expected_shape.compression="gzip | snappy | etc."
expected_shape.maps_into="metric | log"
```

Now, the named shapes mentioned earlier become shortcuts for some predefined complete shapes. Example: 

```toml
[sources.bar]
expected_shape = "prometheus_remote_write"
```

is a shortcut for

```toml
[sources.bar]
expected_shape.encoding="protobuf"
expected_shape.compression="snappy"
expected_shape.maps_into="metric"
```

Going even further with this "super" generalization, users could define their own named shapes and reference them in multiple places. And the way the value is mapped could be defined by the user via templates or even `vrl`. 

But I digress, the "super" generalization tangent apart, for a complete example, let's say we scraped metrics from prometheus, we want to write them into a `kafka` topic, and read them back as metrics

```toml 
# scrape metrics
[sources.promscrape] 
type = "prometheus_scrape"

 # write scraped metrics to kafka 
[sinks.kafka_out]
sources = ["promscrape"]
type = "kafka"
topic = "my_metrics"

# we can use whichever shape suits us the most, it just needs to match the shape expected by the consumer
shape = "vector_metrics"
# or
shape = "prometheus_remote_write" 

[sources.kafka_in]
type = "kafka"
topics = ["my_metrics"]

# we can use whichever shape suits us the most, it just needs to match the shape outputted by the producer
shape = "vector_metrics"
# or
shape = "prometheus_remote_write"
```
