### ISSUE TITLE
Seeing CloudwatchError::Put error in vector agent logs

### ISSUE THREAD

**Issue by roimor** [vectordotdev/vector#9382]
### Vector Version

```
vector-agent-0.16.1 (helm)
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
```

### Vector Configuration File

```yaml
sources:
  ***source:
    type: kubernetes_logs

transforms:
  ****-transform:
    type: filter
    inputs:
      - ***source
    condition: .kubernetes.pod_namespace != "kube-system" && .kubernetes.pod_namespace != "kube-node-lease" && .kubernetes.pod_namespace != "kube-public" && .kubernetes.pod_namespace != "***" && .kubernetes.pod_namespace != "****"

  ***-remap-transform:
    type: remap
    inputs:
      - ***-transform
    source: |-
      del(.file)
      del(.source_type)
      del(.stream)
      del(.kubernetes.container_id)
      del(.kubernetes.container_name)
      del(.kubernetes.pod_ips)
      del(.kubernetes.pod_labels)
      del(.kubernetes.pod_ips)
      del(.kubernetes.pod_node_name)
      del(.kubernetes.pod_uid)

sinks:
  ***-sink:
    type: aws_cloudwatch_logs
    inputs:
      - ****-remap-transform
    create_missing_group: true
    create_missing_stream: true
    group_name: ***-application-logs
    compression: none
    encoding:
      codec: json
      timestamp_format: rfc3339
    healthcheck:
      enabled: true
    region: ****
    stream_name: ***-log-stream

```

### Actual Behavior

```
Oct 04 15:20:32.929 ERROR sink{component_id=api-server-sink component_kind="sink" component_type=aws_cloudwatch_logs component_name=api-server-sink}:request{request_id=18358}: vector::sinks::util::retries: Non-retriable error; dropping the request. error=CloudwatchError::Put: The given sequenceToken is invalid. The next expected sequenceToken is: 49620414437706250368324943759940916345169566932641252466
```
