### ISSUE TITLE
Neither objects nor arrays can be provided as values for `log_fields` inputs in unit tests

### ISSUE THREAD

**Issue by lucperkins** [vectordotdev/vector#9386]
I've hit on what appears to be a bug in our unit testing suite. It seems that you can pass in nested objects as test inputs for metrics but not for logs. Intuitively, this unit test should pass:

```toml
[transforms.one]
type = "remap"
inputs = []
source = '''
.one = 1
'''

[[tests]]
name = "This should work"

[[tests.inputs]]
insert_at = "one"
type = "log"

[tests.inputs.log_fields]
two = 2
tags = { environment = "staging" } # Here's the nested object

[[tests.outputs]]
extract_from = "one"

[[tests.outputs.conditions]]
type = "vrl"
source = '''
assert_eq!(.one, 1)
assert_eq!(.two, 2)
assert_eq!(.tags.environment, "staging")
'''
```

Instead, it throws this error:

```error
data did not match any variant of untagged enum TestInputValue for key `tests.inputs.log_fields.tags` at line 22 column 1.
```

Changing the offending `tags` object to this also fails:

```toml
tags.environment = "staging"
```

This, however, works:

```toml
"tags.environment" = "staging"
```

I only figured this out by looking at some of our existing unit tests for Vector. I find this to be quite counterintuitive and would expect users to stumble on this. Meanwhile, nested objects seem to work fine in metric tests:

```toml
[transforms.add_tags]
type = "remap"
inputs = []
source = '''
.tags.environment = "staging"
'''

[[tests]]
name = "This should work"

[[tests.inputs]]
insert_at = "add_tags"
type = "metric"

[tests.inputs.metric]
name = "my_counter"
kind = "absolute"
tags = { host = "prod-server.com" }
counter = { value = 1 } # Here's the object

[[tests.outputs]]
extract_from = "add_tags"

[[tests.outputs.conditions]]
type = "vrl"
source = '''
assert_eq!(.name, "my_counter")
assert_eq!(.kind, "absolute")
assert_eq!(.tags.environment, "staging")
assert_eq!(.tags.host, "prod-server.com")
'''
```

I've also verified that this doesn't work in YAML:

```yaml
transforms:
  one:
    type: remap
    inputs: []
    source: ".one = 1"
tests:
- name: This should work
  inputs:
  - insert_at: one
    type: log
    log_fields:
      two: 2
      tags: # This doesn't work
        environment: staging
  outputs:
  - extract_from: one
    conditions:
    - type: vrl
      source: |
        assert_eq!(.one, 1)
        assert_eq!(.two, 2)
        assert_eq!(.tags.environment, "staging")
```

While changing the offending lines to `tags.environment: staging` fixes the issue.

The issue appears to be that the [`TestInputValue`](https://github.com/vectordotdev/vector/blob/master/src/config/mod.rs#L533-L540) enum can only handle strings, integers, floats, and Booleans. Indeed, arrays also don't work in `log_fields`:

```toml
[transforms.one]
type = "remap"
inputs = []
source = '''
.one = 1
'''

[[tests]]
name = "This should work"

[[tests.inputs]]
insert_at = "one"
type = "log"

[tests.inputs.log_fields]
two = 2
things = [] # Here's the array

[[tests.outputs]]
extract_from = "one"

[[tests.outputs.conditions]]
type = "vrl"
source = '''
assert_eq!(.one, 1)
assert_eq!(.two, 2)
assert_eq!(length(.things), 0)
'''
```

The corresponding error:

```
data did not match any variant of untagged enum TestInputValue for key `tests.inputs.log_fields.things` at line 22 column 1.
```
