### ISSUE TITLE
Incomplete documentation for `log_to_metrics` `metrics` config

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9387]
The `metrics` documentation for the `log_to_metrics` component seems incomplete:

<img width="723" alt="Screen Shot 2021-09-30 at 9 23 09 AM" src="https://user-images.githubusercontent.com/316880/135473615-cb882637-a5ee-4ceb-9ab9-b5273846d928.png">

https://vector.dev/docs/reference/configuration/transforms/log_to_metric/#metrics

The example shows what this value looks like:

```
[transforms.my_transform_id]
type = "log_to_metric"
inputs = [ "my-source-or-transform-id" ]

  [transforms.my_transform_id.metrics]
  field = "duration"
  name = "duration_total"
  namespace = "service"
  type = "counter"

    [transforms.my_transform_id.metrics.tags]
    host = "${HOSTNAME}"
    region = "us-east-1"
    status = "{{status}}"
```

**Comment by StephenWakely** [comment]
I believe the docs should also have `[[...]]` around the metrics section:

```toml
  [[transforms.my_transform_id.metrics]]
  field = "duration"
  name = "duration_total"
  namespace = "service"
  type = "counter"
```
