### ISSUE TITLE
Vector stopped processing events

### ISSUE THREAD

**Issue by ocrlgv** [vectordotdev/vector#9395]
$ vector --version
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)

I have 2 instances behind a loadbalancer, so metrics can be pushed from a host through LB to any of the 2 vector instances, prometheus then scrapes the [transforms.prometheus_scrape] endpoint and the data could be either up to date or old, depending on which vector instances receives the updates. I remove the tags prometheus adds regarding each vector (so metrics for any particular production system in a query shows up once, not once per vector) so when prometheus scrapes both.

my graphs started a few hours ago to become choppy which indicated stale data on one of the vector hosts, restarting the vector service on the host fixed it. No memory issues or logs from vector of problems at the time it stopped receiving data

My production systems being monitored showing missing or stale data causing queries to show less instances being up.
![Screen Shot 2021-10-01 at 10 01 02 am](https://user-images.githubusercontent.com/78460026/135546968-7c25760d-6d88-4ebe-b308-ea32b08829da.png)

vector before and after restarting one of the vector instances service
![Screen Shot 2021-10-01 at 10 04 49 am](https://user-images.githubusercontent.com/78460026/135547055-3f8419ef-88bf-484e-bcb6-a9fce61ae8a6.png)

this also pushes for some better health check system which I know there's an issue raise for it. could be tied to it for reference

**Comment by ocrlgv** [comment]
I believe the fix to this was to have prometheus remove the per instance tags so vector becomes transparent and not have it's instance tagged to each scrape. vector has it's own metrics sent so I don't need to identify any metric as to which job it came from. not sure if this was self inflicted but ended up placing this in prometheus and now things are running smooth and queries also don't double up due to 2 jobs when doing counts() etc

```
  # Vector ASG
  - job_name: edge_cluster
    relabel_configs:
      - action: labeldrop
        regex: "__meta_ec2_instance_id|__meta_ec2_ami|__meta_ec2_private_ip|instance"
    metric_relabel_configs:
      - action: labeldrop
        regex: ^instance$
    ec2_sd_configs:
      - region: ap-southeast-2
        port: 9100
```

so this can be closed.
