### ISSUE TITLE
VRL is_string function does not imply data type in filter transform

### ISSUE THREAD

**Issue by jeromekleinen-kbc** [vectordotdev/vector#9406]
### Vector Version

```
version="0.16.1" arch="x86_64" build_id="739e878 2021-08-26"
```

### Vector Configuration File

```toml
[sources.input]
  type = "stdin"

[transforms.filter]
  type = "filter"
  inputs = ["input"]
  condition = '''is_string(.message) && !contains(.message, s'test')'''

[sinks.output]
  type = "console"
  inputs = ["filter"]
  # Encoding
  encoding.codec = "text"
  encoding.only_fields = ["message"]
```

### Debug Output

```
Oct 01 15:36:09.986 ERROR vector::topology: Configuration error. error=Transform "filter":
error[E100]: unhandled error
  ┌─ :1:1
  │
1 │ is_string(.message) && !contains(.message, s'test')
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │ │
  │ expression can result in runtime error
  │ handle the error case to ensure runtime success
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = learn more about error code 100 at https://errors.vrl.dev/100
  = see language documentation at https://vrl.dev

```

### Expected Behavior

I believe this should work. The runtime error comes from the contains() function expecting .message to be a string.

### Actual Behavior

In order to make this work, you need to use f.e.

```toml
[sources.input]
  type = "stdin"

[transforms.filter]
  type = "filter"
  inputs = ["input"]
  condition = '''!contains(string!(.message), s'test')'''

[sinks.output]
  type = "console"
  inputs = ["filter"]
  # Encoding
  encoding.codec = "text"
  encoding.only_fields = ["message"]
```

However, my config is a minified example. I use several contains statements, and adding the string() function to all of them makes it harder to read, and is potentially wasteful if vector has to do the same check multiple times.
