### ISSUE TITLE
Incorrect permissions for syslog unix socket

### ISSUE THREAD

**Issue by reyjrar** [vectordotdev/vector#9456]
### Vector Version

```
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
```

### Vector Configuration File

```toml
[sources.syslog]
type = "syslog"
path = "/u/vector/syslog.sock"
mode = "unix_stream"
max_length = 20_000_000

[transforms.add_metadata]
type = "remap"
inputs = [ "syslog" ]
source = """
.labels.hostname = "example.com"
"""

[sinks.kafka_syslog]
type = "kafka"
inputs = [ "add_metadata" ]
compression = "none"
encoding = "json"
topic = "syslog"
bootstrap_servers = "bob:9092,alice:9092"
tls.enabled = true
tls.ca_file = "/etc/pki/ca-trust/source/anchors/example.crt"
```

### Debug Output

N/A

### Expected Behavior

Creation of `/u/vector/syslog.sock` with the same permissions as `/dev/log`:

```
$ ls -l /dev/log
srw-rw-rw-. 1 root root 0 2021-08-04 19:41 /dev/log=
```

### Actual Behavior

Creation of `/u/vector/syslog.sock` with permissions that make it impossible for anything to write to the socket:

```
$ ls -l /u/vector/syslog.sock
srwxr-xr-x. 1 vector vector 0 2021-10-01 21:13 /u/vector/syslog.sock=
```

### Example Data

N/A

### Additional Context

In order for things to write to the unix socket, they'll need write, not execute bits set on the socket.

### References

N/A

-->
