### ISSUE TITLE
Understand why Datadog logs soak has lost throughput telemetry 

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#9475]
In https://github.com/vectordotdev/vector/pull/8858/ we've introduced a component specification which closed https://github.com/vectordotdev/vector/issues/8709. Starting September 27 we've found that our soak performance tests for datadog log sink have lost underlying metrics sufficient to calculate bytes and event throughput. Though we do not document these as part of the external telemetry for the component we do rely on them in our work. 

We want to be sure that:

- [ ] vector still correctly emits telemetry sufficient to calculate throughput
- [ ] the soak testing infra is still capable of collecting it.

**Comment by blt** [comment]
The component spec dictates that `processed_bytes_total` -- which was ambiguous per #8709 -- is replaced by `component_sent_bytes_total`. This value is emitted but the current output is very small, roughly 3kb.

**Comment by blt** [comment]
After rigging up the following config locally and running with lading I can confirm that load through vector is very low. Cause is unknown at this time.

```toml
data_dir = "/tmp/data/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.datadog_agent]
type = "datadog_agent"
acknowledgements = false
address = "0.0.0.0:8282"

##
## Sinks
##

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"

[sinks.dd_logs_egress]
type = "datadog_logs"
inputs = ["datadog_agent"]
endpoint = "http://localhost:8080/v1/input"
default_api_key = "DEADBEEF"
healthcheck.enabled = false
```
