### ISSUE TITLE
Add HTTP 400 Bad request in prom metric -  vector_http_client_responses_total

### ISSUE THREAD

**Issue by isality** [vectordotdev/vector#9490]
Hi there,

Could you please, add HTTP 400 Bad request in prom metrics "vector_http_client_responses_total" for ElasticSearch Source?

### Current Vector Version

```bash
vector --version
vector 0.16.1 (x86_64-unknown-linux-musl 739e878 2021-08-26)
```

### Use-cases

It's can be use for creating alerts for Prometheus, when we have a mapping problem or Limit of total fields problem. 

For example:

```yaml
- alert: VectorAgentESBadRequest
  expr: sum(irate(vector_http_client_responses_total{component_type="elasticsearch", status="400 Bad request"}[10m])) by (pod) > 0
  for: 10m
  labels:
    severity: warning
  annotations:
    summary: "Vector-agent {{ $labels.pod }} got 400 http error when sincs logs in Elasticsearch"
```

Thanks!
