### ISSUE TITLE
decoding feature does not overwrite existing fields

### ISSUE THREAD

**Issue by jeromekleinen-kbc** [vectordotdev/vector#9557]
### Vector Version

```
vector 0.17.0 (x86_64-unknown-linux-gnu 3d34cde 2021-10-08)
```

### Vector Configuration File

```toml
[sources.stdin]
  type = "stdin"
  decoding.codec = "json"

[sinks.console]
  type = "console"
  inputs = ["stdin"]
  encoding.codec = "json"
```

and

```toml
[sources.stdin]
  type = "stdin"
  
[transforms.remap]
  type = "remap"
  inputs = ["stdin"]
  source = '. = parse_json!(.message)'

[sinks.console]
  type = "console"
  inputs = ["remap"]
  encoding.codec = "json"
```

### Debug Output

Consider the following input
```json
{"host": "a.b.c.d"}
```

### Expected Behavior

The `host` field of the resulting event should be the same.

### Actual Behavior

The first config yields:

```json
{"host":"actualhostnameofmymachine","source_type":"stdin","timestamp":"2021-10-11T09:45:00.475394282Z"}
```

The second config yields:

```json
{"host":"a.b.c.d"}
```

Using vrl's parse_json function, the existing host field gets overwritten. Using the new decoding feature this does not happen, and this behavior doesn't seem to be configurable.
