### ISSUE TITLE
`BytesCodec` emits frames that are split at unsuitable bounds

### ISSUE THREAD

**Issue by pablosichert** [vectordotdev/vector#9564]
### Vector Version

```
vector 0.17.0
```

### Vector Configuration File

```toml
[sources.input]
type = "kafka"
bootstrap_servers = "localhost:9091"
group_id = "consumer-group-name"
topics = ["foo"]
framing = { method = "bytes" }

[transforms.remap]
type = "remap"
inputs = ["input"]
source = '. = parse_json!(.message)'

[sinks.console]
inputs = ["remap"]
type = "console"
encoding = "json"
```

### Debug Output

When providing messages larger than 8kB to the `kafka` source in combination with the `bytes` framing, messages are split at the 8kB boundary.

Therefore, subsequent processing steps receive incomplete messages:

```
WARN transform{component_kind="transform" component_id=remap component_scope=global component_type=remap component_name=remap}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_json\" at (4:25): unable to parse json: EOF while parsing a string at line 1 column 8192" internal_log_rate_secs=30
```

This is undesirable, as the `bytes` framing should preserve the payload in message-based protocols.

### Expected Behavior

Source emits one event with >8kB message.

### Actual Behavior

Multiple events are emitted, where the payload is split at 8kB boundaries.

### References

https://discord.com/channels/742820443487993987/746070591097798688/897120565075279883

### Investigation

The `FrameReader` is not initialized with a suitable capacity in various sources, leading to messages being split at the default capacity of 8kB defined in https://github.com/tokio-rs/tokio/blob/f0cb360d7031313fb8bd74dc8a377da2de980df9/tokio-util/src/codec/framed_impl.rs#L27.
