### ISSUE TITLE
Write a RFC regarding automatic namespacing

### ISSUE THREAD

**Issue by jdrouet** [vectordotdev/vector#9568]
Write a RFC regarding automatic namespacing when loading configuration.

```toml
# /etc/vector/vector.toml
[sources.foo]
type = "anything"

[transforms.bar]
type = "anything"

[sinks.baz]
type = "anything"
```

Could be rewritten in several files

```toml
# /etc/vector/sources/foo.toml
type = "anything
```
 and the same for `transforms` and `sinks`.
