### ISSUE TITLE
Unit tests can't use VRL files for conditions

### ISSUE THREAD

**Issue by lucperkins** [vectordotdev/vector#9577]
Given how VRL files work in the `remap` transform, I'd expect that you'd be able to use a `.vrl` file to specify unit testing conditions:

```toml
[[tests.outputs.conditions]]
type = "vrl"
file = "my-long-list-of-conditions.vrl"
```

However, this is not currently supported. I'm not sure if users would expect this as well, but I'm not sure I can think of a principled reason to not provide this.
