### ISSUE TITLE
Kafka backwards offset reset when acknowledgments are enabled.

### ISSUE THREAD

**Issue by bvujanic** [vectordotdev/vector#9587]
### Vector Version

```
vector --version
vector 0.17.0 (x86_64-unknown-linux-gnu 3d34cde 2021-10-08)
```

### Vector Configuration File

```yaml
timezone: UTC
api:
  enabled: true
  address: 127.0.0.1:8686
sources:
  kafka_in:
    type: kafka
    acknowledgements: true
    auto_offset_reset: earliest
    commit_interval_ms: 1000
    bootstrap_servers: ${bootstrap_server}
    group_id: offset-reset-vector-test
    topics:
      - ${topic}
    librdkafka_options:
      'enable.auto.commit': 'true'
    tls:
      enabled: true
      ca_file: /etc/vector/kafka/ca.pem
      crt_file: /etc/vector/kafka/crt.pem
      key_file: /etc/vector/kafka/key.pem
  vector-metrics:
    type: internal_metrics
    scrape_interval_secs: 2
transforms:
  parse_json:
    type: remap
    inputs:
      - kafka_in
    source: |-
      . = parse_json!(.message)
sinks:
  prom:
    type: prometheus_exporter
    inputs:
      - vector-metrics
    address: 0.0.0.0:9500
  vector-sink:
    type: vector
    inputs:
      - parse_json
    address: http://vector_sink:9000/
    version: "2"
    batch:
      max_events: 6000
      timeout_secs: 5
    request:
      concurrency: "adaptive"
```

### Debug Output

N/A

### Expected Behavior

Kafka Offset should not reset and spike down when acknowledgments are enabled and when the number of vector kafka consumers in a kafka group scales down or up.

### Actual Behavior

Kafka Offset resets and goes backward, by an unexpected amount. 

### Example Data
Left side of the graph depicts the behavior when acknowledgments are enabled, right side shows it when acknowledgments are disabled. 

<img width="1431" alt="kafka_offset_reset" src="https://user-images.githubusercontent.com/31449262/137178269-62ee861f-958d-4ba6-bf17-ad6857c53e7b.png">
On the screenshot above you can see the consumer group lag, whose delta should in reality be either 0 (no one is consuming) or <0 when there are consumers. Note that various spikes in delta changes that are <0 are when i was adding and removing vector instances to reproduce the issue.

The following screenshot shows the actual current offset and the drop on one of the partitions(blue), yellow partition is there solely to showcase the expected behavior.
<img width="1438" alt="kafka_offset_drop" src="https://user-images.githubusercontent.com/31449262/137183015-cffc3a6b-ac78-4473-b5a5-1ee5c7c22b24.png">

### Additional  Context
We’re running vector in the following setup kafka -> vector-set1 -> vector-set2 -> sink. Where vector-set1 uses same kafka consumer group and dynamically scales up or down in a stateful set in kubernetes. 
We’re seeing weird behavior when the number of vector instances in the set1 group gets changed and `acknowledgments` are on.  It seems like the offset for the topic/partition on those events randomly drops(or to put in another way consumer lag for the topic/partition spikes) and it does so for a value that’s way too high for it to be considered as a part of “stored offset just didn’t get committed for the interval specified”.
I am however unable to reproduce the same behavior when acknowledgments are off.
Leading me to believe that there might be something weird going on, within either the finalizer or the way that messages get passed into it.
https://github.com/vectordotdev/vector/blob/v0.17.0/src/sources/kafka.rs#L158-L160

### References

https://github.com/vectordotdev/vector/pull/7787
https://vector.dev/releases/0.15.0/
