### ISSUE TITLE
Enrichment table functions need to accept dynamic conditions

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#9595]
Currently the enrichment table functions can only accept a static condition:

```
get_enrichment_table_row("table", { "field": .blah })
```

Dynamic conditions aren't available:

```
condition = merge(.condition1, .condition2);
get_enrichment_table_row("table", condition)
```

The reason for this is because we need to know the fields up front in order to build up the indexes into the data.

However, it would be incredibly useful to allow dynamic conditions. The issue is how can Vector then know which fields to index?

One possible solution is to allow indexes to be specified in the config:

```toml
[enrichment_tables.file]
type = "file"
file.path = "../data.csv"
file.encoding.type = "csv"
[[enrichment_tables.file.index]]
  fields = ["id", "name"]
[[enrichment_tables.file.index]]
  fields = ["first_name", "surname"]
```

Searches made using static conditions would still be able to infer the fields to use, so this config would only be necessary for a dynamic condition search.

The function would raise an error at runtime if a search was made on a dynamic condition for which there is no index specified.
