### ISSUE TITLE
Vector sink to vector source between agent and aggregator timeouts

### ISSUE THREAD

**Issue by lstyles** [vectordotdev/vector#9601]
### Vector Version

```
1.16.1
```

### Vector Configuration File

agent:
```toml
[sources.http]
      type = "http"
      address = "0.0.0.0:8080"
      encoding = "json"

    [transforms.split]
    type = "remap"
    inputs = ["http"]
    source = """
      ., err = unnest(.events)
      if err != null {
        log(err, level: "error")
      } 
    """

    [transforms.map]
    type = "remap"
    inputs = ["split"]
    source = """
      .e = .events
      del(.events)

      .@timestamp = .e.Timestamp
      del(.e.Properties.Message)
      del(.e.Properties.Command)
    """

    [sinks.vector]      
      type = "vector"
      inputs = ["map"]
      address = "vector-aggregator:9000"
      version = "2"
      batch.max_bytes = 1024000

      [sinks.vector.buffer]
        type = "disk"
        when_full = "drop_newest"
        max_size = 2000000000  # 2 GB
```

aggregator:

```
[sources.vector]
      address = "0.0.0.0:9000"
      type = "vector"
      version = "2"

[sinks.elasticsearch]
      type = "elasticsearch"
      inputs = [ "vector" ]
      endpoint = "http://core-es.internal.domain.io:9200"
      index = "services-staging-%Y.%m.%d"
      mode = "normal"
      compression = "none"
      [sinks.elasticsearch.buffer]
        type = "disk"
        when_full = "block"
        max_size = 30000000000  # 30 GB
```

### Expected Behavior

I would expect vector to vector communication to be robust.

### Actual Behavior

When the agents receives a burst of events via http source, vector starts logging the following:
```
Oct 13 17:02:11.854  WARN sink{component_id=vector component_kind="sink" component_type=vector component_name=vector}:request{request_id=2466}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.
```

### Example Data

Data incoming to vector http source is coming from Serilog HTTP sink. The payload is JSON and contains top level events key that contains an array of events represented in JSON.

```json
{ "events": [
    {
        ...
    },
    {
        ...
    },
    ...
  ]
}
```
### Additional Context

We're running vector as a daemonset on kubernetes but we're not using it to read kubernetes logs. Instead we listen to events coming from microservices via http source.

We have very inconsistent load on our systems and we don't need the events to be processed immediately. Our CPU limits are set to 1 CPU core and 1.5 GB of RAM on each agent. When the above timeouts are logged, the CPU is maxed out which is probably the cause. I'd prefer to not give vector more resources and instead for it to take longer to process with what it has.

Is something along those lines possible?

There is no increased usage recorded on the aggregator during that time.
