### ISSUE TITLE
Inputs with wildcards that match nothing became illegal with 0.17

### ISSUE THREAD

**Issue by flyingflo** [vectordotdev/vector#9602]
### Vector Version

```
vector 0.17.0 (x86_64-unknown-linux-gnu 3d34cde 2021-10-08)
```

### Vector Configuration File

```yml
transforms:
  parse_mylog:
    type: remap
    inputs:
      - source1
      - sources_type_*
      - another_*
      - a_third_*
   [...]
```

### Expected Behavior

We use modular config files with sources for several applications, that are not present on all hosts.
We connect them to a common transform with a wildcard input list. 
With 0.16, this was ok, as long as there was at least one input.

### Actual Behavior
Since 0.17, any wildcard input that does not match anything fails the validation.
```
x Input "sources_type_*" for transform "parse_mylog" doesn't match any components.

```
This could be intended behaviour, but it comes by surprise and breaks configs.
