### ISSUE TITLE
Allow `aws_ec2_metadata` transform to be best effort

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9749]
A user reported that they'd prefer, if Vector cannot fetch the metadata, that events be able to flow through without enrichment. Currently Vector, if it cannot fetch the metadata initially, blocks indefinitely. This can happen when, for example, the "max hops" are set too low for the EC2 IMDSv2 token API.

This should be configurable behavior with a new configuration option like:

```toml
[transforms.my_transform_id]
type = "aws_ec2_metadata"
inputs = [ "my-source-or-transform-id" ]
fields = [ "instance-id" ]
refresh_interval_secs = 10
required = false
```

Where `required` defaults to `true` and has the current behavior. `false` would make the initial metadata refresh optimistic and not block Vector start-up.
