### ISSUE TITLE
Documentation: Loki sink appears to require `encoding` section

### ISSUE THREAD

**Issue by aroberts** [vectordotdev/vector#9754]
### Vector Version

```
vector 0.17.3 (x86_64-unknown-linux-gnu d72c6e7 2021-10-21)
```

### Vector Configuration File

```toml
[sinks.loki]
type = "loki"
inputs = [ "docker" ]
endpoint = "<snipped>"
auth.strategy = "basic"
auth.user = "<snipped>"
auth.password = "<snipped>"
```

### Expected Behavior

Vector starts with some default for `encoding` for the Loki sink.

### Actual Behavior

Vector does not start.

### Additional Context
Doc here listing encoding as optional: https://vector.dev/docs/reference/configuration/sinks/loki/#encoding

### References
#2776 seems to be the same issue. Possibly only the codec is required?
