### ISSUE TITLE
transforms pipeline stops processing events after couple seconds of run

### ISSUE THREAD

**Issue by oktal** [vectordotdev/vector#9786]
### Vector Version

```
vector 0.17.2 (x86_64-pc-windows-msvc debug=full)
```

### Vector Configuration File

```toml
#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs/
# ------------------------------------------------------------------------------

data_dir = "C:\\ProgramData\\vector"

[sources.raw_logs]
  type = "file"
  include = ["D:\\Logs\\*.log"]
  # Ignore files with a modification date older than 1 day
  ignore_older = 86400
  # Useful for testing.
  #start_at_beginning = true

  fingerprint.strategy = "checksum"
  fingerprint.bytes = 1024

  # In last version of vectors, fingerprinter will only read the first line to compute its checksum.
  # Make it ignore the first line since the File-Id starts on the second line.
  # See https://github.com/timberio/vector/blob/master/rfcs/2020-10-15-3480-file-source-rework.md#file-identity
  fingerprint.ignored_header_bytes = 90

[sources.internal_metrics]
  type = "internal_metrics"

[transforms.parse]
  type = "remap"
  inputs = ["raw_logs"]
  source = '''
    if .message != "" {
      fields = {}
      message_parts = split(.message, "~~") ?? []
      if length(message_parts) >= 1 {
        message_fields, err = parse_regex(message_parts[0], r'^(?P<log_timestamp>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]+Z)\s+([-|]\s+(?P<log_thread_id>[^-|]+)\s+[-|]\s+(?P<log_level>[^\s]+)\s+[-|]\s+(?P<log_name>.*?)\s+)?\|\|\s+(?P<log_text>.*)')
        if err == null {
          # Parse timestamp.
          ts = message_fields.log_timestamp
          ts = replace(ts, "Z", "+00:00")
          ts = replace(ts, " ", "T")

          ts, err = parse_timestamp(ts, format: "%Y-%m-%dT%H:%M:%S%.9f%:z")
          if err == null {
            fields.ts = to_string(ts)
            .timestamp = ts
          }

          # Uniform log levels.
          lvl = message_fields.log_level
          if lvl == "Fatal" {
            lvl = "FATAL"
          } else if lvl == "Critical" {
            lvl = "FATAL"
          } else if lvl == "Error" {
            lvl = "ERROR"
          } else if lvl == "Warning" {
            lvl = "ERROR"
          } else if lvl == "Notice" {
            lvl = "INFO"
          } else if lvl == "Information" {
            lvl = "INFO"
          } else if lvl == "Debug" {
            lvl = "DEBUG"
          } else if lvl == "Trace" {
            lvl = "TRACE"
          }

          fields.lvl = downcase(lvl)
          fields.logger = message_fields.log_name
          fields.msg = strip_whitespace(message_fields.log_text)
          fields.tid = message_fields.log_thread_id

          # Parse JSON structured data.
          if length(message_parts) == 2 {
            structured_data, err = parse_json(message_parts[1])
            if err == null {
              fields = merge!(fields, structured_data)
            }
          }

          .message = encode_logfmt!(fields, ["ts", "lvl", "logger", "tid", "msg"])
        }
      }
    }

    # Extract peer ID from file name.
    file_fields, err = parse_regex(.file, r'^.*?(?P<peer_id>Prefix.*?)(\-(?P<log_category>.*))?(\.[0-9]{8})?\.log$')
    if err == null {

      # Extract service name and instance id.
      peer_id_fields, err = parse_regex(file_fields.peer_id, r'(?P<service_name>Prefix\.(?P<service_short_name>.*))\.(?P<instance_id>.*)$')

      if err == null {
        .service.id = file_fields.peer_id
        .service.name = peer_id_fields.service_name
        .service.node.name = peer_id_fields.service_short_name
        .instance.id = peer_id_fields.instance_id
      }

      if file_fields.log_category != null {
        .event.module = file_fields.log_category
      }
    }

    # Trim fully qualified hostname.
    if exists(.host) {
      if ends_with(.host, ".host.com") ?? false {
       .host = replace(.host, ".host.com", "") ?? ""
      }
    }
  '''

# Send structured data to a short-term storage
[sinks.loki]
  inputs = ["parse"]
  type = "loki"
  endpoint = "https://logs-dev"
  out_of_order_action = "rewrite_timestamp"
  remove_label_fields = false
  remove_timestamp = true

  auth.user = ""
  auth.strategy = ""
  auth.password = ""

  healthcheck.enabled = false

  tls.ca_file = "C:\\Program Files\\vector\\config\\cert.cer"

  request.retry_attempts = 3

  encoding.codec = "text"

  buffer.type = "memory"
  buffer.when_full = "block"
  batch.max_bytes = 10490000
  batch.max_events = 100

  labels.agent = "vector"
  labels.dc = ""
  labels.host = "{{ host }}"
  labels.file = "{{ file }}"
  labels.peer_id = "{{ service.id }}"
  labels.scope = "{{ event.module }}"
  labels.service_name = "{{ service.name }}"

[sinks.metrics_influxdb]
  inputs = [ "internal_metrics" ]
  type = "influxdb_metrics"

  request.retry_attempts = 3

  endpoint = "https://influx-dev"
  namespace = "vector"
  database = ""
  healthcheck = true

  username = ""
  password = ""

  tags.dc = ""
  tags.host = ""
```

### Actual Behavior

After updating vector to top master version, we noticed that, somehow, after a couple seconds of run, the pipeline stops processing events (as if something was deadlock'ed).

I've been able to bisect between our current deployed version (`0.15.1`) and top `master` to find the culprit commit: 6396474a0915490dd0302d2ca0631f4fd2448c4a

Running from the previous revision works as expected, running from this revision breaks.
