### ISSUE TITLE
Develop a soak test for the Vrl Bytecode VM

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#9832]
Ref #9515 

It would be highly useful to have some accurate benchmarks for the work in #9829  so we can ascertain how much of a benefit moving Vrl to compile and run with a Bytecode VM.

A useful config to test with would be:

```toml
[sources.in]
type = "http"
address = "0.0.0.0:8080"
encoding = "text"

[transforms.remap]
type = "remap"
inputs = ["in"]
source = '''
.hostname = "vector"

if .status == "warning" {
  .thing = upcase(.hostname)
} else if .status == "notice" {
  .thung = downcase(.hostname)
} else {
  .nong = upcase(.hostname)
}

.matches = { "name": .message, "num": "2" }
.origin, .err = .hostname + "/" + .matches.name + "/" + .matches.num
'''

[sinks.blackhole]
type = "blackhole"
inputs = ["remap"]
```

SHA to test against: 9d6108db380e743554d2aee70342e7088dfdfe3e
