### ISSUE TITLE
Ensure `vector` sources/sink works with AWS ALBs

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9901]
We should setup a demo in https://github.com/timberio/vector-demos using an AWS ALB. If I remember right, last time we tried this, we ran into a gRPC protocol error that we haven't resolved yet.

**Comment by spencergilbert** [comment]
I _think_ it was something like https://stackoverflow.com/questions/60044046/how-to-setup-grpc-ingress-on-gke-w-nginx-ingress which I'm also running into while testing against `nginx-ingress`

**Comment by gbregar** [comment]
The error I'm getting on the agent vector instance while trying to send data to an aggregator which is behind AWS ALB is 
`"http2 error: connection error detected: frame with invalid size"`.
The only relevant result I got with this error message is: https://github.com/hyperium/hyper/issues/1574

**Comment by tesharp** [comment]
Was running into same problem with `nginx-ingress`. Trying to do TLS termination on ingress.

Like the post @spencergilbert linked to it has a problem with the initial "PRI * HTTP/2.0" package. Nginx just returns 400. Strangely enough nginx also says schema for this package is `http` and not `https`, even if tls is enables.

After lots of testing I did manage to get it to work based on the post linked by @gbregar (thanks!)

Setting the connection to use only h2 protocol in `sinks\vector\v2\config.rs` -> new_client: 

```rust
https.set_callback(move |c, _uri| {
    if let Some(settings) = &settings {
        c.set_alpn_protos(b"\x02h2")?;
        settings.apply_connect_configuration(c);
    }

    Ok(())
});
```

it works! now, dont know if this is the right fix for this.. but at least fixed problem with nginx ingress

**Comment by jszwedko** [comment]
Interesting, thank you for that note @tesharp ! We'll test this and integrate it.

**Comment by mr-karan** [comment]
Is there any more progress on this? I'd really appreciate some help in using ALBs for Vector sources. Since I am using `version=2` (which is the `gRPC` version), I've set the `protocol_version` for target groups to be `gRPC`. However, I am unsure what should be the correct `healthcheck` config here:

Port 6000 is where vector source listens on. 

This is what I have and it's failing:

![image](https://user-images.githubusercontent.com/5689132/195084761-49a6728f-3d54-41b7-b690-8eba953e5f4d.png)

**Comment by gopiio** [comment]
>Healthcheck path is incorrect.  If you set the backend-protocol to `GRPC` then path should be `/grpc.health.v1.Health/Check`

**Comment by mr-karan** [comment]
@gopiio Thanks for the help! The following config worked for healthcheck.

![image](https://user-images.githubusercontent.com/5689132/195967177-83a368e0-ce8f-48dc-bc6a-341ae77b5cf0.png)

However, I am still unable to connect it for vector sink. Anything that I am missing here?

![image](https://user-images.githubusercontent.com/5689132/195970817-549cccc4-84d2-46ce-9eef-5b9f63677b2a.png)

```
[sinks.vector_out]
type = "vector"
inputs = ["tag_events"]
address = "alb-address:443"
version = "2"
```

```
$ curl -i https://alb-address:443
HTTP/2 464 
server: awselb/2.0
date: Sat, 15 Oct 2022 05:34:47 GMT
content-length: 0
```

**Comment by jszwedko** [comment]
Hi @gopiio !

I think you need to set: `tls.apln_protocols = "h2"` on the `vector` sink. Or, at least, one other user had success with that and AWS ALBs. Hopefully this works for you too! Assuming it does, we should add this mention to the documentation.

**Comment by dizlv** [comment]
@jszwedko just tried to glue two Vector topologies with `vector` sink and source in-between, and it failed.

1. Topolgy 1 -> AWS ALB -> Topology 2
2. AWS ALB has HTTPS listener, HTTP with gRPC in Target Group

Component has following configurations:

```
tls.apln_protocols = "h2"
tls.enabled = true
```

And it fails with 

```
{"timestamp":"2022-11-22T15:50:50.975966Z","level":"WARN","message":"Retrying after error.","error":"Request failed: status: Unknown, message: \"http2 error: connection error detected: frame with invalid size\", details: [], metadata: MetadataMap { headers: {} }","internal_log_rate_limit":true,"target":"vector::sinks::util::retries","span":{"component_id":"sink_name","component_kind":"sink","component_name":"sink_name","component_type":"vector","name":"sink"},"spans":[{"component_id":"sink_name","component_kind":"sink","component_name":"sink_name","component_type":"vector","name":"sink"}]}
```

Do you have any working examples or tips on make this working?

Thank you!

**Comment by jszwedko** [comment]
> @jszwedko just tried to glue two Vector topologies with `vector` sink and source in-between, and it failed.
> 
> 1. Topolgy 1 -> AWS ALB -> Topology 2
> 2. AWS ALB has HTTPS listener, HTTP with gRPC in Target Group
> 
> Component has following configurations:
> 
> ```
> tls.apln_protocols = "h2"
> tls.enabled = true
> ```
> 
> And it fails with
> 
> ```
> {"timestamp":"2022-11-22T15:50:50.975966Z","level":"WARN","message":"Retrying after error.","error":"Request failed: status: Unknown, message: \"http2 error: connection error detected: frame with invalid size\", details: [], metadata: MetadataMap { headers: {} }","internal_log_rate_limit":true,"target":"vector::sinks::util::retries","span":{"component_id":"sink_name","component_kind":"sink","component_name":"sink_name","component_type":"vector","name":"sink"},"spans":[{"component_id":"sink_name","component_kind":"sink","component_name":"sink_name","component_type":"vector","name":"sink"}]}
> ```
> 
> Do you have any working examples or tips on make this working?
> 
> Thank you!

Hmm, that's odd. Another user had reported it working for them with that configuration. Which version of Vector?

**Comment by dizlv** [comment]
Yes, it is configured on the sink, Vector 0.25.1

**Comment by jszwedko** [comment]
> @jszwedko just tried to glue two Vector topologies with `vector` sink and source in-between, and it failed.
> 
> 1. Topolgy 1 -> AWS ALB -> Topology 2
> 2. AWS ALB has HTTPS listener, HTTP with gRPC in Target Group
> 
> Component has following configurations:
> 
> ```
> tls.apln_protocols = "h2"
> tls.enabled = true
> ```
> 
> And it fails with
> 
> ```
> {"timestamp":"2022-11-22T15:50:50.975966Z","level":"WARN","message":"Retrying after error.","error":"Request failed: status: Unknown, message: \"http2 error: connection error detected: frame with invalid size\", details: [], metadata: MetadataMap { headers: {} }","internal_log_rate_limit":true,"target":"vector::sinks::util::retries","span":{"component_id":"sink_name","component_kind":"sink","component_name":"sink_name","component_type":"vector","name":"sink"},"spans":[{"component_id":"sink_name","component_kind":"sink","component_name":"sink_name","component_type":"vector","name":"sink"}]}
> ```
> 
> Do you have any working examples or tips on make this working?
> 
> Thank you!

Gotcha, I'm not sure why it isn't working for you then unfortunately. Someone will probably have to dig back into this issue. It is in our backlog.

**Comment by dizlv** [comment]
I got some more time to investigate this issue and actually found some rough edges, but successfully launched working setup at the end with AWS stack.

Working configurations file:

```
[sources.test]
type = "demo_logs"
format = "shuffle"
lines = ["hello, world"]
interval = 2

[sinks.vector]
type = "vector"
tls.enabled = true
tls.alpn_protocols = ["h2"]  # Note: should be a list, not string. And do not type in the field name, Vector won't notice it, instead just runs with default value (which is None).
inputs = ["test"]
address = "https://fqdn:443"  # Note: do not forget https! It is important. Otherwise the code does some magic stuff and provision default values.
```

And source:
```
[sources.vector]
type = "vector"
address = "0.0.0.0:9000"
version = "2"
```

1. Create `Application Load Balancer` with `HTTPS` listener (do not forget to attach proper certificate)
2. Create `Target Group` with `HTTP` protocol (since TLS is offloaded on the ALB) & configured port (`9000` in my example). `Protocol version` should be `gRPC` and health-check path `/grpc.health.v1.Health/Check`.

Why it did not work before:

> I think you need to set: `tls.apln_protocols = "h2"` on the vector sink
1. Proper field name is `alpn_protocols`, not `apln_protocols`
2. Proper value is a list, containing `"h2"`
3. Apparently code does some magic hand waving and applies http for protocol, if it is not specified in `address` field

I think that in general there are 2 issues:

1. Vector does not comply about wrong configuration values (at least for this TLS options)
2. `"h2"` as a `str` passes for the value in the `Vec` field

I'm not sure if the third one – some non-intuitive default values logic – is a design problem or lack of documentation or is a problem at all.

**Comment by tim-klarna** [comment]
So vector doesn't fail with typos in configuration keys? (`apln_protocols` vs `alpn_protocols`).
And also accepts garbage values and invalid types in configuration too.

I can see now why I couldn't get this working when I tried 😅

**Comment by tim-klarna** [comment]
Oh, and for security reasons, probably better to default to `https` and not `http`!

**Comment by hong823** [comment]
We also faced issues with getting ALB working with vector, after some trial and error we got it working with our ALB + EKS using [AWS ALB Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller). In the version of the vector we're using, the health check endpoint seems to be `/vector.Vector/HealthCheck`.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: <CERT ARN>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol-version: "GRPC"
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"

    alb.ingress.kubernetes.io/healthcheck-path: /vector.Vector/HealthCheck
    alb.ingress.kubernetes.io/healthcheck-port: "9000"
    alb.ingress.kubernetes.io/success-codes: "0"
  name: ingress-test
spec:
  ingressClassName: alb
  rules:
    - host: vector-intake.example.com
      http:
        paths:
          - backend:
              service:
                name: vector
                port:
                  name: 9000
            pathType: ImplementationSpecific

```

Vector config:
```
sinks:
  vector:
    type: vector
    address: https://vector-intake.example.com
    version: "2"
    tls:
      enabled: true
      alpn_protocols: ["h2"]

sources:
  vector_in:
    type: vector
    address: 0.0.0.0:9000
    version: "2"
```

We used [grpcurl](https://github.com/fullstorydev/grpcurl) to test the health check endpoint which requires to download a few `*.proto` file from vector's repository:
```
grpcurl -v -plaintext -proto vector.proto -d '{}' vector-intake.example.com:443 vector.Vector/HealthCheck
```

We tried to get it working with nginx ingress controller but kept getting `464` HTTP error. Hope this is helpful for anyone.

**Comment by JohnLBevan** [comment]
Has anyone got this working when using `mTLS` configured on the Vector Aggregator in EKS behind an ALB?  We had the issues reported on this thread when trying this and have temporarily worked around it by using an NLB to pass the traffic through as TCP; though that means managing certificate renewals in our pods rather than relying on ALB & AWS Cert Manager to manage our server authentication certs.  

(The ALB doesn't care if the backend server auth certificate is invalid; so we could configure a self-signed long life cert there to enable TLS, in order to be able to have the client authentication piece handled by the backend).

Newer versions of ALB support mTLS locally - so that may be something else we can look into; though we've yet to delve there...

**Comment by satellite-no** [comment]
Is there any updates on this? 

I have this working but its throughput is terrible.  The sending nodes are like 20% CPU and the receiving nodes are like 33% CPU with a throughput of roughly 32Mb/second while the s3 direct writes throughput is around 100Mb/second. Sink disk buffer is backing up into the hundreds of GB.  

Seems like Im limited by something but Im not certain what. 

sink config:
```yaml
type: vector
inputs:
  - core_*
address: 'https://vectorcore.datalake.com:6000'
compression: true
tls:
  enabled: true
  alpn_protocols: ["h2"]
batch:
  max_bytes: 3048576
request:
  adaptive_concurrency:
    initial_concurrency: 16
    max_concurrency_limit: 300
buffer:
  type: "disk"
  max_size: 989560464998
  when_full: "block"
```

Note: Im playing with `max_bytes` to try to increase throughput.
