### ISSUE TITLE
Support unix datagram sockets for the `statsd` sink

### ISSUE THREAD

**Issue by anupamdialpad** [vectordotdev/vector#9952]
### Vector Version

```
vector 0.17.3 (x86_64-unknown-linux-gnu d72c6e7 2021-10-21)
```

### Vector Configuration File

```toml
[sinks.datadog_metrics]
  type = "statsd"
  inputs = ["post_process_metric"]
  path = "/var/run/datadog/dsd.socket"
  mode = "unix"
  healthcheck.enabled = true
```

### Output

```json
{
    "error": "Connect error: Protocol wrong type for socket (os error 91)",
    "message": "Unable to connect.",
    "metadata": {
        "kind": "event",
        "level": "ERROR",
        "module_path": "vector::internal_events::unix",
        "target": "vector::internal_events::unix"
    },
    "path": "\"/var/run/datadog/dsd.socket\"",
    "timestamp": "2021-11-08T15:03:02.452638512Z"
}
```

### Expected Behavior

Successfully send metrics over unix socket.

### Additional Context

Vector container is running inside a Kubernetes pod. After transforming logs to metric we send it out to Datadog cloud through unix socket
