### ISSUE TITLE
`source_type_key` global override is ignored

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#9960]
Example config
```toml
log_schema.source_type_key = "xyz_source_type"
log_schema.timestamp_key = "xyz_timestamp"

[sources.generator]
type = "generator"
format = "shuffle"
interval = 1
lines = ["test"]

[sinks.out]
encoding.codec = "json"
inputs = ["generator"]
type = "console"
```

This produces an output of 
```
{"message":"test","source_type":"generator","xyz_timestamp":"2021-11-08T20:25:39.006348964Z"}
```

Notice the `timestamp` is mapped, and the `source_type` is not

This seems to impact all sources. I tested `http`, `stdin` and `generator`
