### ISSUE TITLE
Slow GCS sink on Vector-aggregator caused open file handles for deleted logs on Vector-clients

### ISSUE THREAD

**Issue by vpedosyuk** [vectordotdev/vector#9986]
### Vector Version

Vector clients:
```
0.17.3
```

Vector aggregator:
```
0.17.3
```

though the same was happening with the `0.15.1` version

### Vector Configuration File

Vector client
```toml
[sources.logs]
  type = "file"
  include = ["/var/log/*.log", "/var/log/*/*.log"]
  ignore_older_secs = 3600
  ignore_not_found = true
  max_read_bytes = 2048
  fingerprint.strategy = "device_and_inode"

[transforms.logs-setup]
  type = "remap"
  inputs = ["logs"]

  source = '''
  .<additional_tag_name> = "<additional_tag_value>"
  '''

[sinks.vector-logs]
  type = "vector"
  version = "2"
  inputs = ["logs-setup"]
  address = "<vector_aggregator_address>:9000"
  healthcheck = true

  buffer.max_events = 2000000
  buffer.type = "memory"
  buffer.when_full = "block"

  batch.max_events = 20000
  batch.timeout_secs = 1
```

Vector aggregator:
```toml
[sources.logs]
  type = "vector"
  version = "2"
  address = "0.0.0.0:9000"

[sinks.gcs]
  type = "gcp_cloud_storage"
  inputs = ["logs"]
  healthcheck = true

  bucket = "<gcs_bucket_name>"
  credentials_path = "/etc/gcs/credentials.json"

  batch.max_size = 50000000
  batch.timeout_secs = 60

  buffer.type = "memory"
  buffer.max_events = 100000
  buffer.when_full = "block"

  encoding.codec = "text"
  compression = "none"

  key_prefix = "{{ <additional_tag_name> }}/{{ host }}{{ file }}/%F/%H_xx/"

  filename_append_uuid = false
  filename_time_format = "%H:%M:%S"
```

### Expected Behavior

1. Throughput should increase with adding more CPU and RAM, Vector should handle the increased data rate.
2. Despite any possible issue in the Vector->Vector-aggregator pipeline, it should not damage production servers.

### Actual Behavior

1. Throughput doesn't increase with adding more CPU and RAM, Vector got stuck in the same conditions despite a pod restart and increased cpu/mem resources.
2. Issues in the Vector->Vector-aggregator pipeline causes "out of space" issues on production servers

### Context

We use Vector->Vector-aggregator scheme. Once the Vector-aggregator receives data from the Vector-clients, it sends logs onto a GCS bucket. There're 10 Vector clients (bare metal servers) and 1 Vector aggregator in Kubernetes.

There're 2 issues we faced:
1. Vector-aggregator can't scale vertically with the GCS sink. `vector_utilization` metric reports almost 100% utilization for the`gcp_cloud_storage` sink on Vector-aggregator and for the `vector` sink on Vector-clients, however, a very small amount of data (or no data) is actually get transmitted.
2. Vector-clients keep more and more file descriptors open even for already deleted logs, which leads to "out of space" problems on our servers. Though it seems to be a known issue.

#### Details
I tried to reproduce the issue and it turned out to be quite similar to what we've seen before.

I marked moments when I took an action:
<img src="https://user-images.githubusercontent.com/16594968/141139983-e9acf545-136b-459f-8ede-ea0de6231dcc.png" width="200">

Taken actions:

0. restart all 10 Vectors-clients, for some reason this triggered the issue, maybe due to a somewhat increased data rate after a Vector restart

1. increased pod's `limits` (`2 cpu`, `4Gi mem` ->  `3 cpu`, `5Gi mem`) of the Vector-aggregator and did a pod restart. Actually, even before this change, it wasn't using all the resources.

2. but Vector-aggregator still didn't want to handle all the data it was receiving, it wasn't using all the allocated resources:
```bash
$ kubectl top po vector-7c66c785bd-wm97r
NAME                      CPU(cores)   MEMORY(bytes)
vector-7c66c785bd-wm97r   1399m        2382Mi
```
and logs: [vector-7c66c785bd-wm97r.log](https://github.com/vectordotdev/vector/files/7514255/vector-7c66c785bd-wm97r.log)

3. scale Vector-aggregator out to 2 replicas. Horizontal scaling works better than vertical.

4. since Kubernetes alone cannot balance gRPC traffic, I restarted all 10 Vector-clients so that they init new connections
