### ISSUE TITLE
Limit pipeline nesting to one level

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9991]
The `pipeline` transform allows for nested `pipelines` transforms. This is necessary to support Datadog's nested Pipelines feature, but we only want to allow one level of nested pipelines. This is because:

1. The UI will only support a single level.
2. We want to limit complexity. The purpose of this transform is to facilitate collaboration by limiting complexity.

Instead, pipelines should support nested pipelines, but one level. Because we are already in the context of a specific pipeline, the type of the nested pipeline should be elided.

Example configuration:

```toml
[transforms.processing.logs.pipelines.services]
name = "Services"
filter.type = "datadog_search"
filter.condition = "service:*"

order = [
    "auth",
    "api"
]

[transforms.processing.logs.pipelines.services.pipelines.auth]
name = "Authentication Service"
filter.type = "datadog_search"
filter.condition = "service:auth"

[[transforms.processing.logs.pipelines.services.pipelines.auth.transforms]]
type = "remap"
source = '' #...

[transforms.processing.logs.pipelines.services.pipelines.api]
name = "API Service"
filter.type = "datadog_search"
filter.condition = "service:api"

[[transforms.processing.logs.pipelines.services.pipelines.api.transforms]]
type = "remap"
source = '' #...
```
